New resources - `azurerm_key_vault_managed_storage_account` and `azurerm_key_vault_managed_storage_account_sasdefinition`
hashicorp/terraform-provider-azurerm pull request #11579
Opened 2021-05-04 17:29 UTC by MattiasAng

Will fix #4659.

2021-06-17 18:07 UTC, katbyte requested changes
Thanks @MattiasAng - i've given this an initial review and left some comments inline to address

2021-06-17 18:07 UTC, katbyte commented on azurerm/internal/services/keyvault/key_vault_managed_storage_account.go
> +			return err
could we wrap this error?

2021-06-17 18:07 UTC, katbyte commented on azurerm/internal/services/keyvault/key_vault_managed_storage_account.go
> +				}
we can combine these lines? and wrap this error
```suggestion
				if _, err := client.SetStorageAccount(ctx, *keyVaultBaseUrl, name, parameters); err != nil {
					return err
				}
```

2021-06-17 18:07 UTC, katbyte commented on azurerm/internal/services/keyvault/key_vault_managed_storage_account_sasdefinition.go
> +			return err
same comments as above

2021-06-17 18:07 UTC, katbyte commented on azurerm/internal/services/keyvault/registration.go
> +		"azurerm_key_vault_managed_storage_account_sasdefinition": resourceKeyVaultManagedStorageAccountSasToken(),
this name seems incomplete, should we make it?
```suggestion
		"azurerm_key_vault_managed_storage_account_sas_token_definition": resourceKeyVaultManagedStorageAccountSasTokenDefinition(),
```

2021-08-17 15:18 UTC, katbyte commented
Hey @MattiasAng - as theres been no activity on this for a couple months now i'm going to close this PR - thanks for opening it and if you do come back to address the comments please do re open it!

2021-08-17 15:18 UTC, closed without merging

2021-09-06 14:59 UTC, tjololo commented
@katbyte @MattiasAng seems like we are close to a solution for #4659.
Any chance we can make this happen?

2021-09-08 12:18 UTC, aristosvo commented
@MattiasAng If you don't mind, I'll try to rebase and close this in another PR.

2021-09-08 12:28 UTC, MattiasAng commented
Thanks @aristosvo, too much at work to finish this one.