azurerm_virtual_hub_route_table - add support for default route table
hashicorp/terraform-provider-azurerm pull request #11646
Opened 2021-05-10 11:20 UTC by TomKimber

Add support for modifying the default route table in azurerm_virtual_hub_route_table resources.

(fixes #10039)

2021-05-17 17:02 UTC, TomKimber commented on azurerm/internal/services/network/virtual_hub_data_source.go
> +				Optional: true,
Should now be resolved.

2021-05-17 17:12 UTC, TomKimber commented on azurerm/internal/services/network/virtual_hub_resource.go
> +											"Service",
The SDK doesn't appear to have constants for destination_type currently - Please see: https://azuresdkdocs.blob.core.windows.net/$web/java/azure-resourcemanager-network/2.2.0/com/azure/resourcemanager/network/models/VirtualHubRouteV2.html#destinationType--

2021-05-17 17:21 UTC, TomKimber commented on azurerm/internal/services/network/virtual_hub_resource.go
> +							},
Validation function reference added.

2021-05-20 11:04 UTC, TomKimber commented
Fixed Terraform linting - All tests should now pass.

2021-06-01 09:48 UTC, TomKimber commented
Ran plugin-sdk-fixerupper.sh to fix merge conflict with master and resolved import issue.

2021-06-02 02:27 UTC, katbyte requested changes
Thanks @TomKimber - looks like we have some test failures:
```
------- Stdout: -------
=== RUN   TestAccVirtualHubConnection_recreateWithSameConnectionName
=== PAUSE TestAccVirtualHubConnection_recreateWithSameConnectionName
=== CONT  TestAccVirtualHubConnection_recreateWithSameConnectionName
    testing.go:620: Step 1/5 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # azurerm_virtual_hub.test will be updated in-place
          ~ resource "azurerm_virtual_hub" "test" {
                id                  = "/subscriptions/*******/resourceGroups/acctestRG-vhub-210601180507399446/providers/Microsoft.Network/virtualHubs/acctest-VHUB-210601180507399446"
                name                = "acctest-VHUB-210601180507399446"
                # (4 unchanged attributes hidden)
        
              - default_route_table {
                  - labels = [
                      - "default",
                    ] -> null
                }
            }
        
```

2021-06-22 14:13 UTC, TomKimber commented
@katbyte This test failure is due to the API requiring the creation of a default route table when the Virtual Hub is created meaning the labels value can't be null. I believe the correct handling of this would be to default the default route table labels set to a set containing "default" which would then create the default route table, would not effect existing users updating the provider who hadn't specified non-default labels and would still allow the removing of the default label if required (Passing an empty set).

It seems that it's not possible currently to default a set or list in the schema (https://github.com/hashicorp/terraform-plugin-sdk/issues/142). How would you advise approaching this?

2021-06-29 16:32 UTC, katbyte commented
@TomKimber - in the create function you can detect an empty set and sent that yourself, and if its computed the read should pick it up. but i'd definitly want some good tests to make sure it works

2021-07-09 16:57 UTC, katbyte requested changes
Thanks @TomKimber - running the tests for this we have a bunch of failures:
```
------- Stdout: -------
=== RUN   TestAccVirtualHubConnection_requiresImport
=== PAUSE TestAccVirtualHubConnection_requiresImport
=== CONT  TestAccVirtualHubConnection_requiresImport
    testcase.go:89: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # azurerm_virtual_hub.test will be updated in-place
          ~ resource "azurerm_virtual_hub" "test" {
                id                  = "/subscriptions/*******/resourceGroups/acctestRG-vhub-210709000609670360/providers/Microsoft.Network/virtualHubs/acctest-VHUB-210709000609670360"
                name                = "acctest-VHUB-210709000609670360"
                # (4 unchanged attributes hidden)
        
              - default_route_table {
                  - labels = [
                      - "default",
                    ] -> null
                }
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccVirtualHubConnection_requiresImport (2393.29s)
FAIL

```

2021-08-16 00:23 UTC, manicminer commented
@TomKimber I have rebased your changes and I have some fixes as per katbyte's suggestions - are you able to [allow edits from maintainers](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so I can push these and get them tested? Thanks!

2021-08-16 00:59 UTC, manicminer reviewed
@TomKimber Additionally, in your `defaultRouteTable` test config there is a circular reference between `azurerm_virtual_hub_connection.test` and `azurerm_virtual_hub.test`. This may require implementation as a separate resource to resolve.

2021-08-16 07:33 UTC, timja commented
> @TomKimber I have rebased your changes and I have some fixes as per katbyte's suggestions - are you able to [allow edits from maintainers](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so I can push these and get them tested? Thanks!

unfortunately this was submitted from our organisational fork rather than a personal fork.
Organisation forks don't provide that option 😢 

You can send a PR to https://github.com/hmcts/terraform-provider-azurerm/tree/10039-virtual-hub-default-route-table or we can re-submit from someones fork

2021-08-23 03:04 UTC, manicminer commented
@timja (cc @TomKimber) Thanks, I'd prefer to close this and open a new PR. Unfortunately however as I mentioned above, in the current state this is unimplementable. This will likely need to be redone as a separate resource, as there is a circular dependency  between `azurerm_virtual_hub` and `azurerm_virtual_hub_connection`:

```hcl
resource "azurerm_virtual_hub" "test" {
  # ...
  default_route_table {
    labels = ["default"]
    route {
      name              = "acctestdefaultroute"
      destinations_type = "CIDR"
      destinations      = ["10.0.2.128/25"]
      next_hop_type     = "ResourceId"
      next_hop          = azurerm_virtual_hub_connection.test.id
    }
  }
}

resource "azurerm_virtual_hub_connection" "test" {
  name                      = "acctestvhubconn"
  virtual_hub_id            = azurerm_virtual_hub.test.id
  remote_virtual_network_id = azurerm_virtual_network.test.id
}
```

2021-09-07 19:04 UTC, closed without merging