`kubernetes_cluster`: Support for BYO `kubelet_identity`
hashicorp/terraform-provider-azurerm pull request #12037
Opened 2021-06-02 12:29 UTC by aristosvo

Fixes #11980. Feature in Preview.

## Register before testing:
```bash
az feature register --namespace Microsoft.ContainerService -n CustomKubeletIdentityPreview
# wait until registered:
watch az feature list -o table --query "\"[?contains(name, 'Microsoft.ContainerService/CustomKubeletIdentityPreview')].{Name:name,State:properties.state}\""
az provider register --namespace Microsoft.ContainerService
```

## Acceptance Tests run:
- `TestAccKubernetesCluster_userAssignedKubeletIdentity` (with BYO Kubelet Identity)
- `TestAccKubernetesCluster_userAssignedIdentity` (without BYO Kubelet Identity)
```
❯ make acctests SERVICE='containers' TESTARGS='-run=TestAccKubernetesCluster_userAssigned'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/containers -run=TestAccKubernetesCluster_userAssigned -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
2021/06/02 13:43:06 [DEBUG] not using binary driver name, it's no longer needed
2021/06/02 13:43:08 [DEBUG] not using binary driver name, it's no longer needed
=== RUN   TestAccKubernetesCluster_userAssignedIdentity
=== PAUSE TestAccKubernetesCluster_userAssignedIdentity
=== RUN   TestAccKubernetesCluster_userAssignedKubeletIdentity
=== PAUSE TestAccKubernetesCluster_userAssignedKubeletIdentity
=== CONT  TestAccKubernetesCluster_userAssignedIdentity
=== CONT  TestAccKubernetesCluster_userAssignedKubeletIdentity
--- PASS: TestAccKubernetesCluster_userAssignedIdentity (615.75s)
--- PASS: TestAccKubernetesCluster_userAssignedKubeletIdentity (710.19s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers    714.228s
```

## ToDo:
- [ ] Docs

2021-06-07 17:42 UTC, mbfrahry requested changes
This is looking good but I do have a doc question to make things a little more clear

2021-06-07 18:56 UTC, aristosvo commented on website/docs/r/kubernetes_cluster.html.markdown
> +* `client_id` - (Optional) The Client ID of the user-defined Managed Identity to be assigned to the Kubelets. If not specified a Managed Identity is created automatically. Requires `kubelet_identity.
Sounds like a plan! I moved the requirement on `identity.0.user_assigned_identity_id` to the generic note below.

Thanks!

2021-06-07 19:31 UTC, mbfrahry approved these changes
LGTM! Thanks @aristosvo!

2021-06-07 19:31 UTC, merged

2021-06-11 11:17 UTC, dwrusse commented
Is there any way to enable the kubeletpreview provider via terraform?  I was hoping to embed this into a module that will be used on several different accounts.

2021-06-11 12:11 UTC, aristosvo commented
@dwrusse Would https://www.terraform.io/docs/language/resources/provisioners/local-exec.html maybe work for you combined with `az cli`?

2021-06-11 12:30 UTC, dwrusse commented
Potentially, yes.  I was hoping for a more "native" terraform method, but I agree with you that there likely isn't.  Thanks!