Add `allow_shared_key_access` to `azurerm_storage_account`
hashicorp/terraform-provider-azurerm pull request #12276
Opened 2021-06-18 13:43 UTC by JohannWeging

This PR adds the `allow_shared_key_access` attribute to the `azurerm_storage_account` resource and fixes #11460.
I took the documentation from https://docs.microsoft.com/en-us/rest/api/storagerp/storage-accounts/get-properties.

When i ran the the unit test suite it errored and mentioned to move the id management over to terraform. So I did that.

Two questions regarding the id management. 
In line 1024 I dropped the ID check because the account is no longer required. Should this check be readded in another way?
And second: In line 1501 and 1758 I dropped the id parsing and now the name and resource group from the schema is used. Is this the right way?

2021-06-21 01:57 UTC, yupwei68 commented
Hi @JohannWeging , thanks for opening this PR.
On fact, I open the issue to track that we could not implement `AllowSharedKeyAccess` currently.
Because currently we use `SharedKey` to authenticate data plane. We could not disable `SharedKey` in storage account. If you run the test and disable the `SharedKey`, it will return error in reading queue properties in storage account. Because we use data plane to read the queue properties. And it'll limit all the resources using data plane, like container and share.

2021-06-22 11:07 UTC, JohannWeging commented
@yupwei68 thanks for the information, I see. Should I remove the "fixes" from the top comment?
My use case for this feature is to create the initial terraform state setup. I create a blob only storage account for terraform  states with shared key access disabled. The terraform state for this setup is than committed to git.

2021-07-19 23:26 UTC, katbyte requested changes

2021-07-19 23:26 UTC, katbyte commented on azurerm/internal/services/storage/storage_account_resource.go
> +			"allow_shared_key_access": {
lets be consistent with other booleans
```suggestion
			"shared_key_access_enabled": {
```

2021-07-27 07:43 UTC, kevinharing commented
Any update on this feature?

2021-07-27 08:51 UTC, tombuildsstuff requested changes
hi @JohannWeging

Thanks for pushing those changes.

To answer your questions above:

> In line 1024 I dropped the ID check because the account is no longer required. Should this check be readded in another way?
> And second: In line 1501 and 1758 I dropped the id parsing and now the name and resource group from the schema is used. Is this the right way?

In short: Terraform needs to set the ID in the Create and then parse that ID in the Update/Read/Delete functions - as such rather than pulling this from the config (via `d.Get`) we'll need to revert this, I've left a comment inline showing what's needed here.

> When i ran the the unit test suite it errored and mentioned to move the id management over to terraform. So I did that.

Taking a look through my guess is this is because the `parse.ServiceID` method that's being used comes from the Database Migration package (and as such is expecting a Database Migration Resource ID) rather than from the Storage package (and expecting a Storage Account ID) - as such updating the ID Parsing function here should fix this - I've left comments inline which should fix this 👍

If we can fix the comments that I've left inline then this should otherwise be good to go however 👍

Thanks!

2021-07-27 08:51 UTC, tombuildsstuff commented on website/docs/r/storage_account.html.markdown
> +* `allow_blob_public_access` - Indicates whether the storage account permits requests to be authorized with the account access key via Shared Key. If false, then all requests, including shared access
Two things here, first the name of this needs updating and we also need to add an info box:

```suggestion
* `allow_shared_key_access` - Indicates whether the storage account permits requests to be authorized with the account access key via Shared Key. If false, then all requests, including shared access signatures, must be authorized with Azure Active Directory (Azure AD). The default value is `true`.

~> **Note:** Terraform uses Shared Key Authorisation to provision Storage Containers, Blobs and other items - when Shared Key Access is disabled, you will need to enable [the `storage_use_azuread` flag in the Provider block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#storage_use_azuread) to use Azure AD for authentication, however not all Azure Storage services support Active Directory authentication.
```

2021-07-27 08:51 UTC, tombuildsstuff commented on azurerm/internal/services/storage/storage_account_resource.go
> +	d.Set("resource_group_name", resourceGroupName)
We'll also need to set the value of `allow_shared_key_access` into the state to be able to track it.

Given the API has a default value (true) but can return `null` when this value isn't explicitly configured, we'll need to default this within Terraform using:

```suggestion
	allowSharedKeyAccess := true
	if props.AllowSharedKeyAccess != nil {
		allowSharedKeyAccess = *props.AllowSharedKeyAccess
	}
	d.Set("allow_shared_key_access", allowSharedKeyAccess)
```

(within the `if props := response.AccountProperties; props != nil` statement below)

2021-07-29 18:19 UTC, katbyte requested changes
all tests are failing with:
```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccStorageAccount_tagCount
=== PAUSE TestAccStorageAccount_tagCount
=== CONT  TestAccStorageAccount_tagCount

------- Stderr: -------
panic: interface conversion: interface {} is nil, not bool

goroutine 415 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/storage.resourceStorageAccountCreate(0xc002178a80, 0x5844f00, 0xc001a3b880, 0x0, 0x0)
	/opt/teamcity-agent/work/a73be106926a7472/azurerm/internal/services/storage/storage_account_resource.go:925 +0x4385
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000bbc8c0, 0x68378a8, 0xc0024ffb00, 0xc002178a80, 0x5844f00, 0xc001a3b880, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000bbc8c0, 0x68378a8, 0xc0024ffb00, 0xc000eb6150, 0xc0024cf940, 0x5844f00, 0xc001a3b880, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00227e018, 0x68378a8, 0xc0024ffb00, 0xc0041061e0, 0xc0024ffb00, 0x5d32840, 0xc00216ca00)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0000646a0, 0x6837950, 0xc0024ffb00, 0xc000eb6000, 0xc0000646a0, 0xc00216ca50, 0xc002b69ba0)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x5d32840, 0xc0000646a0, 0x6837950, 0xc00216ca50, 0xc002d8af00, 0x0, 0x6837950, 0xc00216ca50, 0xc000ef8000, 0xdee)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001c5a380, 0x6883178, 0xc003645980, 0xc002ba78c0, 0xc00183c540, 0x9e1e8e0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc001c5a380, 0x6883178, 0xc003645980, 0xc002ba78c0, 0x0)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000fc4d0, 0xc001c5a380, 0x6883178, 0xc003645980, 0xc002ba78c0)
	/opt/teamcity-agent/work/a73be106926a7472/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/a73be106926a7472/vendor/google.golang.org/grpc/server.go:938 +0x1fd
```

2021-08-16 14:58 UTC, catriona-m commented
Hi @JohannWeging I've taken this and reopened as #13014 - due to the recent move and the amount of changes to the repo I wasn't able to push to this ☹️  , so closing this so the functionality can hopefully be merged this week. Thanks for doing the ground work on this!

2021-08-16 14:58 UTC, closed without merging