11347 supporting azurerm subscription tags
hashicorp/terraform-provider-azurerm pull request #12287
Opened 2021-06-19 19:40 UTC by crkg

Supporting azurerm subscription tags

2021-06-24 10:04 UTC, crkg commented
@jackofallops , can you please approve the workflow. we will close this topic.

2021-06-30 12:15 UTC, jackofallops requested changes
Hi @crkg - Thanks for this PR, it's off to a good start. I've left some comments and changes in line below. If you can address those, I'll re-review asap. 
Thanks!

2021-06-30 12:15 UTC, jackofallops commented on azurerm/internal/services/subscription/subscription_resource.go
> +
We shouldn't need to do anything with the tags here, as we will be disabling the subscription.
```suggestion
```

2021-06-30 12:15 UTC, jackofallops commented on azurerm/internal/services/subscription/subscription_resource.go
> +	return resourceSubscriptionRead(d, meta)
We only ever return nil at the end of a delete, returning read here will result in Terraform presenting an erroneous not-found error to the user on success.
```suggestion
	return nil
```

2021-06-30 12:15 UTC, jackofallops commented on azurerm/internal/services/subscription/subscription_resource_test.go
> +				assert.Key("tags.environment").HasValue("Production"),
Can we keep these in long-hand form as with the rest of the test suite?

2021-06-30 12:15 UTC, jackofallops commented on azurerm/internal/services/subscription/subscription_resource_test.go
> +	fmt.Println(tagsResp.Properties)
This shouldn't be necessary. The exists and implicit read/import functionality will check the values for the tags.  The `Exists` function itself is simply to check the resource is present, not for any particular setting / configuration
```suggestion
```

2021-06-30 12:15 UTC, jackofallops commented on azurerm/internal/services/subscription/subscription_resource_test.go
> +  }
This is not supported here and will create a test config error when run
```suggestion
```

2021-06-30 12:41 UTC, crkg commented
Thanks Steve, i will work on the recommendation and push the changes.

2021-07-06 09:15 UTC, crkg commented
> Hi @crkg - Thanks for this PR, it's off to a good start. I've left some comments and changes in line below. If you can address those, I'll re-review asap.
> Thanks!

Hi Steve, 

PR is ready to be merged with no conflicts. please take a moment to review and merge. 

Thank you.

2021-07-14 07:26 UTC, jackofallops requested changes
Hi @crkg - Thanks for the updates, I've left a couple more comments inline below. If you can address those I'll make time to test this as the Subscription resource isn't compatible with our CI test runner currently, so needs running by hand.

Thanks!

2021-07-14 07:26 UTC, jackofallops commented on azurerm/internal/services/subscription/subscription_resource.go
> +		d.Set("tags", *updateTags.ID)
We can remove this, it should be handled by the `Read`.
```suggestion
```

2021-07-14 07:26 UTC, jackofallops commented on azurerm/internal/services/subscription/subscription_resource_test.go
> +				assert.Key("tags.environment").HasValue("Production"),
Looks like this one was missed from the last review? Can we get these in the form:
```suggestion
				check.That(data.ResourceName).ExistsInAzure(r),
				check.That(data.ResourceName).Key("tags.%").HasValue("2"),
				check.That(data.ResourceName).Key("tags.cost_center").HasValue("MSFT"),
				check.That(data.ResourceName).Key("tags.environment").HasValue("Production"),
```
The consistency helps us make bulk changes if/when we update approaches to the test framework.

2021-07-22 12:29 UTC, gro1m commented
Hey @crkg it looks like you missed a review for your test file. I saw this when looking at the file view: https://github.com/terraform-providers/terraform-provider-azurerm/pull/12287/files and for some reason the Terraform Schema Linting seems to have failed - just in case you did not notice.

2021-07-23 07:23 UTC, jackofallops commented
Hi @crkg - There's still an outstanding change requested from the previous review, specifically updating the test cases where `assert := check.That(data.ResourceName)` is used to being the long-hand version.  If you can update those, I'll re-review and get the tests run. 👍 
Thanks!

2021-07-23 10:38 UTC, crkg commented
> Hi @crkg - There's still an outstanding change requested from the previous review, specifically updating the test cases where `assert := check.That(data.ResourceName)` is used to being the long-hand version. If you can update those, I'll re-review and get the tests run. 👍
> Thanks!

Hi Steve, sorry i missed to commit those changes in previous commit. thank you for the suggestions.

2021-08-03 10:59 UTC, crkg commented
> > Hi @crkg - There's still an outstanding change requested from the previous review, specifically updating the test cases where `assert := check.That(data.ResourceName)` is used to being the long-hand version. If you can update those, I'll re-review and get the tests run. 👍
> > Thanks!
> 
> Hi Steve, sorry i missed to commit those changes in previous commit. thank you for the suggestions. its fixed please approve the workflow.

@jackofallops ( Steve) can you please review and approve the changes.

2021-08-03 14:56 UTC, jackofallops commented
Hi @crkg - We have an issue testing subscription creation/update currently, so I'm afraid this is blocked until that support ticket is resolved. I'll loop back to this just as soon as we're able to test.

2021-08-12 17:16 UTC, crkg commented
> Hi @crkg - We have an issue testing subscription creation/update currently, so I'm afraid this is blocked until that support ticket is resolved. I'll loop back to this just as soon as we're able to test.

Hi Steve, thank you. let me know when we are good to loop back this PR.

2021-09-12 17:09 UTC, crkg commented
> > Hi @crkg - We have an issue testing subscription creation/update currently, so I'm afraid this is blocked until that support ticket is resolved. I'll loop back to this just as soon as we're able to test.
> 
> Hi Steve, thank you. let me know when we are good to loop back this PR.

Hi Steve, may i know if this feature can be plugged back, I was waiting for a confirmation on a blocked support ticket if its resolved?

2021-10-01 20:38 UTC, donwlewis commented
It would be great to see this get implemented soon.  Thanks!

2021-10-03 16:00 UTC, pinophyta commented
Looking forward to having this useful feature in the provider soon!

2021-10-21 22:53 UTC, katbyte commented
Hey all, sorry that this PR has been languishing here for so long. We're still working to unblock our ability to test - but progress has finally been made on that front so are now working towards getting this queued up. No timeframe to share yet but hopefully sooner than later!

2021-11-30 15:35 UTC, Eslam10 commented
Hello, 
Would someone please share the updates on this ? 
Thank you.

2021-12-02 16:49 UTC, jackofallops commented
Hi @crkg - we've been able to resolve the testing issues for this. A lot has changed in the provider structure since this was first opened, so I've had to take your work forward to another PR to add changes I found to be necessary. Thanks again for your work on this, and your continued patience in getting this through.  I'm going to close this PR out, please subscribe to #14445 for further updates.

2021-12-02 16:49 UTC, closed without merging

2021-12-03 15:27 UTC, crkg commented
> Hi @crkg - we've been able to resolve the testing issues for this. A lot has changed in the provider structure since this was first opened, so I've had to take your work forward to another PR to add changes I found to be necessary. Thanks again for your work on this, and your continued patience in getting this through. I'm going to close this PR out, please subscribe to #14445 for further updates.

Thank you for the feature, much appreciated.