Create Express Route  Circuits on Express Route Port
hashicorp/terraform-provider-azurerm pull request #12289
Opened 2021-06-21 04:57 UTC by xuzhang3

2021-06-21 06:02 UTC, magodo requested changes
@xuzhang3 Thank you for the PR! I've looked through and left some comments.

2021-06-21 06:02 UTC, magodo commented on website/docs/r/express_route_circuit.html.markdown
> +* `allow_classic_operations` - (Optional) Allow the circuit to interact with classic (RDFE) resources.
```suggestion
* `allow_classic_operations` - (Optional) Allow the circuit to interact with classic (RDFE) resources. Defaults to `false`.
```

2021-06-21 06:02 UTC, magodo commented on website/docs/r/express_route_circuit.html.markdown
> +~> **NOTE:** The `allow_classic_operations` cannot be set while using the Express Route Port.
Can we add this constraint back in the schema definition?

2021-06-21 06:02 UTC, magodo commented on website/docs/r/express_route_circuit.html.markdown
> +* `express_route_port_id` - (Optional) The ID of the Express Route Port which this circuit should be based on.
```suggestion
* `express_route_port_id` - (Optional) The ID of the Express Route Port which this Express Route Circuit is based on.
```

2021-06-22 03:25 UTC, magodo requested changes
Thanks for this PR!
I have left some additional mostly minor comments that once addressed this should be good to merge 👍

2021-06-22 03:25 UTC, magodo commented on azurerm/internal/services/network/express_route_circuit_resource.go
> +		portID, err := parse.ExpressRoutePortID(*resp.ExpressRoutePort.ID)
Can we nil check the `resp.ExpressRoutePort.ID` here?

2021-06-22 03:25 UTC, magodo commented on website/docs/r/express_route_circuit.html.markdown
> +* `peering_location` - (Optional) The name of the peering location and **not** the Azure resource location. Any change to the configuration will recreate the resource.
```suggestion
* `peering_location` - (Optional) The name of the peering location and **not** the Azure resource location. Changing this forces a new resource to be created.
```

2021-06-22 03:25 UTC, magodo commented on website/docs/r/express_route_circuit.html.markdown
> +* `service_provider_name` - (Optional) The name of the ExpressRoute Service Provider. Any change to the configuration will recreate the resource.
```suggestion
* `service_provider_name` - (Optional) The name of the ExpressRoute Service Provider. Changing this forces a new resource to be created.
```

2021-06-22 13:28 UTC, magodo commented
@xuzhang3 overall it LGTM! Despite, the test has one small error, which looks like wants to adding some sequential in the acctest. If we can fix that, it should be good to go!

![image](https://user-images.githubusercontent.com/7970698/122932965-c5b2f580-d3a0-11eb-805f-c26c1cbd4471.png)

2021-06-23 02:17 UTC, xuzhang3 commented
> @xuzhang3 overall it LGTM! Despite, the test has one small error, which looks like wants to adding some sequential in the acctest. If we can fix that, it should be good to go!
> 
> ![image](https://user-images.githubusercontent.com/7970698/122932965-c5b2f580-d3a0-11eb-805f-c26c1cbd4471.png)

Every subscription can create no more than 10 circuits by default. https://docs.microsoft.com/en-us/azure/expressroute/expressroute-faqs#can-i-have-more-than-one-expressroute-circuit-in-my-subscription

2021-06-23 03:01 UTC, magodo commented
@xuzhang3 So can we reflect that in the acctest?

2021-06-23 05:59 UTC, xuzhang3 commented
Fixed

> @xuzhang3 So can we reflect that in the acctest?

Fixed

2021-06-24 06:14 UTC, magodo commented
LGTM now, thank you!
![image](https://user-images.githubusercontent.com/7970698/123211738-6d8e0780-d4f6-11eb-8472-d865936c6095.png)

2021-06-24 06:18 UTC, katbyte approved these changes
LGTM 🍰

2021-06-24 06:19 UTC, merged