Vendor pandora sdk identity related types
hashicorp/terraform-provider-azurerm pull request #12725
Opened 2021-07-24 02:17 UTC by magodo

This PR defines 5 types of identity related types that exist in azure Swagger spec in the provider, together with the cast to and cast from method with the `ExpandedConfig`. This is to aid the Pandora SDK custom types for identity.

2021-07-27 16:03 UTC, tombuildsstuff requested changes
hey @magodo

Thanks for this PR - apologies for the delayed review here.

Taking a look through the changes to the identity package looks fine here, but would you mind rebasing this to include the changes from master so that this no longer conflicts?

Thanks!

2021-07-27 16:03 UTC, tombuildsstuff commented on azurerm/internal/identity/schema.go
> +	TenantId                string   `tfschema:"tenant_id"`
Whilst this is fine, some of the other service packages (shown below) are expecting `*string` and `*[]string` - so we'll need to update those - I believe this'll be fixed by a rebase?

2021-07-28 01:35 UTC, magodo commented
@tombuildsstuff Thank you for your review! I've resolved the comments, please take another look!

2021-08-11 09:29 UTC, tombuildsstuff approved these changes
LGTM - thanks for rebasing this / apologies for the delayed review here @magodo

2021-08-11 09:30 UTC, merged