New resource azurerm_app_service_slot_custom_hostname_binding
hashicorp/terraform-provider-azurerm pull request #12763
Opened 2021-07-28 07:47 UTC by haraldatbmw

This PR introduces a new resource azurerm_app_service_slot_custom_hostname_binding for adding custom hostname bindings for App Service Slots.

2021-07-28 07:48 UTC, haraldatbmw commented
Fix for issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/11295

2021-08-04 09:15 UTC, jackofallops requested changes
Hi @haraldatbmw - Thanks for the PR, it's off to a really good start. I've left some comments/changes below. If you can address those I'll continue review.

Thanks again!

2021-08-04 09:15 UTC, jackofallops commented on azurerm/internal/services/web/app_service_slot_custom_hostname_binding_resource.go
> +			log.Printf("[DEBUG] App Service Hostname Binding %q (App Service %q / Slot %q / Resource Group %q) was not found - removing from state", id.Name, id.AppServiceName, id.AppServiceSlot, id.ResourceG
As above:
```suggestion
			log.Printf("[DEBUG] %s was not found - removing from state", id)
```

2021-08-04 09:15 UTC, jackofallops commented on azurerm/internal/services/web/app_service_slot_custom_hostname_binding_resource.go
> +		return fmt.Errorf("Error retrieving Custom Hostname Binding %q (App Service %q / Slot %q / Resource Group %q): %+v", id.Name, id.AppServiceName, id.AppServiceSlot, id.ResourceGroup, err)
as above:
```suggestion
		return fmt.Errorf("retrieving %s: %+v", *id, err)
```

2021-08-04 09:15 UTC, jackofallops commented on azurerm/internal/services/web/app_service_slot_custom_hostname_binding_resource.go
> +		d.Set("ssl_state", props.SslState)
This may need casting to a string?
```suggestion
		d.Set("ssl_state", string(props.SslState))
```

2021-08-04 09:15 UTC, jackofallops commented on azurerm/internal/services/web/app_service_slot_custom_hostname_binding_resource.go
> +			return fmt.Errorf("Error deleting Custom Hostname Binding %q (App Service %q / Slot %q / Resource Group %q): %+v", id.Name, id.AppServiceName, id.AppServiceSlot, id.ResourceGroup, err)
as above for error message:
```suggestion
			return fmt.Errorf("deleting %s: %+v", *id, err)
```

2021-08-04 12:08 UTC, haraldatbmw commented on azurerm/internal/services/web/app_service_slot_custom_hostname_binding_resource.go
> +	ctx, cancel := timeouts.ForCreate(meta.(*clients.Client).StopContext, d)
I used the subscriptionId out of the slotId (`slotId.SubscriptionId`)

2021-08-04 12:09 UTC, haraldatbmw commented on azurerm/internal/services/web/app_service_slot_custom_hostname_binding_resource.go
> +			},
Is implemented.

2021-08-04 12:09 UTC, haraldatbmw commented on azurerm/internal/services/web/app_service_slot_custom_hostname_binding_resource.go
> +	appServiceSlot := d.Get("app_service_slot").(string)
Is implemented.

2021-08-04 12:10 UTC, haraldatbmw commented on azurerm/internal/services/web/parse/app_service_slot_custom_hostname_binding.go
> +package parse
Is implemented.

2021-08-04 12:10 UTC, haraldatbmw commented on azurerm/internal/services/web/app_service_slot_custom_hostname_binding_resource.go
> +		existing, err := client.GetHostNameBindingSlot(ctx, resourceGroup, appServiceName, appServiceSlot, hostname)
Is implemented.

2021-08-04 12:17 UTC, haraldatbmw commented on azurerm/internal/services/web/app_service_slot_custom_hostname_binding_resource.go
> +	}
Is implemented.

2021-08-04 12:17 UTC, haraldatbmw commented on azurerm/internal/services/web/app_service_slot_custom_hostname_binding_resource.go
> +	if _, err := client.CreateOrUpdateHostNameBindingSlot(ctx, resourceGroup, appServiceName, hostname, properties, appServiceSlot); err != nil {
Is implemented.

2021-08-04 12:26 UTC, haraldatbmw commented on azurerm/internal/services/web/app_service_slot_custom_hostname_binding_resource.go
> +	d.SetId(*read.ID)
Is implemented.

2021-08-10 06:42 UTC, jackofallops commented
Hi @haraldatbmw - The repo move and structure update detailed [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/12867) has meant we have some conflicts. If you can rebase to resolve those, I'll get straight back onto review.

Thanks!

2021-08-23 12:25 UTC, haraldatbmw commented
Closing this PR in favor of https://github.com/hashicorp/terraform-provider-azurerm/pull/13097

2021-08-23 12:25 UTC, closed without merging