Support for `azurerm_api_management_notification_recipient_email`
hashicorp/terraform-provider-azurerm pull request #12849
Opened 2021-08-05 01:45 UTC by yupwei68

Partial Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/12848

--- PASS: TestAccApiManagementNotificationRecipientEmail_basic (4169.09s)

2021-08-12 22:40 UTC, katbyte requested changes
Thanks @yupwei68 - just one comment

2021-08-12 22:40 UTC, katbyte commented on azurerm/internal/services/apimanagement/api_management_notification_recipient_email.go
> +		"notification_name": {
should this be
```suggestion
		"notification_type": {
```

2021-08-13 08:40 UTC, yupwei68 commented
@kt Tests have passed. Please continue reviewing.

2021-08-17 03:15 UTC, katbyte approved these changes
Thanks @yupwei68 - LGTM 🏗️

2021-08-17 03:15 UTC, merged