Support for `PurgeSoftDeleteOnDestroy` in `azurerm_api_management`
hashicorp/terraform-provider-azurerm pull request #12850
Opened 2021-08-05 02:31 UTC by yupwei68

Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/11061

--- PASS: TestAccApiManagement_purgeSoftDelete (743.86s)

2021-08-18 02:33 UTC, yupwei68 commented
@katbyte I've updated to solve the conflicts. Please continue reviewing.

2021-09-07 19:55 UTC, katbyte requested changes
thanks @yupwei68 - could we update the docs with this new property?

2021-09-15 07:14 UTC, wasfree commented on website/docs/index.html.markdown
> +* `purge_soft_delete_on_destroy` - (Optional) Should the `azurerm_api_management` resources be permanently deleted (e.g. purged) when destroyed? Defaults to `false`.
We should also place a note in [azurerm_api_management](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management) resource referring to this feature flag.

2021-09-16 18:59 UTC, katbyte approved these changes
THANKS @yupwei68 - LGTM 🚀

2021-09-16 18:59 UTC, merged

2021-09-22 09:51 UTC, akhileshnirapure commented
The **feature** is missing any explicit action required?

https://github.com/hashicorp/cdktf-provider-azurerm/issues/448