Event grid topic system managed identity
hashicorp/terraform-provider-azurerm pull request #12951
Opened 2021-08-11 13:10 UTC by jrauschenbusch

Reopened PR for https://github.com/hashicorp/terraform-provider-azurerm/pull/9906

Issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/9525

@mbfrahry Please review

2021-09-03 08:38 UTC, stephybun requested changes
Thanks for reopening this PR and for fixing most of the comments left from #9906 @jrauschenbusch. The tests are passing, once the comments left on on the docs are fixed then this LGTM 👍🏼.

2021-09-03 08:38 UTC, stephybun commented on website/docs/r/eventgrid_topic.html.markdown
> +* `type` - Specifies the identity type of Event Grid Domain. Possible values are `SystemAssigned` (where Azure will generate a Principal for you) or `UserAssigned` where you can specify the User Assi
This should be 
```suggestion
* `type` - Specifies the identity type of Event Grid Topic. Possible values are `SystemAssigned` (where Azure will generate a Principal for you) or `UserAssigned` where you can specify the User Assigned Managed Identity IDs in the `identity_ids` field.
```

2021-09-03 08:38 UTC, stephybun commented on website/docs/r/eventgrid_topic.html.markdown
> +~> **NOTE:** When `type` is set to `SystemAssigned`, The assigned `principal_id` and `tenant_id` can be retrieved after the Event Grid Domain has been created. More details are available below.
Same here 
```suggestion
~> **NOTE:** When `type` is set to `SystemAssigned`, The assigned `principal_id` and `tenant_id` can be retrieved after the Event Grid Topic has been created. More details are available below.
```

2021-09-03 08:38 UTC, stephybun commented on website/docs/r/eventgrid_topic.html.markdown
> +* `identity` - An `identity` block as defined below, which contains the Managed Service Identity information for this Event Grid Domain.
Same here 
```suggestion
* `identity` - An `identity` block as defined below, which contains the Managed Service Identity information for this Event Grid Topic.
```

2021-09-03 08:38 UTC, stephybun commented on website/docs/r/eventgrid_topic.html.markdown
> +A `identity` block exports the following:
Going by the doc comments from #9906 this should be 
```suggestion
A `identity` block supports the following:
```

2021-09-03 08:38 UTC, stephybun commented on website/docs/r/eventgrid_topic.html.markdown
> +* `type` - Specifies the type of Managed Service Identity that is configured on this Event Grid Domain.
Same here
```suggestion
* `type` - Specifies the type of Managed Service Identity that is configured on this Event Grid Topic.
```

2021-09-03 08:38 UTC, stephybun commented on website/docs/r/eventgrid_topic.html.markdown
> +* `principal_id` - Specifies the Principal ID of the System Assigned Managed Service Identity that is configured on this Event Grid Domain.
```suggestion
* `principal_id` - Specifies the Principal ID of the System Assigned Managed Service Identity that is configured on this Event Grid Topic.
```

2021-09-03 08:38 UTC, stephybun commented on website/docs/r/eventgrid_topic.html.markdown
> +* `tenant_id` - Specifies the Tenant ID of the System Assigned Managed Service Identity that is configured on this Event Grid Domain.
```suggestion
* `tenant_id` - Specifies the Tenant ID of the System Assigned Managed Service Identity that is configured on this Event Grid Topic.
```

2021-09-03 11:31 UTC, jrauschenbusch commented
@stephybun Done

2021-09-03 18:23 UTC, katbyte approved these changes
Thanks both! LGTM 🚀

2021-09-03 18:30 UTC, katbyte commented
@jrauschenbusch - this is ready to go once the merge conflicts are resolved!

2021-09-03 20:04 UTC, jrauschenbusch commented
@katbyte Could you please fix it? I'm currently in vacation with mobile phone access only.

2021-09-06 07:33 UTC, javier-moreno-h commented
Thanks a lot for reopening this PR for fixing #9925. What about **azurerm_eventgrid_system_topic** ? Will it also support identities ? King Regards.

2021-09-06 08:12 UTC, stephybun submitted a review, later dismissed

2021-09-06 08:13 UTC, jrauschenbusch commented
@javier-moreno-h Until now this PR just comprised the identity support for `azurerm_eventgrid_domain` and `azurerm_eventgrid_topic`.  I've now added also support for `azurerm_eventgrid_system_topic`. I'll do a few tests and give an update here if the state is mergable. Basically it was the really same code changes as needed for the topic resource. Hence a further PR review should be just a comparison of those two resources.

2021-09-06 08:15 UTC, stephybun commented
@jrauschenbusch please re-request review when ready.

2021-09-06 08:24 UTC, javier-moreno-h commented
> @javier-moreno-h Until now this PR just comprised the identity support for `azurerm_eventgrid_domain` and `azurerm_eventgrid_topic`. I've now added also support for `azurerm_eventgrid_system_topic`. I'll do a few tests and give an update here if the state is mergable. Basically it was the really same code changes as needed for the topic resource. Hence a further PR review should be just a comparison of those two resources.

@jrauschenbusch thanks a lot. I really appreciate it. I will be watching this thread. Regards.

2021-09-06 09:14 UTC, jrauschenbusch commented
@stephybun PR  is now ready to be re-reviewed. I had to adjust the expand/flatten function names due to collisions with another PR which was merged before. Basically there is some misalignment of the identity implementation in the Azure SDK. Therefore we need multiple functions for this job within the event grid module. This was already addressed by @tombuildsstuff within the azure-rest-api-specs repository (see https://github.com/Azure/azure-rest-api-specs/issues/13340). Also i had to adjust a few parts of the system topic tests, due to source resource restrictions (allowed lengths of storage accounts).

Below you'll find the output of my acceptance test execution. I ran the whole event grid acceptance test collection.

<details>
<summary>Console Output</summary>

```
make acctests SERVICE='eventgrid' TESTARGS='-run=TestAccEventGrid' TESTTIMEOUT='60m' 
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/eventgrid -run=TestAccEventGrid -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccEventGridDomainDataSource_basic
=== PAUSE TestAccEventGridDomainDataSource_basic
=== RUN   TestAccEventGridDomain_basic
=== PAUSE TestAccEventGridDomain_basic
=== RUN   TestAccEventGridDomain_requiresImport
=== PAUSE TestAccEventGridDomain_requiresImport
=== RUN   TestAccEventGridDomain_mapping
=== PAUSE TestAccEventGridDomain_mapping
=== RUN   TestAccEventGridDomain_basicWithTags
=== PAUSE TestAccEventGridDomain_basicWithTags
=== RUN   TestAccEventGridDomain_inboundIPRules
=== PAUSE TestAccEventGridDomain_inboundIPRules
=== RUN   TestAccEventGridDomain_basicWithSystemManagedIdentity
=== PAUSE TestAccEventGridDomain_basicWithSystemManagedIdentity
=== RUN   TestAccEventGridDomain_basicWithUserAssignedManagedIdentity
=== PAUSE TestAccEventGridDomain_basicWithUserAssignedManagedIdentity
=== RUN   TestAccEventGridDomainTopicDataSource_basic
=== PAUSE TestAccEventGridDomainTopicDataSource_basic
=== RUN   TestAccEventGridDomainTopic_basic
=== PAUSE TestAccEventGridDomainTopic_basic
=== RUN   TestAccEventGridDomainTopic_requiresImport
=== PAUSE TestAccEventGridDomainTopic_requiresImport
=== RUN   TestAccEventGridEventSubscription_basic
=== PAUSE TestAccEventGridEventSubscription_basic
=== RUN   TestAccEventGridEventSubscription_requiresImport
=== PAUSE TestAccEventGridEventSubscription_requiresImport
=== RUN   TestAccEventGridEventSubscription_eventHubID
=== PAUSE TestAccEventGridEventSubscription_eventHubID
=== RUN   TestAccEventGridEventSubscription_serviceBusQueueID
=== PAUSE TestAccEventGridEventSubscription_serviceBusQueueID
=== RUN   TestAccEventGridEventSubscription_serviceBusTopicID
=== PAUSE TestAccEventGridEventSubscription_serviceBusTopicID
=== RUN   TestAccEventGridEventSubscription_update
=== PAUSE TestAccEventGridEventSubscription_update
=== RUN   TestAccEventGridEventSubscription_filter
=== PAUSE TestAccEventGridEventSubscription_filter
=== RUN   TestAccEventGridEventSubscription_advancedFilter
=== PAUSE TestAccEventGridEventSubscription_advancedFilter
=== RUN   TestAccEventGridEventSubscription_advancedFilterMaxItems
=== PAUSE TestAccEventGridEventSubscription_advancedFilterMaxItems
=== RUN   TestAccEventGridEventSubscription_identity
=== PAUSE TestAccEventGridEventSubscription_identity
=== RUN   TestAccEventGridSystemTopicEventSubscription_basic
=== PAUSE TestAccEventGridSystemTopicEventSubscription_basic
=== RUN   TestAccEventGridSystemTopicEventSubscription_requiresImport
=== PAUSE TestAccEventGridSystemTopicEventSubscription_requiresImport
=== RUN   TestAccEventGridSystemTopicEventSubscription_eventHubID
=== PAUSE TestAccEventGridSystemTopicEventSubscription_eventHubID
=== RUN   TestAccEventGridSystemTopicEventSubscription_serviceBusQueueID
=== PAUSE TestAccEventGridSystemTopicEventSubscription_serviceBusQueueID
=== RUN   TestAccEventGridSystemTopicEventSubscription_serviceBusTopicID
=== PAUSE TestAccEventGridSystemTopicEventSubscription_serviceBusTopicID
=== RUN   TestAccEventGridSystemTopicEventSubscription_update
=== PAUSE TestAccEventGridSystemTopicEventSubscription_update
=== RUN   TestAccEventGridSystemTopicEventSubscription_filter
=== PAUSE TestAccEventGridSystemTopicEventSubscription_filter
=== RUN   TestAccEventGridSystemTopicEventSubscription_advancedFilter
=== PAUSE TestAccEventGridSystemTopicEventSubscription_advancedFilter
=== RUN   TestAccEventGridSystemTopicEventSubscription_advancedFilterMaxItems
=== PAUSE TestAccEventGridSystemTopicEventSubscription_advancedFilterMaxItems
=== RUN   TestAccEventGridSystemTopicEventSubscription_identity
=== PAUSE TestAccEventGridSystemTopicEventSubscription_identity
=== RUN   TestAccEventGridSystemTopic_basic
=== PAUSE TestAccEventGridSystemTopic_basic
=== RUN   TestAccEventGridSystemTopic_policyStates
=== PAUSE TestAccEventGridSystemTopic_policyStates
=== RUN   TestAccEventGridSystemTopic_requiresImport
=== PAUSE TestAccEventGridSystemTopic_requiresImport
=== RUN   TestAccEventGridSystemTopic_complete
=== PAUSE TestAccEventGridSystemTopic_complete
=== RUN   TestAccEventGridSystemTopic_basicWithSystemManagedIdentity
=== PAUSE TestAccEventGridSystemTopic_basicWithSystemManagedIdentity
=== RUN   TestAccEventGridSystemTopic_basicWithUserAssignedManagedIdentity
=== PAUSE TestAccEventGridSystemTopic_basicWithUserAssignedManagedIdentity
=== RUN   TestAccEventGridTopicDataSource_basic
=== PAUSE TestAccEventGridTopicDataSource_basic
=== RUN   TestAccEventGridTopic_basic
=== PAUSE TestAccEventGridTopic_basic
=== RUN   TestAccEventGridTopic_requiresImport
=== PAUSE TestAccEventGridTopic_requiresImport
=== RUN   TestAccEventGridTopic_mapping
=== PAUSE TestAccEventGridTopic_mapping
=== RUN   TestAccEventGridTopic_basicWithTags
=== PAUSE TestAccEventGridTopic_basicWithTags
=== RUN   TestAccEventGridTopic_inboundIPRules
=== PAUSE TestAccEventGridTopic_inboundIPRules
=== RUN   TestAccEventGridTopic_basicWithSystemManagedIdentity
=== PAUSE TestAccEventGridTopic_basicWithSystemManagedIdentity
=== RUN   TestAccEventGridTopic_basicWithUserAssignedManagedIdentity
=== PAUSE TestAccEventGridTopic_basicWithUserAssignedManagedIdentity
=== CONT  TestAccEventGridDomainDataSource_basic
=== CONT  TestAccEventGridSystemTopicEventSubscription_eventHubID
=== CONT  TestAccEventGridEventSubscription_requiresImport
=== CONT  TestAccEventGridSystemTopicEventSubscription_requiresImport
=== CONT  TestAccEventGridSystemTopicEventSubscription_basic
=== CONT  TestAccEventGridEventSubscription_identity
=== CONT  TestAccEventGridEventSubscription_advancedFilterMaxItems
=== CONT  TestAccEventGridEventSubscription_advancedFilter
=== CONT  TestAccEventGridEventSubscription_filter
=== CONT  TestAccEventGridEventSubscription_update
=== CONT  TestAccEventGridEventSubscription_serviceBusTopicID
=== CONT  TestAccEventGridEventSubscription_serviceBusQueueID
--- PASS: TestAccEventGridEventSubscription_advancedFilterMaxItems (131.63s)
=== CONT  TestAccEventGridSystemTopic_basicWithSystemManagedIdentity
--- PASS: TestAccEventGridEventSubscription_advancedFilter (131.92s)
=== CONT  TestAccEventGridEventSubscription_eventHubID
--- PASS: TestAccEventGridEventSubscription_filter (138.49s)
=== CONT  TestAccEventGridDomain_basicWithSystemManagedIdentity
--- PASS: TestAccEventGridDomainDataSource_basic (149.60s)
=== CONT  TestAccEventGridTopic_basicWithUserAssignedManagedIdentity
--- PASS: TestAccEventGridSystemTopicEventSubscription_basic (152.47s)
=== CONT  TestAccEventGridEventSubscription_basic
--- PASS: TestAccEventGridSystemTopicEventSubscription_requiresImport (166.92s)
=== CONT  TestAccEventGridTopic_basicWithSystemManagedIdentity
--- PASS: TestAccEventGridEventSubscription_requiresImport (189.39s)
=== CONT  TestAccEventGridDomainTopic_requiresImport
--- PASS: TestAccEventGridEventSubscription_update (240.98s)
=== CONT  TestAccEventGridTopic_inb [...]

2021-09-06 11:29 UTC, stephybun approved these changes
Thanks @jrauschenbusch LGTM 🥳

2021-09-06 11:30 UTC, merged