Tags of Redis Enterprise ressources can be updated
hashicorp/terraform-provider-azurerm pull request #12956
Opened 2021-08-11 18:44 UTC by cloutier

I noticed my terraform plan wanted to recreate my redis enterprise when I changed the tags. I tried via the portal and I confirmed I could change them without recreating anything.

2021-08-12 04:39 UTC, katbyte requested changes
Thanks @cloutier - looks good but could we update the docs to reflect this change? thanks!

2021-08-12 13:46 UTC, cloutier commented
@katbyte done!

2021-08-12 22:57 UTC, katbyte approved these changes
Thanks @cloutier - LGTM 💯

2021-08-12 22:57 UTC, merged

2021-08-20 11:52 UTC, stack72 commented
Hi @cloutier / @katbyte 

This change actually made the tags for this a computed parameter only - they can no longer be set

I don't believe this is the correct change - I believe it should have been tags.Schema()

Paul