`azurerm_express_route_port`: Added `macsec_sci_state` and additional ciphers
hashicorp/terraform-provider-azurerm pull request #13006
Opened 2021-08-16 09:42 UTC by tiwood

New attribute: `macsec_sci_state`, which sets https://docs.microsoft.com/en-us/rest/api/expressroute/express-route-ports/create-or-update#expressroutelinkmacsecscistate

Added missing XPN ciphers.

This has to be merged first: https://github.com/hashicorp/terraform-provider-azurerm/pull/13002

2021-08-18 00:13 UTC, katbyte requested changes
Thanks @tiwood - looks good aside from one comment about the schema and missing docs

2021-08-18 00:13 UTC, katbyte commented on internal/services/network/express_route_port_resource.go
> +			"macsec_sci_state": {
state doesn't make much sense here? shoudl this be
```suggestion
			"macsec_sci_enabled": {
```

2021-09-01 23:07 UTC, tiwood commented
Just to let you know, there currently is an issue with the Azure API - it seems the SCI State is not reported back, which kind of blocks us here.

2021-09-09 23:33 UTC, katbyte commented
@tiwood - should we close this until the API has been fixed? it can be reopened once thats happened

2021-09-16 17:40 UTC, katbyte commented
Going to close this for now @tiwood - we can reopen it once the bug is fixed. thanks!

2021-09-16 17:40 UTC, closed without merging