add: eventgrid domain data source, test, docs
hashicorp/terraform-provider-azurerm pull request #13033
Opened 2021-08-17 13:29 UTC by Hjortsberg

2021-08-19 19:14 UTC, katbyte requested changes
Thanks for the pr @Hjortsberg - overall looks good and i've left some comments inline and the linters have called out the schema changes required

2021-08-19 19:14 UTC, katbyte commented on internal/services/eventgrid/eventgrid_domain_data_source.go
> +	d.SetId(*resp.ID)
we should be nil checking ID here

2021-08-19 19:14 UTC, katbyte commented on internal/services/eventgrid/eventgrid_domain_data_source_test.go
> +func TestAccEventGridDomainDataSource_basic(t *testing.T) {
we can probably remove the other tests, usually we just have a single data source test

2021-09-02 08:06 UTC, stephybun commented
@Hjortsberg since we haven't heard anything back yet i'm going to jump in here and finish up this PR so that your work can be merged and released to the community.

2021-09-02 08:16 UTC, Hjortsberg commented
@stephybun, sorry for the lack of replies from me. I greatly appreciate the contribution here, thank you.

2021-09-03 17:47 UTC, katbyte approved these changes
Thanks @Hjortsberg & @stephybun - LGTM 🍰

2021-09-03 17:47 UTC, merged