ml_compute_instance supports creation_script and startup_script
hashicorp/terraform-provider-azurerm pull request #13072
Opened 2021-08-20 02:10 UTC by ms-henglu

ml_compute_instance supports creation_script and startup_script

2021-08-29 01:05 UTC, katbyte requested changes

2021-08-29 01:05 UTC, katbyte commented on internal/services/machinelearning/machine_learning_compute_instance_resource.go
> +				d.Set("creation_script", flattenComputeScript(props.Properties.SetupScripts.Scripts.StartupScript))
should this be?
```suggestion
				d.Set("creation_script", flattenComputeScript(props.Properties.SetupScripts.Scripts. CreationScript))
```

2021-08-30 01:42 UTC, ms-henglu commented
@katbyte , Hi, thanks for pointing it out, I've fixed it, please take another look, thanks!

2021-08-30 11:28 UTC, katbyte approved these changes
Thanks @ms-henglu - LGTM 🚀

2021-08-30 12:40 UTC, katbyte requested changes
could we update/fix the tests so they pass when run at the same time please?
```
------ Stdout: -------
=== RUN   TestAccComputeCluster_basic
=== PAUSE TestAccComputeCluster_basic
=== CONT  TestAccComputeCluster_basic
    testcase.go:88: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Vault: (Name "acctestvault210830113699" / Resource Group "acctestRG-ml-210830113653483699"): keyvault.VaultsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="VaultAlreadyExists" Message="The vault name 'acctestvault210830113699' is already in use. Vault names are globaly unique so it is possible that the name is already taken. If you are sure that the vault name was not taken then it is possible that a vault with the same name was recently deleted but not purged after being placed in a recoverable state. If the vault is in a recoverable state then the vault will need to be purged before reusing the name. For more information on soft delete and purging a vault follow this link https://go.microsoft.com/fwlink/?linkid=2147740."
        
          with azurerm_key_vault.test,
          on terraform_plugin_test.tf line 24, in resource "azurerm_key_vault" "test":
          24: resource "azurerm_key_vault" "test" {
        
--- FAIL: TestAccComputeCluster_basic (164.97s)
FAIL
```

2021-08-31 03:18 UTC, ms-henglu commented
@katbyte , Hi, keyvault's name updated.
![image](https://user-images.githubusercontent.com/79895375/131436215-1a0f1af1-e48f-4bf3-8b1a-6e4d057badc4.png)

2021-09-02 17:08 UTC, katbyte commented
Looks like we have a transitory failure? 
```
------- Stdout: -------
=== RUN   TestAccComputeInstance_complete
=== PAUSE TestAccComputeInstance_complete
=== CONT  TestAccComputeInstance_complete
    testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Subnet: (Name "internal" / Virtual Network Name "acctest21083190" / Resource Group "acctestRG-ml-210831223127158990"): network.SubnetsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet internal is in use by /subscriptions/9327cac6-f79a-46ec-a3fb-75563f3f7b8e/resourceGroups/f6341291-5815-4ad7-9e7c-25a1d2fd5319-AzureBatch-CloudService/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|f6341291-5815-4ad7-9e7c-25a1d2fd5319-AzureBatch-Deployment|virtualMachines|1|networkInterfaces|nic1/ipConfigurations/ip1 and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]
        
--- FAIL: TestAccComputeInstance_complete (1066.33s)
FAIL
```

2021-09-08 01:51 UTC, ms-henglu commented
@katbyte , please hold on merging this PR, I got some requests from service team.

2021-09-16 18:18 UTC, katbyte commented
@ms-henglu - given this is sitting blocked on the service team iu am going to close it, please reopen it once its ready to go!

2021-09-16 18:18 UTC, closed without merging