Feature/synapse activate workspace
hashicorp/terraform-provider-azurerm pull request #13179
Opened 2021-08-30 18:19 UTC by MoAhuja

Fixes: #12348

- Added new synapse_workspace_key resource type to support activation of a workspace encryption key
- Updated synapse_workspace to support naming of the CMK. Currently implementation defaults to "cmk" which makes it challenging to rotate encryption keys.

2021-09-02 17:03 UTC, katbyte requested changes
Thanks for the pr @MoAhuja - looks like we have some test failures to fix:
```
------- Stdout: -------
=== RUN   TestAccSynapseWorkspace_azdo
=== PAUSE TestAccSynapseWorkspace_azdo
=== CONT  TestAccSynapseWorkspace_azdo
    testcase.go:88: Step 1/1 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # azurerm_synapse_workspace.test will be updated in-place
          ~ resource "azurerm_synapse_workspace" "test" {
              + customer_managed_key_name            = "cmk"
                id                                   = "/subscriptions/*******/resourceGroups/acctestRG-synapse-210831222712997048/providers/Microsoft.Synapse/workspaces/acctestsw210831222712997048"
                name                                 = "acctestsw210831222712997048"
                # (11 unchanged attributes hidden)
        
                # (1 unchanged block hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccSynapseWorkspace_azdo (741.82s)
FAIL
```

2021-09-10 15:10 UTC, MoAhuja commented on internal/services/synapse/synapse_workspace_key_resource.go
> +			"is_active_cmk": {
Adjusted

2021-09-10 15:28 UTC, MoAhuja commented
@katbyte  Thanks for the review. I've modified the synapse_workspace resource's property structure to bundle up key_name and key_versionless_id into a new type. This seemed like the only way to support a model where key_name could be optional and defaulted to "cmk" while making sure it's only ever used if key_versionless_id is set.

Called this out here because this is breaking change from the previous version of the synapse workspace  resource type and I'm not sure how those typically get handled as part of provider releases.

2021-09-16 03:50 UTC, katbyte approved these changes
Thanks @MoAhuja - LGTM 🏗️

2021-09-16 15:58 UTC, merged