azurerm_data_factory_trigger_schedule supports schedule and description
hashicorp/terraform-provider-azurerm pull request #13243
Opened 2021-09-07 03:43 UTC by ms-henglu

2021-09-07 13:35 UTC, stephybun requested changes
Thanks for this PR @ms-henglu, tests look good, just a few minor remarks and some suggestions for the docs. Once those are addressed then this LGTM 👍🏼

2021-09-07 13:35 UTC, stephybun commented on website/docs/r/data_factory_trigger_schedule.html.markdown
> +* `schedule` - (Optional) The recurrence schedule for the trigger. A trigger with a specified frequency value alters its recurrence based on a recurrence schedule. The schedule property contains modi
```suggestion
* `schedule` - (Optional) A `schedule` block as defined below, which further specifies the recurrence schedule for the trigger. A schedule is capable of limiting or increasing the number of trigger executions specified by the `frequency` and `interval` properties.
```

2021-09-07 13:35 UTC, stephybun commented on website/docs/r/data_factory_trigger_schedule.html.markdown
> +* `days_of_month` - (Optional) 	Day of the month on which the trigger runs. The value can be specified with a monthly frequency only.
```suggestion
* `days_of_month` - (Optional) Day(s) of the month on which the trigger is scheduled. This value can be specified with a monthly frequency only.
```

2021-09-07 13:35 UTC, stephybun commented on website/docs/r/data_factory_trigger_schedule.html.markdown
> +* `hours` - (Optional) Hours of the day at which the trigger runs.
```suggestion
* `hours` - (Optional) Hours of the day on which the trigger is scheduled.
```

2021-09-07 13:35 UTC, stephybun commented on website/docs/r/data_factory_trigger_schedule.html.markdown
> +`monthly_occurrence` supports the following:
```suggestion
A `monthly_occurrence` block supports the following:
```

2021-09-07 13:35 UTC, stephybun commented on website/docs/r/data_factory_trigger_schedule.html.markdown
> +* `occurrence` - (Optional) The occurrence of the specified day during the month. For example, a `monthly_occurrence` property with day and occurrence values of `Sunday, -1` means the last Sunday of
```suggestion
* `occurrence` - (Optional) The occurrence of the specified day during the month. For example, a `monthly_occurrence` property with `day` and `occurrence` values of `Sunday, -1` means the last Sunday of the month.
```

2021-09-07 13:38 UTC, stephybun commented on internal/services/datafactory/data_factory_trigger_schedule_resource.go
> +			"description": {
Disregard this comment, I think github/browser is messing with the appearance of the formatting.

2021-09-07 19:04 UTC, katbyte commented on internal/services/datafactory/data_factory_trigger_schedule_resource.go
> +						"monthly_occurrence": {
i think we can remove occurrence here for a bit better UX
```suggestion
						"monthly": {
```

2021-09-07 19:05 UTC, katbyte commented on internal/services/datafactory/data_factory_trigger_schedule_resource.go
> +									"occurrence": {
and occurrence is not clear, how about
```suggestion
									"week": {
```

2021-09-07 20:05 UTC, katbyte commented on internal/services/datafactory/data_factory_trigger_schedule_resource.go
> +									"day": {
would this be more clear as 
```suggestion
									"weekday": {
```

2021-09-08 02:21 UTC, ms-henglu commented
@katbyte @stephybun Hi all, thanks for code review!
I've added a commit according to your suggestions, please take another look, thanks!

2021-09-09 01:18 UTC, katbyte approved these changes
Thanks @ms-henglu - LGTM 🍰

2021-09-09 01:18 UTC, merged