`azurerm_kubernetes_cluster`: Support `local_account_disabled` setup in data source
hashicorp/terraform-provider-azurerm pull request #13260
Opened 2021-09-07 18:47 UTC by aristosvo

Fixes #13248

2021-09-07 19:21 UTC, katbyte requested changes
Thanks @aristosvo - couple minor comments and it looks like the test is failing: 
```
------- Stdout: -------
=== RUN   TestAccDataSourceKubernetesCluster_localAccountDisabled
=== PAUSE TestAccDataSourceKubernetesCluster_localAccountDisabled
=== CONT  TestAccDataSourceKubernetesCluster_localAccountDisabled
    testcase.go:88: Step 1/1 error: Check failed: Check 8/8 error: data.azurerm_kubernetes_cluster.test: Attribute 'kube_admin_config_raw' found when not expected
--- FAIL: TestAccDataSourceKubernetesCluster_localAccountDisabled (532.56s)
FAIL
```

2021-09-07 19:21 UTC, katbyte commented on website/docs/d/kubernetes_cluster.html.markdown
> +* `kube_admin_config` - A `kube_admin_config` block as defined below. This is only available when Role Based Access Control with Azure Active Directory is enabled and local accounts not disabled.
```suggestion
* `kube_admin_config` - A `kube_admin_config` block as defined below. This is only available when Role Based Access Control with Azure Active Directory is enabled and local accounts are not disabled.
```

2021-09-07 19:21 UTC, katbyte commented on website/docs/d/kubernetes_cluster.html.markdown
> +* `kube_admin_config_raw` - Raw Kubernetes config for the admin account to be used by [kubectl](https://kubernetes.io/docs/reference/kubectl/overview/) and other compatible tools. This is only availa
```suggestion
* `kube_admin_config_raw` - Raw Kubernetes config for the admin account to be used by [kubectl](https://kubernetes.io/docs/reference/kubectl/overview/) and other compatible tools. This is only available when Role Based Access Control with Azure Active Directory is enabled and local accounts are not disabled.
```

2021-09-07 19:24 UTC, aristosvo commented on website/docs/d/kubernetes_cluster.html.markdown
> +* `kube_admin_config` - A `kube_admin_config` block as defined below. This is only available when Role Based Access Control with Azure Active Directory is enabled and local accounts not disabled.
Thanks, resolved! 🥳

2021-09-07 19:25 UTC, aristosvo commented on website/docs/d/kubernetes_cluster.html.markdown
> +* `kube_admin_config_raw` - Raw Kubernetes config for the admin account to be used by [kubectl](https://kubernetes.io/docs/reference/kubectl/overview/) and other compatible tools. This is only availa
Thanks, fixed! 🎈

2021-09-07 19:26 UTC, aristosvo commented
@katbyte Thanks for the quick review! Was already running (and fixing) locally, so I believe it is solved for now 👍🏽

2021-09-08 21:24 UTC, katbyte approved these changes
Thanks @aristosvo! LGTM 🏗️

2021-09-08 21:25 UTC, merged