Deprecate storage_account_name in favor of storage_account_id
hashicorp/terraform-provider-azurerm pull request #13307
Opened 2021-09-10 13:00 UTC by owenfarrell

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### Summary

This pull request establishes a migration path from the current use resource group name and storage account name towards storage account IDs instead.

* The resouce group name and storage account name fields have been marked as deprecated in favor of the storage account ID
* Existing acceptance tests have **_not_** been modified to confirm backwards compatibility with the current implementation 

Fixes: #9899
Related: #13106

Output from acceptance testing:

```
$ make acctests SERVICE='storage' TESTARGS='-run=TestAccStorageAccountNetworkRules_' TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/storage -run=TestAccStorageAccountNetworkRules_ -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccStorageAccountNetworkRules_basic
=== PAUSE TestAccStorageAccountNetworkRules_basic
=== RUN   TestAccStorageAccountNetworkRules_id
=== PAUSE TestAccStorageAccountNetworkRules_id
=== RUN   TestAccStorageAccountNetworkRules_update
=== PAUSE TestAccStorageAccountNetworkRules_update
=== RUN   TestAccStorageAccountNetworkRules_privateLinkAccess
=== PAUSE TestAccStorageAccountNetworkRules_privateLinkAccess
=== RUN   TestAccStorageAccountNetworkRules_SynapseAccess
=== PAUSE TestAccStorageAccountNetworkRules_SynapseAccess
=== RUN   TestAccStorageAccountNetworkRules_empty
=== PAUSE TestAccStorageAccountNetworkRules_empty
=== CONT  TestAccStorageAccountNetworkRules_basic
=== CONT  TestAccStorageAccountNetworkRules_privateLinkAccess
=== CONT  TestAccStorageAccountNetworkRules_update
=== CONT  TestAccStorageAccountNetworkRules_id
=== CONT  TestAccStorageAccountNetworkRules_empty
=== CONT  TestAccStorageAccountNetworkRules_SynapseAccess
--- PASS: TestAccStorageAccountNetworkRules_empty (183.93s)
--- PASS: TestAccStorageAccountNetworkRules_basic (251.22s)
--- PASS: TestAccStorageAccountNetworkRules_id (289.08s)
--- PASS: TestAccStorageAccountNetworkRules_privateLinkAccess (512.75s)
--- PASS: TestAccStorageAccountNetworkRules_update (529.76s)
--- PASS: TestAccStorageAccountNetworkRules_SynapseAccess (880.36s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/storage       883.124s
```

2021-09-22 22:57 UTC, mbfrahry requested changes
Hey @owenfarrell! This PR is looking pretty great but I am seeing issues with one of the tests. Do you mind rerunning `TestAccStorageAccountNetworkRules_update` with this code rebased against the master branch? Here is the error I'm seeing: 

```
Error: updating Azure Storage Account Network Rules "XXXX" (Resource Group "XXXX): storage.AccountsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NetworkAclsValidationFailure" Message="Validation of network acls failure: ParentResourceNotFound:Can not perform requested operation on nested resource. Parent resource 'XXXX' not found.."
```

2021-09-23 01:10 UTC, owenfarrell commented
@mbfrahry - thanks for taking a look!

As much as I hate this response, this one goes under the "works for me" category. I just reran the acceptance tests and everything came out clean.

Granted, I've force pushed a handful of time to try to keep the commit list clean - but that was mostly to make the documentation diffs more readable.

But when I diff the **_parent_** of my original commit (https://github.com/hashicorp/terraform-provider-azurerm/commit/7f8a940cab6e7b4537f845df6cb707ed95750978) with the current contents of [`main`](https://github.com/hashicorp/terraform-provider-azurerm/tree/main), the only changes related to the storage service come from #13269... which doesn't seem to have anything that overlaps with these changes.

Maybe this is just a flaky test?

2021-09-23 03:24 UTC, katbyte commented
hmm, seems like its a change that just started happening for us on main too @mbfrahry 
![image](https://user-images.githubusercontent.com/1638467/134450362-38950d8c-1ac0-450e-98f8-89c434664ba9.png)

if it passes for @owenfarrell but not us could just be a transitory things with our account 🤷‍♀️

2021-09-23 15:44 UTC, mbfrahry approved these changes
Ohh, good catch @katbyte. Sorry for the extra work on your end @owenfarrell. This LGTM!

2021-09-23 15:45 UTC, merged