Update Log Analytics Solution to no longer enforce naming requirements
hashicorp/terraform-provider-azurerm pull request #13532
Opened 2021-09-28 14:28 UTC by dhensby

Fixes #1775

This change no longer enforces the arbitrary naming of Log Analytic Solution resources. As per my testing with the REST API directly and this change, the resources are correctly created without seeing errors as reported in the above issue.

As the resource name is no longer constructed for the developer, the `workspance_name` value is deprecated and no longer used.

2021-09-29 19:41 UTC, katbyte requested changes
Thanks for the fix @dhensby - could we get a test with the relaxed namign conventions to ensure it works, and we catch any regressions for the API? thanks!

2021-09-30 21:26 UTC, katbyte requested changes
Thanks @dhensby - looks like we have some failing tests now:
```
------- Stdout: -------
=== RUN   TestAccLogAnalyticsSolution_basicContainerMonitoring
=== PAUSE TestAccLogAnalyticsSolution_basicContainerMonitoring
=== CONT  TestAccLogAnalyticsSolution_basicContainerMonitoring
    testcase.go:88: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating/updating Log Analytics Solution "ContainerInsights" (Workspace "/subscriptions/*******/resourceGroups/acctestRG-210930185701893506/providers/Microsoft.OperationalInsights/workspaces/acctestLAW-210930185701893506" / Resource Group "acctestRG-210930185701893506"): pollingTrackerBase#updateRawBody: failed to unmarshal response body: StatusCode=0 -- Original Error: invalid character 'F' looking for beginning of value
        
          with azurerm_log_analytics_solution.test,
          on terraform_plugin_test.tf line 18, in resource "azurerm_log_analytics_solution" "test":
          18: resource "azurerm_log_analytics_solution" "test" {
        
--- FAIL: TestAccLogAnalyticsSolution_basicContainerMonitoring (85.62s)
FAIL
```

2021-10-04 15:24 UTC, dhensby commented
Interesting, I'm using this locally to provision a VMInsights LAS and it is working fine:

```hcl
resource "azurerm_log_analytics_solution" "log_analytics" {
  solution_name         = var.las_name
  location              = var.location
  resource_group_name   = var.rg_name
  workspace_resource_id = var.workspace_resource_id

  plan {
    product   = "Microsoft"
    publisher = "OMSGallery/VMInsights"
  }
}
```

```
  + resource "azurerm_log_analytics_solution" "log_analytics" {
      + id                    = (known after apply)
      + location              = "westeurope"
      + resource_group_name   = "resource-group"
      + solution_name         = "vm-las-random"
      + workspace_resource_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resource-group/providers/Microsoft.OperationalInsights/workspaces/log-analytics-workspace"

      + plan {
          + name      = (known after apply)
          + product   = "Microsoft"
          + publisher = "OMSGallery/VMInsights"
        }
    }

...

module.entire_di.module.drop_server.azurerm_log_analytics_solution.log_analytics: Creation complete after 4s [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resource-group/providers/Microsoft.OperationsManagement/solutions/log-analytics-solution]
```

I'll investigate with other solution names that may well be enforcing this naming convention...

2021-10-04 15:32 UTC, dhensby commented
Seems to be working with `ContainerInsights` too...

I'm going to see if we get another failure in the test suite and then look further if it continues to fail.

2021-10-05 08:21 UTC, dhensby commented
@katbyte all the CI runs have passed, does that mean we are good? I'm not sure why the old ones failed...

2021-12-01 09:53 UTC, BrewToR commented
We are stuck because of this issue, when it will be release please ?

2021-12-01 14:02 UTC, dhensby commented
I've rebased this in an attempt to integrate the upstream changes. Let's see if this passes 🤞

2021-12-01 14:57 UTC, manicminer commented
Hi @dhensby, thanks for working on this! I've done some testing both with and without your changes, and I'm not sure why these changes are necessary? The resource as it currently stands is working for me - I also added a test for the `OMSGallery/VMInsights` solution/plan and that also worked. Conversely, when testing with these changes, I'm getting the (malformed) response:

```For first party solution, the solution name has to be convention of solutionType(workspaceName), and the product has to be OMSGallery/solutionType.  For example, product OMSGallery/ChangeTracking, solution name ChangeTracking(myworkspace)```

To clarify, I agree that this "convention" and overloading of names by the API is less than optimal, but at least in our testing subscription, it seems to be working as it is right now. I'm assuming that this isn't the case in your subscription, or for your configuration - would you be able to share a configuration that doesn't work with the current implementation of the resource?

For the actual change, we will need to ensure backwards compatibility for existing configurations (and statefiles), else the change can only be merged for the next major release of the provider. I believe this should be possible with some string matching to try and get a best guess of what to send to the API - also not ideal but this is what we have to work with!

2021-12-01 16:30 UTC, dhensby commented
Yep - with my set-up I'm seeing the error without this fix. I have given up on deploying the log analytic solution, but may revisit it later to take a look at a replication example.

2021-12-01 16:55 UTC, dhensby commented
config that fails for me:

```hcl
resource "azurerm_log_analytics_solution" "log_analytics" {
  solution_name         = "dev-drop-las-random"
  location              = "westeurope"
  resource_group_name   = var.rg_name
  workspace_resource_id = var.workspace_resource_id
  workspace_name        = var.workspace_name

  plan {
    product   = "Microsoft"
    publisher = "OMSGallery/VMInsights"
  }

  tags = var.tags
}
```

output is the failed to unmarshal resposne body error

2021-12-01 17:00 UTC, dhensby commented
FYI - [this comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/1775#issuecomment-927765831) still outlines my issues in the most detail.

2021-12-02 00:10 UTC, manicminer commented
@dhensby Thanks for coming back, I'll look into this further tomorrow. Sorry, I don't mean to be pedantic, but could you provide the values of the variables you're referencing? If they're the same as in the linked issue then I can infer them from the logs you posted, but it would be good to have clarity given the API behavior we're trying to narrow down. Thanks!

2021-12-03 00:21 UTC, manicminer commented
@dhensby Looking at the config you posted, it seems like the `publisher` and `product` properties (in the `plan` block) are mixed up? Can you confirm if this is the case in your configuration? When I use your config as supplied, I do indeed get the error (which admittedly fails to unmarshal), but when I correct these, I am able to create solutions, with ContainerInsights, Security and VMInsights all working.

2021-12-03 00:28 UTC, dhensby commented
Oh jeez... Let me check that out tomorrow. I hope it is that simple 😅🤦‍♂️

2021-12-03 07:41 UTC, dhensby commented
OK - I just tried them the otherway round and I still get the same problem:

```hcl
resource "azurerm_log_analytics_solution" "log_analytics" {
  solution_name         = "${var.app_name}-${var.name}-las-${var.uniqid}"
  location              = var.location
  resource_group_name   = var.rg_name
  workspace_resource_id = var.workspace_resource_id
  workspace_name        = var.workspace_name

  plan {
    product   = "OMSGallery/VMInsights"
    publisher = "Microsoft"
  }

  tags = var.tags
}
```

I'd rather not share the resource names publicly, but I can try to set up a temp sub/resource group to replicate this and share that.

2021-12-03 11:22 UTC, manicminer commented
Hi @dhensby, thanks for checking that. I'm not sure why that config would be expected to work - as the API error states:

> For first party solution, the solution name has to be convention of solutionType(workspaceName), and the product has to be OMSGallery/solutionType.  For example, product OMSGallery/ChangeTracking, solution name ChangeTracking(myworkspace)

i.e. the value of `solution_name` in your configuration should be `VMInsights` rather than the custom name provided.

Did this perhaps work in the past / is this naming convention a new constraint? It looks like our tests have always conformed to this convention and have consistently been working.

2021-12-03 11:47 UTC, dhensby commented
Whilst that may be the response from the API, it's not actually the case, it appears to only be the response if you attempt to create a resource with the name in a format that is *like* `xxx(yyy)` *then* you get the error. You can create log analytics solutions that don't confirm to the naming format requirement.

However, I do note that this does work when I replace the `solution_name` with `VMInsights`, which seems a bit tautologous (why do we define a solution name twice considering there is no option or flexibility in this parameter).

Anyway, I've come to some kind of resolution (but I'd definitely prefer to provide my own name) for my problem.

A solution could be to add a `name` parameter, if that's provided it is used as the name, otherwise the current convention is used to calculate the `name`?

2021-12-03 12:00 UTC, manicminer commented
@dhensby Ah I see, appreciate the clarification. In that case we can perhaps tackle this without any schema changes - if the user-supplied `workspace_name` matches the latter segment of the plan name, we can transform it per the API's expectation (as we do now), otherwise attempt to create with the custom, unmangled `workspace_name`. It would preclude being able to use an unqualified matching name like `workspace_name = "VMInsights"` but perhaps that's for the best given the potential confusion.

2021-12-07 14:28 UTC, manicminer commented
Closing this as the implementation doesn't maintain compatibility. In terms of customization of the resource name (for a Log Analytics Workspace Solution), please see further observations in the linked issue.

2021-12-07 14:28 UTC, closed without merging