State migration for storage account resource
hashicorp/terraform-provider-azurerm pull request #13607
Opened 2021-10-04 11:42 UTC by koikonom

In 3.0 we're renaming `allow_blob_public_access` to
`allow_nested_items_to_be_public`.

This PR adds a state migration to support this change that only takes
place when we're actually running on 3.0 or the user has opted-in.

2021-10-04 16:34 UTC, tombuildsstuff reviewed
A few minor comments but this otherwise LGTM 👍

2021-10-04 16:34 UTC, tombuildsstuff commented on internal/services/storage/storage_account_resource.go
> +	if features.ThreePointOhBetaResources() {
this should be gated behind 3.0 not the new app service resources:

```suggestion
	if features.ThreePointOh() {
```

2021-10-04 16:34 UTC, tombuildsstuff commented on internal/services/storage/storage_account_resource.go
> +	return features.ThreePointOhBetaResources()
this should be gated behind 3.0 not the new app service resources:

```suggestion
	return features.ThreePointOh()
```

2021-10-04 16:34 UTC, tombuildsstuff commented on internal/services/storage/storage_account_resource_test.go
> +		t.Skip("Skipping since ARM_THREEPOINTZERO_BETA_RESOURCES is set")
```suggestion
		t.Skip("Skipping since 3.0 mode is enabled")
```

2021-10-04 16:34 UTC, tombuildsstuff commented on internal/services/storage/storage_account_resource_test.go
> +	if features.ThreePointOhBetaResources() {
can we gate this behind 3.0 and not the new resources:

```suggestion
	if features.ThreePointOh() {
```

2021-10-04 16:34 UTC, tombuildsstuff commented on internal/services/storage/storage_account_resource_test.go
> +      allowed_origins    = ["	http://www.example.com"]
is that intentional spacing?

2021-10-05 08:49 UTC, koikonom commented on internal/services/storage/storage_account_resource_test.go
> +      allowed_origins    = ["	http://www.example.com"]
more like accidental :)

2021-10-05 08:50 UTC, koikonom commented on internal/services/storage/storage_account_resource.go
> +	if features.ThreePointOhBetaResources() {
@tombuildsstuff I'm assuming you did not leave this out on purpose?

2021-11-16 12:30 UTC, tombuildsstuff requested changes
hey @koikonom 

Thanks for pushing those changes - apologies for the delayed re-review here.

Taking a look through if we can strip out the validation functions and expand the common schema (since State Migrations are a point-in-time reference, so these shouldn't change over time which common schema may) then this should otherwise be good to go, I've tried to call all of those out so 🤞 most of those can be fixed with Github

Thanks!

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +			Default: string(storage.StorageV2),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +			ValidateFunc: validate.StorageAccountName,
fwiw you don't need this for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +		"location": azure.SchemaLocation(),
this is a point in time reference - can we expand `location` and `resource_group_name` (and strip out the validation etc)?

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +			DiffSuppressFunc: suppress.CaseDifference,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +			DiffSuppressFunc: suppress.CaseDifference,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +			}, true),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +						}, false),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.StringIsNotEmpty,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.IsUUID,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.StringIsNotEmpty,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.StringIsNotEmpty,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.StringIsNotEmpty,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.StringIsNotEmpty,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +			}, false),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +							}, true),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +							ValidateFunc: validate.StorageAccountIpRule,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +						}, false),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: azure.ValidateResourceID,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.IsUUID,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +						}, true),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +							ValidateFunc: msiValidate.UserAssignedIdentityID,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +					"cors_rule": helpers.SchemaStorageAccountCorsRule(true),
since this is a point in time can we duplicate the schema (and strip out any validation) here

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.IntBetween(1, 365),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +						ValidateFunc: validate.BlobPropertiesDefaultServiceVersion,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.IntBetween(1, 365),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +					"cors_rule": helpers.SchemaStorageAccountCorsRule(false),
(as above) this is a point in time reference - can we expand this (and strip out the validation etc)?

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.StringIsNotEmpty,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.IntBetween(1, 365),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.StringIsNotEmpty,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.IntBetween(1, 365),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.StringIsNotEmpty,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.IntBetween(1, 365),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +						Default: string(storage.MicrosoftRouting),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +					"cors_rule": helpers.SchemaStorageAccountCorsRule(true),
(as above) this is a point-in-time reference could we expand this and strip out the validation functions?

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +									ValidateFunc: validation.IntBetween(1, 365),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +										}, false),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +										}, false),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +										}, false),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +										}, false),
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +						ValidateFunc: validation.StringIsNotEmpty,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +						ValidateFunc: validation.StringIsNotEmpty,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-16 12:30 UTC, tombuildsstuff commented on internal/services/storage/migration/account.go
> +			ValidateFunc: validate.StorageAccountTags,
fwiw you don't need these for a state migration - only the Type and Required/Optional/Computed iirc

```suggestion
```

2021-11-17 13:06 UTC, koikonom commented
Rebased on top of latest main

2021-11-17 18:35 UTC, merged