r/azurerm_linux_virtual_machine and r/azurerm_linux_virtual_machine_scale_set - secure_boot_enabled, vtpm_enabled
hashicorp/terraform-provider-azurerm pull request #13842
Opened 2021-10-22 05:54 UTC by ms-henglu

```
=== RUN   TestAccLinuxVirtualMachine_otherUefi
=== PAUSE TestAccLinuxVirtualMachine_otherUefi
=== CONT  TestAccLinuxVirtualMachine_otherUefi
--- PASS: TestAccLinuxVirtualMachine_otherUefi (863.74s)

=== RUN   TestAccLinuxVirtualMachineScaleSet_otherUefi
=== PAUSE TestAccLinuxVirtualMachineScaleSet_otherUefi
=== CONT  TestAccLinuxVirtualMachineScaleSet_otherUefi
--- PASS: TestAccLinuxVirtualMachineScaleSet_otherUefi (750.46s)

=== RUN   TestAccWindowsVirtualMachine_otherUefi
=== PAUSE TestAccWindowsVirtualMachine_otherUefi
=== CONT  TestAccWindowsVirtualMachine_otherUefi
--- PASS: TestAccWindowsVirtualMachine_otherUefi (813.99s)

=== RUN   TestAccWindowsVirtualMachineScaleSet_otherUefi
=== PAUSE TestAccWindowsVirtualMachineScaleSet_otherUefi
=== CONT  TestAccWindowsVirtualMachineScaleSet_otherUefi
--- PASS: TestAccWindowsVirtualMachineScaleSet_otherUefi (781.65s)
PASS

Process finished with exit code 0

```

Fixes #13039

2021-11-16 13:41 UTC, tombuildsstuff requested changes
hi @ms-henglu 

Thanks for pushing those changes - I've taken a look through and left a few comments inline, if we can fix those up then this should otherwise be good to go 👍 

Thanks!

2021-11-16 13:41 UTC, tombuildsstuff commented on internal/services/compute/linux_virtual_machine_resource_other_test.go
> +		data.ImportStep(),
this field is ForceNew, so the update will recreate this, so we can remove this:

2021-11-16 13:41 UTC, tombuildsstuff commented on internal/services/compute/linux_virtual_machine_resource_other_test.go
> +			Config: r.otherSecureBootEnabled(data, false),
which means this should be Enabled true:

```suggestion
			Config: r.otherSecureBootEnabled(data, true),
```

2021-11-16 13:41 UTC, tombuildsstuff commented on internal/services/compute/linux_virtual_machine_scale_set_other_resource_test.go
> +		),
(same here) this field is ForceNew but we're checking we can enable this field:

```suggestion
```

2021-11-16 13:41 UTC, tombuildsstuff commented on internal/services/compute/linux_virtual_machine_scale_set_other_resource_test.go
> +  sku                 = "Standard_DS3_V2"
this is a machine with 4 cores and 14GB of ram.. an F1 will be more than sufficient here

2021-11-17 02:21 UTC, ms-henglu commented on internal/services/compute/linux_virtual_machine_resource_other_test.go
> +  size                = "Standard_DS3_v2"
I tried F1, but got "The selected VM size 'Standard_F1' cannot boot Hypervisor Generation '2'"

2021-11-17 02:46 UTC, ms-henglu commented
Hi @tombuildsstuff ,

I've added a commit according to your suggestions, would you please take another look? thanks!

2021-11-17 09:17 UTC, tombuildsstuff commented on internal/services/compute/linux_virtual_machine_resource_other_test.go
> +  size                = "Standard_DS3_v2"
you'll need to use the Gen1 image too (see the other VM/VMSS tests for examples)

2021-11-17 09:19 UTC, ms-henglu commented on internal/services/compute/linux_virtual_machine_resource_other_test.go
> +  size                = "Standard_DS3_v2"
It seems this feature can only be enabled in Gen2 image.

2021-11-18 02:06 UTC, ms-henglu commented on internal/services/compute/linux_virtual_machine_resource_other_test.go
> +  size                = "Standard_DS3_v2"
I changed to `Standard_B1ls`, please take another look, thanks!

2021-11-18 05:57 UTC, ms-henglu commented
Hi @tombuildsstuff ,

I changed them to use a smaller vm size, please take another look, thanks!

2021-11-22 23:34 UTC, tombuildsstuff approved these changes
LGTM - thanks for making those changes @ms-henglu

2021-11-26 16:52 UTC, merged