new resource `azurerm_stream_analytics_output_synapse`
hashicorp/terraform-provider-azurerm pull request #14013
Opened 2021-11-03 12:18 UTC by owenfarrell

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### Summary

This pull request adds a new resource to manage a Stream Analytics output to a Synapse Workspace.

Fixes: #8881

Output from acceptance testing:

```
$ make acctests SERVICE='streamanalytics' TESTARGS='-run="^TestAccStreamAnalyticsOutputSynapse_"'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/streamanalytics -run="^TestAccStreamAnalyticsOutputSynapse_" -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccStreamAnalyticsOutputSynapse_basic
=== PAUSE TestAccStreamAnalyticsOutputSynapse_basic
=== RUN   TestAccStreamAnalyticsOutputSynapse_sqlPool
=== PAUSE TestAccStreamAnalyticsOutputSynapse_sqlPool
=== RUN   TestAccStreamAnalyticsOutputSynapse_update
=== PAUSE TestAccStreamAnalyticsOutputSynapse_update
=== RUN   TestAccStreamAnalyticsOutputSynapse_requiresImport
=== PAUSE TestAccStreamAnalyticsOutputSynapse_requiresImport
=== CONT  TestAccStreamAnalyticsOutputSynapse_basic
=== CONT  TestAccStreamAnalyticsOutputSynapse_update
=== CONT  TestAccStreamAnalyticsOutputSynapse_requiresImport
=== CONT  TestAccStreamAnalyticsOutputSynapse_sqlPool
--- PASS: TestAccStreamAnalyticsOutputSynapse_basic (629.72s)
--- PASS: TestAccStreamAnalyticsOutputSynapse_requiresImport (794.48s)
--- PASS: TestAccStreamAnalyticsOutputSynapse_update (895.11s)
--- PASS: TestAccStreamAnalyticsOutputSynapse_sqlPool (1147.35s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/streamanalytics       1150.196s
```

2021-11-03 15:13 UTC, stephybun requested changes
Thanks for this PR @owenfarrell. This is almost good to go, just a few suggestions and waiting for the tests to run through 🙂.

2021-11-03 15:13 UTC, stephybun commented on website/docs/r/stream_analytics_output_synapse.html.markdown
> +* `id` - The ID of the Stream Analytics Output Microsoft SQL Server Database.
Wondering whether this should actually be
```suggestion
* `id` - The ID of the Stream Analytics Output Azure Synapse Workspace.
```

2021-11-04 20:27 UTC, owenfarrell commented
@stephybun - All updates incorporated. I may have gone overboard on the stream analytics type calculation, but I tried to replicate the existing pattern, which should help incorporate type validation in to the other stream analytics output resource types as well.

2021-11-04 22:36 UTC, katbyte approved these changes
Thanks @owenfarrell! LGTM 🚀

2021-11-04 22:36 UTC, merged