Create Batch Application data source
hashicorp/terraform-provider-azurerm pull request #14043
Opened 2021-11-04 21:39 UTC by oWretch

2021-11-09 17:25 UTC, stephybun requested changes
Thanks for this new data source @oWretch. Overall this is in good shape, there are just a few minor suggestions 🙂

2021-11-09 17:25 UTC, stephybun commented on CHANGELOG.md
> +* **New Data Source:** `azurerm_batch_application` ([#14043](https://github.com/hashicorp/terraform-provider-azurerm/issues/14043))
While the foresight is appreciated here, the changelog entry is only done after the PR has been approved and merged.
```suggestion
```

2021-11-09 17:25 UTC, stephybun commented on internal/services/batch/batch_application_data_source.go
> +	accountName := d.Get("account_name").(string)
Could we use the id parser here
```suggestion
        subscriptionId := meta.(*clients.Client).Account.SubscriptionId
        id := parse.NewApplicationID(subscriptionId, d.Get("resource_group_name").(string), d.Get("account_name").(string), d.Get("name").(string))
```

2021-11-09 17:25 UTC, stephybun commented on internal/services/batch/batch_application_data_source.go
> +	resp, err := client.Get(ctx, resourceGroup, accountName, name)
Any references to resource group, account name or name can be replaced with the values from the id
```suggestion
	resp, err := client.Get(ctx, id.ResourceGroup id.BatchAccountName, id.Name)
```

2021-11-09 17:25 UTC, stephybun commented on internal/services/batch/batch_application_data_source.go
> +			return fmt.Errorf("Error: Batch Application %q (Resource Group %q) was not found", name, resourceGroup)
When the `id` is printed it contains all of this information, so the error messages can become more succinct
```suggestion
			return fmt.Errorf("%s was not found", id)
```

2021-11-09 17:25 UTC, stephybun commented on internal/services/batch/batch_application_data_source.go
> +		return fmt.Errorf("making Read request on AzureRM Batch Application %q (Account Name %q / dataSource Group %q): %+v", name, accountName, resourceGroup, err)
```suggestion
		return fmt.Errorf("reading %s: %+v", id, err)
```

2021-11-09 17:25 UTC, stephybun commented on internal/services/batch/batch_application_data_source.go
> +	d.SetId(*resp.ID)
We'll set the id here with the one from the parser.
```suggestion
	d.SetId(id.ID())
```

2021-11-09 17:25 UTC, stephybun commented on website/docs/d/batch_application.html.markdown
> +* `resource_group_name` - The Name of the Resource Group where this Batch account exists.
```suggestion
* `resource_group_name` - The name of the Resource Group where this Batch account exists.
```

2021-11-09 20:42 UTC, oWretch commented
Thanks @stephybun for the great suggestions. I see more work ahead to take those and back-port them to the existing definitions in the batch service definitions :)

2021-11-10 14:46 UTC, stephybun commented
Thanks @oWretch, LGTM 👍🏼

2021-11-10 14:46 UTC, stephybun approved these changes

2021-11-10 14:53 UTC, merged