`azurerm_storage_account` - add supports of `{table|queue}_encryption_key_type`
hashicorp/terraform-provider-azurerm pull request #14080
Opened 2021-11-08 06:54 UTC by magodo

Fixes #13999 (the issue has all the details)

## Test

```shell
terraform-provider-azurerm on  storage_account_encryption_key_type via 🐹 v1.17.3 took 11s                                             
💤 TF_ACC=1 go test -timeout=3h -v ./internal/services/storage -run='TestAccStorageAccount_encryptionKeyType'
=== RUN   TestAccStorageAccount_encryptionKeyType
=== PAUSE TestAccStorageAccount_encryptionKeyType                                                                                       
=== CONT  TestAccStorageAccount_encryptionKeyType                                                                                                                                                                                                                               
--- PASS: TestAccStorageAccount_encryptionKeyType (174.58s)                                                                             
PASS                                                                                                                                    
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/storage       174.605s
```

2021-11-08 10:11 UTC, sambyng-msft commented
Thanks for implementing this! 

Looks good. For my knowledge, why have you not updated the following?

- storage_account_resource: UPDATE operations with a check for whether the field has changed.
- storage_account_data_source to return the new fields.

[As per the design i wrote last friday. https://github.com/hashicorp/terraform-provider-azurerm/issues/13999]

Aside from the above, can we really try to get this in for the release on Thursday this week (the 11th November)? 

My team and I need this feature as soon as possible - thanks!

2021-11-08 12:27 UTC, magodo commented
@sambyng-msft Thanks for pointing this out! I've added a new commit to include the datasource. For the update, since these properties are `ForceNew`, which means when users try to modify them, the TF will warn the users that the next apply will replace the current resource. That said, the update of these two properties is eliminated by TF itself.

2021-11-08 13:55 UTC, sambyng-msft commented
> That said, the update of these two properties is eliminated by TF itself.

Can you clarify - wouldn't this introduce a bug? 
e.g. User attempts to update the field from "Service" to "Account", expecting a new resource to be created with "Account", but then TF 'eliminates' the properties so the default "Service" is given. That's not the expected behaviour. Would we be better without any TF elimination at all or have I misunderstood?

2021-11-08 14:16 UTC, lonegunmanb commented
> > That said, the update of these two properties is eliminated by TF itself.
> 
> Can you clarify - wouldn't this introduce a bug? e.g. User attempts to update the field from "Service" to "Account", expecting a new resource to be created with "Account", but then TF 'eliminates' the properties so the default "Service" is given. That's not the expected behaviour. Would we be better without any TF elimination at all or have I misunderstood?

Hi @sambyng-msft , what @magodo means I think is, in Terraform, if a property is marked as `ForceNew`, when user modify this property, Terraform would destroy the old resource and create a new one to replace it, with latest config that user defined via Terraform code. It often happened when user want to update a property that has no way to update via API and SDK (for example the property is part of resource id).

Since there's no way to update some properties via API, and Terraform GUARANTEE the resource config in real world would be same as user defined in code, a `ForceNew` would be required to be declared on these properties.

As in this case, I think it depends on whether this property updatable via API, otherwise `ForceNew` is the best we could do for now.

2021-11-08 14:43 UTC, sambyng-msft commented
@lonegunmanb That makes sense now, thanks for clarifying. When `ForceNew` is present the ability to update these properties has effectively been 'eliminated'. 

Looks good then. 

@mbfrahry @katbyte Is there any chance that we could get this merged before Thursday?

2021-11-15 13:36 UTC, aristosvo reviewed
Just a minor comment on the docs, as changing `{table|queue}_encryption_key_type` forces recreation.

2021-11-15 13:36 UTC, aristosvo commented on website/docs/r/storage_account.html.markdown
> +
```suggestion
* `queue_encryption_key_type` - (Optional) The encryption type of the queue service. Possible values are `Service` and `Account`. Default value is `Service`. Changing this forces a new resource to be created.

* `table_encryption_key_type` - (Optional) The encryption type of the table service. Possible values are `Service` and `Account`. Default value is `Service`. Changing this forces a new resource to be created.

```

2021-11-15 14:32 UTC, sambyng-msft commented
@magodo It looks like update to 2021-04-01 storage account requires 'storageV2' to change to 'KindStorageV2'

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v54.3.0+incompatible/services/storage/mgmt/2021-01-01/storage#Account
to
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v54.3.0+incompatible/services/storage/mgmt/2021-04-01/storage#Account

2021-11-15 15:27 UTC, aristosvo approved these changes
Looks great, thanks!

@sambyng-msft I cannot help with merging, just a community maintainer 🤷🏽‍♂️

2021-11-15 17:35 UTC, tombuildsstuff requested changes
hey @magodo 

Thanks for this PR - I've taken a look through and left a couple of comments inline but if we can fix those up then this should otherwise be good to merge 👍 

Thanks!

2021-11-15 17:35 UTC, tombuildsstuff commented on internal/services/storage/storage_account_resource.go
> +			tableEncryptionKeyType = "Service"
can we use the constants here

```suggestion
			queueEncryptionKeyType = string(storage.KeyTypeService)
			tableEncryptionKeyType = string(storage.KeyTypeService)
```

2021-11-15 17:35 UTC, tombuildsstuff commented on internal/services/storage/storage_account_data_source.go
> +			tableEncryptionKeyType = "Service"
can we use the constants here:

```suggestion
			queueEncryptionKeyType = string(storage.KeyTypeService)
			tableEncryptionKeyType = string(storage.KeyTypeService)
```

2021-11-17 15:28 UTC, stephybun approved these changes
Thanks for this PR @magodo. Apologies for the delay and LGTM! 👍🏼

2021-11-17 15:28 UTC, merged

2021-11-17 15:37 UTC, sambyng-msft commented
thanks!