[MS] Adding DNS PTR Record
hashicorp/terraform-provider-azurerm pull request #141
Opened 2017-06-28 02:31 UTC by echuvyrov

Enabling the creation of DNS PTR Record

2017-06-28 06:51 UTC, whiskeyjay commented on azurerm/resource_arm_dns_ptr_record.go
> +				Elem:     &schema.Schema{Type: schema.TypeString},
Can this contain zero records?

2017-06-28 06:51 UTC, whiskeyjay commented on azurerm/resource_arm_dns_ptr_record.go
> +func resourceArmDnsPtrRecordCreate(d *schema.ResourceData, meta interface{}) error {
resourceArmDnsPtrRecordCreateOrUpdate

2017-06-28 06:51 UTC, whiskeyjay commented on azurerm/resource_arm_dns_ptr_record.go
> +	_, err := dnsClient.CreateOrUpdate(resGroup, zoneName, name, dns.PTR, parameters, "", "")
It is not obvious what the last two parameters are and why are they empty strings.

2017-06-28 06:51 UTC, whiskeyjay commented on azurerm/resource_arm_dns_ptr_record.go
> +	rec, err := dnsClient.Get(resGroup, zoneName, name, dns.PTR)
I believe the dnsClient.CreateOrUpdate method's "response" return value already contains the resource ID, there is no need to call Get just to retrieve the ID value.

```
rec, err := dnsClient.CreateOrUpdate(...)

if err != nil {
    return err
}
d.SetId(*rec.ID)
```

2017-06-28 07:51 UTC, tombuildsstuff requested changes
Hey @echuvyrov 

Thanks for this PR - I've taken a look and left some comments in-line - but this is looking good!

Thanks!

2017-06-28 07:51 UTC, tombuildsstuff commented on azurerm/provider.go
> +			//PTR record uses Azure Go SDK
_minor_: can we move this sorted alphabetically under the Azure SDK for Go comment?

2017-06-28 07:51 UTC, tombuildsstuff commented on azurerm/resource_arm_dns_ptr_record.go
> +	recordStrings := d.Get("records").(*schema.Set).List()
we'd generally tend to pull this out into a separate function - could we update this to match?

2017-06-28 07:51 UTC, tombuildsstuff commented on azurerm/resource_arm_dns_ptr_record.go
> +		return fmt.Errorf("Error reading DNS PTR record %s: %s", name, err)
this last one should be `%+v` as it's an error

2017-06-28 07:51 UTC, tombuildsstuff commented on azurerm/resource_arm_dns_ptr_record.go
> +	if resp.PtrRecords != nil {
we'd generally pull this out into a Flatten method - could we update this to match?

2017-06-28 07:51 UTC, tombuildsstuff commented on azurerm/resource_arm_dns_ptr_record_test.go
> +	config := fmt.Sprintf(testAccAzureRMDnsPtrRecord_basic, ri, ri, ri)
could we switch this to match the newer resources by making this a function which returns a formatted string?

2017-06-28 07:51 UTC, tombuildsstuff commented on azurerm/resource_arm_dns_ptr_record_test.go
> +	postConfig := fmt.Sprintf(testAccAzureRMDnsPtrRecord_updateRecords, ri, ri, ri)
(same here)

2017-06-28 07:51 UTC, tombuildsstuff commented on azurerm/resource_arm_dns_ptr_record_test.go
> +	postConfig := fmt.Sprintf(testAccAzureRMDnsPtrRecord_withTagsUpdate, ri, ri, ri)
(same here)

2017-06-28 07:51 UTC, tombuildsstuff commented on azurerm/resource_arm_dns_ptr_record_test.go
> +						"azurerm_dns_ptr_record.test", "tags.%", "2"),
do we want to check the ordering of the values here?

2017-06-28 07:51 UTC, tombuildsstuff commented on azurerm/resource_arm_dns_ptr_record_test.go
> +			return fmt.Errorf("Bad: Get PTR RecordSet: %s", err)
this needs to be `%+v`

2017-06-28 08:07 UTC, tombuildsstuff commented on website/docs/r/dns_ptr_record.html.markdown
> +# azurerm\_dns\_a\_record
*`ptr`

2017-06-29 21:56 UTC, echuvyrov commented on azurerm/resource_arm_dns_ptr_record.go
> +				Elem:     &schema.Schema{Type: schema.TypeString},
It cannot, it would be invalid

2017-06-29 21:56 UTC, echuvyrov commented on azurerm/resource_arm_dns_ptr_record.go
> +func resourceArmDnsPtrRecordCreate(d *schema.ResourceData, meta interface{}) error {
changed

2017-06-29 21:56 UTC, echuvyrov commented on azurerm/resource_arm_dns_ptr_record.go
> +	_, err := dnsClient.CreateOrUpdate(resGroup, zoneName, name, dns.PTR, parameters, "", "")
good catch, changed second-to-last parameter to properly be the eTag of the record and added comments explaining why the last parameter is empty

2017-06-29 21:56 UTC, echuvyrov commented on azurerm/resource_arm_dns_ptr_record.go
> +	rec, err := dnsClient.Get(resGroup, zoneName, name, dns.PTR)
good catch, changed

2017-06-29 21:56 UTC, echuvyrov commented on azurerm/provider.go
> +			//PTR record uses Azure Go SDK
done

2017-06-29 21:56 UTC, echuvyrov commented on azurerm/resource_arm_dns_ptr_record.go
> +	recordStrings := d.Get("records").(*schema.Set).List()
changed

2017-06-29 21:56 UTC, echuvyrov commented on azurerm/resource_arm_dns_ptr_record.go
> +		return fmt.Errorf("Error reading DNS PTR record %s: %s", name, err)
changed, thanks for catching that!

2017-06-29 21:56 UTC, echuvyrov commented on azurerm/resource_arm_dns_ptr_record.go
> +	if resp.PtrRecords != nil {
changed

2017-06-29 21:56 UTC, echuvyrov commented on azurerm/resource_arm_dns_ptr_record_test.go
> +	config := fmt.Sprintf(testAccAzureRMDnsPtrRecord_basic, ri, ri, ri)
changed

2017-06-29 21:56 UTC, echuvyrov commented on azurerm/resource_arm_dns_ptr_record_test.go
> +	postConfig := fmt.Sprintf(testAccAzureRMDnsPtrRecord_updateRecords, ri, ri, ri)
changed

2017-06-29 21:56 UTC, echuvyrov commented on azurerm/resource_arm_dns_ptr_record_test.go
> +	postConfig := fmt.Sprintf(testAccAzureRMDnsPtrRecord_withTagsUpdate, ri, ri, ri)
changed

2017-06-29 21:56 UTC, echuvyrov commented on azurerm/resource_arm_dns_ptr_record_test.go
> +						"azurerm_dns_ptr_record.test", "tags.%", "2"),
changed

2017-06-29 21:57 UTC, echuvyrov commented on azurerm/resource_arm_dns_ptr_record_test.go
> +			return fmt.Errorf("Bad: Get PTR RecordSet: %s", err)
changed

2017-06-29 21:57 UTC, echuvyrov commented on website/docs/r/dns_ptr_record.html.markdown
> +# azurerm\_dns\_a\_record
changed

2017-06-29 22:40 UTC, echuvyrov commented
@tombuildsstuff @whiskeyjay made the changes you guys suggested, thanks! The only one I wasn't sure about was about order checking in the tests - I added tag checking, lmk if you meant something else.

2017-07-03 10:03 UTC, tombuildsstuff approved these changes
Hey @echuvyrov

Thanks for pushing those updates - I've pushed a commit to resolve a couple of minor issues I noticed below (I hope you don't mind) - and this now LGTM :)

Tests pass:
```
$ TF_ACC=1 envchain azurerm go test ./azurerm -v -timeout 120m -run TestAccAzureRMDns
=== RUN   TestAccAzureRMDnsARecord_importBasic
--- PASS: TestAccAzureRMDnsARecord_importBasic (106.92s)
=== RUN   TestAccAzureRMDnsAAAARecord_importBasic
--- PASS: TestAccAzureRMDnsAAAARecord_importBasic (92.47s)
=== RUN   TestAccAzureRMDnsCNameRecord_importBasic
--- PASS: TestAccAzureRMDnsCNameRecord_importBasic (92.02s)
=== RUN   TestAccAzureRMDnsMxRecord_importBasic
--- PASS: TestAccAzureRMDnsMxRecord_importBasic (91.66s)
=== RUN   TestAccAzureRMDnsNsRecord_importBasic
--- PASS: TestAccAzureRMDnsNsRecord_importBasic (92.20s)
=== RUN   TestAccAzureRMDnsPtrRecord_importBasic
--- PASS: TestAccAzureRMDnsPtrRecord_importBasic (74.45s)
=== RUN   TestAccAzureRMDnsSrvRecord_importBasic
--- PASS: TestAccAzureRMDnsSrvRecord_importBasic (94.21s)
=== RUN   TestAccAzureRMDnsTxtRecord_importBasic
--- PASS: TestAccAzureRMDnsTxtRecord_importBasic (93.43s)
=== RUN   TestAccAzureRMDnsZone_importBasic
--- PASS: TestAccAzureRMDnsZone_importBasic (89.80s)
=== RUN   TestAccAzureRMDnsARecord_basic
--- PASS: TestAccAzureRMDnsARecord_basic (88.74s)
=== RUN   TestAccAzureRMDnsARecord_updateRecords
--- PASS: TestAccAzureRMDnsARecord_updateRecords (91.76s)
=== RUN   TestAccAzureRMDnsARecord_withTags
--- PASS: TestAccAzureRMDnsARecord_withTags (103.81s)
=== RUN   TestAccAzureRMDnsAAAARecord_basic
--- PASS: TestAccAzureRMDnsAAAARecord_basic (78.32s)
=== RUN   TestAccAzureRMDnsAAAARecord_updateRecords
--- PASS: TestAccAzureRMDnsAAAARecord_updateRecords (106.47s)
=== RUN   TestAccAzureRMDnsAAAARecord_withTags
--- PASS: TestAccAzureRMDnsAAAARecord_withTags (110.22s)
=== RUN   TestAccAzureRMDnsCNameRecord_basic
--- PASS: TestAccAzureRMDnsCNameRecord_basic (89.36s)
=== RUN   TestAccAzureRMDnsCNameRecord_subdomain
--- PASS: TestAccAzureRMDnsCNameRecord_subdomain (95.82s)
=== RUN   TestAccAzureRMDnsCNameRecord_updateRecords
--- PASS: TestAccAzureRMDnsCNameRecord_updateRecords (94.08s)
=== RUN   TestAccAzureRMDnsCNameRecord_withTags
--- PASS: TestAccAzureRMDnsCNameRecord_withTags (108.93s)
=== RUN   TestAccAzureRMDnsMxRecord_basic
--- PASS: TestAccAzureRMDnsMxRecord_basic (74.31s)
=== RUN   TestAccAzureRMDnsMxRecord_updateRecords
--- PASS: TestAccAzureRMDnsMxRecord_updateRecords (106.70s)
=== RUN   TestAccAzureRMDnsMxRecord_withTags
--- PASS: TestAccAzureRMDnsMxRecord_withTags (136.45s)
=== RUN   TestAccAzureRMDnsNsRecord_basic
--- PASS: TestAccAzureRMDnsNsRecord_basic (91.50s)
=== RUN   TestAccAzureRMDnsNsRecord_updateRecords
--- PASS: TestAccAzureRMDnsNsRecord_updateRecords (145.28s)
=== RUN   TestAccAzureRMDnsNsRecord_withTags
--- PASS: TestAccAzureRMDnsNsRecord_withTags (106.33s)
=== RUN   TestAccAzureRMDnsPtrRecord_basic
--- PASS: TestAccAzureRMDnsPtrRecord_basic (82.45s)
=== RUN   TestAccAzureRMDnsPtrRecord_updateRecords
--- PASS: TestAccAzureRMDnsPtrRecord_updateRecords (125.35s)
=== RUN   TestAccAzureRMDnsPtrRecord_withTags
--- PASS: TestAccAzureRMDnsPtrRecord_withTags (89.33s)
=== RUN   TestAccAzureRMDnsSrvRecord_basic
--- PASS: TestAccAzureRMDnsSrvRecord_basic (70.97s)
=== RUN   TestAccAzureRMDnsSrvRecord_updateRecords
--- PASS: TestAccAzureRMDnsSrvRecord_updateRecords (103.76s)
=== RUN   TestAccAzureRMDnsSrvRecord_withTags
--- PASS: TestAccAzureRMDnsSrvRecord_withTags (89.54s)
=== RUN   TestAccAzureRMDnsTxtRecord_basic
--- PASS: TestAccAzureRMDnsTxtRecord_basic (73.52s)
=== RUN   TestAccAzureRMDnsTxtRecord_updateRecords
--- PASS: TestAccAzureRMDnsTxtRecord_updateRecords (101.40s)
=== RUN   TestAccAzureRMDnsTxtRecord_withTags
--- PASS: TestAccAzureRMDnsTxtRecord_withTags (104.44s)
=== RUN   TestAccAzureRMDnsZone_basic
--- PASS: TestAccAzureRMDnsZone_basic (85.98s)
=== RUN   TestAccAzureRMDnsZone_withTags
--- PASS: TestAccAzureRMDnsZone_withTags (99.68s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	3481.650s
```

Thanks!

2017-07-03 10:05 UTC, merged