New resource for Service Fabric Managed Clusters service
hashicorp/terraform-provider-azurerm pull request #14131
Opened 2021-11-10 15:59 UTC by koikonom

2021-11-15 18:02 UTC, koikonom commented
![image](https://user-images.githubusercontent.com/158027/141831588-b9512b29-294f-40cf-b19c-a5932d0f0929.png)

2021-11-19 15:59 UTC, katbyte requested changes
Thanks @koikonom - overall looks good and I've let some comments inline

2021-11-19 15:59 UTC, katbyte commented on website/docs/r/service_fabric_managed_cluster.html.markdown
> +* `backup_restore_service` - (Optional) If true, backup service is enabled.
this is not very clear from the name, should we make it
```suggestion
* `backup_and_restore_service_enabled` - (Optional) If true, backup service is enabled.
```

or even
```suggestion
* `backup_service_enabled` - (Optional) If true, backup service is enabled.
```

2021-11-19 15:59 UTC, katbyte commented on website/docs/r/service_fabric_managed_cluster.html.markdown
> +A `custom_fabric_setting` block supports the following:
setting seems redundant
```suggestion
A `custom_fabric` block supports the following:
```

2021-11-19 15:59 UTC, katbyte commented on website/docs/r/service_fabric_managed_cluster.html.markdown
> +* `data_disk_size` - (Required) The size of the data disk in gigabytes..
would this be better as 
```suggestion
* `data_disk_size_gb` - (Required) The size of the data disk in gigabytes..
```

2021-11-19 15:59 UTC, katbyte commented on internal/services/servicefabricmanaged/service_fabric_managed_cluster_resource.go
> +		"dns_service": {
```suggestion
		"dns_service_enabled": {
```

2021-11-19 15:59 UTC, katbyte commented on internal/services/servicefabricmanaged/service_fabric_managed_cluster_resource.go
> +					"parameter": {
I almost feel like this should be 
```suggestion
		"custom_fabric_parameter": {
			Type:     pluginsdk.TypeList,
			Optional: true,
			Elem: &pluginsdk.Resource{
				Schema: map[string]*pluginsdk.Schema{
					"name": {
```

🤔  - WDYT?

2021-11-19 15:59 UTC, katbyte commented on internal/services/servicefabricmanaged/service_fabric_managed_cluster_resource.go
> +
```suggestion
```

2021-11-19 15:59 UTC, katbyte commented on website/docs/r/service_fabric_managed_cluster.html.markdown
> +* `multiple_placement_groups` - (Optional) If set the node type can be composed of multiple placement groups.
```suggestion
* `multiple_placement_groups_enabled` - (Optional) If set the node type can be composed of multiple placement groups.
```

2021-11-19 19:42 UTC, koikonom commented
(rebased to resolve conflicts)

2021-11-19 20:34 UTC, merged