Changing Postgres instance type from Default to Replica forces a new resource to be created
hashicorp/terraform-provider-azurerm pull request #14351
Opened 2021-11-25 19:11 UTC by sheffsky

According to the [Microsoft documentation](https://docs.microsoft.com/en-us/azure/postgresql/concepts-read-replicas)
> The standalone server can't be made into a replica again.

So changing instance type from Default to Replica should lead to resource re-creation.

2021-11-25 19:31 UTC, tombuildsstuff requested changes
hey @sheffsky 

Thanks for this PR - taking a look through here whilst on the whole this looks pretty good we need to cast these to strings since these are coming from the Plugin SDK as string values rather than the `postgresql.CreateMode` type - but if we can fix those up and the tests pass then we should be able to take another look.

Thanks!

2021-11-25 19:31 UTC, tombuildsstuff commented on internal/services/postgres/postgresql_server_resource.go
> +				newMode := new.(postgresql.CreateMode)
these'll need to be:

```suggestion
				oldMode := postgresql.CreateMode(old.(string))
				newMode := postgresql.CreateMode(new.(string))
```

2021-11-25 19:45 UTC, sheffsky commented
Hey @tombuildsstuff 
Thanks for the review! I've pushed the proposed changes.

2021-11-26 01:34 UTC, katbyte approved these changes
Thanks @sheffsky - LGTM 🏗️

2021-11-26 01:35 UTC, merged