update spring cloud sdk version
hashicorp/terraform-provider-azurerm pull request #14365
Opened 2021-11-29 05:07 UTC by ms-henglu

2021-12-10 22:52 UTC, tombuildsstuff requested changes
hi @ms-henglu

Thanks for this PR.

I've taken a look through and spotted what appears to be a breaking change with the discriminator here, as such I believe there's additional code changes required for this to work?

Thanks!

2021-12-13 01:53 UTC, ms-henglu commented on vendor/github.com/Azure/azure-sdk-for-go/services/preview/appplatform/mgmt/2021-09-01-preview/appplatform/models.go
> +	Properties BasicCertificateProperties `json:"properties,omitempty"`
Yes, I also made changes to certificate resource to adopt this change.

2021-12-20 02:03 UTC, ms-henglu commented
Hi @tombuildsstuff , would you please take another look? thanks!

2021-12-20 12:16 UTC, tombuildsstuff commented
Rebased on top of main rather than merging main, since this is also going to conflict with #14667

2021-12-20 12:22 UTC, tombuildsstuff approved these changes
LGTM 👍

2021-12-20 14:21 UTC, tombuildsstuff commented
Tests seem fine 👍

2021-12-20 14:29 UTC, merged