Modified the docs of resource_group_policy_assignment
hashicorp/terraform-provider-azurerm pull request #14461
Opened 2021-12-03 09:37 UTC by Sheetalsingh23

Fixed #12542 Changed the incorrect code sample.

2021-12-03 09:39 UTC, Sheetalsingh23 commented
@gswallow can you please review the PR?

2021-12-03 10:27 UTC, stephybun requested changes
Thanks for this @Sheetalsingh23! Once the formatting issue caught by the website linting is fixed this can be merged.

2021-12-03 18:50 UTC, katbyte commented on website/docs/r/resource_group_policy_assignment.html.markdown
>    policy_definition_id = azurerm_policy_definition.example.id
```suggestion
  name                         = "example"
  resource_group_id  = azurerm_resource_group.example.id
  policy_definition_id = azurerm_policy_definition.example.id
```

2021-12-06 12:50 UTC, stephybun approved these changes
LGTM 👍🏼

2021-12-06 12:50 UTC, merged