Migrate APIM to `sku` block, and add zones and public IP support
hashicorp/terraform-provider-azurerm pull request #14660
Opened 2021-12-20 05:07 UTC by oWretch

This PR adds the functionality released in the 2021-08-01 API update to the core API Management resources.

Resolves #12021, #13445

2022-01-05 00:21 UTC, lrsvendsen commented
Any updates on this PR? The added functionality is is really needed.

2022-01-05 15:42 UTC, katbyte commented
Thanks for the pr @oWretch - however we try to use `sku_name` instead of a sku block unless absolutely necessary. Could we undo that change? and add capacity as a top level property? thanks!

2022-01-05 19:08 UTC, oWretch commented
Thanks @katbyte & @tombuildsstuff. I’m happy revert that change if required. 

My reason for making the change was to keep consistency through the main and additional locations. It is now supported to run a different capacity for the main location and for the individual additional locations. I added the `capacity` property to the `additional_location` block and then moved to the `sku` block so we could have a separate `capacity` property there which then resembled the same property in the additional location configuration.

Let me know which way you prefer me to go.

2022-01-10 12:38 UTC, lrsvendsen commented
Sorry for being annoying. Any chance to get it into 2.92?

@oWretch - Thanks for the good work!

2022-01-10 18:30 UTC, katbyte commented
@oWretch - i think what we can do is keep the original `sku_name` property and then have a capacity in the additional location block that overrides the default set by the sku name?

2022-01-10 21:30 UTC, oWretch commented
> @oWretch - i think what we can do is keep the original `sku_name` property and then have a capacity in the additional location block that overrides the default set by the sku name?

@katbyte will do. Won’t be for a couple of weeks as I have limited connectivity for the moment.

2022-01-17 09:20 UTC, Khayoann2 commented
Hello,

Any news about this PR ?

Thank you

2022-02-04 01:31 UTC, katbyte requested changes
Thanks @oWretch - overall this looks good aside from one comment about public network access, elsewhere in the provider we change it to a bool and add enabled into the name. could we match that here? 

https://github.com/hashicorp/terraform-provider-azurerm/blob/817593a715edc0f4086008c1bc2f9b7dd5d166e3/internal/services/redis/redis_cache_resource.go#L289

2022-02-04 01:31 UTC, katbyte commented on internal/services/apimanagement/api_management_resource.go
> +			"public_network_access": {
Could we change this to be a boolean and match the rest of the provider?
```suggestion
			"public_network_access_enabled": {
```

2022-02-04 19:31 UTC, katbyte commented
Hope you don't mind @oWretch  but i've pushed that change to get this merged today

2022-02-04 19:33 UTC, mbfrahry approved these changes
LGTM

2022-02-04 19:47 UTC, katbyte commented on internal/services/apimanagement/api_management_resource.go
> +	"github.com/hashicorp/terraform-provider-azurerm/internal/services/cognitive/sdk/2021-04-30/cognitiveservicesaccounts"
```suggestion
```

2022-02-04 21:48 UTC, oWretch commented
> Hope you don't mind @oWretch but i've pushed that change to get this merged today

I don’t mind at all. Thanks for your help to get this committed

2022-02-08 19:45 UTC, merged