New datasource: `azurerm_sql_managed_instance`
hashicorp/terraform-provider-azurerm pull request #14739
Opened 2021-12-28 12:51 UTC by favoretti

TODO:
- [ ] Docs

Fixes #14729

2021-12-31 03:23 UTC, saradaathavale commented
Hi Favoretti,
         Thank you for looking into this. What is the ETA on this feature? And please passon the terraform release number once it is available

2022-01-02 03:43 UTC, katbyte commented
have a test failure:

```
=== RUN   TestAccDataSourceSqlManagedInstance_basic
=== PAUSE TestAccDataSourceSqlManagedInstance_basic
=== CONT  TestAccDataSourceSqlManagedInstance_basic
    testcase.go:110: Step 1/1 error: Error running apply: exit status 1
        
        Error: parsing Azure ID: parse "": empty url
        
          with data.azurerm_sql_managed_instance.test,
          on terraform_plugin_test.tf line 1223, in data "azurerm_sql_managed_instance" "test":
        1223: data "azurerm_sql_managed_instance" "test" {
        
--- FAIL: TestAccDataSourceSqlManagedInstance_basic (19566.37s)
FAIL
```

2022-01-02 12:02 UTC, favoretti commented
@katbyte fixed that in the last commits. Hopelessly retrying now.

2022-01-05 07:45 UTC, favoretti commented
Aside of TC failing, here's a manual test:
```
[8:42](⎈ |eastus2-fxs-racer-prod-main:ingress-controller)➜  ~/terraform-tests git:(kusto) ✗ $ terraform output
sql = {
  "administrator_login" = "vlad"
  "collation" = "SQL_Latin1_General_CP1_CI_AS"
  "dns_zone_partner_id" = tostring(null)
  "fqdn" = "vladtestsqlmi.9e09f65e817f.database.windows.net"
  "id" = "/subscriptions/xxx/resourceGroups/vlad-test/providers/Microsoft.Sql/managedInstances/vladtestsqlmi"
  "identity" = tolist([
    {
      "principal_id" = "aad82945-67bd-4cc0-b021-049ae22987ff"
      "tenant_id" = "b945c813-dce6-41f8-8457-5a12c2fe15bf"
      "type" = "SystemAssigned"
    },
  ])
  "license_type" = "LicenseIncluded"
  "location" = "eastus2"
  "minimum_tls_version" = "1.2"
  "name" = "vladtestsqlmi"
  "proxy_override" = "Proxy"
  "public_data_endpoint_enabled" = false
  "resource_group_name" = "vlad-test"
  "sku_name" = "GP_Gen5"
  "storage_account_type" = "GRS"
  "storage_size_in_gb" = 256
  "subnet_id" = "/subscriptions/xxx/resourceGroups/vlad-test/providers/Microsoft.Network/virtualNetworks/vnet-vladtestsqlmi/subnets/ManagedInstance"
  "tags" = tomap({})
  "timeouts" = null /* object */
  "timezone_id" = "UTC"
  "vcores" = 8
}
```

TF code:

```
[8:42](⎈ |eastus2-fxs-racer-prod-main:ingress-controller)➜  ~/terraform-tests git:(kusto) ✗ $ cat sql.tf
data "azurerm_sql_managed_instance" "test" {
  name                = "vladtestsqlmi"
  resource_group_name = "vlad-test"
}
```

![image](https://user-images.githubusercontent.com/805046/148179447-714acdb2-9fc0-4fb3-a897-ccf1ec5b0255.png)

2022-01-05 09:20 UTC, tombuildsstuff requested changes
hey @favoretti 

Thanks for this PR - I've left a few comments inline but this otherwise LGTM 👍 

Thanks!

2022-01-05 09:20 UTC, tombuildsstuff commented on internal/services/sql/sql_managed_instance_data_source.go
> +			"identity": managedInstanceIdentity{}.Schema(),
this'll need to be different for the data source, since the resource one allows this to be configured (when this should be computed-only here)

2022-01-05 09:20 UTC, tombuildsstuff commented on website/docs/d/sql_managed_instance.html.markdown
> +Use this data source to access information about an existing SQL Azure Managed Instance.
```suggestion
Use this data source to access information about an existing SQL Managed Instance.
```

2022-01-05 09:20 UTC, tombuildsstuff commented on website/docs/d/sql_managed_instance.html.markdown
> +  Gets information about a SQL Azure Managed Instance.
```suggestion
  Gets information about a SQL Managed Instance.
```

2022-01-05 09:20 UTC, tombuildsstuff commented on website/docs/d/sql_managed_instance.html.markdown
> +* `resource_group_name` - (Required) The name of the resource group in which to create the SQL Server.
```suggestion
* `resource_group_name` - (Required) The name of the Resource Group in which the SQL Managed Instance exists.
```

2022-01-05 09:20 UTC, tombuildsstuff commented on website/docs/d/sql_managed_instance.html.markdown
> +* `name` - (Required) The name of the SQL Managed Instance. This needs to be globally unique within Azure.
```suggestion
* `name` - (Required) The name of the SQL Managed Instance.
```

2022-01-05 09:20 UTC, tombuildsstuff commented on website/docs/d/sql_managed_instance.html.markdown
> +* `tags` - A mapping of tags to assign to the resource.
```suggestion
* `tags` - A mapping of tags assigned to the resource.
```

2022-01-05 09:20 UTC, tombuildsstuff commented on internal/services/sql/sql_managed_instance_data_source.go
> +			return nil
a Data Source should raise an error when these aren't found:

```suggestion
			return fmt.Errorf("%s was not found", id)
```

2022-01-05 12:26 UTC, tombuildsstuff approved these changes
LGTM - thanks for this @favoretti

2022-01-05 12:30 UTC, merged