`d/azurerm_virtual_machine_scale_set`: Add scale set instances details
hashicorp/terraform-provider-azurerm pull request #14754
Opened 2021-12-30 17:52 UTC by mouellet

### Summary

Outputs the list of virtual machine instance currently in the scale set w/ details including private/public ip adresses, computer name, etc. Useful when using auto scaling...

Supersede #14744 

### Acceptance tests
```
make acctests SERVICE='compute' TESTARGS='-run=TestAccDataSourceVirtualMachineScaleSet_basicLinux' TESTTIMEOUT='10m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/compute -run=TestAccDataSourceVirtualMachineScaleSet_basicLinux -timeout 10m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccDataSourceVirtualMachineScaleSet_basicLinux
=== PAUSE TestAccDataSourceVirtualMachineScaleSet_basicLinux
=== CONT  TestAccDataSourceVirtualMachineScaleSet_basicLinux
--- PASS: TestAccDataSourceVirtualMachineScaleSet_basicLinux (245.95s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/compute	247.273s
```

2022-06-29 16:30 UTC, tombuildsstuff requested changes
hey @mouellet

Apologies for the delayed review on this one - we've been trying to work out how to proceed here. Having chatted about this internally we think this is fine and have left some comments inline, if you can fix those up then we should be able to take another look and get this merged 👍 

Thanks!

2022-06-29 16:30 UTC, tombuildsstuff commented on internal/services/compute/virtual_machine_scale_set_data_source.go
> +	}
```suggestion
	d.Set("location", location.Normalize(resp.Location))
```

2022-07-01 15:45 UTC, mouellet commented on internal/services/compute/virtual_machine_scale_set_data_source.go
> +		nics, err := networkInterfacesClient.ListVirtualMachineScaleSetVMNetworkInterfacesComplete(ctx, resGroup, name, *instance.InstanceID)
I've added a nil check here! However, I couldn't find any underlying properties (even when adding the expand w/ instanceView parameter) that hold this attribute in the client or documentation (see: https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-set-vms/list).

2022-07-01 16:00 UTC, mouellet commented
Hi @tombuildsstuff, Thanks for the review! I've rebased and pushed the changes you suggested.. Let me know if there's anything else I can do!

2022-08-18 22:39 UTC, katbyte approved these changes
Thanks @mouellet - LGTM ♻️

2022-08-18 22:39 UTC, merged