Added infrastructure_encryption to azurerm_storage_account
hashicorp/terraform-provider-azurerm pull request #14864
Opened 2022-01-09 14:44 UTC by scottambroseio

Resolves https://github.com/hashicorp/terraform-provider-azurerm/issues/8816

I've run the new tests in my own subscription and they pass 👍

2022-01-12 03:21 UTC, katbyte requested changes
We have a test failure here:
```
------- Stdout: -------
=== RUN   TestAccStorageAccount_storageV1ToV2Update
=== PAUSE TestAccStorageAccount_storageV1ToV2Update
=== CONT  TestAccStorageAccount_storageV1ToV2Update
    testcase.go:110: Step 1/4 error: Error running apply: exit status 1
        
        Error: creating Azure Storage Account "unlikely23exst2acctm4xeb": storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="FeatureNotSupportedForAccount" Message="Infrastructure encryption is not supported for the account."
        
          with azurerm_storage_account.test,
          on terraform_plugin_test.tf line 11, in resource "azurerm_storage_account" "test":
          11: resource "azurerm_storage_account" "test" {
        
--- FAIL: TestAccStorageAccount_storageV1ToV2Update (124.02s)
FAIL
```

2022-01-12 15:21 UTC, scottambroseio commented
Thanks for letting me know. I ran the new tests I added but not the existing ones 🤦 . This time I ran all the TestAccStorageAccount prefixed tests and they all seem happy 👍 .

2022-01-12 21:02 UTC, katbyte commented on internal/services/storage/storage_account_resource.go
> +	}
we should probably return an error if the user is trying to set this with v1?

2022-01-12 21:03 UTC, katbyte commented
no worries @scottambroseio! tests pass now thou we should probably return an error if the user tried to set this with v1 accounts?

2022-01-13 22:35 UTC, katbyte approved these changes
Thanks @scottambroseio - LGTM now 🏗️ 

However you did commit your test.sh file 😅 so you definitely want to rotate your secrets ASAP!!

2022-01-13 22:36 UTC, merged

2022-01-13 23:10 UTC, katbyte commented
added enabled to the property name in #14956