`r\VirtualMachine`: Add support for `dedicated_host_group_id`
hashicorp/terraform-provider-azurerm pull request #14936
Opened 2022-01-13 08:10 UTC by myc2h6o

- Implement [Host Group Automatic Placement](https://docs.microsoft.com/en-us/azure/virtual-machines/dedicated-hosts#manual-vs-automatic-placement)
- The new property `dedicated_host_group_id` is similar to `dedicated_host_id`, it puts the VM on a Host Group instead, the Host Group needs to have automatic placement enabled.
- Minor fix for a test case config `func (r WindowsVirtualMachineResource) scalingDedicatedHostRemoved` which didn't remove the `dedicated_host_id`

2022-01-17 12:57 UTC, tombuildsstuff requested changes
hi @myc2h6o 

Thanks for this PR - I've taken a look through and left a couple of comments inline, if we can fix those up then we should be able to take another look 👍 

Thanks!

2022-01-17 12:57 UTC, tombuildsstuff commented on website/docs/r/linux_virtual_machine.html.markdown
> +* `dedicated_host_group_id` - (Optional) The ID of a Dedicated Host Group where this machine should be run on. The target Host Group must have automatic placement enabled. Conflicts with `dedicated_h
```suggestion
* `dedicated_host_group_id` - (Optional) The ID of a Dedicated Host Group that this Linux Virtual Machine should be run within. Conflicts with `dedicated_host_id`.

-> **Note:** The Dedicated Host Group must have automatic placement enabled.
```

2022-01-17 12:57 UTC, tombuildsstuff commented on website/docs/r/windows_virtual_machine.html.markdown
> +* `dedicated_host_group_id` - (Optional) The ID of a Dedicated Host Group where this machine should be run on. The target Host Group must have automatic placement enabled. Conflicts with `dedicated_h
```suggestion
* `dedicated_host_group_id` - (Optional) The ID of a Dedicated Host Group that this Windows Virtual Machine should be run within. Conflicts with `dedicated_host_id`.

-> **Note:** The Dedicated Host Group must have automatic placement enabled.
```

2022-01-18 03:50 UTC, myc2h6o commented on website/docs/r/linux_virtual_machine.html.markdown
> +* `dedicated_host_group_id` - (Optional) The ID of a Dedicated Host Group where this machine should be run on. The target Host Group must have automatic placement enabled. Conflicts with `dedicated_h
Updated

2022-01-18 03:51 UTC, myc2h6o commented on website/docs/r/windows_virtual_machine.html.markdown
> +* `dedicated_host_group_id` - (Optional) The ID of a Dedicated Host Group where this machine should be run on. The target Host Group must have automatic placement enabled. Conflicts with `dedicated_h
Updated

2022-01-18 03:51 UTC, myc2h6o commented
Hi @tombuildsstuff I've fixed the comment, please take a look

2022-02-02 22:18 UTC, katbyte approved these changes
Thanks @myc2h6o - LGTM 🏗️

2022-02-02 22:18 UTC, merged