Support for azurerm_container_group data source
hashicorp/terraform-provider-azurerm pull request #14946
Opened 2022-01-13 13:15 UTC by logineimer

Fixes #14945. Let me know if there's something missing.

2022-01-13 23:06 UTC, katbyte requested changes
Have a test failure @logineimer 
```
------- Stdout: -------
=== RUN   TestAccDataSourceAzureRMContainerGroup_basic
=== PAUSE TestAccDataSourceAzureRMContainerGroup_basic
=== CONT  TestAccDataSourceAzureRMContainerGroup_basic
    testcase.go:110: Step 1/1 error: Check failed: Check 5/5 error: data.azurerm_container_group.test: Attribute 'fqdn' expected to be set
--- FAIL: TestAccDataSourceAzureRMContainerGroup_basic (98.88s)
FAIL
```

2022-01-14 08:55 UTC, logineimer commented
Yeah my bad, the dns_label_name was missing in the test ressources. This led to the fqdn being an empty string. Now it should work.

2022-01-15 03:04 UTC, katbyte commented
Tests pass now, but linting needs fixing - `make terrafmt` should fix that up

2022-01-15 20:48 UTC, logineimer commented
I fixed the linting error. Looking forward to merge. :)

2022-01-27 09:22 UTC, stephybun commented on internal/services/containers/container_group_data_source.go
> +	resp, err := client.Get(ctx, resourceGroup, name)
We should generate the container group ID like we do in the resource
```suggestion
	id := parse.NewContainerGroupID(subscriptionId, d.Get("resource_group_name").(string), d.Get("name").(string))

	resp, err := client.Get(ctx, id.ResourceGroup, id.Name)
```

2022-01-27 09:25 UTC, stephybun commented on internal/services/containers/container_group_data_source.go
> +	d.Set("resource_group_name", resourceGroup)
And here we can use the values from the id
```suggestion
	d.SetId(id.ID())
	d.Set("name", id.Name)
	d.Set("resource_group_name", id.ResourceGroup)
```

2022-01-27 09:29 UTC, stephybun commented on website/docs/d/container_group.html.markdown
> +page_title: "Azure Resource Manager: Data Source: azurerm_container_group"
```suggestion
page_title: "Azure Resource Manager: azurerm_container_group"
```

2022-02-01 22:33 UTC, logineimer commented
Thanks for the feedback! I never used Go before and oriented my solution at similar resources and data source. Would you like me to fixup the new commits now that I applied your suggestions? :)

2022-02-02 08:09 UTC, stephybun requested changes
Thanks for making those changes @logineimer! Looks like we forgot to import the parse package and initialize the `subscriptionId` needed for the parser, one those are there I can run the tests.

2022-02-02 08:09 UTC, stephybun commented on internal/services/containers/container_group_data_source.go
> +	"github.com/hashicorp/terraform-provider-azurerm/utils"
```suggestion
	"github.com/hashicorp/terraform-provider-azurerm/helpers/azure"
	"github.com/hashicorp/terraform-provider-azurerm/internal/clients"
	"github.com/hashicorp/terraform-provider-azurerm/internal/services/containers/parse"
	"github.com/hashicorp/terraform-provider-azurerm/internal/tags"
	"github.com/hashicorp/terraform-provider-azurerm/internal/tf/pluginsdk"
	"github.com/hashicorp/terraform-provider-azurerm/internal/tf/validation"
	"github.com/hashicorp/terraform-provider-azurerm/internal/timeouts"
	"github.com/hashicorp/terraform-provider-azurerm/utils"
```

2022-02-02 08:09 UTC, stephybun commented on internal/services/containers/container_group_data_source.go
> +	ctx, cancel := timeouts.ForRead(meta.(*clients.Client).StopContext, d)
```suggestion
	client := meta.(*clients.Client).Containers.GroupsClient
	subscriptionId := meta.(*clients.Client).Account.SubscriptionId
	ctx, cancel := timeouts.ForRead(meta.(*clients.Client).StopContext, d)
```

2022-02-02 18:42 UTC, logineimer commented
No problem @stephybun! Just to be sure: Do you want the commits to be squashed? :)

2022-02-03 15:53 UTC, stephybun approved these changes
Thanks @logineimer, LGTM!
Don't worry about squashing, I can do that when I merge 🚀

2022-02-03 15:56 UTC, merged