Feature: allow ZRS as storage type on rsv
hashicorp/terraform-provider-azurerm pull request #14980
Opened 2022-01-17 02:00 UTC by josh-barker

This PR:
- updates the backup api to 2021-07-01
- add zone redundant as allowed storage mode type in rsv

It might be easier to review by commit.
Also happy to split into 2 x PRs if you'd prefer.

Cheers

2022-01-17 11:56 UTC, tombuildsstuff requested changes
hey @josh-barker 

Thanks for this PR - I've taken a look through and left some comments inline but this is looking good, if we can fix those up then we should be able to take another look, run the tests and get this merged 👍 

Thanks!

2022-01-17 11:56 UTC, tombuildsstuff commented on internal/services/recoveryservices/recovery_services_vault_resource.go
> +			if resp.Properties.StorageType != storageCfg.Properties.StorageModelType {
it's possible for `resp.Properties` to be nil here:

```suggestion
			if resp.Properties == nil {
				return pluginsdk.NonRetryableError(fmt.Errorf("updating %s Storage Config: `properties` was nil"))
			}
			if resp.Properties.StorageType != storageCfg.Properties.StorageModelType {
```

2022-01-17 11:56 UTC, tombuildsstuff commented on internal/services/recoveryservices/recovery_services_vault_resource.go
> +				return pluginsdk.RetryableError(fmt.Errorf("updating Recovery Service Storage Cfg %s: %+v", id.String(), err))
the `id` is wrapped below, so we can remove this:

```suggestion
				return pluginsdk.RetryableError(fmt.Errorf("updating Storage Config: %+v", err))
```

2022-01-18 00:15 UTC, josh-barker commented
Hey @tombuildsstuff, no worries. I've addressed your feedback.

2022-02-04 01:40 UTC, katbyte approved these changes
Thanks @josh-barker - LGTM 🌳

2022-02-04 01:40 UTC, merged