Firewall rule related resources change block type from `Set` to `List`
hashicorp/terraform-provider-azurerm pull request #15008
Opened 2022-01-18 11:47 UTC by magodo

There are typically two reasons to use the set type:

1. It allows users to reorder the elements inside the array, without getting a plan diff
2. Some API will return the elements without honoring its original order, in which case we have to use the set

It turns out (#11181, #10083), the first benefit is not more valuable than a readable plan. After contacting with the Azure firewall PM that he confirms the order of rules together with the other compound properties are reserved in turns of API, this PR changes the type of those blocks from `TypeSet` to `TypeList`.

Fixes #11181, fixes #10083.

2022-01-19 01:28 UTC, magodo commented
![image](https://user-images.githubusercontent.com/7970698/150046432-c8d681a1-3ce2-4fc6-b29e-3b551852a5a2.png)

2022-01-24 09:06 UTC, jackofallops requested changes
Hi @magodo - Could you add multiple value and update test coverage that shows the schema items changed here being updated with multiple values? The tests currently only have a single value in each case, so don't confirm the changes are correct?

Thanks!

2022-01-25 06:14 UTC, magodo commented
@jackofallops I've made the single elements to multiples to cover all the changed properties. Please take another look, thanks!

2022-01-28 03:29 UTC, katbyte requested changes
Lots of test failures here:
```
------- Stdout: -------
=== RUN   TestAccFirewallApplicationRuleCollection_basic
=== PAUSE TestAccFirewallApplicationRuleCollection_basic
=== CONT  TestAccFirewallApplicationRuleCollection_basic
    testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Azure Firewall Firewall: (Azure Firewall Name "acctestfirewall220128025321388480" / Resource Group "acctestRG-fw-220128025321388480") : network.AzureFirewallsClient#Delete: Failure sending request: StatusCode=415 -- Original Error: Code="UnsupportedMediaType" Message="The content media type '<null>' is not supported. Only 'application/json' is supported."
        
--- FAIL: TestAccFirewallApplicationRuleCollection_basic (541.65s)
FAIL
```

2022-01-28 07:46 UTC, magodo commented
@katbyte That's strange, since the test result of https://github.com/hashicorp/terraform-provider-azurerm/pull/15008/commits/11e1e8ca5ec7b4b616d984536d8c3af51264913c only has two failed cases, then I submit two new commits to fix them, then it failed a lot...

2022-02-04 03:46 UTC, katbyte commented
Given the failures are consistent i think this is blocked until we get to the bottom of them:
<img width="484" alt="image" src="https://user-images.githubusercontent.com/1638467/152468544-df3db9a2-7412-401d-8a5c-f28cfc9aeb77.png">

2022-02-05 00:28 UTC, crawfs commented
> I've run some of the tests locally (by merging the main branch) and it all works well. Also the main branch for the firewall RP starts to fail since Jan.27.

Might be worth mentioning, I've noticed for our firewall deployments we are suddenly getting errors from our deployments with configuration changes to the Azure Firewall and associated rules despite no obvious change to our deployments that are causing this. We have a case open with microsoft for the issue as I suspect it may be an upstream issue by them. I don't know if it's related to the errors experienced here but I figured I'd mention it.

2022-02-16 09:02 UTC, tapaszto commented
Hi @magodo,

We are also looking forward to this fix as it would resolve our blocking issue. When do we expect this PR to be completed?

2022-02-16 10:38 UTC, magodo commented
@katbyte Can we merge this? The test failures are not related to this issue, and should have been fixed in another PR (merged).

2022-02-17 00:17 UTC, crawfs commented
> @katbyte Can we merge this? The test failures are not related to this issue, and should have been fixed in another PR (merged).

Which PR is this, just for reference?

2022-02-17 01:28 UTC, magodo commented
@crawfs https://github.com/hashicorp/terraform-provider-azurerm/pull/15330

2022-02-17 22:17 UTC, YMaestr commented
So from what I gathered, this PR would stop the deletion of rule collection blocks when creating new rules in azure firewall and azure firewall policy? Will the terraform plan also show each individual rule to be added (ie. if adding 3 new rules, terraform plan will say 'resources: 3 added')?

2022-03-22 04:24 UTC, mbfrahry approved these changes
LGTM!

2022-03-22 04:26 UTC, merged