Function app consumption plan bug
hashicorp/terraform-provider-azurerm pull request #1515
Opened 2018-07-07 20:09 UTC by ranieuwe

This PR fixes #1453 by disabling the `WEBSITE_CONTENT` app setting when a dynamic App service plan is used. All `TestAccAzureRMFunctionApp`* tests are successful. 

It is very hard to write a test for this scenario because the default app settings variables get deleted on resource read and are not transported to the terraform schema. This means it is not possible not to do a `TestCheckResourceAttr` or similar. Have manually inspected the resources and the settings are applied correctly with these fixes.

As an aside, the function app logic will need refactoring as it is fairly inefficient and not DRY. Create calls update, likely to update the app_settings, but update basically reruns the same ARM call that Create just made, slowing down the progress by approx 20 to 30 seconds. 

Because of this double logic you'll see the app service plan needing to be retrieved twice and introduced throughout. There is no cleaner way without refactoring extensively.

2018-07-09 12:40 UTC, ranieuwe commented on azurerm/resource_arm_function_app.go
> +	if strings.EqualFold(appServiceTier, "dynamic") {
You are absolute right. D'oh. Thanks for spotting this. Will fix

2018-07-11 06:00 UTC, tombuildsstuff requested changes
hey @ranieuwe 

Thanks for this PR :)

I've taken a look through and aside from the logic bug this mostly LGTM; if we can fix up the potential crash then we should be good to run the tests/get this merged

Thanks!

2018-07-11 06:00 UTC, tombuildsstuff commented on azurerm/resource_arm_function_app.go
> +	return *appServicePlan.Sku.Tier, nil
there's a crash here if `appServicePlan.Sku` or `appServicePlan.Sku.Tier` is nil (which happens for older resources); can we make this:

```
if sku := appServicePlan.Sku; sku != nil {
 if tier := sku.Tier; tier != nil {
    return *tier, nil
  }
}
return fmt.Errorf("No `sku` block was returned for App Service Plan %q (Resource Group %q)", resourceGroup, name)
```

2018-07-11 06:00 UTC, tombuildsstuff commented on azurerm/resource_arm_function_app.go
> +		return "", fmt.Errorf("[ERROR] Could not retrieve App Service Plan ID '%s': %+v", appServicePlanId, err)
_minor_ these two `'%s'` can become `%q`

2018-07-11 06:03 UTC, tombuildsstuff commented
> As an aside, the function app logic will need refactoring as it is fairly inefficient and not DRY. Create calls update, likely to update the app_settings, but update basically reruns the same ARM call that Create just made, slowing down the progress by approx 20 to 30 seconds.

Some context here: for both App Service and Function Apps the App Settings weren't persisted on the initial creation (at least when we first worked on this, there's a new API version so this may have changed) - so this was the only way to ensure the settings were actually set (and that users wouldn't see a perpetual diff)

2018-07-12 07:31 UTC, ranieuwe commented
Changes done, nil check added and logic inversed. Tests all pass.

2018-07-16 12:07 UTC, tombuildsstuff commented
hey @ranieuwe 

I hope you don't mind - but I've taken a look into this and have pushed a commit which verifies the settings aren't set at the server end :)

Thanks!

2018-07-16 12:15 UTC, tombuildsstuff approved these changes
hey @ranieuwe 

Thanks for pushing those changes - I've pushed a commit to add a test for this but this now LGTM 👍 

Thanks!

2018-07-16 12:29 UTC, tombuildsstuff commented
Tests pass:

<img width="466" alt="screenshot 2018-07-16 at 14 28 53" src="https://user-images.githubusercontent.com/666005/42758685-976daef2-8904-11e8-96fd-8837cecee1f8.png">

2018-07-16 12:29 UTC, merged