`azurerm_managed_disk` `azurerm_snapshot`: Deprecate `enabled` in `encryption_settings`
hashicorp/terraform-provider-azurerm pull request #15317
Opened 2022-02-08 09:09 UTC by myc2h6o

- Fix #14574 `enabled` can be determined according to `disk_encryption_key`, deprecating it to avoid additional settings and confusion.
- Removed `enabled` in doc.
- Added missing `encryption_settings` in `r\snapshot.html.markdown`
- `encryption_settings` now supports updating the keys, did some change in expand function signature so that it suits the Update call

2022-02-08 09:11 UTC, myc2h6o commented on internal/services/compute/encryption_settings.go
> +					Default:    true,
Set the default value to `true`, so that it fits the logic when only `disk_encryption_key` is specified and `enabled` is not specified

2022-02-08 09:15 UTC, myc2h6o commented on internal/services/compute/encryption_settings.go
> +		return &compute.EncryptionSettingsCollection{}
This is for update call, when removing the `encryption_settings` block. This will set the enabled to false and remove encryption keys

2022-02-15 03:09 UTC, myc2h6o commented
Example for Disk ADE is moved to #15356 so that example linting can pass.
Because `enabled` is changed from `Required` to `Optional`, need to wait for new release to allow the example linting to pass

2022-03-23 09:16 UTC, myc2h6o commented on internal/services/compute/managed_disk_resource.go
> +					return false
For 2.x `enabled` is `ForceNew`, so return `false`

2022-03-23 09:22 UTC, myc2h6o commented
Hi @katbyte @tombuildsstuff I've added `CustomizeDiff` and `ForceNewIfChange` to `encryption_settings` in disk and snapshot resource and move 3.0 related changes behind the 3.0 beta flag. Please take a look.

2022-03-24 03:44 UTC, myc2h6o commented
Test result with `TestAccManagedDisk_|TestAccSnapshot_ `
`TestAccManagedDisk_import` fails on main as well for missing blob `https://accsa220323034733968725.blob.core.windows.net/vhds/myosdisk1.vhd`, maybe it was deleted in the subscription or blob permission changed?
![image](https://user-images.githubusercontent.com/10579712/159837690-e9eeed3c-8d53-4ce3-87ca-9e57149b1866.png)

2022-09-02 01:54 UTC, katbyte requested changes
build failures:
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/1638467/188042192-72214d42-8e10-4f8c-a92b-d48f7d6faccd.png">

2022-09-08 07:17 UTC, myc2h6o commented on internal/services/compute/encryption_settings.go
> +						Deprecated: "Deprecated, Azure Disk Encryption is now configured directly by `disk_encryption_key` and `key_encryption_key`. To disable Azure Disk Encryption, please remove `encryption_settings
Updated

2022-09-08 07:18 UTC, myc2h6o commented
@katbyte thanks for reviewing! I've updated the deprecation message, as well as resolved the build issue after merging latest main. Please take a look

2022-09-08 10:14 UTC, myc2h6o commented
Updated test result: (`TestAccManagedDisk_import` is being fixed in #18303)
![image](https://user-images.githubusercontent.com/10579712/189097088-5cb03d18-809f-43ae-a252-f9c13592363e.png)

2022-09-26 23:25 UTC, katbyte approved these changes
Thanks @myc2h6o - LGTM 👾

2022-09-26 23:25 UTC, katbyte commented
@myc2h6o - good to go once merge conflicts are fixed

2022-09-27 05:00 UTC, myc2h6o commented
Hi @katbyte I've resolved the merge conflicts.

2022-09-27 05:23 UTC, myc2h6o commented
Test result after the update
![image](https://user-images.githubusercontent.com/10579712/192439042-fecdfda0-339e-4e8e-b104-4b428b3908da.png)

2022-10-04 03:37 UTC, merged