New Data Source: `azurerm_backup_protected_file_share`
hashicorp/terraform-provider-azurerm pull request #15367
Opened 2022-02-10 20:36 UTC by SudoSpartanDan

## Summary

Adding new Data Source `azurerm_backup_protected_file_share`.

Fixes #13216

2022-02-14 19:14 UTC, favoretti requested changes
Hi there and thank you for this PR. Left a few minor comments/suggestions inline. If we can get this patched up - this otherwise LGTM.

2022-02-15 02:06 UTC, SudoSpartanDan commented on internal/services/recoveryservices/backup_protected_file_share_data_source.go
> +			sourceResourceID := strings.Replace(*item.SourceResourceID, "Microsoft.storage", "Microsoft.Storage", 1) // The SDK is returning inconsistent capitalization
Good catch, updated

2022-02-15 02:07 UTC, SudoSpartanDan commented on website/docs/d/backup_protected_file_share.html.markdown
> +Use this data source to access information about an existing VM Backup Policy.
Good catch, updated

2022-02-16 00:24 UTC, katbyte requested changes
Have a test failure here:
```
------- Stdout: -------
=== RUN   TestAccDataSourceBackupProtectedFileShare_basic
=== PAUSE TestAccDataSourceBackupProtectedFileShare_basic
=== CONT  TestAccDataSourceBackupProtectedFileShare_basic
    testcase.go:110: Step 1/1 error: Error running apply: exit status 1
        
        Error: making Read request on Recovery Service Protected File Share "acctest-ss-220215235951921355" (Vault "acctest-VAULT-220215235951921355" Resource Group "acctestRG-backup-220215235951921355"): backup.ProtectedItemsClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BMSUserErrorProtectedItemNameIncorrectFormat" Message="Protected Item name is not in the correct format."
        
          with data.azurerm_backup_protected_file_share.test,
          on terraform_plugin_test.tf line 71, in data "azurerm_backup_protected_file_share" "test":
          71: data "azurerm_backup_protected_file_share" "test" {
        
--- FAIL: TestAccDataSourceBackupProtectedFileShare_basic (707.64s)
FAIL
```

2022-02-24 15:48 UTC, SudoSpartanDan commented
I am not able to get the tests working properly, looks like the other associated tests with this resource have been failing as well. I'm going to close this until those other acceptance tests are able to work properly.

2022-02-24 15:48 UTC, closed without merging