website: example of python function app
hashicorp/terraform-provider-azurerm pull request #15460
Opened 2022-02-16 18:31 UTC by jfreeland

I apologize in advance.  It might be that this PR does not make sense to include and is otherwise irrelevant.

I was recently exploring `azurerm_function_app`'s and spent time troubleshooting as documented in https://github.com/Azure/azure-functions-python-worker/issues/627 what was a simple miss of including `FUNCTIONS_WORKER_RUNTIME`.  While the term is mentioned in this page, having a more complete example in this page might have saved me some time; maybe it can also help others.

2022-02-24 06:36 UTC, jackofallops requested changes
Hi @jfreeland - Thanks for submitting this example for the docs. There's just a few changes in-line below.

It's worth mentioning that this resource is going to be deprecated as part of the 3.0 release, and is being superseded by [azurerm_windows_function_app](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_function_app) and [azurerm_linux_function_app](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app) which both have significant improvements around the handling of the application stacks.

Thanks again!

2022-02-24 06:36 UTC, jackofallops commented on website/docs/r/function_app.html.markdown
> +~> **Note:** Linux Function Apps will be available separately as `azurerm_linux_function_app` **as an opt-in Beta** in [the upcoming version 3.0 of the Azure Provider](https://registry.terraform.io/p
There's a deprecation notice coming for this resource as it's being superseded.
```suggestion
```

2022-02-24 06:36 UTC, jackofallops commented on website/docs/r/function_app.html.markdown
> +  name     = "azure-functions-cptest-rg"
The convention in these examples is to use `example` over `test`
```suggestion
  name     = "azure-functions-example-rg"
```

2022-02-24 06:36 UTC, jackofallops commented on website/docs/r/function_app.html.markdown
> +  name                     = "functionsapptestsa"
as above
```suggestion
  name                     = "functionsappexamlpesa"
```

2022-02-24 06:36 UTC, jackofallops commented on website/docs/r/function_app.html.markdown
> +  name                = "azure-functions-test-service-plan"
as above
```suggestion
  name                = "azure-functions-example-sp"
```

2022-02-24 06:36 UTC, jackofallops commented on website/docs/r/function_app.html.markdown
> +  name                       = "test-azure-functions"
as above
```suggestion
  name                       = "example-azure-function"
```

2022-02-24 06:36 UTC, jackofallops commented on website/docs/r/function_app.html.markdown
> +~> **Note:** While you can develop your Python based Azure Functions locally on Windows, Python is only supported on a Linux based hosting plan when running in Azure.  See [the documentation for addi
```suggestion
~> **Note:** The Python runtime is only supported on a Linux based hosting plan.  See [the documentation for additional information](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python).
```

2022-03-08 00:29 UTC, katbyte approved these changes
Thanks @jfreeland - LGTM 🦀

2022-03-08 00:29 UTC, merged