`azurerm_kubernetes_cluster` deprecate and remove `role_based_access_control` block and `private_link_enabled`
hashicorp/terraform-provider-azurerm pull request #15546
Opened 2022-02-22 09:34 UTC by stephybun

Closes #11140

2022-02-22 23:46 UTC, katbyte approved these changes
LGTM 💯

2022-02-23 09:13 UTC, tombuildsstuff requested changes
hey @stephybun 

Thanks for this PR - I've taken a look through and left some comments inline but on the whole this is looking good to me. The main question I've got it to check that the behavioural change here is introduced only in version 3.0 of the Azure Provider rather than beforehand, since this field is also ForceNew.

Thanks!

2022-02-23 09:13 UTC, tombuildsstuff commented on internal/services/containers/migration/kubernetes_cluster.go
> +				0: map[string]interface{}{
this doesn't need indexing since it's defining a new slice fwiw:

```suggestion
				map[string]interface{}{
```

2022-02-23 09:13 UTC, tombuildsstuff commented on internal/services/containers/kubernetes_cluster_resource.go
> +				Default:  true,
this'd be a breaking change right now, should this be feature-flagged behind 3.0?

2022-02-23 09:13 UTC, tombuildsstuff commented on website/docs/r/kubernetes_cluster.html.markdown
> +* `role_based_access_control_enabled` (Optional) - Whether Role Based Access Control for the Kubernetes Cluster should be enabled. Defaults to `true`. Changing this forces a new resource to be create
this'd be a breaking change right now, should this be feature-flagged behind 3.0?

2022-03-07 10:22 UTC, tombuildsstuff approved these changes
LGTM 👍

2022-03-07 11:40 UTC, merged