`r\orchestrated_virtual_machine_scale_set`: Rename `termination_notification` to `terminate_notification`
hashicorp/terraform-provider-azurerm pull request #15570
Opened 2022-02-23 09:45 UTC by myc2h6o

`linux_virtual_machine_scale_set_resource` and `windows_virtual_machine_scale_set_resource` has this property named `terminate_...`, however in `orchestrated_virtual_machine_scale_set_resource` it's `termination_...` Renaming it for consistency.

This property is `Optional` + `Computed`, so in the `Update` function, by simply checking the `HasChange` for each of them, it can handle the migration from old property name to new one.

https://github.com/hashicorp/terraform-provider-azurerm/blob/ddf6321ca4aeb11ce5725989feb9392fab23e3cc/internal/services/compute/linux_virtual_machine_scale_set_resource.go#L287

https://github.com/hashicorp/terraform-provider-azurerm/blob/ddf6321ca4aeb11ce5725989feb9392fab23e3cc/internal/services/compute/windows_virtual_machine_scale_set_resource.go#L313

2022-02-23 09:46 UTC, myc2h6o commented
Test result:
$ TF_ACC=1 go test -v ./internal/services/compute -run='TestAccOrchestratedVirtualMachineScaleSet_Te
=== RUN   TestAccOrchestratedVirtualMachineScaleSet_TerminateNotification
=== PAUSE TestAccOrchestratedVirtualMachineScaleSet_TerminateNotification
=== RUN   TestAccOrchestratedVirtualMachineScaleSet_TerminationNotificationMigration
=== PAUSE TestAccOrchestratedVirtualMachineScaleSet_TerminationNotificationMigration
=== CONT  TestAccOrchestratedVirtualMachineScaleSet_TerminateNotification
=== CONT  TestAccOrchestratedVirtualMachineScaleSet_TerminationNotificationMigration
--- PASS: TestAccOrchestratedVirtualMachineScaleSet_TerminateNotification (580.10s)
--- PASS: TestAccOrchestratedVirtualMachineScaleSet_TerminationNotificationMigration (619.60s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/compute       620.328s

2022-02-25 00:06 UTC, katbyte requested changes
@myc2h6o - could we instead rename terminate to termination as from the docs this is a "termination" notification and that is the correct word, and is more explicit on what this does.

thanks

2022-02-28 07:55 UTC, myc2h6o commented
New test result after the update:
![image](https://user-images.githubusercontent.com/10579712/155945279-43f5f5f4-6a22-4cd8-a490-0257efef8bc4.png)

2022-02-28 07:55 UTC, myc2h6o commented
Hi @katbyte Thanks for the comment, yes `termination_notification` seems more reasonable. I've updated the pr, please take a look

2022-02-28 15:48 UTC, myc2h6o commented
Test result after update:
![image](https://user-images.githubusercontent.com/10579712/156013580-2fff7bab-8dc5-4cc1-892d-de0e5d715c91.png)

2022-04-27 03:46 UTC, myc2h6o commented
Updated test result
![image](https://user-images.githubusercontent.com/10579712/165435849-97c3d50d-3853-42f9-b374-d127aa6b99f9.png)

2022-04-27 17:05 UTC, katbyte requested changes

2022-04-28 01:11 UTC, myc2h6o commented on internal/services/compute/virtual_machine_scale_set.go
> +		Deprecated: "`terminate_notification` has been renamed to `termination_notification` and will be removed in 4.0.",
Deprecation notice is put here

2022-04-28 01:12 UTC, myc2h6o commented on internal/services/compute/linux_virtual_machine_scale_set_resource.go
> +		out["terminate_notification"] = VirtualMachineScaleSetTerminateNotificationSchema()
Yeah, it's added in `VirtualMachineScaleSetTerminateNotificationSchema` in virtual_machine_scale_set.go: https://github.com/hashicorp/terraform-provider-azurerm/blob/dd5af47fb37f86cb5511fe6e274dce66071f75b9/internal/services/compute/virtual_machine_scale_set.go#L1408

2022-04-29 01:54 UTC, katbyte approved these changes
Thanks @myc2h6o - LGTM 🚀

2022-04-29 01:54 UTC, katbyte commented on internal/services/compute/linux_virtual_machine_scale_set_resource.go
> +		out["terminate_notification"] = VirtualMachineScaleSetTerminateNotificationSchema()
ah perfect! thanks :)

2022-04-29 01:55 UTC, merged