document: Update doc for `r\application_insights` `workspace_id`
hashicorp/terraform-provider-azurerm pull request #15621
Opened 2022-02-28 04:58 UTC by myc2h6o

2022-03-02 05:44 UTC, tombuildsstuff requested changes
hi @myc2h6o 

Thanks for this PR - taking a look through whilst this documents this limitation we should also add a CustomizeDiff to conditionally recreate this if this field is changed when using the Workspace model.

Thanks!

2022-03-02 05:44 UTC, tombuildsstuff commented on website/docs/r/application_insights.html.markdown
> +~> **NOTE:** This can not be removed after set. More details can be found at [Migrate to workspace-based Application Insights resources](https://docs.microsoft.com/azure/azure-monitor/app/convert-cla
we should also add a CustomizeDiff to conditionally trigger this for a Workspace Application Insights instance

2022-03-07 04:29 UTC, myc2h6o commented
Update comment to remove waiting-response tag

2022-05-30 08:12 UTC, myc2h6o commented
Hi @tombuildsstuff `workspace_id` is likely to be interpolated so instead of adding a CustomizeDiff, I'm putting the validation inside the CreateUpdate instead, could you take a look?

2022-06-06 04:13 UTC, myc2h6o commented
@katbyte probably it's better to just make it ForceNew, I've updated the change, could you take a look?

2022-06-27 23:29 UTC, katbyte approved these changes
Thanks @myc2h6o - LGTM ⛵

2022-06-27 23:29 UTC, merged