feature(SpringCloud): add Java 17 support #15814
hashicorp/terraform-provider-azurerm pull request #15815
Opened 2022-03-12 17:06 UTC by rtrompier

2022-03-14 06:57 UTC, jackofallops requested changes
Hi @rtrompier - Thanks for opening this PR.  Sadly we can't make direct changes to vendor'd files as they'd simply be overwritten when Go manages it's dependencies. As a first-time contributor, GHA doesn't run automatically, which contains a test to ensure these files are intact and unmodified as Go needs them to be, so I'm afraid it would fail this and not be mergeable.

I've checked the API specs and this change is available in a later version of the preview API, however, so we can look to upgrade that to enable your change to add Java17. If this is not something you're comfortable doing, just say, and one of the team can try to take a look as soon as time allows.

2022-03-14 07:45 UTC, rtrompier commented
Hi @jackofallops 
Yes, really sorry, it's my first contribution and first time with GO language ;)
I didn't see I modify the vendor source ... Maybe the folder should be ignored by git ?
If someone more experimented can have a look about this request it will be really great.

2022-03-14 11:04 UTC, jackofallops commented
Hi @rtrompier - No apologies necessary! We appreciate all efforts to help improve the provider 😃 

The vendor'd files are (currently) included to provide the best consistent build experience, so cannot be excluded via `.gitignore` for now, this may change in future. As a first time contributor the GitHub Actions require a maintainer to approve to run, since I knew it would fail I've not done this on this occasion. fwiw - any file under the `vendor` folder should not be modified directly as Go manages those via [tidy](https://go.dev/ref/mod#go-mod-tidy) and [vendor](https://go.dev/ref/mod#go-mod-vendor).

I'll mention this to the team and see if anyone has capacity to check if the API version can be bumped with no breaking changes, which will unblock this and allow you to update this PR on top of the newer API. Does that work for you?

2022-03-14 11:11 UTC, rtrompier commented
Perfect ! 
I wait for your feedback ;) 
Have a good day.

2022-05-13 01:30 UTC, katbyte requested changes
Hey @rtrompier - Thanks for the PR - it looks like that constant doesn't exit in the currently vendored in SDK? perhapes do we need to upgrade to a new SDK version to enable this property?

2022-05-13 01:30 UTC, katbyte commented on internal/services/springcloud/spring_cloud_java_deployment_resource.go
> +				string(appplatform.RuntimeVersionJava17),
This doesn't appear to exist in the SDK?

2022-06-29 17:31 UTC, tombuildsstuff commented
hey @rtrompier 

As mentioned above unfortunately this change needs to be added [to the upstream Swagger Definition where the Azure SDK is generated from](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2022-04-01) - as such whilst we'd like to thank you for this contribution I'm going to close this PR for the moment as this change needs to first be made in the Swagger before this is usable in the Azure SDK (and ultimately in Terraform).

Thanks!

2022-06-29 17:31 UTC, closed without merging