`netapp_snapshot` wait LRO
hashicorp/terraform-provider-azurerm pull request #15830
Opened 2022-03-15 02:54 UTC by shu-ying789

linked to https://github.com/hashicorp/terraform-provider-azurerm/issues/15641

test result:
<img width="743" alt="net1" src="https://user-images.githubusercontent.com/96756505/158296602-8e8e64d2-fed9-4b82-8ddc-dc56da36f627.png">

2022-03-20 17:15 UTC, katbyte requested changes

2022-03-20 17:15 UTC, katbyte commented on internal/services/netapp/netapp_snapshot_resource.go
> -	// The resource NetApp Snapshot depends on the resource NetApp Volume.
have you confirmed this is no longer required?

2022-03-26 00:58 UTC, paulomarquesc commented
The wait functions are still required, this PR will introduce the initial instability we had in the past, usage of future.WaitForCompletion does not change the behavior that is in the underlying infrastructure.

2022-03-26 01:23 UTC, katbyte commented
@shu-ying789, as expected the state wait is still required so closing this at the behest of the service's maintainer, if you have any questions please reach out to @paulomarquesc.

2022-03-26 01:23 UTC, closed without merging