`azurerm_static_site` - `identity` supports `SystemAssigned, UserAssigned`
hashicorp/terraform-provider-azurerm pull request #15834
Opened 2022-03-15 06:51 UTC by magodo

Fix #15794

## Test

```shell
💢  TF_ACC=1 go test -v -timeout=20h ./internal/services/web  -run='TestAccAzureStaticSite_with|TestAccAzureStaticSite_identity'
=== RUN   TestAccAzureStaticSite_withSystemAssignedIdentity
=== PAUSE TestAccAzureStaticSite_withSystemAssignedIdentity
=== RUN   TestAccAzureStaticSite_identity
=== PAUSE TestAccAzureStaticSite_identity
=== RUN   TestAccAzureStaticSite_withSystemAssignedUserAssignedIdentity
=== PAUSE TestAccAzureStaticSite_withSystemAssignedUserAssignedIdentity
=== RUN   TestAccAzureStaticSite_withUserAssignedIdentity
=== PAUSE TestAccAzureStaticSite_withUserAssignedIdentity
=== CONT  TestAccAzureStaticSite_withSystemAssignedIdentity
=== CONT  TestAccAzureStaticSite_withSystemAssignedUserAssignedIdentity
=== CONT  TestAccAzureStaticSite_identity
=== CONT  TestAccAzureStaticSite_withUserAssignedIdentity
--- PASS: TestAccAzureStaticSite_withSystemAssignedUserAssignedIdentity (131.75s)
--- PASS: TestAccAzureStaticSite_withSystemAssignedIdentity (182.29s)
--- PASS: TestAccAzureStaticSite_identity (227.74s)
--- PASS: TestAccAzureStaticSite_withUserAssignedIdentity (807.10s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/web   807.112s
```

2022-03-15 10:58 UTC, tombuildsstuff commented on internal/services/web/static_site_resource_test.go
> +		// There is API issue to downgrade the sku to Free with identity configured: https://github.com/Azure/azure-rest-api-specs/issues/18253
can we make this a TODO:

```suggestion
		// TODO: re-enable this once the API issue is resolved: https://github.com/Azure/azure-rest-api-specs/issues/18253
		// API currently doesn't allow downgrading to a Free SKU with an Identity attached
```

2022-03-15 11:00 UTC, tombuildsstuff requested changes
A couple of minor comments but if we can fix those up then this should otherwise be good to go 👍

2022-03-16 01:37 UTC, magodo commented on internal/services/web/static_site_resource_test.go
>  		data.ImportStep(),
@tombuildsstuff Isn't the current step is the SystemAssinged and UserAssigned use case? While I noticed that the 3rd and 5th steps are actually the same, I'm not sure whether it is intentional, so just keep it as is.

2022-03-16 09:58 UTC, tombuildsstuff commented on internal/services/web/static_site_resource_test.go
>  		data.ImportStep(),
Yep, good spot - yes the 5th should be UserAssigned I guess?

2022-03-17 02:24 UTC, magodo commented
@tombuildsstuff I've updated the test and passed it, please take another look, thank you!

## Test

```shell
💤  TF_ACC=1 go test -v -timeout=20h ./internal/services/web  -run='TestAccAzureStaticSite_identity$'
=== RUN   TestAccAzureStaticSite_identity
=== PAUSE TestAccAzureStaticSite_identity
=== CONT  TestAccAzureStaticSite_identity
--- PASS: TestAccAzureStaticSite_identity (873.12s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/web   873.134s
```

2022-03-18 16:20 UTC, merged