`dependencies`: Upgrade sqlvirtualmachine to 2021-11-01-preview
hashicorp/terraform-provider-azurerm pull request #15835
Opened 2022-03-15 07:29 UTC by myc2h6o

2022-03-15 07:31 UTC, myc2h6o commented on internal/services/mssql/mssql_virtual_machine_resource.go
> +		"temp_db_settings":      flattenSqlVirtualMachineTempDbSettings(input.SQLTempDbSettings),
The type has been changed in the new api version so created a copy of the old expand/flatten

2022-04-19 07:44 UTC, myc2h6o commented
Hi @katbyte there seems to be multiple features waiting for the api upgrade, would you be able to take a look?

2022-04-21 22:48 UTC, katbyte requested changes
@myc2h6o - all tests are failing with this PR:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/1638467/164563741-037244b3-9285-40ab-8316-665ea81932f8.png">

2022-04-23 14:48 UTC, myc2h6o commented
Hi @katbyte I found these tests failing on main due to dangling resources during delete phase, fixing them with #16519. Please take a look.

2022-04-26 09:36 UTC, myc2h6o commented
The fixing pr #16519 is merged, updated test result with this change:
![image](https://user-images.githubusercontent.com/10579712/165269970-5ce061d2-10a6-404d-bd18-915701190a48.png)

Ampng these, the test `TestAccMsSqlVirtualMachine_autoPatching` is intermittently failing ever since it's introduced due to the refresh latency, similar to the other property `auto_backup`, we may need to apply the same workaround for it, will address it in a separate pr:
https://github.com/hashicorp/terraform-provider-azurerm/blob/cdd2a577a0ed4717318d575d2b03330ca68a07a8/internal/services/mssql/mssql_virtual_machine_resource.go#L397-L407

2022-04-27 20:49 UTC, katbyte approved these changes
LGTM 🚜

2022-04-27 20:50 UTC, merged