New Resource: azurerm_stream_analytics_function_javascript_uda
hashicorp/terraform-provider-azurerm pull request #15831
Opened 2022-03-15 04:53 UTC by neil-yechenwei

fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/7303

--- PASS: TestAccStreamAnalyticsFunctionJavaScriptUDA_basic (244.77s)
--- PASS: TestAccStreamAnalyticsFunctionJavaScriptUDA_requiresImport (282.79s)
--- PASS: TestAccStreamAnalyticsFunctionJavaScriptUDA_update (288.96s)
--- PASS: TestAccStreamAnalyticsFunctionJavaScriptUDA_inputs (464.66s)

2022-03-16 08:20 UTC, stephybun requested changes
Thanks for this PR @neil-yechenwei, this is off to a great start! I left some suggestions in line, once those are fixed up we can take another look.

2022-03-16 08:20 UTC, stephybun commented on website/docs/r/stream_analytics_function_javascript_uda.html.markdown
> +* `type` - The Data Type output from this JavaScript Function. Possible values include `any`, `array`, `bigint`, `datetime`, `float`, `nvarchar(max)` and `record`.
```suggestion
An `input` block supports the following:

* `type` - The input data type of this JavaScript Function. Possible values include `any`, `array`, `bigint`, `datetime`, `float`, `nvarchar(max)` and `record`.

---

An `output` block supports the following:

* `type` - The output data type from this JavaScript Function. Possible values include `any`, `array`, `bigint`, `datetime`, `float`, `nvarchar(max)` and `record`.
```

2022-03-17 02:48 UTC, neil-yechenwei commented on website/docs/r/stream_analytics_function_javascript_uda.html.markdown
> +* `type` - The Data Type output from this JavaScript Function. Possible values include `any`, `array`, `bigint`, `datetime`, `float`, `nvarchar(max)` and `record`.
Updated

2022-03-17 02:48 UTC, neil-yechenwei commented on website/docs/r/stream_analytics_function_javascript_uda.html.markdown
> +* `output` - (Required) An `output` blocks as defined below.
Updated

2022-03-17 02:48 UTC, neil-yechenwei commented on website/docs/r/stream_analytics_function_javascript_uda.html.markdown
> +Manages a JavaScript UDA Function within Stream Analytics Streaming Job.
Updated

2022-03-17 02:48 UTC, neil-yechenwei commented on website/docs/r/stream_analytics_function_javascript_uda.html.markdown
> +  Manages a JavaScript UDA Function within Stream Analytics Streaming Job.
Updated

2022-03-17 02:48 UTC, neil-yechenwei commented on internal/services/streamanalytics/stream_analytics_function_javascript_uda_resource.go
> +			return fmt.Errorf("deleting %s: %+v", id, err)
Updated

2022-03-17 02:49 UTC, neil-yechenwei commented on internal/services/streamanalytics/stream_analytics_function_javascript_uda_resource.go
> +			log.Printf("[DEBUG] %q was not found - removing from state!", id)
Updated

2022-03-17 02:49 UTC, neil-yechenwei commented on internal/services/streamanalytics/stream_analytics_function_javascript_uda_resource.go
> +		return fmt.Errorf("retrieving %s: %+v", id, err)
Updated

2022-03-17 02:49 UTC, neil-yechenwei commented on internal/services/streamanalytics/stream_analytics_function_javascript_uda_resource.go
> +			"resource_group_name": azure.SchemaResourceGroupName(),
Yes. You're right. Removed it.

2022-03-17 02:49 UTC, neil-yechenwei commented on internal/services/streamanalytics/registration.go
> +		"azurerm_stream_analytics_function_javascript_uda": resourceStreamAnalyticsFunctionUDA(),
Updated

2022-03-17 03:32 UTC, neil-yechenwei commented on internal/services/streamanalytics/stream_analytics_function_javascript_uda_resource.go
> +		Update: resourceStreamAnalyticsFunctionUDACreateUpdate,
Updated

2022-03-17 04:32 UTC, neil-yechenwei commented
@stephybun , thanks for your comments. I've updated code. Please take another look. Thanks.

2022-03-17 11:30 UTC, stephybun approved these changes
Thanks @neil-yechenwei, LGTM 🚀

2022-03-17 11:30 UTC, merged