`azurerm_sentinel_watchlist` - Add required property `item_search_key`
hashicorp/terraform-provider-azurerm pull request #15861
Opened 2022-03-17 06:33 UTC by magodo

Since March, the sentinel API now requires the `itemSearchey` in the `PUT` request. Meanwhile, the `contentType` is now not needed here as we don't actually send any content, but delegate it to the `azurerm_sentinel_watchlist_item`.

Fixes #15851.
Superseds: #15856.

## Test

```shell
💤  TF_ACC=1 go test -v -timeout=20h ./internal/services/sentinel  -run='TestAccWatchlist'
=== RUN   TestAccWatchlistItem_basic
=== PAUSE TestAccWatchlistItem_basic
=== RUN   TestAccWatchlistItem_update
=== PAUSE TestAccWatchlistItem_update
=== RUN   TestAccWatchlistItem_requiresImport
=== PAUSE TestAccWatchlistItem_requiresImport
=== RUN   TestAccWatchlist_basic
=== PAUSE TestAccWatchlist_basic
=== RUN   TestAccWatchlist_complete
=== PAUSE TestAccWatchlist_complete
=== RUN   TestAccWatchlist_requiresImport
=== PAUSE TestAccWatchlist_requiresImport
=== CONT  TestAccWatchlistItem_basic
=== CONT  TestAccWatchlist_requiresImport
=== CONT  TestAccWatchlist_basic
=== CONT  TestAccWatchlistItem_requiresImport
=== CONT  TestAccWatchlist_complete
=== CONT  TestAccWatchlistItem_update
--- PASS: TestAccWatchlist_basic (124.25s)
--- PASS: TestAccWatchlistItem_requiresImport (150.89s)
--- PASS: TestAccWatchlistItem_basic (184.24s)
--- PASS: TestAccWatchlistItem_update (228.30s)
--- PASS: TestAccWatchlist_requiresImport (784.88s)
--- PASS: TestAccWatchlist_complete (820.07s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/sentinel      820.092s
```

2022-03-17 08:51 UTC, magodo commented
The CI failure of the example is due to there is new property introduced.

2022-03-17 09:06 UTC, mcamenzind commented
Any reason for deviating from Microsoft's property naming `itemsSearchKey` (notice the `s`)?

2022-03-22 16:24 UTC, tombuildsstuff commented on internal/services/sentinel/sentinel_watchlist_resource.go
> -					ContentType: utils.String("Text/Csv"),
this is a breaking change, we should be exposing a field for this with a default value here?

2022-03-22 20:59 UTC, katbyte requested changes
Thanks @magodo - left some comments inline. as for the the name `items_seach_key` sounds incorrect? correct grammar should be `item_search_key` regardless of what the SDK is using?

2022-03-22 20:59 UTC, katbyte commented on internal/services/sentinel/sentinel_watchlist_resource.go
> +					Source: securityinsight.Source("a.csv"),
"a.csv" is not a valid value for securityinsight.Source? at that should we not expose this in schema with a default?

2022-03-22 20:59 UTC, katbyte commented on internal/services/sentinel/sentinel_watchlist_resource.go
> -					ContentType: utils.String("Text/Csv"),
how come we are removing this? should it not be in schema with a default?

2022-03-22 20:59 UTC, katbyte commented on internal/services/sentinel/sentinel_watchlist_resource.go
> +					ItemsSearchKey: utils.String(model.ItemsSearchKey),
ditto here? should this not just be in schema with a default?

2022-03-23 04:04 UTC, magodo commented
@tombuildsstuff and @katbyte The `Source` and `ContentType` are not returned from API, they are used by the service during the `PUT` so that the service can create watchlist items based on the specified source. However, as is stated in #14258 this resource is only to create an empty watchlist, if users want to create watchlist items, they can then use `azurerm_sentinel_watchlist_item` resource.

Therefore, this PR removes the `ContentType` (as is actually optional in turns of API), and the value of the `Source` is actually doesn't have any real effect, but only to make API happy, which even can be regarded as not a breaking change for TF users.

2022-04-08 07:42 UTC, Andyandpandy commented
Any progress here? 
This PR is blocking me from going > 3.0.x

2022-04-14 02:28 UTC, katbyte approved these changes
LGTM 🚜

2022-04-14 02:28 UTC, merged