new resource `azurerm_spring_cloud_builder`
hashicorp/terraform-provider-azurerm pull request #16036
Opened 2022-03-25 02:40 UTC by ms-henglu

![image](https://user-images.githubusercontent.com/79895375/160043964-11510b83-8e2b-447a-8bd5-6d23dc304d06.png)

2022-04-06 18:01 UTC, katbyte commented on website/docs/r/spring_cloud_builder.html.markdown
> +  }
should this be build_pack_group? so

```suggestion
  build_pack_group {
    name           = "mix"
    build_pack_ids = ["tanzu-buildpacks/java-azure"]
  }
  
   build_pack_group {
    name           = "mix"
    build_pack_ids = ["tanzu-buildpacks/java-azure"]
  }
```

?

2022-04-07 02:15 UTC, ms-henglu commented
Thanks @katbyte , I've updated it, please take another look.

2022-04-21 23:24 UTC, katbyte requested changes

2022-04-21 23:24 UTC, katbyte commented on internal/services/springcloud/spring_cloud_builder_resource.go
> +					},
can we please properly validate all this?

2022-04-21 23:24 UTC, katbyte commented on website/docs/r/spring_cloud_builder.html.markdown
> +* `version` - (Required) Version of the ClusterStack
and fix the grammar/punctuation here?

2022-05-02 21:32 UTC, katbyte approved these changes
LGTM 🌿

2022-05-02 21:33 UTC, merged