`kubernetes_cluster_resource` support network_profile.ip_families
hashicorp/terraform-provider-azurerm pull request #16088
Opened 2022-03-28 05:59 UTC by heiazuo

### create an public pull request for `kubernetes_cluster_resource` support network_profile.ip_families
**test result:**
![kubernetes_cluster_network_resource_test go](https://user-images.githubusercontent.com/46072066/160062376-5e819719-339c-4e65-b187-c77bb5b32f8c.png)

2022-03-29 13:01 UTC, stephybun requested changes
Thanks for this PR @heiazuo, this is off to a good start. Aside from the comments left in-line I also have two additional suggestions:

1. We should create an additional test and that tests dual-stack networking with the value `["IPv4", "IPv6"]`
2. In the create method could we add a check that throws an error if a user tries to specify `["IPv6"]`, the validation for the property allows it, but it isn't valid for the API.

Once the above is addressed we can take another look through this.

2022-04-01 07:04 UTC, heiazuo commented
Thanks @stephybun, thanks for your suggestion, I made the changes as suggested

2022-04-01 10:21 UTC, stephybun requested changes
Thanks for renaming the property and adding the test for dual-stack networking @heiazuo, I still have a question and suggestion regarding the check on the value.

2022-04-01 10:21 UTC, stephybun commented on internal/services/containers/kubernetes_cluster_resource.go
> +}
Like so
```suggestion
func expandIPVersions(input []interface{}) (*[]containerservice.IPFamily, error) {
	if len(input) == 0 {
		return nil, nil
	}
	ipf := make([]containerservice.IPFamily, 0)
	for _, data := range input {
		ipf = append(ipf, containerservice.IPFamily(data.(string)))
	}
	if len(ipf) == 1 && ipf[0] == containerservice.IPFamilyIPv6 {
		return nil, fmt.Errorf("`ip_versions` must be `IPv4` or `IPv4` and `IPv6`. `IPv6` alone is not supported")
	}

	return &ipf, nil
}
```

2022-04-01 10:21 UTC, stephybun commented on internal/services/containers/kubernetes_cluster_resource.go
> +		IPFamilies:      expandIPVersions(ipVersions),
```suggestion
	ipVersions, err := expandIPVersions(config["ip_versions"].([]interface{}))
	if err != nil {
		return nil, err
	}

	networkProfile := containerservice.NetworkProfile{
		NetworkPlugin:   containerservice.NetworkPlugin(networkPlugin),
		NetworkMode:     containerservice.NetworkMode(networkMode),
		NetworkPolicy:   containerservice.NetworkPolicy(networkPolicy),
		LoadBalancerSku: containerservice.LoadBalancerSku(loadBalancerSku),
		OutboundType:    containerservice.OutboundType(outboundType),
		IPFamilies:      ipVersions,
	}
```

2022-04-05 13:54 UTC, stephybun approved these changes
Thanks @heiazuo, LGTM 🥟

2022-04-05 13:54 UTC, merged