`azurerm_static_site` - Fix update error after publishing the site
hashicorp/terraform-provider-azurerm pull request #16184
Opened 2022-03-31 09:34 UTC by magodo

Fixes #16165.

## Test

As the issue #16165 is less likely to reproduce via the acctest (at least we need to setup the repo, using github provider, etc), I've verified it locally, with [this example](https://github.com/hashicorp/terraform-provider-azurerm/tree/main/examples/web/static-site).

After I've published the site, I tried to update the project's tag:

```shell
💤  tf apply -var=github_owner=magodo -var=github_token=<token> -auto-approve

azurerm_resource_group.test: Refreshing state... [id=/subscriptions/****/resourceGroups/example]
azurerm_static_site.test: Refreshing state... [id=/subscriptions/****/resourceGroups/example/providers/Microsoft.Web/staticSites/example]
github_repository_file.foo: Refreshing state... [id=my-first-static-web-app/.github/workflows/azure-static-web-app.yml]
github_actions_secret.test: Refreshing state... [id=my-first-static-web-app:AZURE_STATIC_WEB_APPS_API_TOKEN]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azurerm_static_site.test has changed
  ~ resource "azurerm_static_site" "test" {
        id                  = "/subscriptions/****/resourceGroups/example/providers/Microsoft.Web/staticSites/example"
        name                = "example"
        tags                = {
            "foo" = "foo"
        }
        # (6 unchanged attributes hidden)

      ~ identity {
          + identity_ids = []
            # (3 unchanged attributes hidden)
        }
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_static_site.test will be updated in-place
  ~ resource "azurerm_static_site" "test" {
        id                  = "/subscriptions/****/resourceGroups/example/providers/Microsoft.Web/staticSites/example"
        name                = "example"
      ~ tags                = {
          ~ "foo" = "foo" -> "bar"
        }
        # (6 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
azurerm_static_site.test: Modifying... [id=/subscriptions/****/resourceGroups/example/providers/Microsoft.Web/staticSites/example]
azurerm_static_site.test: Still modifying... [id=/subscriptions/67a9759d-d099-4aa8-8675-...ders/Microsoft.Web/staticSites/example, 10s elapsed]
azurerm_static_site.test: Modifications complete after 16s [id=/subscriptions/****/resourceGroups/example/providers/Microsoft.Web/staticSites/example]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

hostname = "****"

azurerm/static_web_site/e2e via 💠 default took 27s
💤  tf plan -var=github_owner=magodo -var=github_token=<token>

azurerm_resource_group.test: Refreshing state... [id=/subscriptions/****/resourceGroups/example]
github_repository_file.foo: Refreshing state... [id=my-first-static-web-app/.github/workflows/azure-static-web-app.yml]
azurerm_static_site.test: Refreshing state... [id=/subscriptions/****/resourceGroups/example/providers/Microsoft.Web/staticSites/example]
github_actions_secret.test: Refreshing state... [id=my-first-static-web-app:AZURE_STATIC_WEB_APPS_API_TOKEN]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

The existing acctests:

```shell
💤  TF_ACC=1 go test -v -timeout=20h ./internal/services/web -run='TestAccAzureStaticSite_basicUpdate|TestAccAzureStaticSite_identity$'
=== RUN   TestAccAzureStaticSite_identity
=== PAUSE TestAccAzureStaticSite_identity
=== RUN   TestAccAzureStaticSite_basicUpdate
=== PAUSE TestAccAzureStaticSite_basicUpdate
=== CONT  TestAccAzureStaticSite_identity
=== CONT  TestAccAzureStaticSite_basicUpdate
--- PASS: TestAccAzureStaticSite_basicUpdate (204.65s)
--- PASS: TestAccAzureStaticSite_identity (386.76s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/web   386.777s
```

2022-03-31 09:56 UTC, jackofallops requested changes
Hi @magodo - Thanks for this PR. Before I get into a full review, can you address the 2 comments below? Rather than annotating items for 4.0 with todo's we're going ahead with feature-flagged implementations. 

Thanks!

2022-03-31 09:56 UTC, jackofallops commented on internal/services/web/static_site_resource.go
> +			// TODO 4.0 - Rename this to be `sku_name`
Can you implement this change behind the `features.FourPointOhBeta()` feature flag, rather than leaving as todo?

2022-03-31 09:56 UTC, jackofallops commented on internal/services/web/azuresdkhacks/static_site.go
> +	//Type              *string                     `json:"type,omitempty"`
Can we remove these, rather than comment?

2022-04-21 06:21 UTC, fvdnabee commented
Any update on this?

2022-04-21 22:24 UTC, katbyte requested changes
tests need updating for 3.0?

```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccAzureStaticSite_withUserAssignedIdentity
=== PAUSE TestAccAzureStaticSite_withUserAssignedIdentity
=== CONT  TestAccAzureStaticSite_withUserAssignedIdentity

------- Stderr: -------
panic: Invalid address to set: []string{"sku_name"}

goroutine 396 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc000322a00, {0x5e6a942, 0x8}, {0x5400920, 0xc0030e54f0})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:230 +0x291
github.com/hashicorp/terraform-provider-azurerm/internal/services/web.resourceStaticSiteRead(0xc000322a00, {0x5541420?, 0xc0042fb180?})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/services/web/static_site_resource.go:304 +0x5db
github.com/hashicorp/terraform-provider-azurerm/internal/services/web.resourceStaticSiteCreate(0x0?, {0x5541420?, 0xc0042fb180})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/services/web/static_site_resource.go:175 +0xc4d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc003a18510?, {0x663ebf0?, 0xc002116280?}, 0x2?, {0x5541420?, 0xc0042fb180?})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00414a8c0, {0x663ebf0, 0xc002116280}, 0xc00231b1e0, 0xc000322880, {0x5541420, 0xc0042fb180})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:467 +0x6f1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000d09578, {0x663ebf0, 0xc002116280}, 0xc0027c1630)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc003dce580, {0x663ec98?, 0xc001e275f0?}, 0xc00261f7a0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:603 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x5aaf520?, 0xc003dce580}, {0x663ec98, 0xc001e275f0}, 0xc000ce2c60, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002cd180, {0x664ff70, 0xc0003bb380}, 0xc001d94120, 0xc002192a80, 0xa548ea0, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc0002cd180, {0x664ff70, 0xc0003bb380}, 0xc001d94120, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1617 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:938 +0x28a
```

2022-04-22 02:52 UTC, magodo commented
@katbyte The error is due to a mistake I made when introducing the 4.0 feature toggle, it is now fixed, please take another look:

```bash
💢  TF_ACC=1 go test -v -timeout=20h ./internal/services/web -run='TestAccAzureStaticSite_identity|TestAccAzureStaticSite_withUserAssignedIdentity'
=== RUN   TestAccAzureStaticSite_identity
=== PAUSE TestAccAzureStaticSite_identity
=== RUN   TestAccAzureStaticSite_withUserAssignedIdentity
=== PAUSE TestAccAzureStaticSite_withUserAssignedIdentity
=== CONT  TestAccAzureStaticSite_identity
=== CONT  TestAccAzureStaticSite_withUserAssignedIdentity
--- PASS: TestAccAzureStaticSite_withUserAssignedIdentity (239.61s)
--- PASS: TestAccAzureStaticSite_identity (1704.37s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/web   1704.385s
```

2023-01-09 15:26 UTC, katbyte commented
@magodo - are there any updates on https://github.com/Azure/azure-rest-api-specs/issues/18501 ?

2023-06-12 14:41 UTC, jackofallops commented
Hi @magodo - Since this has been waiting on a response from the service team on the upstream issue for quite some time I'm going to close this PR until we get some traction there.  If we get a response, or some way to progress this again, we can look to re-open it.

Thanks!

2023-06-12 14:41 UTC, closed without merging