New Resourece: azurerm_signalr_shared_private_link_resource
hashicorp/terraform-provider-azurerm pull request #16187
Opened 2022-03-31 12:08 UTC by xiaxyi

Comparing to the private link resource which supported by network, this can be considered as the outbound private link which is initiated by the corresponding service.

Acc tests:
```
--- PASS: TestAccSignalrSharedPrivateLinkResource_basicSites (569.88s)
--- PASS: TestAccSignalrSharedPrivateLinkResource_basic (647.43s)
--- PASS: TestAccSignalrSharedPrivateLinkResource_requiresImport (671.23s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/signalr       671.972s

```

2022-04-01 15:07 UTC, catriona-m requested changes
Thanks @xiaxyi, this is looking good so far, just left a couple of comments inline. Also, looks like there may be a linting error that needs fixed up. Thanks!

2022-04-01 15:18 UTC, xiaxyi commented on internal/services/signalr/signalr_shared_private_link_resource.go
> +			"subresource_name": {
yep, I think so, I changed the name of the property.

2022-04-01 15:39 UTC, xiaxyi commented
Thanks @catriona-m , updated the code.

2022-04-11 14:41 UTC, tombuildsstuff commented on internal/services/signalr/client/client.go
> +	"github.com/hashicorp/terraform-provider-azurerm/internal/services/signalr/sdk/2021-10-01/signalr"
where's the upstream PR using this? I can only see 2020-05-01 upstream?

2022-04-11 14:41 UTC, tombuildsstuff commented on internal/services/signalr/client/client.go
> +	"github.com/hashicorp/terraform-provider-azurerm/internal/services/signalr/sdk/2021-10-01/signalr"
where's the upstream PR using this? I can only see 2020-05-01 upstream?

2022-07-20 02:14 UTC, xiaxyi commented
@katbyte Sure, updated the SDK.

2022-07-29 00:13 UTC, katbyte approved these changes
LGTM 🍬

2022-07-29 00:13 UTC, merged