`cluster_node_pool/kubernetes_cluster` remove node_labels forceNew
hashicorp/terraform-provider-azurerm pull request #16360
Opened 2022-04-13 01:33 UTC by heiazuo

### create a pull request for `cluster_node_pool/kubernetes_cluster` remove node_labels forceNew

2022-04-13 04:08 UTC, tombuildsstuff commented
@heiazuo whilst this is true for newly provisioned clusters, is this behaviour consistent for clusters created previously (e.g. a month ago)? The behaviour of the AKS API depends on when the AKS Cluster was provisioned, fwiw - so a cluster created today can have different behaviours to a cluster from last week (and depends on the kubernetes version being used etc)

2022-04-13 18:05 UTC, grayzu commented
@tombuildsstuff, I just pinged the AKS team and they said "So long as you’re using the newer rest API/SDK, it’s the same for any version."

2022-04-21 10:22 UTC, stephybun requested changes
Thanks for this PR @heiazuo. The docs should be amended since the resource will no longer be recreated if the node labels are updated. Can you also please add a test that updates the node labels?

2022-05-06 05:36 UTC, ms-henglu commented
Hi @stephybun , would you please take another look?

2022-05-06 08:55 UTC, stephybun commented
@ms-henglu, a test that updates the node labels is still missing.

2022-05-06 09:17 UTC, heiazuo commented
Hi @stephybun, node_labels test case already exists, we don't need to create
The test case is `TestAccKubernetesCluster_nodeLabels`, under `kubernetes_cluster_other_resource_test.go` file

2022-05-09 07:24 UTC, stephybun approved these changes
Thanks @heiazuo, LGTM 👍

2022-05-09 07:24 UTC, merged