New resource - `azurerm_sentinel_data_connector_aws_s3`
hashicorp/terraform-provider-azurerm pull request #16440
Opened 2022-04-19 07:10 UTC by magodo

This PR adds support for a new sentinel data connector type: AWS S3. Checkout https://docs.microsoft.com/en-us/azure/sentinel/connect-aws for details.

As this resource needs setup of several AWS resources as a precondition, this PR didn't include an AccTest for it. I've locally tested the functionalities: CRUD and plan, which behaves as expected.

2022-04-21 22:50 UTC, katbyte requested changes

2022-04-21 22:50 UTC, katbyte commented on internal/services/sentinel/sentinel_data_connector_aws_s3_resource.go
> +		"log_analytics_workspace_id": {
```suggestion
		},
		
		"log_analytics_workspace_id": {
```

2022-04-21 22:50 UTC, katbyte commented on internal/services/sentinel/sentinel_data_connector_aws_s3_resource.go
> +			ValidateFunc: validation.StringIsNotEmpty,
can we validate this? maybe copy the validation function AWS provider uses

2022-04-21 22:50 UTC, katbyte commented on website/docs/r/sentinel_data_connector_aws_s3.html.markdown
> +* `destination_table` - (Required) The logs destination table name.
grammer

2022-04-22 02:45 UTC, magodo commented
@katbyte Thank you for the comments! I've fixed all of them. Please take another look!

2022-05-06 00:15 UTC, katbyte approved these changes
LGTM 🔍

2022-05-06 00:15 UTC, merged