`azurerm_kubernetes_cluster` `azurerm_kubernetes_cluster_node_pool` Support for Azure Dedicated Host (ADH)
hashicorp/terraform-provider-azurerm pull request #16444
Opened 2022-04-19 09:39 UTC by shu-ying789

linked to https://github.com/hashicorp/terraform-provider-azurerm/issues/15658

2022-04-28 11:17 UTC, stephybun requested changes
Thanks @shu-ying789, this looks good to me. Two minor comments on the docs and there is also a test failure, looks like the location is passed to `kubernetes_version`?
```
------- Stdout: -------
=== RUN   TestAccKubernetesCluster_dedicatedHost
=== PAUSE TestAccKubernetesCluster_dedicatedHost
=== CONT  TestAccKubernetesCluster_dedicatedHost
testcase.go:110: Step 1/1 error: Error running apply: exit status 1
Error: creating Cluster: (Managed Cluster Name "acctestaks220428103126887507" / Resource Group "acctestRG-aks-220428103126887507"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Client Error: error parsing version(westus2) as semver: Invalid Semantic Version"
with azurerm_kubernetes_cluster.test,
on terraform_plugin_test.tf line 39, in resource "azurerm_kubernetes_cluster" "test":
39: resource "azurerm_kubernetes_cluster" "test" {
--- FAIL: TestAccKubernetesCluster_dedicatedHost (320.81s)
FAIL
```

2022-05-07 03:17 UTC, shu-ying789 commented on website/docs/d/kubernetes_cluster.html.markdown
> +* `host_group_id` - The ID of a Dedicated Host Group that this xxx should be run within. Changing this forces a new resource to be created.
@stephybun Documentation and test have been modified, please check again, thank you!

2022-05-12 10:19 UTC, stephybun reviewed
Have another test failure:
```
------- Stdout: -------
=== RUN   TestAccKubernetesCluster_dedicatedHost
=== PAUSE TestAccKubernetesCluster_dedicatedHost
=== CONT  TestAccKubernetesCluster_dedicatedHost
testcase.go:110: Step 1/1 error: Error running apply: exit status 1
Error: waiting for creation of Cluster: (Managed Cluster Name "acctestaks220512100349784765" / Resource Group "acctestRG-aks-220512100349784765"): Code="CreateVMSSAgentPoolFailed" Message="Code=\"AllocationFailed\" Message=\"VM allocation to the dedicated host failed. Please ensure that the dedicated host has enough capacity or try allocating elsewhere.\""
with azurerm_kubernetes_cluster.test,
on terraform_plugin_test.tf line 39, in resource "azurerm_kubernetes_cluster" "test":
39: resource "azurerm_kubernetes_cluster" "test" {
testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
Error: deleting Dedicated Host Group "Host Group: (Name \"acctestDHG-compute-220512100349784765\" / Resource Group \"acctestRG-aks-220512100349784765\")" : compute.DedicatedHostGroupsClient#Delete: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Host Group 'acctestDHG-compute-220512100349784765' cannot be deleted. Before deleting the host group, please ensure it does not contain any Host. Also, the host group should not contain any Virtual Machine or Virtual Machine Scale Set placed through automatic placement." Target="hostGroup"
--- FAIL: TestAccKubernetesCluster_dedicatedHost (401.57s)
FAIL
```

2022-06-13 02:43 UTC, ms-henglu commented
Hi @stephybun - thanks for code review, there seem to be an issue that the resources can't be destroyed successfully, I'll reopen this PR when it's fixed.

2022-06-13 02:46 UTC, closed without merging