Add access_tier attribute to storage_share
hashicorp/terraform-provider-azurerm pull request #16462
Opened 2022-04-20 08:42 UTC by koikonom

Also upgrades giovanni to v0.19.0 which addresses a panic when uploading large files

2022-05-05 15:54 UTC, tombuildsstuff requested changes
Left a few comments inline but this otherwise LGTM 👍

2022-05-05 15:54 UTC, tombuildsstuff commented on internal/services/storage/storage_share_resource.go
> +	}
this'll want a value always set:

```suggestion
	accessTier := ""
	if props.AccessTier != nil {
		accessTier = string(*props.AccessTier)
	}
	d.Set("access_tier", accessTier)
```

2022-05-05 15:54 UTC, tombuildsstuff commented on internal/services/storage/storage_share_resource_test.go
> +			Config: r.accessTier(data, string(shares.TransactionOptimizedAccessTier)),
can we hard-code the string values for these? that protects against the value changing casing etc

2022-05-05 15:54 UTC, tombuildsstuff commented on website/docs/d/storage_share.html.markdown
> +* `access_tier` - The tier of the File Share. Can be one of `Hot`, `Cool`, `TransactionOptimized`, or `Premium`.
Premium isn't a supported value? https://github.com/hashicorp/terraform-provider-azurerm/pull/16462/files#diff-773e6c18c4552e9b5d5496623bb06e64cc9703e228698492c8f33be90d700781R128-R130

2022-05-06 08:56 UTC, tombuildsstuff approved these changes
LGTM 👍

2022-05-06 09:39 UTC, merged

2022-05-18 07:01 UTC, wernerfred reviewed
@tombuildsstuff @koikonom shouldn't the `website/docs/d/storage_share.html.markdown` (datasource) go into `website/docs/r/storage_share.html.markdown` (resources)?