Added `triggers` attribute to `azurerm_virtual_network_peering` to allow `address_space` synchronisation
hashicorp/terraform-provider-azurerm pull request #16563
Opened 2022-04-27 09:18 UTC by tiwood

This is a continuation of the abandoned PR #14067

# Problem

Azure Virtual network peerings require a "resync" after the address space of one
of the connected Virtual network changes. This effectively syncs the network routes
from the remote vnet to the local vnet.

Right now its not possible to trigger a resync without tainting/recreating the
peering resource.

**The resync has to be initiated on the remote peering, which further complicates things**

The API for triggering a sync is currently the same as creating/updating the
peering, with an additional URI parameter:
https://docs.microsoft.com/en-us/rest/api/virtualnetwork/virtual-network-peerings/create-or-update#uri-parameters

# Possible solutions

We discussed and I've tried a few implementations

#### Solution 1: Added a `triggers` property to the `azurerm_virtual_network_peering` resource, which for example can be used together with the `address_space` property of the peered remote vnet (resource or data source)

- Good, easy to implement, flexible to use
- Good, no dependency or cycle issues
- Good, final state can be reached in one `plan/apply`
- Bad, `triggers` is not intuitive

Example:

```terraform
resource "azurerm_resource_group" "example" {
  name     = "peeredvnets-rg"
  location = "West Europe"
}

resource "azurerm_virtual_network" "peer1" {
  name                = "peer1"
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.1.0/24"]
  location            = "West US"
}

resource "azurerm_virtual_network" "peer2" {
  name                = "peer2"
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.2.0/24", "10.0.3.0/24"]
  location            = "West US"
}

resource "azurerm_virtual_network_peering" "peer1to2" {
  name                      = "peer1to2"
  resource_group_name       = azurerm_resource_group.example.name
  virtual_network_name      = azurerm_virtual_network.example-1.name
  remote_virtual_network_id = azurerm_virtual_network.example-2.id
  triggers = {
    remote_address_space = join(",", azurerm_virtual_network.peer2.address_space)
  }
}

resource "azurerm_virtual_network_peering" "peer2to1" {
  name                      = "peer2to1"
  resource_group_name       = azurerm_resource_group.example.name
  virtual_network_name      = azurerm_virtual_network.peer2.name
  remote_virtual_network_id = azurerm_virtual_network.peer1.id
  triggers = {
    remote_address_space = join(",", azurerm_virtual_network.peer1.address_space)
  }
}
```

#### Solution 2: I've updated the `azurerm_virtual_network` resource to automatically update all remote peerings if the local `address_space` list changed.

- Good, this just works out of the box, without user interaction 
- Good, no dependency or cycle issues
- Neutral, can be implemented as opt-in feature (that's what I did)
- Really bad, this only works if the remote peering is in the same subscription, which may not always be the case

If interested, working implementation is here: https://github.com/tiwood/terraform-provider-azurerm/commit/b7f09b2aaf3884d35f4508bf3af54ebf84c984c8

#### Solution 3: Create a dedicated `azure_virtual_network_peering_sync`

- Good, makes more sense to the users than a `triggers` property
- Bad, this is basically code dup of the actual peering resource, as a resync is just a `create/update` operations which requires all properties from the peering resource (these can be discovered automatically)
- Bad, if the address space changes happen in the same configuration where this resource is located, you need more than one `plan/apply` to trigger the sync
- Neutral, would need a `triggers` property to allow for "one step" plan/apply.

Example:

```terraform
resource "azurerm_virtual_network_peering_sync" "peer1to2" {
  virtual_network_peering_id = azurerm_virtual_network_peering.peer1to2.id

  # Optional triggers
  triggers = {}
}
```

This PR implements `Solution 1`. Let me know what you guys think.

2022-05-06 07:01 UTC, tiwood commented
@tombuildsstuff, you where involved in the original PR, maybe you can find the time to take a look?

2022-05-17 15:04 UTC, tiwood commented
fyi, I've checked if the new Terraform core `replace_triggered_by` functionality makes this obsolete, but a replace means there will be a network downtime, while a simple update does not have this effect.

2022-06-29 17:28 UTC, tombuildsstuff commented
@tiwood apologies for the delayed review, we were under the impression from #14067 that the API changes potentially meant this is no longer needed - is that still the case or is this still needed?

2022-06-30 08:25 UTC, tiwood commented
@tombuildsstuff, unfortunately I was wrong and you need to trigger the re-sync actively to propagate the routes.
So a solution of any kind is still required imo.

2022-07-22 10:16 UTC, tiwood commented
@tombuildsstuff friendly ping

2023-03-06 18:46 UTC, mbfrahry requested changes
Hey @tiwood, apologies on the delay for this PR. It does look good but we should update the docs with this attribute and an example in the docs on how to use it

2023-03-09 20:58 UTC, mbfrahry commented
@tiwood, I wrote the docs/example out but have to close this as I can't push to this branch. Thank you for getting the bulk of this done and we'll get it merged with #20877

2023-03-09 20:58 UTC, closed without merging