Added client certificate exclusion paths app service setting
hashicorp/terraform-provider-azurerm pull request #16603
Opened 2022-04-29 09:30 UTC by olofattemo

Allows setting the "client_cert_exclusion_paths" on app service web and function apps as suggested in:
https://github.com/hashicorp/terraform-provider-azurerm/issues/8876

2022-05-05 23:46 UTC, katbyte requested changes
Thanks for the pr @olofattemo, overall this looks great! my only comments being that we should change the property names (left a comment inline) and that the docs need updating. once that is resolved this should be good to merge!

2022-05-05 23:46 UTC, katbyte commented on internal/services/appservice/linux_function_app_data_source.go
> +		"client_cert_exclusion_paths": {
i think we should not be abbreviating certificate?
```suggestion
		"client_certificate_exclusion_paths": {
```

2022-05-05 23:46 UTC, katbyte commented on internal/services/appservice/linux_function_app_resource.go
> +		"client_cert_exclusion_paths": {
same here

2022-05-05 23:46 UTC, katbyte commented on internal/services/appservice/linux_function_app_slot_resource.go
> +		"client_cert_exclusion_paths": {
and for the rest

2022-05-13 18:13 UTC, olofattemo commented
Thanks for the review @katbyte. Will update the docs.
Regarding the naming I definitively agree with you that to avoid ambiguity, shortening variable names should be avoided.
You may however want to consider that it could be justified in this case, or have a hint that could help me keep it tidy.
The issue is that a set of related options controlling the use of client certificate exists in the app service. It consists of three options. Two which are existing: "client_certificate_enabled" and "client_certificate_mode". The new option added by this PR "client_cert_exclusion_paths" follows the naming pattern of the current options.
Naming only the new option "client_certificate_exclusion_paths" might confuse users, and if the existing options were to be renamed the old names have to be kept as not to break compatibility. Thoughts?

2022-05-13 18:18 UTC, olofattemo commented
Ok will update the docs and change the name of the property name. Going to draft until resolved.

2022-05-19 18:48 UTC, olofattemo commented on internal/services/appservice/linux_function_app_resource.go
> +		"client_cert_exclusion_paths": {
fixed

2022-05-19 18:48 UTC, olofattemo commented on internal/services/appservice/linux_function_app_slot_resource.go
> +		"client_cert_exclusion_paths": {
fixed

2022-05-23 22:07 UTC, katbyte requested changes
Thanks @olofattemo - we definitely do try and use the name that provides the best UI. looks like we have some test failures to fix:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/1638467/169913110-128a29ad-44a4-4f29-a6f1-505bbb946ba8.png">

2022-05-24 05:21 UTC, olofattemo commented
Ok @katbyte I fixed the formatting. I assumed the fmtcheck target in the makefile would catch this but I needed to be more thorough

2022-06-09 19:14 UTC, katbyte requested changes
Thanks @olofattemo - looks like we have some test failures now thou
<img width="1570" alt="image" src="https://user-images.githubusercontent.com/1638467/172926134-c2c2fa79-5f70-4acf-919d-60b171646ffc.png">

2022-10-12 08:01 UTC, jackofallops commented
Hi @olofattemo - Hope you don't mind, but I pushed some changes to your branch to resolve the merge conflicts and fix the test issues. I'll loop back asap to re-review.

2022-10-18 05:02 UTC, katbyte approved these changes
LGTM 🍄

2022-10-18 05:32 UTC, merged