add storage account config to function apps
hashicorp/terraform-provider-azurerm pull request #16684
Opened 2022-05-06 12:32 UTC by Benedikt-Fuchs-Crayon

adds support for storage_account blocks in azurerm_<os>_function_app as described in https://github.com/hashicorp/terraform-provider-azurerm/issues/6790
also fixing a small copy paste mistake, where a error message falsely claims the wrong os

2022-06-09 18:55 UTC, katbyte requested changes
Thanks @Benedikt-Fuchs-Crayon  - looks like we have some test failures to fix thou:

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/1638467/172923113-ac8b86af-a198-45a8-9233-61b3c219019a.png">

2022-07-04 07:14 UTC, jackofallops requested changes
Hi @Benedikt-Fuchs-Crayon 
Thanks for the changes, there's just a couple test config changes needed and I think this is good to go. 

Thanks!

2022-07-04 07:14 UTC, jackofallops commented on internal/services/appservice/windows_function_app_resource_test.go
> +    mount_path   = "/files"
This needs to be a path below `mounts` for Windows functions:

```
Details=[{"Message":"The parameter 'AzureStoragePropertyDictionary' has an invalid value.

...

MountPath: /files. MountPath must be sub-directory of \\mounts."}
```

2022-07-04 07:14 UTC, jackofallops commented on internal/services/appservice/windows_function_app_resource_test.go
> +    mount_path   = "/blob"
As above.

2022-07-04 07:56 UTC, Benedikt-Fuchs-Crayon commented
thank you for the feedback,
I changed the paths to `\\mounts\\files` and `\\mounts/blob` respectively

2022-09-04 01:21 UTC, katbyte requested changes
Thanks @Benedikt-Fuchs-Crayon - still seeing some test failures related to this pr:

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/1638467/188293083-a2a9d5e5-652f-465d-9555-6994e8a8f5a0.png">

2022-10-14 05:33 UTC, jackofallops commented
Hi @Benedikt-Fuchs-Crayon - To resolve the conflicts and extend the feature to slots I've pulled your changes onto a new branch/PR (I was unable to safely push to your fork as the PR originated from your `main` branch, sorry 🙈 ). I'm going to close this PR in favour of the new one, where I've kept as much as I can of your code while resolving the conflicts and extending the functionality to slots.

Thanks again for the contribution, and apologies for the delays in getting back to this!

2022-10-14 05:33 UTC, closed without merging