update containerservice sdk to 2022-03-02-preview
hashicorp/terraform-provider-azurerm pull request #16698
Opened 2022-05-07 03:05 UTC by ms-henglu

2022-05-09 07:57 UTC, stephybun requested changes

2022-05-09 07:57 UTC, stephybun commented on internal/services/containers/kubernetes_cluster_node_pool_resource.go
> +	future, err := client.Delete(ctx, id.ResourceGroup, id.ManagedClusterName, id.AgentPoolName, nil)
We should be defaulting this toggle to `true`

2022-05-09 07:57 UTC, stephybun commented on internal/services/containers/kubernetes_cluster_resource.go
> +	future, err := client.Delete(ctx, id.ResourceGroup, id.ManagedClusterName, nil)
Same here

2022-05-09 08:01 UTC, ms-henglu commented
Hi @stephybun , I've changed them to true, would you please take another look? Thanks!

2022-05-12 06:35 UTC, stephybun reviewed
There seem to be new test failures as a result of the upgrade that are not happening on main
```
------- Stdout: -------
=== RUN   TestAccKubernetesCluster_addonProfileIngressApplicationGateway_subnetCIDR
=== PAUSE TestAccKubernetesCluster_addonProfileIngressApplicationGateway_subnetCIDR
=== CONT  TestAccKubernetesCluster_addonProfileIngressApplicationGateway_subnetCIDR
testcase.go:110: Step 1/4 error: Error running apply: exit status 1
Error: creating Cluster: (Managed Cluster Name "acctestaks220509082729837134" / Resource Group "acctestRG-aks-220509082729837134"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="IngressAppGwAddonConfigInvalidSubnetCIDRNotContainedWithinVirtualNetwork" Message="Subnet Prefix '10.241.0.0/16' specified for IngressApplicationGateway addon is not contained within the AKS Agent Pool's Virtual Network address prefixes '[10.224.0.0/12]'." Target="AddonProfiles.IngressApplicationGateway"
with azurerm_kubernetes_cluster.test,
on terraform_plugin_test.tf line 11, in resource "azurerm_kubernetes_cluster" "test":
11: resource "azurerm_kubernetes_cluster" "test" {
--- FAIL: TestAccKubernetesCluster_addonProfileIngressApplicationGateway_subnetCIDR (125.31s)
FAIL
```

```
------- Stdout: -------
=== RUN   TestAccDataSourceKubernetesCluster_addOnProfileIngressApplicationGatewaySubnetCIDR
=== PAUSE TestAccDataSourceKubernetesCluster_addOnProfileIngressApplicationGatewaySubnetCIDR
=== CONT  TestAccDataSourceKubernetesCluster_addOnProfileIngressApplicationGatewaySubnetCIDR
testcase.go:110: Step 1/1 error: Error running apply: exit status 1
Error: creating Cluster: (Managed Cluster Name "acctestaks220509101114912432" / Resource Group "acctestRG-aks-220509101114912432"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="IngressAppGwAddonConfigInvalidSubnetCIDRNotContainedWithinVirtualNetwork" Message="Subnet Prefix '10.241.0.0/16' specified for IngressApplicationGateway addon is not contained within the AKS Agent Pool's Virtual Network address prefixes '[10.224.0.0/12]'." Target="AddonProfiles.IngressApplicationGateway"
with azurerm_kubernetes_cluster.test,
on terraform_plugin_test.tf line 12, in resource "azurerm_kubernetes_cluster" "test":
12: resource "azurerm_kubernetes_cluster" "test" {
--- FAIL: TestAccDataSourceKubernetesCluster_addOnProfileIngressApplicationGatewaySubnetCIDR (129.39s)
FAIL
```

2022-05-12 09:15 UTC, ms-henglu commented
@stephybun - thanks for pointing it out, I've fixed the testcases.

2022-05-12 17:48 UTC, katbyte requested changes
As we are updating the SDK can we please try and fix all the test failures?

<img width="693" alt="image" src="https://user-images.githubusercontent.com/1638467/168137292-5a6baba3-9fbc-44ad-967b-08b328fc7eea.png">

2022-05-24 02:22 UTC, ms-henglu commented
Hi @katbyte , would you please take another look? I've fixed the most of the test cases.

2022-05-26 04:13 UTC, katbyte commented
Still have some test failures, some of which first occurrence was this pr: 
<img width="612" alt="image" src="https://user-images.githubusercontent.com/1638467/170414489-3b2a9098-a921-4f6d-af5e-b2f49b35f84a.png">

2022-05-27 05:07 UTC, ms-henglu commented
Hi @katbyte - in another build, is it good to go? Because some of failed cases are caused by preview feature not enabled, and others seem to be temporary failure?
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/79895375/170633137-8f89e1b4-4aee-46a7-8058-11bb7465b851.png">

2022-06-01 00:41 UTC, katbyte commented
these failures are pretty consistent:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/1638467/171305681-a13c0a3c-9d4d-41c7-a8c0-eb349c289f3e.png">

could we please fix them? as for features the docs should have the required powershell to enable them (and if not it should be added) - paste it here and i'll get them enabled on the test subscription

thanks

2022-06-06 02:21 UTC, ms-henglu commented
hi @katbyte , would you please help register the following features?
```
Microsoft.ContainerService/AKS-AzureDefender
Microsoft.ContainerService/AKS-EnableDualStack
```

2022-06-07 06:34 UTC, ms-henglu commented
@katbyte - thanks for the code review, but I'll close this PR because there're no required features pending on this api-version. I opened another PR fixing the failed tests: https://github.com/hashicorp/terraform-provider-azurerm/pull/17124

2022-06-07 06:34 UTC, closed without merging