new resource `azurerm_spring_cloud_api_portal`
hashicorp/terraform-provider-azurerm pull request #16719
Opened 2022-05-10 02:37 UTC by ms-henglu

2022-05-13 01:47 UTC, katbyte requested changes
test failures:
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/1638467/168195026-0722ff24-a030-4964-802c-86f99e086f4f.png">

2022-05-13 01:47 UTC, katbyte commented on website/docs/r/spring_cloud_api_portal.html.markdown
> +* `https_only` - (Optional) is only https is allowed?
shoudl this be?
```suggestion
* `https_only_enabled` - (Optional) is only https is allowed?
```

2022-05-13 04:05 UTC, ms-henglu commented
@katbyte - I've fixed the testcases, and renamed the field, please take another look, thanks!
![image](https://user-images.githubusercontent.com/79895375/168209159-2ce89ab4-a147-4839-9a33-32c85deb1d80.png)

2022-05-26 05:12 UTC, katbyte approved these changes
Thanks @ms-henglu - LGTM 🍾

2022-05-26 05:12 UTC, merged