Azure kusto service upgrade sdk to version 2022-02-01
hashicorp/terraform-provider-azurerm pull request #16859
Opened 2022-05-19 01:29 UTC by liuwuliuyun

Upgrade kusto sdk version to latest and prepare for adding new properties.

2022-05-20 05:56 UTC, liuwuliuyun commented
![MicrosoftTeams-image](https://user-images.githubusercontent.com/17947406/169460343-7b6ef128-b294-465d-8115-250790a86067.png)
Regression test evidence.

2022-05-20 05:57 UTC, liuwuliuyun commented
FYI, the vnet test fail is not due to the version update, it is an exsiting bug on our main branch before updating.

2022-05-26 05:12 UTC, ms-henglu commented
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/79895375/170420409-30aa9841-e5c5-4967-9cdc-afd9420e081d.png">

There's a failed test, but it's a temporary failure, no need to worry.

2022-05-30 02:00 UTC, liuwuliuyun commented
Rerun above and pass
![image](https://user-images.githubusercontent.com/17947406/170903789-c13b4098-2577-4d0f-bc4d-345b5dbe21fd.png)

2022-06-13 03:17 UTC, liuwuliuyun commented
> We still have a test failure here:
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccKustoCluster_zones
> === PAUSE TestAccKustoCluster_zones
> === CONT  TestAccKustoCluster_zones
>     testcase.go:110: Step 1/1 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
>         stdout
>         
>         
>         Terraform used the selected providers to generate the following execution
>         plan. Resource actions are indicated with the following symbols:
>         -/+ destroy and then create replacement
>         
>         Terraform will perform the following actions:
>         
>           # azurerm_kusto_cluster.test must be replaced
>         -/+ resource "azurerm_kusto_cluster" "test" {
>               ~ data_ingestion_uri            = "https://ingest-acctestkchfjj2.eastus2.kusto.windows.net/" -> (known after apply)
>               - double_encryption_enabled     = false -> null
>               ~ id                            = "/subscriptions/*******/resourceGroups/acctestRG-220608200522335526/providers/Microsoft.Kusto/Clusters/acctestkchfjj2" -> (known after apply)
>               - language_extensions           = [] -> null
>                 name                          = "acctestkchfjj2"
>               - tags                          = {} -> null
>               ~ trusted_external_tenants      = [] -> (known after apply)
>               ~ uri                           = "https://acctestkchfjj2.eastus2.kusto.windows.net/" -> (known after apply)
>               ~ zones                         = [ # forces replacement
>                   - "1",
>                   + "3",
>                 ]
>                 # (8 unchanged attributes hidden)
>         
>                 # (1 unchanged block hidden)
>             }
>         
>         Plan: 1 to add, 0 to change, 1 to destroy.
> --- FAIL: TestAccKustoCluster_zones (1266.27s)
> FAIL
> ```

I have checked this one, this is related to kusto service API behavior and I will reach out to them to see what is the expected behavior of this API and determine whether this is suitable for us to add this "zone" property to azure provider of terraform.

2022-06-13 03:17 UTC, liuwuliuyun commented
The API behavior is unstable from my test case, so I will mark this PR as draft for now until I heard from kusto service team.

2022-06-20 07:48 UTC, liuwuliuyun commented
Just got confirmation from kusto service team that they are aware of this bug and will fix in 1~2 weeks. When they perform the fix,  the failed test case will pass automatically. As a result, I reopen the MR for review.

2022-06-29 14:20 UTC, tombuildsstuff requested changes
hey @liuwuliuyun 

Thanks for pushing those changes - apologies for the delayed re-review here.

Taking a look through this it appears there's one thing to fix, but if we can fix that up then this should otherwise be good to go 👍 

Thanks!

2022-07-01 01:49 UTC, liuwuliuyun commented on internal/services/kusto/kusto_cluster_resource_test.go
> +    }
Oh, this is not needed now, to keep our commit history clean, I raise a new PR https://github.com/hashicorp/terraform-provider-azurerm/pull/17457. Actually, the service team is making a release now and once their service is released, I will provide clean test results on that new PR.

2022-07-01 01:52 UTC, liuwuliuyun commented
Close this PR to keep up with latest upgrade with new PR after kusto service team complete release.

2022-07-01 01:52 UTC, closed without merging