`azurerm_spring_cloud_service`: Add `zone_redundant` property
hashicorp/terraform-provider-azurerm pull request #16872
Opened 2022-05-19 13:26 UTC by favoretti

Fixes #16871

```
$ TF_ACC=1 go test -v ./internal/services/springcloud -timeout=1000m -run='TestAccSpringCloudService_complete'
=== RUN   TestAccSpringCloudService_complete
=== PAUSE TestAccSpringCloudService_complete
=== CONT  TestAccSpringCloudService_complete
--- PASS: TestAccSpringCloudService_complete (528.85s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/springcloud	529.925s
```

2022-05-19 14:39 UTC, favoretti commented
TC "passed" with 1 failure that's unrelated.

2022-05-19 22:35 UTC, mbfrahry requested changes
Hey @favoretti, this looks good but it'll cause a breaking change as is. More info below

2022-05-19 22:35 UTC, mbfrahry commented on website/docs/r/spring_cloud_service.html.markdown
> +* `zone_redundant` - (Optional) Whether zone redundancy is enabled for this Spring Cloud Service.
We'll want to add the default here too.

2022-05-20 16:08 UTC, mbfrahry requested changes
Ack! My bad @favoretti. The main comment didn't go through

2022-05-20 16:08 UTC, mbfrahry commented on internal/services/springcloud/spring_cloud_service_resource.go
> +				Default:  true,
This is a breaking change since we don't pass this in now and it gets defaulted to false

2022-05-20 16:34 UTC, mbfrahry commented
So I'm just building a basic spring cloud service with the current version of the provider and seeing what is returned from the API. 

Running `TestAccSpringCloudService_basic` sends the following to the API:

```
{
	"location": "francecentral",
	"properties": {},
	"sku": {
		"name": "S0"
	},
	"tags": {}
}
```

The api returns:

```
	"zoneRedundant": false,
```

2022-05-21 14:57 UTC, favoretti commented
Hrm. Interesting. I'll retest on Monday. Thanks!

2022-05-25 22:11 UTC, mbfrahry approved these changes
LGTM!

2022-05-25 22:12 UTC, merged