`synapse` - `docs example improvement`
hashicorp/terraform-provider-azurerm pull request #17071
Opened 2022-06-02 03:49 UTC by shu-ying789

2022-06-02 07:16 UTC, stephybun requested changes

2022-06-02 07:16 UTC, stephybun commented on website/docs/r/synapse_sql_pool_vulnerability_assessment.html.markdown
> +}
I don't see this referenced anywhere else in the example config so why are we adding this here?

2022-06-02 07:16 UTC, stephybun commented on website/docs/r/synapse_workspace_vulnerability_assessment.html.markdown
> +
Same here

2022-06-06 03:16 UTC, shu-ying789 commented
@stephybun I added this resource because it is referenced by storage_container_path.

2022-06-06 06:25 UTC, stephybun approved these changes
LGTM 🥟

2022-06-06 06:25 UTC, merged