New Data Source/Resource: `azurerm_cdn_frontdoor_rule_set`
hashicorp/terraform-provider-azurerm pull request #17094
Opened 2022-06-03 13:12 UTC by tombuildsstuff

This PR introduces a new Data Source/Resource for `azurerm_cdn_frontdoor_rule_set` - split out from #16671

2022-06-03 18:03 UTC, mbfrahry requested changes
This is mostly good except for the datasource not following the `cdn_frontdoor_profile_id` of the resource

2022-06-04 02:52 UTC, WodansSon approved these changes
LGTM! 🚀

2022-06-07 08:11 UTC, tombuildsstuff commented on internal/services/cdn/cdn_frontdoor_rule_set_data_source.go
> +			"cdn_frontdoor_profile_id": {
nope, that's intentional since users may be referencing the Rule Set without the parents details

2022-06-09 19:02 UTC, mbfrahry approved these changes
LGTM!

2022-06-09 19:02 UTC, merged