Doc Fix : azurerm_subnet - Add note to address_prefixes that "AllowMultipleAddressPrefixesOnSubnet" is currently not supported
hashicorp/terraform-provider-azurerm pull request #17109
Opened 2022-06-06 07:32 UTC by sinbai

Although I didn't find any documentation stating that `address_prefixes` doesn't support multiple prefixes. However, someone ever mentioned "The feature AllowMultipleAddressPrefixesOnSubnet is not available for public as of now", [here ](https://github.com/Azure/azure-cli/issues/18194#issuecomment-880484269) is the link. So I assume we should add a comment explaining it to fix issue [#17052](https://github.com/hashicorp/terraform-provider-azurerm/issues/17052), WDYT?

2022-06-08 03:35 UTC, katbyte requested changes

2022-06-08 03:35 UTC, katbyte commented on website/docs/r/subnet.html.markdown
> +-> **NOTE:** The feature of `AllowMultipleAddressPrefixesOnSubnet` is not available for public as of now, so `address_prefixes` only supports setting one address prefix.
could we fix the grammar for this?
```suggestion
-> **NOTE:** Currently only a single address prefix can be set as the [Multiple Subnet Address Prefixes Feature](put-a-url-to-something-describing-it) is not yet in public preview or general availability.
```

2022-06-08 03:56 UTC, sinbai commented on website/docs/r/subnet.html.markdown
> +-> **NOTE:** The feature of `AllowMultipleAddressPrefixesOnSubnet` is not available for public as of now, so `address_prefixes` only supports setting one address prefix.
Thank you. Fixed.

2022-06-26 20:52 UTC, stephybun approved these changes
Thanks @sinbai, LGTM 👍

2022-06-26 20:52 UTC, merged