`docs example improvement`-` 30 file part1`
hashicorp/terraform-provider-azurerm pull request #17237
Opened 2022-06-14 06:47 UTC by heiazuo

public pr for `docs example improvement`-` 30 file part1`

2022-06-14 06:57 UTC, ms-henglu requested changes

2022-06-14 06:57 UTC, ms-henglu commented on website/docs/r/cosmosdb_account.html.markdown
> +    location          = azurerm_resource_group.example.location
This should be another location.

2022-06-14 06:57 UTC, ms-henglu commented on website/docs/r/data_factory_custom_dataset.html.markdown
> +
This new line should be removed.

2022-06-14 06:57 UTC, ms-henglu commented on website/docs/r/disk_encryption_set.html.markdown
> +    "Purge",
Does this resource requires these permissions?

2022-06-15 11:06 UTC, katbyte approved these changes
LGTM 💯

2022-06-15 11:06 UTC, merged