`azurerm_storage_account` - support disable `blob_properties.0.{delete_retention_policy|container_delete_retention_policy}` & `share_properties.0.retention_policy`
hashicorp/terraform-provider-azurerm pull request #17256
Opened 2022-06-15 02:50 UTC by magodo

Fix #17204

The original issue seems was introduced since https://github.com/hashicorp/terraform-provider-azurerm/pull/11960/files#diff-2c154d637b511904ff11c516331a83f1e3b17cd85d601fd0fc21556fbdfb5a31R1870. This change seems out of topic of that original PR. So I've just reverted that back and verified the expected behavior about disabling the soft delete in the acctest.

## Test

```shell
💤  TF_ACC=1 go test -v -timeout=20h ./internal/services/storage -run='TestAccAzureRMStorageAccount_shareSoftDelete'
=== RUN   TestAccAzureRMStorageAccount_shareSoftDelete
=== PAUSE TestAccAzureRMStorageAccount_shareSoftDelete
=== CONT  TestAccAzureRMStorageAccount_shareSoftDelete
--- PASS: TestAccAzureRMStorageAccount_shareSoftDelete (376.53s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/storage       376.538s

💤  TF_ACC=1 go test -v -timeout=20h ./internal/services/storage -run='TestAccStorageAccount_blobProperties'
=== RUN   TestAccStorageAccount_blobProperties
=== PAUSE TestAccStorageAccount_blobProperties
=== RUN   TestAccStorageAccount_blobProperties_containerAndLastAccessTimeDisabled
=== PAUSE TestAccStorageAccount_blobProperties_containerAndLastAccessTimeDisabled
=== RUN   TestAccStorageAccount_blobPropertiesEmptyAllowedExposedHeaders
=== PAUSE TestAccStorageAccount_blobPropertiesEmptyAllowedExposedHeaders
=== CONT  TestAccStorageAccount_blobProperties
=== CONT  TestAccStorageAccount_blobPropertiesEmptyAllowedExposedHeaders
=== CONT  TestAccStorageAccount_blobProperties_containerAndLastAccessTimeDisabled
--- PASS: TestAccStorageAccount_blobProperties_containerAndLastAccessTimeDisabled (129.19s)
--- PASS: TestAccStorageAccount_blobPropertiesEmptyAllowedExposedHeaders (152.47s)
--- PASS: TestAccStorageAccount_blobProperties (170.18s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/storage       170.195s
```

2022-06-24 19:10 UTC, brad-vendia commented
@magodo thanks for the fix. What's the process for getting this live, and will this change also be applied to v2.99?

2022-06-24 19:12 UTC, brad-lucas commented
@magodo thanks for the fix!

- What's missing to get this merged and live?
- Will this fix also be applied to v2.99?
    - We're currently unable to upgrade to v3+ as we're using the azurerm provider via CDKTF and are awaiting a pre-generated package on pypi

2022-06-25 00:03 UTC, magodo commented
@katbyte Can you take a look at this PR?

@brad-lucas I don't think we will make a separate release for v2.99. Whilst you might be able to cherry pick this commit on top of v2.99 and make a private build.

2022-06-27 16:08 UTC, katbyte requested changes
Have some test failureS:
```
<div class="rightBlock expandedDetails" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; float: right; background-color: rgba(245, 245, 245, 0.81); border-left-width: 5px; border-left-style: solid; border-left-color: rgb(255, 255, 255); border-bottom-width: 5px; border-bottom-style: solid; border-bottom-color: rgb(255, 255, 255); caret-color: rgb(31, 35, 38); color: rgb(31, 35, 38); font-family: system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 13px;"><br class="Apple-interchange-newline"><div class="icon_before icon16 collapser collapser_expanded" title="Click to hide the details block" style="float: right; height: 2em; padding: 5px; cursor: pointer;"></div><div class="relatedBuildsWrapper" style="border-right-width: 3px; border-right-style: solid; border-right-color: white; float: right;">

  | First failure: |   | #810 | wztdyl (2) | 15 Jun 22 11:01
-- | -- | -- | -- | -- | --


<div id="div_iaa_17c33809e6d"></div></div></div><span style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(31, 35, 38); color: rgb(31, 35, 38); font-family: system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 13px; background-color: rgb(255, 255, 255); float: none; display: inline !important;"></span><span style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(31, 35, 38); color: rgb(31, 35, 38); font-family: system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 13px; background-color: rgb(255, 255, 255); float: none; display: inline !important;"></span><div class="testMetadata" id="testMetadata_tdi_17c33809e6b" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(31, 35, 38); color: rgb(31, 35, 38); font-family: system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 13px;"></div><pre class="fullStacktrace" id="fullStacktrace_301970_-1083011438371632074" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; font-stretch: normal; font-size: 12px; line-height: 1.2em; font-family: Menlo, &quot;Bitstream Vera Sans Mono&quot;, &quot;Ubuntu Mono&quot;, Consolas, &quot;Courier New&quot;, Courier, monospace; padding: 3px 3px 0px; color: darkred; margin-top: 0.5em; margin-bottom: 0.5em; white-space: pre-wrap; overflow-wrap: break-word;">------- Stdout: -------
=== RUN   TestAccStorageAccount_updateToUsingIdentityAndCustomerManagedKey
=== PAUSE TestAccStorageAccount_updateToUsingIdentityAndCustomerManagedKey
=== CONT  TestAccStorageAccount_updateToUsingIdentityAndCustomerManagedKey
    testcase.go:110: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) (len=5) {
         (string) (len=18) "share_properties.#": (string) (len=1) "1",
         (string) (len=20) "share_properties.0.%": (string) (len=1) "3",
         (string) (len=37) "share_properties.0.retention_policy.#": (string) (len=1) "1",
         (string) (len=39) "share_properties.0.retention_policy.0.%": (string) (len=1) "1",
         (string) (len=42) "share_properties.0.retention_policy.0.days": (string) (len=1) "7"
        }
        
        
        (map[string]string) {
        }
--- FAIL: TestAccStorageAccount_updateToUsingIdentityAndCustomerManagedKey (514.26s)
FAIL
</pre><a href="https://ci-oss.hashicorp.engineering/viewLog.html?buildId=301970&amp;#" class="hideStacktrace" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; color: rgb(15, 91, 153); text-decoration: none; padding-top: 0.5em; margin-right: 1em; display: inline-block; font-family: system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 13px;"></a><br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><br class="Apple-interchange-newline">First failure: 	refs/pull/17256/merge	[#810 ](https://ci-oss.hashicorp.engineering/viewLog.html?buildId=301970&tab=buildResultsDiv&buildTypeId=TerraformOpenSource_TerraformProviders_AzureRMPublic_AZURERM_SERVICE_PUBLIC_STORAGE) 	[wztdyl (2)](https://ci-oss.hashicorp.engineering/viewLog.html?buildId=301970&tab=buildChangesDiv&buildTypeId=TerraformOpenSource_TerraformProviders_AzureRMPublic_AZURERM_SERVICE_PUBLIC_STORAGE) 	15 Jun 22 11:01
 ------- Stdout: -------
=== RUN   TestAccStorageAccount_updateToUsingIdentityAndCustomerManagedKey
=== PAUSE TestAccStorageAccount_updateToUsingIdentityAndCustomerManagedKey
=== CONT  TestAccStorageAccount_updateToUsingIdentityAndCustomerManagedKey
    testcase.go:110: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) (len=5) {
         (string) (len=18) "share_properties.#": (string) (len=1) "1",
         (string) (len=20) "share_properties.0.%": (string) (len=1) "3",
         (string) (len=37) "share_properties.0.retention_policy.#": (string) (len=1) "1",
         (string) (len=39) "share_properties.0.retention_policy.0.%": (string) (len=1) "1",
         (string) (len=42) "share_properties.0.retention_policy.0.days": (string) (len=1) "7"
        }
        
        
        (map[string]string) {
        }
--- FAIL: TestAccStorageAccount_updateToUsingIdentityAndCustomerManagedKey (514.26s)
FAIL
```

2022-06-28 02:13 UTC, magodo commented
@katbyte That's weired. I've locally ran again both in current head and with main branch merged, all successfully. Also, I've ensure the primary location is west europe.

2022-07-07 10:22 UTC, magodo commented
@katbyte Can we continue reviewing above change? I recently observed that the failed test case also appears intermittently in main branch.

2022-07-14 21:13 UTC, katbyte commented
@magodo - its popping up fairly regularly so would be great to fix it, but at the very least can you create an issue on the rest spec detailing what the issue is and link it here?

2022-07-20 04:04 UTC, katbyte approved these changes
LGTM 🌵

2022-07-20 04:04 UTC, merged