fixing dotnet core version issue for resource `azurerm_windows_web_app`
hashicorp/terraform-provider-azurerm pull request #17285
Opened 2022-06-17 07:28 UTC by xiaxyi

The dotnet core web app version is not controlled by the property .NETFrameworkVersion, thus, not to set the version to an unsupported .net framework version such as v3.0

fixing the issue: #16867 #17232

2022-06-24 04:03 UTC, JohnBoneJones commented
May I set current_stack  = "dotnetcore", dotnet_version = "core3.1" in next version?

2022-06-24 04:10 UTC, JohnBoneJones commented
How can I set  dotnet_version = "core3.1" for azurerm_windows_web_app

2022-06-28 01:54 UTC, xiaxyi commented
> May I set current_stack = "dotnetcore", dotnet_version = "core3.1" in next version and How can I set dotnet_version = "core3.1" for azurerm_windows_web_app?

For asp.net runtime stack, you don't need to set the dotnet_version to core 3.1 as there is no 3.1 version of CLR (you can refer to ). Core3.1 is provided for dotnet core runtime. you can refer to this doc for the version and clr dependency:https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies

2022-06-28 18:52 UTC, katbyte requested changes

2022-06-28 18:52 UTC, katbyte commented on internal/services/appservice/helpers/web_app_schema.go
> -						"v3.0",
i'm afraid we can't just remove this value, could we add it back in and conditionally remove it when the 4.0 flag is enabled? thanks

2022-06-30 05:57 UTC, xiaxyi commented
@katbyte Thanks for the comments, changed the code.

2022-07-28 23:07 UTC, katbyte approved these changes
Thanks @xiaxyi - LGTM 🦕

2022-07-28 23:08 UTC, merged