`azurerm_kubernetes_cluster` update document
hashicorp/terraform-provider-azurerm pull request #17299
Opened 2022-06-20 07:08 UTC by shu-ying789

linked to :https://github.com/hashicorp/terraform-provider-azurerm/issues/16890

2022-06-20 12:26 UTC, stephybun requested changes

2022-06-20 12:26 UTC, stephybun commented on website/docs/d/kubernetes_cluster.html.markdown
> +-> **NOTE:** Currently only support 1 User Assigned Identity.
```suggestion
-> **Note:** Currently only one User Assigned Identity is supported.

2022-06-21 02:58 UTC, shu-ying789 commented
@stephybun I have modified it, please check again, thank you.

2022-06-21 06:19 UTC, stephybun approved these changes
Thanks @shu-ying789! LGTM 🍌

2022-06-21 06:20 UTC, merged