`r\shared_image`: support `end_of_life_date` `disallowed_disk_types` `[max|min]_recommended_[vcpu_count|memory_in_gb]`
hashicorp/terraform-provider-azurerm pull request #17300
Opened 2022-06-20 09:12 UTC by myc2h6o

Properties are from https://docs.microsoft.com/en-us/azure/virtual-machines/shared-image-galleries?tabs=azure-cli#image-definitions

2022-06-20 09:34 UTC, myc2h6o commented
Test result:
![image](https://user-images.githubusercontent.com/10579712/174572377-5c80b033-ea0e-4385-b3d6-5f98da059e74.png)

2022-07-06 00:27 UTC, katbyte requested changes

2022-07-06 00:27 UTC, katbyte commented on internal/services/compute/shared_image_resource.go
> +			"disallowed_disk_types": {
could we change this to 
```suggestion
			"disk_types_not_allowed": {
```

```suggestion
			"disallowed_disk_types": {
```

2022-07-06 08:17 UTC, myc2h6o commented on internal/services/compute/shared_image_resource.go
> +			"disallowed_disk_types": {
Updated

2022-07-06 08:17 UTC, myc2h6o commented
Hi @katbyte thanks for reviewing the pr! I've updated the property name, could you take another look?

2022-07-06 13:01 UTC, myc2h6o commented
Updated test result
![image](https://user-images.githubusercontent.com/10579712/177556139-16567df0-b3bb-43e1-8f60-452434582993.png)

2022-07-11 02:57 UTC, katbyte approved these changes
LGTM 🌻

2022-07-11 02:57 UTC, merged