`d/shared_image_version`: fix `id`
hashicorp/terraform-provider-azurerm pull request #17332
Opened 2022-06-22 06:31 UTC by myc2h6o

Fix #17307. id seems to be set to `latest` by mistake in [this change](https://github.com/hashicorp/terraform-provider-azurerm/pull/14934/files#diff-12e064c48daacb4c1b9cb364b8c84324c957c44bf2ea72af2d0f41ab3dc9dcf6), updating it with the exact version name retrieved from the image version.

2022-06-22 13:47 UTC, myc2h6o commented
Test result
![image](https://user-images.githubusercontent.com/10579712/175044822-b0396d92-2f52-4194-abbe-5961e5351f71.png)

2022-06-27 20:08 UTC, mbfrahry requested changes
Hey @myc2h6o, this looks good but we do have to do a nil check so we don't crash

2022-06-27 20:08 UTC, mbfrahry commented on internal/services/compute/shared_image_version_data_source.go
> +	exactId := parse.NewSharedImageVersionID(subscriptionId, id.ResourceGroup, id.GalleryName, id.ImageName, *image.Name)
We need to confirm that `*image.Name` isn't `nil` before casting to it

2022-06-28 08:51 UTC, myc2h6o commented
Hi @mbfrahry thanks for reviewing the change! I've added the nil validation for image.Name, could you take another look?

2022-06-28 13:32 UTC, myc2h6o commented
Updated test result
![image](https://user-images.githubusercontent.com/10579712/176191409-413bf952-ca48-42cb-adba-aa4039a56fc5.png)

2022-07-05 15:44 UTC, katbyte approved these changes
LGTM 🌻

2022-07-05 15:44 UTC, merged