HDInsight clusters add support for `disk_encryption_properties` block
hashicorp/terraform-provider-azurerm pull request #17351
Opened 2022-06-23 08:42 UTC by jiaweitao001

* Add support for `disk_encryption_properties` to reach 100% coverage for HDInsight service.

* All tests passed.

2022-06-28 18:51 UTC, katbyte requested changes
test failures:
```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccHDInsightInteractiveQueryCluster_tls
=== PAUSE TestAccHDInsightInteractiveQueryCluster_tls
=== CONT  TestAccHDInsightInteractiveQueryCluster_tls

------- Stderr: -------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x42cac54]

goroutine 430 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/hdinsight.resourceHDInsightInteractiveQueryClusterRead(0xc0029e6080, {0x5777380?, 0xc000e7b180?})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/services/hdinsight/hdinsight_interactive_query_cluster_resource.go:355 +0xdf4
github.com/hashicorp/terraform-provider-azurerm/internal/services/hdinsight.resourceHDInsightInteractiveQueryClusterCreate(0x0?, {0x5777380?, 0xc000e7b180})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/services/hdinsight/hdinsight_interactive_query_cluster_resource.go:281 +0x1f07
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc002c21560?, {0x68b3c70?, 0xc00298b7c0?}, 0x2?, {0x5777380?, 0xc000e7b180?})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0007a35e0, {0x68b3c70, 0xc00298b7c0}, 0xc0029c7040, 0xc0034ddf00, {0x5777380, 0xc000e7b180})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:467 +0x6f1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0027c80f0, {0x68b3c70, 0xc00298b7c0}, 0xc001359180)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001a1a00, {0x68b3d18?, 0xc002993e60?}, 0xc001269b20)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:603 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x5d215c0?, 0xc0001a1a00}, {0x68b3d18, 0xc002993e60}, 0xc0029ba0c0, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002d6c40, {0x68c5460, 0xc001d3a780}, 0xc0029b4480, 0xc000e5a180, 0xa9783a0, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc0002d6c40, {0x68c5460, 0xc001d3a780}, 0xc0029b4480, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1617 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:938 +0x28a

```

2022-06-29 06:58 UTC, jiaweitao001 commented
> test failures:
> 
> ```
> Test ended in panic.
> 
> ------- Stdout: -------
> === RUN   TestAccHDInsightInteractiveQueryCluster_tls
> === PAUSE TestAccHDInsightInteractiveQueryCluster_tls
> === CONT  TestAccHDInsightInteractiveQueryCluster_tls
> 
> ------- Stderr: -------
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x42cac54]
> 
> goroutine 430 [running]:
> github.com/hashicorp/terraform-provider-azurerm/internal/services/hdinsight.resourceHDInsightInteractiveQueryClusterRead(0xc0029e6080, {0x5777380?, 0xc000e7b180?})
> 	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/services/hdinsight/hdinsight_interactive_query_cluster_resource.go:355 +0xdf4
> github.com/hashicorp/terraform-provider-azurerm/internal/services/hdinsight.resourceHDInsightInteractiveQueryClusterCreate(0x0?, {0x5777380?, 0xc000e7b180})
> 	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/services/hdinsight/hdinsight_interactive_query_cluster_resource.go:281 +0x1f07
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc002c21560?, {0x68b3c70?, 0xc00298b7c0?}, 0x2?, {0x5777380?, 0xc000e7b180?})
> 	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:329 +0x178
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0007a35e0, {0x68b3c70, 0xc00298b7c0}, 0xc0029c7040, 0xc0034ddf00, {0x5777380, 0xc000e7b180})
> 	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:467 +0x6f1
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0027c80f0, {0x68b3c70, 0xc00298b7c0}, 0xc001359180)
> 	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:977 +0xd8a
> github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001a1a00, {0x68b3d18?, 0xc002993e60?}, 0xc001269b20)
> 	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:603 +0x2ad
> github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x5d215c0?, 0xc0001a1a00}, {0x68b3d18, 0xc002993e60}, 0xc0029ba0c0, 0x0)
> 	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
> google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002d6c40, {0x68c5460, 0xc001d3a780}, 0xc0029b4480, 0xc000e5a180, 0xa9783a0, 0x0)
> 	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
> google.golang.org/grpc.(*Server).handleStream(0xc0002d6c40, {0x68c5460, 0xc001d3a780}, 0xc0029b4480, 0x0)
> 	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1617 +0xa1b
> google.golang.org/grpc.(*Server).serveStreams.func1.2()
> 	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:940 +0x98
> created by google.golang.org/grpc.(*Server).serveStreams.func1
> 	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:938 +0x28a
> ```

The failing tests are fixed. Thanks.

2022-07-14 20:35 UTC, katbyte requested changes
Thanks @jiaweitao001 - i've reviewed the schema and left some suggestions inline, let me know what you think

2022-07-14 20:35 UTC, katbyte commented on internal/services/hdinsight/hdinsight_hadoop_cluster_resource.go
> +			"disk_encryption_properties": SchemaHDInsightsDiskEncryptionProperties(),
i think properties is redundant?
```suggestion
			"disk_encryption": SchemaHDInsightsDiskEncryptionProperties(),
```

2022-07-14 20:35 UTC, katbyte commented on internal/services/hdinsight/hdinsight_hbase_cluster_resource.go
> +			"disk_encryption_properties": SchemaHDInsightsDiskEncryptionProperties(),
```suggestion
			"disk_encryption": SchemaHDInsightsDiskEncryptionProperties(),
```

2022-07-14 20:35 UTC, katbyte commented on internal/services/hdinsight/hdinsight_spark_cluster_resource.go
> +			"disk_encryption_properties": SchemaHDInsightsDiskEncryptionProperties(),
```suggestion
			"disk_encryption": SchemaHDInsightsDiskEncryptionProperties(),
```

2022-07-14 20:35 UTC, katbyte commented on website/docs/r/hdinsight_spark_cluster.html.markdown
> +* `encryption_at_host` - (Optional) This is indicator to show whether resource disk encryption is enabled.
we put enabled on the end of bools, also should this be worded different
```suggestion
* `encrypted_at_host_enabled` - (Optional) This is indicator to show whether resource disk encryption is enabled.
```

2022-07-14 20:35 UTC, katbyte commented on website/docs/r/hdinsight_spark_cluster.html.markdown
> +* `key_version` - (Optional) This is the specific version of the key used for enabling disk encryption.
these are key vault items?
```suggestion
* `key_vault_key_name` - (Optional) This is the name of key used for enabling disk encryption.

* `key_vault_key_version` - (Optional) This is the specific version of the key used for enabling disk encryption.
```

also could you not combine these into `key_vault_key_id` which takes the versionless or versioned id?

2022-07-14 20:35 UTC, katbyte commented on website/docs/r/hdinsight_spark_cluster.html.markdown
> +* `vault_uri` - (Optional) this is the base key vault URI where the customers key is located.
and if we take the key vault key id above this can be removed?

2022-07-14 20:35 UTC, katbyte commented on website/docs/r/hdinsight_spark_cluster.html.markdown
> +* `msi_resource_id` - (Optional) This is the resource ID of Managed Identity used to access the key vault.
should this be something like
```suggestion
* `keyv_ault_managed_identity_id` - (Optional) This is the resource ID of Managed Identity used to access the key vault.
```

2022-07-18 05:38 UTC, jiaweitao001 commented on website/docs/r/hdinsight_spark_cluster.html.markdown
> +* `msi_resource_id` - (Optional) This is the resource ID of Managed Identity used to access the key vault.
Will change.

2022-07-20 03:59 UTC, katbyte requested changes
test failures:
![Uploading image.png…]()

2022-07-20 04:59 UTC, jiaweitao001 commented
@katbyte Hi, the test failing image have problem showing up. Can you plz post it again? Thanks.

2022-07-22 02:11 UTC, katbyte commented
You can always find them in teamcity (and those should pass before we merge), but here is another screenshot

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/1638467/180347615-4dc20ade-d4c3-4962-b839-41cf5f45c7df.png">

2022-08-04 04:37 UTC, jiaweitao001 commented
Hi @katbyte ,  a PR for fixing the stale failing tests is [here](https://github.com/hashicorp/terraform-provider-azurerm/pull/17795), please check it out. Thanks.

2022-08-30 02:39 UTC, katbyte approved these changes
Thanks @jiaweitao001 - LGTM ♻️

2022-08-30 09:19 UTC, magodo commented
The failures below are not related to this PR, they also occur in the main branch:

![image](https://user-images.githubusercontent.com/7970698/187399504-4fcfca2b-c5e6-4ceb-ba5a-5e308830f040.png)

2022-08-30 09:20 UTC, jiaweitao001 commented
![Screenshot 2022-08-30 171820](https://user-images.githubusercontent.com/100274846/187399918-d78f2f2e-87c5-47d7-b1a4-a9e65185000d.png)

2022-08-30 09:27 UTC, merged