Feat kubernetes cluster supports capacity reservation group
hashicorp/terraform-provider-azurerm pull request #17395
Opened 2022-06-27 04:13 UTC by heiazuo

### public pr for `kubernetes_cluster/node_pool`- `capacity_reservation_group_id`

2022-06-27 07:53 UTC, tombuildsstuff requested changes
hi @heiazuo 

Thanks for this PR, I've taken a look through and left a couple of comments inline but if we can fix those up then we can take another look.

Thanks!

2022-06-27 07:53 UTC, tombuildsstuff commented on website/docs/r/kubernetes_cluster.html.markdown
> +* `capacity_reservation_group_id` - (Optional) AKS will associate the specified agent pool with the Capacity Reservation Group. Changing this forces a new resource to be created.
presumably this should be:

```suggestion
* `capacity_reservation_group_id` - (Optional) Specifies the ID of the Capacity Reservation Group within which this AKS Cluster should be created. Changing this forces a new resource to be created.
```

2022-06-27 07:53 UTC, tombuildsstuff commented on website/docs/r/kubernetes_cluster_node_pool.html.markdown
> +* `capacity_reservation_group_id` - (Optional) AKS will associate the specified agent pool with the Capacity Reservation Group. Changing this forces a new resource to be created.
```suggestion
* `capacity_reservation_group_id` - (Optional) Specifies the ID of the Capacity Reservation Group where this Node Pool should exist. Changing this forces a new resource to be created.
```

2022-06-28 03:11 UTC, heiazuo commented
Thanks @tombuildsstuff , documents updated, please take another look.

2022-07-06 00:22 UTC, katbyte approved these changes
LGTM 🦕

2022-07-06 00:22 UTC, merged