New Resource: azurerm_application_insights_workbook_template
hashicorp/terraform-provider-azurerm pull request #17433
Opened 2022-06-29 09:14 UTC by ms-zhenhua

[Swagger Link](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2020-11-20)

2022-06-29 14:16 UTC, tombuildsstuff requested changes
A couple of minor comments but this otherwise LGTM 👍

2022-06-29 14:16 UTC, tombuildsstuff commented on internal/services/applicationinsights/validate/workbook_template_id.go
> +func WorkbookTemplateID(input interface{}, key string) (warnings []string, errors []error) {
this is available within the sdk (`applicationinsights.ValidateWorkbookTemplateID`) - so we can remove this?

2022-06-30 04:10 UTC, ms-zhenhua commented
Hi @tombuildsstuff, thank you for reviewing my code. I have resolved the comments, kindly help review it again. Thanks.

2022-07-08 21:40 UTC, katbyte approved these changes
LGTM 🎩

2022-07-08 21:40 UTC, merged