`azurerm_automation_account`  - support for the `encryption` and `local_authentication_enabled` property
hashicorp/terraform-provider-azurerm pull request #17454
Opened 2022-06-30 08:37 UTC by wuxu92

support of `encryption` and `disable_local_auth` 

--- PASS: TestAccAutomationAccount_basic (119.18s)
--- PASS: TestAccAutomationAccount_requiresImport (128.41s)
--- PASS: TestAccAutomationAccount_complete (66.28s)
--- PASS: TestAccAutomationAccount_encryption (298.88s)
--- PASS: TestAccAutomationAccount_identityUpdate (157.56s)
--- PASS: TestAccAutomationAccount_systemAssignedIdentity (68.73s)
--- PASS: TestAccAutomationAccount_systemAssignedUserAssignedIdentity (79.94s)
--- PASS: TestAccAutomationAccount_userAssignedIdentity (145.22s)
PASS

2022-08-02 13:29 UTC, stephybun requested changes
Thanks for this @wuxu92, this is off to a solid start. I left some suggestions in-line, once those are fixed up we can take another look through.

2022-08-02 13:29 UTC, stephybun commented on internal/services/automation/automation_account_resource.go
> +						"user_identity_id": {
Can we rename this to be consistent with other encryption blocks within the provider?
```suggestion
						"user_assigned_identity_id": {
```

2022-08-02 13:29 UTC, stephybun commented on website/docs/r/automation_account.html.markdown
> +* `user_identity_id` - (Optional) The user identity used for CMK. It will be an ARM resource id.
```suggestion
* `user_identity_id` - (Optional) The User Assigned Managed Identity ID to be used for accessing the Customer Managed Key for encryption.
```

2022-08-03 02:38 UTC, wuxu92 commented on internal/services/automation/automation_account_resource.go
> +							ValidateFunc: validation.StringIsNotEmpty,
Is that mean we do a query to get the `key_name`, `key_version`, and `key_vault_uri` by the `key_vault_key_id` and then fill them into the request model?  looks like no common way to do this in our repo.

2022-08-03 05:17 UTC, stephybun commented on internal/services/automation/automation_account_resource.go
> +							ValidateFunc: validation.StringIsNotEmpty,
Here is an example of what I mean https://github.com/hashicorp/terraform-provider-azurerm/blob/4620cb506b866b649c7f666e54ba2431825a2475/internal/services/cognitive/cognitive_account_customer_managed_key_resource.go#L96-L104

2022-08-08 01:48 UTC, wuxu92 commented
Hi @stephybun i have updated the pr to fix the comments could you please have another look, thanks!

2022-08-09 14:17 UTC, katbyte requested changes

2022-08-09 14:17 UTC, katbyte commented on internal/services/automation/automation_account_resource.go
> +						"key_source": {
can we space things consistanty with the rest of the provider
```suggestion
						},

						"key_source": {
```

2022-08-09 14:17 UTC, katbyte commented on internal/services/automation/automation_account_resource.go
> +			"local_auth_enabled": {
```suggestion
			"local_authentication_enabled": {
```

2022-08-09 14:17 UTC, katbyte commented on internal/services/automation/automation_account_resource_test.go
> +  encryption {
```suggestion
  }
  
  local_auth_enabled = false
  
  encryption {
```

2022-08-09 14:17 UTC, katbyte commented on website/docs/r/automation_account.html.markdown
> +* `disable_local_auth` - (Optional) Whether requests using non-AAD authentication are blocked.
this hasn't been updated?

2022-08-10 07:42 UTC, wuxu92 commented
@katbyte pr updated and all checks passed now

2022-08-16 06:15 UTC, katbyte approved these changes
LGTM 🔒

2022-08-16 06:15 UTC, merged