Adding enhancements for GraphQL
hashicorp/terraform-provider-azurerm pull request #17505
Opened 2022-07-05 12:03 UTC by kikoluiss

- Type GraphQL: api_management_api
- Definitions and Components: api_management_api_schema

2022-07-05 15:14 UTC, katbyte commented on website/docs/r/api_management_api.html.markdown
> +* `type` - (Optional) The type of the API: "http", "graphql", "soap", "websocket"
should this be `api_type` to make sure its exceptionally clear what "type" we are referring to?

2022-07-05 15:14 UTC, katbyte commented on website/docs/d/api_management_api.html.markdown
> +* `type` - The type of the API: "http", "graphql", "soap", "websocket"
should this be `api_type` to make sure its exceptionally clear what "type" we are referring to?

2022-07-08 04:41 UTC, katbyte requested changes

2022-07-08 04:41 UTC, katbyte commented on internal/services/apimanagement/api_management_api_data_source.go
> +			"type": {
missed renaming this one

2022-07-13 03:55 UTC, katbyte commented
thanks @kikoluiss - have some test failures now
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/1638467/178647200-0e51f0e8-6acc-4004-b740-322081c82904.png">

2022-07-19 21:58 UTC, kikoluiss commented
I will review this issue tonight! Regards.

Sent from my iPhone

> On 19 Jul 2022, at 15:40, Dan Cash ***@***.***> wrote:
> 
> ﻿
> Is there a status/timeframe for merging this? Currently our TF is broken due to there being no implementation of graphql as an option in azurerm. Trying to find a timeframe so we know if we should just delay and let our TF be broken for now, or if we need to do a rewrite for this.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-08-17 01:16 UTC, katbyte requested changes
still seeing some failures related to api_type
<img width="1615" alt="image" src="https://user-images.githubusercontent.com/1638467/185013327-91d2bacb-9b12-4d15-ba23-d84dd84da451.png">

2022-10-20 17:11 UTC, closed without merging