azurerm_key_vault_{key|secret|certificate} - Cache the key vault id to url mapping during C/U and avoid calling resource list API during C/U/D
hashicorp/terraform-provider-azurerm pull request #17536
Opened 2022-07-07 05:58 UTC by magodo

A follow up of #17407, which is related to #11059.

With #17407, the resource list API is avoided in following cases:

- Create a key together with a key vault (managed resource or data source)
- Read a key item together with a key vault (managed resource or data source)

But doesn't cover following cases (as the cache is only populated when a key vault is created/read):

- Create a key separately
- Read a key separately (this only applies when the depending key vault is hardcoded)
- Update a key separately
- Delete a key (no matter separately or together with the key vault)

This PR made following changes:

1. In `BaseUriForKeyVault` to lookup the key vault base uri by its name, if no hit, populate the record into the cache. This is called in create, which makes the read called by create can read the record back from cache.
2. In the update and delete function of the key, instead of calling `KeyVaultIDFromBaseUrl()` to get the key vault id, just directly read the `key_vault_id` from state file, as state file is accessble during update and delete, also `key_vault_id` is a force new and required property, which means it won't change between last write to state and this point.

So hopefully, the only time that the resource list api will be called is when the key vault nested item resource are depending on a hardcoded key vault id.

2022-07-13 09:40 UTC, tombuildsstuff requested changes
hey @magodo 

Thanks for this PR - I've taken a look through and left a few comments inline, but unfortunately we can't use `d.Get` inside of the Delete function - depending on how resources are deleted (`terraform destroy` verses removing them from the config and running `terraform apply`, for example) the config isn't necessarily available during the Delete function. In addition unfortunately terraform-plugin-framework doesn't expose the config during the deletion, so this isn't forwards compatible there - as such we're going to need to continue looking this up during the deletion.

Thanks!

2022-07-13 09:40 UTC, tombuildsstuff commented on internal/services/keyvault/key_vault_certificate_resource.go
> +	keyVaultId, err := parse.VaultID(d.Get("key_vault_id").(string))
unfortunately we can't use schema fields in the delete function - this isn't always available in the Plugin SDK and isn't available in Framework so we have to look this up from the API instead

2022-07-13 09:40 UTC, tombuildsstuff commented on internal/services/keyvault/key_vault_secret_resource.go
> +	keyVaultId, err := parse.VaultID(d.Get("key_vault_id").(string))
(same here)

2022-07-13 10:56 UTC, magodo commented
@tombuildsstuff My intent here is to read from the state ([prior state](https://github.com/hashicorp/terraform-plugin-go/blob/df65cd885837c0a41f571da95b81a705acc130eb/tfprotov5/internal/tfplugin5/tfplugin5.proto#L291) actually), which should be always available for update and delete. From my understanding, the `d.Get()` will [read field from a couple of sources](https://github.com/hashicorp/terraform-provider-azurerm/blob/d2111e647efca5d9629a933d1bc89b8a93d714a1/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go#L535-L543). So for this case, it will failed to read from reading from `set` and `diff`, also if the `config` is not available, then it will finally read from `state`, as expected. This is just my assumption, I'll test for this scenario to confirm.

2022-07-14 01:44 UTC, magodo commented
@tombuildsstuff I've just verified that using `d.Get()` also works when *removing them from the config and running terraform apply*.

2022-07-14 11:46 UTC, tombuildsstuff commented
@magodo 

> I've just verified that using d.Get() also works when removing them from the config and running terraform apply.

In which version of Terraform? At any rate, since that information isn't available in Terraform Plugin Framework we'd end up having to revert this change in time - so unfortunately we can't pull those from the config/state here / would still have to look these up unfortunately.

2022-07-15 01:42 UTC, magodo commented
@tombuildsstuff I'm using v1.2.4. For the framework, both [Update](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework@v0.9.0/tfsdk#UpdateResourceRequest) and [Delete](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework@v0.9.0/tfsdk#DeleteResourceRequest) request has access to the prior state.

2022-07-21 07:46 UTC, magodo commented on internal/services/keyvault/client/helpers.go
> +	}
Moving it above the lock might introduce concurrent read and write on the `keyVaultsCache` map?

2022-12-14 10:25 UTC, tombuildsstuff commented
@magodo apologies for the delay with this one, any chance you could rebase this and we should be able to get this one in?

2022-12-14 11:54 UTC, magodo commented
@tombuildsstuff Thank you for revisiting this! I've merged against main branch and verified that running acctest `TestAccKeyVaultSecret_update` will only call one time the list api (due to exists check at the very end).

2022-12-14 17:22 UTC, merged