New Resource: `azurerm_automation_connection_type`
hashicorp/terraform-provider-azurerm pull request #17538
Opened 2022-07-07 06:55 UTC by wuxu92

add a new resource for automation connection type.  

--- PASS: TestAccAutomationConnectionType_basic (131.51s)

2022-08-09 14:07 UTC, katbyte requested changes

2022-08-09 14:07 UTC, katbyte commented on website/docs/r/automation_connection_type.html.markdown
> +  Manages a Automation.
this is incomplete?

2022-08-09 14:07 UTC, katbyte commented on internal/services/automation/automation_connection_type_resource.go
> +		"field_definitions": {
definitions feels redundant?
```suggestion
		"field": {
```

2022-08-10 02:34 UTC, wuxu92 commented
@katbyte i have fixed the comments, but the CI failed because the terrafmt's new version breaks the process

```
go: github.com/katbyte/terrafmt@latest (in github.com/katbyte/terrafmt@v0.5.0):
	The go.mod file for the module providing named packages contains one or
	more exclude directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
make: *** [GNUmakefile:17: tools] Error 1
Error: Process completed with exit code 2.
```

2022-08-30 02:43 UTC, katbyte approved these changes
LGTM aside from my comment 📜

2022-08-30 02:43 UTC, katbyte commented on website/docs/r/automation_connection_type.html.markdown
> +Manages a Automation Connection Type.
grammer
```suggestion
  Manages an Automation Connection Type.
---

# azurerm_automation_connection_type

Manages anAutomation Connection Type.
```

2022-08-30 02:44 UTC, merged