azurerm_key_vault : Support public_network_access_enabled proptery for resource azurerm_key_vault
hashicorp/terraform-provider-azurerm pull request #17552
Opened 2022-07-08 03:44 UTC by sinbai

The purpose of this PR:

- Support `public_network_access_enabled ` property for  azurerm_key_vault and data.azurerm_key_vault.
- Delete func `enableSoftDelete` as it is unused.

Fix issue #17533.

2022-07-08 16:42 UTC, CorrenSoft commented
It is possible to have null (nil) as the default value?
Otherwise, it could force to update each keyvault implementation to have the desired value...

2022-08-09 14:00 UTC, katbyte requested changes

2022-08-09 14:00 UTC, katbyte commented on internal/services/keyvault/key_vault_data_source.go
> +		d.Set("public_network_access_enabled", *props.PublicNetworkAccess == "Enabled")
this needs a nil check

2022-08-11 04:59 UTC, sinbai commented on internal/services/keyvault/key_vault_data_source.go
> +		d.Set("public_network_access_enabled", *props.PublicNetworkAccess == "Enabled")
Thanks for your feedback. Fixed.

2022-08-12 03:37 UTC, katbyte approved these changes
LGTM 🌿

2022-08-12 03:38 UTC, merged