New data source: azurerm_log_analytics_workspace
hashicorp/terraform-provider-azurerm pull request #1755
Opened 2018-08-11 23:51 UTC by mb290

2018-08-13 05:38 UTC, tombuildsstuff requested changes
hey @mb290 

Thanks for this PR - I've left a few minor comments inline but if we can fix those up this otherwise LGTM 👍 

Thanks!

2018-08-13 05:38 UTC, tombuildsstuff commented on azurerm/data_source_log_analytics_workspace.go
> +			"resource_group_name": resourceGroupNameDiffSuppressSchema(),
can we update this to be `resourceGroupNameForDataSourceSchema`?

2018-08-13 05:38 UTC, tombuildsstuff commented on website/docs/d/log_analytics_workspace.html.markdown
> +* `portal_url` - The Portal URL for the Log Analytics Workspace.
can we also add `retention_in_days`, `sku` and `tags` here?

2018-08-13 05:38 UTC, tombuildsstuff commented on azurerm/data_source_log_analytics_workspace_test.go
> +	config := testAccDataSourceAzureRMStorageAccount_basic(rInt, rString, location)
_minor_ we could probably switch to using the basic resource from the Resource instead here? e.g. `testAccAzureRMLogAnalyticsWorkspace_requiredOnly`

2018-08-13 12:54 UTC, mb290 commented
Hi @tombuildsstuff! Changes have been made. Didn't think/know about being able to leverage the resource from the resource test case so have updated it. Let me know if it's not the right way.

2018-08-13 13:12 UTC, mb290 commented
@tombuildsstuff after a couple of failed builds and understanding the test harness much more I ended up using

`testAccAzureRMLogAnalyticsWorkspace_retentionInDaysComplete`

One of my tests was for the number of days retention so I wanted to make sure we aren't expecting MS to keep the same value, instead we can just use what we set. I also updated the expected Sku based on the new test case.

2018-08-14 01:08 UTC, katbyte approved these changes
@mb290, 

Thank you for the requested updates, this LGTM now 👍

2018-08-14 01:09 UTC, katbyte commented
Tests pass:

```
gofmt -w $(find . -name '*.go' |grep -v vendor)
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -test.run=TestAccDataSourceAzureRMLogAnalyticsWorkspace -timeout 180m
=== RUN   TestAccDataSourceAzureRMLogAnalyticsWorkspace_basic
--- PASS: TestAccDataSourceAzureRMLogAnalyticsWorkspace_basic (91.97s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	92.005s

```

2018-08-14 01:12 UTC, merged