`azurerm_windows_web_app` - fix `health_check_eviction_time_in_min` not being set issue
hashicorp/terraform-provider-azurerm pull request #17656
Opened 2022-07-18 07:31 UTC by xiaxyi

This pr is fixing two issues:
1. The property `WEBSITE_HEALTHCHECK_MAXPINGFAILURES` in app_setting is suppose to be set if user assign a value to the property `health_check_eviction_time_in_min`.
2. The `WEBSITE_HEALTHCHECK_MAXPINGFAILURES` should be written back to the state file if user explicitly specify it in config.

fix issues:https://github.com/hashicorp/terraform-provider-azurerm/issues/17123
https://github.com/hashicorp/terraform-provider-azurerm/issues/17546
https://github.com/hashicorp/terraform-provider-azurerm/issues/16302

2022-08-05 06:28 UTC, jackofallops requested changes
Hi @xiaxyi - Thanks for this PR. I've left a couple comments below for changes I believe to be needed. But otherwise I think it looks good 👍 

Thanks!

2022-08-09 02:30 UTC, xiaxyi commented on internal/services/appservice/helpers/web_app_schema.go
> +	maxPingFailures := "WEBSITE_HEALTHCHECK_MAXPINGFAILURES"
I think we need to move the `WEBSITE_HEALTHCHECK_MAXPINGFAILURES` from the `unmanagedSettings` list if user adds the key explicitly in the config?

2022-08-09 02:42 UTC, xiaxyi commented on internal/services/appservice/helpers/web_app_schema.go
> +
But azure provided such way to set this property and lots of users are aware of this usage as well. shall we just let them set it via app_setting?

2022-08-09 02:42 UTC, xiaxyi commented
Thank @jackofallops for the comments, left some feedbacks inline

2022-08-09 13:52 UTC, katbyte commented on internal/services/appservice/helpers/web_app_schema.go
> +
we have moved it out of the map into its own property, therefor it should only be set there as @jackofallops, and if the user does put it into the app settings map we should maybe toss up an error telling the user to set it there?

2022-08-09 13:52 UTC, katbyte commented
also we have some test failureS:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/1638467/183666762-a1e0eed6-cf3b-4bbf-bf5d-5b788a623b7b.png">

2022-08-29 08:56 UTC, xiaxyi commented
Thanks @jackofallops for the comments. I removed the app_setting KVP code change, also, the update check of app_setting should be removed as we are collecting data from site_config, which means, app_setting still needs to be updated even there is no change in the config.

For the test cases, I removed the property checks as we have the import step.

2022-09-02 01:44 UTC, xiaxyi commented
> we still have test failures <img alt="image" width="1220" src="https://user-images.githubusercontent.com/1638467/188040982-45e6fd0f-2c72-4813-b173-fe3f00ecf782.png">

Thanks @katbyte for the comment, the acc test failure will be fixed in https://github.com/hashicorp/terraform-provider-azurerm/pull/18177

2022-12-08 08:54 UTC, cmoetzing commented on internal/services/appservice/helpers/web_app_schema.go
> +
@katbyte If think the error is really important. I fixed this issue by placing the env variable in `app_settings` and probably many others will have too.

2022-12-09 15:52 UTC, pierluca commented
Is there any ETA on when this issue will be fixed/merged/released ?

2022-12-14 15:38 UTC, jackofallops commented
Closing as superseded by 19685

2022-12-14 15:38 UTC, closed without merging