azurerm_web_application_firewall_policy - support [exclusionManagedRuleSets]
hashicorp/terraform-provider-azurerm pull request #17757
Opened 2022-07-26 02:56 UTC by ms-zhenhua

--- PASS: TestAccWebApplicationFirewallPolicy_basic (372.88s)
--- PASS: TestAccWebApplicationFirewallPolicy_knownCVEs (373.61s)
--- PASS: TestAccWebApplicationFirewallPolicy_update (452.23s)
--- PASS: TestAccWebApplicationFirewallPolicy_excludedRules (461.71s)
--- PASS: TestAccWebApplicationFirewallPolicy_updateDisabledRules (569.86s)
PASS

2022-08-16 06:05 UTC, katbyte requested changes

2022-08-16 06:05 UTC, katbyte commented on internal/services/network/web_application_firewall_policy_resource.go
> +									"exclusion_managed_rule_set": {
this is in a block called `managed_rules`, so should it maybe be
```suggestion
									"excluded_rule_set": {
```

so we get `managed_rules.excluded_rule_set`

2022-08-17 01:26 UTC, katbyte approved these changes
LGTM ⏳

2022-08-17 01:27 UTC, katbyte commented
needs terrafmt to be run

2022-08-17 01:55 UTC, ms-zhenhua commented
Hi @katbyte, thank you for your help. Now all checks have passed. Kindly help check it again.

2022-08-17 08:56 UTC, merged