azurerm_log_analytics_cluster - update the validation for size_gb
hashicorp/terraform-provider-azurerm pull request #17780
Opened 2022-07-28 01:09 UTC by neil-yechenwei

This PR is to update the validation for `size_gb`.

--- PASS: TestAccLogAnalyticsCluster_resize (1932.09s)
--- PASS: TestAccLogAnalyticsCluster_basic (2118.79s)
--- PASS: TestAccLogAnalyticsCluster_requiresImport (2191.80s)

2022-07-28 05:21 UTC, WodansSon requested changes
@neil-yechenwei, thank you so much for this PR... the changes look mostly good to me but I have a few suggestions on the wording in the documentation. Can you take a look and let me know what you think? 🚀

2022-07-28 05:21 UTC, WodansSon commented on website/docs/r/log_analytics_cluster.html.markdown
>  * `size_gb` - (Optional) The capacity of the Log Analytics Cluster specified in GB/day. Defaults to 1000.
```suggestion
* `size_gb` - (Optional) The capacity of the Log Analytics Cluster is specified in GB/day. Possible values include `500`, `1000`, `2000` or `5000`. Defaults to `1000`.
```

2022-07-28 05:21 UTC, WodansSon commented on website/docs/r/log_analytics_cluster.html.markdown
> +~> **NOTE:** The cluster capacity must start at 500 GB and can be set to 1000, 2000 or 5000 GB/day. For more information on cluster costs, see [Dedicate clusters](https://docs.microsoft.com/en-us/azu
```suggestion
~> **NOTE:** For more information on cluster costs and capacity please see the [product documentation](https://docs.microsoft.com/azure/azure-monitor/logs/cost-logs#dedicated-clusters).
```

2022-07-28 05:48 UTC, neil-yechenwei commented on website/docs/r/log_analytics_cluster.html.markdown
>  * `size_gb` - (Optional) The capacity of the Log Analytics Cluster specified in GB/day. Defaults to 1000.
Updated

2022-07-28 05:49 UTC, neil-yechenwei commented on website/docs/r/log_analytics_cluster.html.markdown
> +~> **NOTE:** The cluster capacity must start at 500 GB and can be set to 1000, 2000 or 5000 GB/day. For more information on cluster costs, see [Dedicate clusters](https://docs.microsoft.com/en-us/azu
Updated

2022-07-28 05:55 UTC, WodansSon approved these changes
@neil-yechenwei, thanks for pushing those changes... this LGTM! 🚀

2022-07-29 07:53 UTC, mybayern1974 commented
This PR fixes #17787

2022-07-29 10:58 UTC, niks-singh commented
Can you please provide the version number in which this change will be available to use. I do not see this change in [v3.16.0] in registry

2022-08-02 07:28 UTC, stephybun approved these changes
Thanks for this @neil-yechenwei and for the review @WodansSon. I went ahead and rebased this so that we can get this in, hope you don't mind.

2022-08-02 07:28 UTC, merged