add `private_ranges` and `allow_sql_redirect` for firewall_policy_resource
hashicorp/terraform-provider-azurerm pull request #17842
Opened 2022-08-02 11:12 UTC by wuxu92

and update test code for fix acc test failure

2022-08-09 16:39 UTC, katbyte requested changes

2022-08-09 16:39 UTC, katbyte commented on website/docs/r/firewall_policy.html.markdown
> +* `allow_sql_redirect` - (Optional) Whether SQL Redirect traffic filtering is enabled. Turning on the flag requires no rule using port 11000-11999.
```suggestion
* `sql_redirect_allowed` - (Optional) Whether SQL Redirect traffic filtering is allowed. Turning on the flag requires no rule using port 11000-11999.
```

or does it enable it and should be
```suggestion
* `sql_redirect_enabled` - (Optional) Whether SQL Redirect traffic filtering is enabled. Turning on the flag requires no rule using port 11000-11999.
```

2022-08-10 03:38 UTC, wuxu92 commented
hi @katbyte have refactored the schema name

2022-08-10 03:55 UTC, katbyte commented on website/docs/r/firewall_policy.html.markdown
> +* `sql_redirect_allowed` - (Optional) Whether SQL Redirect traffic filtering is allowed. Turning on the flag requires no rule using port 11000-11999.
```suggestion
* `sql_redirect_allowed` - (Optional) Whether SQL Redirect traffic filtering is allowed. Enabling this flag requires no rule using ports between `11000`-`11999`.
```

2022-08-12 05:07 UTC, katbyte requested changes
test failures
<img width="859" alt="image" src="https://user-images.githubusercontent.com/1638467/184288571-0dc6baed-e6c0-4134-91af-417657e32ff0.png">

2022-08-12 08:46 UTC, wuxu92 commented
@katbyte sorry I forgot to change the acc test code, now all tests passed.

![image](https://user-images.githubusercontent.com/2633022/184318988-9c8bdb49-cde6-47d0-960b-355a4880405c.png)

2022-08-16 05:37 UTC, katbyte approved these changes
LGTM 🧾

2022-08-16 05:37 UTC, merged