Storage Account add multichannel support
hashicorp/terraform-provider-azurerm pull request #17999
Opened 2022-08-15 12:46 UTC by alexwilcox9

Hi,

I'd like to make use of multichannel SMB shares so thought I'd have a go at adding this functionality to the storage account resource. I'm finding however that whilst it does successfully enable multichannel it doesn't seem to read that back in so Terraform still thinks it has work to do on the next plan.

My guess is I'm missing something on the flatten function, any suggestions would be greatly appreciated.

https://github.com/hashicorp/terraform-provider-azurerm/issues/13715

2022-09-05 18:21 UTC, katbyte requested changes
Thanks @alexwilcox9 - seems like we need to enable a feature on the storage account?
```
------- Stdout: -------
=== RUN   TestAccAzureRMStorageAccount_shareProperties
=== PAUSE TestAccAzureRMStorageAccount_shareProperties
=== CONT  TestAccAzureRMStorageAccount_shareProperties
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: updating Azure Storage Account `share_properties` "unlikely23exst2acct1rvfl": storage.FileServicesClient#SetServiceProperties: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="FeatureNotSupportedOnStorageAccount" Message="Feature is not supported on this storage account.\nRequestId:b45ca9e4-501a-001b-7d40-c17878000000\nTime:2022-09-05T15:59:49.6466540Z"
        
          with azurerm_storage_account.test,
          on terraform_plugin_test.tf line 11, in resource "azurerm_storage_account" "test":
          11: resource "azurerm_storage_account" "test" {
        
--- FAIL: TestAccAzureRMStorageAccount_shareProperties (96.13s)
FAIL
```

- could you document how to do this in the docs?

2022-09-06 12:14 UTC, alexwilcox9 commented
Hi @katbyte 
This feature is only for premium storage accounts, I've added that to the documentation now.

What's confusing me now is why it complained for that test in particular as multichannel isn't enabled in that test. From a quick test it seems if you send a storage.Multichannel block on a Standard storage account it complains. Even if enabled is set to False
To try and address this I've changed the code to only send the block if it's explicitly enabled however this has caused a new problem where multichannel can't be disabled if it's already enabled (as we only send the block if it's enabled)

Have you got any tips on how to get around this?

2022-09-15 07:37 UTC, katbyte requested changes
we'll need to handle the non premium account situation, so likely what needs to happen is the correct handling if the API return value in that situation

2022-09-15 15:49 UTC, alexwilcox9 commented
Hi @katbyte 
I think I've got it this time, both tests are passing for me. Could you please also test and let me know if the approach I've taken to deal with Standard accounts is appropriate?
Thanks!

2022-09-15 19:12 UTC, katbyte approved these changes
THanks @alexwilcox9! LGTM now 🍄

2022-09-28 05:21 UTC, merged