`azurerm_batch_pool` - support for the `mount_configuration` property
hashicorp/terraform-provider-azurerm pull request #18042
Opened 2022-08-19 09:21 UTC by liuwuliuyun

2022-08-19 11:00 UTC, liuwuliuyun commented
![捕获](https://user-images.githubusercontent.com/17947406/185604555-5ce14f24-dcb5-4b4c-ab3f-81f0da94a339.PNG)

2022-08-30 03:38 UTC, katbyte requested changes

2022-08-30 03:38 UTC, katbyte commented on website/docs/r/batch_pool.html.markdown
> +* `mount_configuration` - (Optional) A `mount_configuration` block defined as below.
configuration is redundant
```suggestion
* `mount` - (Optional) A `mount_configuration` block defined as below. 
```

2022-08-30 03:38 UTC, katbyte commented on website/docs/r/batch_pool.html.markdown
> +* `nfs_mount_configuration` - (Optional) A `nfs_mount_configuration` block defined as below.
same here
```suggestion
* `azure_blob_file_system` - (Optional) A `azure_blob_file_system_configuration` block defined as below.

* `azure_file_share` - (Optional) A `azure_file_share_configuration` block defined as below.

* `cifs_mount` - (Optional) A `cifs_mount_configuration` block defined as below.

* `nfs_mount` - (Optional) A `nfs_mount_configuration` block defined as below.
```

2022-08-31 06:01 UTC, liuwuliuyun commented
![image](https://user-images.githubusercontent.com/17947406/187605256-b09eed2b-3e81-4d82-ae4e-2169f5c60075.png)

2022-09-02 02:21 UTC, katbyte approved these changes
LGTM ⚡

2022-09-02 02:21 UTC, merged