`azurerm_policy_definition` - expose `role_definition_ids`
hashicorp/terraform-provider-azurerm pull request #18043
Opened 2022-08-19 10:14 UTC by wuxu92

for issue #18018 and will simplify customers with role assignment in policy_assigment.

fixes #18018

2022-08-30 03:39 UTC, katbyte requested changes
test failure
```
------- Stdout: -------
=== RUN   TestAccAzureRMPolicyDefinition_computedMetadata
=== PAUSE TestAccAzureRMPolicyDefinition_computedMetadata
=== CONT  TestAccAzureRMPolicyDefinition_computedMetadata
    testcase.go:110: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # azurerm_policy_definition.test will be updated in-place
          ~ resource "azurerm_policy_definition" "test" {
                id                  = "/subscriptions/*******/providers/Microsoft.Authorization/policyDefinitions/acctest-220829192559906588"
                name                = "acctest-220829192559906588"
              + role_definition_ids = (known after apply)
                # (5 unchanged attributes hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccAzureRMPolicyDefinition_computedMetadata (154.89s)
FAIL
```

2022-08-31 05:19 UTC, wuxu92 commented
all checks have passed now.

--- PASS: TestAccDataSourceAzureRMPolicyDefinition_builtIn (28.21s)
--- PASS: TestAccDataSourceAzureRMPolicyDefinition_builtInLogAnalytics (9.91s)
--- PASS: TestAccDataSourceAzureRMPolicyDefinition_builtInByName (11.97s)
--- PASS: TestAccDataSourceAzureRMPolicyDefinition_builtIn_AtManagementGroup (26.63s)
--- PASS: TestAccDataSourceAzureRMPolicyDefinition_customByDisplayName (126.06s)
--- PASS: TestAccDataSourceAzureRMPolicyDefinition_customByName (106.59s)
--- PASS: TestAccAzureRMPolicyDefinition_basic (107.76s)
--- PASS: TestAccAzureRMPolicyDefinition_basicWithDetail (107.67s)
--- PASS: TestAccAzureRMPolicyDefinition_requiresImport (110.10s)
--- PASS: TestAccAzureRMPolicyDefinition_computedMetadata (106.50s)
--- PASS: TestAccAzureRMPolicyDefinition_metadata (107.92s)
--- PASS: TestAccAzureRMPolicyDefinition_modeUpdate (308.42s)
PASS

2022-08-31 08:42 UTC, wuxu92 commented
![image](https://user-images.githubusercontent.com/2633022/187636643-fc0e000e-28a9-43cb-9661-a12ae3e46a2c.png)

2022-09-02 02:22 UTC, katbyte approved these changes
LGTM but it seems like we are missing the docs?

2022-09-02 02:55 UTC, wuxu92 commented
doc updated

2022-09-02 03:22 UTC, merged