`azurerm_spring_cloud_gateway_route_config` - order defaults to -1 to differenciate 0 and not set
hashicorp/terraform-provider-azurerm pull request #18162
Opened 2022-08-29 09:12 UTC by ms-henglu

2022-08-29 19:10 UTC, katbyte requested changes

2022-10-10 02:50 UTC, ms-henglu commented on internal/services/springcloud/spring_cloud_gateway_route_config_resource.go
> +							Default:  -1,
Hi @katbyte , what do you think about this solution:

We add a `order_enabled` property, then only add the `order` in the payload when it's enabled?

2022-10-17 15:27 UTC, tombuildsstuff commented on internal/services/springcloud/spring_cloud_gateway_route_config_resource.go
> +							Default:  -1,
let's just make this field Required which removes the problem?

2022-10-18 01:57 UTC, ms-henglu commented on internal/services/springcloud/spring_cloud_gateway_route_config_resource.go
> +							Default:  -1,
Makes sense, but it's still a breaking change, is it okay?

2022-11-14 15:58 UTC, katbyte commented on internal/services/springcloud/spring_cloud_gateway_route_config_resource.go
> +							Default:  -1,
@ms-henglu - that should be fine, just make sure there is a test if there is two of them as well checking the upgrade path for users

2022-12-06 16:02 UTC, katbyte approved these changes
LGTM  provided tests pass

2022-12-09 00:50 UTC, merged