`azurerm_api_management_product_group` - fix resource get error
hashicorp/terraform-provider-azurerm pull request #18206
Opened 2022-09-01 02:54 UTC by xuzhang3

Fixes: #14868
Function  `CheckEntityExists` is case sensitive, update to `ListByProduct` as this function is case insensitive and can properly handle the user's camel/lower/upper case  input.
```log
=== RUN   TestAccApiManagementProductGroup_basic
=== PAUSE TestAccApiManagementProductGroup_basic
=== RUN   TestAccApiManagementProductGroup_requiresImport
=== PAUSE TestAccApiManagementProductGroup_requiresImport
=== CONT  TestAccApiManagementProductGroup_basic
=== CONT  TestAccApiManagementProductGroup_requiresImport
--- PASS: TestAccApiManagementProductGroup_requiresImport (5248.41s)
--- PASS: TestAccApiManagementProductGroup_basic (5613.96s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement 5652.794s

```

2022-09-04 01:04 UTC, katbyte requested changes
@xuzhang3 - is there a specific reason we should be making this case insensitive? is the api not respecting case? if so isn't that a bug and we should have an open issue to track it?

2022-09-05 03:32 UTC, xuzhang3 commented
@katbyte This group ID is case insensitive, to find the group we should change the search operation  to case insensitive API. This is not a bug, `CheckEntityExists` is case sensitive since released.

2022-11-10 21:06 UTC, katbyte commented
@xuzhang3 - i'm not sure why we should be ignoring case for this lookup? we should expect that the inputs to terraform in the config are in the correct case. Also with this fix will the API not just return the correct case for the ID causing a diff for those properties?

2022-12-16 16:55 UTC, mbfrahry commented
Thank you for this PR but I am going to go ahead and close this down since we are looking to avoid looking this resource up case insensitively.

2022-12-16 16:55 UTC, closed without merging