Upgrade Automation/Runbook API version from 2020-01-13-preview to 2019-06-01
hashicorp/terraform-provider-azurerm pull request #18213
Opened 2022-09-01 08:43 UTC by wuxu92

For updating from 2020-01-13-preview to 2019-06-01 may cause incompatible changes, so I only updated the Runbook resource which is trying to fix the issue https://github.com/hashicorp/terraform-provider-azurerm/issues/1602.

and because there are some breaking changes in swagger which cause the `RunbookClient.GetContent` and `RunbookDraftClinet.Create` cannot work in `2019-06-01` so these two Calls keep using the `2020-01-13-preview` of `Azure/azure-sdk-for-go`. more detail in this issue comment: https://github.com/Azure/azure-sdk-for-go/issues/17591#issuecomment-1233676539 .

2022-09-06 15:45 UTC, katbyte requested changes
This also seems blocked by a bug in the swagger/generated SDK? we should not be rolling back to an old API version or have the service split across api versions

2022-09-06 15:45 UTC, katbyte commented on internal/services/automation/automation_runbook_resource.go
> +				ValidateFunc: validation.StringInSlice(runbook.PossibleValuesForRunbookTypeEnum(), false),
we should be explicit on the values here, that slice can change without warning due to bad swagger and then we would break users

2022-09-07 03:45 UTC, wuxu92 commented
yes, the root source is the swagger broken. en... as for runbook resource, it [uses `stable/2018-06-30/runbook.json` in `2020-01-13-preview` Track 1 sdk]( https://github.com/Azure/azure-rest-api-specs/blob/55458b642a7cdc8dd9b2928942d13c6f076399bc/specification/automation/resource-manager/readme.md?plain=1#L231), so it is a kind of API upgrade in this PR in fact. the track 1 version management is a bit messy I think.

and hashicorp/go-azure-sdk cannot generate for a single resource making us have to cross API versions. or we directly generate the `stable/2018-06-30` version in `hashicorp/go-azure-sdk` then we can fix the [`runbook` issue ](https://github.com/hashicorp/terraform-provider-azurerm/issues/1602)all in one version. but still, that makes us keep both  hashicorp and azure versions of sdk in `azurerm`.

2022-09-09 00:06 UTC, katbyte commented
@wuxu92 - can we get the service team to fix the swagger? or is this the way they are going to detail their api in the specs going forward? if so it seems like what we should do is fix the pandora generator so it handles this new file type?

2022-09-09 06:45 UTC, wuxu92 commented
yes, seems the service team will not revert this change because `azure-sdk-go-go` has released a Track2 SDK(which is compatible with this swagger) to replace the track1 SDK. As I know that @manicminer is working on the pandora generator to use a new base layer to fix this. but i don't know when will it be released.

2022-09-12 08:12 UTC, manicminer commented
@wuxu92 The new base layer is not too far from ready but is still going through testing. Can you detail the issue? If you think this should/could be solved with an improved base client I'd like to make sure that's indeed the case :)

2022-09-13 01:28 UTC, wuxu92 commented
@manicminer Thanks for your work! The case here is when the response body is a single string, not structured data, Track1 and current pandora will try to `json.Unmarshal` the HTTP response body to a `string pointer` which raises a JSON error. it would be beneficial if you could test this case in the new base layer.

Below is an example of track1 code (and the current pandora SDK is almost the same).

```go
func (client DscConfigurationClient) GetContentResponder(resp *http.Response) (result String, err error) {
	err = autorest.Respond(
		resp,
		azure.WithErrorUnlessStatusCode(http.StatusOK),
		autorest.ByUnmarshallingJSON(&result.Value),   // <-- result.Value is a *string
		autorest.ByClosing())
```

the error message: `Error occurred unmarshalling JSON - Error = 'invalid character 'C' looking for beginning of value'`

2022-09-13 16:13 UTC, katbyte commented
@wuxu92 - how does track 2 handle it differently?

2022-09-14 03:40 UTC, katbyte commented
@wuxu92 - i meant more how does it handle this "file" swagger change?

2022-09-15 14:01 UTC, tombuildsstuff commented
Blocked on https://github.com/Azure/azure-rest-api-specs/pull/20588

2022-09-22 13:00 UTC, DuneganS commented
Since https://github.com/Azure/azure-rest-api-specs/pull/20588 was merged 3 days ago, is there anything blocking this going though?

2022-09-28 05:51 UTC, katbyte commented
@wuxu92 - now that the swagger PR has been merged can we update the `go-azure-sdk` version (in a separate PR please) if needed and not split the service across API versions now?

2022-09-28 06:57 UTC, wuxu92 commented
@katbyte since the `hashicorp/go-azure-sdk`'s new base layer is not released, and the current generated code for `2019-06-01` still broken the process(as described before). so it's still needed to use both hashi SDK and azure Trask1 SDK.

I think a better way is wanting for  @manicminer 's new base layer to be ready, so we can use only hashi's SDK to support this. it is expected to be ready in recent weeks.

2022-10-12 16:07 UTC, katbyte commented
@wuxu92 - ok, is this good to merge before then to add the new property? tests seem to be passing and we can consolidate versions at a later date

2022-10-19 07:02 UTC, wuxu92 commented
@katbyte thanks for your review i have updated the pr and re-run the tests

![image](https://user-images.githubusercontent.com/2633022/196619653-d0be1877-f953-4b4c-a182-b9ac6d9172ce.png)

2022-10-21 18:57 UTC, katbyte approved these changes
thanks @wuxu92 - LGTM 🍄

2022-10-21 18:57 UTC, merged

2022-10-25 03:42 UTC, DuneganS commented
Can anyone assure that this was included in version 3.28.0? In the documentation I still do not see the options for Python2/3 and and I still get the error that they are not options.

2022-10-25 05:27 UTC, wuxu92 commented
> Can anyone confirm that this was included in version 3.28.0? In the documentation I still do not see the options for Python2/3 and and I still get the error that they are not options.

hi @DuneganS  python 2/3 has been added in https://github.com/hashicorp/terraform-provider-azurerm/pull/18921 which release in 3.28.0 too. looks like forget to update the document and I'll update the doc soon.

could you please share the detail of the current error?

2022-10-25 05:33 UTC, wuxu92 commented
@katbyte looks like these two PRs with the wrong release version, they should be released in 3.29.0? 3.28.0 was released on (October 20, 2022) but these two merged on Oct. 22.