Reverse the order of policies lookup to favour builtin
hashicorp/terraform-provider-azurerm pull request #18338
Opened 2022-09-10 10:24 UTC by Nepomuceno

This one would solve #18337 

It changed the plan time from over 2 minutes to less than 40 seconds fot the sample case

```hcl
terraform {
}

provider "azurerm" {
  features {}
}

data "azurerm_policy_set_definition" "policy_set" {
  name = "179d1daa-458f-4e47-8086-2a68d0d6c38f"
}

data "azurerm_policy_definition" "for_each_pol" {
    count = length(data.azurerm_policy_set_definition.policy_set.policy_definition_reference)
    name = data.azurerm_policy_set_definition.policy_set.policy_definition_reference[0].reference_id
}
```

2022-09-15 06:48 UTC, katbyte requested changes
Thanks @Nepomuceno - however i don't think we can just change the order without impacting existing users (and the ability to lookup a custom policy with the same name as a built in policy)

instead how about we add 2 new properties? a name_builtin and name_user_defined which allows a user to specify the type? this will allow you to save the time while also not impacting existing users. WDYT?

2022-09-22 02:34 UTC, wuxu92 commented
what about using a parallel query: one for built-in policy and another for custom policy and then joining both results? there will be no scheme update, and users will not aware of it.

2022-09-22 04:58 UTC, Nepomuceno commented
This would just increase the problem. The problem right now it is that if you have too many policies to lookup you go over the 120 queries per minute limit and needs to keep waiting the throttling. If you execute both queries always you will reach this even earlier.

2022-10-28 18:55 UTC, mbfrahry approved these changes
LGTM! After another internal discussion, we should be ok here as @katbyte was thinking about `display_name` versus `name`. Thanks for getting this written out @Nepomuceno

2022-10-28 18:56 UTC, merged

2022-10-28 20:06 UTC, Nepomuceno commented
Yeah calling this property "name" it is quite misleading. It should have been called ID