Add ability to specify path to OIDC token
hashicorp/terraform-provider-azurerm pull request #18335
Opened 2022-09-09 22:11 UTC by mpminardi

Adds the ability to specify a path to an OIDC token on disk in place of supplying the token directly to the provider.

2022-09-26 17:20 UTC, katbyte requested changes
Thanks @caius - juts a couple minor comments around the schema

2022-09-26 17:20 UTC, katbyte commented on internal/provider/provider.go
> +				Description: "The path to an OIDC ID token for use when authenticating as a Service Principal using OpenID Connect.",
```suggestion
				Description: "The path to a file containing an OIDC ID token for use when authenticating as a Service Principal using OpenID Connect.",
```

2022-09-26 17:20 UTC, katbyte commented on internal/provider/provider.go
> +			"oidc_token_path": {
would this be better as
```suggestion
			"oidc_token_file_path": {
```

2022-09-26 17:20 UTC, katbyte commented on internal/provider/provider.go
> +				DefaultFunc: schema.EnvDefaultFunc("ARM_OIDC_TOKEN_PATH", ""),
```suggestion
				DefaultFunc: schema.EnvDefaultFunc("ARM_OIDC_TOKEN_FILE_PATH", ""),
```

2022-09-28 21:32 UTC, manicminer approved these changes
Thanks for the contribution @mpminardi! I've gone ahead and vendored in the upstream change and merged in main. Just waiting on the checks & unit tests but this LGTM 👍

2022-09-28 21:53 UTC, merged