azurerm_api_connection - add parameter_value_type property
hashicorp/terraform-provider-azurerm pull request #18393
Opened 2022-09-15 09:28 UTC by Dyhr

I have been attempting to configure a logic app with an API connection using managed identity, specifically with Sentinel, but this does not seem to be supported. According to the [documentation ](https://docs.microsoft.com/en-us/azure/logic-apps/create-managed-service-identity?tabs=consumption#arm-template-for-api-connections-and-managed-identities) the property `parameterValueType` needs to be set to `Alternative`, but this property does not exist in this provider. This PR adds that property.

I have had a hard time finding relevant documentation for this, so feedback or alternative solutions is highly appreciated.

2022-09-28 05:55 UTC, katbyte requested changes
Thanks @Dyhr - in addtion to my comments inline could we update the docs with the new property and add it to the complete test? thanks!

2022-09-28 05:55 UTC, katbyte commented on internal/services/connections/api_connection_resource.go
> +			"parameter_value_type": {
```suggestion
			},

			"parameter_value_type": {
```

2022-09-28 05:55 UTC, katbyte commented on vendor/github.com/hashicorp/go-azure-sdk/resource-manager/web/2016-06-01/connections/model_apiconnectiondefinitionproperties.go
> +	ParameterValueType			 *string                       `json:"parameterValueType,omitempty"`
`make fmt` will fix this

2022-09-28 05:55 UTC, katbyte commented on internal/services/connections/api_connection_resource.go
>  	}
we'll also need to update the read function to read this back in

2022-09-28 06:51 UTC, Dyhr commented
Thank you for the review. After posting this, I realized that the parameter is also missing from Azure's swagger docs, so it will have to be resolved upstream first. I'll get back to this when it resolved on that end.

2022-10-24 15:56 UTC, katbyte commented
👋  @Dyhr  - any update on this? or a link to an issue/pr on the rest-api-specs that we can track or raise internally to get merged?

2023-01-27 00:58 UTC, katbyte commented
Hey @Dyhr - as theres been no update for a few months i'm going to close this out. please do let us know/re open then when theres an update

2023-01-27 00:58 UTC, closed without merging