`azurerm_linux_virtual_machine` `azurerm_windows_virtual_machine` - support for `gallery_applications`
hashicorp/terraform-provider-azurerm pull request #18406
Opened 2022-09-16 07:07 UTC by myc2h6o

This is similar to what we have added in VMSS. And `gallery_applications` in VM is updatable
https://github.com/hashicorp/terraform-provider-azurerm/blob/fa35df5cce72dc7466be7c19d0225cc879156127/website/docs/r/linux_virtual_machine_scale_set.html.markdown?plain=1#L363-L373

2022-09-16 08:17 UTC, myc2h6o commented
Test result (Failed tests are being fixed as part of #17671)
![image](https://user-images.githubusercontent.com/10579712/190590938-55c94727-136b-4f4b-9922-c23df51bdebc.png)

2022-09-24 02:41 UTC, katbyte requested changes

2022-09-24 02:41 UTC, katbyte commented on website/docs/r/linux_virtual_machine.html.markdown
> +-> **NOTE:** The `package_reference_id` should be in the form of `/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Compute/galleries/gallery1/applicatio
should this be called
```suggestion
* `version_id` - (Required) Specifies the Gallery Application Version resource ID.
```
or
```suggestion
* `package_reference_id` - (Required) Specifies the Gallery Application Version resource ID.

-> **NOTE:** The `gallery_application_version_id` should be in the form of `/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Compute/galleries/gallery1/applications/application1/versions/version1`.
```

so the note sins't required?

2022-09-24 02:41 UTC, katbyte commented on website/docs/r/windows_virtual_machine.html.markdown
> +* `configuration_reference_blob_uri` - (Optional) Specifies the URI to an Azure Blob that will replace the default configuration for the package if provided.
is reference make sense here?
```suggestion
* `configuration_blob_uri` - (Optional) Specifies the URI to an Azure Blob that will replace the default configuration for the package if provided.
```

2022-09-24 02:41 UTC, katbyte commented on internal/services/compute/linux_virtual_machine_resource.go
> +			"gallery_applications": VirtualMachineGalleryApplicationsSchema(),
this should be
```suggestion
			"gallery_application": VirtualMachineGalleryApplicationsSchema(),
```

2022-09-26 08:46 UTC, myc2h6o commented
Hi @katbyte thanks for reviewing the pr! The new property names you suggested totally make sense. Just the feature has just been added to VMSS with these property names (could be found in pr description), shall we use the same one from VMSS here, or use the new name instead, add deprecate those in VMSS?

2022-09-27 06:23 UTC, katbyte commented
i think these names are sufficiently better the old ones should be deprecated ?

2022-09-28 09:36 UTC, myc2h6o commented
@katbyte got it! I've updated the property names, please take a look.

2022-09-28 09:37 UTC, myc2h6o commented
After this change is done, I'll start another pr to update these property names in VMSS resources

2022-09-29 00:45 UTC, katbyte approved these changes
LGTM 🌵

2022-09-29 00:46 UTC, merged

2022-10-05 12:22 UTC, farwind commented
seems like functionality was released for both linux and windows properly but release notes states only windows vitrual machine twice : 
"azurerm_storage_account - support for the multichannel_enabled property (https://github.com/hashicorp/terraform-provider-azurerm/issues/17999)
azurerm_windows_virtual_machine - support for the gallery_application property (https://github.com/hashicorp/terraform-provider-azurerm/issues/18406)
azurerm_virtual_hub_bgp_connection - support for the virtual_network_connection_id property (https://github.com/hashicorp/terraform-provider-azurerm/issues/18469)
azurerm_windows_virtual_machine - support for the gallery_application property (https://github.com/hashicorp/terraform-provider-azurerm/issues/18406)"

2022-10-27 22:41 UTC, katbyte commented
thanks @farwind for pointing that out - i've corrected the changelog