`azurerm_role_assignment` - Support scope to be `/providers/Microsoft.Marketplace`
hashicorp/terraform-provider-azurerm pull request #18439
Opened 2022-09-19 08:49 UTC by ms-zhenhua

fix https://github.com/hashicorp/terraform-provider-azurerm/issues/18387

2022-09-20 02:20 UTC, ms-zhenhua commented
Note: `TestAccRoleAssignment_marketPlaceScoped` cannot pass on TC because the SP used by TC does not have authorization to create a `Marketplace Admin` role. The admin should first grant the SP with `owner` access according to this [Doc](https://learn.microsoft.com/en-us/marketplace/create-manage-private-azure-marketplace-new#assign-the-marketplace-admin-role-with-access-control-iam), then run this testcase.

2022-10-24 17:48 UTC, katbyte requested changes
@ms-zhenhua - could we update the docs & add that link and an example powershell of how to grant permissions to a SP?

2022-10-25 02:05 UTC, ms-zhenhua commented
Hi @katbyte, thank you for reviewing. I have updated the document with the related link which contains the information of how to grant permissions to different identities by Azure Portal, Azure PowerShell, Azure Cli and Rest API. Kindly help review it again. Thanks.

2022-10-31 14:46 UTC, manicminer requested changes
@ms-zhenhua I've assigned the `Marketplace Admin` role so you should be able to test this in TC now. I've left another comment below regarding parsing the scope, if you can rework this I'll be happy to re-review. Thanks!

2022-10-31 14:46 UTC, manicminer commented on internal/services/authorization/parse/role_assignment.go
> +		roleAssignmentId.Name = matches[2]
Can we avoid parsing with regular expressions and rather perform simple string matching/splitting? It's better that we test new RPs and explicitly support them.

2022-11-01 05:37 UTC, ms-zhenhua commented
Hi @manicminer, thank you for reviewing. The testcase needs to assign `Marketplace Admin` role to a new SP. But the existing SP with `Marketplace Admin` role does not have the permission to assign `Marketplace Admin` role to a new SP. To make the testcase runnable on TC, could you grant the test SP with the `Owner` role of private marketplace?
![image](https://user-images.githubusercontent.com/76987228/199166116-f100f88b-3a41-4502-80be-54952c1fcfd5.png)

2022-11-01 06:35 UTC, ms-zhenhua commented on website/docs/r/role_assignment.html.markdown
> +~> **NOTE:** The Principal ID is also known as the Object ID (ie not the "Application ID" for applications). To assign Azure roles, the Principal mush have `Microsoft.Authorization/roleAssignments/wr
According to the description of roles on Azure Portal, he calling principal with `Marketplace Admin role` role cannot assign `Marketplace Admin role` to other principals, so I updated this comment as:  
![image](https://user-images.githubusercontent.com/76987228/199173461-56577c75-4784-4585-8312-132b5c368e23.png)

2022-11-01 11:11 UTC, manicminer commented
@ms-zhenhua Ah, I misunderstood, this has now been assigned. Please could you add a comment to the acctest mentioning the required owner role (with docs link)? Thanks!

2022-11-02 23:30 UTC, ms-zhenhua commented
Hi @manicminer, thank you for your update. I have added the comments to the acctest and all related testcases have passed on TC. Kindly help review it again.

2022-11-03 15:35 UTC, katbyte commented
@ms-zhenhua - upon some internal discussion we've come to the conclusion that the role assignment resource should probably be broken out into separate ones for each resource type for an improved UX much like we have different resource for policy assignments.

as such for this resource we could extract it out into  `azurerm_role_assignment_marketplace` and leave the old resource to be refactored at a later time.

WDYT?

2022-11-04 04:29 UTC, ms-zhenhua commented
Hi @katbyte, totally agree. Then I will temporarily close this PR and create a new one for the new resource `azurerm_role_assignment_marketplace`

2022-11-04 04:29 UTC, closed without merging