new resource: `azurerm_dns_resolver`
hashicorp/terraform-provider-azurerm pull request #18473
Opened 2022-09-21 05:22 UTC by ms-henglu

https://github.com/hashicorp/terraform-provider-azurerm/issues/16956

2022-09-24 02:35 UTC, katbyte requested changes
you may need to configure what regions to run this service in:
```
Test Failed

------- Stdout: -------
=== RUN   TestAccDNSResolverDnsResolver_requiresImport
=== PAUSE TestAccDNSResolverDnsResolver_requiresImport
=== CONT  TestAccDNSResolverDnsResolver_requiresImport
=== CONT  TestAccDNSResolverDnsResolver_requiresImport
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Dns Resolver (Subscription: "*******"
        Resource Group Name: "acctest-rg-220922165907733233"
        Dns Resolver Name: "acctest-dr-220922165907733233"): performing CreateOrUpdate: dnsresolvers.DnsResolversClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="The provided location 'westus2' is not available for Microsoft.Network/dnsResolvers and Microsoft.Network/dnsForwardingRulesets resources." Target="" Details=[{}] InnerError={}
        
          with azurerm_dns_resolver.test,
          on terraform_plugin_test.tf line 20, in resource "azurerm_dns_resolver" "test":
          20: resource "azurerm_dns_resolver" "test" {
        
        creating Dns Resolver (Subscription: "*******"
        Resource Group Name: "acctest-rg-220922165907733233"
        Dns Resolver Name: "acctest-dr-220922165907733233"): performing
        CreateOrUpdate: dnsresolvers.DnsResolversClient#CreateOrUpdate: Failure
        sending request: StatusCode=0 -- Original Error: Code="BadRequest"
        Message="The provided location 'westus2' is not available for
        Microsoft.Network/dnsResolvers and Microsoft.Network/dnsForwardingRulesets
        resources." Target="" Details=[{}] InnerError={}
--- FAIL: TestAccDNSResolverDnsResolver_requiresImport (70.39s)
```

2022-09-26 01:37 UTC, ms-henglu commented
Hi @katbyte , maybe disable the `ARM_PROVIDER_DYNAMIC_TEST `?

2022-09-27 23:18 UTC, katbyte commented
No, we can configure this service to only run in certain regions grep for:
```
// Server is only available in certain locations
        "analysisservices" to testConfiguration(locationOverride = LocationConfiguration("westus", "northeurope", "southcentralus", true)),
```

2022-09-28 01:39 UTC, ms-henglu commented
Hi @katbyte , thanks for the suggestion, I've added it into test configs. Please take another look, thanks!

2022-09-30 11:54 UTC, sebader commented
The service itself is very specially called "Azure DNS Private Resolver" (not just DNS resolver). I'd highly recommend to align the name of the terraform resource, too. Or is there a reason to only call it azurerm_dns_resolver?

https://learn.microsoft.com/en-us/azure/dns/dns-private-resolver-overview

2022-10-01 14:29 UTC, ms-henglu commented
Hi @sebader , thanks for the suggestion! I've confirmed with the service's PM, he prefers `azurerm_dns_resolver`, which aligns with azure cli and powershell.

2022-10-01 14:56 UTC, tombuildsstuff commented
@ms-henglu are there plans for this service to also support the Public DNS resources? If not this'd make more sense as `Private DNS` since it's scoped at that?

2022-10-03 16:08 UTC, katbyte commented
@ms-henglu - i agree with @sebader, we should match the correct name and change this to azurerm_dns_private_resolver

2022-10-04 17:03 UTC, sfiguemsft commented
@katbyte @sebader we're looking for consistency with naming which is already in place for PSH and CLI clients

2022-10-13 02:05 UTC, ms-henglu commented
Hi @katbyte , WDYT about 
> we're looking for consistency with naming which is already in place for PSH and CLI clients

2022-10-13 23:07 UTC, katbyte commented
@ms-henglu - are there plans to support public DNS with this service? because if not this the name is misleading and conflicts with the existing nomenclature in the provider with azurerm_private_dns_* for private DNS, and azurerm_dns for public DNS

2022-10-13 23:13 UTC, sfiguemsft commented
> @ms-henglu - are there plans to support public DNS with this service? because if not this the name is misleading and conflicts with the existing nomenclature in the provider with azurerm_private_dns_* for private DNS, and azurerm_dns for public DNS

@katbyte yes, public version will still be under this same service

2022-10-18 15:09 UTC, katbyte approved these changes
Thanks both - with public going into the same service this LGTM now 🙌

2022-10-19 12:49 UTC, desweil commented
@JannoTjarks It is probably true that there never will be a "public resolver SAAS Services". Still I think the name is fine, because it is "THE" Azure DNS Resolver and it already is named like this in PSH (see for [example](https://learn.microsoft.com/en-us/powershell/module/az.dnsresolver/new-azdnsresolver?view=azps-9.0.1) and AZ CLI (see for [example](https://learn.microsoft.com/en-us/cli/azure/dns-resolver?view=azure-cli-latest) from MS.

2022-10-19 17:54 UTC, sfiguemsft commented
> > Thanks both - with public going into the same service this LGTM now 🙌
> 
> Hi @katbyte, I think there is a misunderstanding for this resource. I think, there will never be something like a azure public dns resolver, because there is no need. Microsoft has two possible dns zones: Public DNS und Private DNS. Public DNS can be resolved from the internet. Private DNS Zones can only be resolved from a virtual network in your specific azure tenant. So if you want to resolve a private dns record from your on-premise network, you need a dns resolver in azure for the private dns records. The Azure Private DNS Resolver is Microsoft SaaS Solution for this.
> 
> As I mentioned, public dns can resolved from everyone from anywhere. There is no SaaS from Microsoft needed.
> 
> So I would recommend to use the correct name azure dns private resolver.

@JannoTjarks as product owner of the services mentioned above, I prefer not to disclose any information on this PR related to roadmap and/or directional strategy of Azure DNS. Lets keep consistency with CLI/PSH were possible given that this is the only DNS resolver service from Azure

2022-10-19 18:02 UTC, JannoTjarks commented
Hi @sfiguemsft thanks for the clarification 👍🏻 I understand that the product owner has more insights :D

2022-10-19 21:18 UTC, mbfrahry requested changes
Based on responses here and how the naming is in the portal/docs, the name should not be `azurerm_dns_resolver` and instead be `azurerm_private_dns_resolver`. We should keep it consistent with the other dns resources in Terraform and not psh and cli.

2022-10-19 21:31 UTC, sfiguemsft commented
> Based on responses here and how the naming is in the portal/docs, the name should not be `azurerm_dns_resolver` and instead be `azurerm_dns_private_resolver`. We should keep it consistent with the other dns resources in Terraform and not psh and cli.

@mbfrahry I'm asking the name to be azurerm_dns_resolver and this is what I would like customers to see in the TF modules - if this needs to be formalized through other channel please let me know.

2022-10-19 21:52 UTC, katbyte requested changes
@sfiguemsft - given this is for private DNS only i also agree this should be `azurerm_private_dns_resolver` - our resources names often do not 1:1 match service names and generally are chosen to create the least confusion for our users. Primarily we look to the portal for guidance on what to pick as that is where most people will be using the service/coming to terraform from. Given the existing private dns resources all start `azurerm_private_dns_*` and that the portal also calls it Private resolver users are going to expect/look for "azure private resolver" not "azure dns resolver"

Because of this i concur with everyone else here the name should be `azurerm_private_dns_resolver` to match the portal's chosen name for these resources and match existing resource in terraform. As long as that is its name in the portal (our primary reference for names - not APIs or docs) i don't see us being able to call it something else.

@ms-henglu can we update the name as requested to at the very least get this in for users? we can always add a resource alias later on for a different name if required

2022-10-20 20:22 UTC, katbyte requested changes

2022-10-20 20:22 UTC, katbyte commented on .github/labeler-pull-request-triage.yml
> +  - internal/services/dnsresolver/**/*
```suggestion
service/private-dns-resolver:
  - internal/services/privatednsresolver/**/*
```

2022-10-20 20:22 UTC, katbyte commented on .teamcity/components/generated/services.kt
> +        "dnsresolver" to "DNS Resolver",
```suggestion
        "privatednsresolver" to "Private DNS Resolver",
```

2022-10-20 20:22 UTC, katbyte commented on .teamcity/components/settings.kt
> +        "dnsresolver" to testConfiguration(locationOverride = LocationConfiguration("eastus", "westus3", "westeurope", true)),
```suggestion
        "privatednsresolver" to testConfiguration(locationOverride = LocationConfiguration("eastus", "westus3", "westeurope", true)),
```

2022-10-20 20:22 UTC, katbyte commented on internal/clients/client.go
> +	DNSResolver           *dnsresolver.Client
and here

2022-10-20 20:22 UTC, katbyte commented on internal/clients/client.go
> +	client.DNSResolver = dnsresolver.NewClient(o)
and here

2022-10-20 20:22 UTC, katbyte commented on internal/services/dnsresolver/client/client.go
> +package client
and the path for the service needs to change

2022-10-22 01:45 UTC, katbyte approved these changes
Thanks @ms-henglu - LGTM 🧮

2022-10-22 01:45 UTC, merged

2022-10-27 16:43 UTC, DevopsMercenary commented
Don't see any docs in v3.28.0 for azurerm_private_dns_resolver nor in the release notes.

2022-10-28 02:05 UTC, ms-henglu commented
Hi @DevopsMercenary ,

I guess it was labeled v3.28.0 by mistake, but these resources have been released in v3.29.0, please check: https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.29.0