`azurerm_application_gateway` - fix T`estAccApplicationGateway_sslCertificateManualChangeIgnoreChange`
hashicorp/terraform-provider-azurerm pull request #18492
Opened 2022-09-22 08:45 UTC by wuxu92

`ApplicationGatewaysClient.CreateOrUpdate` with ctx from provider will timeout. so use a new context with a new timeout value.

current failure message: 

```
    testcase.go:110: Step 1/2 error: Check failed: Check 3/3 error: Check 1/1 error: Bad: waiting for update of AGW: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded`
```

![image](https://user-images.githubusercontent.com/2633022/191883023-4d6b8527-0bba-4770-9889-d69c45fb3083.png)

2022-09-22 16:33 UTC, katbyte requested changes

2022-09-22 16:33 UTC, katbyte commented on internal/services/network/application_gateway_resource_test.go
> +		defer cancel()
these always go at the top of functions

2022-09-23 02:27 UTC, wuxu92 commented on internal/services/network/application_gateway_resource_test.go
> +		defer cancel()
moved it up to the top

2022-09-24 03:04 UTC, katbyte approved these changes
LGTM 🧮

2022-09-24 03:04 UTC, merged