Enhance: `azurerm_api_management` - Support `gateway_disabled`, `certificate_source`, `certificate_status`
hashicorp/terraform-provider-azurerm pull request #18508
Opened 2022-09-23 08:07 UTC by xuzhang3

Support config `gateway_disabled`, `certificate_status`, `certificat`

```log
=== RUN   TestAccApiManagement_additionalLocationGateway
=== PAUSE TestAccApiManagement_additionalLocationGateway
=== CONT  TestAccApiManagement_additionalLocationGateway
--- PASS: TestAccApiManagement_additionalLocationGateway (5274.84s)
PASS
```

2022-09-27 16:27 UTC, katbyte approved these changes
LGTM 💎

2022-09-27 16:28 UTC, katbyte requested changes
actually missed a potential panic, comment inline

2022-09-28 03:05 UTC, xuzhang3 commented
> actually missed a potential panic, comment inline

you may forgot to submit the commend 😄

2022-09-29 00:44 UTC, katbyte commented on internal/services/apimanagement/api_management_resource.go
> +			"gateway_disabled":              *prop.DisableGateway,
i did, its here

2022-09-29 16:06 UTC, katbyte approved these changes
LGTM 🦕

2022-09-29 16:06 UTC, merged