`azurerm_windows_function_app`, `azurerm_linux_function_app`: add usage tips
hashicorp/terraform-provider-azurerm pull request #18512
Opened 2022-09-23 08:57 UTC by xiaxyi

2022-09-24 02:30 UTC, katbyte requested changes

2022-09-24 02:30 UTC, katbyte commented on website/docs/r/linux_function_app.html.markdown
> +~> **Note:** please set the node version using `node_version`, instead of specifying `WEBSITE_NODE_DEFAULT_VERSION` in app setting.
should these notes all be on app settings not the property to use instead?

2022-09-24 15:07 UTC, xiaxyi commented
Thanks @katbyte , it makes sense. I modified the code

2022-09-27 06:12 UTC, katbyte approved these changes
LGTM ⚙️

2022-09-27 06:12 UTC, merged