`compute` - ensure `azurerm_marketplace_agreement` cleaned up before vm/vmss test
hashicorp/terraform-provider-azurerm pull request #18522
Opened 2022-09-25 15:13 UTC by myc2h6o

`azurerm_marketplace_agreement` with same combination of `publisher/offer/sku` could only be registered once in the same subscription. If the test exits unexpected, there will be remaining `azurerm_marketplace_agreement` in the subscription. And since it's not within a specific Resource Group, it's not easy to clean up. Thus, adding additional code to cancel the Marketplace Agreement before the tests which uses it, similar to https://github.com/hashicorp/terraform-provider-azurerm/blob/5455c89b189b107828305cb9d177612641dc7e3a/internal/services/compute/marketplace_agreement_resource_test.go#L125
And also updating the offer/sku to be different for VM and VMSS test, so that they won't conflict with each other.

2022-09-25 23:44 UTC, katbyte requested changes

2022-09-25 23:44 UTC, katbyte commented on internal/services/compute/linux_virtual_machine_resource_images_test.go
> +func (r LinuxVirtualMachineResource) cancelExistingAgreement(publisher string, offer string, sku string) acceptance.ClientCheckFunc {
should this be done in the delete function?

2022-09-25 23:46 UTC, katbyte requested changes
How come the tests are failing unexpectedly? should we not be solving that those bugs then working around them?

2022-09-26 01:07 UTC, myc2h6o commented
Hi @katbyte thanks for reviewing the pr! The test creates an `azurerm_marketplace_agreement`, and if things work fine, it is auto cleaned up in the destroy part of test.
But sometimes when the test exits due to some unexpected reason, this resource will remain undeleted. And different from other resources which reside in a resource group, this resides in the subscription directly, so even if we cleaned up the resource groups, this still remains in the subscription and needs manual interfere. e.g. in below test history, before the `azurerm_marketplace_agreement` is cleaned up, it cannot be registered again.
![image](https://user-images.githubusercontent.com/10579712/192175115-1f6bb38d-2bb6-4055-bafa-fe5168826100.png)

2022-09-26 03:17 UTC, myc2h6o commented
Test result
![image](https://user-images.githubusercontent.com/10579712/192187183-06460b1b-63cd-41af-b698-2430721081f0.png)

2022-09-27 23:15 UTC, katbyte approved these changes
LGTM 🧮

2022-09-27 23:15 UTC, merged