`azurerm_iotcentral_application` - fix default `display_name`
hashicorp/terraform-provider-azurerm pull request #18586
Opened 2022-09-30 04:51 UTC by myc2h6o

In the document and Update function, `display_name` is defaults to the ResourceName. However, in Create function it's ResourceGroupName, fixing the value there.

https://github.com/hashicorp/terraform-provider-azurerm/blob/a5a6c08e1c03b722a4b271d19d581bceb01433e6/website/docs/r/iotcentral_application.html.markdown?plain=1#L49

https://github.com/hashicorp/terraform-provider-azurerm/blob/a5a6c08e1c03b722a4b271d19d581bceb01433e6/internal/services/iotcentral/iotcentral_application_resource.go#L190-L193

2022-09-30 05:37 UTC, myc2h6o commented
Test result
![image](https://user-images.githubusercontent.com/10579712/193197902-69ea3739-4160-44c0-8dcf-54bf6b13fb74.png)

2022-10-03 16:07 UTC, katbyte requested changes

2022-10-03 16:07 UTC, katbyte commented on internal/services/iotcentral/iotcentral_application_resource.go
> +		displayName = id.ResourceName
Given we are changing the existing default behaviour can we make this a 4.0 change and wrap it in the flag?

2022-10-08 03:47 UTC, myc2h6o commented
@katbyte thanks for reviewing the pr! I've moved the change behind the 4.0 flag and updated the corresponding document. Please take a look.

2022-10-08 04:25 UTC, myc2h6o commented
Updated test result
![image](https://user-images.githubusercontent.com/10579712/194687979-6fa981df-167d-435f-b18b-4108b45d6649.png)

2022-10-12 01:59 UTC, katbyte approved these changes
Thanks LGTM 🎧

2022-10-12 01:59 UTC, merged