`azurerm_data_factory_integration_runtime_azure_ssis` - support Elastic Pool
hashicorp/terraform-provider-azurerm pull request #18696
Opened 2022-10-11 06:21 UTC by ziyeqf

fix #18079

test
---
```
TF_ACC=1 go test -v ./internal/services/datafactory -run=TestAccDataFactoryIntegrationRuntimeManagedSsis_basic 
=== RUN   TestAccDataFactoryIntegrationRuntimeManagedSsis_basic
=== PAUSE TestAccDataFactoryIntegrationRuntimeManagedSsis_basic
=== CONT  TestAccDataFactoryIntegrationRuntimeManagedSsis_basic
--- PASS: TestAccDataFactoryIntegrationRuntimeManagedSsis_basic (255.56s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/datafactory   256.664s

TF_ACC=1 go test -v ./internal/services/datafactory -run=TestAccDataFactoryIntegrationRuntimeManagedSsis_withElasticPool    
=== RUN   TestAccDataFactoryIntegrationRuntimeManagedSsis_withElasticPool
=== PAUSE TestAccDataFactoryIntegrationRuntimeManagedSsis_withElasticPool
=== CONT  TestAccDataFactoryIntegrationRuntimeManagedSsis_withElasticPool
--- PASS: TestAccDataFactoryIntegrationRuntimeManagedSsis_withElasticPool (423.17s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/datafactory   424.286s

```

2022-10-11 08:23 UTC, magodo requested changes
Thanks for this PR!
I've taken a look through and left some comments inline, but this is mostly looking good to me 👍

2022-10-11 08:23 UTC, magodo commented on internal/services/datafactory/data_factory_integration_runtime_azure_ssis_resource.go
> +						},
Can we add an conflict with for the `elastic_pool_name` and `pricing_tier` as they both correspond to the same API property?

2022-10-11 08:23 UTC, magodo commented on internal/services/datafactory/data_factory_integration_runtime_azure_ssis_resource.go
> +		var pricingTier datafactory.IntegrationRuntimeSsisCatalogPricingTier
Can we add some comments about the fact that both `pricing_tier` and `elastic_pool_name` ends up to the same API prop: `CatalogPricingTier`

2022-10-11 08:23 UTC, magodo commented on internal/services/datafactory/data_factory_integration_runtime_azure_ssis_resource.go
> +		}
Can we put this piece of code to a separate function (like `parseElasticPool()`)? Also we shall simplify it to something like below:

```
{
    matches := regexp.MustCompile(`^ELASTIC_POOL\(name="(.+)"\)$`).FindStringSubmatch(s)
    if len(matches) != 2 {
      return "", false
   }
   return matches[1], true
}
```

2022-10-11 08:23 UTC, magodo commented on internal/services/datafactory/data_factory_integration_runtime_azure_ssis_resource.go
> +func expandDataFactoryIntegrationRuntimeElasticPool(input string) string {
Can we rename this function to `formatDataFactoryIntegrationRuntimeElasticPool`?

2022-10-11 08:23 UTC, magodo commented on website/docs/r/data_factory_integration_runtime_azure_ssis.html.markdown
> +* `elastic_pool_name` - (Optional) the name of SQL elastic pool where the database will be created for the SSIS catalog. (Mutually exclusive with `pricing_tier`.)
```suggestion
* `elastic_pool_name` - (Optional) the name of SQL elastic pool where the database will be created for the SSIS catalog. Mutually exclusive with `pricing_tier`.
```

2022-10-11 08:23 UTC, magodo commented on website/docs/r/data_factory_integration_runtime_azure_ssis.html.markdown
> +* `pricing_tier` - (Optional) Pricing tier for the database that will be created for the SSIS catalog. Valid values are: `Basic`, `S0`, `S1`, `S2`, `S3`, `S4`, `S6`, `S7`, `S9`, `S12`, `P1`, `P2`, `P
```suggestion
* `pricing_tier` - (Optional) Pricing tier for the database that will be created for the SSIS catalog. Valid values are: `Basic`, `S0`, `S1`, `S2`, `S3`, `S4`, `S6`, `S7`, `S9`, `S12`, `P1`, `P2`, `P4`, `P6`, `P11`, `P15`, `GP_S_Gen5_1`, `GP_S_Gen5_2`, `GP_S_Gen5_4`, `GP_S_Gen5_6`, `GP_S_Gen5_8`, `GP_S_Gen5_10`, `GP_S_Gen5_12`, `GP_S_Gen5_14`, `GP_S_Gen5_16`, `GP_S_Gen5_18`, `GP_S_Gen5_20`, `GP_S_Gen5_24`, `GP_S_Gen5_32`, `GP_S_Gen5_40`, `GP_Gen5_2`, `GP_Gen5_4`, `GP_Gen5_6`, `GP_Gen5_8`, `GP_Gen5_10`, `GP_Gen5_12`, `GP_Gen5_14`, `GP_Gen5_16`, `GP_Gen5_18`, `GP_Gen5_20`, `GP_Gen5_24`, `GP_Gen5_32`, `GP_Gen5_40`, `GP_Gen5_80`, `BC_Gen5_2`, `BC_Gen5_4`, `BC_Gen5_6`, `BC_Gen5_8`, `BC_Gen5_10`, `BC_Gen5_12`, `BC_Gen5_14`, `BC_Gen5_16`, `BC_Gen5_18`, `BC_Gen5_20`, `BC_Gen5_24`, `BC_Gen5_32`, `BC_Gen5_40`, `BC_Gen5_80`, `HS_Gen5_2`, `HS_Gen5_4`, `HS_Gen5_6`, `HS_Gen5_8`, `HS_Gen5_10`, `HS_Gen5_12`, `HS_Gen5_14`, `HS_Gen5_16`, `HS_Gen5_18`, `HS_Gen5_20`, `HS_Gen5_24`, `HS_Gen5_32`, `HS_Gen5_40` and `HS_Gen5_80`. Mutually exclusive with `elastic_pool_name`.
```

2022-10-12 14:31 UTC, katbyte approved these changes
LGTM 🏷️

2022-10-12 16:38 UTC, merged