New resource: `azurerm_databricks_access_connector`
hashicorp/terraform-provider-azurerm pull request #18709
Opened 2022-10-12 09:13 UTC by favoretti

Also upgrade Databricks SDK to `2022-04-01-preview` 
I added acceptance tests, but feature is in private preview.

Fixes #18518

2022-10-12 09:19 UTC, nfx commented
Thank you so much, @favoretti !

2022-10-12 13:03 UTC, favoretti commented
@tombuildsstuff One catch about this resource. Apparently SPN auth doesn't work with this API, only user-based auth. Wonder what to do about it..

2022-10-12 13:18 UTC, stephybun requested changes
Thanks for this @favoretti! Since this is still in private preview I expected the tests to fail when trying to create the connector. Unfortunately it's created the connector in a failed state and currently can't be deleted. I'm going to mark this PR as blocked for the time being while we investigate this further.

Also just as an aside all resources within the provider will eventually need to be converted to typed resources for the gradual shift to using Pandora generated ones. Our [contributor docs have a section on how to add new typed resources](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/guide-new-resource.md) which will hopefully be helpful for future contributions 🙂.

2022-10-12 19:41 UTC, favoretti commented
Thanks @stephybun. I completely blacked out on typed resources, I'll rewrite tomorrow, sorry about that. 

That failed connector will eventually be deletable. But the real reason it fails is that API doesn't work with SPN auth. I'm working with @nfx and team to see what the ETA is on supporting that. 

If persona authentication is used - resource works.

2022-10-13 08:09 UTC, nfx commented
@favoretti You say it's the same style of issue as creating the AKV scope for Databricks? 🫣

2022-10-13 08:49 UTC, favoretti commented
@stephybun rewrote this, SPN thing is still under investigation, but can you please have another look code-wise? Thanks!

2022-10-13 10:53 UTC, favoretti commented
> @favoretti You say it's the same style of issue as creating the AKV scope for Databricks? 🫣

@nfx Don't think so. AKV scope talks to Databricks DataPlane API, i.e. directly to the instance. This call is directed at management.azure.com, i.e. ARM API. Although you folks would know better, but I think this one should be easier to address.

2022-10-14 06:58 UTC, favoretti commented
I hear SPN auth should be fixed. I'll retest today.

2022-10-14 08:21 UTC, favoretti commented
Local acceptance tests pass, running TC now.

```
$ TF_ACC=1 go test -v ./internal/services/databricks -timeout=1000m -run='TestAccDatabricksAccessConnector'
=== RUN   TestAccDatabricksAccessConnector_basic
=== PAUSE TestAccDatabricksAccessConnector_basic
=== RUN   TestAccDatabricksAccessConnector_requiresImport
=== PAUSE TestAccDatabricksAccessConnector_requiresImport
=== CONT  TestAccDatabricksAccessConnector_basic
=== CONT  TestAccDatabricksAccessConnector_requiresImport
--- PASS: TestAccDatabricksAccessConnector_basic (164.31s)
--- PASS: TestAccDatabricksAccessConnector_requiresImport (184.18s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/databricks	185.333s
```

2022-10-14 08:38 UTC, favoretti commented
Failed test isn't related to either upgrade or the changes and seems to be transient. All the rest passes.
![image](https://user-images.githubusercontent.com/805046/195802177-8eba78ce-7c59-4a3f-82f2-20be0f10f5e7.png)

2022-10-14 08:38 UTC, favoretti commented
@stephybun should be good to go for another review and potential merge. Would you take a look? Thanks a lot!

2022-10-14 09:09 UTC, stephybun reviewed
A few minor comments on the error messages, other this is good to go!

2022-10-14 09:09 UTC, stephybun commented on internal/services/databricks/databricks_access_connector_resource.go
> +				return fmt.Errorf("reading Access Connector %s: %v", id, err)
```suggestion
				return fmt.Errorf("reading %s: %v", id, err)
```

2022-10-14 09:09 UTC, stephybun commented on internal/services/databricks/databricks_access_connector_resource.go
> +				return fmt.Errorf("updating Access Connector %s: %+v", id, err)
```suggestion
				return fmt.Errorf("updating %s: %+v", id, err)
```

2022-10-14 09:09 UTC, stephybun commented on internal/services/databricks/databricks_access_connector_resource.go
> +				return fmt.Errorf("while checking for Access Connectors's %q existence: %+v", id.ConnectorName, err)
```suggestion
				return fmt.Errorf("retrieving %s: %+v", *id, err)
```

2022-10-14 09:09 UTC, stephybun commented on internal/services/databricks/databricks_access_connector_resource.go
> +				return fmt.Errorf("while removing Access Connector %q: %+v", id.ConnectorName, err)
```suggestion
				return fmt.Errorf("deleting %s: %+v", *id, err)
```

2022-10-14 10:57 UTC, favoretti commented
Thanks for the suggestions, @stephybun, committed, once unit tests complete, we should be gtg.

2022-10-14 10:59 UTC, stephybun approved these changes
Thanks @favoretti LGTM 🧋

2022-10-14 11:00 UTC, merged

2022-10-14 14:27 UTC, nfx commented
🥳

2022-11-10 21:30 UTC, mvvsubbu commented
> Thanks for this @favoretti! Since this is still in private preview I expected the tests to fail when trying to create the connector. Unfortunately it's created the connector in a failed state and currently can't be deleted. I'm going to mark this PR as blocked for the time being while we investigate this further.
> 
> Also just as an aside all resources within the provider will eventually need to be converted to typed resources for the gradual shift to using Pandora generated ones. Our [contributor docs have a section on how to add new typed resources](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/guide-new-resource.md) which will hopefully be helpful for future contributions 🙂.


I am from Databricks Product group and I see the conversation about creation failing with SPN and Private Preview of the resource. Let me clarify those two issues here.

1.  SPN support for Access Connector is enabled in mid of October.
2. Access Connector Resource is in Public Preview (**Not Private Preview**).


We have received a customer escalation about the resource being documented as Private Preview. Can you help us understand the process to update this to Public Preview. 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/databricks_access_connector