app service: add notes to the usage of virtual network properties
hashicorp/terraform-provider-azurerm pull request #18738
Opened 2022-10-13 06:23 UTC by xiaxyi

fix: #18288 
fix: #18225

2022-10-13 06:55 UTC, peterprumbach-telekom commented on website/docs/r/windows_web_app_slot.html.markdown
> +~> **NOTE on regional virtual network integration:** The AzureRM Terraform provider provides regional virtual network integration via the standalone resource [app_service_virtual_network_swift_connec
It's "web app slot" instead of "function app"

2022-10-13 06:56 UTC, peterprumbach-telekom commented on website/docs/r/windows_web_app.html.markdown
> +~> **NOTE on regional virtual network integration:** The AzureRM Terraform provider provides regional virtual network integration via the standalone resource [app_service_virtual_network_swift_connec
It's "web app" instead of "function app"

2022-10-13 06:56 UTC, peterprumbach-telekom commented on website/docs/r/windows_function_app_slot.html.markdown
> +~> **NOTE on regional virtual network integration:** The AzureRM Terraform provider provides regional virtual network integration via the standalone resource [app_service_virtual_network_swift_connec
It's "function app slot" instead of "function app"

2022-10-13 06:56 UTC, peterprumbach-telekom commented on website/docs/r/linux_web_app_slot.html.markdown
> +~> **NOTE on regional virtual network integration:** The AzureRM Terraform provider provides regional virtual network integration via the standalone resource [app_service_virtual_network_swift_connec
It's "web app" instead of "function app"

2022-10-13 06:56 UTC, peterprumbach-telekom commented on website/docs/r/linux_web_app.html.markdown
> +~> **NOTE on regional virtual network integration:** The AzureRM Terraform provider provides regional virtual network integration via the standalone resource [app_service_virtual_network_swift_connec
It's "web app" instead of "function app"

2022-10-13 06:57 UTC, peterprumbach-telekom commented on website/docs/r/linux_function_app_slot.html.markdown
> +~> **NOTE on regional virtual network integration:** The AzureRM Terraform provider provides regional virtual network integration via the standalone resource [app_service_virtual_network_swift_connec
It's "function app slot" instead of "function app"

2022-10-13 07:17 UTC, xiaxyi commented
Thanks @peterprumbach-telekom , updated

2022-10-13 16:37 UTC, stephybun requested changes
Thanks @xiaxyi, I have a suggestion on the wording and the grammar which can be applied to all the notes.

2022-10-13 16:37 UTC, stephybun commented on website/docs/r/linux_function_app.html.markdown
> +~> **NOTE on regional virtual network integration:** The AzureRM Terraform provider provides regional virtual network integration via the standalone resource [app_service_virtual_network_swift_connec
A suggestion on the wording and grammar. 
```suggestion
~> **NOTE on regional virtual network integration:** The AzureRM Terraform provider provides regional virtual network integration via the standalone resource [app_service_virtual_network_swift_connection](app_service_virtual_network_swift_connection.html) and in-line within this resource using the `virtual_network_subnet_id` property. You cannot use both methods simultaneously. If the virtual network is set via the resource `app_service_virtual_network_swift_connection` then `ignore_changes` should be used in the function app configuration.
```

2022-10-14 02:39 UTC, xiaxyi commented
Thanks @stephybun , updated

2022-10-14 05:58 UTC, stephybun approved these changes
Thanks @xiaxyi LGTM 💯

2022-10-14 05:58 UTC, merged

2022-10-24 09:55 UTC, vanmash commented
Hey,

I wouldn't say it is a real solution, rather workaround. Maybe making one of the vnet integration methods obsolete would help? Or improve the documentation, perhaps add a code example.
I admit the documentation mention `ignore_changes` but I'd say it is not clear enough.

Also why there is no such problem with MSSQL Vnet integration?