Remove sql password requirement for synapse
hashicorp/terraform-provider-azurerm pull request #18850
Opened 2022-10-18 22:15 UTC by RaphHaddad

Please excuse any major mistakes. This is my first PR.

This PR removes the requirement for a local SQL User on Synapse as per Azure's constraints.

I am not sure how to add a validation to check either AAD auth or local SQL user enabled. Any direction is appreciated.

2022-10-20 09:55 UTC, stephybun requested changes
Thanks for this PR @RaphHaddad! When properties are not required rather than setting the property `Required` to `false` we set `Optional` to `true`.

We would also still need to add a test to validate that this change works, you can probably just copy one of the existing tests and remove the values for `sql_administrator_login` and `sql_administrator_login_password` in the test config. Once that's done we can run the tests and get this merged.

Thanks!

2022-10-20 09:55 UTC, stephybun commented on internal/services/synapse/synapse_workspace_resource.go
> +				Required:     false,
```suggestion
				Optional:     true,
```

2022-10-20 09:55 UTC, stephybun commented on internal/services/synapse/synapse_workspace_resource.go
> +				Required:  false,
```suggestion
				Optional:  true,
```

2022-10-20 21:34 UTC, RaphHaddad commented
Hello @stephybun, thanks for the guidance.

I have made the changes necessary and added a new test. Can you confirm that the naming is correct for the test?

2022-10-21 06:37 UTC, stephybun requested changes
Thanks @RaphHaddad the tests are passing 🎉 . I forgot to mention the docs need to be updated to reflect this change too, but once that's done this will be good to go!

2022-10-21 23:25 UTC, RaphHaddad commented
@stephybun , done!

2022-10-24 06:13 UTC, stephybun approved these changes
Thanks for this @RaphHaddad LGTM 🌻

2022-10-24 06:13 UTC, merged