`azurerm_network_connection_monitor`: `TestAccNetworkWatcher` set delete os disk of virtual machine
hashicorp/terraform-provider-azurerm pull request #18899
Opened 2022-10-21 03:19 UTC by wuxu92

## Information
There is a `delete_os_disk_on_termination` property of the virtual machine resource that has to be set as `true` to auto-remote the disk resource. or it will cause the destroy of resource group falling.

## What to Fix
There are about 20 test cases that failed for the same reason. one example current error case message:

```
=== RUN   TestAccNetworkWatcher/ConnectionMonitor/vmUpdate
    testing_new.go:84: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Resource Group "acctestRG-Watcher-220815051508682900": the Resource Group still contains Resources.
        
        Terraform is configured to check for Resources within the Resource Group when deleting the Resource Group - and
        raise an error if nested Resources still exist to avoid unintentionally deleting these Resources.
        
        Terraform has detected that the following Resources still exist within the Resource Group:
        
        * `/subscriptions/*******/resourceGroups/ACCTESTRG-WATCHER-220815051508682900/providers/Microsoft.Compute/disks/osdisk-dest220815051508682900`
        * `/subscriptions/*******/resourceGroups/ACCTESTRG-WATCHER-220815051508682900/providers/Microsoft.Compute/disks/osdisk-src220815051508682900`
```

2022-10-21 08:13 UTC, stephybun requested changes
Look like there are still some test failures
```
--- FAIL: TestAccNetworkWatcher (13863.90s)
--- PASS: TestAccNetworkWatcher/basic (834.42s)
--- PASS: TestAccNetworkWatcher/basic/basic (132.50s)
--- PASS: TestAccNetworkWatcher/basic/requiresImport (156.96s)
--- PASS: TestAccNetworkWatcher/basic/complete (196.92s)
--- PASS: TestAccNetworkWatcher/basic/update (170.09s)
--- PASS: TestAccNetworkWatcher/basic/disappears (177.95s)
--- PASS: TestAccNetworkWatcher/DataSource (175.28s)
--- PASS: TestAccNetworkWatcher/DataSource/basic (175.28s)
--- FAIL: TestAccNetworkWatcher/ConnectionMonitor (9231.07s)
--- PASS: TestAccNetworkWatcher/ConnectionMonitor/bothDestinationsInvalid (363.48s)
--- PASS: TestAccNetworkWatcher/ConnectionMonitor/requiresImport (352.63s)
--- FAIL: TestAccNetworkWatcher/ConnectionMonitor/updateEndpoint (368.17s)
--- FAIL: TestAccNetworkWatcher/ConnectionMonitor/vmBasic (925.27s)
--- PASS: TestAccNetworkWatcher/ConnectionMonitor/missingDestinationInvalid (376.25s)
--- PASS: TestAccNetworkWatcher/ConnectionMonitor/addressBasic (463.97s)
--- PASS: TestAccNetworkWatcher/ConnectionMonitor/addressUpdate (722.42s)
--- FAIL: TestAccNetworkWatcher/ConnectionMonitor/vmUpdate (862.46s)
--- FAIL: TestAccNetworkWatcher/ConnectionMonitor/httpConfiguration (972.24s)
--- FAIL: TestAccNetworkWatcher/ConnectionMonitor/icmpConfiguration (320.51s)
--- FAIL: TestAccNetworkWatcher/ConnectionMonitor/addressComplete (309.25s)
--- FAIL: TestAccNetworkWatcher/ConnectionMonitor/destinationUpdate (1254.51s)
--- FAIL: TestAccNetworkWatcher/ConnectionMonitor/bothAddressAndVirtualMachineId (953.69s)
--- FAIL: TestAccNetworkWatcher/ConnectionMonitor/vmComplete (986.22s)
--- FAIL: TestAccNetworkWatcher/PacketCapture (1750.57s)
--- FAIL: TestAccNetworkWatcher/PacketCapture/storageAccountAndLocalDisk (348.58s)
--- PASS: TestAccNetworkWatcher/PacketCapture/withFilters (387.37s)
--- PASS: TestAccNetworkWatcher/PacketCapture/requiresImport (405.72s)
--- FAIL: TestAccNetworkWatcher/PacketCapture/localDisk (304.68s)
--- FAIL: TestAccNetworkWatcher/PacketCapture/storageAccount (304.22s)
--- FAIL: TestAccNetworkWatcher/FlowLog (1872.56s)
--- FAIL: TestAccNetworkWatcher/FlowLog/requiresImport (91.75s)
--- PASS: TestAccNetworkWatcher/FlowLog/disabled (250.02s)
--- PASS: TestAccNetworkWatcher/FlowLog/reenabled (306.73s)
--- PASS: TestAccNetworkWatcher/FlowLog/retentionPolicy (331.62s)
--- PASS: TestAccNetworkWatcher/FlowLog/updateStorageAccount (363.82s)
--- FAIL: TestAccNetworkWatcher/FlowLog/trafficAnalytics (86.17s)
--- PASS: TestAccNetworkWatcher/FlowLog/basic (165.45s)
--- FAIL: TestAccNetworkWatcher/FlowLog/location (89.79s)
--- FAIL: TestAccNetworkWatcher/FlowLog/tags (88.26s)
--- FAIL: TestAccNetworkWatcher/FlowLog/version (98.94s)
```

2022-10-21 08:14 UTC, wuxu92 commented
Sorry, mixed up with another PR's test results 😢

2022-10-24 07:38 UTC, wuxu92 commented
@stephybun the test pass now could you please have a look again?

2022-10-24 13:07 UTC, jackofallops reviewed
Thanks @wuxu92 
Question below that I think needs some clarification before this can proceed.

Thanks again!

2022-10-24 13:15 UTC, wuxu92 commented on internal/services/network/network_connection_monitor_resource_test.go
> +  }
sorry, forget to delete them. these tags will be added automatically for MS subscriptions, so I added them here for local test. they are not required for teamcity. I am going to delete them.

2022-10-31 23:14 UTC, katbyte approved these changes
LGTM 🦕

2022-10-31 23:14 UTC, merged