`azurerm_kubernetes_cluster`: Add support for KEDA Autoscaler
hashicorp/terraform-provider-azurerm pull request #18967
Opened 2022-10-25 10:38 UTC by favoretti

2022-10-25 11:14 UTC, favoretti commented
```
$ TF_ACC=1 go test -v ./internal/services/containers -timeout=1000m -run='TestAccKubernetesCluster_workloadAutoscalerProfileKeda'
=== RUN   TestAccKubernetesCluster_workloadAutoscalerProfileKeda
=== PAUSE TestAccKubernetesCluster_workloadAutoscalerProfileKeda
=== CONT  TestAccKubernetesCluster_workloadAutoscalerProfileKeda
--- PASS: TestAccKubernetesCluster_workloadAutoscalerProfileKeda (803.01s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/containers	804.172s
```

2022-10-26 16:56 UTC, katbyte approved these changes
LGTM 🤖

2022-10-27 07:23 UTC, stephybun requested changes
Thanks for this @favoretti. The behaviour of blocks (at least on this resource) is that if the block was present but then absent the feature should be disabled. While messing around with this I noticed that if I try to disable KEDA by removing the block we aren't disabling it.

```
=== CONT  TestAccKubernetesCluster_workloadAutoscalerProfileKeda
    testcase.go:110: Step 2/2 error: Check failed: Check 2/2 error: azurerm_kubernetes_cluster.test: Attribute 'workload_autoscaler_profile.0.keda_enabled' expected "false", got "true"
```
To elaborate on the above error message I changed the second apply in that test to a config where the block is absent.

Once that's fixed this should be good to go though!

2022-10-27 11:40 UTC, favoretti commented
```
$ TF_ACC=1 go test -v ./internal/services/containers -timeout=1000m -run='TestAccKubernetesCluster_workloadAutoscalerProfileKedaOnOff'
=== RUN   TestAccKubernetesCluster_workloadAutoscalerProfileKedaOnOff
=== PAUSE TestAccKubernetesCluster_workloadAutoscalerProfileKedaOnOff
=== CONT  TestAccKubernetesCluster_workloadAutoscalerProfileKedaOnOff
--- PASS: TestAccKubernetesCluster_workloadAutoscalerProfileKedaOnOff (790.52s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/containers	791.656s
```

```
$ TF_LOG_PATH=debug TF_LOG=trace TF_ACC=1 go test -v ./internal/services/containers -timeout=1000m -run='TestAccKubernetesCluster_workloadAutoscalerProfileKedaOnAbsent'
=== RUN   TestAccKubernetesCluster_workloadAutoscalerProfileKedaOnAbsent
=== PAUSE TestAccKubernetesCluster_workloadAutoscalerProfileKedaOnAbsent
=== CONT  TestAccKubernetesCluster_workloadAutoscalerProfileKedaOnAbsent
--- PASS: TestAccKubernetesCluster_workloadAutoscalerProfileKedaOnAbsent (824.45s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/containers	825.598s
```

2022-10-27 12:16 UTC, stephybun approved these changes
Thanks @favoretti! LGTM 🎉

2022-10-27 12:16 UTC, merged