new resource: `azurerm_private_dns_resolver_outbound_endpoint`
hashicorp/terraform-provider-azurerm pull request #18986
Opened 2022-10-26 02:17 UTC by ms-henglu

https://github.com/hashicorp/terraform-provider-azurerm/issues/16956

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/79895375/197918768-883bfa59-660e-499b-a27c-567735938c71.png">

2022-10-26 15:06 UTC, katbyte requested changes

2022-10-26 15:06 UTC, katbyte commented on website/docs/r/private_dns_resolver_outbound_endpoint.html.markdown
> +* `private_dns_resolver_private_dns_resolver_id` - (Required) Specifies the ID of the Private DNS Resolver Outbound Endpoint. Changing this forces a new Private DNS Resolver Outbound Endpoint to be c
a copy paste error in this file?

2022-10-27 01:49 UTC, ms-henglu commented
Hi @katbyte - Thanks for the code review. I've updated the docs and resolved the conflicts, please take another look, thanks!

2022-10-27 05:40 UTC, stephybun commented on internal/services/privatednsresolver/private_dns_resolver_outbound_endpoint_resource.go
> +	PrivateDNSResolverDnsResolverId string            `tfschema:"private_dns_resolver_id"`
Could this be 
```suggestion
	PrivateDnsResolverId string            `tfschema:"private_dns_resolver_id"`
```

2022-10-27 06:38 UTC, stephybun approved these changes
Thanks @ms-henglu LGTM 💯

2022-10-27 06:38 UTC, merged