`azurerm_api_management` - fix `subnet_id` case sensitivity
hashicorp/terraform-provider-azurerm pull request #18988
Opened 2022-10-26 03:25 UTC by teowa

Resolves https://github.com/hashicorp/terraform-provider-azurerm/issues/18399

2022-10-26 05:22 UTC, katbyte requested changes

2022-10-26 05:22 UTC, katbyte commented on internal/services/apimanagement/api_management_resource.go
> +		subnetId, _ := networkParse.SubnetID(*input.SubnetResourceID)
can we nil check this deference?

2022-10-31 23:24 UTC, katbyte requested changes

2022-10-31 23:24 UTC, katbyte commented on internal/services/apimanagement/api_management_resource.go
> +		subnetId, err := networkParse.SubnetID(*input.SubnetResourceID)
should this not be `SubnetIDInsensitively` ?

2022-11-01 14:40 UTC, tombuildsstuff approved these changes
LGTM providing the tests pass 👍

2022-11-02 08:59 UTC, teowa commented
![image](https://user-images.githubusercontent.com/104055472/199445735-36b3250b-8b1d-4f50-ae7d-a76e82a41f77.png)

The failed test also fail in main branch.

2022-11-02 19:12 UTC, merged