`azurerm_mssql_virtual_machine` - support `sql_instance_setting`
hashicorp/terraform-provider-azurerm pull request #19123
Opened 2022-11-03 09:10 UTC by myc2h6o

Fix #15824

2022-11-03 13:35 UTC, myc2h6o commented
Test result
![image](https://user-images.githubusercontent.com/10579712/199734943-e79a5e30-f7c9-4ab8-b1ba-b539f4e05dee.png)

2022-11-03 15:52 UTC, katbyte requested changes
just one comment to address and then this looks good

2022-11-03 15:52 UTC, katbyte commented on internal/services/mssql/mssql_virtual_machine_resource.go
> +			"sql_instance_setting": {
setting seems redundant?
```suggestion
			"sql_instance": {
```

2022-11-04 08:54 UTC, myc2h6o commented on internal/services/mssql/mssql_virtual_machine_resource.go
> +			"sql_instance_setting": {
Have removed `_setting`.

2022-11-04 08:56 UTC, myc2h6o commented
Hi @katbyte thanks for reviewing the pr! I've updated the code according to the comment. Please take a look

2022-11-06 22:00 UTC, katbyte approved these changes
thanks @myc2h6o - LGTM 🦀

2022-11-06 22:00 UTC, merged