New RP `automanage` with three new resources
hashicorp/terraform-provider-azurerm pull request #19166
Opened 2022-11-07 08:33 UTC by liuwuliuyun

new resource `azurerm_automanage_configuration_profile`
new resource `azurerm_automanage_configuration_profile_assignment`
new resource `azurerm_automanage_configuration_profile_hci_assignment`

2022-11-07 08:44 UTC, liuwuliuyun commented
Testing evidence on Teamcity will be provided shortly.

2022-11-07 10:37 UTC, liuwuliuyun commented
![image](https://user-images.githubusercontent.com/17947406/200289909-a210136c-c0e2-403b-9cda-bc6a21bd6fee.png)

2022-11-08 15:24 UTC, katbyte requested changes

2022-11-08 15:24 UTC, katbyte commented on website/docs/r/automanage_configuration_profiles.html.markdown
> +  configuration       = "{\"Antimalware/Enable\":false,\"AzureSecurityCenter/Enable\":true,\"Backup/Enable\":false,\"BootDiagnostics/Enable\":true,\"ChangeTrackingAndInventory/Enable\":true,\"GuestCo
this is json so would it be better as
```suggestion
  configuration_json       = "{\"Antimalware/Enable\":false,\"AzureSecurityCenter/Enable\":true,\"Backup/Enable\":false,\"BootDiagnostics/Enable\":true,\"ChangeTrackingAndInventory/Enable\":true,\"GuestConfiguration/Enable\":true,\"LogAnalytics/Enable\":true,\"UpdateManagement/Enable\":true,\"VMInsights/Enable\":true}"
```

2022-11-08 15:24 UTC, katbyte commented on website/docs/r/automanage_configuration_profile_hci_assignments.html.markdown
> +  configuration_profile = "/providers/Microsoft.Automanage/bestPractices/AzureBestPracticesProduction"
this is an id?
```suggestion
  configuration_profile_id = "/providers/Microsoft.Automanage/bestPractices/AzureBestPracticesProduction"
```

2022-11-08 15:24 UTC, katbyte commented on website/docs/r/automanage_configuration_profile_assignments.html.markdown
> +* `configuration_profile` - (Required) The Automanage configurationProfile ARM Resource URI.
this is an id?
```suggestion
* `configuration_profile_id` - (Required) The Automanage configurationProfile ARM Resource URI.
```

2022-11-09 04:23 UTC, liuwuliuyun commented on website/docs/r/automanage_configuration_profiles.html.markdown
> +  configuration       = "{\"Antimalware/Enable\":false,\"AzureSecurityCenter/Enable\":true,\"Backup/Enable\":false,\"BootDiagnostics/Enable\":true,\"ChangeTrackingAndInventory/Enable\":true,\"GuestCo
Done

2022-11-09 04:24 UTC, liuwuliuyun commented on website/docs/r/automanage_configuration_profile_hci_assignments.html.markdown
> +  configuration_profile = "/providers/Microsoft.Automanage/bestPractices/AzureBestPracticesProduction"
Done

2022-11-09 04:24 UTC, liuwuliuyun commented on website/docs/r/automanage_configuration_profile_assignments.html.markdown
> +* `configuration_profile` - (Required) The Automanage configurationProfile ARM Resource URI.
Done

2022-11-15 10:11 UTC, stephybun requested changes
Thanks for this PR @liuwuliuyun. There are a number of issues that need to be fixed up in addition to the ones I've left in line:

1. These need to be typed resources, because these will have to be typed resources in the future
2. The create and update methods should be split and take advantage of `d.HasChanges()`, so that ignore changes works
3. We need to remove the `managed_by` and `type` properties since they're not something users should need to set or care about
4. The `configuration_json` property in `azurerm_automanage_configuration_profile` needs to be exposed as individual properties or a block of properties if it makes sense to group them, could you provide some examples of how this is supposed to be used?

Once the points above have been addressed we can take another look through this.

Thanks!

2022-11-16 02:29 UTC, liuwuliuyun commented
Thanks for the comment, I will work on the improvment and let you know the progress.

2022-11-16 09:20 UTC, liuwuliuyun commented
Hi @katbyte and @stephybun, I agree that swiching to Typed SDK is good for future update. But switching to typed sdk will result in a lot code change, and make it hard to review. So I will close this PR for now and open a new one after switching.

2022-11-16 09:20 UTC, closed without merging