`azurerm_postgresql_flexible_server` - support for `auth_config`, `azurerm_postgresql_flexible_server_active_directory_administrator` - add new resource
hashicorp/terraform-provider-azurerm pull request #19269
Opened 2022-11-14 06:14 UTC by ziyeqf

--draft to run acctest on TC---

fix 18838

2022-11-14 21:54 UTC, katbyte requested changes
noticed while passing through

2022-11-16 18:53 UTC, catriona-m commented on website/docs/r/postgresql_flexible_server_active_directory_administrator.html.markdown
> +* `principal_type` - (Required) The type of Azure active directory principal. Possible values are `Group`, `ServicePrincipal` and `User`.
It looks like these are ForceNew in the schema, so we should add Changing this forces a new resource to be created. to these descriptions.

2022-11-17 14:22 UTC, catriona-m requested changes
Thanks @ziyeqf, I noticed a couple of other minor things that could be fixed up when looking through again, but overall this is looking good. Thanks!

2022-11-18 13:56 UTC, catriona-m approved these changes
Thanks @ziyeqf LGTM!

2022-11-18 13:57 UTC, merged