Docs: Fix document possible value missed of 45 resources
hashicorp/terraform-provider-azurerm pull request #19270
Opened 2022-11-14 08:14 UTC by wuxu92

This PR is to fix the documents in which the property `ValidateFunc` is `StringInSlice` but some values are missed in the document.

2022-11-14 10:30 UTC, stephybun requested changes
Thanks for this @wuxu92, I left a review comment over in #19271 which is relevant for this PR as well, would you mind applying those suggestions to this one as well? Thanks!

2022-11-15 02:42 UTC, wuxu92 commented
This PR only adds the missed values, it's different from 19271. I have updated both of them though.

2022-11-15 09:36 UTC, stephybun commented on website/docs/r/iot_time_series_insights_standard_environment.html.markdown
> +* `sku_name` - (Required) Specifies the SKU Name for this IoT Time Series Insights Standard Environment. It is string consisting of two parts separated by an underscore(\_).The fist part is the `name
```suggestion
* `sku_name` - (Required) Specifies the SKU Name for this IoT Time Series Insights Standard Environment. It is string consisting of two parts separated by an underscore(\_).The first part is the `name`, valid values include: `S1_1`, `S1_2`, `S1_3`, `S1_4`, `S1_5`, `S1_6`, `S1_7`, `S1_8`, `S1_9`, `S1_10`, `S2_1`, `S2_2`, `S2_3`, `S2_4`, `S2_5`, `S2_6`, `S2_7`, `S2_8`, `S2_9` and `S2_10`. The second part is the `capacity` (e.g. the number of deployed units of the `sku`), which must be a positive `integer` (e.g. `S1_1`). Changing this forces a new resource to be created.
```

2022-11-15 09:37 UTC, stephybun commented on website/docs/r/mssql_managed_instance.html.markdown
> +* `license_type` - (Required) What type of license the Managed Instance will use. Valid values include can be `LicenseIncluded` and `BasePrice`.
```suggestion
* `license_type` - (Required) What type of license the Managed Instance will use. Possible values are `LicenseIncluded` and `BasePrice`.
```

2022-11-15 09:38 UTC, stephybun commented on website/docs/r/mssql_server_security_alert_policy.html.markdown
> +* `state` - (Required) Specifies the state of the policy, whether it is enabled or disabled or a policy has not been applied yet on the specific database server. Allowed values are: `Disabled`, `Enab
```suggestion
* `state` - (Required) Specifies the state of the policy, whether it is enabled or disabled or a policy has not been applied yet on the specific database server. Possible values are `Disabled`, `Enabled` and `New`.
```

2022-11-15 09:39 UTC, stephybun commented on website/docs/r/synapse_spark_pool.html.markdown
> +* `node_size_family` - (Required) The kind of nodes that the Spark Pool provides. Possible value is `MemoryOptimized` and `None`.
```suggestion
* `node_size_family` - (Required) The kind of nodes that the Spark Pool provides. Possible values are `MemoryOptimized` and `None`.
```

2022-11-15 09:39 UTC, stephybun commented on website/docs/r/synapse_spark_pool.html.markdown
> +* `node_size` - (Required) The level of node in the Spark Pool. Possible value is `Small`, `Medium`, `Large`, `None`, `XLarge`, `XXLarge` and `XXXLarge`.
```suggestion
* `node_size` - (Required) The level of node in the Spark Pool. Possible values are `Small`, `Medium`, `Large`, `None`, `XLarge`, `XXLarge` and `XXXLarge`.
```

2022-11-15 09:39 UTC, stephybun commented on website/docs/r/synapse_sql_pool_security_alert_policy.html.markdown
> +* `policy_state` - (Required) Specifies the state of the policy, whether it is enabled or disabled or a policy has not been applied yet on the specific SQL pool. Allowed values are: `Disabled`, `Enab
```suggestion
* `policy_state` - (Required) Specifies the state of the policy, whether it is enabled or disabled or a policy has not been applied yet on the specific SQL pool. Possible values are `Disabled`, `Enabled` and `New`.
```

2022-11-15 09:39 UTC, stephybun commented on website/docs/r/synapse_workspace_security_alert_policy.html.markdown
> +* `policy_state` - (Required) Specifies the state of the policy, whether it is enabled or disabled or a policy has not been applied yet on the specific workspace. Allowed values are: `Disabled`, `Ena
```suggestion
* `policy_state` - (Required) Specifies the state of the policy, whether it is enabled or disabled or a policy has not been applied yet on the specific workspace. Possible values are `Disabled`, `Enabled` and `New`.
```

2022-11-15 09:40 UTC, stephybun commented on website/docs/r/windows_function_app_slot.html.markdown
> +* `node_version` - (Optional) The version of Node to use. Possible values include `~12`, `~14`, `~16` and `~18`.
```suggestion
* `node_version` - (Optional) The version of Node to use. Possible values are `~12`, `~14`, `~16` and `~18`.
```

2022-11-16 07:08 UTC, stephybun approved these changes
Thanks @wuxu92 LGTM 🌻

2022-11-16 07:08 UTC, merged