`azurerm_storage_account` - fix crash in multichannel checking
hashicorp/terraform-provider-azurerm pull request #19298
Opened 2022-11-15 10:32 UTC by jackofallops

Fixes #19220

2022-11-15 15:19 UTC, tombuildsstuff requested changes
Left a few comments inline but otherwise 👍

2022-11-15 15:19 UTC, tombuildsstuff commented on internal/services/storage/storage_account_resource_test.go
> +  share_properties {}
the `share_properties` block also wants to become un-computed fwiw?

2022-11-16 10:01 UTC, jackofallops commented on internal/services/storage/storage_account_resource.go
>  				}
This is dual purpose here, we need to error on `*smb.Multichannel.Enabled == true` and zero the `*smb.Multichannel` regardless, hence the split of `if` conditions, so I think this is correct as is?

2022-11-16 10:09 UTC, jackofallops commented on internal/services/storage/storage_account_resource.go
> +		if accountTier != string(storage.SkuTierPremium) && shareProperties.FileServicePropertiesProperties.ProtocolSettings != nil {
Good shout

2022-11-24 10:42 UTC, tombuildsstuff approved these changes
LGTM 👍

2022-11-24 10:42 UTC, tombuildsstuff commented on internal/services/storage/storage_account_resource.go
>  				}
sorry missed this notification - sounds good/works for me

2022-11-24 11:01 UTC, merged