Fixes inconsistency `Required`, `Optional` and `ForceNew` properties between code and document.
hashicorp/terraform-provider-azurerm pull request #19514
Opened 2022-12-01 02:23 UTC by liuwuliuyun

This PR checks and updates inconsistency `Required`, `Optional` and `ForceNew` properties between code and document. I took the code as the ground truth and update document accordingly.

1. for `Required` property in code - mark doc as `(Required)`.
2. for `Optional` property in code - mark doc as `(Optional)`.
3. for `ForceNew` property in code - mark doc as `Changing this forces a new resource to be created`.

fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/19471

2022-12-01 11:44 UTC, stephybun requested changes
Thanks @liuwuliuyun it's great to have these consistent with the code. There are a number of places where there's a full stop missing, or text gets inserted in the wrong places or duplicated even, can you please go through and fix those? Then it should be good to go.

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/local_network_gateway.html.markdown
>      forces a new resource to be created.
```suggestion
* `name` - (Required) The name of the local network gateway. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/local_network_gateway.html.markdown
>      create the local network gateway.
```suggestion
* `resource_group_name` - (Required) The name of the resource group in which to create the local network gateway. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/local_network_gateway.html.markdown
>      created. Changing this forces a new resource to be created.
```suggestion
* `location` - (Required) The location/region where the local network gateway is created. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/logic_app_standard.html.markdown
> +* `resource_group_name` - (Required) The name of the resource group in which to create the Logic App Changing this forces a new resource to be created.
```suggestion
* `resource_group_name` - (Required) The name of the resource group in which to create the Logic App. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/logic_app_standard.html.markdown
> +* `storage_account_name` - (Required) The backend storage account name which will be used by this Logic App (e.g. for Stateful workflows data) Changing this forces a new resource to be created.
```suggestion
* `storage_account_name` - (Required) The backend storage account name which will be used by this Logic App (e.g. for Stateful workflows data). Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/managed_disk.html.markdown
> +* `source_resource_id` - (Optional) The ID of an existing Managed Disk or Snapshot to copy when `create_option` is `Copy` or the recovery point to restore when `create_option` is `Restore` Changing t
```suggestion
* `source_resource_id` - (Optional) The ID of an existing Managed Disk or Snapshot to copy when `create_option` is `Copy` or the recovery point to restore when `create_option` is `Restore`. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/redis_cache.html.markdown
>      create the Redis instance.
```suggestion
* `resource_group_name` - (Required) The name of the resource group in which to create the Redis instance. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/sql_firewall_rule.html.markdown
>      create the SQL Server.
```suggestion
* `resource_group_name` - (Required) The name of the resource group in which to create the SQL Server. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/storage_blob.html.markdown
>      for the blob to be created. Changing this forces a new resource to be created. This field cannot be specified for Append blobs and cannot be specified if `source` or `source_content` is specified
```suggestion
* `source_uri` - (Optional) The URI of an existing blob, or a file in the Azure File service, to use as the source contents for the blob to be created. Changing this forces a new resource to be created. This field cannot be specified for Append blobs and cannot be specified if `source` or `source_content` is specified.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/storage_share.html.markdown
>   Changing this forces a new resource to be created.
```suggestion
* `storage_account_name` - (Required) Specifies the storage account in which to create the share. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/storage_table.html.markdown
>   Changing this forces a new resource to be created.
```suggestion
* `storage_account_name` - (Required) Specifies the storage account in which to create the storage table. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/storage_table_entity.html.markdown
>   Changing this forces a new resource to be created.
```suggestion
* `storage_account_name` - (Required) Specifies the storage account in which to create the storage table entity. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/storage_table_entity.html.markdown
>  Changing this forces a new resource to be created.
```suggestion
* `table_name` - (Required) The name of the storage table in which to create the storage table entity. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/subnet.html.markdown
> +* `name` - (Required) The name of the subnet. Changing this forces a new resource to be created. Changing this forces a new resource to be created.
```suggestion
* `name` - (Required) The name of the subnet. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/subnet.html.markdown
> +* `resource_group_name` - (Required) The name of the resource group in which to create the subnet. Changing this forces a new resource to be created. Changing this forces a new resource to be created
```suggestion
* `resource_group_name` - (Required) The name of the resource group in which to create the subnet. Changing this forces a new resource to be created.

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/subnet.html.markdown
> +* `virtual_network_name` - (Required) The name of the virtual network to which to attach the subnet. Changing this forces a new resource to be created. Changing this forces a new resource to be creat
```suggestion
* `virtual_network_name` - (Required) The name of the virtual network to which to attach the subnet. Changing this forces a new resource to be created.

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/template_deployment.html.markdown
>      create the template deployment.
```suggestion
* `resource_group_name` - (Required) The name of the resource group in which to create the template deployment. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_desktop_application.html.markdown
>      Virtual Desktop Application. Changing the ID forces a new resource to be created.
```suggestion
* `application_group_id` - (Required) Resource ID for a Virtual Desktop Application Group to associate with the Virtual Desktop Application. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_desktop_application_group.html.markdown
>      a new resource to be created.
```suggestion
* `resource_group_name` - (Required) The name of the resource group in which to create the Virtual Desktop Application Group. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_desktop_application_group.html.markdown
>      located. Changing the location/region forces a new resource to be created.
```suggestion
* `location` - (Required) The location/region where the Virtual Desktop Application Group is located. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_desktop_host_pool.html.markdown
>      forces a new resource to be created.
```suggestion
* `name` - (Required) The name of the Virtual Desktop Host Pool. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_desktop_host_pool.html.markdown
>      a new resource to be created.
```suggestion
* `resource_group_name` - (Required) The name of the resource group in which to create the Virtual Desktop Host Pool. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_desktop_host_pool.html.markdown
>      located. Changing the location/region forces a new resource to be created.
```suggestion
* `location` - (Required) The location/region where the Virtual Desktop Host Pool is located. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_desktop_host_pool.html.markdown
>      `Direct` Assignment – Admin selects a specific host to assign to an user.
```suggestion
* `personal_desktop_assignment_type` - (Optional) `Automatic` assignment – The service will select an available host and assign it to an user. Possible values are `Automatic` and `Direct`. `Direct` Assignment – Admin selects a specific host to assign to an user. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_desktop_workspace.html.markdown
>      forces a new resource to be created.
```suggestion
* `name` - (Required) The name of the Virtual Desktop Workspace. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_desktop_workspace.html.markdown
>      a new resource to be created.
```suggestion
* `resource_group_name` - (Required) The name of the resource group in which to create the Virtual Desktop Workspace. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_machine_extension.html.markdown
>      this forces a new resource to be created.
```suggestion
* `name` - (Required) The name of the virtual machine extension peering. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_network_gateway.html.markdown
>    located. Changing the location/region forces a new resource to be created.
```suggestion
* `location` - (Required) The location/region where the Virtual Network Gateway is located. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_network_gateway.html.markdown
>    forces a new resource to be created.
```suggestion
* `name` - (Required) The name of the Virtual Network Gateway. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_network_gateway.html.markdown
>    a new resource to be created.
```suggestion
* `resource_group_name` - (Required) The name of the resource group in which to create the Virtual Network Gateway. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_network_gateway.html.markdown
>      `vnetGatewayConfig`.
```suggestion
* `name` - (Optional) A user-defined name of the IP configuration. Defaults to `vnetGatewayConfig`. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_network_gateway_connection.html.markdown
>      create the connection Changing the name forces a new resource to be created.
```suggestion
* `resource_group_name` - (Required) The name of the resource group in which to create the connection Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_network_gateway_connection.html.markdown
>      located. Changing this forces a new resource to be created.
```suggestion
* `location` - (Required) The location/region where the connection is located. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_network_gateway_connection.html.markdown
>      to be created.
```suggestion
* `type` - (Required) The type of connection. Valid options are `IPsec` (Site-to-Site), `ExpressRoute` (ExpressRoute), and `Vnet2Vnet` (VNet-to-VNet). Each connection type requires different mandatory arguments (refer to the examples above). Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_network_gateway_connection.html.markdown
>      resource to be created.
```suggestion
* `virtual_network_gateway_id` - (Required) The ID of the Virtual Network Gateway in which the connection will be created. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_network_gateway_connection.html.markdown
>      The Express Route Circuit can be in the same or in a different subscription.
```suggestion
* `express_route_circuit_id` - (Optional) The ID of the Express Route Circuit when creating an ExpressRoute connection (i.e. when `type` is `ExpressRoute`). The Express Route Circuit can be in the same or in a different subscription. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_network_gateway_connection.html.markdown
>      in a different subscription.
```suggestion
* `peer_virtual_network_gateway_id` - (Optional) The ID of the peer virtual network gateway when creating a VNet-to-VNet connection (i.e. when `type` is `Vnet2Vnet`). The peer Virtual Network Gateway can be in the same or in a different subscription. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_network_gateway_connection.html.markdown
>  -> **Note:** Only valid for `IPSec` connections on virtual network gateways with SKU `VpnGw1`, `VpnGw2`, `VpnGw3`, `VpnGw1AZ`, `VpnGw2AZ` or `VpnGw3AZ`.
```suggestion
* `connection_protocol` - (Optional) The IKE protocol version to use. Possible values are `IKEv1` and `IKEv2`, values are `IKEv1` and `IKEv2`. Defaults to `IKEv2`. Changing this forces a new resource to be created.
-> **Note:** Only valid for `IPSec` connections on virtual network gateways with SKU `VpnGw1`, `VpnGw2`, `VpnGw3`, `VpnGw1AZ`, `VpnGw2AZ` or `VpnGw3AZ`.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/virtual_network_peering.html.markdown
> +* `resource_group_name` - (Required) The name of the resource group in which to Changing this forces a new resource to be created.
Please remove the duplicate notices here

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/vpn_gateway.html.markdown
>  [Microsoft Docs](https://docs.microsoft.com/azure/virtual-wan/virtual-wan-site-to-site-portal#gateway) to create a VPN Gateway. Changing this forces a new resource to be created.
```suggestion
* `routing_preference` - (Optional) Azure routing preference lets you to choose how your traffic routes between Azure and the internet. You can choose to route traffic either via the Microsoft network (default value, `Microsoft Network`), or via the ISP network (public internet, set to `Internet`). More context of the configuration can be found in the [Microsoft Docs](https://docs.microsoft.com/azure/virtual-wan/virtual-wan-site-to-site-portal#gateway) to create a VPN Gateway. Changing this forces a new resource to be created.
```

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/web_pubsub.html.markdown
> +* `location` - (Required) Specifies the supported Azure location where the Web PubSub service exists. Changing this Changing this forces a new resource to be created.
Same here

2022-12-01 11:44 UTC, stephybun commented on website/docs/r/web_pubsub_hub.html.markdown
> +* `name` - (Required) The name of the Web Pubsub hub service. Changing this forces a new resource to be created. Changing this forces a new resource to be created.
```suggestion
* `name` - (Required) The name of the Web Pubsub hub service. Changing this forces a new resource to be created.
```

2022-12-02 01:20 UTC, liuwuliuyun commented
Thanks for the review, let me make an update on this.

2022-12-02 09:16 UTC, stephybun approved these changes
Thanks @liuwuliuyun LGTM 👍

2022-12-02 09:18 UTC, merged

2022-12-05 01:47 UTC, wuxu92 reviewed
some property already has a mark of `Changing this forces a new resource to be created` but this PR also appended a repeated one.

2022-12-05 02:10 UTC, liuwuliuyun commented on website/docs/r/private_endpoint.html.markdown
> +* `subresource_name` - (Required) Specifies the subresource this IP address applies to. `subresource_names` corresponds to `group_id` and in this context is also used for `member_name`. Changing this
Good point, let me detect and fix this in a seperate PR