`azurerm_kubernetes_cluster` - support for the `kube_proxy` property
hashicorp/terraform-provider-azurerm pull request #19567
Opened 2022-12-06 02:50 UTC by ms-henglu

```
=== RUN   TestAccKubernetesCluster_kubeProxy
=== PAUSE TestAccKubernetesCluster_kubeProxy
=== CONT  TestAccKubernetesCluster_kubeProxy
--- PASS: TestAccKubernetesCluster_kubeProxy (809.84s)
PASS
```

2022-12-08 15:07 UTC, stephybun requested changes
Thanks for this PR @ms-henglu, i've left several questions and comments in-line, once those are resolved we can take another look through.

2022-12-08 15:07 UTC, stephybun commented on website/docs/r/kubernetes_cluster.html.markdown
> +* `ipvs_config` - (Optional) A `ipvs_config` block.
```suggestion
* `ipvs_config` - (Optional) An `ipvs_config` block.
```

2022-12-08 15:07 UTC, stephybun commented on website/docs/r/kubernetes_cluster.html.markdown
> +A `ipvs_config` block supports the following:
```suggestion
An `ipvs_config` block supports the following:
```

2022-12-08 15:13 UTC, NissesSenap commented
Great to see that this feature is coming.
I might misunderstand the code but It feels like a feature is missing.

In https://learn.microsoft.com/en-us/azure/aks/configure-kube-proxy it's an option to disable `kube-proxy` all together.

```.json
{
  "enabled": true,
  "mode": "IPVS",
  "ipvsConfig": {
    "scheduler": "LeastConnection",
    "TCPTimeoutSeconds": 900,
    "TCPFINTimeoutSeconds": 120,
    "UDPTimeoutSeconds": 300
  }
}
```

This is something that needs to be supported, especially together with BYOCNI mode.

2022-12-08 15:34 UTC, stephybun commented
@NissesSenap, the omission of the block in the config should disable `kube_proxy` for the cluster. We have a [section in the contributor docs](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/schema-design-considerations.md) explaining how to map features that are toggled with an `Enabled` field and how blocks should behave in the provider. Hopefully that helps in clarifying any confusion!

2022-12-08 15:43 UTC, NissesSenap commented
Thanks for the quick reply @stephybun.
From reading the docs my understanding is that it should contain `optional_feature_enabled`, for example `open_service_mesh_enabled`.

This feature is also optional, so I think we are missing the `kube_proxy_enabled` from this PR.
But I could of course misunderstand it.

2022-12-09 02:30 UTC, ms-henglu commented on internal/services/containers/kubernetes_cluster_resource.go
> +	}
I've removed this if block and made the `mode` a required field.

2022-12-09 05:45 UTC, NissesSenap commented
@stephybun once again I might be wrong but I'm rather sure that what you describe would be a breaking change.

The kube-proxy config supports three big configuration areas according to my understanding of https://learn.microsoft.com/en-us/azure/aks/configure-kube-proxy.

## Configure kube-proxy to use IPVS

A new feature in AKS that makes it possible to use IPVS in kube-proxy

```.json
{
  "enabled": true,
  "mode": "IPVS",
  "ipvsConfig": {
    "scheduler": "LeastConnection",
    "TCPTimeoutSeconds": 900,
    "TCPFINTimeoutSeconds": 120,
    "UDPTimeoutSeconds": 300
  }
}
```

## Configure kube-proxy to use IPAM

This is the default setting and currently used by all AKS clusters (don't know the exact config but something like this).

```.json
{
  "enabled": true,
  "mode": "IPAM",
  "ipvsConfig": {
    "scheduler": "LeastConnection",
    "TCPTimeoutSeconds": 900,
    "TCPFINTimeoutSeconds": 120,
    "UDPTimeoutSeconds": 300
  }
}
```

## Disable kube-proxy

If you want to disable kube-proxy from running in your cluster all together.

```.json
{
  "enabled": false,
}
```

What you describe in your last comment

```.hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "myakscluster"

...

  network_profile {
    network_plugin = "azure"
  }

...

}
```

Would disable kube-proxy on all clusters that have defined the `network_profile`.

This is **not** what you want.

## Real example

This is my current setting in my cluster when using BYOCNI in AKS.
According to your example this config would be `kube_proxy = disabled` on the cluster.

```.hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "myakscluster"

...
  network_profile {
    network_plugin    = "none"
    load_balancer_sku = "standard"
    load_balancer_profile {
      outbound_ip_prefix_ids = [
        var.aks_public_ip_prefix_id
      ]
    }
  }
...
```

## Summary

All I want to do is to disable kube-proxy from running on my cluster all together.
If I still have misunderstood you I'm sorry about wasting your time and all I can say is that I'm looking forward to the new feature.

2023-01-05 14:45 UTC, stephybun requested changes

2023-01-05 14:45 UTC, stephybun commented on internal/services/containers/kubernetes_cluster_resource.go
> +		KubeProxyConfig: expandKubernetesClusterKubeProxyConfig(config["kube_proxy"].([]interface{})),
We should only set this in the payload in the create if it's been explicitly specified in the config.

2023-01-05 14:45 UTC, stephybun commented on internal/services/containers/kubernetes_cluster_resource.go
> +		existing.Model.Properties.NetworkProfile.KubeProxyConfig = expandKubernetesClusterKubeProxyConfig(d.Get("network_profile.0.kube_proxy").([]interface{}))
This needs to be wrapped in `d.HasChanges()` so that the default for existing clusters is respected.

2023-01-13 07:11 UTC, stephybun requested changes
@ms-henglu could you please resolve the merge conflict? This should be good to go then.

2023-01-13 08:28 UTC, ms-henglu commented
Hi @stephybun , Thanks! I've resolved the conflicts.

2023-01-15 08:33 UTC, stephybun commented
@NissesSenap, apologies for the late response and thank you for outlining your concerns and current scenario.

After looking through the PR again and making further changes I believe this should no longer be a breaking change. 

The API returns kube proxy information in the response only once it's been modified. With the current implementation the provider would only send a value for `kube_proxy` once it's been modified. This means the current kube proxy settings for the cluster (whether it's enabled or disabled) should be respected and Terraform shouldn't flag a diff.

I hope this resolves any confusion about this feature. If there are any issues please do let us know and thanks again for your input!

2023-01-15 08:34 UTC, stephybun approved these changes
Thanks @ms-henglu, LGTM 🦘

2023-01-15 08:34 UTC, merged

2023-01-16 19:47 UTC, EppO commented
> The API returns kube proxy information in the response only once it's been modified. With the current implementation the provider would only send a value for `kube_proxy` once it's been modified. This means the current kube proxy settings for the cluster (whether it's enabled or disabled) should be respected and Terraform shouldn't flag a diff.

How do you explicitly disable it then? It looks like to me that keeping the default kube-proxy config or disabling it altogether are both using the absence of the block, am I wrong?

2023-01-16 23:50 UTC, mkilchhofer commented
Yes, I was also thinking about this. Does the absence of the whole block results in a cluster with missing kube-proxy?

2023-01-17 16:21 UTC, EppO commented
Glad we helped you sort this one out. 
Can't we have a default block config passed to the API when user doesn't provide one instead of sending `"enabled": false`? 

EDIT: scratch that, I just read https://github.com/Azure/azure-rest-api-specs/issues/22208 and I get it's an API issue.

2023-01-18 14:26 UTC, mkilchhofer commented
So I think we should also reopen the enhancement request over here: https://github.com/hashicorp/terraform-provider-azurerm/issues/19300