new resource: `azurerm_spring_cloud_dev_tool_portal`
hashicorp/terraform-provider-azurerm pull request #19568
Opened 2022-12-06 02:54 UTC by ms-henglu

2022-12-06 06:52 UTC, yuwzho approved these changes

2022-12-07 07:12 UTC, katbyte requested changes

2022-12-07 07:12 UTC, katbyte commented on internal/services/springcloud/spring_cloud_dev_tool_portal_resource.go
> +		"feature": {
i don't think we need to put these into a block called features? could we bring these up to the top level

2022-12-07 07:12 UTC, katbyte commented on internal/services/springcloud/spring_cloud_dev_tool_portal_resource.go
> +					"application_accelerator": {
```suggestion
					"application_accelerator_enabled": {
```

2022-12-07 07:12 UTC, katbyte commented on internal/services/springcloud/spring_cloud_dev_tool_portal_resource.go
> +			if err != nil {
```suggestion
			if _, err = client.Get(ctx, id.ResourceGroup, id.SpringName, id.DevToolPortalName); err != nil {
```

2022-12-07 07:12 UTC, katbyte commented on internal/services/springcloud/spring_cloud_dev_tool_portal_resource.go
> +	return &appplatform.DevToolPortalSsoProperties{
```suggestion
	if len(input) == 0 {
		return nil
	}
	sso := input[0]
	
	return &appplatform.DevToolPortalSsoProperties{
```

2022-12-07 07:12 UTC, katbyte commented on internal/services/springcloud/spring_cloud_dev_tool_portal_resource.go
> +	return []SsoModel{
```suggestion
	if properties == nil {
		return []SsoModel{}
	}
	
	clientId := ""
	if properties.ClientID != nil {
		clientId = *properties.ClientID
	}
	
	clientSecret := ""
	if len(model.Sso) != 0 {
		clientSecret = model.Sso[0].ClientSecret
	}
	
	metadataUrl := ""
	if properties.MetadataURL != nil {
		metadataUrl = *properties.MetadataURL
	}
	
	scopes := make([]string, 0)
	if properties.Scopes != nil {
		scopes = *properties.Scopes
	}
	
	return []SsoModel{
```

2022-12-12 05:40 UTC, katbyte approved these changes
LGTM 🌵

2022-12-12 05:40 UTC, merged