`azurerm_log_analytics_cluster_customer_managed_key` - fix a bug in resource operation
hashicorp/terraform-provider-azurerm pull request #19609
Opened 2022-12-08 07:00 UTC by ziyeqf

fix #13166

cause: https://github.com/Azure/azure-rest-api-specs/issues/21799

-- draft to run tests --

2022-12-12 07:56 UTC, katbyte requested changes

2022-12-12 07:56 UTC, katbyte commented on internal/services/loganalytics/log_analytics_cluster_customer_managed_key_resource.go
> +		Update: resourceLogAnalyticsClusterCustomerManagedKeyCreateOrUpdate,
we should not be combining creating and update functions as it breaks lifecycle - please keep this seperate

2022-12-13 02:22 UTC, ziyeqf commented
test after refactor
---
```
TF_ACC=1 go test -v ./internal/services/loganalytics -run=TestAccLogAnalyticsClusterCustomerManagedKey -timeout=600m
=== RUN   TestAccLogAnalyticsClusterCustomerManagedKey_basic
=== PAUSE TestAccLogAnalyticsClusterCustomerManagedKey_basic
=== RUN   TestAccLogAnalyticsClusterCustomerManagedKey_update
=== PAUSE TestAccLogAnalyticsClusterCustomerManagedKey_update
=== CONT  TestAccLogAnalyticsClusterCustomerManagedKey_basic
=== CONT  TestAccLogAnalyticsClusterCustomerManagedKey_update
--- PASS: TestAccLogAnalyticsClusterCustomerManagedKey_basic (2163.43s)
--- PASS: TestAccLogAnalyticsClusterCustomerManagedKey_update (2901.14s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/loganalytics  2902.305s
```

2022-12-15 22:14 UTC, katbyte approved these changes
LGTM 🦺

2022-12-15 22:14 UTC, merged