Adding multiple data sources
hashicorp/terraform-provider-azurerm pull request #19628
Opened 2022-12-09 10:09 UTC by steweg

This patch adds the following data sources:
- azurerm_virtual_hub_route_table
- azurerm_marketplace_agreement

2022-12-13 09:59 UTC, steweg commented on internal/services/compute/marketplace_agreement_data_source_test.go
> +	offer := "waf"
Ok, I have adjusted it to be hardcoded inside the test

2022-12-14 10:36 UTC, tombuildsstuff requested changes
hey @steweg 

Thanks for pushing those changes, I've taken a look through and left a few more minor comments inline, if we can fix those up then these two should be good to merge 👍 

Thanks!

2022-12-14 12:30 UTC, steweg commented on internal/services/compute/marketplace_agreement_data_source.go
> +		}
Done

2022-12-14 12:31 UTC, steweg commented on internal/services/network/virtual_hub_route_table_data_source.go
> +				Type:     pluginsdk.TypeSet,
Done - but here I have followed the schema within the existing "resource". So I guess it should be fixed in the resource as well, which is beyond scope of this patch.

2022-12-14 12:31 UTC, steweg commented on internal/services/network/virtual_hub_route_table_data_source.go
> +							Type:     pluginsdk.TypeSet,
Done - the same comment about the resource as above

2022-12-14 12:31 UTC, steweg commented on internal/services/network/virtual_hub_route_table_data_source.go
> +		return fmt.Errorf("reading %s: %+v", id, err)
Done

2022-12-14 12:31 UTC, steweg commented on website/docs/d/virtual_hub_route_table.html.markdown
> +* `route` - A `route` block as defined below.
Done

2022-12-15 21:50 UTC, katbyte commented on internal/services/network/virtual_hub_route_table_data_source.go
> +				Type:     pluginsdk.TypeSet,
data sources are always lists regardless of if the resources is a set or not so all good here :)

2022-12-28 10:37 UTC, steweg commented
@tombuildsstuff As all the open items were resolved, is there anything else needed from my side, or is it ready to be merged? Thanks

2023-01-03 17:59 UTC, katbyte approved these changes
LGTM 🦀

2023-01-03 17:59 UTC, merged