Update `azurerm_kubernetes_cluster` to allow the linux_profile ssh key to be rotated
hashicorp/terraform-provider-azurerm pull request #19634
Opened 2022-12-09 18:32 UTC by implodingduck

Changing SSH key for aks nodes no longer requires a forceNew:
https://learn.microsoft.com/en-us/azure/aks/node-access#update-ssh-key-on-an-existing-aks-cluster-preview

so this pull request removes the force new flag and adds a testcase to change the ssh key

2022-12-12 09:20 UTC, stephybun requested changes
Thanks for this PR @implodingduck. Two minor comments, also the docs need to be updated. Once that's done this should be good to go 👍

2022-12-12 09:20 UTC, stephybun commented on internal/services/containers/kubernetes_cluster_other_resource_test.go
> +				check.That(data.ResourceName).Key("linux_profile.0.admin_username").Exists(),
We can omit these explicit checks for this test
```suggestion
```

2022-12-12 09:20 UTC, stephybun commented on internal/services/containers/kubernetes_cluster_other_resource_test.go
> +				check.That(data.ResourceName).Key("linux_profile.0.admin_username").Exists(),
Same here 
```suggestion
```

2022-12-12 17:02 UTC, implodingduck commented
Thanks @stephybun, I have made the changes that you requested.

2022-12-13 11:14 UTC, stephybun approved these changes
Thanks @implodingduck LGTM 🌮

2022-12-13 11:14 UTC, merged