`azurerm_kubernetes_cluster` - support for the `backend_pool_type` property
hashicorp/terraform-provider-azurerm pull request #19664
Opened 2022-12-13 08:55 UTC by ms-henglu

```
=== RUN   TestAccKubernetesCluster_backendPoolType
=== PAUSE TestAccKubernetesCluster_backendPoolType
=== CONT  TestAccKubernetesCluster_backendPoolType
--- PASS: TestAccKubernetesCluster_backendPoolType (1036.95s)
PASS
```

2022-12-14 09:59 UTC, stephybun requested changes
This is still a preview feature so we should add a note with a link to the docs
```
=== CONT  TestAccKubernetesCluster_backendPoolType
testcase.go:110: Step 1/4 error: Error running apply: exit status 1
Error: creating Managed Cluster (Subscription: "*******"
Resource Group Name: "acctestRG-aks-221214065953610567"
Resource Name: "acctestaks221214065953610567"): managedclusters.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="The feature 'IPBasedLoadBalancerPreview' is not registered for subscription *******. Please register the feature 'Microsoft.ContainerService/IPBasedLoadBalancerPreview' to use this feature."
with azurerm_kubernetes_cluster.test,
```

2022-12-15 01:47 UTC, ms-henglu commented
Thanks @stephybun ! I've added the note.

2022-12-15 06:34 UTC, stephybun requested changes
Preview feature is enabled on our subscription but tests are still failing:
```
steph $ az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/IPBasedLoadBalancerPreview')].{Name:name,State:properties.state}"
Name                                                   State
-----------------------------------------------------  ----------
Microsoft.ContainerService/IPBasedLoadBalancerPreview  Registered
```
![image](https://user-images.githubusercontent.com/25562180/207789587-bf188429-3b32-4a95-a195-2abcc81fcd41.png)

2023-01-09 01:43 UTC, ms-henglu commented
Close this PR since it's a preview feature.

2023-01-09 01:43 UTC, closed without merging