Tengzh/vanguard/sentinel/onboardstates
hashicorp/terraform-provider-azurerm pull request #19692
Opened 2022-12-15 08:36 UTC by ziyeqf

ready to review, depends on #19609 and #19608 to run tests

2023-01-12 23:22 UTC, katbyte requested changes

2023-01-12 23:22 UTC, katbyte commented on website/docs/r/sentinel_log_analystic_workspace_onboard.html.markdown
> +page_title: "Azure Resource Manager: azurerm_sentinel_log_analytics_workspace_onboard"
given the description below uses onboarding
```suggestion
page_title: "Azure Resource Manager: azurerm_sentinel_log_analytics_workspace_onboarding"
```

as "onboard" doesn't seem like the right name?

2023-01-12 23:22 UTC, katbyte commented on website/docs/r/sentinel_log_analystic_workspace_onboard.html.markdown
> +resource "azurerm_security_insights_sentinel_onboarding_state" "example" {
and its onboarding here, thou with state?
```suggestion
resource "azurerm_security_insights_sentinel_onboarding" "example" {
```

2023-01-13 07:43 UTC, stephybun commented on website/docs/r/sentinel_log_analystic_workspace_onboard.html.markdown
> +---
There's a typo in this filename `sentinel_log_analystic_workspace_onboard.html.markdown` -> `sentinel_log_analytics_workspace_onboarding.html.markdown`

2023-01-17 22:55 UTC, katbyte approved these changes
LGTM 🍄

2023-01-17 22:55 UTC, merged