`azurerm_site_recovery_protection_container_mapping` - add auto update extension settings
hashicorp/terraform-provider-azurerm pull request #19710
Opened 2022-12-16 09:22 UTC by ziyeqf

closes #19691 
closes #19407 

Test
---
```
TF_ACC=1 go test -v ./internal/services/recoveryservices -run=TestAccSiteRecoveryProtectionContainerMapping -timeout=60m            [ tengzh/issue/vault_auto_update][$!][🐹 v1.19.4][⏱ 22m11s][16:57:14]
=== RUN   TestAccSiteRecoveryProtectionContainerMapping_basic
=== PAUSE TestAccSiteRecoveryProtectionContainerMapping_basic
=== RUN   TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension
=== PAUSE TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension
=== CONT  TestAccSiteRecoveryProtectionContainerMapping_basic
=== CONT  TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension
--- PASS: TestAccSiteRecoveryProtectionContainerMapping_basic (884.46s)
--- PASS: TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension (1268.62s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices      1269.810s
```

2022-12-16 23:00 UTC, mbfrahry requested changes
Hey @ziyeqf, thanks for this PR. It's mostly good but I think that we could lump these two attributes into a TypeList instead.

2022-12-16 23:00 UTC, mbfrahry commented on internal/services/recoveryservices/site_recovery_protection_container_mapping_resource.go
> +				RequiredWith: []string{"automatic_update_extensions_enabled"},
I believe something weird will happen here if they pass in an `automation_account_id` and have `automatic_update_extensions_enabled` set to false. We should just have this wrapped in a TypeList to show that these two attributes go together.

2022-12-19 04:51 UTC, ziyeqf commented
Test after modification
---
```
TF_ACC=1 go test -v ./internal/services/recoveryservices -run=TestAccSiteRecoveryProtectionContainerMapping -timeout=60m
=== RUN   TestAccSiteRecoveryProtectionContainerMapping_basic
=== PAUSE TestAccSiteRecoveryProtectionContainerMapping_basic
=== RUN   TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension
=== PAUSE TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension
=== CONT  TestAccSiteRecoveryProtectionContainerMapping_basic
=== CONT  TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension
--- PASS: TestAccSiteRecoveryProtectionContainerMapping_basic (886.50s)
--- PASS: TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension (1229.09s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices      1230.260s
```

2023-01-03 23:07 UTC, katbyte requested changes
One comment left inline

2023-01-03 23:07 UTC, katbyte commented on internal/services/recoveryservices/site_recovery_protection_container_mapping_resource.go
> +			"automatic_update_extension_settings": {
i think settings is redundant?
```suggestion
			"automatic_update_extension": {
```

2023-01-09 21:07 UTC, mbfrahry reviewed
Hey @ziyeqf, thanks for making those changes. I was looking more into this and it looks like we are changing the `ProviderSpecificInput` type from the basic type `ReplicationProviderSpecificContainerMappingInput` to `A2A`. I also see that there is another type called `VMwareCbt`.

I don't like that we're favoring one type over the other in this resource and we are making that decision for the user based off their input whilst also not letting them use the other type if they want. 

Do you know if this resource does anything? It doesn't appear so since most of the functionality comes from what you're adding here. If this resource isn't doing anything, it's probably worth creating a new resource and deprecating this one. That new resource will be `azurerm_site_recovery_protection_container_mapping_a2a`. That will also give us the flexibility to add the other type `azurerm_site_recovery_protection_container_mapping_vmware_cbt` if there are asks for it.

2023-01-10 02:24 UTC, ziyeqf commented
Hi @mbfrahry , For the current resources `azurerm_site_recovery_xxx`, they are all for `A2A`(Azure To Azure) type. 

For Site Recovery, there are basically four type `A2A`,`V2A(Vmware To Azure) Classic`,`V2A Modern` and `H2A`(HyperV To Azure).  I have worked to add the rest three types and I think the current resources are all for A2A so it should be ok to specify a input type. For the others I'm going to name them as `azure_site_recovery_xxx_v2a_classic` and so on.. 

How do you like that?

2023-01-10 20:03 UTC, mbfrahry requested changes
That is fair. So with that being the case, we can nearly revert it back to the way you had it with those attributes being at the top level. But we should also force the type to be `InstanceTypeBasicReplicationProviderSpecificContainerMappingInputInstanceTypeA2A` as in the original PR submitted, the type was being changed back to `ReplicationProviderSpecificContainerMappingInput` if these new attributes weren't set. 

Apologies for the run around on this!

2023-01-11 03:52 UTC, ziyeqf commented
temporarily close this PR to reduce noise in refactoring.

2023-01-11 05:40 UTC, ziyeqf commented
test

2023-01-12 23:20 UTC, katbyte commented
@ziyeqf - is there any progress on getting this merged so we don't need the hack? https://github.com/Azure/azure-rest-api-specs/pull/21652

2023-01-17 09:09 UTC, ziyeqf commented
> @ziyeqf - is there any progress on getting this merged so we don't need the hack? [Azure/azure-rest-api-specs#21652](https://github.com/Azure/azure-rest-api-specs/pull/21652)

oh, it's a mistake because Tom has explained it's not a Pandora issue. While the codes on `main` branch has been changed. I'm wondering if we can specify the property type to `A2A` in the create function then we will not need the workaround.

2023-01-17 09:15 UTC, ziyeqf commented
new test result
---
```
TF_ACC=1 go test -v ./internal/services/recoveryservices -run=TestAccSiteRecoveryProtectionContainerMapping -timeout=60m
=== RUN   TestAccSiteRecoveryProtectionContainerMapping_basic
=== PAUSE TestAccSiteRecoveryProtectionContainerMapping_basic
=== RUN   TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension
=== PAUSE TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension
=== CONT  TestAccSiteRecoveryProtectionContainerMapping_basic
=== CONT  TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension
--- PASS: TestAccSiteRecoveryProtectionContainerMapping_basic (841.12s)
--- PASS: TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension (1290.34s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices      1291.507s
```

2023-01-20 04:44 UTC, katbyte requested changes

2023-01-20 04:44 UTC, katbyte commented on internal/services/recoveryservices/site_recovery_protection_container_mapping_resource.go
> +			"automatic_update_extension": {
extension is redundant?
```suggestion
			"automatic_update": {
```

2023-01-20 05:26 UTC, ziyeqf commented
test result after rename
---
```
terraform-provider-azurerm ❯ TF_ACC=1 go test -v ./internal/services/recoveryservices -run=TestAccSiteRecoveryProtectionContainerMapping -timeout=60m
=== RUN   TestAccSiteRecoveryProtectionContainerMapping_basic
=== PAUSE TestAccSiteRecoveryProtectionContainerMapping_basic
=== RUN   TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension
=== PAUSE TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension
=== CONT  TestAccSiteRecoveryProtectionContainerMapping_basic
=== CONT  TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension
--- PASS: TestAccSiteRecoveryProtectionContainerMapping_basic (848.41s)
--- PASS: TestAccSiteRecoveryProtectionContainerMapping_withAutoUpdateExtension (1179.99s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices      1183.464s
```

2023-01-30 19:56 UTC, katbyte approved these changes
Thanks @ziyeqf - LGTM 🛠️

2023-01-30 19:57 UTC, merged