`azurerm_spring_cloud_gateway` - `apm_types`, `environment_variables` `sensitive_environment_variables`
hashicorp/terraform-provider-azurerm pull request #19884
Opened 2023-01-06 06:28 UTC by ms-henglu

2023-01-10 00:37 UTC, katbyte requested changes

2023-01-10 00:37 UTC, katbyte commented on internal/services/springcloud/spring_cloud_gateway_resource.go
> +			"apm_types": {
apm? could we expand this acronym?

2023-01-12 02:26 UTC, ms-henglu commented
Hi @katbyte , Thanks for code review, I've updated it as suggested, please take another look.

2023-01-12 23:14 UTC, katbyte approved these changes
Thanks @ms-henglu - LGTM 🦀

2023-01-12 23:14 UTC, merged