New Resource: azurerm_monitor_activitylog_alert
hashicorp/terraform-provider-azurerm pull request #1989
Opened 2018-09-27 20:47 UTC by JunyiYi

#### Description

In this pull request, I added a new Azure monitoring resource called activity log alerts. It will monitor the operations (such as update, delete, started, etc.) of a specific resource or all resources under one or more scope (like subscription, resource group, etc.). It is also one of the [unified alerts](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-overview-unified-alerts) in Azure monitor.

#### Related Issues

#1252 

#### References

Resource Description: https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-activity-log-alerts
REST API Reference: https://docs.microsoft.com/en-us/rest/api/monitor/activitylogalerts/createorupdate

2018-10-05 12:22 UTC, tombuildsstuff requested changes
hey @JunyiYi 

Thanks for this PR - apologies for the delayed review here! I've taken a look through and left some comments inline (mostly around the usage List vs Set) but this is off to a good start - if we can fix up the comments we should be able to take another look and kick off the tests 👍

Thanks!

2018-10-05 18:32 UTC, JunyiYi commented on azurerm/provider.go
> +			"azurerm_monitor_activitylog_alert":               resourceArmMonitorActivityLogAlert(),
Make sense.

2018-10-05 18:34 UTC, JunyiYi commented on azurerm/resource_arm_monitor_activitylog_alert.go
> +			"criteria": {
In portal it is called `criteria`, I'm just trying to match the names appear in portal which I think is more human readable.

2018-10-05 18:39 UTC, JunyiYi commented on azurerm/resource_arm_monitor_activitylog_alert.go
> +								"Service Health",
This part there is no 1:1 mapping to the API. The API used to define criteria is very unusable (it a list of raw field string to value string with no special type and no validation rule). So I redesigned the interface here according to the [documentation](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-activity-log-alerts) to make it more usable from the user's perspective.

2018-10-05 18:42 UTC, JunyiYi commented on azurerm/resource_arm_monitor_activitylog_alert.go
> +							DiffSuppressFunc: ignoreCaseDiffSuppressFunc,
Is this for all enum fields? Are there any exceptions?

2018-10-05 18:42 UTC, JunyiYi commented on azurerm/resource_arm_monitor_activitylog_alert.go
> +								"Informational",
Explained in the `category` part.

2018-10-05 18:44 UTC, JunyiYi commented on azurerm/resource_arm_monitor_activitylog_alert.go
> +				Type:     schema.TypeList,
Make sense.

2018-10-05 18:44 UTC, JunyiYi commented on azurerm/resource_arm_monitor_activitylog_alert.go
> +				Type:     schema.TypeList,
Make sense.

2018-10-05 18:46 UTC, JunyiYi commented on azurerm/resource_arm_monitor_activitylog_alert.go
> +	criteriaRaw := d.Get("criteria.0").(map[string]interface{})
Does not supported mean in future versions the behavior might be changed? (since the code works fine now)

2018-10-05 18:54 UTC, JunyiYi commented on azurerm/resource_arm_monitor_activitylog_alert.go
> +			})
Do you mean the code below?
```
op := v["operation_name"]
if op != "" {
    conditions = append(conditions, ... { Field: "operationName", Equals: op }
}
caller := v["caller"]
if caller != "" {
    conditions = append(conditions, ... { Field: "caller", Equals: caller }
}
...
```

2018-10-05 18:58 UTC, JunyiYi commented on website/docs/r/monitor_activitylog_alert.html.markdown
> +## Example Usage (Monitor one specific storage account updates)
You are right. But I'm also want to demonstrate the user how to monitor everything under a subscription using `scopes              = ["/subscriptions/${data.azurerm_client_config.current.subscription_id}"]`. Do you prefer to let the users figuring it out by themselves or somewhere else in this documentation.

2018-10-05 19:02 UTC, JunyiYi commented on website/docs/r/monitor_activitylog_alert.html.markdown
> +* `scopes` - (Required) The individual resource or set of resources for which the alert on activity log is defined. For example, a subscription ID, or a resource group ID.
Further question, do we also need to rename this field to `resource_ids`?

2018-10-05 19:04 UTC, JunyiYi commented on website/docs/r/monitor_activitylog_alert.html.markdown
> +* `action_group_id` - (Required) The resource ID of an action group (`azurerm_monitor_action_group`).
Question for best practice, what URL should I put here? The absolute URL to `action_group` page or some relative path?

2018-10-05 19:07 UTC, JunyiYi commented
Thanks @tombuildsstuff for the review. I would be appreciated if you could answer the questions I replied in the comment. And I will change the code accordingly. I believe the comments here also applies to another similar resource called [metric alert](https://github.com/terraform-providers/terraform-provider-azurerm/pull/2026) as well, right?

2018-10-11 02:05 UTC, JunyiYi commented on azurerm/resource_arm_monitor_activitylog_alert.go
> +				}
I'm already looping through the result and mapping each item to the attribute.

2018-10-11 02:12 UTC, JunyiYi commented on azurerm/resource_arm_monitor_activitylog_alert.go
> +		Location: utils.String(azureRMNormalizeLocation("Global")),
Not exactly due to an error from API: `Status=400 Code="LocationRequired" Message="The location property is required for this definition."`

2018-10-15 20:08 UTC, katbyte approved these changes
Hi @JunyiYi,

LGTM 👍  running tests now

2018-10-15 20:09 UTC, katbyte commented
Tests pass:
<img width="522" alt="screen shot 2018-10-15 at 13 06 16" src="https://user-images.githubusercontent.com/1638467/46975455-7c506b00-d07b-11e8-895a-63c4ade503ce.png">

2018-10-15 20:09 UTC, merged