Docs: fix missed properties in document of `automation`, `network`, `fluidrelay server`, etc.
hashicorp/terraform-provider-azurerm pull request #19913
Opened 2023-01-09 09:46 UTC by wuxu92

fix document typos or missed properties of some RPs.

2023-01-09 12:21 UTC, stephybun requested changes
Thanks for this @wuxu92, left some suggestions in line but once those are fixes this should be good to go.

2023-01-09 12:21 UTC, stephybun commented on website/docs/r/automation_module.html.markdown
> +* `module_link` - (Required) The published Module link `module_link` block defined as blow.
```suggestion
* `module_link` - (Required) A `module_link` block as defined below.
```

2023-01-09 12:21 UTC, stephybun commented on website/docs/r/automation_module.html.markdown
> +* `hash` - (Optional) A `hash` block defined as below.
```suggestion
* `hash` - (Optional) A `hash` block as defined below.
```

2023-01-10 05:20 UTC, katbyte approved these changes
LGTM ⚒️

2023-01-10 05:21 UTC, merged