azurerm_site_recovery_replicated_vm - support for the   `unmanaged_disk`,`target_proximity_placement_group_id`, `target_boot_diag_storage_account_id`, `target_capacity_reservation_group_id`, `target_virtual_machine_scale_set_id`,`multi_vm_group_name`,`target_edge_zone` properties
hashicorp/terraform-provider-azurerm pull request #19939
Opened 2023-01-10 08:36 UTC by ziyeqf

---draft to run acctest---

fix #19898

2023-01-11 06:44 UTC, ziyeqf commented
convert to draft to run tests after adding tfo settings

2023-01-11 08:44 UTC, ziyeqf commented
close and will reopen when the test running done

2023-01-11 20:09 UTC, dsiperek-vendavo commented
Anyway this could get released in this Friday's release?

2023-01-12 05:27 UTC, ziyeqf commented
@dsiperek-vendavo Sorry but it could not, there are still some work need to do before make this PR active

2023-01-12 16:34 UTC, dsiperek-vendavo commented
When do you expect it to be released? This is an active ticket i also opened up with Azure Support.

2023-01-12 16:56 UTC, richshadman commented
@ziyeqf this is fantastic forward motion. I do not think the test failover settings in network will be viable unless we add a root property for **test_network_id** (equivalent to **target_network_id**). Are you able to add that change as well?

2023-01-13 02:27 UTC, ziyeqf commented
@richshadman Sure, working on that.

2023-01-13 09:20 UTC, ziyeqf commented
@dsiperek-vendavo sorry but I can not give a clear expect right now, as you can see it's a XL PR and there are some prepare work not ready..

2023-01-24 02:36 UTC, katbyte requested changes

2023-01-24 02:36 UTC, katbyte commented on website/docs/r/site_recovery_replicated_vm.html.markdown
> +* `target_boot_diag_storage_account_id` - (Optional) Id of the storage account which the new VM should used for boot diagnostic when a failover is done.
we should avoid shortening words
```suggestion
* `target_boot_diagnostic_storage_account_id` - (Optional) Id of the storage account which the new VM should used for boot diagnostic when a failover is done.
```

2023-01-24 02:36 UTC, katbyte commented on website/docs/r/site_recovery_replicated_vm.html.markdown
> +* `test_public_ip_address_id` - (Optional) Id of the public IP object to use when a test failover is done.
should these be clear this is for failove tests?
```suggestion
* `failover_test_static_ip` - (Optional) Static IP to assign when a test failover is done.

* `failover_test_subnet_name` - (Optional) Name of the subnet to to use when a test failover is done.

* `failover_test_public_ip_address_id` - (Optional) Id of the public IP object to use when a test failover is done.
```

2023-01-30 20:15 UTC, katbyte approved these changes
LGTM ☔

2023-01-30 20:15 UTC, merged