New Data Source: `azurerm_private_dns_resolver_inbound_endpoint`
hashicorp/terraform-provider-azurerm pull request #19948
Opened 2023-01-10 16:18 UTC by pchanvallon

``` txt
=== RUN   TestAccDNSResolverInboundEndpointDataSource_basic
=== PAUSE TestAccDNSResolverInboundEndpointDataSource_basic
=== CONT  TestAccDNSResolverInboundEndpointDataSource_basic
--- PASS: TestAccDNSResolverInboundEndpointDataSource_basic (434.96s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/privatednsresolver    436.195s

=== RUN   TestAccDNSResolverInboundEndpointDataSource_complete
=== PAUSE TestAccDNSResolverInboundEndpointDataSource_complete
=== CONT  TestAccDNSResolverInboundEndpointDataSource_complete
--- PASS: TestAccDNSResolverInboundEndpointDataSource_complete (604.47s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/privatednsresolver    605.711s
```

2023-01-11 21:11 UTC, pchanvallon commented
Following PR #19947 review, I have implemented the same suggestions. 

Here is the updated test result :
``` txt
=== RUN   TestAccDNSResolverInboundEndpointDataSource_basic
=== PAUSE TestAccDNSResolverInboundEndpointDataSource_basic
=== CONT  TestAccDNSResolverInboundEndpointDataSource_basic
--- PASS: TestAccDNSResolverInboundEndpointDataSource_basic (435.39s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/privatednsresolver    436.573s
```

2023-01-12 00:21 UTC, mbfrahry requested changes
This looks good as well with just similar comments as the other PRs.

2023-01-12 00:21 UTC, mbfrahry commented on website/docs/d/private_dns_resolver_inbound_endpoint.html.markdown
> +* `read` - (Defaults to 5 minutes) Used when retrieving the Private DNS SRV Record.
```suggestion
* `read` - (Defaults to 5 minutes) Used when retrieving the Private DNS Resolver Inbound Endpoint.
```

2023-01-12 00:21 UTC, mbfrahry commented on internal/services/privatednsresolver/private_dns_resolver_inbound_endpoint_data_source_test.go
> +`, data.Locations.Primary, data.RandomInteger)
Same comment as before

2023-01-12 08:14 UTC, pchanvallon commented on website/docs/d/private_dns_resolver_inbound_endpoint.html.markdown
> +* `read` - (Defaults to 5 minutes) Used when retrieving the Private DNS SRV Record.
done

2023-01-12 08:14 UTC, pchanvallon commented on internal/services/privatednsresolver/private_dns_resolver_inbound_endpoint_data_source_test.go
> +`, data.Locations.Primary, data.RandomInteger)
done

2023-01-12 08:14 UTC, pchanvallon commented
Thanks again for you review, I've updated the documentation and tests following your comments.

2023-01-12 22:40 UTC, merged