`azurerm_data_factory_integration_runtime_self_hosted` - fix failed test case
hashicorp/terraform-provider-azurerm pull request #20023
Opened 2023-01-16 03:22 UTC by ms-henglu

2023-01-16 10:50 UTC, jackofallops requested changes
HI @ms-henglu 
I'm concerned that the fix here is just masking an underlying problem, can we check what's not being deleted and see if there's a resource that possibly has a delete issue?

Thanks!

2023-01-16 10:50 UTC, jackofallops commented on internal/services/datafactory/data_factory_integration_runtime_self_hosted_resource_test.go
> +      prevent_deletion_if_contains_resources = false
Needing this suggests that a resource is not being correctly deleted. Can we look into what's not being removed and see if there's a delete bug?

2023-01-18 07:21 UTC, ms-henglu commented
Hi @jackofallops ,

Thanks for the code review, I've updated the test case, would you please take another look, thanks!

<img width="978" alt="image" src="https://user-images.githubusercontent.com/79895375/213108596-731f0778-0f4a-4a25-9b8e-e537eec3d292.png">

2023-01-20 04:12 UTC, katbyte approved these changes
LGTM 🗄️

2023-01-20 04:12 UTC, merged