`azurerm_key_vault` - use `virtual_network_rules` as block and add support for `ignore_missing_vnet_service_endpoint` property
hashicorp/terraform-provider-azurerm pull request #20032
Opened 2023-01-16 09:16 UTC by wuxu92

**Looks like there is a problem in updating `ignore_missing_vnet_service_endpoint` property. it takes no effect on the exists keyvault resource**, so convert this PR to draft status. created an issue to track this: https://github.com/Azure/azure-rest-api-specs/issues/22128

`ignore_missing_vnet_service_endpoint` need support from version `2021-10-01`, and mark `virtual_network_subnet_ids` as deprecated.

https://github.com/Azure/azure-rest-api-specs/blob/63a4b37b66740087b113e00c1b32b2b9c98fd9db/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2021-10-01/keyvault.json#L1798-L1800

```
--- PASS: TestAccDataSourceKeyVault_networkAcls (543.73s)
```

2023-01-17 09:53 UTC, jackofallops requested changes
Hi @wuxu92 - Thanks for this PR.
I've left some comments below, if you can take a look?

Thanks

2023-01-17 09:53 UTC, jackofallops commented on website/docs/r/key_vault.html.markdown
> +* `ignore_missing_vnet_service_endpoint_enabled` - (Optional) Whether NRP will ignore the check if parent subnet has serviceEndpoints configured.
Can we make this clearer for users, the description straight from the Swagger isn't very helpful for new users?

2023-01-18 02:38 UTC, wuxu92 commented on internal/services/keyvault/key_vault_resource.go
> +						"virtual_network_rules": {
Should it rename `virtual_network_rules` to `virtual_network_subnet_id`?

I have tested several times locally and the order is stable. it doesn't need a `TypeSet` here.

2023-02-27 21:05 UTC, katbyte commented
@wuxu92 - is this ready for a review or still a draft?

2023-04-23 02:30 UTC, closed without merging

2023-04-23 02:31 UTC, wuxu92 commented
close this for swagger issue.