Add support for create_option = ImportSecure for managed_disk
hashicorp/terraform-provider-azurerm pull request #20030
Opened 2023-01-16 08:37 UTC by balazs92117

"Security Type 'ConfidentialVM_DiskEncryptedWithCustomerKey' is not supported for CreateOption 'Import'. Supported create options are FromImage, ImportSecure, UploadPreparedSecure."

2023-01-17 10:23 UTC, jackofallops requested changes
Hi @balazs92117
Thanks for this PR. I've left some comments in-line below.  Could you also look at adding tests for the new value to verify/ensure this works as expected?

Thanks!

2023-01-17 10:23 UTC, jackofallops commented on internal/services/compute/managed_disk_resource.go
> +			return fmt.Errorf("trusted_launch_enabled cannot be set to true with create_option %q. Supported Create Options when Trusted Launch is enabled are FromImage, Import, ImportSecure", createOption)
```suggestion
			return fmt.Errorf("trusted_launch_enabled cannot be set to true with create_option %q. Supported Create Options when Trusted Launch is enabled are `FromImage`, `Import`, `ImportSecure`", createOption)
```

2023-01-17 10:23 UTC, jackofallops commented on website/docs/r/managed_disk.html.markdown
> +* `os_type` - (Optional) Specify a value when the source of an `Import`, `ImportSecure` or `Copy` operation targets a source that contains an operating system. Valid values are `Linux` or `Windows`.
Do we need a note here to let users know `ImportSecure` is valid for ConfidentialVM only?

2023-01-17 10:23 UTC, jackofallops commented on website/docs/r/managed_disk.html.markdown
>  -> **Note:** Trusted Launch can only be enabled when `create_option` is `FromImage` or `Import`.
This note needs updating for `ImportSecure` also?

2023-01-20 04:07 UTC, katbyte approved these changes
LGTM ☔

2023-01-20 04:08 UTC, merged