Implements Disable Local Auth for Log Analytics Workspaces
hashicorp/terraform-provider-azurerm pull request #20092
Opened 2023-01-18 19:56 UTC by gusfcarvalho

Fixes #20091
Signed-off-by: Gustavo <gusfcarvalho@gmail.com>

2023-01-18 19:57 UTC, gusfcarvalho commented
First time contributing to this repo - please let me know if I'm missing something 🙈

2023-01-18 20:48 UTC, gusfcarvalho commented
```
make acctests SERVICE='loganalytics' TESTARGS='-run=TestAccLogAnalyticsWorkspace_ToggleDisableLocalAuth' TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/loganalytics -run=TestAccLogAnalyticsWorkspace_ToggleDisableLocalAuth -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccLogAnalyticsWorkspace_ToggleDisableLocalAuth
=== PAUSE TestAccLogAnalyticsWorkspace_ToggleDisableLocalAuth
=== CONT  TestAccLogAnalyticsWorkspace_ToggleDisableLocalAuth
--- PASS: TestAccLogAnalyticsWorkspace_ToggleDisableLocalAuth (462.77s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/loganalytics
```

2023-01-19 20:36 UTC, katbyte requested changes
thanks @gusfcarvalho ! overall this looks good with my only comment being around the property name. once that is fixed up i think this will be good to merge 🙂

2023-01-19 20:36 UTC, katbyte commented on website/docs/r/log_analytics_workspace.html.markdown
> +* `disable_local_auth` - (Optional) Specifices if the log Analytics workspace should enforce authentication using Azure AD. Defaults to `false`.
as this is a boolean, it should be consistent with other booleans in the provider (enabled/disabled on the end of the name)
```suggestion
* `local_authentication_disabled` - (Optional) Specifices if the log Analytics workspace should enforce authentication using Azure AD. Defaults to `false`.
```

2023-01-19 21:42 UTC, gusfcarvalho commented
Thanks for the review! I’m going for holidays today, I’ll pick this up on Tuesday.

2023-01-24 08:56 UTC, gusfcarvalho commented
Updated the PR with the requested name change!

2023-01-25 09:32 UTC, gusfcarvalho commented
hi @katbyte ! Can you take a look at it now? Sorry to bother 🙈

2023-01-26 16:56 UTC, katbyte approved these changes
Thanks @gusfcarvalho - LGTM 🦀

2023-01-26 16:56 UTC, merged