`azurerm_dashboard_grafana` - Support `grafana_integrations`
hashicorp/terraform-provider-azurerm pull request #20102
Opened 2023-01-19 08:29 UTC by ms-zhenhua

2023-01-30 19:44 UTC, katbyte requested changes

2023-01-31 01:23 UTC, ms-zhenhua commented on internal/services/dashboard/dashboard_grafana_resource.go
> +		},
Hi @katbyte, thank you for your review.
To simplify the property names, I suggest renaming `azure_monitor_workspace_integrations` to `azure_monitor_workspace` and `azure_monitor_workspace_resource_id` to `resource_id`.
However, I suggest keeping the middle block of `azure_monitor_workspace`. The reason is **Azure Service Team** may add new properties under `azure_monitor_workspace` in future swagger.  If we keep `azure_monitor_workspace`, we only need to add new properties under `azure_monitor_workspace`, or we have to define a new `grafana_integrations` with a new `list` definition to replace the existing one, which is more complicated. WDYT?

2023-01-31 01:47 UTC, katbyte commented on internal/services/dashboard/dashboard_grafana_resource.go
> +		},
that works

2023-01-31 05:51 UTC, ms-zhenhua commented
Hi @katbyte, I have resolved the comments. Kindly help review it again. Thanks.

2023-02-06 21:18 UTC, katbyte approved these changes
LGTM 🍄

2023-02-06 21:18 UTC, merged