`azurerm_monitor_diagnostic_setting` - set `log_analytics_destination_type`  inferred value to `AzureDiagnostics `
hashicorp/terraform-provider-azurerm pull request #20203
Opened 2023-01-28 02:52 UTC by teowa

resolves #20140

For some resources (e.g. `azurerm_data_factory`) the `log_analytics_destination_type` property will default to `AzureDiagnostics` value, but for other resources (e.g. `azurerm_key_vault`) the default is empty (null).  And the issue is caused by service API behavior changes (days ago the API also returns `AzureDiagnostics` for resource like Key Vault).

From [this doc](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/azurediagnostics#resource-types), the null value should be inferred as `AzureDiagnostics`, so this PR sets the empty value to  `AzureDiagnostics` when read.

2023-01-31 16:14 UTC, Klaas- commented
@teowa the doc you linked, https://github.com/MicrosoftDocs/azure-docs/blob/e294e228cf8249e82172695143e0a21084636b67/articles/azure-monitor/essentials/resource-logs.md#select-the-collection-mode , it says that we should use Dedicated because AzureDiagnostics will be removed in future, right? So we should maybe put a deprecaion on that and change default in 4.0 or something like that?

2023-02-02 07:21 UTC, teowa commented
As I tested, for some target resources (e.g., KeyVault) this property is not settable, and for other resources (e.g., DataFactory) it still works well, see details in https://github.com/Azure/azure-rest-api-specs/issues/22400. I am still contacting with service team about the details of the affected resource types. Temporarily close this and once a solution is determined I am going to reopen this PR.

2023-02-09 08:37 UTC, teowa commented
The two cases of  `log_analytics_destination_type` property:
1. for resources (Keyvault), the property is no longer applicable, either set `AzureDiagnostics` or `Dedicated`, returns  null 
2. for others (DataFactory), defaults to `AzureDiagnostics` but can also be changed to `Dedicated`.

We are asking service team to change case1 to return an error. And I think it's better to change this property to `Computed` for now, from the [doc](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/azurediagnostics#azure-diagnostics-mode), case1 is more common and set this as computed can remove the diff noise for users who dont set this property.

2023-02-17 01:59 UTC, katbyte requested changes

2023-02-17 01:59 UTC, katbyte commented on internal/services/monitor/monitor_diagnostic_setting_resource.go
> -				Default:  "AzureDiagnostics",
the documentation will need to be updated?

2023-02-24 03:07 UTC, katbyte approved these changes
LGTM 📓

2023-02-24 03:07 UTC, merged