`azurerm_app_configuration_key` - fix test 403 error
hashicorp/terraform-provider-azurerm pull request #20324
Opened 2023-02-06 02:18 UTC by teowa

need to test

2023-02-06 20:48 UTC, katbyte requested changes
Hi @teowa 

as a rule we should never be sleeping in the provider, this is just a sleep with extra steps and a sign there is something wrong with the resource in question, users should not be waiting after create to use a resource/having to use the time provider like this.

can you please update the create function to poll for the resource to be done propagated?

2023-02-20 16:18 UTC, stephybun commented
@teowa any update on this?

2023-02-24 03:14 UTC, katbyte approved these changes
Aside from 2 comments LGTM ⛰️

2023-02-24 03:14 UTC, katbyte commented on internal/services/appconfiguration/app_configuration_key_resource.go
> +				return fmt.Errorf("waiting for App Configuration Key %q read permission to be done propagated: %+v", model.Key, err)
```suggestion
				return fmt.Errorf("waiting for App Configuration Key %q read permission to be propagated: %+v", model.Key, err)
```

2023-02-24 03:14 UTC, katbyte commented on internal/services/appconfiguration/app_configuration_feature_resource.go
> +				return fmt.Errorf("waiting for App Configuration Key %q read permission to be done propagated: %+v", featureKey, err)
```suggestion
				return fmt.Errorf("waiting for App Configuration Key %q read permission to be propagated: %+v", featureKey, err)
```

2023-02-24 03:26 UTC, merged