`azurerm_windows_web_app`,`azurerm_windows_web_app_slot`, `azurerm_windows_function_app`, `azurerm_windows_function_app_slot`, `azurerm_linux_web_app`,`azurerm_linux_web_app_slot`, `azurerm_linux_function_app`, `azurerm_linux_function_app_slot` - add `hosting_environment_id` property
hashicorp/terraform-provider-azurerm pull request #20471
Opened 2023-02-15 07:06 UTC by xiaxyi

2023-03-24 09:43 UTC, jackofallops requested changes
Hi @xiaxyi - Thanks for this PR.  I've left a few comments inline below if you can take a look and address I think this will be good to merge.

Thanks!

2023-03-24 09:43 UTC, jackofallops commented on internal/services/appservice/windows_function_app_resource.go
> +				state.HostingEnvId = utils.NormalizeNilableString(hostingEnv.ID)
Can we change this to use the `pointer` package as it's already imported? We'll be refactoring all references of this soon, but we shouldn't continue use of  the `utils` package in new changes.

2023-03-24 09:43 UTC, jackofallops commented on internal/services/appservice/windows_web_app_data_source.go
> +					webApp.HostingEnvId = utils.NormalizeNilableString(hostingEnv.ID)
As above, can we change to `pointer` package here?

2023-03-24 09:43 UTC, jackofallops commented on website/docs/d/linux_function_app.html.markdown
> +* `hosting_environment_id` - The hosting environment id used by Function App.
The resource name in the provider is `app_servce_environment` we should make this clearer in the documentation references? Perhaps:
 ```suggestion
* `hosting_environment_id` - The ID of the App Service Environment used by this Linux Function App.
```
Can you also do similar for the other property references below?

2023-04-06 08:15 UTC, xiaxyi commented
Thanks @jackofallops , code is updated.

2023-04-20 05:33 UTC, jackofallops approved these changes
Thanks for those changes @xiaxyi - this LGTM now 👍

2023-04-20 05:36 UTC, merged