`azurerm_media_streaming_policy` - support for more feature
hashicorp/terraform-provider-azurerm pull request #20524
Opened 2023-02-17 09:45 UTC by teowa

Support for:
- `common_encryption_cbcs.clear_key_encryption_configuration`
- `common_encryption_cenc.clear_key_encryption_configuration`
- `common_encryption_cenc.clear_track`
- `common_encryption_cenc.content_key_to_track_mapping`
- `envelope_encryption`

Reference:
- [Streaming Policies](https://learn.microsoft.com/en-us/azure/media-services/latest/stream-streaming-policy-concept)
- [Swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/mediaservices/resource-manager/Microsoft.Media/Metadata/stable/2022-08-01/StreamingPoliciesAndStreamingLocators.json#L826)

Test:
```
make acctests SERVICE="media" TESTARGS="-parallel 20 -test.run=TestAccStreamingPolicy_" TESTTIMEOUT='1440m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/media -parallel 20 -test.run=TestAccStreamingPolicy_ -timeout 1440m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccStreamingPolicy_basic
=== PAUSE TestAccStreamingPolicy_basic
=== RUN   TestAccStreamingPolicy_clearKeyEncryption
=== PAUSE TestAccStreamingPolicy_clearKeyEncryption
=== RUN   TestAccStreamingPolicy_requiresImport
=== PAUSE TestAccStreamingPolicy_requiresImport
=== RUN   TestAccStreamingPolicy_complete
=== PAUSE TestAccStreamingPolicy_complete
=== RUN   TestAccStreamingPolicy_update
=== PAUSE TestAccStreamingPolicy_update
=== CONT  TestAccStreamingPolicy_basic
=== CONT  TestAccStreamingPolicy_complete
=== CONT  TestAccStreamingPolicy_requiresImport
=== CONT  TestAccStreamingPolicy_clearKeyEncryption
=== CONT  TestAccStreamingPolicy_update
--- PASS: TestAccStreamingPolicy_basic (133.83s)
--- PASS: TestAccStreamingPolicy_clearKeyEncryption (136.04s)
--- PASS: TestAccStreamingPolicy_requiresImport (137.51s)
--- PASS: TestAccStreamingPolicy_complete (198.46s)
--- PASS: TestAccStreamingPolicy_update (227.08s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/media 228.374s

```

2023-02-23 14:54 UTC, stephybun requested changes
Thanks for this @teowa, the docs needs a few adjustments as well as the schema. Otherwise this is looking good.

2023-02-23 14:54 UTC, stephybun commented on website/docs/r/media_streaming_policy.html.markdown
> +* `clear_key_encryption_configuration` - (Optional) A `clear_key_encryption_configuration` block defined as below. Changing this forces a new Streaming Policy to be created.
```suggestion
* `clear_key_encryption_configuration` - (Optional) A `clear_key_encryption_configuration` block as defined below. Changing this forces a new Streaming Policy to be created.
```

2023-02-23 14:54 UTC, stephybun commented on website/docs/r/media_streaming_policy.html.markdown
> +
```suggestion
* `clear_key_encryption_configuration` - (Optional) A `clear_key_encryption_configuration` block as defined below. Changing this forces a new Streaming Policy to be created.

* `clear_track` - (Optional) One or more `clear_track` blocks as defined below. Changing this forces a new Streaming Policy to be created.

* `content_key_to_track_mapping` - (Optional) One or more `content_key_to_track_mapping` blocks as defined below. Changing this forces a new Streaming Policy to be created.

```

2023-02-23 14:54 UTC, stephybun commented on website/docs/r/media_streaming_policy.html.markdown
> +* `custom_keys_acquisition_url_template` - (Required) Template for the URL of the custom service delivering content keys to end user players. Not required when using Azure Media Services for issuing
Looks like we're exposing implementation detail here, we should remove that.
```suggestion
* `custom_keys_acquisition_url_template` - (Required) The URL template for the custom service that delivers content keys to the end user. This is not required when using Azure Media Services for issuing licenses. Changing this forces a new Streaming Policy to be created.
```

2023-02-23 14:54 UTC, stephybun commented on website/docs/r/media_streaming_policy.html.markdown
> +* `condition` - (Required) One or more `condition` blocks defined as below. Changing this forces a new Streaming Policy to be created.
```suggestion
* `condition` - (Required) One or more `condition` blocks as defined below. Changing this forces a new Streaming Policy to be created. 
```

2023-02-23 14:54 UTC, stephybun commented on website/docs/r/media_streaming_policy.html.markdown
> +* `value` - (Required) Track property value. Changing this forces a new Streaming Policy to be created.
```suggestion
* `operation` - (Required) The track property condition operation. Possible value is `Equal`. Changing this forces a new Streaming Policy to be created.

* `property` - (Required) The track property type. Possible value is `FourCC`. Changing this forces a new Streaming Policy to be created.

* `value` - (Required) The track property value. Changing this forces a new Streaming Policy to be created.
```

2023-02-23 14:54 UTC, stephybun commented on website/docs/r/media_streaming_policy.html.markdown
> +* `label` - (Optional) Label can be used to specify Content Key when creating a Streaming Locator. Changing this forces a new Streaming Policy to be created.
```suggestion
* `label` - (Optional) Specifies the content key when creating a Streaming Locator. Changing this forces a new Streaming Policy to be created.
```

2023-02-23 14:54 UTC, stephybun commented on website/docs/r/media_streaming_policy.html.markdown
> +* `track` - (Optional) One or more `track` blocks defined as below. Changing this forces a new Streaming Policy to be created.
```suggestion
* `policy_name` - (Optional) The policy used by the default key. Changing this forces a new Streaming Policy to be created.

* `track` - (Optional) One or more `track` blocks as defined below. Changing this forces a new Streaming Policy to be created.
```

2023-02-23 14:54 UTC, stephybun commented on website/docs/r/media_streaming_policy.html.markdown
> +* `custom_key_acquisition_url_template` - (Optional) Template for the URL of the custom service delivering keys to end user players. Not required when using Azure Media Services for issuing keys. The
Same as above
```suggestion
* `custom_keys_acquisition_url_template` - (Required) The URL template for the custom service that delivers content keys to the end user. This is not required when using Azure Media Services for issuing licenses. Changing this forces a new Streaming Policy to be created.
```

2023-02-23 14:54 UTC, stephybun commented on website/docs/r/media_streaming_policy.html.markdown
> +* `condition` - (Required) One or more `condition` blocks defined as below. Changing this forces a new Streaming Policy to be created.
```suggestion
* `condition` - (Required) One or more `condition` blocks as defined below. Changing this forces a new Streaming Policy to be created. 
```

2023-02-23 14:54 UTC, stephybun commented on internal/services/media/media_streaming_policy_resource.go
> +						"clear_key_encryption_configuration": {
Configuration is implied, we should remove that from the name
```suggestion
						"clear_key_encryption": {
```

2023-02-23 14:54 UTC, stephybun commented on internal/services/media/media_streaming_policy_resource.go
> +						"clear_key_encryption_configuration": {
Same as below
```suggestion
						"clear_key_encryption": {
```

2023-02-24 03:08 UTC, teowa commented
Hi @stephybun , thanks for reviewing.
I have changed the code per review comment, please kindly have another look.

```
TF_ACC=1 go test -v ./internal/services/media -parallel 20 -test.run=TestAccStreamingPolicy_ -timeout 1440m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccStreamingPolicy_basic
=== PAUSE TestAccStreamingPolicy_basic
=== RUN   TestAccStreamingPolicy_clearKeyEncryption
=== PAUSE TestAccStreamingPolicy_clearKeyEncryption
=== RUN   TestAccStreamingPolicy_requiresImport
=== PAUSE TestAccStreamingPolicy_requiresImport
=== RUN   TestAccStreamingPolicy_complete
=== PAUSE TestAccStreamingPolicy_complete
=== RUN   TestAccStreamingPolicy_update
=== PAUSE TestAccStreamingPolicy_update
=== CONT  TestAccStreamingPolicy_basic
=== CONT  TestAccStreamingPolicy_complete
=== CONT  TestAccStreamingPolicy_requiresImport
=== CONT  TestAccStreamingPolicy_clearKeyEncryption
=== CONT  TestAccStreamingPolicy_update
--- PASS: TestAccStreamingPolicy_basic (131.54s)
--- PASS: TestAccStreamingPolicy_complete (131.57s)
--- PASS: TestAccStreamingPolicy_requiresImport (132.65s)
--- PASS: TestAccStreamingPolicy_clearKeyEncryption (193.25s)
--- PASS: TestAccStreamingPolicy_update (208.67s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/media 210.662s

```

2023-02-24 08:56 UTC, stephybun approved these changes
Thanks @teowa LGTM 🦢

2023-02-24 08:56 UTC, merged