`azurerm_mariadb_server`: Add support for `ssl_minimal_tls_version_en…
hashicorp/terraform-provider-azurerm pull request #20556
Opened 2023-02-19 16:05 UTC by favoretti

…forced`

```
$ TF_ACC=1 go test -v ./internal/services/mariadb -timeout=1000m -run='TestAccMariaDbServer_basicTenTwo'

=== RUN   TestAccMariaDbServer_basicTenTwo
=== PAUSE TestAccMariaDbServer_basicTenTwo
=== CONT  TestAccMariaDbServer_basicTenTwo
--- PASS: TestAccMariaDbServer_basicTenTwo (296.33s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/mariadb	297.574s
```

Fixes #7899

2023-02-19 18:54 UTC, favoretti commented
![image](https://user-images.githubusercontent.com/805046/219968969-8f6f70cf-38b8-4aef-991e-50baf76e60e4.png)

2023-02-21 08:43 UTC, stephybun requested changes
Thanks for this @favoretti, one minor typo in the docs and also a concern regarding the default value for the property. Once those are resolved this should be good to go though!

2023-02-21 08:43 UTC, stephybun commented on website/docs/r/mariadb_server.html.markdown
> +* `ssl_minimal_tls_version_enforced` - (Optional) The minimum TLS version to support on the sever. Possible values are `TLSEnforcementDisabled`, `TLS1_0`, `TLS1_1`, and `TLS1_2`. Defaults to `TLS1_2`
```suggestion
* `ssl_minimal_tls_version_enforced` - (Optional) The minimum TLS version to support on the server. Possible values are `TLSEnforcementDisabled`, `TLS1_0`, `TLS1_1`, and `TLS1_2`. Defaults to `TLS1_2`.
```

2023-02-21 08:43 UTC, stephybun commented on internal/services/mariadb/mariadb_server_resource.go
> +			},
Whilst I agree from a security perspective that this should be defaulted to `TLS1_2`, it looks like the API is defaulting this to `TLSEnforcementDisabled`. Perhaps this should be `Computed` for now and default to `TLS1_2` in 4.x?

2023-04-04 10:10 UTC, stephybun commented
@favoretti any updates?

2023-04-09 10:00 UTC, favoretti commented
Oh, I’m so sorry, I totally forgot about this one. Will pick it up later
today.

On Tue, 4 Apr 2023 at 12:11, stephybun ***@***.***> wrote:

> @favoretti <https://github.com/favoretti> any updates?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hashicorp/terraform-provider-azurerm/pull/20556#issuecomment-1495701793>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGERNUCVYALWN5HDAYTL43W7PXT5ANCNFSM6AAAAAAVBBFWDE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-11 09:08 UTC, favoretti commented
Ah, it seems #20782 got merged ahead of slowpokle me :) Closing this one then.

2023-04-11 09:08 UTC, closed without merging