`azurerm_express_route_connection` - Support `inbound_route_map_id`, `outbound_route_map_id`, `enabled_private_link_fast_path`
hashicorp/terraform-provider-azurerm pull request #20619
Opened 2023-02-23 02:33 UTC by xuzhang3

Support `inbound_route_map_id`, `outbound_route_map_id`, `enabled_private_link_fast_path`

```log
=== RUN   TestAccExpressRouteConnection_basic
--- PASS: TestAccExpressRouteConnection_basic (5665.34s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/network       5705.892s

PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/network       6358.210s

=== RUN   TestAccExpressRouteConnection
=== RUN   TestAccExpressRouteConnection/Resource
=== RUN   TestAccExpressRouteConnection/Resource/requiresImport
--- PASS: TestAccExpressRouteConnection (5550.84s)
    --- PASS: TestAccExpressRouteConnection/Resource (5550.84s)
        --- PASS: TestAccExpressRouteConnection/Resource/requiresImport (5550.84s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/network       5603.748s

=== RUN   TestAccExpressRouteConnection
=== RUN   TestAccExpressRouteConnection/Resource
=== RUN   TestAccExpressRouteConnection/Resource/complete
--- PASS: TestAccExpressRouteConnection (5472.03s)
    --- PASS: TestAccExpressRouteConnection/Resource (5472.03s)
        --- PASS: TestAccExpressRouteConnection/Resource/complete (5472.03s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/network       5532.557s

=== RUN   TestAccExpressRouteConnection
=== RUN   TestAccExpressRouteConnection/Resource
=== RUN   TestAccExpressRouteConnection/Resource/update
--- PASS: TestAccExpressRouteConnection (6486.12s)
    --- PASS: TestAccExpressRouteConnection/Resource (6486.12s)
        --- PASS: TestAccExpressRouteConnection/Resource/update (6486.12s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/network       6533.837s
```

2023-02-23 09:48 UTC, stephybun requested changes
Thanks for this @xuzhang3, left a few comments in-line but once those are resolved we can take another look and get this merged!

2023-02-23 09:48 UTC, stephybun commented on internal/services/network/express_route_connection_resource.go
> +			"enabled_express_route_gateway_bypass": {
Can we rename this to
```suggestion
			"express_route_gateway_bypass_enabled": {
```

2023-02-23 09:48 UTC, stephybun commented on website/docs/r/express_route_connection.html.markdown
> +* `enabled_express_route_gateway_bypass` - (Optional) Indicates whether FastPath enabled for Virtual Wan Firewall Hub. Defaults to `false`.
Is that what this property does? The description doesn't sound like it matches the property name
```suggestion
* `enabled_express_route_gateway_bypass` - (Optional) Specified whether Fast Path is enabled for Virtual Wan Firewall Hub. Defaults to `false`.
```

2023-02-23 09:48 UTC, stephybun commented on website/docs/r/express_route_connection.html.markdown
> +
```suggestion
* `inbound_route_map_id` - (Optional) The ID of the Route Map associated with this Express Route Connection for inbound routes.

* `outbound_route_map_id` - (Optional) The ID of the Route Map associated with this Express Route Connection for outbound routes.

```

2023-02-23 23:50 UTC, katbyte approved these changes
LGTM 🦀

2023-02-23 23:50 UTC, merged

2023-02-24 07:56 UTC, stephybun reviewed
Thanks @xuzhang3 LGTM 🚴