`azurerm_kusto_cluster` - fixes `TestAccKustoCluster_languageExtensions`
hashicorp/terraform-provider-azurerm pull request #20707
Opened 2023-03-01 06:04 UTC by liuwuliuyun

This PR resolves an issue with the `TestAccKustoCluster_languageExtensions` test, which was failing due to an update to the `language_extensions` property. This property is now treated as an unordered array, and this PR updates the test to accommodate this change.

2023-03-06 16:36 UTC, katbyte requested changes
Should we not be just making this property a set instead of a list?

2023-03-07 05:58 UTC, liuwuliuyun commented
I think that would introduce a breaking change to exsiting users. But if that is allowed, I agree that we could easily make this as typeSet.

2023-03-10 06:14 UTC, liuwuliuyun commented
Shall I change this to typeSet? It will be breaking change for anyone using tolist() instead of toset() in terraform.

2023-03-14 11:05 UTC, tombuildsstuff requested changes
hey @liuwuliuyun 

Thanks for replying inline, I've left a few comments inline, but if we can make this a Set rather than a List we should be good to go here.

Thanks!

2023-03-14 11:05 UTC, tombuildsstuff commented on internal/services/kusto/kusto_cluster_resource_test.go
> +				check.That(data.ResourceName).Key("language_extensions.1").Exists(),
the `import` step below will validate this, so we can remove these:

```suggestion
```

2023-03-14 11:05 UTC, tombuildsstuff commented on internal/services/kusto/kusto_cluster_resource.go
> +}
this isn't needed if we make this a `Set` instead of a `List`

```suggestion
```

2023-03-14 11:05 UTC, tombuildsstuff commented on internal/services/kusto/kusto_cluster_resource.go
> +				DiffSuppressFunc: languageExtensionDiffSuppress,
we can remove this in favour of making `language_extensions` a Set - this field isn't going to be interpolated, so whilst this is a breaking change, this isn't an issue here.

2023-03-15 03:29 UTC, liuwuliuyun commented
Thanks for the review @tombuildsstuff. PR reraised in https://github.com/hashicorp/terraform-provider-azurerm/pull/20951

2023-03-15 03:29 UTC, closed without merging