`azurerm_mysql_flexible_server` - support `geo_backup_key_vault_key_id` and `geo_backup_user_assigned_identity_id`
hashicorp/terraform-provider-azurerm pull request #20796
Opened 2023-03-06 06:34 UTC by neil-yechenwei

fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/20408

To enable `geo_redundant_backup_enabled`, these two properties `geo_backup_key_vault_key_id` and `geo_backup_user_assigned_identity_id` also need to be set.

--- PASS: TestAccMySqlFlexibleServer_enableGeoRedundantBackup (1382.72s)

2023-03-07 05:44 UTC, katbyte requested changes
Test failures:
```
------- Stdout: -------
=== RUN   TestAccMySqlFlexibleServer_complete
=== PAUSE TestAccMySqlFlexibleServer_complete
=== CONT  TestAccMySqlFlexibleServer_complete
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Flexible Server (Subscription: "*******"
        Resource Group Name: "acctestRG-mysql-230307035443686329"
        Flexible Server Name: "acctest-fs-230307035443686329"): polling after Create: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '60d8c15a-3b56-48bd-9726-18b7f576fa67'"
        
          with azurerm_mysql_flexible_server.test,
          on terraform_plugin_test.tf line 63, in resource "azurerm_mysql_flexible_server" "test":
          63: resource "azurerm_mysql_flexible_server" "test" {
        
--- FAIL: TestAccMySqlFlexibleServer_complete (544.95s)
FAIL
```

2023-03-08 01:01 UTC, neil-yechenwei commented
@katbyte , due to quota, I changed the test location for mysql in settings.kt in this PR. So maybe you also have to change the test location before PR merge. I just now reran the test cases. Seems they all passed.

![image](https://user-images.githubusercontent.com/19754191/223591829-4ca591d5-3ddc-4f32-9355-e34b5dc81324.png)

2023-03-09 00:42 UTC, katbyte commented
@neil-yechenwei - if the wrong location is picked `Code="InternalServerError" Message="An unexpected error occured while processing the request. ` is the error?

if that is so could you please open an issue on the rest specs detailing it, and adding a note in the documentation as that is a very hard to action/understand error

2023-03-09 01:49 UTC, neil-yechenwei commented
@katbyte , raised an [issue](https://github.com/Azure/azure-rest-api-specs/issues/22980) on azure rest api spec. Actually, the test case you mentioned has failed for a long time. It's not related with this PR.

2023-03-10 07:20 UTC, neil-yechenwei commented
@katbyte , Seems the quota issue is resolved on your test subs. So I reverted the change about test location. I just now reran test cases and all passed.

![image](https://user-images.githubusercontent.com/19754191/224240358-b070b699-22b4-4a52-82ea-3a49b897e722.png)
![image](https://user-images.githubusercontent.com/19754191/224249714-73f867e8-74d0-4fdc-a7f5-c1530298d601.png)

2023-03-16 01:13 UTC, neil-yechenwei commented
Hi @katbyte , as test cases passed, is it fine to be merged for this PR?

2023-03-20 21:27 UTC, katbyte approved these changes
Thanks, LGTM aside from 1 comment

2023-03-20 21:27 UTC, katbyte commented on internal/services/mysql/mysql_flexible_server_resource_test.go
> +func TestAccMySqlFlexibleServer_enableGeoRedundantBackup(t *testing.T) {
```suggestion

// this test can fail with a uninformative error, tracked here https://github.com/Azure/azure-rest-api-specs/issues/22980
func TestAccMySqlFlexibleServer_enableGeoRedundantBackup(t *testing.T) {
```

2023-03-21 00:21 UTC, merged