`azurerm_key_vault_managed_hardware_security_module` - support activate ManagedHSM in terraform
hashicorp/terraform-provider-azurerm pull request #20855
Opened 2023-03-09 04:24 UTC by wuxu92

the managed HSM has to be activated before using it. This PR add this function by using the certificates generated from keyvault reosurce.

this function is needed for creating keys under managed HSM.

reference doc: https://learn.microsoft.com/en-us/azure/key-vault/managed-hsm/quick-create-cli#activate-your-managed-hsm

```
=== RUN   TestAccKeyVaultManagedHardwareSecurityModule/resource/download
        --- PASS: TestAccKeyVaultManagedHardwareSecurityModule/resource/download (1839.39s)
```

2023-04-04 00:34 UTC, katbyte requested changes
we need to fix the tests up:
```
 testcase.go:117: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Managed H S M: (Name "kvHsm230401192111680619" / Resource Group "acctestRG-KV-230401192111680619"): keyvault.ManagedHsmsClient#CreateOrUpdate: Failure sending request: StatusCode=503 -- Original Error: Code="503" Message="Pool creation is disabled in this region"
        
          with azurerm_key_vault_managed_hardware_security_module.test,
          on terraform_plugin_test.tf line 27, in resource "azurerm_key_vault_managed_hardware_security_module" "test":
          27: resource "azurerm_key_vault_managed_hardware_security_module" "test" {
        
=== RUN   TestAccKeyVaultManagedHardwareSecurityModule/resource/update
    testcase.go:117: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Managed H S M: (Name "kvHsm230401192433135766" / Resource Group "acctestRG-KV-230401192433135766"): keyvault.ManagedHsmsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ManagedHsmInsufficentQuota" Message="You may only create only 5 HSM pool(s) per subscription in a region."
        
          with azurerm_key_vault_managed_hardware_security_module.test,
          on terraform_plugin_test.tf line 27, in resource "azurerm_key_vault_managed_hardware_security_module" "test":
          27: resource "azurerm_key_vault_managed_hardware_security_module" "test" {
        
=== RUN   TestAccKeyVaultManagedHardwareSecurityModule/resource/complete
=== RUN   TestAccKeyVaultManagedHardwareSecurityModule/resource/download
    testcase.go:117: Step 1/6 error: Error running apply: exit status 1
        
        Error: creating Managed H S M: (Name "kvHsm230401195642032955" / Resource Group "acctestRG-KV-230401195642032955"): keyvault.ManagedHsmsClient#CreateOrUpdate: Failure sending request: StatusCode=503 -- Original Error: Code="503" Message="Pool creation is disabled in this region"
        
          with azurerm_key_vault_managed_hardware_security_module.test,
          on terraform_plugin_test.tf line 27, in resource "azurerm_key_vault_managed_hardware_security_module" "test":
          27: resource "azurerm_key_vault_managed_hardware_security_module" "test" {
```

2023-04-23 04:31 UTC, wuxu92 commented
```

2023-04-23 08:05 UTC, wuxu92 commented
acc local run pass now, I'll run in TC later.
```
=== RUN   TestAccKeyVaultManagedHardwareSecurityModule
--- PASS: TestAccKeyVaultManagedHardwareSecurityModule (11364.42s)
=== RUN   TestAccKeyVaultManagedHardwareSecurityModule/data_source
    --- PASS: TestAccKeyVaultManagedHardwareSecurityModule/data_source (2352.79s)
=== RUN   TestAccKeyVaultManagedHardwareSecurityModule/data_source/basic
        --- PASS: TestAccKeyVaultManagedHardwareSecurityModule/data_source/basic (2352.79s)
=== RUN   TestAccKeyVaultManagedHardwareSecurityModule/resource
    --- PASS: TestAccKeyVaultManagedHardwareSecurityModule/resource (9011.63s)
=== RUN   TestAccKeyVaultManagedHardwareSecurityModule/resource/update
        --- PASS: TestAccKeyVaultManagedHardwareSecurityModule/resource/update (1775.53s)
=== RUN   TestAccKeyVaultManagedHardwareSecurityModule/resource/complete
        --- PASS: TestAccKeyVaultManagedHardwareSecurityModule/resource/complete (1876.14s)
=== RUN   TestAccKeyVaultManagedHardwareSecurityModule/resource/download
        --- PASS: TestAccKeyVaultManagedHardwareSecurityModule/resource/download (3319.75s)
=== RUN   TestAccKeyVaultManagedHardwareSecurityModule/resource/basic
        --- PASS: TestAccKeyVaultManagedHardwareSecurityModule/resource/basic (2040.20s)
PASS
```

2023-05-23 05:52 UTC, wuxu92 commented
Hi @mbfrahry I have rebased origin/main and the LRO issue exists in the new sdk too.

2023-05-23 23:07 UTC, mbfrahry requested changes
Hey @wuxu92, thanks for getting that ported over. I've looked through again and it needs more testing and design changes that I've documented below.

2023-05-24 09:36 UTC, tombuildsstuff requested changes
Left some comments inline, but if we can fix those up then we should be able to take another look here 👍

2023-05-25 05:52 UTC, wuxu92 commented on internal/services/keyvault/key_vault_managed_hardware_security_module_resource.go
> +			"security_domain_enc_data": {
this is an activate action rather than a resource. it has no update/delete methods so I think it should be a part of the managed HSM itself.

2023-05-25 06:04 UTC, wuxu92 commented on internal/services/keyvault/key_vault_managed_hardware_security_module_resource.go
> +// https://github.com/Azure/azure-rest-api-specs/issues/23035
this is a data-plane API. Does go-azure-sdk support data-plane now?

2023-05-25 06:34 UTC, wuxu92 commented on internal/services/keyvault/key_vault_managed_hardware_security_module_resource.go
> +		}
The length of certs has been checked in the `if` statement before.

2023-05-25 13:28 UTC, wuxu92 commented on website/docs/r/key_vault_managed_hardware_security_module.html.markdown
> +* `security_domain_certificate` - (Required) A list of KeyVault certificates resource ID(minimum of three and up to a maximum of 10) to activate this Managed HSM. More information see [activate-your-
how do you think of renaming as `certificate_ids`?

2023-05-25 14:57 UTC, katbyte commented on website/docs/r/key_vault_managed_hardware_security_module.html.markdown
> +* `security_domain_certificate` - (Required) A list of KeyVault certificates resource ID(minimum of three and up to a maximum of 10) to activate this Managed HSM. More information see [activate-your-
`security_domain_certificate_ids` or `acrivation_key_vault_certificat_ids` ?

2023-05-29 03:23 UTC, wuxu92 commented on website/docs/r/key_vault_managed_hardware_security_module.html.markdown
> +* `security_domain_certificate` - (Required) A list of KeyVault certificates resource ID(minimum of three and up to a maximum of 10) to activate this Managed HSM. More information see [activate-your-
renamed to `activation_key_vault_certificate_ids`

2023-06-06 02:26 UTC, wuxu92 commented
@katbyte Only some regions support creating Managed HSM resources and there is a quota limitation (only 5 in my experience) for a subscription in each region. so it's easy to failed. This case can get pass easier if set `env.ARM_PROVIDER_DYNAMIC_TEST` as `false`.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/2633022/fd899fdb-ef0d-4134-b0cc-00d96ac89b4a)

2023-06-08 23:42 UTC, mbfrahry approved these changes
LGTM! Thanks for making those changes @wuxu92

2023-06-09 01:36 UTC, merged