`azurerm_role_assignment`: Allow for sub aliases scopes
hashicorp/terraform-provider-azurerm pull request #20895
Opened 2023-03-10 15:45 UTC by favoretti

2023-03-13 13:57 UTC, favoretti commented
1 failing is transient and isn't related to the chages.

![image](https://user-images.githubusercontent.com/805046/224723139-9f5f0ba9-27bf-4d57-b3ac-dcafd85f34b4.png)

2023-03-17 13:51 UTC, manicminer requested changes
Hi @favoretti, thanks for looking at this. I think overall this looks good, I'm just concerned about unit test coverage (see comment below).

2023-03-17 13:51 UTC, manicminer commented on internal/services/authorization/parse/role_assignment_test.go
> +				Name:                     "23456781-2349-8764-5631-234567890121",
It looks like `IsSubscriptionAliasLevel` is not being tested below?

Also I think `SubscriptionAlias` should be added/tested here?

```suggestion
				Name:                     "23456781-2349-8764-5631-234567890121",
				SubscriptionAlias:        "my-awesome-sub",
```

2023-03-17 15:58 UTC, favoretti commented
> Hi @favoretti, thanks for looking at this. I think overall this looks good, I'm just concerned about unit test coverage (see comment below).

@manicminer Good catch on testing `SubscriptionAlias` value, thanks for that. Not sure I follow though about `IsSubscriptionAliasLevel` not being tested below?

2023-03-17 16:34 UTC, manicminer commented
@favoretti Towards the end of the `TestRoleAssignmentID()` func, there are checks to ensure the returned ID is populated correctly - we'll want to add checks for the `IsSubscriptionAliasLevel and `SubscriptionAlias` fields, else the test will just pass whatever their value :)

2023-03-17 16:40 UTC, favoretti commented
@manicminer gotcha, pushed a fix.

2023-03-21 00:28 UTC, katbyte approved these changes
LGTM 💡

2023-03-21 00:28 UTC, merged

2023-04-20 07:57 UTC, PreciousEdmund commented
Hi, I have a customer that has issues with this version though
When using this version he gets this error **_"Error: reading Subscription Alias “Hidden ID”: subscriptions.SubscriptionsClient#AliasGet: Failure responding to request: StatusCode=401 – Original Error: autorest/azure: Service returned an error. Status=401 Code=”UserNotAuthorized” Message=”User does not have access Microsoft.Subscription/aliases/write over scope providers/Microsoft.Subscription/aliases/HiddenID"_**

But when using the version 3.49.0 everything works out fine.

**Hidden ID**: To Prevent personal information

2023-04-26 22:14 UTC, sampathkovuri commented
It seems that I am experiencing a similar error as mentioned above, but only with manually created subscriptions. I have several subscriptions that were created programmatically with Terraform, where I am able to upgrade the azurerm provider without any issues. If anyone has a solution for this problem, please inform me.

2023-04-26 23:06 UTC, favoretti commented
So initial release code in 3.49 worked? Any ideas which release broke it?

2023-04-27 06:09 UTC, sampathkovuri commented
> So initial release code in 3.49 worked? Any ideas which release broke it?

It works without any issues with 3.49.0, breaks with all versions above it

2023-04-27 08:03 UTC, PreciousEdmund commented
Oh, glad i'm not the only @sampathkovuri 

Please @favoretti , can you look into this 


![image](https://user-images.githubusercontent.com/131344840/234799003-819a09ee-19a3-4d69-b4c5-997ebda236bb.png)