`azurerm_postgresql_flexible_server`: fix the logic in update
hashicorp/terraform-provider-azurerm pull request #20929
Opened 2023-03-14 06:50 UTC by ziyeqf

fix https://github.com/hashicorp/terraform-provider-azurerm/issues/20900

the root cause is: `administrator_login` is only able to be set when `authentication.password_auth_enabled` set to `true`...

draft to run acctest on TC

2023-03-14 17:56 UTC, nbjohnson commented
I just want to clarify, is this change going to allow me to remove password auth after creation? Or is this just going to clarify the error output that once password auth is enabled it cannot be disabled?

2023-03-15 01:59 UTC, ziyeqf commented
> I just want to clarify, is this change going to allow me to remove password auth after creation? Or is this just going to clarify the error output that once password auth is enabled it cannot be disabled?

It's going to allow update `password_auth_enabled` from `true` to `false`, which get an error before. And when doing so, there is no need to remove `administrator_login` and `administrator_password`. it allows to do the following steps:

1. first time apply
```
resource "azurerm_postgresql_flexible_server" "test" {
# other properties...
  administrator_login    = "adminZhenTerraform"
  administrator_password = "QAZwsx123"

  authentication {
    password_auth_enabled         = true
  }
}
```

2. update to disable `password_auth_enabled`
```
resource "azurerm_postgresql_flexible_server" "test" {
# other properties...
  administrator_login    = "adminZhenTerraform"
  administrator_password = "QAZwsx123"

  authentication {
    password_auth_enabled         = false
  }
}
```
```

2023-03-15 15:05 UTC, ziyeqf commented
> @ziyeqf Ok thanks for the clarification. I guess I don't care if it allows users to pass in a login and password that it will just ignore. If you look at my code I was passing in `null` for both of them while at the same time disabling password auth. So my problem was that I just couldn't turn off password auth as it still thought login and password were present even when I was passing in `null`.
> 
> 
> 
> ```
> 
> administrator_login = var.password_auth_enabled == true ? var.administrator_login : null
> 
> administrator_password = var.password_auth_enabled == true ? var.administrator_password : null
> 
> ```

This PR will fix the bug which blocks disabling password auth. And my personal suggestion is not to pass "administrator_login" a "null" value, because once it has been set,setting it to another value (except "null") will force a new server to be created.

2023-03-17 12:40 UTC, nbjohnson commented
@ziyeqf Thanks for putting this together as having the ability to disable password auth after creation is a big requirement for me so I can switch existing servers from password auth to only AD auth. Do we know when this change might be implemented as it is blocking my implementation.

2023-03-21 00:31 UTC, katbyte requested changes

2023-03-21 00:31 UTC, katbyte commented on internal/services/postgres/postgresql_flexible_server_resource.go
> +			return fmt.Errorf("`administrator_login` and `administrator_password` cannot be set in creation when `authentication.password_auth_enabled` is set to `false`")
grammer
```suggestion
			return fmt.Errorf("`administrator_login` and `administrator_password` cannot be set during creation when `authentication.password_auth_enabled` is set to `false`")
```

2023-03-21 00:31 UTC, katbyte commented on internal/services/postgres/postgresql_flexible_server_resource.go
> +				return fmt.Errorf("when `administrator_login` is set first time, `authentication.password_auth_enabled` must be set to `true`")
grammer
```suggestion
				return fmt.Errorf("when `administrator_login` is first set, `authentication.password_auth_enabled` must be set to `true`")
```

2023-03-21 00:31 UTC, katbyte commented on website/docs/r/postgresql_flexible_server.html.markdown
> +-> **Note:** To create with `administrator_login` specified or update with it specified first time, `authentication.password_auth_enabled` must be set to `true`.
as above

2023-03-28 13:09 UTC, nbjohnson commented
Any update on this fix? I need this fix as soon as possible as it is blocking my implementation

2023-04-01 16:35 UTC, katbyte approved these changes
LGTM 🦀

2023-04-01 16:35 UTC, merged