`azurerm_kusto_cluster` - fixes `TestAccKustoCluster_languageExtensions`
hashicorp/terraform-provider-azurerm pull request #20951
Opened 2023-03-15 03:29 UTC by liuwuliuyun

This PR resolves an issue with the `TestAccKustoCluster_languageExtensions` test, which was failing due to an update to the `language_extensions` property. This property is now treated as an unordered array, and this PR updates the test to accommodate this change.

Reraise this according to @tombuildsstuff 's comment in https://github.com/hashicorp/terraform-provider-azurerm/pull/20707

2023-03-15 03:30 UTC, liuwuliuyun commented
Testing evidence will be listed shortly after TC test.

2023-03-17 11:50 UTC, tombuildsstuff requested changes
One comment but otherwise 👍

2023-03-17 11:50 UTC, tombuildsstuff commented on internal/services/kusto/migration/kusto_cluster_migration_v0_to_v1.go
> +			Type:     pluginsdk.TypeSet,
this is a point-in-time reference which shouldn't change - so this would still be a List:

```suggestion
			Type:     pluginsdk.TypeList,
```

2023-03-20 09:46 UTC, tombuildsstuff approved these changes
LGTM 👍

2023-03-20 10:35 UTC, merged