[Fix] - `azurerm_redis_cache` - Remove `redis_version` 4 support
hashicorp/terraform-provider-azurerm pull request #20977
Opened 2023-03-16 09:19 UTC by xuzhang3

Remove `redis_version` 4 support as this version is to be retied and no longer support creating new instance.
Ref: https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-retired-features#important-upgrade-timelines
```log
=== RUN   TestAccRedisCache_RedisVersion
=== PAUSE TestAccRedisCache_RedisVersion
=== CONT  TestAccRedisCache_RedisVersion
--- PASS: TestAccRedisCache_RedisVersion (1138.03s)
PASS
```

2023-03-21 00:51 UTC, katbyte requested changes
@xuzhang3 - would this not break the resources for users with existing redis 4 instances?

2023-03-21 08:02 UTC, xuzhang3 commented
> existing



> @xuzhang3 - would this not break the resources for users with existing redis 4 instances?

Old v4 instance can still be managed. This fix will stop creating new v4 instance.

2023-03-21 08:19 UTC, tombuildsstuff commented
@xuzhang3 if we remove the possibility of setting this value to `4`, how would existing users be able to manage those clusters, until they upgrade to v6?

2023-03-21 09:24 UTC, xuzhang3 commented
> @xuzhang3 if we remove the possibility of setting this value to `4`, how would existing users be able to manage those clusters, until they upgrade to v6?

I verified with a private package that with remove the version 4 the old instance can still be updated.  It seems that the service only prevents creation, but update requests will be accepted.   My tests not cover all the scenario. Should we add v4 back but add a local validator on create?

2023-03-21 09:45 UTC, tombuildsstuff commented
@xuzhang3 as the API will reject new v4 caches, so removing this value at this time would only mean users couldn't update existing clusters - so rather than removing this value, we should add a documentation note for now that it's not possible to create new v4 caches, and that support for v4 caches will be removed in a future release.

2023-03-22 09:28 UTC, tombuildsstuff approved these changes
One minor comment but otherwise 👍

2023-03-22 09:28 UTC, tombuildsstuff commented on website/docs/r/redis_cache.html.markdown
> +-> **Note:** Redis version 4 is being retired and no longer supports creating new instances. Version 4 will be removed in a future release. [Redis Version 4 Retirement](https://learn.microsoft.com/en
FYI: if you remove the language from the URI (as below) then it'll redirect into the users local language (if available)

```suggestion
-> **Note:** Redis version 4 is being retired and no longer supports creating new instances. Version 4 will be removed in a future release. [Redis Version 4 Retirement](https://learn.microsoft.com/azure/azure-cache-for-redis/cache-retired-features#important-upgrade-timelines)
```

2023-04-01 16:33 UTC, katbyte approved these changes

2023-04-01 16:33 UTC, merged