`azurerm_sentinel_alert_rule_template`: fix the id trim when reading by display name
hashicorp/terraform-provider-azurerm pull request #21054
Opened 2023-03-21 05:27 UTC by ziyeqf

fix https://github.com/hashicorp/terraform-provider-azurerm/issues/21040

Test
---
```
terraform-provider-azurerm ❯ TF_ACC=1 go test -v ./internal/services/sentinel -run=TestAccSentinelAlertRuleTemplateDataSource -timeout=600m
=== RUN   TestAccSentinelAlertRuleTemplateDataSource_fusion
=== PAUSE TestAccSentinelAlertRuleTemplateDataSource_fusion
=== RUN   TestAccSentinelAlertRuleTemplateDataSource_securityIncident
=== PAUSE TestAccSentinelAlertRuleTemplateDataSource_securityIncident
=== RUN   TestAccSentinelAlertRuleTemplateDataSource_scheduled
=== PAUSE TestAccSentinelAlertRuleTemplateDataSource_scheduled
=== RUN   TestAccSentinelAlertRuleTemplateDataSource_nrt
=== PAUSE TestAccSentinelAlertRuleTemplateDataSource_nrt
=== CONT  TestAccSentinelAlertRuleTemplateDataSource_fusion
=== CONT  TestAccSentinelAlertRuleTemplateDataSource_scheduled
=== CONT  TestAccSentinelAlertRuleTemplateDataSource_securityIncident
=== CONT  TestAccSentinelAlertRuleTemplateDataSource_nrt
--- PASS: TestAccSentinelAlertRuleTemplateDataSource_securityIncident (273.88s)
--- PASS: TestAccSentinelAlertRuleTemplateDataSource_scheduled (274.09s)
--- PASS: TestAccSentinelAlertRuleTemplateDataSource_nrt (275.56s)
--- PASS: TestAccSentinelAlertRuleTemplateDataSource_fusion (282.20s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/sentinel      282.269s

```

2023-03-23 11:35 UTC, catriona-m requested changes
Thanks for this @ziyeqf - just left one minor suggestion for you to consider.

2023-03-23 11:35 UTC, catriona-m commented on internal/services/sentinel/sentinel_alert_rule_template_data_source.go
> +		id.AlertRuleTemplateName = name
```suggestion
		resp, name, err = getAlertRuleTemplateByDisplayName(ctx, client, workspaceID, displayName)
		}
		id := parse.NewSentinelAlertRuleTemplateID(subscriptionId, workspaceID.ResourceGroupName, workspaceID.WorkspaceName, name)
```

2023-03-23 11:35 UTC, catriona-m commented on internal/services/sentinel/sentinel_alert_rule_template_data_source.go
> +		id.AlertRuleTemplateName = name
it might be nicer to parse the id after getting the name, rather than just setting it in the id afterwards?

2023-04-11 09:28 UTC, tombuildsstuff commented on internal/services/sentinel/sentinel_alert_rule_template_data_source.go
> +	}
we can simplify this to:

```suggestion
 	if name != "" {
 		nameToLog = name
 		resp, err = getAlertRuleTemplateByName(ctx, client, workspaceID, name)
 		if err != nil {
 			return fmt.Errorf("an Alert Rule Template named %q was not found", name)
 		}
 	} else {
 		nameToLog = displayName
 		var realName *string
 		resp, realName, err = getAlertRuleTemplateByDisplayName(ctx, client, workspaceID, displayName)
 		if err != nil {
 			return fmt.Errorf("an Alert Rule Template with the Display Name %q was not found", displayName)
 		}
 		name = *realName
 	}
```

2023-04-26 11:02 UTC, stephybun approved these changes
Thanks @ziyeqf LGTM 🥪

2023-04-26 11:02 UTC, merged