`azurerm_kubernetes_cluster` - `multiple_standard_load_balancer_enabled`
hashicorp/terraform-provider-azurerm pull request #21072
Opened 2023-03-22 06:56 UTC by ms-henglu

2023-03-23 19:36 UTC, katbyte requested changes

2023-03-23 19:36 UTC, katbyte commented on internal/services/containers/kubernetes_cluster_resource.go
> +			lb["multiple_standard_load_balancer_enabled"] = v
this should be plural? as the property is + it doesn't make sense without a s?
```suggestion
		if v := lbp.EnableMultipleStandardLoadBalancers; v != nil {
			lb["multiple_standard_load_balancers_enabled"] = v
```

2023-03-23 19:36 UTC, katbyte commented on website/docs/r/kubernetes_cluster.html.markdown
> +* `multiple_standard_load_balancer_enabled` - (Optional) Is multiple standard load balancers per AKS cluster enabled?
grammer
```suggestion
* `multiple_standard_load_balancer_enabled` - (Optional) Are multiple standard load balancers for the cluster enabled?
```

2023-03-28 10:09 UTC, stephybun requested changes
Test failure:
```
------- Stdout: -------
=== RUN   TestAccKubernetesCluster_multipleLoadBalancer
=== PAUSE TestAccKubernetesCluster_multipleLoadBalancer
=== CONT  TestAccKubernetesCluster_multipleLoadBalancer
testcase.go:110: Step 3/4 error: After applying this test step, the plan was not empty.
stdout:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
# azurerm_kubernetes_cluster.test will be updated in-place
~ resource "azurerm_kubernetes_cluster" "test" {
id                                  = "/subscriptions/*******/resourceGroups/acctestRG-aks-230328075412883011/providers/Microsoft.ContainerService/managedClusters/acctestaks230328075412883011"
name                                = "acctestaks230328075412883011"
tags                                = {}
# (24 unchanged attributes hidden)
~ network_profile {
# (10 unchanged attributes hidden)
~ load_balancer_profile {
~ multiple_standard_load_balancers_enabled = true -> false
# (7 unchanged attributes hidden)
}
}
# (3 unchanged blocks hidden)
}
Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccKubernetesCluster_multipleLoadBalancer (876.03s)
FAIL
```

2023-03-30 02:04 UTC, ms-henglu commented
Hi all,

Thanks for the code review, but I got confirmation from the service team that this feature is not available yet, so I'll close this PR for now.

2023-03-30 02:04 UTC, closed without merging