New Resource : `azurerm_voice_services_communications_gateway_test_line`
hashicorp/terraform-provider-azurerm pull request #21111
Opened 2023-03-24 06:56 UTC by sinbai

Swagger Link: https://github.com/Azure/azure-rest-api-specs/blob/d632c45f406c48b5f72b7d031bf0742e46246c4b/specification/voiceservices/resource-manager/Microsoft.VoiceServices/stable/2023-01-31/voiceservices.json#L557

Test Result:
PASS: TestAccVoiceServicesTestLine_basic (234.97s)
PASS: TestAccVoiceServicesTestLine_requiresImport (308.26s)
PASS: TestAccVoiceServicesTestLine_complete (286.76s)
PASS: TestAccVoiceServicesTestLine_update (410.06s)

2023-03-24 14:49 UTC, catriona-m requested changes
Hi @sinbai thanks for this. I've left a couple of minor comments inline but overall this is looking pretty good. Thanks!

2023-03-27 08:05 UTC, sinbai commented on website/docs/r/voice_services_communications_gateway_test_line.html.markdown
> +  location                                 = "West Europe"
Fixed.

2023-03-27 08:05 UTC, sinbai commented on internal/services/voiceservices/voice_services_communications_gateway_test_line_resource.go
> +type CommunicationsGatewayTestLineModel struct {
Fixed.

2023-03-27 08:06 UTC, sinbai commented
@catriona-m thanks for your feedback. In addition to fix the comments above, I also updated the setting file of teamcity  to update the `LocationConfiguration`, since the devtest subscription only supports one (`westcentralus` ) of the three regions to create resource group. Could you please take another look?

The test result as follows:
![image](https://user-images.githubusercontent.com/39109137/227865083-4d19d44e-8e39-445a-aea1-57f235f5cec2.png)

2023-04-01 16:29 UTC, katbyte approved these changes
LGTM ☎️

2023-04-01 16:29 UTC, merged