New Resource - `azurerm_signalr_custom_certificate_binding`
hashicorp/terraform-provider-azurerm pull request #21112
Opened 2023-03-24 07:06 UTC by xiaxyi

acc test:
--- PASS: TestAccCustomCertBindingSignalrService_basic (619.70s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/signalr       620.378s

2023-03-24 15:48 UTC, catriona-m requested changes
Hi @xiaxyi, thanks for this. I've left a couple of comments inline for you to consider and then we can take another look at this. Thanks!

2023-03-24 15:48 UTC, catriona-m commented on internal/services/signalr/signalr_custom_certificate_binding_resource.go
> +			}
would it make sense to use something like `client.CustomCertificatesCreateOrUpdateThenPoll` here?

2023-03-24 15:48 UTC, catriona-m commented on internal/services/signalr/signalr_custom_certificate_binding_resource.go
> +				return fmt.Errorf("creating signalR custom certificate binding: %s: %+v", id, err)
```suggestion
				return fmt.Errorf("updating signalR custom certificate binding: %s: %+v", id, err)
```

2023-03-24 15:48 UTC, catriona-m commented on internal/services/signalr/signalr_custom_certificate_binding_resource.go
> +		return nil, "", fmt.Errorf("error fetching the custom certificate provisioing state")
```suggestion
		return nil, "", fmt.Errorf("error fetching the custom certificate provisioning state")
```

2023-03-24 15:48 UTC, catriona-m commented on internal/services/signalr/signalr_custom_certificate_binding_resource.go
> +type CustomCertBindingSignalrModel struct {
```suggestion
type CustomCertBindingSignalrResourceModel struct {
```

2023-03-24 15:48 UTC, catriona-m commented on internal/services/signalr/signalr_custom_certificate_binding_resource.go
> +			Computed:     true,
does this need to be computed?

2023-04-01 16:27 UTC, katbyte approved these changes
LGTM 🍰

2023-04-01 16:27 UTC, merged