`azurerm_app_configuration_feature` - support `key` property
hashicorp/terraform-provider-azurerm pull request #21252
Opened 2023-04-03 06:09 UTC by teowa

resolves https://github.com/hashicorp/terraform-provider-azurerm/issues/20985
The key is generated from the feature flag `name` by default, this PR export a customizable `key` property, which support `:` character in feature key. From Portal:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/104055472/229425049-b31e3be3-15ee-497c-9b44-f1fb094825c3.png">

2023-04-03 09:18 UTC, stephybun requested changes
Thanks for this @teowa

We have a test failure though
```
------- Stdout: -------
=== RUN   TestAccAppConfigurationFeature_noLabelUpdate
=== PAUSE TestAccAppConfigurationFeature_noLabelUpdate
=== CONT  TestAccAppConfigurationFeature_noLabelUpdate
testcase.go:110: Step 3/4 error: After applying this test step, the plan was not empty.
stdout:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
# azurerm_app_configuration_feature.test will be updated in-place
~ resource "azurerm_app_configuration_feature" "test" {
~ enabled                 = true -> false
id                      = "https://testacc-appconf230403091031840358.azconfig.io/kv/.appconfig.featureflag%2Facctest-ackey-230403091031840358?label=
name                    = "acctest-ackey-230403091031840358"
tags                    = {}
# (5 unchanged attributes hidden)
}
Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccAppConfigurationFeature_noLabelUpdate (163.47s)
FAIL
```

2023-04-03 13:29 UTC, stephybun commented
@teowa if there's an issue on the API side we should raise it with the service team - is there a ticket open on the swagger repo?

2023-04-04 01:27 UTC, teowa commented
> @teowa if there's an issue on the API side we should raise it with the service team - is there a ticket open on the swagger repo?

I should be more specific, the provided test failure seems hard to reproduce, I have re-run the tests for several times but all test pass. I guess it might be caused by things behind of the provider, like network or unstable API.

2023-04-04 06:23 UTC, stephybun requested changes
Thanks @teowa, two comments on the docs which I overlooked yesterday, the validation is caught/checked by the schema, we don't need to outline it in the docs. Once that's fixed up this should be good to go!

2023-04-04 06:23 UTC, stephybun commented on website/docs/r/app_configuration_feature.html.markdown
> +* `key` - (Optional) The key of the App Configuration Feature. `%` character is not allowed in key. If not specified, `name` will be used as the key. Changing this forces a new resource to be created
```suggestion
* `key` - (Optional) The key of the App Configuration Feature. The value for `name` will be used if this is unspecified. Changing this forces a new resource to be created.
```

2023-04-04 06:23 UTC, stephybun commented on website/docs/r/app_configuration_feature.html.markdown
> +* `name` - (Required) The name of the App Configuration Feature. `:` or `%` characters are not allowed in name. Changing this forces a new resource to be created.
```suggestion
* `name` - (Required) The name of the App Configuration Feature. Changing this forces a new resource to be created.
```

2023-04-04 10:23 UTC, stephybun approved these changes
Thanks for making those updates @teowa. LGTM 👍

2023-04-04 10:23 UTC, merged