`azurerm_container_apps` - Add scale rules
hashicorp/terraform-provider-azurerm pull request #21274
Opened 2023-04-04 06:48 UTC by jsok

Adds initial support for `http` and `custom` scale rules.
Note: Authentication support on the triggers is not supported in this PR.

Fixes #20629 #21207

2023-04-07 19:04 UTC, stewartbeck commented
Is there a possibility of adding Azure Queue support at the same time?  That would get to parity with what's available in the azure portal.

2023-04-14 10:15 UTC, jsok commented
> Is there a possibility of adding Azure Queue support at the same time?  That would get to parity with what's available in the azure portal.

Probably not by myself, but this PR should set it up for an easy addition.

Any progress on getting this reviewed?

2023-05-12 07:02 UTC, Dyhr commented
I'm also awaiting this feature and would love to see it being reviewed soon

2023-05-29 13:38 UTC, stfnzl commented
It would be AMAZING if this get merged <3

2023-06-05 01:16 UTC, jsok commented
2 month anniversary bump, @stephybun @jackofallops :)

2023-06-09 02:18 UTC, katbyte requested changes
Hey @jsok - looks like you have some test failures:

```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccContainerAppResource_basic
=== PAUSE TestAccContainerAppResource_basic
=== CONT  TestAccContainerAppResource_basic

------- Stderr: -------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4a3dbb1]

goroutine 528 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/containerapps/helpers.flattenContainerScale(0xc00283a438)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/services/containerapps/helpers/container_apps.go:1174 +0x51
github.com/hashicorp/terraform-provider-azurerm/internal/services/containerapps/helpers.FlattenContainerAppTemplate(0xc004257500)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/services/containerapps/helpers/container_apps.go:810 +0x68
github.com/hashicorp/terraform-provider-azurerm/internal/services/containerapps.ContainerAppResource.Read.func1({0x79ef9a8, 0xc0040fe900}, {0xc00475e400, {0x79f0230, 0xc00403a9a8}, 0xc004752880, 0x0, {0x79f1420, 0xc14d860}})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/services/containerapps/container_app_resource.go:263 +0xabf
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func2({0x79ef9a8, 0xc0040fe900}, 0x1a3185c441e?, {0x64ab6a0?, 0xc00475e400?})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/sdk/wrapper_resource.go:59 +0x1e5
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.diagnosticsWrapper.func1({0x79ef9a8, 0xc0040fe900}, 0x0?, {0x64ab6a0, 0xc00475e400})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/sdk/wrapper_resource.go:185 +0xbe
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0019737a0, {0x79ef9e0, 0xc0051ad080}, 0xd?, {0x64ab6a0, 0xc00475e400})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0019737a0, {0x79ef9e0, 0xc0051ad080}, 0xc000e3aa90, 0xc004752700, {0x64ab6a0, 0xc00475e400})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000cacf90, {0x79ef9e0?, 0xc0051acfc0?}, 0xc0051a60f0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc003eda1e0, {0x79ef9e0?, 0xc0051ac600?}, 0xc002f14070)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x6ca6ec0?, 0xc003eda1e0}, {0x79ef9e0, 0xc0051ac600}, 0xc002f14000, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0021c05a0, {0x7a000e0, 0xc003d4e340}, 0xc002bcc000, 0xc002b3a240, 0xc10c720, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0021c05a0, {0x7a000e0, 0xc003d4e340}, 0xc002bcc000, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:963 +0x28a

```

2023-06-30 15:52 UTC, ivanl-out commented
We'd also need an `auth` section for most scale rules as outlined here:
https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?pivots=deployment-language-terraform#customscalerule-2

2023-07-03 08:25 UTC, ivanl-out commented
I see there was a similar PR #22219 which was closed in favour of this one. That PR did have the `auth` schema implemented and it also contained documentation updates. Can those bits be cherry picked into this PR?

2023-09-17 23:58 UTC, jsok commented
Sorry all, I'm not in a position to follow up on these requested changes. My team has since decided to not use Container Apps after an initial PoC (Cloud Run is more mature and has better TF support).
I hope someone from the ACA team can pick this up and get it merged!

2023-09-17 23:58 UTC, closed without merging