Data source azurerm_keyvault_secret: support not_before_date and expiration_date
hashicorp/terraform-provider-azurerm pull request #21359
Opened 2023-04-11 00:18 UTC by herquan-docusign

Attribute `not_before_date` and `expiration_date` is already supported in resource `azurerm_key_vault_secret` but not supported in data source.

I didn't run the acceptance tests because I don't want to test on the whole subscription but I can have full access to a single resource group. Is there any document about how to do this?

2023-04-12 07:23 UTC, jackofallops requested changes
Thanks @herquan-docusign - Just a couple minor changes to take a look at, but should be good to merge once those are addressed.

2023-04-12 07:23 UTC, jackofallops commented on website/docs/d/key_vault_secret.html.markdown
> +* `not_before_date` - Key not usable before the provided UTC datetime (Y-m-d'T'H:M:S'Z').
We should keep the wording consistent with the rest of the resource/provider:
```suggestion
* `not_before_date` - The earliest date at which the Key Vault Secret can be used.
```

2023-04-12 07:23 UTC, jackofallops commented on website/docs/d/key_vault_secret.html.markdown
> +* `expiration_date` - Expiration UTC datetime (Y-m-d'T'H:M:S'Z').
as above
```suggestion
* `expiration_date` - The date and time at which the Key Vault Secret expires and is no longer valid.
```

2023-04-12 07:23 UTC, jackofallops commented on internal/services/keyvault/key_vault_secret_data_source.go
>  			"version": {
Whitespace here
```suggestion

			"not_before_date": {
				Type:     pluginsdk.TypeString,
				Computed: true,
			},

			"expiration_date": {
				Type:     pluginsdk.TypeString,
				Computed: true,
			},
			
			"version": {
```

2023-04-12 19:33 UTC, jackofallops approved these changes
Thanks for making those changes @herquan-docusign - LGTM now 👍

2023-04-12 19:33 UTC, jackofallops commented
Tests passing:

 <img width="616" alt="image" src="https://user-images.githubusercontent.com/11830746/231565285-385762ea-5c19-496f-af9a-902f7fc7d590.png">

2023-04-12 20:32 UTC, herquan-docusign commented
@jackofallops I did a rebase so we can have a clean change before merge

2023-04-13 05:14 UTC, jackofallops commented
> @jackofallops I did a rebase so we can have a clean change before merge

Thanks @herquan-docusign - This wasn't necessary in this case, you'd typically only need to do that to resolve conflicts or if you needed to pick up changes in the `main` branch, but we appreciate the diligence. 👍

2023-04-13 05:24 UTC, merged