`d/azurerm_key_vault_access_policy` - Fix Permission Case
hashicorp/terraform-provider-azurerm pull request #21410
Opened 2023-04-13 08:34 UTC by myc2h6o

Fix #21360

2023-04-13 08:52 UTC, tombuildsstuff requested changes
hi @myc2h6o 

Thanks for this PR - taking a look at the resource here it appears that there's already a function which we can use for this information which comes from the Resource, as such it should be possible to use that instead of duplicating this?

Thanks!

2023-04-13 08:52 UTC, tombuildsstuff commented on internal/services/keyvault/key_vault_access_policy_data_source.go
> +	})
we can use `certificatePermissions()` for this?

2023-04-13 08:52 UTC, tombuildsstuff commented on internal/services/keyvault/key_vault_access_policy_data_source.go
> +	})
we can use `keyPermissions()` for this?

2023-04-13 08:52 UTC, tombuildsstuff commented on internal/services/keyvault/key_vault_access_policy_data_source.go
>  	}
we'll need to ensure that a value is always set into the state for these fields, else the list will be `null` rather than an empty slice

2023-04-14 08:53 UTC, myc2h6o commented
Hi @tombuildsstuff thanks for reviewing the change! I've looked at the templates from Portal and figured out the values from template are different from the functions `keyPermission(), ...`. I've tuned some values according to the latest templates and used the functions we have in the central location.
Below is the screenshot I captured from Portal:

![image](https://user-images.githubusercontent.com/10579712/231994225-74eac252-a9a6-45f9-9509-cad135efc88e.png)

2023-05-09 14:14 UTC, tombuildsstuff commented
The PR https://github.com/hashicorp/pandora/pull/2456 should supersede this fwiw, since we'll be dynamically recasing this in both the Data Source and the Resource via the SDK

2023-05-09 14:36 UTC, myc2h6o commented
@tombuildsstuff there are permissions change in `key_permissions` according to the latest template on Azure Portal, and is updated to always set the values even if not returned from API, so it's still needed?

2023-08-10 13:25 UTC, stephybun approved these changes
Thanks @myc2h6o LGTM. As an FYI these will need to be lower cased again once we switch keyvault over to the new base-layer, but since the behaviour is currently broken anyway this is fine for now.

2023-08-14 08:29 UTC, merged