New Resource: azurerm_cosmosdb_postgresql_coordinator_configuration
hashicorp/terraform-provider-azurerm pull request #21595
Opened 2023-04-28 04:15 UTC by neil-yechenwei

2023-05-02 13:37 UTC, catriona-m requested changes
Thanks for this @neil-yechenwei, I left a couple of comments inline for you to consider but otherwise this is looking pretty good so far.

2023-05-02 13:37 UTC, catriona-m commented on internal/services/cosmos/cosmosdb_postgresql_coordinator_configuration_resource.go
> +			}
```suggestion
			if metadata.ResourceData.HasChange("value") {
				parameters := configurations.ServerConfiguration{
					Properties: &configurations.ServerConfigurationProperties{
						Value: model.Value,
					},
				}
				
				if err := client.UpdateOnCoordinatorThenPoll(ctx, *id, parameters); err != nil {
					return fmt.Errorf("updating %s: %+v", *id, err)
				}
			}
```

2023-05-02 13:37 UTC, catriona-m commented on internal/services/cosmos/cosmosdb_postgresql_coordinator_configuration_resource.go
> +			}
```suggestion
			state := CosmosDbPostgreSQLCoordinatorConfigurationModel{
				Name:      id.CoordinatorConfigurationName,
				ClusterId: configurations.NewServerGroupsv2ID(id.SubscriptionId, id.ResourceGroupName, id.ServerGroupsv2Name).ID(),
			}

			if model := resp.Model; model != nil {
				if props := model.Properties; props != nil {
					state.Value = props.Value
				}
			}
```

2023-05-02 13:37 UTC, catriona-m commented on internal/services/cosmos/cosmosdb_postgresql_coordinator_configuration_resource.go
> +			}
```suggestion
			defaultValue := ""
			if resp.Model != nil && resp.Model.Properties != nil && resp.Model.Properties.DefaultValue != nil {
				defaultValue = *resp.Model.Properties.DefaultValue
			}

			parameters := configurations.ServerConfiguration{
				Properties: &configurations.ServerConfigurationProperties{
					Value: defaultValue,
				},
			}

			if err = client.UpdateOnCoordinatorThenPoll(ctx, *id, parameters); err != nil {
				return fmt.Errorf("deleting %s: %+v", *id, err)
			}
```

2023-05-04 01:31 UTC, neil-yechenwei commented on internal/services/cosmos/cosmosdb_postgresql_coordinator_configuration_resource.go
> +			}
Updated

2023-05-04 01:31 UTC, neil-yechenwei commented on internal/services/cosmos/cosmosdb_postgresql_coordinator_configuration_resource.go
> +			}
Updated

2023-05-04 01:31 UTC, neil-yechenwei commented on internal/services/cosmos/cosmosdb_postgresql_coordinator_configuration_resource.go
> +			}
Updated

2023-05-04 01:31 UTC, neil-yechenwei commented on internal/services/cosmos/cosmosdb_postgresql_coordinator_configuration_resource.go
> +			}
Updated

2023-05-04 01:31 UTC, neil-yechenwei commented on internal/services/cosmos/cosmosdb_postgresql_cluster_resource.go
> +var CosmosDbPostgreSQLClusterResourceName = "azurerm_cosmosdb_postgresql_cluster"
Updated

2023-05-04 01:41 UTC, neil-yechenwei commented
@catriona-m , thanks for the comments. I updated PR. Please take another look. Thanks.

2023-05-04 13:25 UTC, catriona-m approved these changes
Thanks @neil-yechenwei - it looks like merging another azurerm_cosmosdb_postgresql* has caused conflicts with this and the other azurerm_cosmosdb_postgresql* PRs, but otherwise this LGTM!

2023-05-05 10:17 UTC, merged