`azurerm_site_recovery_replication_recovery_plan`: support `azure_to_azure_settings`
hashicorp/terraform-provider-azurerm pull request #21666
Opened 2023-05-05 08:53 UTC by ziyeqf

test
---
```
tftest recoveryservices TestAccSiteRecoveryReplicationRecoveryPlan          
=== RUN   TestAccSiteRecoveryReplicationRecoveryPlan_basic
=== PAUSE TestAccSiteRecoveryReplicationRecoveryPlan_basic
=== RUN   TestAccSiteRecoveryReplicationRecoveryPlan_withPreActions
=== PAUSE TestAccSiteRecoveryReplicationRecoveryPlan_withPreActions
=== RUN   TestAccSiteRecoveryReplicationRecoveryPlan_withPostActions
=== PAUSE TestAccSiteRecoveryReplicationRecoveryPlan_withPostActions
=== RUN   TestAccSiteRecoveryReplicationRecoveryPlan_withZones
=== PAUSE TestAccSiteRecoveryReplicationRecoveryPlan_withZones
=== CONT  TestAccSiteRecoveryReplicationRecoveryPlan_basic
=== CONT  TestAccSiteRecoveryReplicationRecoveryPlan_withPreActions
=== CONT  TestAccSiteRecoveryReplicationRecoveryPlan_withZones
=== CONT  TestAccSiteRecoveryReplicationRecoveryPlan_withPostActions
--- PASS: TestAccSiteRecoveryReplicationRecoveryPlan_withPreActions (2968.79s)
--- PASS: TestAccSiteRecoveryReplicationRecoveryPlan_basic (3000.41s)
--- PASS: TestAccSiteRecoveryReplicationRecoveryPlan_withPostActions (3096.27s)
--- PASS: TestAccSiteRecoveryReplicationRecoveryPlan_withZones (3352.37s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices      3352.441s
```

2023-05-06 03:05 UTC, ziyeqf commented
@catriona-m sure, test case added. Sorry for missing that one.
<img width="605" alt="Screenshot 2023-05-06 at 11 04 58" src="https://user-images.githubusercontent.com/51212351/236595377-c065176c-ab0b-4ba6-9591-7fc1686eb028.png">

2023-05-11 10:14 UTC, catriona-m requested changes
Thanks @ziyeqf - just spotted a couple of minor things on having a second look, but otherwise looking pretty good! Thanks!

2023-05-11 10:14 UTC, catriona-m commented on internal/services/recoveryservices/site_recovery_replication_recovery_plan_resource.go
> +
could we move this into an expand function?

2023-05-11 10:14 UTC, catriona-m commented on internal/services/recoveryservices/site_recovery_replication_recovery_plan_resource.go
> +				}
could we move this into a flatten function?

2023-05-11 10:14 UTC, catriona-m commented on website/docs/r/site_recovery_replication_recovery_plan.html.markdown
> +    Manages an Site Recovery Replication Recovery Plan within a Recovery Services vault.
```suggestion
    Manages a Site Recovery Replication Recovery Plan within a Recovery Services vault.
```

2023-05-11 10:14 UTC, catriona-m commented on website/docs/r/site_recovery_replication_recovery_plan.html.markdown
> +Manages an Site Recovery Replication Recovery Plan within a Recovery Services vault. A recovery plan gathers machines into recovery groups for the purpose of failover.
```suggestion
Manages a Site Recovery Replication Recovery Plan within a Recovery Services vault. A recovery plan gathers machines into recovery groups for the purpose of failover.
```

2023-05-24 01:52 UTC, katbyte approved these changes
LGTM 📺

2023-05-24 01:52 UTC, merged