New Datasource: azurerm_virtual_hub_connection
hashicorp/terraform-provider-azurerm pull request #21681
Opened 2023-05-06 00:18 UTC by TechyMatt

2023-05-15 11:00 UTC, tombuildsstuff requested changes
A few minor comments but this otherwise LGTM - thanks for this @TechyMatt

2023-05-15 11:00 UTC, tombuildsstuff commented on internal/services/network/virtual_hub_connection_data_source.go
> +										Type:     pluginsdk.TypeSet,
these'll need to be a List in a data source, else they all get the same hash value and combined into a single item:

```suggestion
										Type:     pluginsdk.TypeList,
```

2023-05-15 11:00 UTC, tombuildsstuff commented on internal/services/network/virtual_hub_connection_data_source.go
> +										Type:     pluginsdk.TypeSet,
(as below) in a data source this'll need to be a TypeList

```suggestion
										Type:     pluginsdk.TypeList,
```

2023-05-15 11:00 UTC, tombuildsstuff commented on website/docs/d/virtual_hub_connection.html.markdown
> +*  `virtual_hub_name` - The name which should be used for Virtual hub using the connection.
can we make this:

```suggestion
*  `virtual_hub_name` - The name of the Virtual Hub where this Connection exists.
```

2023-05-15 11:00 UTC, tombuildsstuff commented on website/docs/d/virtual_hub_connection.html.markdown
> +* `name` - The name of the Virtual Hub Connection.
```suggestion
* `name` - The name of the Connection which should be retrieved.
```

2023-05-15 15:10 UTC, TechyMatt commented
Thanks @tombuildsstuff changes made per comments.

2023-05-17 22:24 UTC, katbyte approved these changes
Thanks @TechyMatt - aside from one minor comment LGTM 🔧

2023-05-17 22:24 UTC, katbyte commented on website/docs/d/virtual_hub_connection.html.markdown
> +*  `virtual_hub_name` - The name of the Virtual Hub where this Connection exists.
```suggestion
* `resource_group_name` - The Name of the Resource Group where the Virtual Hub Connection exists.

*  `virtual_hub_name` - The name of the Virtual Hub where this Connection exists.
```

2023-05-17 22:24 UTC, merged