`data.azurerm_key_vault_encrypted_value`: use base64 url encoding for keyvault secret encrypt/decrypt
hashicorp/terraform-provider-azurerm pull request #21682
Opened 2023-05-06 02:22 UTC by wuxu92

according to the [swagger format](https://github.com/Azure/azure-rest-api-specs/blob/b2fe1573f29f056930d79b1b8abf2611b98fa81a/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.1/keys.json#L1463-L1466), we should pass a base64url encoded string to encrypt. more discussion see #20763 and https://github.com/Azure/azure-rest-api-specs/issues/23829

resolves #20763 

```
--- PASS: TestAccEncryptedValueDataSource_encryptAndDecrypt (459.34s)
PASS
```

*Note*: when base64url decode failed in decrypt stage, it just prints a DEBUG log and assign the API response as plainTextValue to make it compatible with old resources (that encrypt/decrypt accept non-encoded string too).

2023-05-26 17:33 UTC, mbfrahry requested changes
Hey @wuxu92, I think we should add a new attribute as this PR is changing the functionality of the existing attribute which could cause issues if someone is expecting it to do one thing and it is now doing another. We can deprecate the current attribute for 4.0 if need be.

2023-05-29 06:48 UTC, wuxu92 commented
@mbfrahry the current logic for the `plain_text_value` attribute just not work as expect: the decrypted result of an encrypted string is not the same as the string used to encrypt. in this case, remain the current logic for `plain_text_value` would be confusing and buggy. maybe the update notes could show the change and make it clarity to customers?

2023-06-01 22:56 UTC, mbfrahry requested changes
It sounds like this value is something different that `plain_text_value`. What about having a new computed attribute called `decrypted_plain_text_value`? That way there is a clear distinction between the two as they are both doing different things

2023-06-07 10:17 UTC, wuxu92 commented
@mbfrahry added a new `decoded_plain_text` attribute and updated the AccTests and document.

2023-06-07 20:03 UTC, mbfrahry approved these changes
LGTM! Thanks for making that change @wuxu92

2023-06-07 20:04 UTC, merged