`azurerm_app_configuration` - retry checkNameAvailability to fix `TestAccAppConfiguration_softDeletePurgeThenRecreate`
hashicorp/terraform-provider-azurerm pull request #21750
Opened 2023-05-11 03:58 UTC by teowa

add the `state.WaitForStateContext` to retry `checkNameAvailability` accoding to https://github.com/hashicorp/terraform-provider-azurerm/pull/17714#issuecomment-1225449556.
```
TF_ACC=1 go test -v ./internal/services/appconfiguration -parallel 50 -test.run=TestAccAppConfiguration_softDeletePurgeThenRecreate -timeout 1440m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAppConfiguration_softDeletePurgeThenRecreate
=== PAUSE TestAccAppConfiguration_softDeletePurgeThenRecreate
=== CONT  TestAccAppConfiguration_softDeletePurgeThenRecreate
--- PASS: TestAccAppConfiguration_softDeletePurgeThenRecreate (556.89s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/appconfiguration      558.142s

```

2023-05-11 06:36 UTC, stephybun requested changes
```
------- Stdout: -------
=== RUN   TestAccAppConfiguration_softDeleteRecovery
=== PAUSE TestAccAppConfiguration_softDeleteRecovery
=== CONT  TestAccAppConfiguration_softDeleteRecovery
testcase.go:110: Step 4/5 error: Error running apply: exit status 1
Error: waiting for the Configuration Store Configuration Store (Subscription: "*******"
Resource Group Name: "acctestRG-appconfig-230511054705781851"
Configuration Store Name: "testaccappconf230511054705781851") Name Available: timeout while waiting for state to become 'Available' (last state: 'Unavailable', timeout: 29m59.517047832s)
with azurerm_app_configuration.test,
on terraform_plugin_test.tf line 22, in resource "azurerm_app_configuration" "test":
22: resource "azurerm_app_configuration" "test" {
--- FAIL: TestAccAppConfiguration_softDeleteRecovery (1892.83s)
FAIL
```

2023-05-17 20:22 UTC, katbyte requested changes
I'm getting a test failure:
```
------- Stdout: -------
=== RUN   TestAccAppConfigurationKey_basicVault
=== PAUSE TestAccAppConfigurationKey_basicVault
=== CONT  TestAccAppConfigurationKey_basicVault
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to azurerm_app_configuration_key.test, provider
        "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an
        unexpected new value: Root resource was present, but now absent.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
--- FAIL: TestAccAppConfigurationKey_basicVault (409.06s)
FAIL
```

2023-05-24 02:05 UTC, katbyte commented
still seeing test failures
<img width="704" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/1638467/d9d91296-0a42-434f-a99d-5ae4affa88ae">

2023-05-24 08:54 UTC, teowa commented
Need to fix tests

2023-05-29 06:17 UTC, teowa commented
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/104055472/1bcc2fb6-644d-4512-9d85-11fe962fec7f)

2023-05-30 12:19 UTC, stephybun requested changes
Can you please add a test for `azurerm_app_configuration_feature` and `azurerm_app_configuration_key` to validate that the wait functions after creation is actually needed?

2023-05-30 12:19 UTC, stephybun commented on internal/services/appconfiguration/app_configuration.go
> +				if utils.ResponseWasNotFound(autorest.Response{Response: v.Response}) {
Can we make this change above as well for `response.WasForbidden`
```suggestion
				if response.WasNotFound(v.Response) {
```

2023-05-30 12:19 UTC, stephybun commented on internal/services/appconfiguration/app_configuration_feature_resource.go
> +			metadata.Logger.Infof("[DEBUG] Waiting for App Configuration Feature %q read permission to be done propagated", featureKey)
```suggestion
			metadata.Logger.Infof("[DEBUG] Waiting for App Configuration Feature %q read permission to be propagated", featureKey)
```

2023-05-30 12:19 UTC, stephybun commented on internal/services/appconfiguration/app_configuration_feature_resource.go
> +			metadata.Logger.Infof("[DEBUG] Waiting for App Configuration Feature %q to be done provisioned", model.Key)
```suggestion
			metadata.Logger.Infof("[DEBUG] Waiting for App Configuration Feature %q to be provisioned", model.Key)
```

2023-05-30 12:19 UTC, stephybun commented on internal/services/appconfiguration/app_configuration_key_resource.go
> +			metadata.Logger.Infof("[DEBUG] Waiting for App Configuration Key %q to be done provisioned", model.Key)
```suggestion
			metadata.Logger.Infof("[DEBUG] Waiting for App Configuration Key %q to be provisioned", model.Key)
```

2023-05-31 05:35 UTC, teowa commented
Hi @stephybun, thanks for reviewing this. I think it is hard to validate wait function is needed, for the `produced an unexpected new value: Root resource was present, but now absent` error is not 100% reproducible. The wait function is added based on the error from test subscription and customer provided error message in https://github.com/hashicorp/terraform-provider-azurerm/issues/21939. I have also report the error to service team through https://github.com/Azure/AppConfiguration/issues/733

2023-06-01 08:44 UTC, merged