New Resource: `azurerm_cosmosdb_mongo_role_definition`
hashicorp/terraform-provider-azurerm pull request #21754
Opened 2023-05-11 07:31 UTC by neil-yechenwei

--- PASS: TestAccCosmosDbMongoRoleDefinition_update (1421.11s)
--- PASS: TestAccCosmosDbMongoRoleDefinition_complete (1211.48s)
--- PASS: TestAccCosmosDbMongoRoleDefinition_basic (1160.74s)

2023-05-17 20:13 UTC, katbyte requested changes

2023-05-17 20:13 UTC, katbyte commented on internal/services/cosmos/cosmosdb_mongo_role_definition_resource.go
> +		"db_id": {
should this be 
```suggestion
		"cosmos_mongo_database_id": {
```

2023-05-18 01:15 UTC, neil-yechenwei commented on internal/services/cosmos/cosmosdb_mongo_role_definition_resource.go
> +		"db_id": {
Updated.

2023-05-18 01:51 UTC, neil-yechenwei commented
@katbyte , thanks for the comment. I updated PR. Please take another look. Thanks.
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/19754191/b6b814dd-2e97-459a-8535-0ccd948e7026)

2023-05-23 17:24 UTC, merged