`azurerm_windows_function_app`, `azurerm_linux_function_app` - fix `WEBSITE_RUN_FROM_PACKAGE` being removed from `app_setting` issue
hashicorp/terraform-provider-azurerm pull request #21952
Opened 2023-05-29 03:17 UTC by xiaxyi

This is a hot discussed issue. 

When function app is deployed via other platform such as azure devOps, or when function app is a zip deployment. The `WEBSITE_RUN_FROM_PACKAGE` will be added outside of Terraform, so the kvp will be removed when user doing terraform apply and the removal will cause function app to be broke.

fix https://github.com/hashicorp/terraform-provider-azurerm/issues/17081

For linux function app, the `WEBSITE_RUN_FROM_PACKAGE` is not be written back to state if terraform provider doesn't find it in config so ignore change is not going to work as no diff will be detected between state and config, thus `WEBSITE_RUN_FROM_PACKAGE` will still be removed.

For windows function app, we set back the `WEBSITE_RUN_FROM_PACKAGE` and don't do the config check by `metadata.get(app_setting.WEBSITE_RUN_FROM_PACKAGE)` so ignore change works. 

In this PR, a new property `website_run_from_package` is added, the default value is set to false, so for current user, they will get below diff when running the plan but they won't lose the `WEBSITE_RUN_FROM_PACKAGE` in `app_setting` as we set the value back
```
~ resource "azurerm_windows_function_app" "test" {
        id                                = "/subscriptions/xxx/resourceGroups/xiaxin-func-deploy-rg/providers/Microsoft.Web/sites/xiaxin-func-deploy-windows"
        name                              = "xiaxin-func-deploy-windows"
        tags                              = {}
      ~ website_run_from_package          = true -> false
        # (23 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

In this solution, user doesn't need to use the ignore change for `WEBSITE_RUN_FROM_PACKAGE` as they can explicitly set the website_run_from_package to true. When terraform reads the instance, it will check app_setting to see if `WEBSITE_RUN_FROM_PACKAGE` is there then set the property `website_run_from_package` to `true`.

2023-05-29 03:18 UTC, xiaxyi commented
Example usage:
```
resource "azurerm_linux_function_app" "test" {
    name = "functuion_name"
    resource_group_name = "rg_name"
    location = "east us"
    service_plan_id = "service_plan_id"
    storage_account_name = "saaccount"
    
    website_run_from_package = true
    site_config{
        application_stack {
          dotnet_version = "6.0"
        }
    }

    app_settings = {
      "terraformkey" = "terraformvalue"
    }
}
```

2023-06-29 12:16 UTC, jackofallops requested changes
Hi @xiaxyi - Thanks for this, it's looking mostly good, just a few comments below. If you can take a look, we can continue review. Are you able to do any manual testing for this since we're relying on an external change to know this works?

Thanks

2023-06-29 12:16 UTC, jackofallops commented on website/docs/d/linux_function_app.html.markdown
> +* `website_run_from_package` - Does the Function App deployed via a package file?
```suggestion
* `website_run_from_package` - Is the Linux Function App deployed via a package file? 
```

2023-06-29 12:16 UTC, jackofallops commented on website/docs/d/windows_function_app.html.markdown
> +* `website_run_from_package` - Does the Function App deployed via a package file?
```suggestion
* `website_run_from_package` - Is the Windows Function App deployed via a package file?
```

2023-06-29 12:16 UTC, jackofallops commented on website/docs/r/linux_function_app.html.markdown
> +* `website_run_from_package` - (Optional) Does the function App deployed from a package file? Defaults to `false`.
```suggestion
* `website_run_from_package` - (Optional) Should the Linux Function App be deployed from a package file? Defaults to `false`.
```

2023-06-29 12:16 UTC, jackofallops commented on website/docs/r/linux_function_app.html.markdown
> +~> **Note:** Using this value requires either `WEBSITE_RUN_FROM_PACKAGE=1` or `SCM_DO_BUILD_DURING_DEPLOYMENT=true` to be set on the App in `app_settings`. For Linux function app running in consumpti
```suggestion
~> **Note:** Using this value requires either `WEBSITE_RUN_FROM_PACKAGE=1` or `SCM_DO_BUILD_DURING_DEPLOYMENT=true` to be set on the App in `app_settings`, or the `website_run_from_package` property to be set to `true`. For Linux Function Apps running in a Consumption Service Plan, a URL pointing to the remote location of the package file to be run must be specified for  `WEBSITE_RUN_FROM_PACKAGE` in `app_setting`. Refer to the [Azure docs](https://learn.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies) for further details.
```

2023-06-29 12:16 UTC, jackofallops commented on website/docs/r/windows_function_app.html.markdown
> +* `website_run_from_package` - (Optional) Does the function App deployed from a package file? Defaults to `false`.
```suggestion
* `website_run_from_package` - (Optional) Should the Windows Function App be deployed from a package file? Defaults to `false`.
```

2023-06-29 12:16 UTC, jackofallops commented on internal/services/appservice/windows_function_app_resource.go
> +				appSettings[k] = utils.NormalizeNilableString(v)
The utils package is going to be gradually deprecated, so `pointer.From()` should be used here.
```suggestion
				appSettings[k] = pointer.From(v)
```

2023-06-29 12:16 UTC, jackofallops commented on internal/services/appservice/windows_function_app_resource.go
> +			}
as above
```suggestion
			if appSettingsResp.Properties != nil && pointer.From(appSettingsResp.Properties["WEBSITE_RUN_FROM_PACKAGE"]) != "" {
				state.WebsiteRunFromPackage = true
			}
```

2023-06-29 12:16 UTC, jackofallops commented on internal/services/appservice/windows_function_app_resource.go
> +			}
as above
```suggestion
			if appSettingsResp.Properties != nil && pointer.From(appSettingsResp.Properties["WEBSITE_RUN_FROM_PACKAGE"]) != "" {
				if state.AppSettings == nil {
					state.AppSettings = make(map[string]string)
				}
				state.WebsiteRunFromPackage = true
				state.AppSettings["WEBSITE_RUN_FROM_PACKAGE"] = *appSettingsResp.Properties["WEBSITE_RUN_FROM_PACKAGE"]
			}
```

2023-07-12 08:55 UTC, xiaxyi commented
Thanks @jackofallops for the code review. I updated the code per your suggestion.

I did the tests about external deployment to function app and the `WEBSITE_RUN_FROM_PACKAGE` will be added during the deployment. Is this the manual tests you were referring to?

2023-09-07 09:36 UTC, dotSource-bke commented
Hello @jackofallops, @xiaxyi,
is there a reason why the pull request is stuck for such a long time at that stage of development? If so, please provide an update so it is possible to plan when a provider that is fixed will be available. Otherwise, please just fix this painful issue.

2023-09-11 07:46 UTC, jackofallops requested changes
Hi @xiaxyi - In re-review, I think the problem here is actually a bug here: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/linux_function_app_resource.go#L1291-L1295
This will be preventing the `ignore_change` from working I believe. Removing this handling  will allow users to correctly `ignore_change` which would be the desirable behaviour here, rather than introducing further configuration / complication.  

Specifically, if these lines are removed, the following will correctly step over the external changes to the `app_settings` map:

```terraform
lifecycle {
    ignore_changes = [ app_settings["WEBSITE_RUN_FROM_PACKAGE"] ]
  }
```
(note: this is the correct way to reference the map item, not the dotted notation - it may be worth also including this in the docs?)

This already works for the `azurerm_windows_function_app` resource (I just tested it by hand)

If you can take a look and update the PR accordingly, I think this should be able to go in.

Thanks!

2023-12-07 04:56 UTC, katbyte commented
@xiaxyi as this has been untouched for ~3 months i am going to close it out. Please do feel free to reopen it once you are ready to continue working on it. thanks!

2023-12-07 04:56 UTC, closed without merging