`azurerm_express_route_port_authorization`: add a lock when create/update/delete authorization of express route port
hashicorp/terraform-provider-azurerm pull request #21959
Opened 2023-05-30 04:29 UTC by wuxu92

The API permits only one create/update/delete operation on the same express route port resource. Or the API will reponse error as below. this was found in the failure of AccTest [TestAccExpressRoutePortAuthorization_multiple](https://ci-oss.hashicorp.engineering/test/4949330622923002834?currentProjectId=TerraformOpenSource_TerraformProviders_AzureRMPublic&branch=%3Cdefault%3E)

```
Error: deleting Express Route Port Authorization: (Authorization Name "acctestauth1230529023842741531" / Express Route Port Name "acctestERP-230529023842741531" / Resource Group "acctestRG-230529023842741531"): 
network.ExpressRoutePortAuthorizationsClient#Delete: Failure sending request: StatusCode=0 -- 
Original Error: autorest/azure: Service returned an error. Status=<nil> Code="AnotherOperationInProgress" Message="Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: 
https://management.azure.com/subscriptions/*******/providers/Microsoft.Network/locations/eastus2/operations/2c22b9e6-04c1-4b53-b5b3-4f6513d2ccd6?api-version=2022-07-01." Details=[]
```

AccTest Result:

```
=== RUN   TestAccExpressRoutePortAuthorization_multiple
--- PASS: TestAccExpressRoutePortAuthorization_multiple (262.05s)
PASS
````

2023-05-31 01:22 UTC, mbfrahry requested changes
Should we also lock `azurerm_express_route_port` during Create/Update/Delete?

2023-05-31 02:27 UTC, wuxu92 commented
@mbfrahry  `azurerm_express_route_port` does not need a lock when tested in my local machine.

2023-06-01 22:37 UTC, mbfrahry approved these changes
LGTM!

2023-06-01 22:37 UTC, mbfrahry commented
Thanks for adding that lock @wuxu92

2023-06-01 22:37 UTC, merged