`azurerm_sentinel_data_connector_microsoft_threat_intelligence`: deprecate `bing_safety_phishing_url_lookback_date`
hashicorp/terraform-provider-azurerm pull request #21954
Opened 2023-05-29 06:54 UTC by ziyeqf

deprecate it as API no longer support it.

test
---
```
❯ tftest sentinel TestAccSentinelDataConnectorMicrosoftThreatIntelligence
=== RUN   TestAccSentinelDataConnectorMicrosoftThreatIntelligence_basic
=== PAUSE TestAccSentinelDataConnectorMicrosoftThreatIntelligence_basic
=== RUN   TestAccSentinelDataConnectorMicrosoftThreatIntelligence_complete
=== PAUSE TestAccSentinelDataConnectorMicrosoftThreatIntelligence_complete
=== CONT  TestAccSentinelDataConnectorMicrosoftThreatIntelligence_basic
=== CONT  TestAccSentinelDataConnectorMicrosoftThreatIntelligence_complete
--- PASS: TestAccSentinelDataConnectorMicrosoftThreatIntelligence_basic (138.94s)
--- PASS: TestAccSentinelDataConnectorMicrosoftThreatIntelligence_complete (187.07s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/sentinel      187.119s
```

2023-05-31 01:28 UTC, mbfrahry requested changes
Nearly there, I just believe there is duplicate code that can be removed

2023-05-31 01:28 UTC, mbfrahry commented on internal/services/sentinel/sentinel_data_connector_microsoft_threat_intelligence.go
> +			Deprecated:   "This field is deprecated and will be removed in version 4.0 of the AzureRM Provider.",
Is the block here and [here](https://github.com/hashicorp/terraform-provider-azurerm/pull/21954/files#diff-e55bd9e1d873da0245e2ff8bc94d56aa97e053a58387ba539dd75b8e0bc81c0eR78) the same? if so, we can remove this block in favor of the block down below.

2023-06-06 08:44 UTC, ziyeqf commented
have changed `microsoft_emerging_threat_feed_lookback_date` from `optional` to `required`, it seems to be breaking change but it's indeed required by service, without it this resource could not be created

2023-06-06 22:11 UTC, mbfrahry requested changes
Nearly there but we can sidestep the breaking change through the FourPointOh flag

2023-06-06 22:11 UTC, mbfrahry commented on internal/services/sentinel/sentinel_data_connector_microsoft_threat_intelligence.go
> +			Required:     true,
As this is a breaking change, let's set Required/Optional by the `FourPointOh` feature flag. We also need to update the docs to say this is Required now

2023-06-07 16:19 UTC, merged