`azurerm_public_ip`: fix acctest `TestAccPublicIpStatic_importIdError` for new ID parse
hashicorp/terraform-provider-azurerm pull request #21965
Opened 2023-05-30 11:27 UTC by wuxu92

<del>
## TestAccVirtualNetworkGatewayConnection_natRuleIds
The API will response a non-empty `shared_key` even not set in create request, so we have to set it as `Computed: true`. Or the AccTest will failed as below:

```
=== CONT  TestAccVirtualNetworkGatewayConnection_natRuleIds
testcase.go:110: Step 1/2 error: After applying this test step, the plan was not empty.
stdout:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
# azurerm_virtual_network_gateway_connection.test will be updated in-place
~ resource "azurerm_virtual_network_gateway_connection" "test" {
id                                 = "/subscriptions/*******/resourceGroups/acctestRG-230522061759601363/providers/Microsoft.Network/connections/acctestvnetgwconn-230522061759601363"
name                               = "acctestvnetgwconn-230522061759601363"
- shared_key                         = (sensitive value)
# (15 unchanged attributes hidden)
}
Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccVirtualNetworkGatewayConnection_natRuleIds (518.55s)
FAIL
```
</del>

## TestAccPublicIpStatic_importIdError
Update `github.com/hashicorp/terraform-plugin-sdk/v2` to `v2.26.1`. importer validate response a different error format. so have to update the ExpectError in AccTest. 
```
testcase.go:110: Step 2/2 error running import, expected an error with pattern (Error: parsing Resource ID), no match on: exit status 1
Error: ID was missing the `publicIPAddresses` element
--- FAIL: TestAccPublicIpStatic_importIdError (94.13s)
```

Now test pass:
```
=== CONT  TestAccPublicIpStatic_importIdError
--- PASS: TestAccPublicIpStatic_importIdError (253.85s)
PASS
```

2023-05-31 01:16 UTC, mbfrahry requested changes
Hey @wuxu92, it looks like we're still having issues with locking

```
=== CONT  TestAccVirtualNetworkGatewayConnection_updatingSharedKey
Error: deleting Network Gateway Connection: (Connection Name "acctest-230530113720653145" / Resource Group "acctestRG-230530113720653145"): network.VirtualNetworkGatewayConnectionsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="AnotherOperationInProgress" Message="Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: b4d4ecf8-b71c-40d6-afc6-b772c712873d." Details=[]
Error: deleting Network Gateway Connection: (Connection Name "acctest-230530113720654446" / Resource Group "acctestRG-230530113720654446"): network.VirtualNetworkGatewayConnectionsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="AnotherOperationInProgress" Message="Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: dae103ce-21c5-4d7e-b6cb-d31b5f7e5a4d." Details=[]
```

2023-05-31 01:16 UTC, mbfrahry commented on website/docs/r/virtual_network_gateway_connection.html.markdown
> +* `shared_key` - The shared IPSec key. A key could be provided if a Site-to-Site, VNet-to-VNet or ExpressRoute connection is created.
We can remove this as `shared_key` is embedded in a block up above

2023-05-31 07:35 UTC, wuxu92 commented
@mbfrahry the root cause of deleting failure is a swagger issue I have open an issuue to track it. https://github.com/Azure/azure-rest-api-specs/issues/24232 the lock here is helpless and have removed.

2023-06-01 07:15 UTC, wuxu92 commented
@mbfrahry the root cause of deleting failure is a swagger issue. I have open an issuue to track it. [Azure/azure-rest-api-specs/issues/24232](https://github.com/Azure/azure-rest-api-specs/issues/24232). locking here is helpless and has been removed. 

Since the LRO polling not work as expected, I simply added a `time.Sleep` to wait it done (seems no other way for us before the issue fixing?). The AccTest passed in several local runs. WDYT?

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/2633022/1fe8986a-0e66-48f6-b5a9-bda5e3e3a7a5)

2023-06-26 20:08 UTC, katbyte requested changes

2023-06-26 20:08 UTC, katbyte commented on internal/services/network/virtual_network_gateway_connection_resource.go
> +		time.Sleep(time.Second * 10)
we should never rely on a sleep. please do a statewait instead to poll for when the create/update is actually finished

2023-08-07 12:59 UTC, stephybun commented
@wuxu92 any updates?

2023-08-18 03:05 UTC, wuxu92 commented
@stephybun sorry for my delay response. Just update this only fix `TestAccPublicIpStatic_importIdError`. Thanks!

2023-08-18 05:35 UTC, stephybun approved these changes
Thanks @wuxu92 LGTM 🥟

2023-08-18 05:35 UTC, merged