`azurerm_spring_cloud_gateway` - support for the `client_auth` property
hashicorp/terraform-provider-azurerm pull request #22016
Opened 2023-06-02 02:41 UTC by ms-henglu

2023-06-09 00:49 UTC, katbyte requested changes

2023-06-09 00:49 UTC, katbyte commented on website/docs/r/spring_cloud_gateway.html.markdown
> +* `client_auth` - (Optional) A `client_auth` block as defined below.
could we make this 
```suggestion
* `client_authentication` - (Optional) A `client_auth` block as defined below.
```
to match other resources in the provider?

2023-06-09 01:50 UTC, ms-henglu commented
Thanks @katbyte , I've renamed this field as suggested.

2023-06-13 00:46 UTC, katbyte approved these changes
LGTM 🔐

2023-06-13 00:46 UTC, merged