add option to set ManagedBy field.
hashicorp/terraform-provider-azurerm pull request #22012
Opened 2023-06-01 18:08 UTC by rna-afk

Adding the option to set the ManagedBy field to
the `azure_resource_group` resource.

2023-06-05 12:55 UTC, rna-afk commented
We are just looking to use this field for some automated system that we have running in the background that just checks the field and installs a few RBAC resources into the resource group if the right value is set. The almost immutable nature of `managedby` could be useful here.

2023-06-20 12:22 UTC, stephybun requested changes
Thanks for this PR @rna-afk. Looking into this it appears this field can be set. 

In addition to the comments left below we need to add an additional acceptance test for this property and also to update the documentation. Once those points have been resolved we can get this merged. Thanks!

2023-06-20 12:22 UTC, stephybun commented on internal/services/resource/resource_group_data_source.go
> +			"managedBy": managedby.SchemaManagedByOptional(),
Provider properties are all lowercase and snake cased, so can we rename this to `managed_by` and also in-line the schema. Additionally all properties in data sources that aren't required should only be set to Computed.
```suggestion
			"managed_by": {
				Type:     pluginsdk.TypeString, 
				Computed: true,
			},
```

2023-06-20 12:22 UTC, stephybun commented on internal/managedby/schema.go
> +package managedby
Since we're in-lining the schema we can remove this file.

2023-06-20 12:22 UTC, stephybun commented on internal/services/resource/resource_group_data_source.go
> +	d.Set("managedBy", *resp.ManagedBy)
We need to nil check this
```suggestion
	managedBy := ""
	if v := resp.ManagedBy; v != nil {
		managedBy = *v
	}
	d.Set("managedBy", managedBy)
```

2023-06-20 12:22 UTC, stephybun commented on internal/services/resource/resource_group_resource.go
> +			"managedBy": managedby.SchemaManagedByOptional(),
```suggestion
			"managed_by": {
				Type:     pluginsdk.TypeString, 
				Optional: true,
				ValidateFunc: validation.StringIsNotEmpty,
			},
```

2023-06-20 12:22 UTC, stephybun commented on internal/services/resource/resource_group_resource.go
> +	}
```suggestion
```

2023-06-20 12:22 UTC, stephybun commented on internal/services/resource/resource_group_resource.go
>  	}
```suggestion
		Location:  utils.String(location),
		Tags:      tags.Expand(t),
	}
	
	if v := d.Get("managed_by"); v != "" {
		parameters.ManagedBy = pointer.To(v)
	}
```

2023-06-20 12:22 UTC, stephybun commented on internal/services/resource/resource_group_resource.go
> +	d.Set("managedBy", resp.ManagedBy)
```suggestion
	managedBy := ""
	if v := resp.ManagedBy; v != nil {
		managedBy = *v
	}
	d.Set("managedBy", managedBy)
```

2023-06-21 08:48 UTC, stephybun requested changes
Thanks @rna-afk, one more comment and the docs still need to be updated.

2023-06-21 08:48 UTC, stephybun commented on internal/services/resource/resource_group_resource.go
> +	d.Set("managedBy", managedBy)
```suggestion
	d.Set("managed_by", managedBy)
```

2023-06-23 11:54 UTC, rna-afk commented
Thanks @stephybun, added docs.

2023-06-28 07:27 UTC, jackofallops requested changes
Thanks for this contribution @rna-afk 

I've left a few comments below if you can take a look, then we can get this tested.

Thanks!

2023-06-28 07:27 UTC, jackofallops commented on website/docs/r/resource_group.html.markdown
> +* `managed_by` - (Optional) TODO.
TODO here
```suggestion
* `managed_by` - (Optional) The ID of the resource or application that manages this Resource Group.
```

2023-06-28 07:27 UTC, jackofallops commented on website/docs/r/resource_group.html.markdown
> +In addition to the Arguments listed above - the following Attributes are exported:
```suggestion
In addition to the Arguments listed above - the following Attributes are exported:
```

2023-06-28 14:12 UTC, stephybun approved these changes
Thanks for this @rna-afk LGTM 🌻

2023-06-28 14:12 UTC, merged