`network_interface_security_group_association` - Allow network_security_group_id to be case insensitive
hashicorp/terraform-provider-azurerm pull request #22070
Opened 2023-06-07 12:44 UTC by rifelpet

This partially addresses the wider-spread issue documented in #20138 

The Azure API will inconsistently return resource IDs with changes to casing, causing terraform plans to incorrectly force-recreate resources:

```
  # azurerm_network_interface_security_group_association.this must be replaced
-/+ resource "azurerm_network_interface_security_group_association" "this" {
      ~ id                        = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-resource-group/providers/Microsoft.Network/networkInterfaces/my-network-interface|/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-resource-group/providers/Microsoft.Network/networkSecurityGroups/my-network-security-group" -> (known after apply)
      ~ network_security_group_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MY-RESOURCE-GROUP/providers/Microsoft.Network/networkSecurityGroups/MY-NETWORK-SECURITY-GROUP" -> "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-resource-group/providers/Microsoft.Network/networkSecurityGroups/my-network-security-group" # forces replacement
        # (1 unchanged attribute hidden)
    }
``` 

The casing changes is intention by Azure according to [their docs](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules):

> Resource and resource group names are case-insensitive unless specifically noted in the valid characters column.
> 
> When using various APIs to retrieve the name for a resource or resource group, the returned value may have different casing than what you originally specified for the name. The returned value may even display different case values than what is listed in the valid characters table.
> 
> Always perform a case-insensitive comparison of names.

This fix correctly allows plans to correctly report a no-op.

The same behavior can be seen with the `az` cli:

```
$ az network nic show --ids /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-resource-group/providers/Microsoft.Network/networkInterfaces/my-network-interface | jq .networkSecurityGroup
{
  "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MY-RESOURCE-GROUP/providers/Microsoft.Network/networkSecurityGroups/MY-NETWORK-SECURITY-GROUP",
  "resourceGroup": "MY-RESOURCE-GROUP"
}

$ az network nsg show --ids /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-resource-group/providers/Microsoft.Network/networkSecurityGroups/my-network-security-group | jq -r '. | "\(.id) \(.resourceGroup)"'
/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MY-RESOURCE-GROUP/providers/Microsoft.Network/networkSecurityGroups/MY-NETWORK-SECURITY-GROUP MY-RESOURCE-GROUP

$ az group show --subscription 00000000-0000-0000-0000-000000000000 --resource-group my-resource-group |
jq .name
"my-resource-group" # NOTE: the resource group name is lowercase here but uppercase in the earlier API responses
```

NOTE: this is probably worthy of a more generic solution that applies to all resource types but I wanted to at least start the dialogue here

2023-06-07 23:48 UTC, mbfrahry requested changes
Hey @rifelpet, as you noted this happens quite often in Azure. We've moving towards using our own ids that match the case that users are passing in so that we don't have to worry about the inconsistency on Azure's side. 

As such, we can get around this by using the back half of the [splitId](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/network/network_interface_security_group_association_resource.go#L134) and parse it similar to how we are parsing the [nic_id](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/network/network_interface_security_group_association_resource.go#L134). Before we set that though, we should confirm that [props.NetworkSecurityGroup.ID](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/network/network_interface_security_group_association_resource.go#L169) matches the parsed id except for casing. If something is different other than casing, we should set `props.NetworkSecurityGroup.ID` and if not, we can just set the parsed Id. 

It's wonky but unfortunately, we have to work around Azure's inconsistency here. 

Let me know if that all makes sense!

2023-06-14 21:50 UTC, rifelpet commented
@mbfrahry Thanks, that makes sense. I believe I've implemented what you've asked, please take another look

2023-06-27 05:05 UTC, rifelpet commented
Gentle ping on this @mbfrahry, any chance you can take another look?

2023-07-10 20:54 UTC, rifelpet commented
@tombuildsstuff I see you assigned this PR to yourself, any chance you can take a look?

2023-12-12 15:35 UTC, tombuildsstuff commented
hi @rifelpet

Apologies for the delay getting back to you on this one.

Unfortunately there's multiple conflicting sources around the expected behaviour for Resource ID casing - since the guidance has differed over the years - resulting in different Azure APIs implementing this in different manners.

The document referenced above is one such source, however having chatted at length (and raised multiple issues) about this issue with the ARM Team, we've consistently been told that:

1. Resource IDs are supposed to be _case insensitive_ in Requests to the API and _case sensitive_ in Responses from the API.
2. Constants/Enums are supposed to be _case-insensitive_ in Requests to the API and _case sensitive_ in Responses from the API.
3. The Keys within each Resource ID (e.g. `subscriptions`, `resourceGroups`, `providers` and `virtualMachines`) are supposed to be `camelCased` (rather than `lowercased` etc).

For example this is from August 2023:

> Azure has gotten into so much trouble for trying to be case-insensitive. Almost all programming languages are case-sensitive, JSON properties are case-sensitive, Linux commands and file system is case-sensitive. Azure should be case-sensitive too.

Unfortunately the result of this is that different Azure APIs implement this behaviour in different manners - and in some APIs specifying the incorrect Key for a Resource ID can lead to the Resource being provisioned, but unusable.

Ultimately this means that from Terraform's perspective we need to ensure we're providing the correct value to the API - but equally that we're normalizing the values coming back from the Azure API to workaround this.

Whilst this PR goes some way towards doing that, unfortunately whilst we've previously made fields case-insensitive as a workaround to this - we've realised this leads to larger issues (since it requires breaking configuration changes down the line to users who may be unaware of this issue) - and as such is something we're moving away from.

---

We're currently working on migrating the Provider from using `Azure/azure-sdk-for-go` to using `hashicorp/go-azure-sdk` - which exposes far richer Resource ID types than we have available today.

The richer type information available in the new SDK enables us to fix this information in a broader manner (and also some other issues, [example](https://github.com/hashicorp/go-azure-helpers/issues/189)) - consistently across the Provider, since this is a breaking behavioural change.

Whilst we're a good way through the migration, ultimately we can't proceed with this work until we're fully migrated over - as such whilst we're aware this is an issue unfortunately we're in a bit of a holding pattern for this one at the moment.

---

Whilst I appreciate that this remains a pain point in the interim - for the moment it should be possible to workaround this issue either using `ignore_changes` on this value, or by matching the casing being returned for this field.

Since we're looking to fix this issue in a more consistent manner across the Provider I'd like to thank you for this contribution, however, I'm going to close this issue for the moment.

Thanks!

2023-12-12 15:35 UTC, closed without merging

2024-02-15 03:00 UTC, gogonaft commented
We started experiencing the same issue with RG names being inconsistently handled for VNET resources related changes such as route table or nsg assignments, vm put to subnet, etc. It's causing replacements of existing resources.

I've seen in recent build(3.90) you've fixed "serverFarms" issue, but RG name casing is still there, still old sdk in use. Imo, this needs to be addressed(worked around) in current SDK to avoid having ignore_changes everywhere in TF code.

`  # azurerm_subnet_route_table_association.vnet-rt-subnet1 must be replaced
      resource "azurerm_subnet_route_table_association" "vnet-rt-subnet1" {
            ~ id             = "/subscriptions/12345-1111-222-333-4444444/resourceGroups/abc-home-eastus-hub/providers/Microsoft.Network/virtualNetworks/vnet1/subnets/snet-1" -> (known after apply)
            ~ subnet_id      = "/subscriptions/12345-1111-222-333-4444444/resourceGroups/abc-HOME-eastus-HUB/providers/Microsoft.Network/virtualNetworks/vnet1/subnets/snet-1"  ->
                               "/subscriptions/12345-1111-222-333-4444444/resourceGroups/abc-home-eastus-hub/providers/Microsoft.Network/virtualNetworks/vnet1/subnets/snet-1" # forces replacement
    }`