`azurerm_site_recovery_replicated_vm`: handle casing issue & update validate func
hashicorp/terraform-provider-azurerm pull request #22101
Opened 2023-06-09 09:31 UTC by ziyeqf

fix #22075

test
---
the failed ones are also failing on `main` branch so I assume they do not block this PR
<img width="504" alt="Screenshot 2023-06-15 at 10 31 50" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/51212351/de578bb5-ec50-409a-907f-efe6d0295d97">

2023-06-09 09:39 UTC, tombuildsstuff requested changes
hey @ziyeqf 

Thanks for this PR - can we update this to use the `ParseXXXInsensitively` methods instead?

Thanks!

2023-06-09 09:39 UTC, tombuildsstuff commented on internal/services/recoveryservices/site_recovery_replicated_vm_resource.go
>  							DiffSuppressFunc: suppress.CaseDifference,
```suggestion
```

2023-06-09 09:39 UTC, tombuildsstuff commented on internal/services/recoveryservices/site_recovery_replicated_vm_resource.go
> +		}
can we use the `ParseXXXInsensitively` functions for this instead

2023-06-09 09:39 UTC, tombuildsstuff commented on internal/services/recoveryservices/site_recovery_replicated_vm_resource.go
> +			}
(same here)

2023-06-17 17:30 UTC, stephybun requested changes

2023-06-17 17:30 UTC, stephybun commented on internal/services/recoveryservices/site_recovery_replicated_vm_resource.go
> +				return fmt.Errorf("parsing recovery_fabric_id %s: %+v", fabricId, err)
The ID parsers already return detailed error messages so can we simplify all the error messages to 
```suggestion
				return err
```

2023-06-23 18:19 UTC, prashantshetage commented
I am facing the same issue with Terrafom v1.5.0 and azurerm v.3.61.0

2023-06-26 07:53 UTC, stephybun requested changes
Tests are showing up a build failure:
```
# github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices
./site_recovery_replicated_vm_resource.go:766:48: undefined: networkParse.VirtualNetworkIDInsensitively
./site_recovery_replicated_vm_resource.go:776:45: undefined: networkParse.VirtualNetworkIDInsensitively
Process exited with code 1
```

2023-06-26 08:09 UTC, ziyeqf commented
> Tests are showing up a build failure:
> 
> ```
> # github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices
> ./site_recovery_replicated_vm_resource.go:766:48: undefined: networkParse.VirtualNetworkIDInsensitively
> ./site_recovery_replicated_vm_resource.go:776:45: undefined: networkParse.VirtualNetworkIDInsensitively
> Process exited with code 1
> ```

The VirtualNetworkId function was re-located to `commonids` package on `main` branch... just updated

2023-06-26 08:15 UTC, ziyeqf commented
> Tests are showing up a build failure:
> 
> ```
> # github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices
> ./site_recovery_replicated_vm_resource.go:766:48: undefined: networkParse.VirtualNetworkIDInsensitively
> ./site_recovery_replicated_vm_resource.go:776:45: undefined: networkParse.VirtualNetworkIDInsensitively
> Process exited with code 1
> ```

The network parse functions were re-located to `commonids` package on `main` branch... just updated code and triggered a test on TC

2023-06-27 08:56 UTC, stephybun commented
@ziyeqf can you resolve the conflicts please?

2023-06-28 06:38 UTC, stephybun approved these changes
Thanks @ziyeqf LGTM 🍓

2023-06-28 06:38 UTC, merged