Mark ip_configuration as Required
hashicorp/terraform-provider-azurerm pull request #22154
Opened 2023-06-13 13:14 UTC by CiucurDaniel

This PR fixes the issue: [Attribute "ip_configuration" should not be marked as (Optional) #22152](https://github.com/hashicorp/terraform-provider-azurerm/issues/22152)

Fixes #22152

2023-06-13 14:38 UTC, catriona-m requested changes
Hi @CiucurDaniel thanks for spotting this. It looks like this also needs updated in the schema here too: https://github.com/hashicorp/terraform-provider-azurerm/blob/64a9d39b460c419e396c3473b1f210180a1c7f58/internal/services/network/bastion_host_resource.go#L69 . Would it be possible to do this as part of this fix too? Thanks!

2023-06-13 14:39 UTC, CiucurDaniel commented
Sure, doing it now.

2023-06-16 02:44 UTC, katbyte commented on internal/services/network/bastion_host_resource.go
> +				Optional: false,
instead of changing optional to false we should use `Required:     true`
```suggestion
				Required: true,
```

2023-06-16 07:56 UTC, catriona-m approved these changes
Thanks @CiucurDaniel LGTM!

2023-06-16 08:22 UTC, merged

2023-06-16 08:45 UTC, CiucurDaniel commented
Thank you as well! @catriona-m 😄