`azurerm_kubernetes_cluster` - add support for `node_os_channel_upgrade`
hashicorp/terraform-provider-azurerm pull request #22187
Opened 2023-06-15 14:20 UTC by stephybun

Tests are still running.

Superseded #21386 
Related to #20171

2023-06-15 16:53 UTC, mbfrahry approved these changes
LGTM!

2023-06-15 21:52 UTC, mbfrahry requested changes
JK, I take it back. Almost there with a minor addition to fix an existing test

2023-06-15 21:52 UTC, mbfrahry commented on internal/services/containers/kubernetes_cluster_resource.go
> +		if autoChannelUpgrade == string(managedclusters.UpgradeChannelNodeNegativeimage) && nodeOsChannelUpgrade != string(managedclusters.NodeOSUpgradeChannelNodeImage) {
Looks like this wants to be 
```suggestion
		if autoChannelUpgrade == string(managedclusters.UpgradeChannelNodeNegativeimage) && string(managedclusters.NodeOSUpgradeChannelNodeImage) != "" && nodeOsChannelUpgrade != string(managedclusters.NodeOSUpgradeChannelNodeImage) {
```

to get around 
```
=== CONT  TestAccKubernetesCluster_upgradeChannel
testcase.go:110: Step 5/10 error: Error running apply: exit status 1
Error: `node_os_channel_upgrade` must be set to `NodeImage` if `automatic_channel_upgrade` is set to `node-image`
with azurerm_kubernetes_cluster.test,
on terraform_plugin_test.tf line 22, in resource "azurerm_kubernetes_cluster" "test":
22: resource "azurerm_kubernetes_cluster" "test" {
--- FAIL: TestAccKubernetesCluster_upgradeChannel (795.62s)
```

2023-06-20 09:14 UTC, stephybun commented
Thanks for the review @mbfrahry! Relevant tests are passing so this should be good to merge.

2023-06-20 09:14 UTC, merged

2023-06-26 10:37 UTC, stevehipwell commented
@stephybun @mbfrahry this is a breaking change for anyone who was setting `automatic_channel_upgrade` to `node-image` as if they upgrade the provider version to `v3.6.0` or greater the once working code will fail. If you really can't default `node_os_channel_upgrade` to `NodeImage` in the case where it's not explicitly set (I have no idea why not) then this code change should have triggered a SemVer major release.

Ideally this can be fixed in a patch release ASAP?