`azurerm_site_recovery_replication_recovery_plan`: limit set `replicated_protected_items` for `Shutdown` type `recovery_group`
hashicorp/terraform-provider-azurerm pull request #22281
Opened 2023-06-26 07:05 UTC by ziyeqf

fix #22258

2023-06-27 08:50 UTC, stephybun requested changes
Can we add a test to replicate the issue and validate that this indeed fixes it?

2023-06-27 08:50 UTC, stephybun commented on website/docs/r/site_recovery_replication_recovery_plan.html.markdown
> +* `replicated_protected_items` - (Optional) (required) one or more id of protected VM. It must not be specified when `type` is `Shutdown`.
Is this property Optional or Required?

```suggestion
* `replicated_protected_items` - (Optional) (required) One or more protected VM IDs. It must not be specified when `type` is `Shutdown`.
```

2023-06-28 03:55 UTC, ziyeqf commented
As there is no code changes in resource in this commit, just run the specified test
---
```
❯ tftest recoveryservices TestAccSiteRecoveryReplicationRecoveryPlan_wrongSettings
=== RUN   TestAccSiteRecoveryReplicationRecoveryPlan_wrongSettings
=== PAUSE TestAccSiteRecoveryReplicationRecoveryPlan_wrongSettings
=== CONT  TestAccSiteRecoveryReplicationRecoveryPlan_wrongSettings
--- PASS: TestAccSiteRecoveryReplicationRecoveryPlan_wrongSettings (3786.00s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices      3786.049s
```

2023-06-28 09:15 UTC, ziyeqf commented
just updated code and triggered a test on TC, will update the result here.

2023-06-29 03:08 UTC, ziyeqf commented
<img width="594" alt="Screenshot 2023-06-29 at 11 08 46" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/51212351/b6ca1893-8a95-422e-b2fe-d35e0277b012">

2023-06-29 07:56 UTC, stephybun approved these changes
Thanks @ziyeqf LGTM 👍

2023-06-29 07:56 UTC, merged