azurerm_kubernetes_cluster - Add support for upgrade settings such as `IgnoreKubernetesDeprecations`
hashicorp/terraform-provider-azurerm pull request #22325
Opened 2023-06-29 14:52 UTC by seddarj

According to https://learn.microsoft.com/en-us/azure/aks/upgrade-cluster?tabs=azure-cli#bypass-validation-to-ignore-api-changes, it's possible to bypass validation to ignore API changes that would break some existing behavior in the cluster.

For instance, upgrading to 1.26, removes the HPA `v2beta2` API version which workloads (like e.g. Datadog) might be querying. Azure detects this usage and prevents the upgrade to 1.26 in normal conditions.

This PR adds support for those upgrade settings attributes at the cluster resource level.

fixes #21984

2023-07-06 23:29 UTC, katbyte requested changes
Thanks @seddarj , looks like we have a test failure:

```
------- Stdout: -------
=== RUN   TestAccKubernetesCluster_standardLoadBalancerProfileWithPortAndTimeout
=== PAUSE TestAccKubernetesCluster_standardLoadBalancerProfileWithPortAndTimeout
=== CONT  TestAccKubernetesCluster_standardLoadBalancerProfileWithPortAndTimeout
    testcase.go:113: Step 1/1 error: Error running pre-apply refresh: exit status 1
        
        Error: failed to read schema for azurerm_resource_group.test in registry.terraform.io/hashicorp/azurerm: provider registry.terraform.io/hashicorp/azurerm has invalid schema for managed resource type "azurerm_kubernetes_cluster", which is a bug in the provider: "2 errors occurred:\n\t* upgrade_settings.control_plane_upgrade_overrides: cannot set both Computed and Required\n\t* upgrade_settings.until: cannot set both Computed and Required\n\n"
        
--- FAIL: TestAccKubernetesCluster_standardLoadBalancerProfileWithPortAndTimeout (3.49s)
FAIL
```

2023-10-30 07:50 UTC, fbjerggaard commented on internal/services/containers/kubernetes_cluster_resource.go
> +			"controle_plane_upgrade_overrides": *input.OverrideSettings.ControlPlaneOverrides,
`controle` should probably be `control`

2023-10-30 07:52 UTC, fbjerggaard commented on internal/services/containers/kubernetes_cluster_resource.go
> +			"controle_plane_upgrade_overrides": *input.OverrideSettings.ControlPlaneOverrides,
This is something that is occurring multiple times - it is not really consistent whether controle or control is used.

2024-06-20 06:10 UTC, stephybun commented
Closing since there's been no activity or response on this PR. It also looks like this would require significant re-work since the API spec for this feature has changed slightly.

2024-06-20 06:10 UTC, closed without merging