new resource `azurerm_graph_account`
hashicorp/terraform-provider-azurerm pull request #22334
Opened 2023-06-30 04:43 UTC by teowa

reference:
- [doc](https://learn.microsoft.com/en-us/graph/metered-api-setup?tabs=azurecloudshell#enable-an-application)
- [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/graphservicesprod/resource-manager/Microsoft.GraphServices/stable/2023-04-13/graphservicesprod.json)

2023-06-30 09:06 UTC, teowa commented on internal/services/graph/graph_account_resource_test.go
> +resource "azuread_application" "test" {
this resource is depend on an `azuread_application`, however through my local test the resource creation may fail occationally with error: `performing AccountsCreateAndUpdate: unexpected status 400 with error: BadRequest: The application was not found in this tenant.`. The service team told that this is hard to change and advices to use a predefined azure ad app, can we do this?

2023-07-03 02:59 UTC, teowa commented on internal/services/graph/graph_account_resource_test.go
> +  app_id              = azuread_application.test.application_id
this resource is depend on an `azuread_application`, however through my local test the resource creation may fail occationally with error even after the ad app is created: `performing AccountsCreateAndUpdate: unexpected status 400 with error: BadRequest: The application was not found in this tenant.`. The service team told that this is hard to change and advices to use a predefined azure ad app, can we do this?

2023-07-04 15:22 UTC, teowa commented
Hi @manicminer , thanks for reviewing this. I have modified the testcases, but we cannot create two graph account for  single ad application, so I have made the test running in serial.
```
TF_ACC=1 go test -v ./internal/services/graph -parallel 50 -test.run=TestAccGraph -timeout 1440m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccGraphAccount
=== RUN   TestAccGraphAccount/account
=== RUN   TestAccGraphAccount/account/requiresImport
=== RUN   TestAccGraphAccount/account/basic
=== RUN   TestAccGraphAccount/account/update
=== RUN   TestAccGraphAccount/account/complete
--- PASS: TestAccGraphAccount (586.13s)
    --- PASS: TestAccGraphAccount/account (586.13s)
        --- PASS: TestAccGraphAccount/account/requiresImport (150.75s)
        --- PASS: TestAccGraphAccount/account/basic (144.59s)
        --- PASS: TestAccGraphAccount/account/update (150.11s)
        --- PASS: TestAccGraphAccount/account/complete (140.68s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/graph 587.394s

```

2023-07-12 13:54 UTC, teowa commented
Hi @manicminer, kindly ping. The service team is asking for this.

2023-07-13 12:04 UTC, manicminer requested changes
Thanks @teowa, this mostly LGTM. If you can look at the comments below then this should be good to merge.

Tests look good for me:

<img width="1062" alt="Screenshot 2023-07-13 at 13 04 23" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/251987/4117c507-2fe2-47dd-8e12-7e5f67be5d30">

2023-07-18 08:54 UTC, merged