New Resource: `azurerm_key_vault_managed_hardware_security_module_role_definition` and `azurerm_key_vault_managed_hardware_security_module_role_assignment` for managed HSM
hashicorp/terraform-provider-azurerm pull request #22332
Opened 2023-06-30 03:08 UTC by wuxu92

> Draft for TC Test.

2023-11-07 07:18 UTC, wuxu92 commented on website/docs/r/key_vault_managed_hardware_security_module_role_definition.html.markdown
> +* `scope` - (Optional) Specify the scope of this role definition. Possible value is `/`. Defaults to `/`. Changing this forces a new KeyVault to be created.
Okay, I'm deleting this field. Additionally, the `assignable_scopes` field now only supports `/`, as noted in https://github.com/Azure/azure-rest-api-specs/issues/23045. Should I also remove its support and include the issue link in the source code for future reference?

2023-11-07 08:12 UTC, wuxu92 commented on internal/services/keyvault/key_vault_managed_hardware_security_module_role_definition_data_resource.go
> +			model.ResourceManagerId = pointer.From(result.ID)
Is this the parse/normalize function to use? https://github.com/hashicorp/terraform-provider-azurerm/blob/49bf0dc046bbb4fb3d2a8fe5ed1c9d0f89e55b4b/vendor/github.com/hashicorp/go-azure-sdk/resource-manager/authorization/2022-04-01/roledefinitions/id_scopedroledefinition.go#L53 . I have tried with it but the `ID()` method will append a `/` prefix the to role definidion id, and then the role assignment resource will complain that `Unkown role definition`. So, I'll leave it alone.

2023-11-24 00:59 UTC, katbyte requested changes

2023-11-24 00:59 UTC, katbyte commented on internal/services/keyvault/key_vault_managed_hardware_security_module_role_assignment_resource.go
> +			if err != nil {
lines can be combined

2023-11-24 00:59 UTC, katbyte commented on internal/services/keyvault/key_vault_managed_hardware_security_module_role_assignment_resource.go
> +var _ sdk.Resource = (*KeyVaultRoleAssignmentResource)(nil)
@wuxu92 you missed this

2023-11-24 00:59 UTC, katbyte commented on internal/services/keyvault/key_vault_managed_hardware_security_module_role_assignment_resource.go
> +type ManagedHSMRoleAssignmentModel struct {
shoudln't these all be
```suggestion
type KeyVaultManagedHSMRoleAssignmentModel struct {
```

2023-11-24 00:59 UTC, katbyte commented on internal/services/keyvault/key_vault_managed_hardware_security_module_role_assignment_resource_test.go
> +type KeyVaultRoleAssignmentResource struct{}
should this be something like
```suggestion
type KeyVaultManagedHSMRoleAssignmentResource struct{}
```

2023-11-24 00:59 UTC, katbyte commented on internal/services/keyvault/key_vault_managed_hardware_security_module_role_definition_resource.go
> +					},
@wuxu92 - please address this comment and add some validation here

2023-11-24 00:59 UTC, katbyte commented on internal/services/keyvault/key_vault_managed_hardware_security_module_role_definition_resource.go
> +			if err != nil {
these lines can be combined

2023-11-24 00:59 UTC, katbyte commented on internal/services/keyvault/key_vault_managed_hardware_security_module_role_definition_resource.go
> +			model.ResourceManagerId = pointer.From(result.ID)
@wuxu92 - please address this comment. we should always be parsing IDs and normalizing them to prevent casing issues

2023-11-24 00:59 UTC, katbyte commented on internal/services/keyvault/key_vault_managed_hardware_security_module_role_definition_resource.go
> +
```suggestion
```

2023-11-24 00:59 UTC, katbyte commented on website/docs/d/key_vault_managed_hardware_security_module_role_definition.html.markdown
> +* `scope` - (Optional) Specify the scope to retrieve the role definition. Defaults to `/`.
@wuxu92 - comments?

2023-11-24 00:59 UTC, katbyte commented on website/docs/r/key_vault_managed_hardware_security_module_role_definition.html.markdown
> +* `scope` - (Optional) Specify the scope of this role definition. Possible value is `/`. Defaults to `/`. Changing this forces a new KeyVault to be created.
if you deleted it why is it still in the comments?

2023-12-07 05:08 UTC, katbyte approved these changes
LGTM 🔐

2023-12-07 05:08 UTC, merged