New data source `azurerm_communication_service`
hashicorp/terraform-provider-azurerm pull request #22426
Opened 2023-07-08 06:56 UTC by myc2h6o

Close #21736

2023-07-08 08:22 UTC, myc2h6o commented
test result
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/10579712/f05bc0a3-07ed-44e8-924a-5f1f8e296751)

2023-07-10 11:26 UTC, tombuildsstuff requested changes
hey @myc2h6o 

Thanks for this PR - I've taken a look through and left some comments inline, but if we can fix those up then this should otherwise be good to go 👍 

Thanks!

2023-07-10 11:26 UTC, tombuildsstuff commented on internal/services/communication/communication_service_data_source.go
> +				return fmt.Errorf("listing keys for %s: %+v", id, err)
data sources should gracefully handle having limited permissions, so we shouldn't raise this error when there's a permissions error (presumably a 401?)

2023-07-10 11:26 UTC, tombuildsstuff commented on internal/services/communication/communication_service_data_source.go
> +				}
FWIW we can reduce this to:

```suggestion
				state.PrimaryConnectionString = pointer.From(model.PrimaryConnectionString)
				state.PrimaryKey = pointer.From(model.PrimaryKey)
				state.SecondaryConnectionString = pointer.From(model.SecondaryConnectionString)
				state.SecondaryKey = pointer.From(model.SecondaryKey)
```

2023-07-10 14:16 UTC, myc2h6o commented
@tombuildsstuff thanks for reviewing! I've updated the code to use `pointer.From`, and used a warning message to replace the error. Please take a look.

2023-07-10 14:16 UTC, myc2h6o commented
updated test result
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/10579712/5abb8fe1-7940-4c11-9ad7-82bb8758d4ce)

2023-07-12 07:11 UTC, tombuildsstuff approved these changes
LGTM - thanks for pushing those changes @myc2h6o

2023-07-12 07:12 UTC, merged