`azurerm_windows[linux]_web_app_[slot]` - add docker setting to `app_setting` block
hashicorp/terraform-provider-azurerm pull request #22484
Opened 2023-07-12 08:02 UTC by xiaxyi

Fixes
1. Since `app_setting` exists in two places, one is under `site_config` while the other is under `site`, current, when user sets the docker related settings in `site_config` such as `docker_registry_url`, `docker_registry_username` and `docker_registry_password`, these settings are not being updated correctly in `app_setting` under Site. The `app_setting` under `site_config` is not taking any effects...
2. handle provider crash due to nil map.

fix #22379 
fix #22436 
fix #22435

2023-08-10 13:52 UTC, jackofallops requested changes
Hi @xiaxyi - Thanks for this PR, I've left some comments below to more cleanly resolve the reported bugs, if you can take a look?

Thanks!

2023-08-10 13:52 UTC, jackofallops commented on internal/services/appservice/helpers/web_app_slot_schema.go
> +				}
Same here, as above.

2023-08-10 13:52 UTC, jackofallops commented on internal/services/appservice/helpers/web_app_slot_schema.go
> +				}
and again here

2023-08-10 13:52 UTC, jackofallops commented on internal/services/appservice/linux_web_app_resource.go
> +
This shouldn't be necessary with with the above bug fixes in the expands.

2023-08-10 13:52 UTC, jackofallops commented on internal/services/appservice/linux_web_app_resource.go
> +				}
as above, the fixes to the expands should remove the need for this

2023-08-10 13:52 UTC, jackofallops commented on internal/services/appservice/linux_web_app_slot_resource.go
> +
again here

2023-08-10 13:52 UTC, jackofallops commented on internal/services/appservice/linux_web_app_slot_resource.go
> +				}
and here

2023-08-10 13:52 UTC, jackofallops commented on internal/services/appservice/windows_web_app_resource.go
> +
and here

2023-08-10 13:52 UTC, jackofallops commented on internal/services/appservice/windows_web_app_resource.go
> +				}
again here

2023-08-10 13:52 UTC, jackofallops commented on internal/services/appservice/windows_web_app_slot_resource.go
> +
and again here

2023-08-10 13:52 UTC, jackofallops commented on internal/services/appservice/windows_web_app_slot_resource.go
> +				}
and here

2023-08-21 07:24 UTC, xiaxyi commented
updated the comment in thread~

2023-08-30 16:55 UTC, james-mwakichako commented
Are we in a position to merge this PR @jackofallops ? We are waiting for this fix

2023-09-12 00:48 UTC, jgmchan commented
We're in the same position as well, this bug is causing production issues as it keeps removing the DOCKER_* environment variables and this means it won't pull down the latest docker containers.

2023-09-12 04:52 UTC, oletolshaveics commented
My current work around look like this:
```
resource "azurerm_linux_web_app" "core_as" {
  name                						= // ...
  // ...

  site_config {
    // ...
	
	application_stack {
		docker_image_name                               = "(redacted)"		
		# I would like to enable these but currently do not
#              docker_registry_url                                  = "https://ghcr.io"
#		docker_registry_username                       = "(redacted)"
#		docker_registry_password                       = data.azurerm_key_vault_secret.ghdr.value
	}
  }

  app_settings = {
	// ...

    # Remove these when the docker settings no longer need to be in app_settings (https://github.com/hashicorp/terraform-provider-azurerm/pull/22484)
    "DOCKER_REGISTRY_SERVER_URL" 			= "https://ghcr.io"
    "DOCKER_REGISTRY_SERVER_USERNAME" 		= "(redacted)"
    "DOCKER_REGISTRY_SERVER_PASSWORD"		= data.azurerm_key_vault_secret.ghdr.value,
  }
}
```
The 3 app settings are detected as changes on every plan+apply, which is very annoying, but it does work. When I need to initialize an environment from scratch, I have to run Terraform 3(!?) times, before the app settings stabilize. Quite inconvenient, but at least it works.

2023-09-18 14:20 UTC, jackofallops commented
Hi @xiaxyi I couldn't push changes to your fork to resolve this, so I've opened another PR to get the fixes in. I'm going to close this in favour of #23303

2023-09-18 14:20 UTC, closed without merging