`azurerm_log_analytics_workspace`: allow changing `sku` between `CapacityReservation` and `PerGB2018`
hashicorp/terraform-provider-azurerm pull request #22597
Opened 2023-07-19 09:07 UTC by ziyeqf

fix #12177

changing between `CapacityReservation` and `PerGB2018` does not force new resource to be created, but it will lead to a 31-days commitment period during which it could not be changed to lower pricing tier.  https://learn.microsoft.com/en-us/azure/azure-monitor/logs/cost-logs#commitment-tiers)

test
---
```
❯ tftest loganalytics TestAccLogAnalyticsWorkspace    
=== RUN   TestAccLogAnalyticsWorkspace_basic
=== PAUSE TestAccLogAnalyticsWorkspace_basic
=== RUN   TestAccLogAnalyticsWorkspace_requiresImport
=== PAUSE TestAccLogAnalyticsWorkspace_requiresImport
=== RUN   TestAccLogAnalyticsWorkspace_complete
=== PAUSE TestAccLogAnalyticsWorkspace_complete
=== RUN   TestAccLogAnalyticsWorkspace_freeTier
    log_analytics_workspace_resource_test.go:95: `TestAccLogAnalyticsWorkspace_freeTier` due to subscription pricing tier configuration (e.g. Pricing tier doesn't match the subscription's billing model.)
--- SKIP: TestAccLogAnalyticsWorkspace_freeTier (0.00s)
=== RUN   TestAccLogAnalyticsWorkspace_withDefaultSku
=== PAUSE TestAccLogAnalyticsWorkspace_withDefaultSku
=== RUN   TestAccLogAnalyticsWorkspace_withVolumeCap
=== PAUSE TestAccLogAnalyticsWorkspace_withVolumeCap
=== RUN   TestAccLogAnalyticsWorkspace_removeVolumeCap
=== PAUSE TestAccLogAnalyticsWorkspace_removeVolumeCap
=== RUN   TestAccLogAnalyticsWorkspace_withInternetIngestionEnabled
=== PAUSE TestAccLogAnalyticsWorkspace_withInternetIngestionEnabled
=== RUN   TestAccLogAnalyticsWorkspace_withInternetQueryEnabled
=== PAUSE TestAccLogAnalyticsWorkspace_withInternetQueryEnabled
=== RUN   TestAccLogAnalyticsWorkspace_withCapacityReservation
=== PAUSE TestAccLogAnalyticsWorkspace_withCapacityReservation
=== RUN   TestAccLogAnalyticsWorkspace_negativeOne
=== PAUSE TestAccLogAnalyticsWorkspace_negativeOne
=== RUN   TestAccLogAnalyticsWorkspace_cmkForQueryForced
=== PAUSE TestAccLogAnalyticsWorkspace_cmkForQueryForced
=== RUN   TestAccLogAnalyticsWorkspace_ToggleAllowOnlyResourcePermission
=== PAUSE TestAccLogAnalyticsWorkspace_ToggleAllowOnlyResourcePermission
=== RUN   TestAccLogAnalyticsWorkspace_ToggleDisableLocalAuth
=== PAUSE TestAccLogAnalyticsWorkspace_ToggleDisableLocalAuth
=== RUN   TestAccLogAnalyticsWorkspace_updateSku
=== PAUSE TestAccLogAnalyticsWorkspace_updateSku
=== CONT  TestAccLogAnalyticsWorkspace_basic
=== CONT  TestAccLogAnalyticsWorkspace_withInternetQueryEnabled
=== CONT  TestAccLogAnalyticsWorkspace_ToggleAllowOnlyResourcePermission
=== CONT  TestAccLogAnalyticsWorkspace_withVolumeCap
=== CONT  TestAccLogAnalyticsWorkspace_negativeOne
=== CONT  TestAccLogAnalyticsWorkspace_requiresImport
=== CONT  TestAccLogAnalyticsWorkspace_withDefaultSku
=== CONT  TestAccLogAnalyticsWorkspace_complete
=== NAME  TestAccLogAnalyticsWorkspace_withInternetQueryEnabled
    testcase.go:113: Error running init: exit status 1
        
        Error: Failed to install provider
        
        Error while installing hashicorp/azuread v2.8.0: read tcp
        198.18.0.1:52300->198.18.0.44:443: read: operation timed out
        
--- PASS: TestAccLogAnalyticsWorkspace_requiresImport (146.76s)
=== CONT  TestAccLogAnalyticsWorkspace_updateSku
=== CONT  TestAccLogAnalyticsWorkspace_withInternetIngestionEnabled
--- FAIL: TestAccLogAnalyticsWorkspace_withInternetQueryEnabled (148.63s)
--- PASS: TestAccLogAnalyticsWorkspace_withDefaultSku (166.74s)
=== CONT  TestAccLogAnalyticsWorkspace_ToggleDisableLocalAuth
--- PASS: TestAccLogAnalyticsWorkspace_complete (173.74s)
=== CONT  TestAccLogAnalyticsWorkspace_cmkForQueryForced
--- PASS: TestAccLogAnalyticsWorkspace_negativeOne (214.52s)
=== CONT  TestAccLogAnalyticsWorkspace_withCapacityReservation
--- PASS: TestAccLogAnalyticsWorkspace_basic (229.89s)
=== CONT  TestAccLogAnalyticsWorkspace_removeVolumeCap
--- PASS: TestAccLogAnalyticsWorkspace_withVolumeCap (250.41s)
--- PASS: TestAccLogAnalyticsWorkspace_ToggleAllowOnlyResourcePermission (316.67s)
--- PASS: TestAccLogAnalyticsWorkspace_updateSku (183.77s)
--- PASS: TestAccLogAnalyticsWorkspace_withInternetIngestionEnabled (186.86s)
--- PASS: TestAccLogAnalyticsWorkspace_ToggleDisableLocalAuth (177.66s)
--- PASS: TestAccLogAnalyticsWorkspace_cmkForQueryForced (176.09s)
--- PASS: TestAccLogAnalyticsWorkspace_withCapacityReservation (209.43s)
--- PASS: TestAccLogAnalyticsWorkspace_removeVolumeCap (216.31s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-azurerm/internal/services/loganalytics  446.273s
FAIL
```

rerun the failed one
```
❯ tftest loganalytics TestAccLogAnalyticsWorkspace_withInternetQueryEnabled
=== RUN   TestAccLogAnalyticsWorkspace_withInternetQueryEnabled
=== PAUSE TestAccLogAnalyticsWorkspace_withInternetQueryEnabled
=== CONT  TestAccLogAnalyticsWorkspace_withInternetQueryEnabled
--- PASS: TestAccLogAnalyticsWorkspace_withInternetQueryEnabled (144.83s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/loganalytics  144.886s
```

2023-07-19 22:02 UTC, manicminer requested changes
Thanks @ms-henglu, this is off to a good start, however we'll need to avoid using `d.GetRawConfig()`. If you can update this then we'll circle back for re-review and testing. Thanks!

2023-07-19 22:02 UTC, manicminer commented on website/docs/r/log_analytics_workspace.html.markdown
> +~> **NOTE:** Changing `sku` forces a new Log Analytics Workspace to be created, except changing between `PerGB2018` and `CapacityReservation`, but changing it to `CapacityReservation` or changing `re
```suggestion
~> **NOTE:** Changing `sku` forces a new Log Analytics Workspace to be created, except when changing between `PerGB2018` and `CapacityReservation`. However, changing `sku` to `CapacityReservation` or changing `reservation_capacity_in_gb_per_day` to a higher tier will lead to a 31-days commitment period, during which the SKU cannot be changed to a lower one. Please refer to [official documentation](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/cost-logs#commitment-tiers) for further information.
```

2023-07-20 02:13 UTC, ziyeqf commented
we might need to note `reservation_capacity_in_gb_per_day` is not `computed` yet in changelog?

2023-08-01 15:59 UTC, katbyte commented
@ziyeqf - what do you mean by `reservation_capacity_in_gb_per_day is not computed yet` ?

2023-08-02 01:47 UTC, ziyeqf commented
> @ziyeqf - what do you mean by `reservation_capacity_in_gb_per_day is not computed yet` ?

oh, I mean it's not `computed` anymore.

2023-08-03 13:47 UTC, tombuildsstuff approved these changes
LGTM 👍

2023-08-07 02:08 UTC, ziyeqf commented
kindly ping for merge :)

2023-08-07 12:37 UTC, merged