`azurerm_kusto_cosmosdb_data_connection_resource` - fix cosmosdb account id
hashicorp/terraform-provider-azurerm pull request #22663
Opened 2023-07-25 02:32 UTC by liuwuliuyun

`azurerm_kusto_cosmosdb_data_connection_resource` - fix cosmosdb account id

Testing evidence:

```
TO BE Filled
```

2023-07-25 05:12 UTC, liuwuliuyun commented
The Generation Check failed is not introduced by this PR

2023-07-27 06:55 UTC, WodansSon requested changes
While the PR LGTM, can we add some test cases that would mimic the CX issue?

2023-07-28 03:06 UTC, liuwuliuyun commented
After adding two different RGs, the apply failed with Internal Server Error. Dont know why this happens, still testing.

2023-07-28 18:53 UTC, WodansSon commented
@liuwuliuyun, thanks for pushing those changes, but it looks like the test case is failing:
```bash
=== RUN   TestAccKustoCosmosDBDataConnection_diffResourceGroups
=== PAUSE TestAccKustoCosmosDBDataConnection_diffResourceGroups
=== CONT  TestAccKustoCosmosDBDataConnection_diffResourceGroups
    testcase.go:113: Step 1/2 error: Error running apply: exit status 1
        Error: creating Data Connection (Subscription: "*******"
        Resource Group Name: "acctestRG-230728180828682296"
        Cluster Name: "acctestkcrp34i"
        Database Name: "acctestkd-230728180828682296"
        Data Connection Name: "acctestkcdrp34i"): polling after CreateOrUpdate: Code="Failed" Message="Internal Server Error"
          with azurerm_kusto_cosmosdb_data_connection.test,
          on terraform_plugin_test.tf line 129, in resource "azurerm_kusto_cosmosdb_data_connection" "test":
         129: resource "azurerm_kusto_cosmosdb_data_connection" "test" {
        creating Data Connection (Subscription:
        "*******"
        Resource Group Name: "acctestRG-230728180828682296"
        Cluster Name: "acctestkcrp34i"
        Database Name: "acctestkd-230728180828682296"
        Data Connection Name: "acctestkcdrp34i"): polling after CreateOrUpdate:
        Code="Failed" Message="Internal Server Error"
--- FAIL: TestAccKustoCosmosDBDataConnection_diffResourceGroups (1325.46s)
FAIL
```

2023-07-31 04:37 UTC, liuwuliuyun commented
Hi @WodansSon , I updated the test case and now the failed one is passing.

2023-08-04 22:51 UTC, WodansSon commented
@liuwuliuyun, thanks for pushing the test case update. LGTM! 🚀 

<img width="377" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/20408400/adcb5b27-eae9-4686-951d-64598a72edef">

2023-08-04 22:55 UTC, merged