`azurerm_kubernetes_cluster` - Update Azure CNI to Azure CNI Overlay enabled
hashicorp/terraform-provider-azurerm pull request #22709
Opened 2023-07-27 07:01 UTC by aristosvo

Fixes #22704

2023-07-27 12:49 UTC, stephybun reviewed
@aristosvo what happens if we try migrating in the other direction e.g. overlay -> azure?

2023-07-27 16:33 UTC, aristosvo commented
I haven't tried yet, the docs seem unclear. I'll give it a try!

2023-08-03 01:15 UTC, katbyte requested changes
Looks like we have some test failures:

```
Error: creating Kubernetes Cluster (Subscription: "*******"
        Resource Group Name: "acctestRG-230802013926273291"
        Kubernetes Cluster Name: "acctestaks230802013926273291"): managedclusters.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="AgentPoolK8sVersionNotSupported" Message="Version 1.25.5 is not supported in this region. Please use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list"
        
          with azurerm_kubernetes_cluster.test,
          on terraform_plugin_test.tf line 76, in resource "azurerm_kubernetes_cluster" "test":
          76: resource "azurerm_kubernetes_cluster" "test" {
```

2023-08-24 10:41 UTC, aristosvo commented
@katbyte I think these are unrelated, at least as far as I can interpret them

@stephybun I made it a one-way migration for now, as I think it should be. Test is broken because of the `public_network_access_enabled` change, but other than that it should be fine!

2023-09-06 07:34 UTC, stephybun reviewed
Thanks @aristosvo. Hope you don't mind I rebased your branch to pull in the test fix for `public_network_access_enabled`.

I have one suggestion to simplify the ForceNew condition but otherwise this looks like it's ready.

2023-09-07 06:58 UTC, stephybun approved these changes
Thanks @aristosvo LGTM 👍

2023-09-07 06:59 UTC, merged