`azurerm_container_app_environment` - Make `log_analytics_workspace_id` an optional argument.
hashicorp/terraform-provider-azurerm pull request #22733
Opened 2023-07-28 10:16 UTC by lonegunmanb

We found that `log_analytics_workspace_id` is not required for `azurerm_container_app_environment` anymore, this pr change it to an optional argument so our users could save cost. This pr should solve #20748.

The newly added e2e test passed on my side:

```text
=== RUN   TestAccContainerAppEnvironment_withoutLogAnalyticsWorkspace
=== PAUSE TestAccContainerAppEnvironment_withoutLogAnalyticsWorkspace
=== CONT  TestAccContainerAppEnvironment_withoutLogAnalyticsWorkspace
--- PASS: TestAccContainerAppEnvironment_withoutLogAnalyticsWorkspace (670.33s)
```

2023-08-07 11:12 UTC, stephybun requested changes

2023-08-07 11:12 UTC, stephybun commented on internal/services/containerapps/container_app_environment_resource_test.go
> +			Config: r.basic(data, true),
Instead up updating the config to take an argument can you remove the property from basic and add it to the complete test instead.

2023-08-07 11:12 UTC, stephybun commented on website/docs/r/container_app_environment.html.markdown
> +* `log_analytics_workspace_id` - (Optional) The ID for the Log Analytics Workspace to link this Container Apps Managed Environment to. Changing this forces a new resource to be created.
This would need to be moved down to the section where we list the Optional properties.

2023-08-09 04:56 UTC, lonegunmanb commented
@stephybun Thanks for your suggestions, I've updated this pr, would you please give it another review? Thanks!

2023-08-09 05:53 UTC, stephybun approved these changes
Thanks @lonegunmanb LGTM ⭐

2023-08-09 05:53 UTC, merged