`azurerm_spring_cloud_configuration_service` - support for the `ca_certificate_id` property
hashicorp/terraform-provider-azurerm pull request #22814
Opened 2023-08-04 07:23 UTC by ms-henglu

2023-08-04 10:27 UTC, tombuildsstuff requested changes
One comment around the documentation for this field, but this otherwise LGTM 👍

2023-08-04 10:27 UTC, tombuildsstuff commented on website/docs/r/spring_cloud_configuration_service.html.markdown
> +* `ca_certificate_id` - (Optional) Specifies the ID of the CA Spring Cloud Certificate for https URL of Git repository.
Presumably, this is:

```suggestion
* `ca_certificate_id` - (Optional) Specifies the ID of the Certificate Authority used when retrieving the Git Repository via HTTPS.
```

2023-08-07 05:33 UTC, tombuildsstuff commented
@ms-henglu the tests are repeatedly returning an error:

```
 Error: waiting for creation/update of Spring Cloud Configuration Service: (Configuration Service Name "default" / Spring Name "acctest-sc-230807045734471977" / Resource Group "acctestRG-spring-230807045734471977"): Code="CreateOrUpdateAcsFailed" Message="CreateOrUpdateAcsFailed"
```

Is additional configuration needed for this?

2023-08-07 06:49 UTC, ms-henglu commented
Hi @tombuildsstuff ,

Thanks for the heads up! I've updated this PR, and the tests are passing:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/79895375/4eaba2a0-1c06-4955-8ee8-1da724446bf5)

2023-08-07 07:14 UTC, stephybun approved these changes
Thanks @ms-henglu LGTM 🌟

2023-08-07 07:14 UTC, merged