`example` - add example for virtual machine user data
hashicorp/terraform-provider-azurerm pull request #22951
Opened 2023-08-15 08:41 UTC by myc2h6o

Close #21568

2023-08-16 08:25 UTC, jackofallops requested changes
Hi @myc2h6o - Thanks for this new example.

I think we can improve the learning from the example by providing some meaningful content in the `user_data` property, such as a one line script?

Thanks

2023-08-16 08:25 UTC, jackofallops commented on examples/virtual-machines/linux/user-data/main.tf
> +  user_data                       = base64encode("Hello World!")
Can we make this a useful value to have in the User Data to better illustrate the purpose, rather than an arbitrary string?

2023-08-16 08:25 UTC, jackofallops commented on examples/virtual-machines/windows/user-data/main.tf
> +  user_data                       = base64encode("Hello World!")
as above

2023-08-18 06:57 UTC, myc2h6o commented
@jackofallops thanks for reviewing the change! I've checked the [document](https://learn.microsoft.com/azure/virtual-machines/custom-data) again and find out that `custom_data` must be a script, and `user_data` could be either a script or some random data which is later retrieved within the VM by Azure API. So I updated the custom data example instead to put a script in it.

2023-09-05 05:55 UTC, stephybun approved these changes
Thanks @myc2h6o LGTM 🍕

2023-09-05 05:56 UTC, merged