Adding new property zone_redundant to azurerm_container_app_environment
hashicorp/terraform-provider-azurerm pull request #22980
Opened 2023-08-16 10:36 UTC by matt-lethargic

fixes [#2053](https://github.com/hashicorp/terraform-provider-azurerm/issues/20538)

adds zone_redundant property to azurerm_container_app_environment

2023-08-22 10:37 UTC, matt-lethargic commented
Hey @jackofallops I see you've picked this up. I just looked at the files changed and realised that it thinks I've changed every line. I'm not sure how this happened as I followed the contributing instructions. Is there anything I can do to make this easier to review?

2023-08-22 11:17 UTC, jackofallops requested changes
Hi @matt-lethargic - Thanks for this PR. There's a few comments below that need to be addressed, then we can run the GHA's and I can put it through acceptance testing.

Thanks!

2023-08-22 11:17 UTC, jackofallops commented on internal/services/containerapps/container_app_environment_resource_test.go
> +}
Can we move this up to with the other properties?

```suggestion
resource "azurerm_container_app_environment" "test" {
  name                       = "acctest-CAEnv%[2]d"
  resource_group_name        = azurerm_resource_group.test.name
  location                   = azurerm_resource_group.test.location
  log_analytics_workspace_id = azurerm_log_analytics_workspace.test.id
  zone_redundant             = true
  
  infrastructure_subnet_id = azurerm_subnet.control.id

  internal_load_balancer_enabled = true

  tags = {
    Foo    = "Bar"
    secret = "sauce"
  }
}

```

2023-08-22 14:29 UTC, matt-lethargic commented
@jackofallops Thanks for the feedback, updated

2023-08-29 19:02 UTC, matt-lethargic commented
@jackofallops a friendly bump ;-)

2023-09-05 12:35 UTC, jackofallops commented
> @jackofallops a friendly bump ;-)

Hi @matt-lethargic - apologies, I've been out on PTO for a while. Would you be able to rebase against `main` to resolve the conflicts, and I'll finish up review and run the tests?

Thanks!

2023-09-19 06:26 UTC, jackofallops commented
Hi @matt-lethargic - Sincerest apologies, in attempting to rebase your branch to resolve the conflicts, I've typo'd the fetch and overwritten your commits :( I'm going to have to close this PR and I'll open a new one and I'll mark the commits as co-authored by you.  Again, I can only apologise!

2023-09-19 06:26 UTC, closed without merging