New resource `azurerm_iothub_endpoint_cosmosdb_account`
hashicorp/terraform-provider-azurerm pull request #23065
Opened 2023-08-24 07:40 UTC by myc2h6o

Close #20591

2023-08-24 08:53 UTC, myc2h6o commented
Test result
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/10579712/3fc5c7e4-4ae0-4726-93d8-024bc197ed0d)

2023-09-05 13:15 UTC, catriona-m requested changes
Thanks for this @myc2h6o - this is looking pretty good, I've left a couple of minor comments but can have another look once those get fixed up. Thanks!

2023-09-06 16:04 UTC, myc2h6o commented on internal/services/iothub/iothub_endpoint_cosmosdb_account_resource.go
> +						endpoint.SecondaryKey = pointer.To(state.PrimaryKey)
thanks for pointing this out! I've fixed it

2023-09-06 16:04 UTC, myc2h6o commented on internal/services/iothub/iothub_endpoint_cosmosdb_account_resource.go
> +					return nil
have added the error return

2023-09-08 12:01 UTC, catriona-m approved these changes
Thanks for updating @myc2h6o - LGTM 🎷

2023-09-08 12:01 UTC, merged