New Resource : `azurerm_resource_connector_appliance`
hashicorp/terraform-provider-azurerm pull request #23108
Opened 2023-08-29 06:07 UTC by sinbai

Swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resourceconnector/resource-manager/Microsoft.ResourceConnector/stable/2022-10-27/appliances.json

Test results:
```
PASS: TestAccResourceConnectorAppliance_update (261.46s)
PASS:TestAccResourceConnectorAppliance_complete (212.88s)
PASS: TestAccResourceConnectorAppliance_requiresImport (201.50s)
PASS: TestAccResourceConnectorAppliance_basic (202.36s)
```

2023-09-05 06:25 UTC, tombuildsstuff requested changes
hi @sinbai 

Thanks for this PR - I've taken a look through and left some comments inline, if those can be addressed then we should be able to take another look here.

It's worth noting that when a field has to be set via the Update method, that we can first Create the resource and then use the Update API to update this value - as such we don't need to ask users to conditionally apply their Terraform Configuration in two stages.

It's also worth noting there's conflation between the Appliance and the Resource Connector Appliance in the documentation, presumably the Appliance has to exist within AKS/VMware etc first? If so, then we're also missing test cases showing this working end-to-end - could we clarify the behaviour of this service to make it fully usable here?

Thanks!

2023-09-12 03:52 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource.go
> +			}
For `PublicKey` property, I fixed it as the suggested. For the `Version` property, I have removed it as it is not a user settable property after confirming with service team.

2023-09-12 03:56 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource.go
> +				Location: model.Location,
Fixed.

2023-09-12 03:57 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource.go
> +			parameters.Identity = identity
Fixed.

2023-09-12 03:57 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource.go
> +			}
Fixed.

2023-09-12 03:58 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource.go
> +			parameters.Identity = identity
Fixed.

2023-09-12 03:58 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource.go
> +			}
Fixed.

2023-09-12 03:59 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource.go
> +			}
Fixed.

2023-09-12 03:59 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource_test.go
> +	l := ResourceConnectorApplianceResource{}
Fixed.

2023-09-12 03:59 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource_test.go
> +	l := ResourceConnectorApplianceResource{}
Fixed.

2023-09-12 03:59 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource_test.go
> +	l := ResourceConnectorApplianceResource{}
Fixed.

2023-09-12 03:59 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource_test.go
> +	l := ResourceConnectorApplianceResource{}
Fixed.

2023-09-12 03:59 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource_test.go
> +  name     = "acctestRG-Appliances-%[1]d"
Fixed.

2023-09-12 04:00 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource_test.go
> +  name                    = "acctestAppliances-%[1]d"
Fixed.

2023-09-12 04:00 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +-> **Note:** Before using this resource, it's required to submit the request of registering the providers with Azure CLI `az provider register --namespace Microsoft.ResourceConnector`.
Fixed.

2023-09-12 04:01 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +  Manages an Appliance.
Just the connection. The description has been updated.

2023-09-12 04:01 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +Manages an Appliances.
Just the connection. It has been updated.

2023-09-12 04:01 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +  location = "eastus"
Fixed.

2023-09-12 04:02 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +* `distro` - (Required) Specifies the resource group where the resource exists. The possible value is `AKSEdge`.
Fixed.

2023-09-12 04:02 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +* `name` - (Required) The Name which should be used for this Appliance. Changing this forces a new resource to be created.
Fixed.

2023-09-12 04:02 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +* `public_key`- (Required) The `public_key` is an RSA public key in PKCS1 format encoded in base64.
Fixed.

2023-09-12 04:03 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +* `location` - (Required) The Azure Region where the Appliance should exist. Changing this forces a new resource to be created.
Resource Connector Appliance, fixed.

2023-09-12 04:03 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +* `resource_group_name` - (Required) Specifies the resource group where the resource exists. Changing this forces a new resource to be created.
Fixed.

2023-09-12 04:03 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +* `tags` - (Optional) A mapping of tags which should be assigned to the Appliance.
Resource Connector Appliance, fixed.

2023-09-12 04:04 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource.go
> +			}, false),
After confirming with service team, the `version` is not a user settable property, I have removed it.

2023-09-12 04:04 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +-> **NOTE:** The `version` cannot be populated apart from upgrade call.
After confirming with service team, the version is not a user settable property, I have removed it.

2023-09-12 04:04 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +terraform import azurerm_resource_connector_appliance.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/providers/Microsoft.ResourceConnector/apliances/appliancesExample
appliances, fixed.

2023-09-12 04:04 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +* `delete` - (Defaults to 30 minutes) Used when deleting the Appliance.
Resource Connector Appliance, fixed.

2023-09-12 04:04 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +* `id` - The ID of the Appliance.
Resource Connector Appliance, fixed.

2023-09-12 04:05 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +* `version` - (Optional) The version of the Appliance. Possible values is `latest`.
Resource Connector Appliance, fixed.

2023-09-12 04:14 UTC, sinbai commented
> hi @sinbai
> 
> Thanks for this PR - I've taken a look through and left some comments inline, if those can be addressed then we should be able to take another look here.
> 
> It's worth noting that when a field has to be set via the Update method, that we can first Create the resource and then use the Update API to update this value - as such we don't need to ask users to conditionally apply their Terraform Configuration in two stages.
> 
> It's also worth noting there's conflation between the Appliance and the Resource Connector Appliance in the documentation, presumably the Appliance has to exist within AKS/VMware etc first? If so, then we're also missing test cases showing this working end-to-end - could we clarify the behaviour of this service to make it fully usable here?
> 
> Thanks!

@tombuildsstuff  thanks for your detailed feedback. I have fixed the inline feedback. Could you please take another look?

For above `test cases showing this working end-to-end`, the following is the feedback I got from the service team.
```
Appliance RP is a hybrid resource provider service. We have a few operations that deploy a cluster on prem for customers like Validate, Prepare, Deploy are run on prem only and can be done via Arc Appliance CLI as this requires specific parameters depending on the on prem stack being used to deploy the cluster on. 

We do create an Azure resource to help link the on prem resource to Azure, and that is done using  RP operations (that we support using various SDKs) like Create, Update, Get, List, etc, for which we are also looking to support Terraform as the RP is GAing.
```

> Link to public doc - [Azure Arc resource bridge (preview) overview - Azure Arc | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fazure-arc%2Fresource-bridge%2Foverview&data=05%7C01%7Cv-elenaxin%40microsoft.com%7Cc0f9934bf9d24dab02a408dbb31b47b5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638300702068993345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=frjs4LxVjoCP8z76XX%2Fxs60t0oU6IuB8%2B08WC6GC5Vo%3D&reserved=0)

Per above feedback, I assume that we could not add end-to-end testing in TF, what do you think?

2023-09-18 12:51 UTC, stephybun requested changes
Thanks for making those changes @sinbai.

There are a few things that still need to be fixed.

Also since this is from the Azure Arc product line this resource should be renamed to `azurerm_arc_bridge_appliance`/`azurerm_arc_bridge_connector_appliance` or something of the sort? This is because we should go with names that are familiar to the users, in this case since this is being marketed as Arc Bridge. Also existing arc resources within the provider like the Arc Kubernetes cluster or Arc Virtual Machine are also named as such.

2023-09-19 06:37 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource.go
> +	Tags              map[string]string              `tfschema:"tags"`
Fixed.

2023-09-19 06:37 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource.go
> +				Tags: pointer.To(model.Tags),
Fixed.

2023-09-19 06:38 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource.go
> +				parameters.Tags = pointer.To(model.Tags)
Fixed.

2023-09-19 06:38 UTC, sinbai commented on internal/services/resourceconnector/resourceconnector_appliance_resource.go
> +				state.Tags = pointer.From(resp.Model.Tags)
Fixed.

2023-09-19 06:38 UTC, sinbai commented on website/docs/r/resource_connector_appliance.html.markdown
> +* `public_key`- (Optional) The `public_key` is an RSA public key in PKCS1 format encoded in base64. Changing this forces a new resource to be created.
Thanks for your explanation, fixed:)

2023-09-19 06:38 UTC, sinbai commented
> Thanks for making those changes @sinbai.
> 
> There are a few things that still need to be fixed.
> 
> Also since this is from the Azure Arc product line this resource should be renamed to `azurerm_arc_bridge_appliance`/`azurerm_arc_bridge_connector_appliance` or something of the sort? This is because we should go with names that are familiar to the users, in this case since this is being marketed as Arc Bridge. Also existing arc resources within the provider like the Arc Kubernetes cluster or Arc Virtual Machine are also named as such.

@stephybun thanks for you detailed feedback. I updated the resource name to `azurerm_arc_resource_bridge_appliance` based on [What is Azure Arc resource bridge (preview)](https://learn.microsoft.com/en-us/azure/azure-arc/resource-bridge/overview), WDYT? Also, I updated the other comments, could you please take another look?

2023-09-19 10:45 UTC, stephybun approved these changes
Thanks @sinbai LGTM 🍰

2023-09-19 10:46 UTC, merged