Add Support for Icon URL in azurerm_bot_service_azure_bot resource
hashicorp/terraform-provider-azurerm pull request #23114
Opened 2023-08-29 12:53 UTC by fdmsantos

Fixes [23041](https://github.com/hashicorp/terraform-provider-azurerm/issues/23041)

2023-09-05 04:15 UTC, tombuildsstuff requested changes
hey @fdmsantos 

Thanks for this PR - I've taken a look through and left a couple of comments inline, but if we can fix those up then this should otherwise be good to go 👍 

Thanks!

2023-09-05 04:15 UTC, tombuildsstuff commented on internal/services/bot/bot_service_resource_base.go
> +		"icon_url": {
can we add this field [to the documentation](https://github.com/hashicorp/terraform-provider-azurerm/blob/b7eb5a3e8cecd273cd788f606aa46bd323cc68c0/website/docs/r/bot_service_azure_bot.html.markdown?plain=1#L75-L85) too?

2023-09-05 04:15 UTC, tombuildsstuff commented on internal/services/bot/bot_service_resource_base.go
> +				metadata.ResourceData.Set("icon_url", iconUrl)
fwiw this can become:

```suggestion
				metadata.ResourceData.Set("icon_url", pointer.To(props.IconURL))
```

2023-09-05 09:07 UTC, stephybun requested changes
Thanks for this @fdmsantos. Could you also add this to the acceptance test, I think the [configuration for the update](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/bot/bot_service_azure_bot_resource_test.go#L158) is an appropriate place for this property.

2023-09-05 09:41 UTC, fdmsantos commented
Hi, I only can do this on two weeks.
Tks.

On Tue, Sep 5, 2023, 10:07 stephybun ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for this @fdmsantos <https://github.com/fdmsantos>. Could you also
> add this to the acceptance test, I think the configuration for the update
> <https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/bot/bot_service_azure_bot_resource_test.go#L158>
> is an appropriate place for this property.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hashicorp/terraform-provider-azurerm/pull/23114#pullrequestreview-1610588540>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGGIXOXCPSBDMWSPP6BZBG3XY3TVBANCNFSM6AAAAAA4C5BUSA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2023-09-20 09:14 UTC, stephybun requested changes
Thanks @fdmsantos.

The tests are failing because this property has a default value. We need to add that to the schema, then this should be good to go!

2023-09-20 09:14 UTC, stephybun commented on internal/services/bot/bot_service_resource_base.go
> +		},
```suggestion
		"icon_url": {
			Type:         pluginsdk.TypeString,
			Optional:     true,
			Default:      "https://docs.botframework.com/static/devportal/client/images/bot-framework-default.png",
			ValidateFunc: validation.StringIsNotEmpty,
		},
```

2023-09-22 08:08 UTC, stephybun approved these changes
Thanks for this @fdmsantos! Tests are now passing. I hope you don't mind a rebased your branch to fix a merge conflict so that this can go into the next release. LGTM 👍

2023-09-22 08:23 UTC, merged