`azurerm_api_management_api_policy`, `azurerm_api_management_api_operation_policy`, `azurerm_api_management_product_policy` : fix parsing resource id error
hashicorp/terraform-provider-azurerm pull request #23128
Opened 2023-08-30 09:00 UTC by sinbai

For resources `azurerm_api_management_api_policy`, `azurerm_api_management_api_operation_policy`, `azurerm_api_management_product_policy`, after importing the resource using a version before v3.70.0 of Terraform Provider,  the id in state file ends with "/policies/policy", and the id in state file ends with "/policies/xml" when creating resource by Terraform. Therefore, when migrating Pandora SDK, both cases need to be migrated.

 In [PR #22783](https://github.com/hashicorp/terraform-provider-azurerm/pull/22783) only the case where the ID ends with "/policies/xml" is processed, so submit this PR to process the case where the ID ends with "/policies/policy" to solve the parsing id error.

Might fix issue #23112, #23095.

Local manual testing, the steps are as follows:
	

> 1. Import  the existing resources `azurerm_api_management_api_policy`, `azurerm_api_management_api_operation_policy`, `azurerm_api_management_product_policy` using TF provider v3.69.0. 
> 	2. Upgrade TF provider to v3.71.0.
> 	3. Run "terraform plan" => The parsing id error occurred.
> 	4. Upgrade the TF provider to the current PR build version.
> 	5.  Run "terraform plan"  => No error.

2023-08-31 13:57 UTC, tombuildsstuff requested changes
hey @sinbai 

Thanks for this PR - taking a look through on the whole this looks pretty good but since we're updating these IDs we should also look to parse/reformat the ID too to ensure that the `resourceGroups` and other segments are correct at the same time. However if we can fix that up then this should otherwise be good to go 👍 

Thanks!

2023-08-31 13:57 UTC, tombuildsstuff commented on internal/services/apimanagement/migration/api_product_policy_v1_to_v2.go
> +		rawState["id"] = newId
(same here / as above)

2023-08-31 13:57 UTC, tombuildsstuff commented on internal/services/apimanagement/migration/api_operation_policy_v1_to_v2.go
> +		rawState["id"] = newId
(same here)

```suggestion
		newId := strings.TrimSuffix(oldId, "/policies/policy")

		log.Printf("[DEBUG] Updating ID from %q to %q", oldId, newId)
		rawState["id"] = newId
```

2023-09-01 05:25 UTC, sinbai commented on internal/services/apimanagement/migration/api_product_policy_v1_to_v2.go
> +		rawState["id"] = newId
Fixed.

2023-09-01 05:25 UTC, sinbai commented on internal/services/apimanagement/migration/api_operation_policy_v1_to_v2.go
> +		rawState["id"] = newId
Fixed.

2023-09-01 05:25 UTC, sinbai commented on internal/services/apimanagement/migration/api_policy_v1_to_v2.go
> +		rawState["id"] = newId
Fixed.

2023-09-01 05:29 UTC, sinbai commented
> hey @sinbai
> 
> Thanks for this PR - taking a look through on the whole this looks pretty good but since we're updating these IDs we should also look to parse/reformat the ID too to ensure that the `resourceGroups` and other segments are correct at the same time. However if we can fix that up then this should otherwise be good to go 👍
> 
> Thanks!

Hi @tombuildsstuff , thanks for your feedback. The code has been updated. Could you please take another look?

2023-09-07 14:38 UTC, merged