`azurerm_monitor_log_profile` - mark as deprecated
hashicorp/terraform-provider-azurerm pull request #23146
Opened 2023-09-01 03:31 UTC by teowa

from https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log?tabs=powershell#legacy-collection-methods

On 30 September 2026, the legacy solution for forwarding Azure activity logs will be retired and replaced with diagnostic settings. This transition to diagnostic settings will happen automatically—you don’t need to take any action, and the change won’t cause any disruption in your workflow.

2023-09-04 14:34 UTC, tombuildsstuff requested changes
hi @teowa 

Thanks for this PR - I've taken a look through and left some comments inline, but if we can fix those up then this otherwise should be good to go 👍 

Thanks!

2023-09-04 14:34 UTC, tombuildsstuff commented on internal/services/monitor/monitor_log_profile_resource.go
> +		DeprecationMessage: "Azure Log profiles will be retired on 30th September 2026, for more details, please see https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log?tabs=power
```suggestion
		DeprecationMessage: "Azure Log Profiles will be retired on 30th September 2026 and will be removed in v4.0 of the AzureRM Provider. More information on the deprecation can be found at https://learn.microsoft.com/azure/azure-monitor/essentials/activity-log?tabs=powershell#legacy-collection-methods",
```

2023-09-04 14:34 UTC, tombuildsstuff commented on website/docs/d/monitor_log_profile.html.markdown
> +-> **NOTE:** Azure Log profiles will be retired on 30th September 2026, for more details, please see the [doc](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log?tabs=power
We should mark this as a red block:

```suggestion
!> **NOTE:** Azure Log Profiles will be retired on 30th September 2026 and will be removed in v4.0 of the AzureRM Provider. More information on the deprecation can be found [in the Azure documentation](https://learn.microsoft.com/azure/azure-monitor/essentials/activity-log?tabs=powershell#legacy-collection-methods).
```

2023-09-04 14:34 UTC, tombuildsstuff commented on website/docs/r/monitor_log_profile.html.markdown
> +-> **NOTE:** Azure Log profiles will be retired on 30th September 2026, for more details, please see the [doc](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log?tabs=power
!> **NOTE:** Azure Log Profiles will be retired on 30th September 2026 and will be removed in v4.0 of the AzureRM Provider. More information on the deprecation can be found [in the Azure documentation](https://learn.microsoft.com/azure/azure-monitor/essentials/activity-log?tabs=powershell#legacy-collection-methods).

2023-09-04 14:34 UTC, tombuildsstuff commented on internal/services/monitor/monitor_log_profile_resource.go
> +		DeprecationMessage: "Azure Log profiles will be retired on 30th September 2026, for more details, please see https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log?tabs=power
we should also mark the associated Data Source as deprecated too

2023-09-06 05:13 UTC, stephybun approved these changes
Thanks @teowa LGTM 👍

2023-09-06 05:14 UTC, merged