`azurerm_key_vault_certificate`: fix createCertificate lost http.Response to check if recover this certificate
hashicorp/terraform-provider-azurerm pull request #23204
Opened 2023-09-07 10:06 UTC by wuxu92

should fixes: #23177.

2023-09-08 06:16 UTC, stephybun commented on internal/services/keyvault/key_vault_certificate_resource.go
> +					return fmt.Errorf("recover deleted certificqate: %+v", err)
```suggestion
					return fmt.Errorf("recover deleted certificate: %+v", err)
```

2023-09-08 06:16 UTC, stephybun commented on internal/services/keyvault/key_vault_certificate_resource.go
> +					return fmt.Errorf("recover deleted certificqate: %+v", err)
```suggestion
					return fmt.Errorf("recover deleted certificate: %+v", err)
```

2023-09-08 06:22 UTC, wuxu92 commented on internal/services/keyvault/key_vault_certificate_resource.go
> +					return fmt.Errorf("recover deleted certificqate: %+v", err)
updated.

2023-09-19 23:02 UTC, itdevops-channelcapital commented
Hi @wuxu92 and @stephybun,
How is this PR tracking? Seems to be just about done. Would be great to have this fix in the next release.

2023-09-20 06:06 UTC, stephybun requested changes
@wuxu92 could you please add an acceptance test that reproduces the failure described in the issue so that we can verify that this fixes it?

2023-09-21 14:23 UTC, stephybun reviewed
Thanks @wuxu92 LGTM 👍

2023-09-21 14:24 UTC, stephybun approved these changes

2023-09-21 14:24 UTC, merged