`azurerm_managed_disk` - Support `optimized_frequent_attach_enabled` and `performance_plus_enabled`
hashicorp/terraform-provider-azurerm pull request #23241
Opened 2023-09-12 02:54 UTC by ms-zhenhua

## Test Result

API server listening at: 127.0.0.1:54647
=== RUN   TestAccManagedDisk_optimizedFrequentAttach
=== PAUSE TestAccManagedDisk_optimizedFrequentAttach
=== CONT  TestAccManagedDisk_optimizedFrequentAttach
--- PASS: TestAccManagedDisk_optimizedFrequentAttach (265.59s)
PASS

API server listening at: 127.0.0.1:55510
=== RUN   TestAccManagedDisk_performancePlus
=== PAUSE TestAccManagedDisk_performancePlus
=== CONT  TestAccManagedDisk_performancePlus
--- PASS: TestAccManagedDisk_performancePlus (182.98s)
PASS

2023-09-12 14:18 UTC, tombuildsstuff requested changes
hey @ms-zhenhua 

Thanks for this PR - I've taken a look through and left some comments inline, but if we can fix those up then this should otherwise be good to go 👍 

Thanks!

2023-09-12 14:18 UTC, tombuildsstuff commented on website/docs/r/managed_disk.html.markdown
> +* `optimized_frequent_attach_enabled` - (Optional) Whether the feature of improving reliability and performance of data disks that are frequently (more than 5 times a day) detached from one virtual m
```suggestion
* `optimized_frequent_attach_enabled` - (Optional) Specifies whether this Managed Disk should be optimized for frequent disk attachments (where a disk is attached/detached more than 5 times in a day). Defaults to `false`.

-> **Note:** Setting `optimized_frequent_attach_enabled` to `true` causes the disks to not align with the fault domain of the Virtual Machine, which can have operational implications.
```

2023-09-13 02:01 UTC, ms-zhenhua commented on website/docs/r/managed_disk.html.markdown
> +* `performance_plus_enabled` - (Optional) Whether performance plus is enabled for this disk. Performance plus is only supported for UltraSSD disks. Defaults to `false`. Changing this forces a new res
Doc updated. Thanks.

2023-09-13 02:16 UTC, ms-zhenhua commented
Hi @tombuildsstuff, thank you for your review. I have resolved all the comments. Could you kindly help take another review? Thanks.

2023-09-13 14:58 UTC, tombuildsstuff approved these changes
LGTM 👍

2023-09-13 14:59 UTC, merged