DataSource:`azurerm_container_app_environment`: deprecate `log_analytics_workspace_name`, add `log_analytics_workspace_customer_id`
hashicorp/terraform-provider-azurerm pull request #23298
Opened 2023-09-18 08:08 UTC by ziyeqf

`log_analytics_workspace_name` is not consistent with what it really output.

fix #23265

test
---
```
❯ tftest mobilenetwork TestAccMobileNetworkPacketCoreControlPlane
=== RUN   TestAccMobileNetworkPacketCoreControlPlane_basic
=== PAUSE TestAccMobileNetworkPacketCoreControlPlane_basic
=== RUN   TestAccMobileNetworkPacketCoreControlPlane_withAccessInterface
=== PAUSE TestAccMobileNetworkPacketCoreControlPlane_withAccessInterface
=== RUN   TestAccMobileNetworkPacketCoreControlPlane_withInteropJSON
=== PAUSE TestAccMobileNetworkPacketCoreControlPlane_withInteropJSON
=== RUN   TestAccMobileNetworkPacketCoreControlPlane_withUeMTU
=== PAUSE TestAccMobileNetworkPacketCoreControlPlane_withUeMTU
=== RUN   TestAccMobileNetworkPacketCoreControlPlane_withCertificateUserAssignedIdentity
=== PAUSE TestAccMobileNetworkPacketCoreControlPlane_withCertificateUserAssignedIdentity
=== RUN   TestAccMobileNetworkPacketCoreControlPlane_requiresImport
=== PAUSE TestAccMobileNetworkPacketCoreControlPlane_requiresImport
=== RUN   TestAccMobileNetworkPacketCoreControlPlane_update
=== PAUSE TestAccMobileNetworkPacketCoreControlPlane_update
=== RUN   TestAccMobileNetworkPacketCoreControlPlane_complete
=== PAUSE TestAccMobileNetworkPacketCoreControlPlane_complete
=== CONT  TestAccMobileNetworkPacketCoreControlPlane_basic
=== CONT  TestAccMobileNetworkPacketCoreControlPlane_withCertificateUserAssignedIdentity
=== CONT  TestAccMobileNetworkPacketCoreControlPlane_withInteropJSON
=== CONT  TestAccMobileNetworkPacketCoreControlPlane_withAccessInterface
=== CONT  TestAccMobileNetworkPacketCoreControlPlane_withUeMTU
=== CONT  TestAccMobileNetworkPacketCoreControlPlane_update
=== CONT  TestAccMobileNetworkPacketCoreControlPlane_complete
=== CONT  TestAccMobileNetworkPacketCoreControlPlane_requiresImport
--- PASS: TestAccMobileNetworkPacketCoreControlPlane_withUeMTU (866.31s)
--- PASS: TestAccMobileNetworkPacketCoreControlPlane_withAccessInterface (946.18s)
--- PASS: TestAccMobileNetworkPacketCoreControlPlane_requiresImport (1020.02s)
--- PASS: TestAccMobileNetworkPacketCoreControlPlane_basic (1081.86s)
--- PASS: TestAccMobileNetworkPacketCoreControlPlane_update (1087.75s)
--- PASS: TestAccMobileNetworkPacketCoreControlPlane_withInteropJSON (1091.40s)
--- PASS: TestAccMobileNetworkPacketCoreControlPlane_complete (1148.65s)
--- PASS: TestAccMobileNetworkPacketCoreControlPlane_withCertificateUserAssignedIdentity (1231.24s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/mobilenetwork 1232.856s
```

2023-09-18 11:02 UTC, jackofallops requested changes
Hi @ziyeqf - Thanks for this PR. Whilst it corrects the name of the value being output, it doesn't actually help users? Could you take a look at discovering the correct `log_analytics_workspace_name` via the `list` operation and searching for the matching `customerId` instead?
Thanks

2023-09-19 03:46 UTC, ziyeqf commented
code updated, another try triggered on TC, will update once it finish

2023-09-19 04:09 UTC, ziyeqf commented
<img width="538" alt="Screenshot 2023-09-18 at 18 02 46" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/51212351/48ae47e2-4a58-49e5-9411-a4fcc8b283e1">

2023-09-19 05:47 UTC, jackofallops approved these changes
Thanks @ziyeqf - this looks good to me now and provides the useful value to the user, nice work 👍

2023-09-19 05:48 UTC, jackofallops commented
Testing passes:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/11830746/5dd01364-8cff-451f-88f5-f5d00e6373f0)

2023-09-19 05:49 UTC, merged