`azurerm_application_gateway` - datasource support for `backend_http_settings`, `global`, `gateway_ip_configuration` and more attributes.
hashicorp/terraform-provider-azurerm pull request #23318
Opened 2023-09-19 10:31 UTC by teowa

2023-09-25 08:38 UTC, jackofallops requested changes
Hi @teowa - Thanks for this PR bringing the Data Source more in-line with the Resource. I've left quite a few comments below, mostly in regard to the documentation. Unfortunately, we can't copy-paste from one to the other, as the context of the properties changes from an input to, in nearly all cases, just an output. This changes the grammar and tone of the documentation, and means we need to leave out things like the input possible values and hints/limitations.

If you can take a look, I'll continue my review.

Thanks again!

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `protocol` - The Protocol used for this Probe. Possible values are `Http` and `Https`.
```suggestion
* `protocol` - The Protocol used for this Probe.
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `pick_host_name_from_backend_http_settings` - Whether the host header should be picked from the backend HTTP settings.
```suggestion
* `timeout` - The Timeout used for this Probe, indicating when a probe becomes unhealthy.

* `unhealthy_threshold` - The Unhealthy Threshold for this Probe, which indicates the amount of retries which will be attempted before a node is deemed unhealthy.

* `port` - Custom port which is used for probing the backend servers. 

* `pick_host_name_from_backend_http_settings` - Whether the host header is picked from the backend HTTP settings.
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +A `request_routing_rule` block supports the following:
```suggestion
A `request_routing_rule` block exports the following:
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `priority` - Rule evaluation order can be dictated by specifying an integer value from `1` to `20000` with `1` being the highest priority and `20000` being the lowest priority.
```suggestion
* `rule_type` - The Type of Routing that is used for this Rule.

* `http_listener_name` - The Name of the HTTP Listener which is used for this Routing Rule.

* `backend_address_pool_name` - The Name of the Backend Address Pool which is used for this Routing Rule.

* `backend_http_settings_name` - The Name of the Backend HTTP Settings Collection which is used for this Routing Rule. 

* `redirect_configuration_name` - The Name of the Redirect Configuration which is used for this Routing Rule.

* `rewrite_rule_set_name` - The Name of the Rewrite Rule Set which is used for this Routing Rule.

* `url_path_map_name` - The Name of the URL Path Map which is associated with this Routing Rule.

* `priority` - The Priority of the Rule.
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +A `global` block supports the following:
```suggestion
A `global` block exports the following:
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `capacity` - The Capacity of the SKU to use for this Application Gateway. When using a V1 SKU this value must be between 1 and 32, and 1 to 125 for a V2 SKU. This property is optional if `autoscale
```suggestion
A `sku` block exports the following:

* `name` - The Name of the SKU in use for this Application Gateway.

* `tier` - The Tier of the SKU in use for this Application Gateway.

* `capacity` - The Capacity of the SKU in use for this Application Gateway.
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +A `ssl_certificate` block supports the following:
```suggestion
A `ssl_certificate` block exports the following:
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `key_vault_secret_id` - Secret ID of (base-64 encoded unencrypted pfx) `Secret` or `Certificate` object stored in Azure KeyVault. You need to enable soft delete for keyvault to use this feature.
```suggestion
* `key_vault_secret_id` - The Secret ID of the `Secret` or `Certificate` object stored in Azure KeyVault.
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +A `url_path_map` block supports the following:
```suggestion
A `url_path_map` block exports the following:
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `default_rewrite_rule_set_name` - The Name of the Default Rewrite Rule Set which should be used for this URL Path Map. Only valid for v2 SKUs.
```suggestion
* `default_backend_address_pool_name` - The Name of the Default Backend Address Pool which is used for this URL Path Map.

* `default_backend_http_settings_name` - The Name of the Default Backend HTTP Settings Collection which is used for this URL Path Map.

* `default_redirect_configuration_name` - The Name of the Default Redirect Configuration which is used for this URL Path Map.

* `default_rewrite_rule_set_name` - The Name of the Default Rewrite Rule Set which is used for this URL Path Map.
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +A `trusted_client_certificate` block supports the following:
```suggestion
A `trusted_client_certificate` block exports the following:
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `ssl_policy` - a `ssl_policy` block as defined below.
```suggestion
A `ssl_profile` block exports the following:

* `name` - The name of the SSL Profile that is unique within this Application Gateway.

* `trusted_client_certificate_names` - The name of the Trusted Client Certificate that will be used to authenticate requests from clients.

* `verify_client_cert_issuer_dn` - Will client certificate issuer DN to be verified?

* `verify_client_certificate_revocation` - The method to used check client certificate revocation status. 

* `ssl_policy` - a `ssl_policy` block as defined below.
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `min_protocol_version` - The minimal TLS version. Possible values are `TLSv1_0`, `TLSv1_1`, `TLSv1_2` and `TLSv1_3`.
```suggestion
A `ssl_policy` block exports the following:

* `disabled_protocols` - A list of SSL Protocols which should be disabled on this Application Gateway.

* `policy_type` - The Type of the Policy.

* `policy_name` - The Name of the Policy.

* `cipher_suites` - A List of accepted cipher suites. 

* `min_protocol_version` - The minimal TLS version.
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `rules` - A list of rules which should be disabled in that group. Disables all rules in the specified group if `rules` is not specified.
```suggestion
A `disabled_rule_group` block exports the following:

* `rule_group_name` - The rule group where specific rules should be disabled. 

* `rules` - A list of rules which will be disabled in that group. 
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `selector` - String value which will be used for the filter operation. If empty will exclude all traffic on this `match_variable`
```suggestion
A `exclusion` block exports the following:

* `match_variable` - Match variable of the exclusion rule.

* `selector_match_operator` - Operator which will be used to search in the variable content. 

* `selector` - String value which will be used for the filter operation. 
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `max_capacity` - Maximum capacity for autoscaling. Accepted values are in the range `2` to `125`.
```suggestion
A `autoscale_configuration` block exports the following:

* `min_capacity` - Minimum capacity for autoscaling. 

* `max_capacity` - Maximum capacity for autoscaling. 
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +A `rewrite_rule_set` block supports the following:
```suggestion
A `rewrite_rule_set` block exports the following:
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +A `rewrite_rule` block supports the following:
```suggestion
A `rewrite_rule` block exports the following:
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `header_value` - Header value of the header configuration. To delete a request header set this property to an empty string.
```suggestion
A `request_header_configuration` block exports the following:

* `header_name` - Header name of the header configuration.

* `header_value` - Header value of the header configuration.
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +A `url` block supports the following:
```suggestion
A `url` block exports the following:
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `components` - The components used to rewrite the URL. Possible values are `path_only` and `query_string_only` to limit the rewrite to the URL Path or URL Query String only.
```suggestion
* `components` - The components used to rewrite the URL.
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `reroute` - Whether the URL path map should be reevaluated after this rewrite has been applied. [More info on rewrite configutation](https://docs.microsoft.com/azure/application-gateway/rewrite-htt
```suggestion
* `reroute` - Whether the URL path map should be reevaluated after this rewrite has been applied.
```

2023-09-25 08:38 UTC, jackofallops commented on website/docs/r/application_gateway.html.markdown
> +-> **Please Note**: Availability Zones are [only supported in several regions at this time](https://docs.microsoft.com/azure/availability-zones/az-overview).  They are also only supported for [v2 SKU
```suggestion
-> **Please Note**: Availability Zones are not supported in all regions at this time. Please check the [official documentation](https://docs.microsoft.com/azure/availability-zones/az-overview) for more information.  They are also only supported for [v2 SKUs](https://docs.microsoft.com/azure/application-gateway/application-gateway-autoscaling-zone-redundant)
```

2023-09-26 06:03 UTC, teowa commented on website/docs/r/application_gateway.html.markdown
> -* `enable_http2` - (Optional) Is HTTP2 enabled on the application gateway resource?
This is at the `Argument Reference` section: https://github.com/hashicorp/terraform-provider-azurerm/blob/a4d566ea65bc2fdc18422d8003c06f74fc45eb6f/website/docs/r/application_gateway.html.markdown#L167

2023-09-26 06:10 UTC, teowa commented on internal/services/network/application_gateway_data_source.go
> +						"verify_client_cert_issuer_dn": {
This is because the data source use same `expand` function as in the resource, I will correct it.

2023-09-26 08:30 UTC, teowa commented
Thanks a lot for reviewing this, I have modified the code.

2023-10-04 10:20 UTC, jackofallops requested changes
Thanks @teowa - just a couple more changes to look over, thanks.

2023-10-04 10:20 UTC, jackofallops commented on website/docs/d/application_gateway.html.markdown
> +* `rewrite_rule` - One or more `rewrite_rule` blocks as defined above.
```suggestion
* `rewrite_rule` - One or more `rewrite_rule` blocks as defined below.
```

2023-10-04 10:20 UTC, jackofallops commented on website/docs/r/application_gateway.html.markdown
> -* `enable_http2` - (Optional) Is HTTP2 enabled on the application gateway resource?
it should be, but it's absent in the diff here?

2023-10-08 09:31 UTC, teowa commented on website/docs/d/application_gateway.html.markdown
> +* `rewrite_rule` - One or more `rewrite_rule` blocks as defined above.
fixed, thanks.

2023-10-08 09:33 UTC, teowa commented on website/docs/r/application_gateway.html.markdown
> -* `enable_http2` - (Optional) Is HTTP2 enabled on the application gateway resource?
There are duplications:
at `Argument Reference`:
https://github.com/hashicorp/terraform-provider-azurerm/blob/1bd5b7c2a17b1708b23bca84d3ab37b51f5f47bb/website/docs/r/application_gateway.html.markdown?plain=1#L167

and at `Attributes Reference`
https://github.com/hashicorp/terraform-provider-azurerm/blob/1bd5b7c2a17b1708b23bca84d3ab37b51f5f47bb/website/docs/r/application_gateway.html.markdown?plain=1#L696

the diff is to delete the one in `Attributes Reference` while keep it in `Argument Reference`

2023-10-12 07:50 UTC, manicminer approved these changes
Thanks for updating @teowa, just a few more docs changes but this otherwise LGTM

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `ssl_policy` - A `ssl_policy` block as defined below.
```suggestion
* `ssl_policy` - An `ssl_policy` block as defined below.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `name` - The Name of the Authentication Certificate to use.
```suggestion
* `name` - The Name of the Authentication Certificate in use.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `name` - The Name of the Trusted Root Certificate to use.
```suggestion
* `name` - The Name of the Trusted Root Certificate in use.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `fqdns` - A list of FQDN's which are part of the Backend Address Pool.
```suggestion
* `fqdns` - A list of FQDNs which are part of the Backend Address Pool.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `path` - The Path which is used as a prefix for all HTTP requests.
```suggestion
* `path` - The path which is used as a prefix for all HTTP requests.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `protocol` - The Protocol which will be used.
```suggestion
* `protocol` - The protocol which will be used.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `private_link_configuration_name` - The name of the private link configuration in use by this frontend IP configuration.
```suggestion
* `private_link_configuration_name` - The name of the Private Link configuration in use by this Frontend IP Configuration.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `private_link_configuration_id` - The ID of the associated private link configuration.
```suggestion
* `private_link_configuration_id` - The ID of the associated Private Link configuration.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `frontend_port_name` - The Name of the Frontend Port use for this HTTP Listener.
```suggestion
* `frontend_port_name` - The Name of the Frontend Port used for this HTTP Listener.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `require_sni` - Is Server Name Indication be Required?
```suggestion
* `require_sni` - Is Server Name Indication required?
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `body` - A snippet from the Response Body which will be present in the Response.
```suggestion
* `body` - A snippet from the Response Body which must be present in the Response.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `rewrite_rule_set_name` - The Name of the Rewrite Rule Set which is used for this URL Path Map.
```suggestion
* `rewrite_rule_set_name` - The Name of the Rewrite Rule Set which is used for this Path Rule.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `default_backend_address_pool_name` - The Name of the Default Backend Address Pool which is used for this URL Path Map. Cannot be set if `default_redirect_configuration_name` is set.
```suggestion
* `default_backend_address_pool_name` - The Name of the Default Backend Address Pool which is used for this URL Path Map.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `default_backend_http_settings_name` - The Name of the Default Backend HTTP Settings Collection which is used for this URL Path Map. Cannot be set if `default_redirect_configuration_name` is set.
```suggestion
* `default_backend_http_settings_name` - The Name of the Default Backend HTTP Settings Collection which is used for this URL Path Map.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `default_redirect_configuration_name` - The Name of the Default Redirect Configuration which is used for this URL Path Map. Cannot be set if either `default_backend_address_pool_name` or `default_b
```suggestion
* `default_redirect_configuration_name` - The Name of the Default Redirect Configuration which is used for this URL Path Map.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `verify_client_cert_issuer_dn` - Will client certificate issuer DN to be verified?
```suggestion
* `verify_client_cert_issuer_dn` - Will the client certificate issuer DN be verified?
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `min_protocol_version` - The minimal TLS version.
```suggestion
* `min_protocol_version` - The minimum TLS version.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `status_code` - Status code of the application gateway customer error.
```suggestion
* `status_code` - Status code of the application gateway custom error.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `custom_error_page_url` - Error page URL of the application gateway customer error.
```suggestion
* `custom_error_page_url` - Error page URL of the application gateway custom error.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `name` - Unique name of the rewrite rule set block
```suggestion
* `name` - Unique name of the Rewrite Rule Set
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `name` - Unique name of the rewrite rule block
```suggestion
* `name` - Unique name of the Rewrite Rule
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `rule_sequence` - Rule sequence of the rewrite rule that determines the order of execution in a set.
```suggestion
* `rule_sequence` - Rule sequence of the Rewrite Rule that determines the order of execution in a set.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `ignore_case` - Perform a case in-sensitive comparison.
```suggestion
* `ignore_case` - Whether a case insensitive comparison is performed.
```

2023-10-12 07:50 UTC, manicminer commented on website/docs/d/application_gateway.html.markdown
> +* `negate` - Negate the result of the condition evaluation.
```suggestion
* `negate` - Whether the result of the condition evaluation is negated.
```

2023-10-12 09:25 UTC, manicminer commented
Test results

<img width="594" alt="Screenshot 2023-10-12 at 10 24 49" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/251987/e21f40d1-9c82-4634-81f0-90c4dbe98415">

2023-10-12 09:25 UTC, merged

2023-10-12 10:11 UTC, teowa commented
Thanks @manicminer