`azurerm_windows_web_app` : fix the issue of incorrect application stack setting after updating the web app without changing the `application_stack` configuration
hashicorp/terraform-provider-azurerm pull request #23372
Opened 2023-09-25 08:37 UTC by sinbai

Two purposes of this PR:

- Application stack is incorrectly updated

 Symptom: 

> 1. Creating `azurerm_windows_web_app` with `site_config` as shown below.
> 
>   ```
> site_config {
> 	health_check_path           = "/health"
> 	load_balancing_mode="LeastRequests"
>     application_stack {
>         current_stack                = "java"
> 	    java_embedded_server_enabled = true
>         java_version                 = "11"
>       } 
> }
> ```
> 2. Update `azurerm_windows_web_app` and only change `health_check_eviction_time_in_min ` from null to 5 as follows.
>  
> ```
> site_config {
>         health_check_eviction_time_in_min = 5
> 	health_check_path           = "/health"
> 	load_balancing_mode="LeastRequests"
>         application_stack {
>            current_stack                = "java"
> 	    java_embedded_server_enabled = true
>             java_version                 = "11"
>         }
> }
> ```
> 
> Actual:
> <img width="392" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/39109137/b7ae270c-3200-437c-b124-dcefeef2da17">
> Expected:
> <img width="386" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/39109137/939fb0d4-fe19-4db0-8db8-c2353966136e">
> 
> Per the following code in the [existing](https://github.com/hashicorp/terraform-provider-azurerm/blob/6f8b827b654f0145d7f9f39b57b8784abb2b5df5/internal/services/appservice/windows_web_app_resource.go#L511C4-L511C4) in Read(), I assume this should also be added to Update() function to solve the above issue.
> 
> ```
> // Despite being part of the defined `Get` response model, site_config is always nil so we get it explicitly
> webAppSiteConfig, err := client.GetConfiguration(ctx, id.ResourceGroup, id.SiteName)
> if err != nil {
>    return fmt.Errorf("reading Site Config for Windows %s: %+v", id, err)
> }
> ```

- I assume that we should only set `JavaVersion` in Read() function when `currentStack` is `java`  since the API will return the value of `JavaVersion` that was once set.

Test result:
PASS: TestAccWindowsWebApp_updateAppStack (611.57s)

2023-11-17 09:53 UTC, jackofallops requested changes
Hi @sinbai - Thanks for this change and apologies for the delayed review as we've been discussing this internally trying to find a better way to work with the app_stack values for Windows apps. I've left one comment for an additional change, since the `current_stack` property is `Optional` we should not rely on it. Given that there is other reliance on the value already present, we're going to accept it, but we'll need the comment adding to the docs for now, and we'll be taking a look at addressing it appropriately for 4.0 as we believe it will require a breaking change in the longer term.
Thanks!

2023-11-20 05:44 UTC, sinbai commented on internal/services/appservice/helpers/windows_web_app_schema.go
> +	if currentStack == "java" {
Hi @jackofallops thanks for your feedback. The doc has been updated. Could you please take another look?

2023-11-22 08:53 UTC, jackofallops reviewed
Hi @sinbai - Thanks for adding the requested change.  During testing I've found that this is actually doesn't work as expected due to a slightly larger problem / bug. I'm investigating now and I may need to push some changes to your branch to fix the broader problem. If that happens, I'll get another maintainer to review my additions and we'll get this in as soon as it's all good and testing works as expected.

2023-11-22 15:53 UTC, tombuildsstuff approved these changes
LGTM 👍

2023-11-22 16:13 UTC, merged