Feature: MySQL Flex Server Auto IOPS Scaling
hashicorp/terraform-provider-azurerm pull request #23391
Opened 2023-09-26 13:44 UTC by Siddarthyuvaraj

2023-09-26 21:57 UTC, mbfrahry requested changes
Hey @Siddarthyuvaraj, this looks good but the tests are failing due to missing attributes. I've detailed more down below

2023-09-26 21:57 UTC, mbfrahry commented on internal/services/mysql/mysql_flexible_server_resource_test.go
>  `, r.template(data), data.RandomInteger, sizeGB, iops, enabled)
This test is failing as it's missing an argument down below
```suggestion
`, r.template(data), data.RandomInteger, sizeGB, iops, enabled, enabled)
```

2023-09-26 21:57 UTC, mbfrahry commented on internal/services/mysql/mysql_flexible_server_resource_test.go
> +	iops_auto_scaling = %t
This isn't lined up properly 
```suggestion
    iops_auto_scaling = %t
```

2023-09-26 21:57 UTC, mbfrahry commented on internal/services/mysql/mysql_flexible_server_resource_test.go
> +	iops_auto_scaling = false
And here 
```suggestion
    iops_auto_scaling = false
```

2023-09-27 05:14 UTC, Siddarthyuvaraj commented
Hi @mbfrahry i have made the changes. Please run the tests and let me know if any further changes required from my end. Thank you.

2023-09-27 05:40 UTC, stephybun commented
Thanks for this PR @Siddarthyuvaraj. 

Unfortunately we overlooked another PR that's already been opened to add this property. Since the other PR was opened earlier and is already in active review I'm going to close this one in favour of https://github.com/hashicorp/terraform-provider-azurerm/pull/23329.

Apologies for the confusion and thanks again for your contribution!

2023-09-27 05:40 UTC, closed without merging