New Resource: `
hashicorp/terraform-provider-azurerm pull request #23411
Opened 2023-09-28 06:27 UTC by ziyeqf

`azurerm_application_load_balancer` is also affected, and also tested.

test
---
```
❯ tftest servicenetworking TestAccApplicationLoadBalancer
=== RUN   TestAccApplicationLoadBalancerFrontend_basic
=== PAUSE TestAccApplicationLoadBalancerFrontend_basic
=== RUN   TestAccApplicationLoadBalancerFrontend_complete
=== PAUSE TestAccApplicationLoadBalancerFrontend_complete
=== RUN   TestAccApplicationLoadBalancerFrontend_update
=== PAUSE TestAccApplicationLoadBalancerFrontend_update
=== RUN   TestAccApplicationLoadBalancerFrontend_requiresImport
=== PAUSE TestAccApplicationLoadBalancerFrontend_requiresImport
=== RUN   TestAccApplicationLoadBalancer_basic
=== PAUSE TestAccApplicationLoadBalancer_basic
=== RUN   TestAccApplicationLoadBalancer_complete
=== PAUSE TestAccApplicationLoadBalancer_complete
=== RUN   TestAccApplicationLoadBalancer_update
=== PAUSE TestAccApplicationLoadBalancer_update
=== RUN   TestAccApplicationLoadBalancer_requiresImport
=== PAUSE TestAccApplicationLoadBalancer_requiresImport
=== CONT  TestAccApplicationLoadBalancerFrontend_basic
=== CONT  TestAccApplicationLoadBalancer_basic
=== CONT  TestAccApplicationLoadBalancer_update
=== CONT  TestAccApplicationLoadBalancer_requiresImport
=== CONT  TestAccApplicationLoadBalancer_complete
=== CONT  TestAccApplicationLoadBalancerFrontend_update
=== CONT  TestAccApplicationLoadBalancerFrontend_requiresImport
=== CONT  TestAccApplicationLoadBalancerFrontend_complete
--- PASS: TestAccApplicationLoadBalancer_requiresImport (662.87s)
--- PASS: TestAccApplicationLoadBalancer_basic (675.26s)
--- PASS: TestAccApplicationLoadBalancerFrontend_complete (695.94s)
--- PASS: TestAccApplicationLoadBalancer_update (737.62s)
--- PASS: TestAccApplicationLoadBalancer_complete (751.68s)
--- PASS: TestAccApplicationLoadBalancerFrontend_requiresImport (770.02s)
--- PASS: TestAccApplicationLoadBalancerFrontend_basic (778.00s)
--- PASS: TestAccApplicationLoadBalancerFrontend_update (919.29s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/servicenetworking     919.373s

```

2023-10-02 10:01 UTC, tombuildsstuff requested changes
hey @ziyeqf 

Thanks for this PR - I've taken a look through and left some comments inline, but I'm unsure why we've reverted the naming back to as in the previous PR, so can we fix this?

Thanks!

2023-10-12 02:51 UTC, ziyeqf commented
new test
---
```
terraform-provider-azurerm [ tengzh/alb/frontend][$⇡] [🐹 v1.21.1]
❯ tftest servicenetworking TestAccApplicationLoadBalancerFrontend
=== RUN   TestAccApplicationLoadBalancerFrontend_basic
=== PAUSE TestAccApplicationLoadBalancerFrontend_basic
=== RUN   TestAccApplicationLoadBalancerFrontend_complete
=== PAUSE TestAccApplicationLoadBalancerFrontend_complete
=== RUN   TestAccApplicationLoadBalancerFrontend_update
=== PAUSE TestAccApplicationLoadBalancerFrontend_update
=== RUN   TestAccApplicationLoadBalancerFrontend_requiresImport
=== PAUSE TestAccApplicationLoadBalancerFrontend_requiresImport
=== CONT  TestAccApplicationLoadBalancerFrontend_basic
=== CONT  TestAccApplicationLoadBalancerFrontend_update
=== CONT  TestAccApplicationLoadBalancerFrontend_requiresImport
=== CONT  TestAccApplicationLoadBalancerFrontend_complete
--- PASS: TestAccApplicationLoadBalancerFrontend_update (742.62s)
--- PASS: TestAccApplicationLoadBalancerFrontend_basic (756.34s)
--- PASS: TestAccApplicationLoadBalancerFrontend_requiresImport (759.31s)
--- PASS: TestAccApplicationLoadBalancerFrontend_complete (812.33s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/servicenetworking     812.387s
```

the CI failure seems caused by some loading reason, I do not have permision to re-trigger it. Could you please re-run it?

2023-10-19 14:54 UTC, catriona-m requested changes
Hi @ziyeqf - thanks for fixing this up, I left two minor comments but overall this is looking good! Thanks!

2023-10-19 14:54 UTC, catriona-m commented on internal/services/servicenetworking/application_load_balancer_frontend_resource.go
> +				return fmt.Errorf("updating `azurerm_alb_frontend` %s: %+v", *id, err)
```suggestion
				return fmt.Errorf("updating `azurerm_application_load_balancer_frontend` %s: %+v", *id, err)
```

2023-10-19 14:54 UTC, catriona-m commented on internal/services/servicenetworking/application_load_balancer_frontend_resource.go
> +				return fmt.Errorf("parsing %s: %+v", metadata.ResourceData.Id(), err)
```suggestion
				return err
```

2023-10-20 02:46 UTC, katbyte approved these changes
LGTM aside from a couple comments ⛈️

2023-10-20 02:46 UTC, katbyte commented on internal/services/servicenetworking/application_load_balancer_frontend_resource.go
> +
```suggestion

```

2023-10-20 02:46 UTC, katbyte commented on internal/services/servicenetworking/application_load_balancer_resource.go
> +			// tracked o https://github.com/Azure/azure-rest-api-specs/issues/26000n
```suggestion
			// tracked o https://github.com/Azure/azure-rest-api-specs/issues/26000
```

2023-10-20 02:46 UTC, katbyte commented on internal/services/servicenetworking/application_load_balancer_frontend_resource_test.go
> +	%s
```suggestion
%s
```

2023-10-20 02:46 UTC, katbyte commented on internal/services/servicenetworking/application_load_balancer_frontend_resource_test.go
> +	%s
```suggestion
%s
```

2023-10-20 02:46 UTC, katbyte approved these changes
LGTM aside from a couple comments ⛈️

2023-10-20 02:46 UTC, katbyte approved these changes
LGTM aside from a couple comments ⛈️

2023-10-20 03:22 UTC, merged