Auto PR: Regenerating based on (5881169b3df1fd58f770476a0462df15b39b7b97)
hashicorp/terraform-provider-azurerm pull request #23538
Opened 2023-10-12 16:35 UTC by hc-github-team-tf-azure

Regenerating the Terraform Provider based on the latest changes

2023-10-12 16:41 UTC, tombuildsstuff approved these changes

2023-10-12 16:41 UTC, tombuildsstuff commented on internal/services/devcenter/registration_gen.go
> +		"Dev Center Project",
This'll need fixing in Pandora, will PR this in the morning

2023-10-12 17:51 UTC, manicminer requested changes
The acctests may need to run serially as the maximum number of Dev Centers seems to be 2 in total, perhaps 1 per region.

2023-10-13 12:29 UTC, tombuildsstuff commented
> The acctests may need to run serially as the maximum number of Dev Centers seems to be 2 in total, perhaps 1 per region.

I was running this locally against `westeurope` provisioning 4 at a time yesterday, AFAIK the Quota is 5, but agreed on running this serially.

2023-10-13 14:11 UTC, tombuildsstuff commented on internal/services/devcenter/registration_gen.go
> +		"Dev Center Project",
https://github.com/hashicorp/pandora/pull/3160

2023-10-13 15:03 UTC, tombuildsstuff commented
Tests pass 👍 

There's a couple of additional changes in https://github.com/hashicorp/pandora/pull/3160 needed for this to ship, but this is fine to go for now.

2023-10-13 15:03 UTC, merged