Support for ExpressRoute direct MACsec SCI state
hashicorp/terraform-provider-azurerm pull request #23625
Opened 2023-10-20 00:44 UTC by jake-scott

Fixes 23624

2023-10-20 09:56 UTC, catriona-m requested changes
Hi @jake-scott - I've just left one minor comment on the docs but otherwise this is looking good! Thanks!

2023-10-20 09:56 UTC, catriona-m commented on website/docs/r/express_route_port.html.markdown
> +* `macsec_sci_enabled` - (Optional) Enable Secure Channel Identifier on the Express Route Port Link.
```suggestion
* `macsec_sci_enabled` - (Optional) Should Secure Channel Identifier on the Express Route Port Link be enabled? Defaults to `false`.
```

2023-10-20 13:54 UTC, jake-scott commented on website/docs/r/express_route_port.html.markdown
> +* `macsec_sci_enabled` - (Optional) Enable Secure Channel Identifier on the Express Route Port Link.
Thanks - update made and pushed.

2023-10-24 13:11 UTC, catriona-m approved these changes
Thanks @jake-scott LGTM!

2023-10-24 13:12 UTC, merged