Added dotnet_version 8 to both linux and windows function apps
hashicorp/terraform-provider-azurerm pull request #23638
Opened 2023-10-22 07:16 UTC by AdamCoulterOz

Fixes #23637 - adds support for dotnet 8 to both linux and windows function apps

2023-10-30 08:58 UTC, stephybun requested changes
Thanks for this PR @AdamCoulterOz. This looks fine but just to be sure and since this version is in preview, could you please add an acceptance test where we set `dotnet_version` to `8.0`?

2023-11-02 08:27 UTC, ilmax commented on internal/services/appservice/helpers/function_app_schema.go
> +	DotNetVersion         string `tfschema:"dotnet_version"`              // Supported values `v3.0`, `v4.0`, `v6.0`, `v7.0` and `v8.0`
Should this be 3.1 like everywhere else?

2023-11-02 10:35 UTC, AdamCoulterOz commented
> Thanks for this PR @AdamCoulterOz. This looks fine but just to be sure and since this version is in preview, could you please add an acceptance test where we set `dotnet_version` to `8.0`?

I will, I haven't had a chance yet. I'll do it in the next few days.

2023-11-16 03:51 UTC, AdamCoulterOz commented
@stephybun or @jackofallops can I please ask you to take a quick look at this? Thanks! 😀

2023-11-17 09:08 UTC, jackofallops approved these changes
Thanks @AdamCoulterOz - This LGTM now 👍

2023-11-17 09:12 UTC, merged