New Resource: `azurerm_dev_center_gallery`
hashicorp/terraform-provider-azurerm pull request #23760
Opened 2023-11-02 09:10 UTC by jiaweitao001

* Generated by Pandora code gen tool.

* All acc tests passed.

```
=== RUN   TestAccDevCenterGallery_basic
=== PAUSE TestAccDevCenterGallery_basic
=== RUN   TestAccDevCenterGallery_requiresImport
=== PAUSE TestAccDevCenterGallery_requiresImport
=== RUN   TestAccDevCenterGallery_complete
=== PAUSE TestAccDevCenterGallery_complete
=== RUN   TestAccDevCenterGallery_update
=== PAUSE TestAccDevCenterGallery_update
=== CONT  TestAccDevCenterGallery_basic
=== CONT  TestAccDevCenterGallery_complete
=== CONT  TestAccDevCenterGallery_update
=== CONT  TestAccDevCenterGallery_requiresImport
--- PASS: TestAccDevCenterGallery_update (1137.43s)
--- PASS: TestAccDevCenterGallery_basic (1231.93s)
--- PASS: TestAccDevCenterGallery_complete (1424.79s)
--- PASS: TestAccDevCenterGallery_requiresImport (1471.54s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/devcenter     1488.768s
```

2023-11-02 10:00 UTC, stephybun reviewed
@jiaweitao001 - I'm unsure if this PR was opened so that we can see the output of the generated resource from Pandora, but just to clarify:

_pandora generated resources are added to the azurerm repo by an automatically generated PR, they are not manually opened PRs with the resource output copied into it_

Please close this PR, review will continue in https://github.com/hashicorp/pandora/pull/3271

2024-02-06 08:26 UTC, stephybun requested changes
Thanks @jiaweitao001, the tests look good! Just need to rename the `gallery_resource_id` property (don't forget to update it in the tests and docs) and then this should be good to go!

2024-02-06 08:26 UTC, stephybun commented on internal/services/devcenter/dev_center_gallery_resource_gen.go
> +	GalleryResourceId string `tfschema:"gallery_resource_id"`
Like we did for the generated resource let's rename this to `shared_gallery_id`
```suggestion
	GalleryResourceId string `tfschema:"shared_gallery_id"`
```

2024-02-06 08:26 UTC, stephybun commented on internal/services/devcenter/dev_center_gallery_resource_gen.go
> +		"gallery_resource_id": {
```suggestion
		"shared_gallery_id": {
```

2024-02-06 09:37 UTC, stephybun approved these changes
Thanks @jiaweitao001 LGTM 👍

2024-02-06 09:38 UTC, merged

2024-02-07 12:37 UTC, tombuildsstuff commented
@jiaweitao001 FYI the generated files shouldn't be added by hand - the automation regenerates these based [on the files within the Pandora repository](https://github.com/hashicorp/pandora/blob/main/config/resources/devcenter.hcl) - so if these aren't defined there [they'll be removed by the automation when it next runs, as is happening here](https://github.com/hashicorp/terraform-provider-azurerm/pull/24805) - as such we need to add the definition for this Resource, so this doesn't get removed.

2024-02-08 01:34 UTC, jiaweitao001 commented
> @jiaweitao001 FYI the generated files shouldn't be added by hand - the automation regenerates these based [on the files within the Pandora repository](https://github.com/hashicorp/pandora/blob/main/config/resources/devcenter.hcl) - so if these aren't defined there [they'll be removed by the automation when it next runs, as is happening here](https://github.com/hashicorp/terraform-provider-azurerm/pull/24805) - as such we need to add the definition for this Resource, so this doesn't get removed.

Hi @tombuildsstuff , thanks for the reminder. This resource was added manually because we had trouble on generating the code with Pandora code gen tool. I'm wondering if we add a definition for the resource in Pandora, is the auto gen tool gonna skip this resource or overwrite it?

2024-02-08 10:01 UTC, tombuildsstuff commented
@jiaweitao001 forgot to circle back here after fixing this yesterday - apologies.

Reading the context in the other threads I ended up opening https://github.com/hashicorp/terraform-provider-azurerm/pull/24806 to rename these files so these are no longer generated - which'll fix this in a different manner.