Type change: azurerm_virtual_network.address_space to TypeSet
hashicorp/terraform-provider-azurerm pull request #23793
Opened 2023-11-06 21:17 UTC by tiwood

This changes `azurerm_virtual_network.address_space` from TypeList to TypeSet, because

* The Azure API is ignoring ordering changes to this property if only the ordering changes (aka endless plan diffs)
* The ordering as no technical effect on the network itself

Fixes #23328

2023-11-09 13:44 UTC, jackofallops requested changes
Hi @tiwood 
Thanks for this PR. Unfortunately a type change from a List to a Set is considered a breaking change in the schema, and given the importance and prevalence of use of this resource we're reluctant to do so to avoid breaking users configurations (for example, this would require changes to any interpolations of this field value). We understand the frustration of the diff, but this will need to be addressed in another way. I can suggest trying a `CustomiseDiff` which could normalise the order of this list for the old/new comparison and flag correct diffs appropriately.  Is this something you can look into? 

Alternatively, we can possibly reconsider this for a major version where we are better able to communicate and accept breaking changes

Thanks

2023-11-11 13:01 UTC, tiwood commented
Hi @jackofallops 
Thanks for the review. I've implemented a custom diff function to mimic the set behaviour.
WDYT?

2023-11-15 20:13 UTC, tiwood commented
Hi @jackofallops 
we're currently having huge diffs in one of our core automation stacks and merging this would really help us.
If we could get this on the way in the next days it would be much appreciated.

2023-11-30 14:41 UTC, tiwood commented
@jackofallops, @magodo, @tombuildsstuff 

Sorry for the random mention, I was wondering if this can be reviewed soon?

2023-12-07 17:50 UTC, tiwood commented
@katbyte maybe you can help reviewing this?

2024-01-24 12:02 UTC, tiwood commented
@jackofallops friendly ping

2024-04-08 15:10 UTC, tiwood commented
@stephybun, merging this PR is no longer a breaking change, as I've changed the implementation according to the requested changes.

I really would appreciate a review. (ping @tombuildsstuff)

2024-04-23 06:44 UTC, merged

2024-04-23 06:48 UTC, jackofallops reviewed
post-merge approval due to browser error 🙈