New Resource: `azurerm_container_app_job`
hashicorp/terraform-provider-azurerm pull request #23871
Opened 2023-11-12 02:18 UTC by jiaweitao001

* All tests passed.

```
--- PASS: TestAccContainerAppJob_manualTrigger (751.94s)
--- PASS: TestAccContainerAppJob_basic (753.25s)
--- PASS: TestAccContainerAppJob_eventTrigger (755.72s)
--- PASS: TestAccContainerAppJob_scheduleTrigger (808.98s)
```

2023-12-03 09:28 UTC, CaishenNefri commented
Hello @jiaweitao001  Great contribution! I am looking forward for this feature. 
But I am also curious why new resource is needed. I see in #23165 that maybe only additional parameters are needed. What do you think?

2023-12-04 08:32 UTC, ms-zhenhua requested changes
Hey @jiaweitao001,  I've taken a look through and left some comments inline. Kindly confirm. Once that's done I can take another look over.

2023-12-05 03:12 UTC, ms-zhenhua commented on internal/services/containerapps/helper.go
> +				"replica_timeout": {
```suggestion
				"replica_timeout_in_seconds": {
```

2024-01-03 14:26 UTC, catriona-m commented
Hi @jiaweitao001 - I noticed this PR is still marked as a draft, I just wanted to check if this is ready for a re-review? Thanks!

2024-01-08 08:24 UTC, jiaweitao001 commented
> Hi @jiaweitao001 - I noticed this PR is still marked as a draft, I just wanted to check if this is ready for a re-review? Thanks!

Hi @catriona-m, I've updated this PR as discussed offline with Zhenhua. Now it's reusing models already existed for container app resource.

2024-01-11 03:20 UTC, ms-zhenhua requested changes
@jiaweitao001 thank you for your updates.
I've taken a look through and left some comments inline. If we can fix those up, this should be good to go 👍

Thanks!

2024-01-11 03:20 UTC, ms-zhenhua commented on website/docs/r/container_app_job.html.markdown
> +A `template` block supports the following:
`init_container` is missing?

2024-01-11 03:20 UTC, ms-zhenhua commented on website/docs/r/container_app_job.html.markdown
> +    containers {
please also update other places
```suggestion
    container {
```

2024-01-11 03:20 UTC, ms-zhenhua commented on website/docs/r/container_app_job.html.markdown
> +* `containers` - (Optional) A `containers` block as defined below.
```suggestion
* `container` - (Required) One or more `container` blocks as detailed below.
```

2024-01-11 03:20 UTC, ms-zhenhua commented on website/docs/r/container_app_job.html.markdown
> +* `volumes` - (Optional) A `volumes` block as defined below.
```suggestion
* `volume` - (Optional) A `volume` block as detailed below.
```

2024-01-11 03:20 UTC, ms-zhenhua commented on website/docs/r/container_app_job.html.markdown
> +
shall we reuse the content from `container_app.html.markdown` ?

2024-01-11 03:20 UTC, ms-zhenhua commented on website/docs/r/container_app_job.html.markdown
> +* `polling_interval` - (Optional) Interval to check each event source in seconds.
```suggestion
* `polling_interval_in_seconds` - (Optional) Interval to check each event source in seconds.
```

2024-01-17 08:12 UTC, ms-zhenhua approved these changes

2024-01-18 22:22 UTC, Malagari commented
Looks good! Eager to start using this resource alongside our extensive container app environment.

2024-01-23 08:34 UTC, syepes commented
+1

2024-01-24 15:58 UTC, albal commented
@ms-zhenhua can this be merged or if it needs more reviewers can you tag them please?  We'd really like to get this running in our environment.

2024-01-25 13:19 UTC, eddy-vera commented
Same, we are using the az api for now, but using the native azurerm resource would be much better.

2024-01-30 00:41 UTC, loadaverage commented
Highly needed for my use case as well. Checks are green, would be very good to have another check from @katbyte @tombuildsstuff @ms-zhenhua

2024-01-31 13:03 UTC, pavel-krasnousov-LX commented
Waiting for this update...

2024-02-07 00:48 UTC, loadaverage commented
I was forced to build a provider from that branch and use it in Terraform Cloud as private provider. As I don't want to mix bicep with azurerm and unfortunately can't wait so long. Thank your for contribution!

2024-02-07 07:25 UTC, Miouge1 commented
Thank you!

This resource is useful for example to manage Azure DevOps or GitHub self hosted agents, like in https://learn.microsoft.com/en-us/azure/container-apps/tutorial-ci-cd-runners-jobs

It would be great if a maintainer could give some feedback. @stephybun maybe?

2024-02-07 09:57 UTC, syepes commented
Welcome to the reality of the hashicorp community contributions, now you can better understand one of the main motivations of the [OpenTofu](https://opentofu.org/) fork

2024-02-07 10:05 UTC, gercograndia commented
> Welcome to the reality of the hashicorp community contributions, now you can better understand one of the main motivations of the [OpenTofu](https://opentofu.org/) fork

True but `opentofu` is not gonna solve this.

2024-02-13 00:07 UTC, mbfrahry requested changes
Hey @jiaweitao001, I'm seeing issues when building this out 

```
# github.com/hashicorp/go-azure-sdk/resource-manager/containerapps/2023-05-01/jobs
../../../vendor/github.com/hashicorp/go-azure-sdk/resource-manager/containerapps/2023-05-01/jobs/id_execution.go:13:32: cannot use ExecutionId{} (value of type ExecutionId) as resourceids.ResourceId value in variable declaration: ExecutionId does not implement resourceids.ResourceId (method FromParseResult has pointer receiver)
../../../vendor/github.com/hashicorp/go-azure-sdk/resource-manager/containerapps/2023-05-01/jobs/id_execution.go:35:52: cannot use ExecutionId{} (value of type ExecutionId) as resourceids.ResourceId value in argument to resourceids.NewParserFromResourceIdType: ExecutionId does not implement resourceids.ResourceId (method FromParseResult has pointer receiver)
../../../vendor/github.com/hashicorp/go-azure-sdk/resource-manager/containerapps/2023-05-01/jobs/id_execution.go:52:52: cannot use ExecutionId{} (value of type ExecutionId) as resourceids.ResourceId value in argument to resourceids.NewParserFromResourceIdType: ExecutionId does not implement resourceids.ResourceId (method FromParseResult has pointer receiver)
../../../vendor/github.com/hashicorp/go-azure-sdk/resource-manager/containerapps/2023-05-01/jobs/id_job.go:13:32: cannot use JobId{} (value of type JobId) as resourceids.ResourceId value in variable declaration: JobId does not implement resourceids.ResourceId (method FromParseResult has pointer receiver)
../../../vendor/github.com/hashicorp/go-azure-sdk/resource-manager/containerapps/2023-05-01/jobs/id_job.go:33:52: cannot use JobId{} (value of type JobId) as resourceids.ResourceId value in argument to resourceids.NewParserFromResourceIdType: JobId does not implement resourceids.ResourceId (method FromParseResult has pointer receiver)
../../../vendor/github.com/hashicorp/go-azure-sdk/resource-manager/containerapps/2023-05-01/jobs/id_job.go:50:52: cannot use JobId{} (value of type JobId) as resourceids.ResourceId value in argument to resourceids.NewParserFromResourceIdType: JobId does not implement resourceids.ResourceId (method FromParseResult has pointer receiver)
Process exited with code 1
```

could you chase that down before we continue with the review?

2024-02-13 01:58 UTC, jiaweitao001 commented
> Hey @jiaweitao001, I'm seeing issues when building this out
> 
> ```
> # github.com/hashicorp/go-azure-sdk/resource-manager/containerapps/2023-05-01/jobs
> ../../../vendor/github.com/hashicorp/go-azure-sdk/resource-manager/containerapps/2023-05-01/jobs/id_execution.go:13:32: cannot use ExecutionId{} (value of type ExecutionId) as resourceids.ResourceId value in variable declaration: ExecutionId does not implement resourceids.ResourceId (method FromParseResult has pointer receiver)
> ../../../vendor/github.com/hashicorp/go-azure-sdk/resource-manager/containerapps/2023-05-01/jobs/id_execution.go:35:52: cannot use ExecutionId{} (value of type ExecutionId) as resourceids.ResourceId value in argument to resourceids.NewParserFromResourceIdType: ExecutionId does not implement resourceids.ResourceId (method FromParseResult has pointer receiver)
> ../../../vendor/github.com/hashicorp/go-azure-sdk/resource-manager/containerapps/2023-05-01/jobs/id_execution.go:52:52: cannot use ExecutionId{} (value of type ExecutionId) as resourceids.ResourceId value in argument to resourceids.NewParserFromResourceIdType: ExecutionId does not implement resourceids.ResourceId (method FromParseResult has pointer receiver)
> ../../../vendor/github.com/hashicorp/go-azure-sdk/resource-manager/containerapps/2023-05-01/jobs/id_job.go:13:32: cannot use JobId{} (value of type JobId) as resourceids.ResourceId value in variable declaration: JobId does not implement resourceids.ResourceId (method FromParseResult has pointer receiver)
> ../../../vendor/github.com/hashicorp/go-azure-sdk/resource-manager/containerapps/2023-05-01/jobs/id_job.go:33:52: cannot use JobId{} (value of type JobId) as resourceids.ResourceId value in argument to resourceids.NewParserFromResourceIdType: JobId does not implement resourceids.ResourceId (method FromParseResult has pointer receiver)
> ../../../vendor/github.com/hashicorp/go-azure-sdk/resource-manager/containerapps/2023-05-01/jobs/id_job.go:50:52: cannot use JobId{} (value of type JobId) as resourceids.ResourceId value in argument to resourceids.NewParserFromResourceIdType: JobId does not implement resourceids.ResourceId (method FromParseResult has pointer receiver)
> Process exited with code 1
> ```
> 
> could you chase that down before we continue with the review?

@mbfrahry , this is caused by a dependency upgrade happened recently. I'll update the code accordingly.

2024-02-13 18:45 UTC, mbfrahry requested changes
The tests are failing because the image couldn't be parsed. Could you take a look at fixing the tests up? 

```
        Error: creating Job
        Resource Group Name: "acctest-CAJob240213103743537379"
        Job Name: "acctest-cajob240213103743537379"): performing CreateOrUpdate: jobs.JobsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameterValueInContainerTemplate" Message="The following field(s) are either invalid or missing. Field 'template.containers.testcontainerappsjob0.image' is invalid with details: 'Invalid value: \"repo/testcontainerAppsJob0:v1\": could not parse reference: repo/testcontainerAppsJob0:v1';."
```

2024-02-14 09:34 UTC, jiaweitao001 commented
> The tests are failing because the image couldn't be parsed. Could you take a look at fixing the tests up?
> 
> ```
>         Error: creating Job
>         Resource Group Name: "acctest-CAJob240213103743537379"
>         Job Name: "acctest-cajob240213103743537379"): performing CreateOrUpdate: jobs.JobsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameterValueInContainerTemplate" Message="The following field(s) are either invalid or missing. Field 'template.containers.testcontainerappsjob0.image' is invalid with details: 'Invalid value: \"repo/testcontainerAppsJob0:v1\": could not parse reference: repo/testcontainerAppsJob0:v1';."
> ```

@mbfrahry Updated.

2024-02-23 22:07 UTC, syepes commented
Any news on this?

2024-02-26 09:06 UTC, pavel-krasnousov-LX commented
> Any news on this?

Lets wait until next changes in API or core, when author need to update code again because of the failed tests
Ask author to update the code.
Keep silence for a few weeks.
Repeat

2024-02-27 11:09 UTC, guibranco commented
@mbfrahry, is this fixed now and can it be merged?

2024-03-05 14:11 UTC, FakieHeelflip commented
Guys, please merge. Would be awesome.

2024-03-05 16:48 UTC, tombuildsstuff commented
Hey Folks

Unfortunately we're busy with other priorities at the moment, but @jackofallops will take a look as soon as he can.

Whilst we appreciate the enthusiasm around this PR, we'd ask that you refrain from posting `when will this be merged` or similar comments, since these actually delays us reviewing this due to phantom notifications - but we'll take a look as soon as we can.

Thanks!

2024-03-27 10:03 UTC, jackofallops requested changes
Hi @jiaweitao001 - Thanks for this. I've taken a look over and left some comments / changes below if you can take a look?  Once they're done I'll continue review and get the tests run.

Thanks!

2024-03-27 10:03 UTC, jackofallops commented on website/docs/r/container_app_job.html.markdown
> +* `termination_grace_period_seconds` -  The time in seconds after the container is sent the termination signal before the process if forcibly killed.
Can we move this to the bottom?

2024-03-28 02:31 UTC, jiaweitao001 commented on internal/services/containerapps/container_app_job_resource.go
> +				Name:     pointer.To(model.Name),
`Location` is a required by the API, it will throw error if it's omitted. We can omit `Name` here.

2024-03-28 02:31 UTC, jiaweitao001 commented on internal/services/containerapps/container_app_job_resource.go
> +						ReplicaTimeout:    int64(model.ReplicaTimeoutInSeconds),
Will change.

2024-03-28 02:31 UTC, jiaweitao001 commented on internal/services/containerapps/container_app_job_resource.go
> +						}
Will change.

2024-03-28 02:31 UTC, jiaweitao001 commented on internal/services/containerapps/container_app_job_resource.go
> +				model.Properties.Configuration.ReplicaRetryLimit = pointer.To(int64(state.ReplicaRetryLimit))
Will change.

2024-03-28 02:31 UTC, jiaweitao001 commented on internal/services/containerapps/container_app_job_resource.go
> +				model.Properties.Configuration.ReplicaTimeout = int64(state.ReplicaTimeoutInSeconds)
Will change.

2024-03-28 02:31 UTC, jiaweitao001 commented on internal/services/containerapps/container_app_job_resource_test.go
> +func TestAccContainerAppJob_eventTrigger(t *testing.T) {
Chaning trigger types is not supported by the API.

2024-03-28 02:31 UTC, jiaweitao001 commented on internal/services/containerapps/container_app_job_resource_test.go
> +  }
Sure, I'll remove this.

2024-03-28 02:31 UTC, jiaweitao001 commented on internal/services/containerapps/helpers/container_app_job.go
> +	ReplicaCompletionCount int          `tfschema:"replica_completion_count"`
Will do.

2024-03-28 02:31 UTC, jiaweitao001 commented on internal/services/containerapps/helpers/container_app_job.go
> +	ReplicaCompletionCount int    `tfschema:"replica_completion_count"`
Will do.

2024-03-28 02:31 UTC, jiaweitao001 commented on internal/services/containerapps/helpers/container_app_job.go
> +	ReplicaCompletionCount int `tfschema:"replica_completion_count"`
Will do.

2024-03-28 02:31 UTC, jiaweitao001 commented on internal/services/containerapps/helpers/container_app_job.go
> +	PollingInterval int         `tfschema:"polling_interval_in_seconds"`
Will do.

2024-03-28 02:31 UTC, jiaweitao001 commented on internal/services/containerapps/helpers/container_app_job.go
> +			container.Command = &v.Command
Will do.

2024-03-28 02:35 UTC, jiaweitao001 commented on internal/services/containerapps/container_app_job_resource_test.go
> +func (r ContainerAppJobResource) basicUpdate(data acceptance.TestData) string {
Will remove.

2024-04-02 05:38 UTC, jiaweitao001 commented
Hi @jackofallops , I've addressed the comments as requested.

2024-04-22 09:20 UTC, jackofallops requested changes
Hi @jiaweitao001 - Thanks for the updates.  Some additional changes needed below for Identity and it appears we're completely missing the updates for Secrets and testing for them?  Can you take a look? 

Thanks

2024-04-25 10:21 UTC, jiaweitao001 commented on internal/services/containerapps/container_app_job_resource.go
> +					state.Identity = pointer.From(ident)
Will change.

2024-04-25 10:21 UTC, jiaweitao001 commented on internal/services/containerapps/container_app_job_resource.go
> +			job.Identity = pointer.To(identity.LegacySystemAndUserAssignedMap(*ident))
Will do.

2024-04-25 10:22 UTC, jiaweitao001 commented on internal/services/containerapps/container_app_job_resource.go
> +				model.Identity = pointer.To(identity.LegacySystemAndUserAssignedMap(*ident))
Will do.

2024-05-07 05:17 UTC, jackofallops approved these changes
Hi @jiaweitao001 - Thanks for the changes, I think this looks good to me now 👍

2024-05-07 05:18 UTC, jackofallops commented
Tests look good:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/11830746/de9557ab-423c-4e63-80ce-f2c00419a0e0)

2024-05-07 05:18 UTC, merged

2024-05-10 14:02 UTC, kaedroho commented on website/docs/r/container_app_job.html.markdown
> +A `rules` block supports the following:
This block seems to do the same job as [`custom_scale_rule`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_app#custom_scale_rule) on regular container apps. Unclear why there is a new syntax for container app jobs

2024-05-10 21:10 UTC, kaedroho commented on website/docs/r/container_app_job.html.markdown
> +* `secrets` - (Optional) A `secrets` block as defined below.
Noticed another one `registries` => `registry`