`azurerm_monitor_data_collection_rule` - support `WorkspaceTransforms` for `kind`
hashicorp/terraform-provider-azurerm pull request #23873
Opened 2023-11-13 03:40 UTC by teowa

Resolves #23868 
From the [Azure doc](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/tutorial-workspace-transformations-api#create-data-collection-rule-dcr), `kind` can be set as `WorkspaceTransforms`.

2023-11-15 07:47 UTC, teowa commented
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/104055472/e2aa9369-af13-42b5-ac24-fa5010a26b06)

2023-11-16 09:33 UTC, stephybun requested changes

2023-11-16 09:33 UTC, stephybun commented on website/docs/r/monitor_data_collection_rule.html.markdown
> +* `kind` - (Optional) The kind of the Data Collection Rule. Possible values are `Linux`, `Windows`, `AgentDirectToStore`,and `WorkspaceTransforms`. A rule of kind `Linux` does not allow for `windows_
```suggestion
* `kind` - (Optional) The kind of the Data Collection Rule. Possible values are `Linux`, `Windows`, `AgentDirectToStore` and `WorkspaceTransforms`. A rule of kind `Linux` does not allow for `windows_event_log` data sources. And a rule of kind `Windows` does not allow for `syslog` data sources. If kind is not specified, all kinds of data sources are allowed.
```

2023-11-16 09:33 UTC, stephybun reviewed
@teowa docs require a minor fix otherwise this is good to go.

2023-11-16 09:58 UTC, stephybun approved these changes
Thanks @teowa LGTM 👍

2023-11-16 09:58 UTC, merged