New data source: `azurerm_monitor_workspace`
hashicorp/terraform-provider-azurerm pull request #23928
Opened 2023-11-17 01:01 UTC by favoretti

Fixes #23905

2023-11-17 10:29 UTC, favoretti commented
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/805046/6a355ee2-ef93-4b8a-927b-b0b2813d9977)

2023-11-20 13:52 UTC, stephybun requested changes
Thanks for this PR @favoretti.

Overall this looks good, but we should define a data source model and use that when encoding/decoding. Once that's done this should be good to go!

2023-11-20 13:52 UTC, stephybun commented on internal/services/monitor/monitor_workspace_data_source.go
> +}
We should define the data source model here.

2023-11-20 13:52 UTC, stephybun commented on internal/services/monitor/monitor_workspace_data_source.go
> +			var state WorkspaceResourceModel
Although the resource and data source models might be identical now they could drift over time, so we should define a data source model above and use that here.

2023-11-20 13:52 UTC, stephybun commented on website/docs/d/monitor_workspace.html.markdown
> +* `public_network_access_enabled` - Whether network access from public internet to the Workspace are allowed. Possible values are `true` and `false`.
```suggestion
* `public_network_access_enabled` - Whether network access from public internet to the Workspace are allowed.
```

2023-11-20 13:52 UTC, stephybun commented on website/docs/d/monitor_workspace.html.markdown
> +* `tags` - A mapping of tags which should be assigned to the Data Collection Endpoint.
```suggestion
* `tags` - A mapping of tags that are assigned to the Workspace.
```

2023-11-21 07:39 UTC, stephybun approved these changes
Thanks @favoretti LGTM 👍

2023-11-21 07:40 UTC, merged