`azurerm_data_factory_flowlet_data_flow`: Optional source and sink properties
hashicorp/terraform-provider-azurerm pull request #23987
Opened 2023-11-22 13:03 UTC by ashenm

…perties

2023-11-28 16:12 UTC, catriona-m requested changes
Thanks for submitting this @ashenm - I spotted a typo that I've commented inline but otherwise this is looking good. Thanks!

2023-11-28 16:12 UTC, catriona-m commented on internal/services/datafactory/data_factory_data_flow.go
> +func resourceSouceAndSink() *pluginsdk.Resource {
```suggestion
func resourceSourceAndSink() *pluginsdk.Resource {
```

2023-11-29 04:13 UTC, ashenm commented on internal/services/datafactory/data_factory_data_flow.go
> +func resourceSouceAndSink() *pluginsdk.Resource {
@catriona-m fixed 🙌

2023-11-29 14:14 UTC, catriona-m approved these changes
Thanks @ashenm LGTM!

2023-11-29 14:15 UTC, merged