`azurerm_spring_cloud_gateway` - use pandora SDK
hashicorp/terraform-provider-azurerm pull request #23998
Opened 2023-11-23 05:07 UTC by ms-henglu

2023-11-23 06:07 UTC, magodo requested changes
Thanks for this PR!
I have left some additional mostly minor comments that once addressed this should be good to merge 👍

2023-11-23 06:07 UTC, magodo commented on internal/services/springcloud/spring_cloud_gateway_resource.go
> +	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
We shall stick on using `pluginsdk` instead.

2023-11-23 06:07 UTC, magodo commented on internal/services/springcloud/spring_cloud_gateway_resource.go
> +			if service.Model.Sku == nil || service.Model.Sku.Name == nil || service.Model.Sku.Tier == nil {
We shall also nil check `service.Model`

2023-11-23 06:07 UTC, magodo commented on internal/services/springcloud/spring_cloud_gateway_resource.go
> +			if props := resp.Model.Properties; props != nil {
We shall also nil check `resp.Model`.

2023-12-05 03:33 UTC, ms-henglu commented
https://github.com/hashicorp/terraform-provider-azurerm/pull/24116

2023-12-05 03:33 UTC, closed without merging