Feat add azure containers cache
hashicorp/terraform-provider-azurerm pull request #24040
Opened 2023-11-28 00:37 UTC by mhaligowski

2023-12-29 20:17 UTC, aristosvo requested changes
Hi @mhaligowski! Thanks for all this! I gave you a few pointers to start with, as I don't expect a review from the HC maintainers these days, they will have probably a few more remarks.

There are two tests failing as well:
```
------- Stdout: -------
=== RUN   TestAccContainerRegistryCacheRule_basic
=== PAUSE TestAccContainerRegistryCacheRule_basic
=== CONT  TestAccContainerRegistryCacheRule_basic
    testcase.go:113: Step 1/2 error: Error running pre-apply refresh: exit status 1
        Error: Unsupported argument
          on terraform_plugin_test.tf line 35, in resource "azurerm_container_registry_cache_rule" "test":
          35:   resource_group_name = azurerm_resource_group.test.name
        An argument named "resource_group_name" is not expected here.
--- FAIL: TestAccContainerRegistryCacheRule_basic (2.78s)
FAIL
```
```
------- Stdout: -------
=== RUN   TestAccContainerRegistryCacheRule_requiresImport
=== PAUSE TestAccContainerRegistryCacheRule_requiresImport
=== CONT  TestAccContainerRegistryCacheRule_requiresImport
    testcase.go:113: Step 1/2 error: Error running pre-apply refresh: exit status 1
        Error: Unsupported argument
          on terraform_plugin_test.tf line 35, in resource "azurerm_container_registry_cache_rule" "test":
          35:   resource_group_name = azurerm_resource_group.test.name
        An argument named "resource_group_name" is not expected here.
--- FAIL: TestAccContainerRegistryCacheRule_requiresImport (3.10s)
FAIL
```

Hope you enjoy the last bits of 2023!

2023-12-29 20:17 UTC, aristosvo commented on internal/services/containers/container_registry_cache_rule_resource.go
> +		"registry": {
I would opt for `container_registry_id` here, which contains both the resource group name and registry name, as input.

How to work with that ID is shown here: https://github.com/hashicorp/terraform-provider-azurerm/blob/46a95c1b799aca661d980992e65779e8576178e7/internal/services/containers/container_registry_task_resource.go#L126

2023-12-29 20:17 UTC, aristosvo commented on internal/services/containers/container_registry_cache_rule_resource.go
> +	return validate.ContainerRegistryCacheRuleID
I believe you can replace the `validate` package with the content of `cacherules` in the new SDK, like this:
```suggestion
	return cacherules.ValidateCacheRuleID
```

2023-12-29 20:17 UTC, aristosvo commented on internal/services/containers/resourceids.go
> +//go:generate go run ../../tools/generator-resource-id/main.go -path=./ -name=ContainerRegistryCacheRule -id=/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/group1/providers/Micros
If you don't need the `validate` package for ID validation, you can remove this resource ID entry as well!

2023-12-29 20:17 UTC, aristosvo commented on internal/services/containers/client/client.go
> +	cacheRulesClient, err := cacherules.NewCacheRulesClientWithBaseURI(o.Environment.ResourceManager)
I don't think this declaration of the cacheRulesClient is necessary for the new SDK clients anymore

2023-12-29 20:17 UTC, aristosvo commented on internal/services/containers/container_registry_cache_rule_resource_test.go
> +func TestAccContainerRegistryCacheRuleName_validation(t *testing.T) {
This `validate` function is already tested in its own package (and you won't need it after all)

2024-01-05 07:37 UTC, mhaligowski commented
> Hi @mhaligowski! Thanks for all this! I gave you a few pointers to start with, as I don't expect a review from the HC maintainers these days, they will have probably a few more remarks.
> 
> There are two tests failing as well:
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccContainerRegistryCacheRule_basic
> === PAUSE TestAccContainerRegistryCacheRule_basic
> === CONT  TestAccContainerRegistryCacheRule_basic
>     testcase.go:113: Step 1/2 error: Error running pre-apply refresh: exit status 1
>         Error: Unsupported argument
>           on terraform_plugin_test.tf line 35, in resource "azurerm_container_registry_cache_rule" "test":
>           35:   resource_group_name = azurerm_resource_group.test.name
>         An argument named "resource_group_name" is not expected here.
> --- FAIL: TestAccContainerRegistryCacheRule_basic (2.78s)
> FAIL
> ```
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccContainerRegistryCacheRule_requiresImport
> === PAUSE TestAccContainerRegistryCacheRule_requiresImport
> === CONT  TestAccContainerRegistryCacheRule_requiresImport
>     testcase.go:113: Step 1/2 error: Error running pre-apply refresh: exit status 1
>         Error: Unsupported argument
>           on terraform_plugin_test.tf line 35, in resource "azurerm_container_registry_cache_rule" "test":
>           35:   resource_group_name = azurerm_resource_group.test.name
>         An argument named "resource_group_name" is not expected here.
> --- FAIL: TestAccContainerRegistryCacheRule_requiresImport (3.10s)
> FAIL
> ```
> 
> Hope you enjoy the last bits of 2023!

I did, thanks :) I'll try pushing it through in the first week of 2024 :)

2024-03-21 23:17 UTC, katbyte commented
@mhaligowski - is this PR now ready to be reviewed? it has been in draft for a while

2024-05-15 14:18 UTC, closed without merging

2024-05-15 14:18 UTC, stephybun commented
Going to close this for the moment since we haven't heard back. Let us know when you're ready to come back to this @mhaligowski and we can re-open this!