`azurerm_batch_pool` - fixes `TestAccBatchPool_extensions`
hashicorp/terraform-provider-azurerm pull request #24075
Opened 2023-11-30 05:08 UTC by liuwuliuyun

`azurerm_batch_pool`
- fixes `TestAccBatchPool_extensions`
- fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/20530
- change test case to be functional

Testing Evidence:
```
Running on TC
```

2023-11-30 05:54 UTC, WodansSon approved these changes
Hi @liuwuliuyun, thanks for opening this PR. I've given it a look an this LGTM. 🚀

2023-12-05 15:06 UTC, stephybun requested changes
Two minor comments on the error messages, would you mind fixing those? This should be good to go then.

2023-12-05 15:06 UTC, stephybun commented on internal/services/batch/batch_pool.go
> +			return nil, err
Can we wrap this error for a bit more info
```suggestion
			return nil, fmt.Errorf("unmarshaling `settings_json`: %+v", err)
```

2023-12-05 15:06 UTC, stephybun commented on internal/services/batch/batch_pool.go
> +			return nil, err
```suggestion
			return nil, fmt.Errorf("unmarshaling `protected_settings`: %+v", err)
```

2023-12-11 08:15 UTC, stephybun approved these changes
Thanks @liuwuliuyun LGTM 👍

2023-12-11 08:16 UTC, merged