`azurerm_spring_cloud_gateway` - split to create/update functions
hashicorp/terraform-provider-azurerm pull request #24116
Opened 2023-12-05 03:32 UTC by ms-henglu

2023-12-05 08:32 UTC, stephybun requested changes

2023-12-05 08:32 UTC, stephybun commented on internal/services/springcloud/spring_cloud_gateway_resource.go
> +			return fmt.Errorf("checking for existing %s: %+v", id, err)
```suggestion
			return fmt.Errorf("retrieving %s: %+v", id, err)
```

2023-12-05 08:32 UTC, stephybun commented on internal/services/springcloud/spring_cloud_gateway_resource.go
> +		return fmt.Errorf("retreiving %s: sku was nil", id)
Retrieving is mispelled here

2023-12-05 08:32 UTC, stephybun commented on internal/services/springcloud/spring_cloud_gateway_resource.go
> +	}
Please update the error messages in the create as well 
```suggestion
		return fmt.Errorf("updating %s: %+v", id, err)
	}

	if err := future.WaitForCompletionRef(ctx, client.Client); err != nil {
		return fmt.Errorf("waiting for update of %s: %+v", id, err)
	}
```

2023-12-06 02:08 UTC, ms-henglu commented
Hi @stephybun ,

Thanks for the code review! I've updated this PR as suggested, please take another look.

2023-12-06 07:45 UTC, stephybun requested changes

2023-12-06 07:45 UTC, stephybun commented on internal/services/springcloud/spring_cloud_gateway_resource.go
> +		return fmt.Errorf("retreiving %s: properties was nil", id)
still misspelled here

2023-12-06 08:04 UTC, stephybun approved these changes
Thanks @ms-henglu LGTM 👍

2023-12-06 08:14 UTC, merged