`azurerm_spring_cloud_api_portal` - split to create/update functions
hashicorp/terraform-provider-azurerm pull request #24115
Opened 2023-12-05 03:29 UTC by ms-henglu

```
=== RUN   TestAccSpringCloudAPIPortal_basic
=== PAUSE TestAccSpringCloudAPIPortal_basic
=== CONT  TestAccSpringCloudAPIPortal_basic
=== RUN   TestAccSpringCloudAPIPortal_requiresImport
=== PAUSE TestAccSpringCloudAPIPortal_requiresImport
=== CONT  TestAccSpringCloudAPIPortal_requiresImport
=== RUN   TestAccSpringCloudAPIPortal_complete
=== PAUSE TestAccSpringCloudAPIPortal_complete
=== CONT  TestAccSpringCloudAPIPortal_complete
=== RUN   TestAccSpringCloudAPIPortal_update
=== PAUSE TestAccSpringCloudAPIPortal_update
=== CONT  TestAccSpringCloudAPIPortal_update
--- PASS: TestAccSpringCloudAPIPortal_requiresImport (846.38s)
--- PASS: TestAccSpringCloudAPIPortal_update (849.44s)
--- PASS: TestAccSpringCloudAPIPortal_complete (904.65s)
--- PASS: TestAccSpringCloudAPIPortal_basic (1033.62s)
PASS

```

2023-12-05 08:30 UTC, stephybun requested changes
Thanks @ms-henglu. Tests look fine, but there are some typos in the error messages.

2023-12-05 08:30 UTC, stephybun commented on internal/services/springcloud/spring_cloud_api_portal_resource.go
> +			return fmt.Errorf("retreiving %s: %+v", id, err)
This is misspelled multiple times, please fix all of them
```suggestion
			return fmt.Errorf("retrieving %s: %+v", id, err)
```

2023-12-05 08:30 UTC, stephybun commented on internal/services/springcloud/spring_cloud_api_portal_resource.go
> +		return fmt.Errorf("waiting for creation/update of %s: %+v", id, err)
The error messaged in the create function also need to be updated.
```suggestion
		return fmt.Errorf("updating %s: %+v", id, err)
	}

	if err := future.WaitForCompletionRef(ctx, client.Client); err != nil {
		return fmt.Errorf("waiting for update of %s: %+v", id, err)
```

2023-12-06 02:08 UTC, ms-henglu commented
Hi @stephybun ,

Thanks for the code review! I've updated this PR as suggested, please take another look.

2023-12-06 07:43 UTC, stephybun approved these changes
Thanks @ms-henglu LGTM 👍

2023-12-06 07:45 UTC, merged