azurerm_virtual_machine_data_disk_attachment: Ignore applications
hashicorp/terraform-provider-azurerm pull request #24145
Opened 2023-12-07 07:38 UTC by jkroepke

2024-01-04 02:16 UTC, katbyte approved these changes
Thanks @jkroepke - LGTM 🚋

2024-01-04 02:17 UTC, katbyte requested changes
checking the tests looks like we have a failure:
```
------- Stdout: -------
=== RUN   TestAccVirtualMachineDataDiskAttachment_virtualMachineApplication
=== PAUSE TestAccVirtualMachineDataDiskAttachment_virtualMachineApplication
=== CONT  TestAccVirtualMachineDataDiskAttachment_virtualMachineApplication
    testcase.go:113: Step 1/2 error: Error running pre-apply refresh: exit status 1
        
        Error: Missing required argument
        
          on terraform_plugin_test.tf line 115, in resource "azurerm_linux_virtual_machine" "test":
         115: resource "azurerm_linux_virtual_machine" "test" {
        
        The argument "admin_username" is required, but no definition was found.
        
        Error: Missing required argument
        
          on terraform_plugin_test.tf line 115, in resource "azurerm_linux_virtual_machine" "test":
         115: resource "azurerm_linux_virtual_machine" "test" {
        
        The argument "size" is required, but no definition was found.
        
        Error: Insufficient os_disk blocks
        
          on terraform_plugin_test.tf line 115, in resource "azurerm_linux_virtual_machine" "test":
         115: resource "azurerm_linux_virtual_machine" "test" {
        
        At least 1 "os_disk" blocks are required.
        
        Error: Unsupported argument
        
          on terraform_plugin_test.tf line 120, in resource "azurerm_linux_virtual_machine" "test":
         120:   vm_size               = "Standard_F4"
        
        An argument named "vm_size" is not expected here.
        
        Error: Unsupported argument
        
          on terraform_plugin_test.tf line 122, in resource "azurerm_linux_virtual_machine" "test":
         122:   delete_os_disk_on_termination    = true
        
        An argument named "delete_os_disk_on_termination" is not expected here.
        
        Error: Unsupported argument
        
          on terraform_plugin_test.tf line 123, in resource "azurerm_linux_virtual_machine" "test":
         123:   delete_data_disks_on_termination = true
        
        An argument named "delete_data_disks_on_termination" is not expected here.
        
        Error: Unsupported block type
        
          on terraform_plugin_test.tf line 125, in resource "azurerm_linux_virtual_machine" "test":
         125:   storage_image_reference {
        
        Blocks of type "storage_image_reference" are not expected here.
        
        Error: Unsupported block type
        
          on terraform_plugin_test.tf line 132, in resource "azurerm_linux_virtual_machine" "test":
         132:   os_profile {
        
        Blocks of type "os_profile" are not expected here.
        
        Error: Unsupported block type
        
          on terraform_plugin_test.tf line 138, in resource "azurerm_linux_virtual_machine" "test":
         138:   storage_os_disk {
        
        Blocks of type "storage_os_disk" are not expected here.
        
        Error: Unsupported block type
        
          on terraform_plugin_test.tf line 145, in resource "azurerm_linux_virtual_machine" "test":
         145:   os_profile_linux_config {
        
        Blocks of type "os_profile_linux_config" are not expected here.
--- FAIL: TestAccVirtualMachineDataDiskAttachment_virtualMachineApplication (8.47s)
FAIL
```

2024-01-04 08:53 UTC, jkroepke commented
@katbyte could you check that you are on latest revision? I had the same errors on do a force-push here.

For example the error

>         Error: Unsupported argument
>        
>          on terraform_plugin_test.tf line 123, in resource "azurerm_linux_virtual_machine" "test":
>         123:   delete_data_disks_on_termination = true
>        
>        An argument named "delete_data_disks_on_termination" is not expected here.

Lead to an old revision, since on the whole diff, there is no `delete_data_disks_on_termination`.

2024-01-08 04:27 UTC, katbyte approved these changes
Tests pass now ! thanks LGTM 💾

2024-01-08 04:27 UTC, merged