`azurerm_backup_protected_vm` - support recover soft deleted vm
hashicorp/terraform-provider-azurerm pull request #24157
Opened 2023-12-08 03:25 UTC by ziyeqf

fix #24051 

features expand
---
```
❯ go test -v ./internal/provider/ -run=TestExpand                      
=== RUN   TestExpandFeatures
    features_test.go:364: [DEBUG] Test Case: "Empty Block"
    features_test.go:364: [DEBUG] Test Case: "Complete Enabled"
    features_test.go:364: [DEBUG] Test Case: "Complete Disabled"
--- PASS: TestExpandFeatures (0.00s)
=== RUN   TestExpandFeaturesApiManagement
    features_test.go:434: [DEBUG] Test Case: "Empty Block"
    features_test.go:434: [DEBUG] Test Case: "Purge Soft Delete On Destroy and Recover Soft Deleted Api Management Enabled"
    features_test.go:434: [DEBUG] Test Case: "Purge Soft Delete On Destroy and Recover Soft Deleted Api Management Disabled"
--- PASS: TestExpandFeaturesApiManagement (0.00s)
=== RUN   TestExpandFeaturesAppConfiguration
    features_test.go:504: [DEBUG] Test Case: "Empty Block"
    features_test.go:504: [DEBUG] Test Case: "Purge Soft Delete On Destroy and Recover Soft Deleted App Configuration Enabled"
    features_test.go:504: [DEBUG] Test Case: "Purge Soft Delete On Destroy and Recover Soft Deleted App Configuration Disabled"
--- PASS: TestExpandFeaturesAppConfiguration (0.00s)
=== RUN   TestExpandFeaturesApplicationInsights
    features_test.go:569: [DEBUG] Test Case: "Empty Block"
    features_test.go:569: [DEBUG] Test Case: "Disable Generated Rule"
    features_test.go:569: [DEBUG] Test Case: "Enable Generated Rule"
--- PASS: TestExpandFeaturesApplicationInsights (0.00s)
=== RUN   TestExpandFeaturesCognitiveServices
    features_test.go:634: [DEBUG] Test Case: "Empty Block"
    features_test.go:634: [DEBUG] Test Case: "Purge on Destroy Enabled"
    features_test.go:634: [DEBUG] Test Case: "Purge on Destroy Disabled"
--- PASS: TestExpandFeaturesCognitiveServices (0.00s)
=== RUN   TestExpandFeaturesKeyVault
    features_test.go:739: [DEBUG] Test Case: "Empty Block"
    features_test.go:739: [DEBUG] Test Case: "Purge Soft Delete On Destroy and Recover Soft Deleted Key Vaults Enabled"
    features_test.go:739: [DEBUG] Test Case: "Purge Soft Delete On Destroy and Recover Soft Deleted Key Vaults Disabled"
--- PASS: TestExpandFeaturesKeyVault (0.00s)
=== RUN   TestExpandFeaturesTemplateDeployment
    features_test.go:804: [DEBUG] Test Case: "Empty Block"
    features_test.go:804: [DEBUG] Test Case: "Delete Nested Items During Deletion Enabled"
    features_test.go:804: [DEBUG] Test Case: "Delete Nested Items During Deletion Disabled"
--- PASS: TestExpandFeaturesTemplateDeployment (0.00s)
=== RUN   TestExpandFeaturesVirtualMachine
    features_test.go:922: [DEBUG] Test Case: "Empty Block"
    features_test.go:922: [DEBUG] Test Case: "Delete OS Disk Enabled"
    features_test.go:922: [DEBUG] Test Case: "Graceful Shutdown Enabled"
    features_test.go:922: [DEBUG] Test Case: "Skip Shutdown and Force Delete Enabled"
    features_test.go:922: [DEBUG] Test Case: "All Disabled"
--- PASS: TestExpandFeaturesVirtualMachine (0.00s)
=== RUN   TestExpandFeaturesVirtualMachineScaleSet
    features_test.go:1036: [DEBUG] Test Case: "Empty Block"
    features_test.go:1036: [DEBUG] Test Case: "Force Delete Enabled"
    features_test.go:1036: [DEBUG] Test Case: "Roll Instances Enabled"
    features_test.go:1036: [DEBUG] Test Case: "Scale In On Delete Disabled"
    features_test.go:1036: [DEBUG] Test Case: "All Fields Disabled"
--- PASS: TestExpandFeaturesVirtualMachineScaleSet (0.00s)
=== RUN   TestExpandFeaturesLogAnalyticsWorkspace
    features_test.go:1100: [DEBUG] Test Case: "Empty Block"
    features_test.go:1100: [DEBUG] Test Case: "Permanent Delete Enabled"
    features_test.go:1100: [DEBUG] Test Case: "Permanent Delete Disabled"
--- PASS: TestExpandFeaturesLogAnalyticsWorkspace (0.00s)
=== RUN   TestExpandFeaturesResourceGroup
    features_test.go:1165: [DEBUG] Test Case: "Empty Block"
    features_test.go:1165: [DEBUG] Test Case: "Prevent Deletion If Contains Resources Enabled"
    features_test.go:1165: [DEBUG] Test Case: "Prevent Deletion If Contains Resources Disabled"
--- PASS: TestExpandFeaturesResourceGroup (0.00s)
=== RUN   TestExpandFeaturesRecoveryServicesVault
    features_test.go:1230: [DEBUG] Test Case: "Empty Block"
    features_test.go:1230: [DEBUG] Test Case: "Purge Soft Delete On Destroy and Recover Soft Deleted Protected VM Enabled"
    features_test.go:1230: [DEBUG] Test Case: "Purge Soft Delete On Destroy and Recover Soft Deleted Protected VM Disabled"
--- PASS: TestExpandFeaturesRecoveryServicesVault (0.00s)
=== RUN   TestExpandFeaturesManagedDisk
    features_test.go:1295: [DEBUG] Test Case: "Empty Block"
    features_test.go:1295: [DEBUG] Test Case: "No Downtime Resize Enabled"
    features_test.go:1295: [DEBUG] Test Case: "No Downtime Resize Disabled"
--- PASS: TestExpandFeaturesManagedDisk (0.00s)
=== RUN   TestExpandFeaturesSubscription
    features_test.go:1343: [DEBUG] Test Case: "Empty Block"
    features_test.go:1343: [DEBUG] Test Case: "No Downtime Resize Enabled"
--- PASS: TestExpandFeaturesSubscription (0.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/provider	
```

acctest
---
```

```

2023-12-08 08:49 UTC, magodo requested changes
Thanks for this PR!
I've taken a look through and left some comments inline, but this is mostly looking good to me 👍

2023-12-11 06:23 UTC, ziyeqf commented on internal/features/user_flags.go
> +	RecoverSoftDeletedBackupProtected bool
renamed

2023-12-11 06:24 UTC, ziyeqf commented on internal/provider/features_test.go
> +			Name: "Purge Soft Delete On Destroy and Recover Soft Deleted Protected VM Enabled",
removed...

2023-12-11 06:24 UTC, ziyeqf commented on internal/services/recoveryservices/backup_protected_vm_resource.go
> +func resourceRecoveryServicesVaultBackupProtectedVMrecoverSoftDeleted(ctx context.Context, client *protecteditems.ProtectedItemsClient, opClient *backup.ProtectedItemOperationResultsClient, id protec
renamed

2023-12-11 07:51 UTC, ziyeqf commented
TC test triggered

2023-12-11 09:17 UTC, magodo requested changes

2023-12-11 09:17 UTC, magodo commented on internal/services/recoveryservices/backup_protected_vm_resource.go
> +					return fmt.Errorf("reading %s: the VM has been soft deleted, to recover it, specify the `recover_soft_deleted_backup_protected_vm` feature.", id)
Shall we do the same as if the resource is 404?

2023-12-11 09:17 UTC, magodo commented on internal/services/recoveryservices/backup_protected_vm_resource.go
> +				return tf.ImportAsExistsError("azurerm_backup_protected_vm", id.ID())
For soft deleted resource that exists, we shall error out when users haven't opt in the soft delete feature, and ensure we provide a detailed error message as: https://github.com/hashicorp/terraform-provider-azurerm/blob/2d48f47beb482c40e30b12a1f77e95002e0b6cbe/internal/services/keyvault/key_vault_resource.go#L276-L284

2023-12-12 01:57 UTC, magodo reviewed
LGTM now!

2023-12-15 05:40 UTC, ziyeqf commented
just a comment to remove the `waiting-response` label

2024-02-16 02:28 UTC, katbyte requested changes

2024-02-16 02:28 UTC, katbyte commented on internal/provider/features.go
> +		"recovery_services_vault": {
this should be plural 
```suggestion
		"recovery_services_vaults": {
```

2024-02-20 01:45 UTC, katbyte requested changes
We have a bunch of test failures:

can we please fix up all tests?

<img width="1390" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/1638467/eb3abb9e-0e9a-4898-9d60-59ea45c51efc">

2024-02-22 06:52 UTC, ziyeqf commented
The service seems to have something wrong and needs workaround on https://github.com/hashicorp/terraform-provider-azurerm/pull/24978

2024-03-21 23:16 UTC, katbyte requested changes
https://github.com/hashicorp/terraform-provider-azurerm/pull/24978 has been merged but i am still seeing test failures 
<img width="768" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/1638467/28c36749-75ee-4c04-a867-9fef5ad9f16a">

2024-03-22 03:24 UTC, ziyeqf commented
> #24978 has been merged but i am still seeing test failures <img alt="image" width="768" src="https://private-user-images.githubusercontent.com/1638467/315773933-28c36749-75ee-4c04-a867-9fef5ad9f16a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzY5MTQsIm5iZiI6MTcxMTA3NjYxNCwicGF0aCI6Ii8xNjM4NDY3LzMxNTc3MzkzMy0yOGMzNjc0OS03NWVlLTRjMDQtYTg2Ny05ZmVmNWFkOWYxNmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMDMwMzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjEwOGIwZTMxODI4NWNhODIzYTdkODE4MTZlODAzMTVhODAzYTdhN2U0YmIwMTIzZTA4MWNjMGRkYzkzM2Q4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Qemo0NfSwlaimddwC-97HBOlpjasba5sj3J3GSoR9ys">

Code updated and the tests pass now. I removed the change on `site_recovery_xxx` files, as it should not be involved.
<img width="554" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/51212351/9a47db18-6bb9-4fad-91cf-f98d21563e8f">

2024-04-18 16:18 UTC, katbyte requested changes
the tests for this also still seem quite flakey?
<img width="792" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/1638467/73c6e19a-5fe7-462b-955b-914fe2d74d7e">

2024-04-18 16:18 UTC, katbyte commented on website/docs/guides/features-block.html.markdown
> +* `recover_soft_deleted_backup_protected_vm` - (Optional) Should the `azurerm_backup_protected_vm` resource recover a Soft-Deleted protected VM? Defaults to `true`.
I think this should default to false?

2024-04-18 16:18 UTC, katbyte commented on internal/provider/features.go
> +						Default:  true,
this is going to change the existing behaviour?
```suggestion
						Default:  false,
```

2024-04-19 02:25 UTC, ziyeqf commented
> recover_soft_deleted_backup_protected_vm

TBH these tests on main branch are also flakey..

2024-05-06 17:10 UTC, katbyte approved these changes
This doesn't seem to be a flakey test failure:

```
------- Stdout: -------
=== RUN   TestAccBackupProtectedVm_updateBackupPolicyId
=== PAUSE TestAccBackupProtectedVm_updateBackupPolicyId
=== CONT  TestAccBackupProtectedVm_updateBackupPolicyId
    testcase.go:113: Step 1/5 error: Error running pre-apply refresh: exit status 1
        
        Error: Duplicate provider configuration
        
          on terraform_plugin_test.tf line 26:
          26: provider "azurerm" {
        
        A default (non-aliased) provider configuration for "azurerm" was already
        given at terraform_plugin_test.tf:21,1-19. If multiple configurations are
        required, set the "alias" argument for alternative configurations.
    testing_new.go:79: Error retrieving state, there may be dangling resources: exit status 1
        
        Error: Duplicate provider configuration
        
          on terraform_plugin_test.tf line 26:
          26: provider "azurerm" {
        
        A default (non-aliased) provider configuration for "azurerm" was already
        given at terraform_plugin_test.tf:21,1-19. If multiple configurations are
        required, set the "alias" argument for alternative configurations.
--- FAIL: TestAccBackupProtectedVm_updateBackupPolicyId (5.44s)
FAIL
```

Should be good to merge once the test is fixed

2024-05-07 06:00 UTC, ziyeqf commented
uh...my fault. updated
```
❯❯ tftest recoveryservices TestAccBackupProtectedVm_updateBackupPolicyId
=== RUN   TestAccBackupProtectedVm_updateBackupPolicyId
=== PAUSE TestAccBackupProtectedVm_updateBackupPolicyId
=== CONT  TestAccBackupProtectedVm_updateBackupPolicyId
--- PASS: TestAccBackupProtectedVm_updateBackupPolicyId (877.88s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices      879.994s
```

2024-05-09 17:42 UTC, katbyte approved these changes
LGTM 📨

2024-05-09 17:42 UTC, merged