new resource `azurerm_elastic_san_volume_group`
hashicorp/terraform-provider-azurerm pull request #24166
Opened 2023-12-08 13:29 UTC by teowa

2023-12-19 05:25 UTC, teowa commented
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/104055472/38d8a7f2-3e77-4740-9df9-40ab34a81deb)

2023-12-19 11:17 UTC, ms-zhenhua requested changes
Hey @teowa, 
Thanks for this PR - I've taken a look through and left some comments inline. If we can fix those up, this should be good to go 👍

Thanks!

2023-12-19 11:17 UTC, ms-zhenhua commented on website/docs/r/elastic_san_volume_group.html.markdown
> +* `principal_id` - The Principal ID for the System-Assigned Managed Identity assigned to this Elastic SAN Volume Group.
```suggestion
* `principal_id` - The Principal ID associated with the Managed Service Identity assigned to this Elastic SAN Volume Group.
```

2023-12-19 11:17 UTC, ms-zhenhua commented on website/docs/r/elastic_san_volume_group.html.markdown
> +* `tenant_id` - The Tenant ID for the System-Assigned Managed Identity assigned to this Elastic SAN Volume Group.
```suggestion
* `tenant_id` - The Tenant ID associated with this Managed Service Identity assigned to this Elastic SAN Volume Group.
```

2023-12-19 11:17 UTC, ms-zhenhua commented on website/docs/r/elastic_san_volume_group.html.markdown
> +* `current_versioned_key_id` - Current Versioned Key ID.
```suggestion
* `current_versioned_key_id` - The ID of the current versioned Key Vault Key in use.
```

2023-12-19 11:17 UTC, ms-zhenhua commented on website/docs/r/elastic_san_volume_group.html.markdown
> +* `last_key_rotation_timestamp` - Last Key Rotation Timestamp.
```suggestion
* `last_key_rotation_timestamp` - The timestamp of the last rotation of the Key Vault Key.
```

2023-12-19 11:17 UTC, ms-zhenhua commented on website/docs/r/elastic_san_volume_group.html.markdown
> +* `current_versioned_key_expiration_timestamp` - Current Versioned Key Expiration Timestamp of the Elastic SAN Volume Group.
```suggestion
* `current_versioned_key_expiration_timestamp` - The timestamp of the expiration time for the current version of the customer managed key.
```

2023-12-21 08:35 UTC, teowa commented on internal/services/elasticsan/elastic_san_volume_group_resource.go
> +		}
if return nil, the Network Rules will not be removed during update

2023-12-21 08:35 UTC, teowa commented on internal/services/elasticsan/elastic_san_volume_group_resource.go
> +	for _, rule := range *input.VirtualNetworkRules {
will add a nil check for this

2023-12-27 04:30 UTC, teowa commented
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/104055472/b7d67044-94e4-4861-8f2e-a7d38ccc969c)

2023-12-28 02:50 UTC, ms-zhenhua commented on internal/services/elasticsan/elastic_san_volume_group_resource.go
> +				// None is not exposed, Iscsi is only allowed protocolType to connect to volume group
```suggestion
				// None is not a valid value and service team will consider removing it in future versions.
```

2023-12-28 02:50 UTC, ms-zhenhua commented on website/docs/r/elastic_san_volume_group.html.markdown
> +* `protocol_type` - (Optional) Specifies the type of the storage target. The only possible values are `Iscsi`. Defaults to `Iscsi`.
```suggestion
* `protocol_type` - (Optional) Specifies the type of the storage target. The only possible value is `Iscsi`. Defaults to `Iscsi`.
```

2023-12-28 05:39 UTC, ms-zhenhua approved these changes

2023-12-28 05:40 UTC, ms-zhenhua commented
Hey @teowa, thank you for your updates. LGTM~

2024-01-16 08:44 UTC, teowa commented on internal/services/elasticsan/elastic_san_volume_group_resource.go
> +		id, err := keyVaultParse.NewNestedItemID(pointer.From(kv.KeyVaultUri), keyVaultParse.NestedItemTypeKey, pointer.From(kv.KeyName), pointer.From(kv.KeyVersion))
From [doc](https://learn.microsoft.com/en-us/azure/storage/elastic-san/elastic-san-configure-customer-managed-keys?tabs=azure-powershell%2Cnew-vg#automatic-key-version-rotation), If `key_vault_id` has no version, the backend will periodically retrieve the latest version, if version specified, we need to manually update version if key is rotated.

2024-01-16 08:49 UTC, teowa commented on internal/services/elasticsan/elastic_san_volume_group_resource.go
> +	result := volumegroups.EncryptionProperties{
If `version` is specified, specific versioned key will be used;
if `version` is not specified, 
> Elastic SAN checks the key vault daily for a new version of the key.

2024-01-17 05:38 UTC, teowa commented on internal/services/elasticsan/elastic_san_volume_group_resource.go
> +		id, err := keyVaultParse.NewNestedItemID(pointer.From(kv.KeyVaultUri), keyVaultParse.NestedItemTypeKey, pointer.From(kv.KeyName), pointer.From(kv.KeyVersion))
Yes, by my test, `KeyVersion` will not be changed, another versioned Key ID is exported through `currentVersionedKeyId` field of REST API.

2024-01-17 05:40 UTC, teowa commented on internal/services/elasticsan/elastic_san_volume_group_resource.go
> +		return nil, nil
By my test, if `encryptionType` is updated from `EncryptionAtRestWithCustomerManagedKey` to  `EncryptionAtRestWithPlatformKey`, then `encryption` block will be ignored at backend.

2024-01-17 05:42 UTC, teowa commented on internal/services/elasticsan/elastic_san_volume_group_resource.go
> +			CurrentVersionedKeyId:                  pointer.From(input.KeyVaultProperties.CurrentVersionedKeyIdentifier),
nil check added.

2024-01-17 07:06 UTC, ms-zhenhua approved these changes

2024-01-17 09:35 UTC, teowa commented
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/104055472/b3ef0888-8c3c-4e8a-80ad-598fabdf4df2)

2024-01-23 11:33 UTC, stephybun approved these changes
Thanks @teowa and @ms-zhenhua! LGTM 🦀

2024-01-23 11:34 UTC, merged