`azurerm_iothub` - deprecate `endpoint`, fix a bug in updating when a cosmosDB account endpoint exists
hashicorp/terraform-provider-azurerm pull request #24180
Opened 2023-12-11 07:50 UTC by ziyeqf

1. the `endpoint` block is too big to contain paramerters from multiple kind of endpoint, so decide not to add cosmosDB account parameters to it and deprecate it.

2. there is a bug inside the `endpoint`: `azurerm_iothub` does not support `cosmosDB` type endpoint, so if a user has created a `azurerm_iothub_endpoint_cosmosdb_account` attched to the `azurerm_iothub`, then update the `azurerm_iothub`( by editing the `tags` or some other parameters ), it will remove the cosmosDB endpoint.  If there is a `azurerm_iothub_route` set to the `azurerm_iothub_endpoint_cosmosdb_account`, the update will fail with the error. `route to xxx endpoint is invalid`.

Test
---
```
```

2023-12-13 02:30 UTC, magodo commented
@ziyeqf It more sounds like a user usage error as we already have the notification: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/iothub#:~:text=Endpoints%20can%20be,is%20not%20supported:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/7970698/02271584-a623-4741-826a-857dfd30d8cd)

2023-12-13 02:33 UTC, ziyeqf commented
> @ziyeqf It more sounds like a user usage error as we already have the notification: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/iothub#:~:text=Endpoints%20can%20be,is%20not%20supported:
> 
> ![image](https://private-user-images.githubusercontent.com/7970698/290056587-02271584-a623-4741-826a-857dfd30d8cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzQ5NjMsIm5iZiI6MTcwMjQzNDY2MywicGF0aCI6Ii83OTcwNjk4LzI5MDA1NjU4Ny0wMjI3MTU4NC1hNjIzLTQ3NDEtODI2YS04NTdkZmQzMGQ4Y2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDIzMTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTNhOGYxNDQ0ZjU2MGIwNTliOTEyZWRhZDNhMjE5Zjc3MDc3MDJkM2UzMDBmZmYxYTY3YjMzZGIyODY3Mjc4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9EXDeTOt0bcgGiloV3r13FnGk0ZLmLVI1ZviWaxdhXk)

no, this resource has not support cosmosdb account endpoint,  so when a user has deployed a `azurerm_iothub_endpoint_cosmosdb_account`,  then if a change has happened on `azurerm_iothub`, the update call on the iothub will remove the cosmos db endpoint. For other both supported endpoint, they are ok because there are `computed` properties for them.

2023-12-13 06:08 UTC, magodo commented
Instead of doing this, we can split the create and update functions, and use the GET-then-PUT style in the update function, so that if users didn't specify the `endpoint`, it won't override any existing ones.

2023-12-13 07:41 UTC, magodo requested changes

2023-12-13 07:41 UTC, magodo commented on internal/services/iothub/iothub_resource.go
> +		prop.Routing.Endpoints, err = expandIoTHubEndpoints(d, subscriptionId)
Still need the nil check for `prop.Routing`?

2024-01-04 02:22 UTC, katbyte approved these changes
LGTM 🚡

2024-01-04 02:22 UTC, merged