`azure_cognitive_deployment` - Support `source` property and change `version` property to optional
hashicorp/terraform-provider-azurerm pull request #24264
Opened 2023-12-18 06:53 UTC by liuwuliuyun

`azure_cognitive_deployment` 
- support `source` property.
- support optional `version` property based on the swagger description.
- update doc of `version` property for both properties.
- change test case accrodingly.

2024-01-04 02:45 UTC, katbyte requested changes

2024-01-04 02:45 UTC, katbyte commented on internal/services/cognitive/cognitive_deployment_resource.go
> +					"source": {
as this is a resource id  wouldn't it make more sense to have it be

```suggestion
					"source_resource_id": {
```

2024-01-04 02:45 UTC, katbyte commented on website/docs/r/cognitive_deployment.html.markdown
> +* `source` - (Optional) Deployment model source ARM resource ID.
what is a valid resource here? could we expand on the docs a bit more

2024-01-04 02:45 UTC, katbyte commented on internal/services/cognitive/cognitive_deployment_resource_test.go
>  func (r CognitiveDeploymentTestResource) basic(data acceptance.TestData) string {
can we add a test for the new property?

2024-01-09 07:05 UTC, liuwuliuyun commented
@katbyte , Thanks for the comment. I removed the `model.source` property from this PR since we are not able to test this property for now. The reason is that we dont have a self-trained model in our subscription therefore we dont have a valid ARM resource id for `source` property to test.

2024-01-09 07:12 UTC, liuwuliuyun commented
Latest test evidence:

```
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\yunliu1\go #gosetup
"C:\Program Files\Go\bin\go.exe" test -c -o C:\Users\yunliu1\AppData\Local\JetBrains\GoLand2023.3\tmp\GoLand\___TestAccCognitiveDeployment_basic_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_cognitive__1_.test.exe github.com/hashicorp/terraform-provider-azurerm/internal/services/cognitive #gosetup
"C:\Program Files\Go\bin\go.exe" tool test2json -t C:\Users\yunliu1\AppData\Local\JetBrains\GoLand2023.3\tmp\GoLand\___TestAccCognitiveDeployment_basic_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_cognitive__1_.test.exe -test.v -test.paniconexit0 -test.run ^\QTestAccCognitiveDeployment_basic\E$ #gosetup
=== RUN   TestAccCognitiveDeployment_basic

--- PASS: TestAccCognitiveDeployment_basic (200.76s)
PASS


Process finished with the exit code 0
```

2024-01-23 07:05 UTC, stephybun approved these changes
Thanks @liuwuliuyun LGTM 👍

2024-01-23 07:05 UTC, merged