`Nginx`: embed nginx configuration into deployment resource
hashicorp/terraform-provider-azurerm pull request #24276
Opened 2023-12-19 06:51 UTC by wuxu92

deprecate independent `azurerm_nginx_configuration` resource and skip exists AccTests for it. This PR supersedes #24041.

```
--- PASS: TestAccNginxDeployment_withConfiguration (511.17s)
--- PASS: TestAccNginxDeployment_updateWithConfiguration (484.44s)
PASS
```

2024-02-20 22:32 UTC, katbyte requested changes

2024-02-20 22:32 UTC, katbyte commented on internal/services/nginx/nginx_configuration_resource_test.go
> +	t.Skipf("Skipping test due to deprecated nginx_configuration resource")
since these are broken and never will be fixed should we just remove them,?

2024-02-20 22:32 UTC, katbyte commented on website/docs/r/nginx_configuration.html.markdown
> +~> **NOTE** Do not use the independent `azurerm_nginx_configuration` resource anymore due to a [known API issue](https://docs.nginx.com/nginxaas/azure/known-issues/#i-classfa-solid-fa-bug-stylecolore
should we just remove this resource documentation entirely as it no longer works on creation & deprecate the resouce?

2024-03-05 04:28 UTC, katbyte requested changes

2024-03-05 04:28 UTC, katbyte commented on internal/services/nginx/nginx_deployment_resource_test.go
> +
```suggestion

```

2024-03-05 04:28 UTC, katbyte commented on internal/services/nginx/nginx_configuration_resource.go
> +// This resource has been deprecated and will be removed in the next major release.
we should mark this resource as deprecated with instructions to use the new resource?

2024-03-21 23:15 UTC, katbyte approved these changes
LGTM 🎫

2024-03-21 23:15 UTC, katbyte commented
good to mege once merge conflicts are resolved

2024-03-22 07:01 UTC, merged

2024-03-22 15:18 UTC, puneetsarna commented
Hi @katbyte @wuxu92 https://docs.nginx.com/nginxaas/azure/changelog/#march-13-2024 mentions that the issue with the default configuration was fixed. Can we please restore the `azurerm_nginx_configuration` resource?

2024-03-26 14:11 UTC, puneetsarna commented
@wuxu92 I see what you mean here around the config resource being a singleton. I have called out the explanation around why having the separate resource is very useful for us (see PR description here https://github.com/hashicorp/terraform-provider-azurerm/pull/25402). Let's continue to discuss it over the other PR.

I understand that the resource was only deprecated and not removed but the users upgrading to the latest terraform won't see any documentation either thinking that the resource was retired (or will be soon). I believe this will also cause user panic as they would have to migrate to the new embedded resource if they want to use the latest provider. Lastly, users might see issues while transitioning to this new embedded resource as the transition would involve downtime:
- User removes TF resource and tries to use embedded resource.
- Apply would trigger a conf destruction (🔴 ) and re-application.
- Config destruction would cause downtime for the user.

Let's continue these discussions over here: https://github.com/hashicorp/terraform-provider-azurerm/pull/25402