#24134: Default logic app versions to ~4
hashicorp/terraform-provider-azurerm pull request #24280
Opened 2023-12-19 13:01 UTC by harshavmb

Default logic app versions to ~4

Fixes #24134

2023-12-19 14:23 UTC, catriona-m requested changes
Hi @harshavmb thanks for submitting this. This looks good, but we should deprecate this with a 4.0 feature flag so this won't cause issues for users currently relying on the default value of `~3`. This is an example of a Default value deprecation in another resource [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/ab4f143d37136a8b0b6a492de0e51178cb26e279/internal/services/iothub/iothub_resource.go#L222).

2023-12-19 16:09 UTC, harshavmb commented
Hi @catriona-m ,

Thanks for the review & I amended changes as per the review. I do see all PRs failing `
Pull Request Triage / triage (pull_request_target)` check. I don't think it's related to my change.

2023-12-20 10:41 UTC, catriona-m commented on website/docs/r/logic_app_standard.html.markdown
> +* `version` - (Optional) The runtime version associated with the Logic App. Defaults to `~4`.
we can leave this as `Defaults to `~3` for now until we officially move to 4.0.

2023-12-20 12:15 UTC, catriona-m approved these changes
Thanks @harshavmb LGTM!

2023-12-20 12:16 UTC, merged