`azurerm_container_app_environment` - add support for the Custom DNS Suffix and expose the `custom_domain_verification_id` attribute
hashicorp/terraform-provider-azurerm pull request #24346
Opened 2023-12-27 14:44 UTC by iambaim

This PR:
1. Enables the Custom environment DNS Suffix in Azure Container Apps (https://learn.microsoft.com/en-us/azure/container-apps/environment-custom-dns-suffix).
2. Exposes the Custom Domain Validation ID in the Azure Container App Environment level.

Acceptance test:

```shell
% make acctests SERVICE='containerapps' TESTARGS='-run=TestAccContainerAppEnvironment_completeWithCustomDnsSuffix' 
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/containerapps -run=TestAccContainerAppEnvironment_completeWithCustomDnsSuffix -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccContainerAppEnvironment_completeWithCustomDnsSuffix
=== PAUSE TestAccContainerAppEnvironment_completeWithCustomDnsSuffix
=== CONT  TestAccContainerAppEnvironment_completeWithCustomDnsSuffix
--- PASS: TestAccContainerAppEnvironment_completeWithCustomDnsSuffix (1138.06s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/containerapps	1138.125s
```

Fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/24190, https://github.com/hashicorp/terraform-provider-azurerm/issues/20829, https://github.com/hashicorp/terraform-provider-azurerm/issues/20502

2024-01-04 09:35 UTC, iambaim commented
Hi @katbyte, thanks for approving the workflows earlier. I can see one of the checks fails but that seems to be unrelated to my changes.

````
==> Checking for use of gradually deprecated functions...
internal/services/iothub/iothub_resource.go:73:    Create: resourceIotHubCreateUpdate,
New Resources should no longer use combined CreateUpdate methods, please
split these into two separate Create and Update methods.

Existing resources can continue to use combined CreateUpdate methods
for the moment - but over time these will be split into separate Create and
Update methods.
```` 

I have now rebase my commits to the latest main. Hopefully all the checks are good now.

2024-01-09 08:42 UTC, iambaim commented
Can I have a review, @jackofallops ? Thanks!

2024-01-14 14:05 UTC, davidkarlsen commented
Or maybe @katbyte can review?

2024-02-22 22:17 UTC, lgmorand commented
Hi @jackofallops 

anyone who could do the review please ? :) My Cx is looking for the same thing and it blocks the deployment of ACA. I did a code review and it looks fine to me.

ps: @iambaim thanks for the work !

2024-03-18 16:18 UTC, goldmark commented
Hi @jackofallops are there any plans to merge this request? any ETA?

2024-03-20 17:15 UTC, raddaoui commented
any updates on this PR? my customer is blocked

2024-03-20 17:17 UTC, Chigurusetty commented
Hi Team, when this could be available? any ETA please

2024-03-20 21:18 UTC, lgmorand commented
@katbyte for visibility. thanks <3

2024-03-22 08:30 UTC, iambaim commented
Just synced the code with main. Ready for another round of testing, @katbyte and @jackofallops . Thanks!

2024-04-13 10:35 UTC, davidkarlsen commented
@tombuildsstuff can this be merged?

* it's a small thing
* many have voted for it
* it passes
* it is sitting for 4th month on a row waiting for merge
* it's really useful for enterprise customers which have more requirements to networking

2024-04-13 17:00 UTC, iambaim commented
Users wanting to implement any form of custom domains in their Azure Container Apps are in a bit of a pickle now as this is still pending and the on-going issue with `azurerm_container_app_custom_domain` that clashes with secrets. (#25196) :(

2024-04-23 06:36 UTC, jackofallops requested changes
Hi @iambaim - Thanks for this PR.

The successful completion of this configuration requires that the `CustomDomainVerificationId` already be present in resolvable DNS so, for this to be supported in Terraform, this will need to be a separate resource, as is necessary for `azurerm_container_app_custom_domain`, perhaps called `azurerm_container_app_environment_custom_domain`. This virtual resource can then update the Environment after the verification ID is known, and a DNS record can be created in the correct sequence to be present (and used as reference to ensure the dependency graph is in the correct order).

The `CustomDomainVerificationId` should also be added to the `azurerm_container_app_environment` Data Source when the resource is updated.

Can you take a look at splitting this into a new virtual resource, and adding the property to the Data Source, and we'll pick up review from there?

Thanks!

2024-04-26 07:49 UTC, iambaim commented
Hi @jackofallops , thanks for the suggestion. I agree, this is a better approach. WIll update the branch in a few days :)

2024-04-27 17:13 UTC, iambaim commented on internal/services/containerapps/container_app_environment_resource.go
> +			Sensitive:   true,
Agreed

2024-04-29 05:38 UTC, iambaim commented
Hello @jackofallops . The codes are now ready for review.

FYI, the addition of `testdata/testacc_nopassword.pfx` file is necessary to test the resource update feature, because updating using the same cert will trigger an Azure API error. I copied the file from `internal/services/web/testdata/app_service_certificate_nopassword.pfx`.

Thanks!

2024-05-06 21:28 UTC, katbyte requested changes

2024-05-06 21:28 UTC, katbyte commented on website/docs/r/container_app_environment_custom_domain.html.markdown
> +  custom_domain_dns_suffix              = "acceptancetest.contoso.com"
as the parent resource is `___custom_domain` i think we can make these:
```suggestion
  certificate_blob_base64 = filebase64("testacc.pfx")
  certificate_password    = "TestAcc"
  dns_suffix              = "acceptancetest.contoso.com"
```

2024-05-09 17:45 UTC, katbyte approved these changes
aside from a few minor comments this LGTM 🕯️

2024-05-09 17:45 UTC, katbyte commented on website/docs/r/container_app_environment_custom_domain.html.markdown
> +
```suggestion

```

2024-05-09 17:45 UTC, katbyte commented on website/docs/r/container_app_environment_custom_domain.html.markdown
> +
```suggestion
```

2024-05-09 23:44 UTC, merged

2024-05-12 12:36 UTC, lgmorand commented
thanks @iambaim & @katbyte