#24358: Support vmTemplate for azurerm_virtual_desktop_host_pool resource
hashicorp/terraform-provider-azurerm pull request #24369
Opened 2024-01-02 16:25 UTC by harshavmb

Support `vm_template` for `azurerm_virtual_desktop_host_pool` resource. 

Fixes #24358.

2024-01-10 15:20 UTC, catriona-m requested changes
Thanks for this @harshavmb, I've left a couple of minor comments but once those are fixed up I can take another look. It would also be good to include this property in a test. Thanks!

2024-01-10 15:20 UTC, catriona-m commented on internal/services/desktopvirtualization/virtual_desktop_host_pool_resource.go
> +		_, err := pluginsdk.ExpandJsonFromString(*vmTemplate)
```suggestion
	vmTemplate := d.Get("vm_template").(string)
	if vmTemplate != "" {
		// we have no use with the json object as azure accepts string only
		// merely here for validation
		_, err := pluginsdk.ExpandJsonFromString(vmTemplate)
```

2024-01-10 15:20 UTC, catriona-m commented on website/docs/r/virtual_desktop_host_pool.html.markdown
> +* `vm_template` - (Optional) A VM template for sessionhosts configuration within hostpool. This is a JSON string.
```suggestion
* `vm_template` - (Optional) A VM template for session hosts configuration within hostpool. This is a JSON string.
```

2024-01-10 17:33 UTC, harshavmb commented
Hi @catriona-m ,

Indeed I wanted to add a test case but couldn't find some documentation about `vm_template`.  Also my organization has restricted has restricted access to create AVDs. 

I shall check with the request initiator if he could provide me a sample template to play with.

2024-01-30 11:26 UTC, catriona-m commented
HI @harshavmb - just checking in to see if you were able to get the config needed to create a test for this? Thanks!

2024-02-13 12:47 UTC, harshavmb commented
> HI @harshavmb - just checking in to see if you were able to get the config needed to create a test for this? Thanks!

Hi @catriona-m ,

I have added the test case now. Could you please re-review?

2024-02-16 00:34 UTC, katbyte approved these changes
Thanks @harshavmb - LGTM 🖥️

2024-02-16 00:34 UTC, merged