#24401: Support request_body_check part of azurerm_cdn_frontdoor_firewall_policy
hashicorp/terraform-provider-azurerm pull request #24406
Opened 2024-01-05 14:43 UTC by harshavmb

Support `request_body_check` part of `azurerm_cdn_frontdoor_firewall_policy`. 

Fixes #24401.

2024-01-08 03:48 UTC, katbyte requested changes

2024-01-08 03:48 UTC, katbyte commented on internal/services/cdn/cdn_frontdoor_firewall_policy_resource.go
> +			"request_body_check": {
as this is a boolean the convention in the provider is to put enabled into the name such as
```suggestion
			"request_body_check_enabled": {
```

2024-01-08 20:22 UTC, katbyte commented on internal/services/cdn/cdn_frontdoor_firewall_policy_resource_test.go
> +    request_body_check_enabled     = false
I think this is in the wrong place? it should be pulled up into the root level of the resource?

```
------- Stdout: -------
=== RUN   TestAccCdnFrontDoorFirewallPolicy_update
=== PAUSE TestAccCdnFrontDoorFirewallPolicy_update
=== CONT  TestAccCdnFrontDoorFirewallPolicy_update
    testcase.go:113: Step 1/6 error: Error running pre-apply refresh: exit status 1
        
        Error: Unsupported argument
        
          on terraform_plugin_test.tf line 47, in resource "azurerm_cdn_frontdoor_firewall_policy" "test":
          47:     request_body_check_enabled     = false
        
        An argument named "request_body_check_enabled" is not expected here.
--- FAIL: TestAccCdnFrontDoorFirewallPolicy_update (13.25s)
FAIL
```

2024-01-09 07:43 UTC, harshavmb commented
Hi @katbyte ,

Thanks for pointing that! Indeed it was in the wrong place, nevertheless I feel it would have been better to put all `enabled`, `mode` & `request_body_check_enabled` in a `policy_settings` block. This way it would be more alinged to REST API specs. However this would mean it's a breaking change.

2024-01-10 12:49 UTC, catriona-m approved these changes
Hi @harshavmb, thanks for updating this - it looks like the tests are now passing. LGTM!

2024-01-10 12:50 UTC, merged