`azurerm_mssql_database` / `azurerm_mssql_server` - Added fields for database-level TDE
hashicorp/terraform-provider-azurerm pull request #24412
Opened 2024-01-06 07:54 UTC by dkuzmenok

Changes
======

- Fixed issue with setting `transparent_data_encryption_enabled`, when it is already set to same value. It was causing policy failures (looks like Setting `Enabled` to already `Enabled` was causing `Disable -> Enable` chain in new API, so added a check to prevent it).
- In data source `azurerm_mssql_database` new fields: `identity`, `transparent_data_encryption_enabled`, `transparent_data_encryption_key_vault_key_id`, `auto_key_rotation_enabled`
- In data source `azurerm_mssql_server` new fields: `transparent_data_encryption_key_vault_key_id`
- In resource `azurerm_mssql_database` new fields: `identity`, `transparent_data_encryption_key_vault_key_id`, `auto_key_rotation_enabled`

Basically we add support for setting TDE on a database level, that is supported with a newer API we now use.
Tests passed on my side.

Fixes #24316 
Fixes #24253

2024-01-08 03:46 UTC, katbyte requested changes
Thanks for the PR @dkuzmenok - but it looks like we have a test failure
```
------- Stdout: -------
=== RUN   TestAccMsSqlDatabase_complete
=== PAUSE TestAccMsSqlDatabase_complete
=== CONT  TestAccMsSqlDatabase_complete
    testcase.go:113: Step 3/4 error: Error running apply: exit status 1
        
        Error: unable to parse key: "": cannot parse azure key vault child ID: parse "": empty url
        
          with azurerm_mssql_database.test,
          on terraform_plugin_test.tf line 37, in resource "azurerm_mssql_database" "test":
          37: resource "azurerm_mssql_database" "test" {
        
--- FAIL: TestAccMsSqlDatabase_complete (564.94s)
FAIL
```

2024-01-08 10:39 UTC, dkuzmenok commented
> Thanks for the PR @dkuzmenok - but it looks like we have a test failure
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccMsSqlDatabase_complete
> === PAUSE TestAccMsSqlDatabase_complete
> === CONT  TestAccMsSqlDatabase_complete
>     testcase.go:113: Step 3/4 error: Error running apply: exit status 1
>         
>         Error: unable to parse key: "": cannot parse azure key vault child ID: parse "": empty url
>         
>           with azurerm_mssql_database.test,
>           on terraform_plugin_test.tf line 37, in resource "azurerm_mssql_database" "test":
>           37: resource "azurerm_mssql_database" "test" {
>         
> --- FAIL: TestAccMsSqlDatabase_complete (564.94s)
> FAIL
> ```

Please, make another run after my update to test cases.

2024-01-10 22:58 UTC, WodansSon commented
The two failures are due to API internal server errors and the other failure is in VM's so not related to this PR.

<img width="400" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/20408400/55459c9a-d184-4f0e-9ca9-3c08ee484b5b">

2024-01-10 23:21 UTC, katbyte requested changes
thanks for fixing the test @dkuzmenok - aside from one comment about a property name i think this looks good

2024-01-10 23:21 UTC, katbyte commented on internal/services/mssql/mssql_database_data_source.go
> +			"auto_key_rotation_enabled": {
```suggestion
			"transparent_data_encryption_key_automatic_rotation_enabled": {
```

2024-01-11 08:04 UTC, dkuzmenok commented on internal/services/mssql/mssql_database_data_source.go
> +			"auto_key_rotation_enabled": {
@katbyte Changed the name now.

2024-01-11 21:24 UTC, WodansSon commented
Both test fail with internal server errors, API issue... LGTM! 🚀 

<img width="396" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/20408400/bb4e1d30-cb07-4596-9b87-ea3668a7ea41">

2024-01-11 21:25 UTC, merged