new resource: `azurerm_spring_cloud_elastic_application_performance_monitoring`
hashicorp/terraform-provider-azurerm pull request #24507
Opened 2024-01-16 03:19 UTC by ms-henglu

…

2024-01-16 07:00 UTC, magodo requested changes
Thanks for this PR!
I have left some additional mostly minor comments that once addressed this should be good to merge 👍

2024-01-16 14:23 UTC, athlete1947 commented
Good work guys

2024-01-18 02:25 UTC, ms-henglu commented on internal/services/springcloud/spring_cloud_elastic_application_performance_monitoring_resource.go
> +			Type:         pluginsdk.TypeString,
Sure, I've changed it to a list, please take another look, thanks!

2024-01-18 02:35 UTC, magodo reviewed
LGTM!

2024-01-18 02:37 UTC, ms-henglu commented
Thanks!

2024-01-22 11:51 UTC, stephybun requested changes
Thanks @ms-henglu. I left some comments in-line, once they're fixed up we can take another look through.

2024-01-22 11:51 UTC, stephybun commented on internal/services/springcloud/spring_cloud_elastic_application_performance_monitoring_resource.go
> +				return fmt.Errorf("parsing spring service ID: %+v", err)
The parsing functions already return sufficient information in the error messages, there is no need to wrap these. 
```suggestion
				return err
```

2024-01-22 11:51 UTC, stephybun commented on internal/services/springcloud/spring_cloud_elastic_application_performance_monitoring_resource_test.go
> +func TestAccSpringCloudElasticApplicationPerformanceMonitoringPerformanceMonitoring_basic(t *testing.T) {
All the test names have duplicate `PerformanceMonitoring` at the end
```suggestion
func TestAccSpringCloudElasticApplicationPerformanceMonitoring_basic(t *testing.T) {
```

2024-01-22 11:51 UTC, stephybun commented on internal/services/springcloud/spring_cloud_elastic_application_performance_monitoring_resource_test.go
> +func TestAccSpringCloudElasticApplicationPerformanceMonitoringPerformanceMonitoring_requiresImport(t *testing.T) {
same here

2024-01-22 11:51 UTC, stephybun commented on internal/services/springcloud/spring_cloud_elastic_application_performance_monitoring_resource_test.go
> +func TestAccSpringCloudElasticApplicationPerformanceMonitoringPerformanceMonitoring_complete(t *testing.T) {
same here

2024-01-22 11:51 UTC, stephybun commented on internal/services/springcloud/spring_cloud_elastic_application_performance_monitoring_resource_test.go
> +func TestAccSpringCloudElasticApplicationPerformanceMonitoringPerformanceMonitoring_update(t *testing.T) {
same here

2024-01-22 11:51 UTC, stephybun commented on internal/services/springcloud/spring_cloud_elastic_application_performance_monitoring_resource_test.go
> +	return pointer.To(true), nil
```suggestion
	return pointer.To(resp.Model != nil), nil
```

2024-01-22 11:51 UTC, stephybun commented on internal/services/springcloud/spring_cloud_elastic_application_performance_monitoring_resource_test.go
> +  server_url              = "http://127.0.0.1:8200"
These values are identical to the ones in the `basic` config but they can be updated, can you please change them so we can test the update path for these too?

2024-01-22 11:51 UTC, stephybun commented on website/docs/r/spring_cloud_elastic_application_performance_monitoring.html.markdown
> +
We don't separate `Optional` arguments from the required ones
```suggestion
* `globally_enabled` - (Optional) Specifies whether the Spring Cloud Application Performance Monitoring resource for Application Insights is enabled globally. Defaults to `false`.

```

2024-01-29 06:57 UTC, ms-henglu commented
Hi @stephybun ,

Thanks for the code review, I've updated this PR as suggested. Please take another look, thanks!

2024-01-29 08:11 UTC, stephybun approved these changes
Thanks @ms-henglu and @magodo LGTM 👍

2024-01-29 08:11 UTC, merged