Adds TotalRetentionInDays to azurerm_log_analytics_workspace_table
hashicorp/terraform-provider-azurerm pull request #24513
Opened 2024-01-16 15:03 UTC by vanny96

As of now, the `azurerm_log_analytics_workspace_table` resource only allows to set the `retention_in_days` field for its tables
```
resource "azurerm_log_analytics_workspace_table" "example" {
  workspace_id      = azurerm_log_analytics_workspace.example.id
  name              = "AppMetrics"
  retention_in_days = 60
}
```

With this PR the goal is to be able to set also a `total_retention_in_days` using the same logic used for `retention_in_days`.

2024-01-22 11:34 UTC, stephybun requested changes
Thanks for this PR @vanny96. Could you please add a test for this new property as well as update the docs?

2024-02-02 00:53 UTC, katbyte requested changes
We have a test failure here:
```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccLogAnalyticsWorkspaceTable_plan
=== PAUSE TestAccLogAnalyticsWorkspaceTable_plan
=== CONT  TestAccLogAnalyticsWorkspaceTable_plan

------- Stderr: -------
panic: Invalid address to set: []string{"total_retention_in_datys"}

goroutine 531 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc000b3ed80, {0x7c90bf5, 0x18}, {0x7ce8600, 0xf409ee0})
	/opt/teamcity-agent/work/3337027aeff310bf/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:233 +0x2b5
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.ResourceMetaData.Encode({0xc0020a2000, {0x9771c98, 0xc0029b0858}, 0xc000b3ed80, 0x0, {0x9771cd0, 0xf4bb220}}, {0x7a1d340, 0xc0049d5180})
	/opt/teamcity-agent/work/3337027aeff310bf/internal/sdk/resource_encode.go:31 +0x247
github.com/hashicorp/terraform-provider-azurerm/internal/services/loganalytics.(*LogAnalyticsWorkspaceTableResource).Read.LogAnalyticsWorkspaceTableResource.Read.func1({0x9770d80, 0xc0028c0f50}, {0xc0020a2000, {0x9771c98, 0xc0029b0858}, 0xc000b3ed80, 0x0, {0x9771cd0, 0xf4bb220}})
	/opt/teamcity-agent/work/3337027aeff310bf/internal/services/loganalytics/log_analytics_workspace_table_resource.go:241 +0x55b
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func2({0x9770d80, 0xc0028c0f50}, 0x0?, {0x7efaf60?, 0xc0020a2000?})
	/opt/teamcity-agent/work/3337027aeff310bf/internal/sdk/wrapper_resource.go:62 +0x1c8
```

2024-02-02 09:07 UTC, vanny96 commented
Sorry for that, I'll try to debug it a bit! Thank you for your patience!

2024-02-09 00:55 UTC, katbyte commented on internal/services/loganalytics/log_analytics_workspace_table_resource_test.go
> +  total_retention_in_days = 20
```suggestion
  total_retention_in_days = 32
```

2024-02-09 01:02 UTC, katbyte commented on internal/services/loganalytics/log_analytics_workspace_table_resource_test.go
> +				check.That(data.ResourceName).Key("total_retention_in_days").HasValue("20"),
```suggestion
				check.That(data.ResourceName).Key("total_retention_in_days").HasValue("32"),
```

2024-02-09 01:22 UTC, katbyte approved these changes
Thanks @vanny96 - LGTM 🎢

2024-02-09 01:23 UTC, merged