New data source `azurerm_ip_groups`
hashicorp/terraform-provider-azurerm pull request #24540
Opened 2024-01-17 22:24 UTC by KyMidd

`azurerm_ip_group` data source only permits fetching the info of one data source. This data intends to fetch the data from multiple IP Groups within a resource group by using the `name` attribute as a substring match. 

The testing suite currently fails - it's showing the IDs and Names (which I've confirmed are there) aren't being added to the `d` object for some reason. Need to figure that out. 
```
❯ TF_ACC=1 go test -v ./internal/services/network -timeout=1000m -run='TestAccDataSourceIPGroups_'
=== RUN   TestAccDataSourceIPGroups_noResults
=== PAUSE TestAccDataSourceIPGroups_noResults
=== RUN   TestAccDataSourceIPGroups_basic
=== PAUSE TestAccDataSourceIPGroups_basic
=== RUN   TestAccDataSourceIPGroups_complete
=== PAUSE TestAccDataSourceIPGroups_complete
=== CONT  TestAccDataSourceIPGroups_noResults
=== CONT  TestAccDataSourceIPGroups_complete
=== CONT  TestAccDataSourceIPGroups_basic
Names set as:  []
IDs set as:  []
Names set as:  []
IDs set as:  []
Names set as:  []
IDs set as:  []
=== NAME  TestAccDataSourceIPGroups_complete
    testcase.go:113: Step 1/1 error: Check failed: Check 1/2 error: data.azurerm_ip_groups.test: Attribute 'ids.#' not found
Names set as:  []
IDs set as:  []
=== NAME  TestAccDataSourceIPGroups_basic
    testcase.go:113: Step 1/1 error: Check failed: Check 1/2 error: data.azurerm_ip_groups.test: Attribute 'ids.#' not found
Names set as:  []
IDs set as:  []
Names set as:  []
IDs set as:  []
--- FAIL: TestAccDataSourceIPGroups_complete (41.31s)
--- FAIL: TestAccDataSourceIPGroups_basic (44.43s)
--- PASS: TestAccDataSourceIPGroups_noResults (108.46s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-azurerm/internal/services/network	112.190s
FAIL
```

2024-01-18 14:53 UTC, tombuildsstuff commented
hey @KyMidd 

Thanks for this PR.

Data Sources (and Resources) are only written to the state when they've got a Resource ID associated with them - as in this case the Data Source isn't calling `d.SetID(` there's no Resource ID - meaning this isn't tracked in the state.

Since this Data Source is listing the IP Groups available within the specified Resource Group, it'd make sense to use the Resource Group ID as the ID for this Data Source - which is available [in `commonids` as `commonids.NewResourceGroupID`](https://github.com/hashicorp/go-azure-helpers/blob/2366caf86339741802a22c964cd131af57db7a6b/resourcemanager/commonids/resource_group.go#L22) - meaning that if you add:

```go
subscriptionId := meta.(*clients.Client).Account.SubscriptionID
id := commonids.NewResourceGroupID(subscriptionId, resourceGroupName)
d.SetID(id.ID())
```

Then this Data Source should start being tracked in the state (and means that the tests will pass) - would you be able to take a look and see if that works for you?

Thanks!

2024-01-18 20:28 UTC, KyMidd commented
> Data Sources (and Resources) are only written to the state when they've got a Resource ID associated with them

Ooooooooohhhhhh! Thank you, that helps a ton! With that change, and a little cleanup of the tests, I'm able to compile the provider and this functionality works! 🥳 

Interestingly, the checks PASS in VSC, but fail in the console. I don't fully understand that yet, so poking around why. Current results from the terminal are in the PR summary now.

2024-01-22 08:29 UTC, stephybun requested changes
Thanks for this PR @KyMidd.

Overall this looks fine, I left a minor comment on the use of sets in data sources. Once that's been addressed we can run the tests and if they run through this should be good to go!

Also just as an aside, we currently have a mix of [untyped and typed resources/data sources](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/best-practices.md#typed-vs-untyped-resources) in the provider with the goal being to move all untyped resource/data source to typed ones in preparation for the next major release of the provider.

Since (I think?) this is your first contribution to the provider I'm not going to ask you to convert this into a typed data source, but for future contributions I'd recommend checking out our [Contributor Docs](https://github.com/hashicorp/terraform-provider-azurerm/tree/main/contributing) on adding new types resources/data sources 🙂

2024-01-22 08:29 UTC, stephybun commented on internal/services/network/ip_groups_data_source.go
> +				Set:      pluginsdk.HashString,
In data sources every item gets the same hash code, so we should use a List here
```suggestion
				Type:     pluginsdk.TypeList,
				Computed: true,
				Elem:     &pluginsdk.Schema{Type: pluginsdk.TypeString},
```

2024-01-22 08:29 UTC, stephybun commented on internal/services/network/ip_groups_data_source.go
> +				Set:      pluginsdk.HashString,
Same here
```suggestion
				Type:     pluginsdk.TypeList,
				Computed: true,
				Elem:     &pluginsdk.Schema{Type: pluginsdk.TypeString},
```

2024-01-22 16:33 UTC, KyMidd commented
> Since (I think?) this is your first contribution to the provider

It is my first contribution! 🎉  

> Since (I think?) this is your first contribution to the provider I'm not going to ask you to convert this into a typed data source, but for future contributions I'd recommend checking out our [Contributor Docs](https://github.com/hashicorp/terraform-provider-azurerm/tree/main/contributing) on adding new types resources/data sources 🙂

I'm a n00b at Go, so I don't fully understand but I'll read the docs over and educate myself. Hopefully I can come back here later once I understand and fix this up to be better compliant. 

> Once that's been addressed we can run the tests and if they run through this should be good to go!

Done! Thanks so much for the info and suggested code blocks 😸

2024-01-22 16:47 UTC, tiwood commented
If I'm understanding this correctly, this new DS is returning the names and resource IDs of IP groups in a given RG.

This can already be accomplished using the `azurerm_resources` data source:

```terraform
data "azurerm_resources" "example" {
  resource_group_name = "example-resources"
  type  = "Microsoft.Network/IpGroups"
}
```

2024-01-22 16:53 UTC, KyMidd commented
> This can already be accomplished using the `azurerm_resources` data source:

Oh, that's awesome! I didn't realize that existed. It doesn't appear to also offer name filtering, but that could for sure be done as a secondary action. 

I think it's still useful to have data lookups like this, because they're so easy to consume and use. Defer to you and the team if you'd prefer to not use these bespoke data lookups. :)

2024-01-22 18:19 UTC, KyMidd commented
I mocked that locally, and it's not nearly as easy to use the `azurerm_resources` vs this resource type. I think it's still a great idea to move forward with these bespoke resources, and folks can use the `azurerm_resources` with sufficient knowledge or if the bespoke resources don't yet exist. 

Here's an example of using this new resource: 
```hcl
data "azurerm_ip_groups" "example" {
  resource_group_name = "example-resources"
  name = "substring"
}
output "names" {
  value = data.azurerm_ip_groups.example.names
}
```

And here's the identical functionality using the `azurerm_resources` resource. Anytime the answer is "just use regex" I think we should consider simpler alternatives :) 
```hcl
data "azurerm_resources" "example" {
  resource_group_name = "example-resources"
  type  = "Microsoft.Network/IpGroups"
}
output "names" {
  [for r in data.azurerm_resources.example.resources : r.name if can(regex("substring", r.name))]
}
```

2024-01-23 08:57 UTC, stephybun approved these changes
Thanks for making those changes @KyMidd! The linter is still failing but it seems to be error'ing on something outside of this project, so I'm going to ignore it. LGTM 🚀

2024-01-23 08:57 UTC, merged