add sku to stream_analytics_cluste and stream_analytics_job
hashicorp/terraform-provider-azurerm pull request #24554
Opened 2024-01-19 01:39 UTC by katbyte

2024-01-22 07:24 UTC, stephybun requested changes

2024-01-22 07:24 UTC, stephybun commented on internal/services/streamanalytics/stream_analytics_cluster_resource.go
> +			Default:  clusters.ClusterSkuNameDefault,
Can't set a default if property is required?

2024-01-22 07:24 UTC, stephybun commented on internal/services/streamanalytics/stream_analytics_job_resource.go
> +				Default:  string(streamingjobs.SkuNameStandard),
Ditto

2024-01-24 21:06 UTC, katbyte commented
LGTM aside from the CI failures 😱

2024-01-24 23:47 UTC, merged