azurerm_kubernetes_cluster_node_pool - support updating taints
hashicorp/terraform-provider-azurerm pull request #24658
Opened 2024-01-26 13:41 UTC by mseiwald

Closes #24038

2024-01-26 14:26 UTC, stephybun requested changes
Thanks @mseiwald.

Could you add an acceptance test to validate this behaviour?

2024-01-26 14:26 UTC, stephybun commented on internal/services/containers/kubernetes_cluster_node_pool_resource.go
> +			ForceNew: false,
If an attribute is no longer valid we usually remove it instead of setting it to `false`
```suggestion
```

2024-01-26 18:10 UTC, mseiwald commented
> Thanks @mseiwald.
> 
> Could you add an acceptance test to validate this behaviour?

I replaced the existing test with a more comprehensive test with update steps.

2024-01-29 08:53 UTC, stephybun requested changes
Test passes which is great, I forgot to mention in the initial review that we still need to update the docs, once that's done this should be good to go!

2024-01-29 09:39 UTC, mseiwald commented
> Test passes which is great, I forgot to mention in the initial review that we still need to update the docs, once that's done this should be good to go!

Updated the docs.

2024-01-29 10:13 UTC, stephybun approved these changes
Thanks @mseiwald LGTM 🚀

2024-01-29 10:14 UTC, merged