New resource `azurerm_virtual_desktop_scaling_plan_host_pool_association`
hashicorp/terraform-provider-azurerm pull request #24670
Opened 2024-01-27 17:52 UTC by alexwilcox9

PR for the creation of a new resource `azurerm_virtual_desktop_scaling_plan_host_pool_association`

### Why
In my AVD deployments I have a normal worktime scaling plan and a holiday period scaling plan. I'd like to have a variable to easily switch from one SP to another. Using the `host_pool` block within the current `azurerm_virtual_desktop_scaling_plan` you would need to do something with dynamic blocks and there doesn't seem to be a clean solution. 
Having a dedicated resource would make this much easier.

It would also be more inline with the existing resource `azurerm_virtual_desktop_workspace_application_group_association` (which this PR is mostly copied from)

### Help
When using this resource alongside `azurerm_virtual_desktop_scaling_plan` there will be conflicts where an association has been created in the new resource but not declared in a `host_pool` block. Is there a way to prevent the `host_pool` block being checked if it hasn't been declared in the users configuration?

### Documentation and Tests
If you're happy with this resource in principle I'll get the docs and tests written up
Thanks in advance!

2024-03-19 18:34 UTC, mbfrahry requested changes
Hey @alexwilcox9, this PR is looking on the right track but we'll need some tests to confirm it's functionality.

Your ask about what we could be done about `host_pool` on the parent resource showing a diff could be solved by adding `Computed: true` to `host_pool`.

I am wondering if there is a way we could solve this with a conditionals though. Could you open an issue describing your issue and what you're trying to do in a little more detail?

2024-04-15 12:27 UTC, alexwilcox9 commented
Sorry for the slow response, only just got time to come back around to this.

So to describe what I'm trying to do in more detail; I'm looking to make it simpler to switch which scaling plan is currently assigned to a hostpool.

Currently you could probably use a dynamic block to only create the `host_pool` block when a conditional is true but having a separate resource for association is more consistent with the rest of the AVD resources and makes cleaner code

Here's an example of how I think it would be done with conditionals
https://gist.github.com/alexwilcox9/033de7fe2ad46236be0d6ee9062a8462

Whereas the same could be achieved with the new resource as follows
```terraform
resource "azurerm_virtual_desktop_scaling_plan_host_pool_association" "example" {
  host_pool_id    = azurerm_virtual_desktop_host_pool.example.id
  scaling_plan_id = var.holiday ? azurerm_virtual_desktop_scaling_plan.holiday.id : azurerm_virtual_desktop_scaling_plan.example.id
  enabled         = true
}
```

Another problem I find with the conditionals is that Terraform tries to update both scaling plans at the same time causing an error. Meaning I always need to run the apply twice
```
azurerm_virtual_desktop_scaling_plan.holiday: Modifying... [id=/subscriptions/<SUB ID>/resourceGroups/example-rg/providers/Microsoft.DesktopVirtualization/scalingPlans/holiday-scalingplan]
azurerm_virtual_desktop_scaling_plan.example: Modifying... [id=/subscriptions/<SUB ID>/resourceGroups/example-rg/providers/Microsoft.DesktopVirtualization/scalingPlans/regular-scalingplan]
azurerm_virtual_desktop_scaling_plan.example: Modifications complete after 3s [id=/subscriptions/<SUB ID>/resourceGroups/example-rg/providers/Microsoft.DesktopVirtualization/scalingPlans/regular-scalingplan]
╷
│ Error: updating Scaling Plan (Subscription: "<SUB ID>"
│ Resource Group Name: "example-rg"
│ Scaling Plan Name: "holiday-scalingplan"): unexpected status 400 with error: 400: ActivityId: e4a56646-173e-4820-88a2-8a85aa4beee9 Error: ≤{"error":{"code":"BadRequest","message":"Host pools already assigned to another scaling plan: '/subscriptions/<SUB ID>/resourceGroups/example-rg/providers/Microsoft.DesktopVirtualization/hostPools/example-hostpool'","target":"/api/scalingPlans/subscriptions/<SUB ID>/resourceGroups/example-rg/scalingPlans/holiday-scalingplan"}}≥
│ 
│   with azurerm_virtual_desktop_scaling_plan.holiday,
│   on main.tf line 98, in resource "azurerm_virtual_desktop_scaling_plan" "holiday":
│   98: resource "azurerm_virtual_desktop_scaling_plan" "holiday" {
│ 
╵
```

I hope that helps explain why I think this new resource would be beneficial

2024-04-19 21:10 UTC, mbfrahry requested changes
Hey @alexwilcox9, I can see the use for this resource after you walked me through how awful it is to achieve what you're trying to do.

I've left another review as I do have concerns that bringing this resource in will cause breaking changes as you've changed existing tests.

2024-05-23 21:57 UTC, alexwilcox9 commented on internal/services/desktopvirtualization/parse/scaling_plan_host_pool_association.go
> +func ScalingPlanHostPoolAssociationIDInsensitively(input string) (*ScalingPlanHostPoolAssociationId, error) {
Fair enough, removed

2024-05-23 21:57 UTC, alexwilcox9 commented on internal/services/desktopvirtualization/parse/scaling_plan_host_pool_association.go
> +func ScalingPlanHostPoolAssociationID(input string) (*ScalingPlanHostPoolAssociationId, error) {
Just wanted to clarify on this front - this ID is made up of two existing resource IDs that already have tests written so should my tests duplicate those and build up both resource IDs from scratch or just test the parsing of the two combined

For example testing the following
`/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.DesktopVirtualization/scalingPlans/scalingPlanValue`  Invalid
`/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.DesktopVirtualization/scalingPlans/scalingPlanValue|/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.DesktopVirtualization/hostPools/hostPoolValue` Valid
`/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.DesktopVirtualization/scalingPlans/scalingPlanValue|/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.DesktopVirtualization/hostPools/hostPoolValue|/extra` Invalid

2024-05-23 21:57 UTC, alexwilcox9 commented on internal/services/desktopvirtualization/virtual_desktop_scaling_plan_resource_test.go
> -resource "azurerm_role_definition" "test" {
I saw an opportunity to tidy up the tests, when Scaling Plans first released they were only in a handful of regions and didn't have a built in role so creating a custom one was required.
Now there's a built in role and more regions are supported so wanted to update the tests to reflect that

2024-05-23 21:57 UTC, alexwilcox9 commented on internal/services/desktopvirtualization/virtual_desktop_scaling_plan_resource_test.go
> +      load_balancer_type,
The scaling plan changes the load balancer type at different times of day but now I've realised I can just change the scaling plan to use the same load balancer type at all times so no need to ignore changes

2024-05-23 21:57 UTC, alexwilcox9 commented on internal/services/desktopvirtualization/virtual_desktop_scaling_plan_host_pool_association_resource.go
> +	if !exists {
Makes sense, I've added that now

2024-05-23 22:01 UTC, alexwilcox9 commented
Hey, thanks for the review and apologies for the delay in getting back to it. I've replied to your comments and made some changes

2024-05-23 23:29 UTC, alexwilcox9 commented
I also found that during any create/update/delete operation the scaling plans schedule would disappear.
I'm not sure why this happens as other attributes like description and time zone that I don't touch are left alone. In any case, I've added the existing schedules to the patch properties and that seems to solve it

2024-06-21 22:44 UTC, katbyte requested changes
Thanks for the changes @alexwilcox9 - Looks like this is missing documentation for the new resource. once that is added i think this can be reviewed one final time and merged

2024-06-28 01:49 UTC, katbyte approved these changes
Thanks @alexwilcox9 ! LGTM 🍖

2024-06-28 01:49 UTC, merged