new resource: `azurerm_spring_cloud_new_relic_application_performance_monitoring`
hashicorp/terraform-provider-azurerm pull request #24699
Opened 2024-01-30 07:32 UTC by ms-henglu

```
=== RUN   TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_basic
=== PAUSE TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_basic
=== CONT  TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_basic
=== RUN   TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_requiresImport
=== PAUSE TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_requiresImport
=== CONT  TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_requiresImport
=== RUN   TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_complete
=== PAUSE TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_complete
=== CONT  TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_complete
=== RUN   TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_update
=== PAUSE TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_update
=== CONT  TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_update
--- PASS: TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_requiresImport (542.21s)
--- PASS: TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_basic (555.97s)
--- PASS: TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_complete (637.54s)
--- PASS: TestAccSpringCloudNewRelicApplicationPerformanceMonitoring_update (693.14s)
PASS

Process finished with the exit code 0
```

2024-01-31 02:49 UTC, magodo requested changes
Thanks for this PR!
I have left some additional mostly minor comments that once addressed this should be good to merge 👍

2024-01-31 02:49 UTC, magodo commented on internal/services/springcloud/spring_cloud_new_relic_application_performance_monitoring_resource.go
> +				return fmt.Errorf("parsing spring service ID: %+v", err)
```suggestion
				return err
```

2024-01-31 02:49 UTC, magodo commented on website/docs/r/spring_cloud_new_relic_application_performance_monitoring.html.markdown
> +  globally_enabled                = true
These boolean properties all have default values, so can we omit them in the example to make it simple?

2024-01-31 02:49 UTC, magodo commented on website/docs/r/spring_cloud_new_relic_application_performance_monitoring.html.markdown
> +* `labels` - (Optional) Specifies the labels to be added to the New Relic application. The format is `tagName1:tagValue1;tagName2:tagValue2;tagName3:tagValue3`.
Can we make this to be a list instead?

2024-01-31 02:49 UTC, magodo commented on internal/services/springcloud/spring_cloud_new_relic_application_performance_monitoring_resource_test.go
> +  license_key                     = "test-license-key"
Can we change these values to be different than `basic`?

2024-01-31 02:49 UTC, magodo commented on internal/services/springcloud/spring_cloud_new_relic_application_performance_monitoring_resource.go
> +			Default:  false,
```suggestion
```

2024-01-31 02:49 UTC, magodo commented on internal/services/springcloud/spring_cloud_new_relic_application_performance_monitoring_resource_test.go
> +  agent_enabled                   = true
Same here

2024-01-31 02:49 UTC, magodo commented on internal/services/springcloud/spring_cloud_new_relic_application_performance_monitoring_resource_test.go
> +  auto_transaction_naming_enabled = true
Same here

2024-01-31 02:49 UTC, magodo commented on internal/services/springcloud/spring_cloud_new_relic_application_performance_monitoring_resource_test.go
> +  custom_tracing_enabled          = true
Same here

2024-02-01 02:23 UTC, ms-henglu commented
Thanks @magodo ! I've updated it as suggested.

2024-02-01 03:07 UTC, magodo requested changes
Some minor comments, which LGTM once fixed.

2024-02-01 03:07 UTC, magodo commented on internal/services/springcloud/spring_cloud_new_relic_application_performance_monitoring_resource_test.go
> +    "tagName2" = "tagValue2"
The keys can be unquoted?

2024-02-01 03:07 UTC, magodo commented on website/docs/r/spring_cloud_new_relic_application_performance_monitoring.html.markdown
> +    "tagName2" = "tagValue2"
Same here

2024-02-01 04:18 UTC, ms-henglu commented on internal/services/springcloud/spring_cloud_new_relic_application_performance_monitoring_resource_test.go
> +    "tagName2" = "tagValue2"
Thanks! I've fixed it.

2024-02-01 05:19 UTC, magodo commented
LGTM!

2024-02-02 00:47 UTC, katbyte approved these changes
LGTM me too 🚡

2024-02-02 00:47 UTC, merged