[WIP] azurerm_cosmosdb_account add minimal_tls_version
hashicorp/terraform-provider-azurerm pull request #24711
Opened 2024-01-30 17:47 UTC by rizkybiz

fixes #21295

2024-01-31 01:34 UTC, neil-yechenwei commented
Service team confirmed that there is a known issue that the default value of `minimalTlsVersion` of the source CosmosDB Account returned by service API is `Tls12` when it isn't set in the request payload but the default value of `minimalTlsVersion` of the restored CosmosDB Account returned by service API is `Tls` when it isn't set in the request payload. So service team is still investigating this issue.

Note: TestAccCosmosDBAccount_restoreCreateMode would fail once this PR is applied.

2024-01-31 07:04 UTC, jackofallops commented
HI @rizkybiz - Thanks for this PR. Unfortunately, as noted in an earlier PR here https://github.com/hashicorp/terraform-provider-azurerm/pull/24615#discussion_r1469508193  this property has an upstream API issue which we are working with MSFT to resolve.  Due to this  ongoing work with the service team, I'm going to close this for now and we can take a look again when the upstream issue is resolved.
Thanks again!

2024-02-13 19:48 UTC, katbyte requested changes
Hey @rizkybiz - While there is an underlaying API bug this is something i think we can work around by in the create function once we’ve restored the CosmosDB account we can do an update on the other values (e.g. tls) to ensure they match the configuration

2024-02-13 19:48 UTC, katbyte commented on internal/services/cosmos/cosmosdb_account_resource.go
> +				Optional:     true,
should we be specifying a default value here? or making it computed?

2024-02-13 19:48 UTC, katbyte commented on internal/services/cosmos/cosmosdb_account_resource.go
> +	}
how come we need this? shouldn't the allowed values match the constant?

2024-02-14 22:43 UTC, closed without merging