`azurerm_spring_cloud_gateway` - support for the `application_performance_monitoring_ids` property
hashicorp/terraform-provider-azurerm pull request #24919
Opened 2024-02-18 02:29 UTC by ms-henglu

…

2024-02-19 14:42 UTC, catriona-m requested changes
Thanks for this @ms-henglu - I left a couple of suggestions inline, but otherwise this is looking good. Thanks!

2024-02-19 14:42 UTC, catriona-m commented on internal/services/springcloud/spring_cloud_gateway_resource.go
> +	out := make([]string, 0)
```suggestion
        out := make([]string, 0)
	if input == nil {
		return out, nil
	}
```

2024-02-19 14:42 UTC, catriona-m commented on internal/services/springcloud/spring_cloud_gateway_resource_test.go
> +}
should we move this to `apms` rather than have it in `template` if it isn't applicable to the other tests?

2024-02-19 14:42 UTC, catriona-m commented on internal/services/springcloud/spring_cloud_gateway_resource_test.go
> +	})
could we include a step where we update the value of `application_performance_monitoring_ids` here too?

2024-02-23 03:29 UTC, ms-henglu commented
Thanks for the code review, I've updated as suggested.

2024-02-23 15:22 UTC, catriona-m approved these changes
Hi @ms-henglu - thanks for making the requested changes to this. I've had another look through and this LGTM! Thanks!

2024-02-23 15:23 UTC, merged