`azurerm_data_factory_pipeline`: fix `headers` acceptable value
hashicorp/terraform-provider-azurerm pull request #24921
Opened 2024-02-18 09:16 UTC by ziyeqf

fix #24758

2024-02-19 03:25 UTC, magodo requested changes
Thanks for this PR!
I have left some additional mostly minor comments that once addressed this should be good to merge 👍

2024-02-19 03:25 UTC, magodo commented on internal/services/datafactory/azuresdkhacks/pipelines.go
> +
If this file is just a copy paste of the original implementation, we shall also just write down something like: "This file is just a copy paste from file: ...".

2024-02-19 05:34 UTC, magodo commented
LGTM!

2024-02-19 09:00 UTC, tombuildsstuff commented
@ziyeqf rather than doing this and needing to continue patching around this in the future - is `hashicorp/go-azure-sdk` usable as a replacement here? https://github.com/hashicorp/go-azure-sdk/blob/main/resource-manager/datafactory/2018-06-01/pipelines/method_createorupdate.go

2024-02-20 02:13 UTC, ziyeqf commented
@tombuildsstuff I checked it, but it seems `go-azure-sdk` does not have the needed variant of `activity`
`go-azure-sdk`: https://github.com/hashicorp/go-azure-sdk/blob/4f74876e2154eae6add03690707943f92daad264/resource-manager/automation/2015-10-31/activity/model_activityproperties.go#L12
`kermit`: 
```
// WebActivity web activity.
type WebActivity struct {
	// WebActivityTypeProperties - Web activity properties.
	*WebActivityTypeProperties `json:"typeProperties,omitempty"`
	// LinkedServiceName - Linked service reference.
	LinkedServiceName *LinkedServiceReference `json:"linkedServiceName,omitempty"`
	// Policy - Activity policy.
	Policy *ActivityPolicy `json:"policy,omitempty"`
	// AdditionalProperties - Unmatched properties from the message are deserialized this collection
	AdditionalProperties map[string]interface{} `json:""`
	// Name - Activity name.
	Name *string `json:"name,omitempty"`
	// Description - Activity description.
	Description *string `json:"description,omitempty"`
	// State - Activity state. This is an optional property and if not provided, the state will be Active by default. Possible values include: 'ActivityStateActive', 'ActivityStateInactive'
	State ActivityState `json:"state,omitempty"`
	// OnInactiveMarkAs - Status result of the activity when the state is set to Inactive. This is an optional property and if not provided when the activity is inactive, the status will be Succeeded by default. Possible values include: 'ActivityOnInactiveMarkAsSucceeded', 'ActivityOnInactiveMarkAsFailed', 'ActivityOnInactiveMarkAsSkipped'
	OnInactiveMarkAs ActivityOnInactiveMarkAs `json:"onInactiveMarkAs,omitempty"`
	// DependsOn - Activity depends on condition.
	DependsOn *[]ActivityDependency `json:"dependsOn,omitempty"`
	// UserProperties - Activity user properties.
	UserProperties *[]UserProperty `json:"userProperties,omitempty"`
	// Type - Possible values include: 'TypeBasicActivityTypeActivity', 'TypeBasicActivityTypeExecuteWranglingDataflow', 'TypeBasicActivityTypeSparkJob', 'TypeBasicActivityTypeSynapseNotebook', 'TypeBasicActivityTypeScript', 'TypeBasicActivityTypeExecuteDataFlow', 'TypeBasicActivityTypeAzureFunctionActivity', 'TypeBasicActivityTypeDatabricksSparkPython', 'TypeBasicActivityTypeDatabricksSparkJar', 'TypeBasicActivityTypeDatabricksNotebook', 'TypeBasicActivityTypeDataLakeAnalyticsUSQL', 'TypeBasicActivityTypeAzureMLExecutePipeline', 'TypeBasicActivityTypeAzureMLUpdateResource', 'TypeBasicActivityTypeAzureMLBatchExecution', 'TypeBasicActivityTypeGetMetadata', 'TypeBasicActivityTypeWebActivity', 'TypeBasicActivityTypeLookup', 'TypeBasicActivityTypeAzureDataExplorerCommand', 'TypeBasicActivityTypeDelete', 'TypeBasicActivityTypeSQLServerStoredProcedure', 'TypeBasicActivityTypeCustom', 'TypeBasicActivityTypeExecuteSSISPackage', 'TypeBasicActivityTypeHDInsightSpark', 'TypeBasicActivityTypeHDInsightStreaming', 'TypeBasicActivityTypeHDInsightMapReduce', 'TypeBasicActivityTypeHDInsightPig', 'TypeBasicActivityTypeHDInsightHive', 'TypeBasicActivityTypeCopy', 'TypeBasicActivityTypeExecution', 'TypeBasicActivityTypeWebHook', 'TypeBasicActivityTypeAppendVariable', 'TypeBasicActivityTypeSetVariable', 'TypeBasicActivityTypeFilter', 'TypeBasicActivityTypeValidation', 'TypeBasicActivityTypeUntil', 'TypeBasicActivityTypeFail', 'TypeBasicActivityTypeWait', 'TypeBasicActivityTypeForEach', 'TypeBasicActivityTypeSwitch', 'TypeBasicActivityTypeIfCondition', 'TypeBasicActivityTypeExecutePipeline', 'TypeBasicActivityTypeContainer'
	Type TypeBasicActivity `json:"type,omitempty"`
}
```

2024-02-20 16:20 UTC, tombuildsstuff commented on internal/services/datafactory/azuresdkhacks/pipelines.go
> +	}
can we remove the validation here?

2024-02-20 18:02 UTC, katbyte approved these changes
Thanks @ziyeqf - LGTM 🎧

2024-02-20 18:02 UTC, merged