Doc: Update document of `azurerm_storage_account` for the viable combinations for `(queue|share)_properties`
hashicorp/terraform-provider-azurerm pull request #25427
Opened 2024-03-27 06:02 UTC by magodo

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-03-27 07:33 UTC, tombuildsstuff requested changes
Could we rephrase these to be clearer?

2024-03-27 07:33 UTC, tombuildsstuff commented on website/docs/r/storage_account.html.markdown
> +~> **NOTE:** `queue_properties` can only be set for `Standard` (`account_tier`) `StorageV2` (`account_kind`) Storage Accounts.
Perhaps this'd be clearer as:

```suggestion
~> **NOTE:** `queue_properties` can only be configured when `account_tier` is set to `Standard` and `account_kind` is set to `StorageV2` Storage Accounts.
```

(assuming I've inferred that correctly from the message)?

2024-03-27 07:33 UTC, tombuildsstuff commented on website/docs/r/storage_account.html.markdown
> +~> **NOTE:** `share_properties` can only be set for `Standard` (`account_tier`) `StorageV2` (`account_kind`) or `Premium` (`account_tier`) `FileStorage` (`account_kind`) Storage Accounts.
(as above) I think we could probably reword this to be clearer, are these two combinations (Standard+StorageV2 and Premium+FileStorage)? If so:

```suggestion
~> **NOTE:** `share_properties` can only be configured when either `account_tier` is `Standard` and `account_kind` is `StorageV2` - or when `account_tier` is `Premium` and `account_kind` is `FileStorage`.
```

2024-03-27 17:24 UTC, rcskosir commented
@magodo :wave: Thank you for using our new PR template! Can you please update the template to include the description for this PR under the description heading? This helps with the review process as well as traceability in the future for our users.

2024-03-28 11:31 UTC, tombuildsstuff approved these changes
Otherwise LGTM 👍

2024-03-28 11:31 UTC, tombuildsstuff commented on website/docs/r/storage_account.html.markdown
> +~> **NOTE:** `queue_properties` can only be configured when `account_tier` is set to `Standard` and `account_kind` is set to `StorageV2` Storage Accounts.
```suggestion
~> **NOTE:** `queue_properties` can only be configured when `account_tier` is set to `Standard` and `account_kind` is set to `StorageV2`.
```

we can ditch `Storage Accounts` here?

2024-03-29 01:41 UTC, MedFazazi commented
Hi there, have you had a chance to check out my comment on this issue?

https://github.com/hashicorp/terraform-provider-azurerm/issues/25422#issuecomment-2024173406

2024-03-29 06:30 UTC, magodo commented
@tombuildsstuff As @MedFazazi has mentioned, our existing feature check didn't account for the kind `Storage`, I've modified my PR to extend the support level of `(blob|queue|share)_properties` for `Storage` kind then. Please take another look!

2024-03-31 14:01 UTC, MedFazazi commented
Hello @magodo,
Thank you for your efforts in extending the support level for blob_properties, queue_properties, and share_properties to the Storage kind. I wanted to kindly inquire if there's a possibility to also include support for configuring table_properties, including logging features, in Azure Storage Accounts. The ability to manage table service properties, including logging, through Terraform would greatly enhance its usability for various use cases.

Thank you for considering this request!

Warm regards,

2024-04-02 05:50 UTC, tombuildsstuff approved these changes
Left a couple of comments around the docs but otherwise 👍

2024-04-02 05:50 UTC, tombuildsstuff commented on website/docs/r/storage_account.html.markdown
> +~> **NOTE:** `queue_properties` can only be configured when `account_tier` is set to `Standard` and `account_kind` is set to `Storage(V2)`.
The value for the constant is `StorageV2` and not `Storage(V2)`?

```suggestion
~> **NOTE:** `queue_properties` can only be configured when `account_tier` is set to `Standard` and `account_kind` is set to either `Storage` or `StorageV2`.
```

2024-04-02 05:50 UTC, tombuildsstuff commented on website/docs/r/storage_account.html.markdown
> +~> **NOTE:** `share_properties` can only be configured when either `account_tier` is `Standard` and `account_kind` is `Storage(V2)` - or when `account_tier` is `Premium` and `account_kind` is `FileSt
```suggestion
~> **NOTE:** `share_properties` can only be configured when either `account_tier` is `Standard` and `account_kind` is either `Storage` or `StorageV2` - or when `account_tier` is `Premium` and `account_kind` is `FileStorage`.
```

2024-04-08 20:45 UTC, merged