New Resource: `azurerm_maintenance_assignment_dynamic_scope`
hashicorp/terraform-provider-azurerm pull request #25467
Opened 2024-03-29 12:28 UTC by ASHR4

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

Adding support to configure dynamic scopes on maintenance configuration resources.

Having some trouble getting this to work, with the majority of the code being complete, and I was hoping for some support/direction.

On the `Create()` [method](https://github.com/ASHR4/terraform-provider-azurerm/blob/feature/dynamic-maintenance-assignment/internal/services/maintenance/maintenance_assignment_dynamic_scope_resource.go#L168-L173) I'm getting an `Internal Server Error` when checking the presence of an existing configuration response. 

 `Error: checking for presence of existing Scoped Configuration Assignment (Scope: "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxxxxx-xxxxxxxxx"
        Configuration Assignment Name: "acctest-MC240329112250453963"): unexpected status 500 (500 Internal Server Error) with response: {"Message":"An error has occurred."}`

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_maintenance_assignment_dynamic_scope` - support for assigning dynamic scopes for maintenance configurations

This is a (please select all that apply):

- [ ] Bug Fix
- [X] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #24411

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-04-03 10:36 UTC, phil-bevan commented
Hi Rhys, not sure if this helps but I can also reproduce the issue in the portal if I create a dynamic scope on a Subscription.  However, if I apply a further filter and filter by resource group the dynamic scope creates successfully.  Dynamic scopes created at the same time as the maintenance configuration also create without error  I don't know why this makes a difference but hopefully gives you a clue!

2024-04-03 11:53 UTC, phil-bevan commented
From further testing via Powershell it appears to you *must* apply a filter of some kind.  Anything seems to be acceptable. 
```
C:\Users\BevanP> New-AzConfigurationAssignment -ConfigurationAssignmentName "mydynamicscope4" -MaintenanceConfigurationId $config.Id
New-AzConfigurationAssignment : Operation returned an invalid status code 'InternalServerError'
```

```
C:\Users\BevanP> New-AzConfigurationAssignment -ConfigurationAssignmentName "mydynamicscope4" -MaintenanceConfigurationId $config.Id -FilterOsType Linux,Windows


Location                   : global
MaintenanceConfigurationId : /subscriptions/xxx/resourcegroups/rg-testing/provide
rs/microsoft.maintenance/maintenanceconfigurations/config-philtest1
ResourceId                 : /subscriptions/xxx
Id                         : /subscriptions/xxx/providers/microsoft.maintenance/config
urationassignments/mydynamicscope4
Name                       : mydynamicscope4
Type                       : microsoft.maintenance/configurationassignments
FilterOsType[0]            : Linux
FilterOsType[1]            : Windows
```
```
C:\Users\BevanP> New-AzConfigurationAssignment -ConfigurationAssignmentName "mydynamicscope4" -MaintenanceConfigurationId $config.Id -FilterLocation uksouth


Location                   : global
MaintenanceConfigurationId : /subscriptions/75d8ba83-d619-4754-84b0-54fdac14a56a/resourcegroups/rg-mibi-testing/provide
rs/microsoft.maintenance/maintenanceconfigurations/config-philtest1
ResourceId                 : /subscriptions/812bf703-ad72-4249-9800-fbfed44e6363
Id                         : /subscriptions/812bf703-ad72-4249-9800-fbfed44e6363/providers/microsoft.maintenance/config
urationassignments/mydynamicscope4
Name                       : mydynamicscope4
Type                       : microsoft.maintenance/configurationassignments
FilterLocation[0]          : uksouth
```

2024-04-03 13:03 UTC, ASHR4 commented
> Hi Rhys, not sure if this helps but I can also reproduce the issue in the portal if I create a dynamic scope on a Subscription. However, if I apply a further filter and filter by resource group the dynamic scope creates successfully. Dynamic scopes created at the same time as the maintenance configuration also create without error I don't know why this makes a difference but hopefully gives you a clue!

Hi @phil-bevan, thank you for your input! I built a dynamic scope in the Portal and AzApi by amending the filters as you mentioned.

The other error I'm seeing occurs when Terraform verifies whether there is an existing resource in Azure; [code link]([method](https://github.com/ASHR4/terraform-provider-azurerm/blob/feature/dynamic-maintenance-assignment/internal/services/maintenance/maintenance_assignment_dynamic_scope_resource.go#L168-L173))

This is before the Azure Go SDK even calls the method which tells ARM to build the configuration assignment resource.

2024-04-04 08:06 UTC, phil-bevan commented
Hi @ASHR4 , Not a Go expert, but doesn't NewScopedConfigurationAssignmentID expect a ConfigurationAssignmentName rather than a MaintenanceConfigurationName?

2024-04-04 08:15 UTC, ASHR4 commented
> Hi @ASHR4 , Not a Go expert, but doesn't NewScopedConfigurationAssignmentID expect a ConfigurationAssignmentName rather than a MaintenanceConfigurationName?

Hi @phil-bevan, the other configuration assignments do something similar thing, however I have a stashed commit which takes a name argument as each dynamic scope configuration assignment requires a unique resource ID. 

This still didn't resolve my issue. The NewScopeConfigurationAssignmentID is creating a struct which can be used to build the resource ID and check if a configuration assignment already exists.

2024-04-13 12:40 UTC, ASHR4 commented
> @ASHR4 I think I understand why it's not working. The current code will generate a resource ID similar to **_/subscriptions/XXX/resourcegroups/rg-maint-philtest/providers/microsoft.maintenance/maintenanceconfigurations/example-mc/providers/microsoft.maintenance/configurationassignments/example1_**
> 
> which I guess works fine for the other config assignment types, but dynamic scopes are assigned at the subscription level so you need to access them with a resource ID such as **_/subscriptions/XXX/providers/microsoft.maintenance/configurationassignments/example1_**
> 
> I think you need to find a different method to build that resource ID. I have a working sample in C# if that helps you at all:
> 
> ```
> using Azure;
> using Azure.Core;
> using Azure.Identity;
> using Azure.ResourceManager;
> using Azure.ResourceManager.Maintenance;
> using Azure.ResourceManager.Maintenance.Models;
> using Azure.ResourceManager.Resources;
> 
> 
> var cred = new InteractiveBrowserCredential();
> 
> string subId = "XXX";
> string resGroupName = "rg-maint-philtest";
> string maintConfigName = "example-mc";
> string dynamicScopeName = "example3";
> ArmClient client = new ArmClient(cred, subId);
> 
> SubscriptionResource sub = client.GetDefaultSubscription();
> MaintenanceConfigurationResource mc = sub.GetResourceGroup(resGroupName).Value.GetMaintenanceConfiguration(maintConfigName);
> 
> MaintenanceConfigurationAssignmentFilter mcaf = new MaintenanceConfigurationAssignmentFilter();
> mcaf.Locations.Add(AzureLocation.UKSouth);
> 
> MaintenanceConfigurationAssignmentData mcad = new MaintenanceConfigurationAssignmentData()
> {
>     MaintenanceConfigurationId = mc.Id,
>     Filter = mcaf
> 
> };
> 
> // Create dynamic scope.  Comment out this line if you just want to check if one exists.
> sub.CreateOrUpdateConfigurationAssignmentBySubscription(dynamicScopeName, mcad);
> 
> try
> {
>     //Check if scope exists
>     var yy = sub.GetConfigurationAssignmentBySubscription(dynamicScopeName);
> }
> catch (Exception ex)
> {
>     switch (ex)
>     {
>         case RequestFailedException: //If dynamic scope doesn't exist we get a 404 response
>             Console.WriteLine(ex.ToString());
>             break;
> 
>     }
> }
> ```
> 
> I ran Fiddler in the background to identify the resource IDs in use

Hi @phil-bevan,

You were spot on, the `ForSubscription` methods worked. It seems when I had tries those before my validation and input was wrong causing it not to work, hence why I discounted it.

I'll try and work on finishing this over the weekend :)

Appreciate the help!

2024-04-13 20:39 UTC, ASHR4 commented
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/72310905/35b101ec-2e7d-4667-a6b0-25c7c0fd1bef)

2024-04-22 10:51 UTC, ASHR4 commented
@katbyte unsure if this being in draft, for a while, has effected this being reviewed. But the associated issues have over 20+ votes and so I was hoping if this could be reviewed?

Let me know if this is already on your radar :)

2024-04-22 13:35 UTC, jackofallops requested changes
Hi @ASHR4 - Thanks for this PR. There's some design and schema changes noted below, sorry if it looks like a lot, I've tried to cover everything in one pass rather than go in cycles, but if you can take a look at and address the changes, I think we'll be in good shape!

Thanks!

2024-04-22 13:35 UTC, jackofallops commented on internal/services/maintenance/maintenance_assignment_dynamic_scope_resource.go
> +					},
Can we add validation here, I believe the only valid values are `Linux` and `Windows`.

2024-04-22 13:35 UTC, jackofallops commented on internal/services/maintenance/maintenance_assignment_dynamic_scope_resource.go
> +					},
Again here, afaik the only valid values are `Microsoft.Compute/virtualMachines` and `Microsoft.HybridCompute/machines`, so we should add validation for that.

2024-04-22 13:35 UTC, jackofallops commented on internal/services/maintenance/maintenance_assignment_dynamic_scope_resource.go
> +										ValidateFunc: validation.StringIsNotEmpty,
This can be empty as the service uses it to mean that the given tag is unset, so we should remove this validation here.
```suggestion
```

2024-04-23 16:37 UTC, ASHR4 commented on internal/services/maintenance/maintenance_assignment_dynamic_scope_resource.go
> +					existing.Properties.Filter = &configurationassignments.ConfigurationAssignmentFilterProperties{}
Hi @jackofallops, I'm just a little confused by this one. Are you talking specifically nil checking `filterProperties`?

2024-04-23 19:22 UTC, ASHR4 commented on internal/services/maintenance/maintenance_assignment_dynamic_scope_resource_test.go
> +}
Hi @jackofallops, I've tried this and I receive ` Error: Duplicate provider configuration`, all other tests within the maintenance service have the provider in the template too.

2024-04-23 19:55 UTC, ASHR4 commented
> Hi @ASHR4 - Thanks for this PR. There's some design and schema changes noted below, sorry if it looks like a lot, I've tried to cover everything in one pass rather than go in cycles, but if you can take a look at and address the changes, I think we'll be in good shape!
> 
> Thanks!

Hi @jackofallops, appreciate your time on this. I just need a clarification on one of your requested changes and I can get that amended ASAP.

I hope the rest is looking in better shape :)

2024-04-24 14:01 UTC, leewilson86 commented
👋🏻 Bump on this one!

I have a need for this resource. Would be really handy if someone could pull this forward. It seems the author is waiting on a reviewer to get back to him. @jackofallops is this something you can assist with?

Thanks

2024-05-01 17:45 UTC, ASHR4 commented
Hi @jackofallops,

I requested a re-review last week, is there any chance you have any capacity for this, this week?

Thanks

2024-05-06 20:53 UTC, merged