Fix Management Group ID validation when used for System Topics
hashicorp/terraform-provider-azurerm pull request #25555
Opened 2024-04-10 04:14 UTC by BrendanThompson

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

Currently when trying to create a System Topic on a Management Group using the described and validated Management Group ID as per below an error is received:
```
resource "azurerm_eventgrid_system_topic" "this" {
  name                   = "policy-insights"
  resource_group_name    = "resource-group"
  location               = "Global"
  source_arm_resource_id = "/providers/Microsoft.Management/managementGroups/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  topic_type             = "Microsoft.PolicyInsights.PolicyStates"
}
```

This yields the following error:
```
╷
│ Error: creating/updating System Topic (Subscription: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
│ Resource Group Name: "resource-group"
│ System Topic Name: "policy-insights"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: InvalidRequest: ResourceID is not in the expected format: /providers/Microsoft.Management/managementGroups/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (Parameter 'GetSourceScope')
│ 
│   with azurerm_eventgrid_system_topic.this,
│   on main.tf line 14, in resource "azurerm_eventgrid_system_topic" "this":
│   14: resource "azurerm_eventgrid_system_topic" "this" {
│ 
╵
```

This error looks to be coming from the Azure API, which means the current `validate.ManagementGroupID` function from the `github.com/hashicorp/terraform-provider-azurerm/internal/services/managementgroup/validate` package is only checking for valid format on the above and not what is expected by the API.

As shown in the following documentation the resource ID format changes specifically for Management Group IDs when creating a System Topic. 

https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/governance/policy/tutorials/route-state-change-events.md#create-an-event-grid-system-topic

The resolution to this is to create a validator and parser for Management Group IDs based on that format.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_eventgrid_system_topic` - support for using a correctly formatted Management Group ID as the `source_arm_resource_id`

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #24548

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-04-15 06:08 UTC, BrendanThompson commented
@katbyte – is there anything further you would like to see on this PR to help progress it?

2024-04-17 21:16 UTC, mbfrahry requested changes
Hey @BrendanThompson, this change looks good and I was able to get it working locally with a `/tenants/` id. We should add a test though to make sure that we get this coverage in our acceptance test suite. And I'm wondering if we should add a `/tenants/` id to the `azurerm_management_group` resource so people don't have to build that id out themselves. 

What're your thoughts there?

2024-04-17 23:08 UTC, BrendanThompson commented
@mbfrahry — thanks for reviewing, appreciate it! I actually love your idea with having the ID in the data source, would we want it in both the data source and the resource? I think so personally.

When it comes to testing, roger that let me look into it and get back to you ASAP.

2024-04-18 01:51 UTC, BrendanThompson commented
@mbfrahry — added in the tests and everything else. Hopefully they should pass this time.

2024-04-18 03:36 UTC, BrendanThompson commented
I was thinking perhaps `tenant_management_group_id` might be a better attribute name, what are your thoughts?

2024-04-18 07:23 UTC, tombuildsstuff requested changes
Left a few comments inline but otherwise 👍

2024-04-18 07:23 UTC, tombuildsstuff commented on internal/services/managementgroup/management_group_data_source.go
> +			},
(as elsewhere) could we call this `tenant_scoped_id`? I'm omitting `management_group` in the field name here since it's in the resource type

2024-04-18 07:23 UTC, tombuildsstuff commented on internal/services/managementgroup/management_group_resource.go
> +			},
could we call this `tenant_scoped_id`? I'm omitting `management_group` in the field name here since it's in the resource type

2024-04-18 07:44 UTC, BrendanThompson commented on internal/services/eventgrid/eventgrid_system_topic_resource.go
> +					mgmtGroupValidate.ManagementGroupIDForSystemTopic,
Couldn't agree more with this, I struggled with what to call it and hated the fact it referenced a particular scenario rather than what it _is_.

2024-04-18 07:44 UTC, BrendanThompson commented on internal/services/managementgroup/parse/management_group.go
> +	regex := regexp.MustCompile(`^/tenants/.*-.*-.*-.*-.*/providers/[Mm]icrosoft\.[Mm]anagement/[Mm]anagement[Gg]roups/`)
Roger that, have made the changes

2024-04-18 15:54 UTC, katbyte approved these changes
Thanks @BrendanThompson - LGTM 🚜

2024-04-18 15:56 UTC, merged

2024-04-18 22:56 UTC, BrendanThompson commented
Thanks so much @mbfrahry , @tombuildsstuff , & @katbyte !