`azurerm_virtual_desktop_host_pool` - support for `public_network_access_enabled`
hashicorp/terraform-provider-azurerm pull request #25611
Opened 2024-04-14 12:36 UTC by ASHR4

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [X] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/72310905/cb026344-c348-419d-8411-54dc395ad74a)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_virtual_desktop_host_pool` - support for the `public_network_access_enabled` property 

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [X] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #22429

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-04-15 08:21 UTC, stephybun requested changes
Thanks for this PR @ASHR4. Would you mind taking a look over the suggestion left-line. In addition could you also confirm that the default value returned by the API if the field isn't specified at all is indeed `Enabled`? Once that's done we can continue with the review.

2024-04-15 08:21 UTC, stephybun commented on internal/services/desktopvirtualization/virtual_desktop_host_pool_resource.go
> +			},
There appear to be more values supported here than just enabled/disabled.

Although convention in the provider so far has been to expose this as a boolean, due to the rollout of additional network security features we need to begin exposing this as a string property.

Can we please change this to 
```suggestion
			"public_network_access": {
				Type:         pluginsdk.TypeString,
				Optional:     true,
				Default:      hostpool.HostpoolPublicNetworkAccessEnabled,
				ValidateFunc: validation.StringInSlice(hostpool.PossibleValuesForHostpoolPublicNetworkAccess(), false),
			},
```

2024-04-20 10:45 UTC, ASHR4 commented
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/72310905/acf5d1a2-aae8-4c7d-bd50-d9a149d0f0bb)

2024-04-20 11:00 UTC, ASHR4 commented
> Thanks for this PR @ASHR4. Would you mind taking a look over the suggestion left-line. In addition could you also confirm that the default value returned by the API if the field isn't specified at all is indeed `Enabled`? Once that's done we can continue with the review.

Hi @stephybun, if the field is not supplied it is indeed Enabled :)

2024-04-20 12:15 UTC, ASHR4 commented
Updated acceptance tests

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/72310905/1d19eae7-7fef-4b74-a04e-b3fa9e070bb1)

2024-04-22 05:47 UTC, stephybun approved these changes
Thanks @ASHR4 LGTM 🦀

2024-04-22 05:47 UTC, merged