new data source `azurerm_network_manager_connectivity_configuration`
hashicorp/terraform-provider-azurerm pull request #25746
Opened 2024-04-25 06:54 UTC by teowa

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

new data source `azurerm_network_manager_connectivity_configuration`

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```hcl
=== RUN   TestAccNetworkManagerConnectivityConfigurationDataSource_basic
--- PASS: TestAccNetworkManagerConnectivityConfigurationDataSource_basic (204.44s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/network       204.459s
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* new data source `azurerm_network_manager_connectivity_configuration`

This is a (please select all that apply):

- [ ] Bug Fix
- [x] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #25587

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-04-25 13:23 UTC, jackofallops requested changes
Thanks @teowa - Just a couple things to take a look at below if you could.

Thanks!

2024-04-25 13:23 UTC, jackofallops commented on website/docs/d/network_manager_connectivity_configuration.html.markdown
> +* `applies_to_group` - A `applies_to_group` block as defined below.
```suggestion
* `applies_to_group` - An `applies_to_group` block as defined below.
```

2024-04-25 13:23 UTC, jackofallops commented on website/docs/d/network_manager_connectivity_configuration.html.markdown
> +A `applies_to_group` block exports the following:
```suggestion
An `applies_to_group` block exports the following:
```

2024-05-06 20:39 UTC, katbyte approved these changes
LGTM 🍵

2024-05-06 20:39 UTC, merged