new resource: `azurerm_data_factory_credential_service_principal`
hashicorp/terraform-provider-azurerm pull request #25805
Opened 2024-04-30 02:25 UTC by ms-henglu

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-04-30 03:08 UTC, magodo requested changes
Thanks for this PR!
I've taken a look through and left some comments inline, but this is mostly looking good to me 👍

2024-04-30 03:08 UTC, magodo commented on internal/services/datafactory/data_factory_credential_service_principal_resource.go
> +				return tf.ImportAsExistsError("azurerm_data_factory_dataset_http", id.ID())
Wrong RT?

2024-04-30 03:08 UTC, magodo commented on internal/services/datafactory/data_factory_credential_service_principal_resource.go
> +				return fmt.Errorf("retrieving %s: expected `credentials.ServicePrincipalCredential` but got %+v", id, existing.Model.Properties)
```suggestion
				return fmt.Errorf("retrieving %s: expected `credentials.ServicePrincipalCredential` but got %+T", id, existing.Model.Properties)
```

2024-04-30 03:22 UTC, ms-henglu commented on internal/services/datafactory/data_factory_credential_service_principal_resource.go
> +					"linked_service_name": {
Yes,

2024-04-30 05:56 UTC, magodo commented on internal/services/datafactory/data_factory_credential_service_principal_resource.go
> +					"linked_service_name": {
Then I feel a single key vault secret id suffices here?

2024-04-30 06:04 UTC, ms-henglu commented on internal/services/datafactory/data_factory_credential_service_principal_resource.go
> +					"linked_service_name": {
No, the linked service name here is the name of a data factory linked service which connects to the key vault.. So the name could be different from the key vault name.

2024-04-30 06:57 UTC, magodo commented
LGTM now!

2024-04-30 06:59 UTC, ms-henglu commented
Thanks @magodo

2024-05-06 18:31 UTC, katbyte requested changes
Test failure:
```
------- Stdout: -------
=== RUN   TestAccDataFactoryCredentialServicePrincipal_requiresImport
=== PAUSE TestAccDataFactoryCredentialServicePrincipal_requiresImport
=== CONT  TestAccDataFactoryCredentialServicePrincipal_requiresImport
    testcase.go:113: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Key Vault (Subscription: "*******"
        Resource Group Name: "acctestRG-df-240506171043463502"
        Key Vault Name: "acctestkv24050602"): performing CreateOrUpdate: vaults.VaultsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="VaultAlreadyExists" Message="The vault name 'acctestkv24050602' is already in use. Vault names are globally unique so it is possible that the name is already taken. If you are sure that the vault name was not taken then it is possible that a vault with the same name was recently deleted but not purged after being placed in a recoverable state. If the vault is in a recoverable state then the vault will need to be purged before reusing the name. For more information about VaultAlreadyExists, soft delete and purging a vault follow this link https://go.microsoft.com/fwlink/?linkid=2147740."
        
          with azurerm_key_vault.test,
          on terraform_plugin_test.tf line 44, in resource "azurerm_key_vault" "test":
          44: resource "azurerm_key_vault" "test" {
        
--- FAIL: TestAccDataFactoryCredentialServicePrincipal_requiresImport (66.25s)
FAIL
```

2024-05-07 02:37 UTC, ms-henglu commented
Thanks @katbyte , I've updated the tests, now all passing

<img width="1177" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/79895375/96bb60bd-a047-40c5-87c4-90edceecdb13">

2024-05-07 13:22 UTC, katbyte approved these changes
LGTM 🌈

2024-05-07 13:22 UTC, merged