`azurerm_container_app_environment` - Support for Mutual TLS added
hashicorp/terraform-provider-azurerm pull request #25993
Opened 2024-05-16 13:07 UTC by jhisc

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

Adding support for Mutual TLS within Azure Container App Environments.
This is a *non* breaking change and backwards compatable.

Changes can be made to existing resources without requiring a re-creation.
Defaults to `false` which results in a no-changes to existing infrastructure.

Provider tested to validate:

- New Resources created with MTLS enabled and disabled
- Updating existing resource to Enable/Disable MTLS
- State Refresh where changes made outside of Terraform

Feature enhancement - Not a major chance, optional input
PR looks worse than it is, vast majority of changed files are the new SDK version being pulled into the Vendor folder.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [x] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

> I have been unable to execute the tests locally, however conducted manual testing with the new provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_container_app_environment` - support for the MTLS property [GH-25993]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Resolves https://github.com/hashicorp/terraform-provider-azurerm/issues/21960

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-05-16 19:35 UTC, katbyte requested changes
Thanks @jhisc 0- overall looks good i just have 1 minor comment i've left inline. Once that is addressed i think this is good to merge provided tests pass

2024-05-16 19:35 UTC, katbyte commented on internal/services/containerapps/container_app_environment_resource_test.go
> +  mutual_tls_enabled             = false
we don't need to add this as false as the default is falsE?

2024-05-16 19:35 UTC, katbyte commented on internal/services/containerapps/container_app_environment_resource_test.go
> +  mutual_tls_enabled             = false
same for the rest?

2024-05-27 12:15 UTC, stephybun requested changes
Thanks for this PR @jhisc! I have two comments/questions on this PR. Would you mind taking a look? Once they're resolved this should be good to go

2024-05-29 07:16 UTC, stephybun approved these changes
Tests look good, thanks @jhisc LGTM 💯

2024-05-29 07:17 UTC, merged