`azurerm_private_endpoint` - Remove internal lock on subnet while processing private endpoint
hashicorp/terraform-provider-azurerm pull request #26006
Opened 2024-05-17 05:38 UTC by lonegunmanb

Remove internal lock on subnet while processing private endpoint since the [API issue](https://github.com/Azure/azure-rest-api-specs/issues/20289) no longer exist under API version 2023-09-01

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

A new acc test `TestAccPrivateEndpoint_multipleInstancesWithLinkAlias` has been added to verify creating multiple private endpoint with private link alias is good.

=== RUN   TestAccPrivateEndpoint_basic
=== PAUSE TestAccPrivateEndpoint_basic
=== CONT  TestAccPrivateEndpoint_basic
--- PASS: TestAccPrivateEndpoint_basic (376.22s)
=== RUN   TestAccPrivateEndpoint_updateTag
=== PAUSE TestAccPrivateEndpoint_updateTag
=== CONT  TestAccPrivateEndpoint_updateTag
--- PASS: TestAccPrivateEndpoint_updateTag (519.56s)
=== RUN   TestAccPrivateEndpoint_updateNicName
=== PAUSE TestAccPrivateEndpoint_updateNicName
=== CONT  TestAccPrivateEndpoint_updateNicName
--- PASS: TestAccPrivateEndpoint_updateNicName (589.14s)
=== RUN   TestAccPrivateEndpoint_requestMessage
=== PAUSE TestAccPrivateEndpoint_requestMessage
=== CONT  TestAccPrivateEndpoint_requestMessage
--- PASS: TestAccPrivateEndpoint_requestMessage (426.08s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneGroup
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneGroup
=== CONT  TestAccPrivateEndpoint_privateDnsZoneGroup
--- PASS: TestAccPrivateEndpoint_privateDnsZoneGroup (466.67s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRename
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRename
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRename
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRename (559.39s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneUpdate
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneUpdate
=== CONT  TestAccPrivateEndpoint_privateDnsZoneUpdate
--- PASS: TestAccPrivateEndpoint_privateDnsZoneUpdate (611.53s)
=== RUN   TestAccPrivateEndpoint_statiIpAddress
=== PAUSE TestAccPrivateEndpoint_statiIpAddress
=== CONT  TestAccPrivateEndpoint_statiIpAddress
--- PASS: TestAccPrivateEndpoint_statiIpAddress (345.48s)
=== RUN   TestAccPrivateEndpoint_privateDnsZoneRemove
=== PAUSE TestAccPrivateEndpoint_privateDnsZoneRemove
=== CONT  TestAccPrivateEndpoint_privateDnsZoneRemove
--- PASS: TestAccPrivateEndpoint_privateDnsZoneRemove (594.01s)
=== RUN   TestAccPrivateEndpoint_privateConnectionAlias
=== PAUSE TestAccPrivateEndpoint_privateConnectionAlias
=== CONT  TestAccPrivateEndpoint_privateConnectionAlias
--- PASS: TestAccPrivateEndpoint_privateConnectionAlias (325.23s)
=== RUN   TestAccPrivateEndpoint_updateToPrivateConnectionAlias
=== PAUSE TestAccPrivateEndpoint_updateToPrivateConnectionAlias
=== CONT  TestAccPrivateEndpoint_updateToPrivateConnectionAlias
--- PASS: TestAccPrivateEndpoint_updateToPrivateConnectionAlias (445.43s)
=== RUN   TestAccPrivateEndpoint_multipleInstances
=== PAUSE TestAccPrivateEndpoint_multipleInstances
=== CONT  TestAccPrivateEndpoint_multipleInstances
--- PASS: TestAccPrivateEndpoint_multipleInstances (322.07s)
=== RUN   TestAccPrivateEndpoint_multipleIpConfigurations
=== PAUSE TestAccPrivateEndpoint_multipleIpConfigurations
=== CONT  TestAccPrivateEndpoint_multipleIpConfigurations
--- PASS: TestAccPrivateEndpoint_multipleIpConfigurations (455.78s)
=== RUN   TestAccPrivateEndpoint_multipleInstancesWithLinkAlias
=== PAUSE TestAccPrivateEndpoint_multipleInstancesWithLinkAlias
=== CONT  TestAccPrivateEndpoint_multipleInstancesWithLinkAlias
--- PASS: TestAccPrivateEndpoint_multipleInstancesWithLinkAlias (364.07s)
PASS

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-06-06 07:43 UTC, jackofallops requested changes
Hi @lonegunmanb - looks to be a compilation error in the merge branch for this PR relating to `subnetId` being unused. Can you rebase and check so I can run the tests on CI?

Thanks!

2024-06-07 06:49 UTC, lonegunmanb commented
Hello @jackofallops I've rebased the branch with latest main branch then fixed the compilation error, would you please take another look? Thanks!

2024-06-13 07:43 UTC, jackofallops approved these changes
Thanks @lonegunmanb - This LGTM now 👍

2024-06-13 07:43 UTC, jackofallops commented
Tests look good

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/11830746/28aaa9a9-c19a-417e-9d45-be3ba488e9a0)

2024-06-13 07:44 UTC, merged