New Resource: `azurerm_dev_center_dev_box_definition`
hashicorp/terraform-provider-azurerm pull request #26307
Opened 2024-06-12 09:02 UTC by neil-yechenwei

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description
This PR is to support new resource `azurerm_dev_center_dev_box_definition`.

API Reference: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/devcenter/resource-manager/Microsoft.DevCenter/stable/2023-04-01/devcenter.json

Overview: https://learn.microsoft.com/en-gb/azure/dev-box/overview-what-is-microsoft-dev-box

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* New Resource: `azurerm_dev_center_dev_box_definition`

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-06-19 06:25 UTC, ms-zhenhua requested changes
Hi @neil-yechenwei ,

Thanks for this PR - I've taken a look through and left some comments inline. If we can fix those up, this should be good to go 👍

2024-06-19 06:32 UTC, neil-yechenwei commented on internal/services/devcenter/dev_center_dev_box_definition_resource.go
> +					"name": {
I already tested it. I can confirm it can be in-place updated.

2024-06-19 06:33 UTC, neil-yechenwei commented on internal/services/devcenter/dev_center_dev_box_definition_resource.go
> +					"tier": {
API returns nil when it isn't set.

2024-06-19 06:37 UTC, neil-yechenwei commented on internal/services/devcenter/dev_center_dev_box_definition_resource.go
> +				state.Name = id.DevBoxDefinitionName
Updated

2024-06-19 06:43 UTC, neil-yechenwei commented on internal/services/devcenter/dev_center_dev_box_definition_resource.go
> +			parameters := devboxdefinitions.DevBoxDefinitionUpdate{
Updated

2024-06-19 06:43 UTC, neil-yechenwei commented
@ms-zhenhua , thanks for the comments. I updated PR. Please take another look.

2024-06-19 07:45 UTC, neil-yechenwei commented on internal/services/devcenter/dev_center_dev_box_definition_resource.go
> +					"tier": {
Maybe allowing nil is used to be compatible with old version.

2024-06-19 07:46 UTC, neil-yechenwei commented
@ms-zhenhua , thanks for the comments. I updated PR. Please take another look.

2024-06-24 01:12 UTC, ms-zhenhua commented on internal/services/devcenter/dev_center_dev_box_definition_resource.go
> +					"tier": {
@neil-yechenwei, could you double confirm with the service team what type of tier is used when `nil` is set? If it's one of `PossibleValuesForSkuTier`, that value should be set as a `default` value?

2024-06-24 01:25 UTC, neil-yechenwei commented on internal/services/devcenter/dev_center_dev_box_definition_resource.go
> +					"tier": {
@ms-zhenhua , service team confirmed only sku.name is supported. So I removed tier.

2024-06-24 01:25 UTC, neil-yechenwei commented
@ms-zhenhua , thanks for the comments. I updated PR. Please take another look.

2024-06-24 02:09 UTC, neil-yechenwei commented
@ms-zhenhua , below is the test result I just now triggered.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/19754191/089d4628-5210-4abb-8b9a-6319cb03ff3b)

2024-06-24 07:15 UTC, ms-zhenhua approved these changes

2024-06-24 07:16 UTC, ms-zhenhua commented
@neil-yechenwei, thank you for your updates. LGTM~

2024-07-08 10:20 UTC, stephybun requested changes

2024-07-08 10:20 UTC, stephybun commented on internal/services/devcenter/dev_center_dev_box_definition_resource_test.go
> +		return nil, fmt.Errorf("reading %s: %+v", *id, err)
```suggestion
		return nil, fmt.Errorf("retrieving %s: %+v", *id, err)
```

2024-07-08 10:20 UTC, stephybun commented on internal/services/devcenter/dev_center_dev_box_definition_resource_test.go
> +	return utils.Bool(resp.Model != nil), nil
```suggestion
	return pointer.To(resp.Model != nil), nil
```

2024-07-08 10:20 UTC, stephybun commented on website/docs/r/dev_center_dev_box_definition.html.markdown
> +* `image_reference_id` - (Required) The ID of the image for Dev Center Dev Box Definition.
```suggestion
* `image_reference_id` - (Required) The ID of the image for the Dev Center Dev Box Definition.
```

2024-07-08 10:20 UTC, stephybun commented on website/docs/r/dev_center_dev_box_definition.html.markdown
> +* `sku_name` - (Required) The name of the SKU for Dev Center Dev Box Definition.
```suggestion
* `sku_name` - (Required) The name of the SKU for the Dev Center Dev Box Definition.
```

2024-07-08 10:20 UTC, stephybun commented on website/docs/r/dev_center_dev_box_definition.html.markdown
> +terraform import azurerm_dev_center_dev_box_definition.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.DevCenter/devcenters/dc1/devboxdefinitions
Casing here? 
```suggestion
terraform import azurerm_dev_center_dev_box_definition.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.DevCenter/devCenters/dc1/devBoxDefinitions/et1
```

2024-07-09 01:57 UTC, neil-yechenwei commented on website/docs/r/dev_center_dev_box_definition.html.markdown
> +terraform import azurerm_dev_center_dev_box_definition.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.DevCenter/devcenters/dc1/devboxdefinitions
Updated

2024-07-09 01:57 UTC, neil-yechenwei commented on website/docs/r/dev_center_dev_box_definition.html.markdown
> +* `sku_name` - (Required) The name of the SKU for Dev Center Dev Box Definition.
Updated

2024-07-09 01:58 UTC, neil-yechenwei commented on website/docs/r/dev_center_dev_box_definition.html.markdown
> +* `image_reference_id` - (Required) The ID of the image for Dev Center Dev Box Definition.
Updated

2024-07-09 01:58 UTC, neil-yechenwei commented on internal/services/devcenter/dev_center_dev_box_definition_resource_test.go
> +	return utils.Bool(resp.Model != nil), nil
Updated

2024-07-09 01:58 UTC, neil-yechenwei commented on internal/services/devcenter/dev_center_dev_box_definition_resource_test.go
> +		return nil, fmt.Errorf("reading %s: %+v", *id, err)
Updated

2024-07-09 02:48 UTC, neil-yechenwei commented
@stephybun , thanks for the comments. I updated PR. Below is the test result I just now triggered.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/19754191/85518284-124b-438e-b428-8a6f00d3c548)

2024-07-09 07:51 UTC, stephybun approved these changes
Thanks @neil-yechenwei LGTM 👍

2024-07-09 07:51 UTC, merged