New Resource: `azurerm_arc_machine`
hashicorp/terraform-provider-azurerm pull request #26647
Opened 2024-07-16 06:30 UTC by neil-yechenwei

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description
This is the PR to support Hybrid Compute Machine. As HC suggests to use arc_* for this PR, so I named it to azurerm_arc_machine.

API Spec for Hybrid Compute Machine Resource: https://github.com/Azure/azure-rest-api-specs/blob/1aa912658531534e4e57ea613591075f7b97897c/specification/hybridcompute/resource-manager/Microsoft.HybridCompute/preview/2024-05-20-preview/HybridCompute.json#L352

Overview doc link: https://learn.microsoft.com/en-us/azure/azure-arc/system-center-virtual-machine-manager/overview

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* New Resource: `azurerm_arc_machine`

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-07-25 08:42 UTC, ms-zhenhua requested changes
@neil-yechenwei, Thanks for this PR - I've taken a look through and left some comments inline. If we can fix those up, this should be good to go 👍

2024-07-25 08:42 UTC, ms-zhenhua commented on internal/services/hybridcompute/arc_machine_resource.go
> +			}
```suggestion
                        state.Name = id.MachineName
		        state.ResourceGroupName = id.ResourceGroupName
			if model := resp.Model; model != nil {
				state.Location = location.Normalize(model.Location)
				state.Kind = string(pointer.From(model.Kind))
			}
```

2024-07-25 08:42 UTC, ms-zhenhua commented on internal/services/hybridcompute/arc_machine_resource_test.go
> +		return nil, fmt.Errorf("reading %s: %+v", *id, err)
```suggestion
		return nil, fmt.Errorf("retrieving %s: %+v", *id, err)
```

2024-07-25 08:42 UTC, ms-zhenhua commented on internal/services/hybridcompute/arc_machine_resource_test.go
> +	return utils.Bool(resp.Model != nil), nil
```suggestion
	return pointer.To(resp.Model != nil), nil
```

2024-07-26 03:41 UTC, neil-yechenwei commented on internal/services/hybridcompute/client/client.go
> +		return nil, err
Updated

2024-07-26 03:42 UTC, neil-yechenwei commented on internal/services/hybridcompute/arc_machine_resource.go
> +			ValidateFunc: validation.StringIsNotEmpty,
I didn't find any validation from azure portal and service API.

2024-07-26 03:43 UTC, neil-yechenwei commented on website/docs/r/arc_machine.html.markdown
> +* `kind` - (Required) The kind of the Arc Machine. Changing this forces a new resource to be created.
Updated

2024-07-26 04:53 UTC, neil-yechenwei commented on internal/services/hybridcompute/arc_machine_resource.go
> +			}
Updated

2024-07-26 04:53 UTC, neil-yechenwei commented on internal/services/hybridcompute/arc_machine_resource_test.go
> +		return nil, fmt.Errorf("reading %s: %+v", *id, err)
Updated

2024-07-26 04:54 UTC, neil-yechenwei commented on internal/services/hybridcompute/arc_machine_resource_test.go
> +	return utils.Bool(resp.Model != nil), nil
Updated

2024-07-26 04:55 UTC, neil-yechenwei commented
@ms-zhenhua , thanks for the comments. I updated PR. Please take another look.

2024-07-30 01:51 UTC, ms-zhenhua approved these changes

2024-07-30 01:51 UTC, ms-zhenhua commented
@neil-yechenwei, thank you for your updates. LGTM~

2024-09-13 00:41 UTC, katbyte approved these changes
LGTM 🛋️

2024-09-13 00:41 UTC, merged