`azurerm_log_analytics_saved_search` - update validation for `azurerm_log_analytics_saved_search`
hashicorp/terraform-provider-azurerm pull request #26701
Opened 2024-07-19 06:27 UTC by ziyeqf

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description
These validation regxp might be out of date, can not validate some format of parameters.  The expression was provided on https://github.com/hashicorp/terraform-provider-azurerm/issues/26685, Thanks to @Folling

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)
```
❯❯ tftest loganalytics TestAccLogAnalyticsSavedSearch
=== RUN   TestAccLogAnalyticsSavedSearch_basic
=== PAUSE TestAccLogAnalyticsSavedSearch_basic
=== RUN   TestAccLogAnalyticsSavedSearch_complete
=== PAUSE TestAccLogAnalyticsSavedSearch_complete
=== RUN   TestAccLogAnalyticsSavedSearch_withTag
=== PAUSE TestAccLogAnalyticsSavedSearch_withTag
=== RUN   TestAccLogAnalyticsSavedSearch_requiresImport
=== PAUSE TestAccLogAnalyticsSavedSearch_requiresImport
=== CONT  TestAccLogAnalyticsSavedSearch_basic
=== CONT  TestAccLogAnalyticsSavedSearch_withTag
=== CONT  TestAccLogAnalyticsSavedSearch_complete
=== CONT  TestAccLogAnalyticsSavedSearch_requiresImport
--- PASS: TestAccLogAnalyticsSavedSearch_withTag (191.96s)
--- PASS: TestAccLogAnalyticsSavedSearch_requiresImport (202.24s)
--- PASS: TestAccLogAnalyticsSavedSearch_complete (208.41s)
--- PASS: TestAccLogAnalyticsSavedSearch_basic (218.12s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/loganalytics  220.329s
```
```
❯❯ tftest loganalytics TestAccLogAnalyticsSavedSearch_functionParameter
=== RUN   TestAccLogAnalyticsSavedSearch_functionParameter
=== PAUSE TestAccLogAnalyticsSavedSearch_functionParameter
=== CONT  TestAccLogAnalyticsSavedSearch_functionParameter
--- PASS: TestAccLogAnalyticsSavedSearch_functionParameter (281.36s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/loganalytics  283.494s
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_log_analytics_saved_search` - pdate validation for `azurerm_log_analytics_saved_search` [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #26685

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-07-31 07:09 UTC, stephybun requested changes
Thanks @ziyeqf. Could you address the review comments left by @Folling. Once that's done and the tests pass this should be good to go.

2024-08-06 05:34 UTC, ziyeqf commented on internal/services/loganalytics/log_analytics_saved_search_resource_test.go
> +  category     = "Saved Search Test Category"
per the testing result it should be fine

2024-08-06 05:35 UTC, ziyeqf commented on internal/services/loganalytics/log_analytics_saved_search_resource_test.go
> +		{
multiple parameters are tested in the `TestAccLogAnalyticsSavedSearch_complete` test case

2024-08-06 05:36 UTC, ziyeqf commented
Sorry for the delay, just updated

2024-08-07 06:01 UTC, stephybun approved these changes
Thanks @ziyeqf LGTM 👍

2024-08-07 06:01 UTC, merged