`mssql_managed_instance` - upgrade to `2023-08-01-preview` and `hashicorp/go-azure-sdk`
hashicorp/terraform-provider-azurerm pull request #26872
Opened 2024-07-30 18:51 UTC by catriona-m

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)
Tests running in TC

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

`mssql_managed_instance` - upgrade to `2023-08-01-preview` and `hashicorp/go-azure-sdk` [GH-]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-08-07 12:43 UTC, jackofallops requested changes
Thanks @catriona-m - Just a few comments below (sorry if some are already outdated, I started the review before you pushed some changes)

2024-08-07 12:43 UTC, jackofallops commented on internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go
> +	return managedinstances.BackupStorageRedundancyGeo
Can we define local constants/enums for these? Seems a lot of overhead to import the `sql` package for them?

2024-08-09 04:42 UTC, jackofallops approved these changes
Thanks for the changes @catriona-m - LGTM 👍

2024-08-20 11:35 UTC, stephybun approved these changes
Thanks @catriona-m and @jackofallops LGTM 🌶️

2024-08-20 11:35 UTC, merged