New Resource `azurerm_function_app_on_container`
hashicorp/terraform-provider-azurerm pull request #27249
Opened 2024-08-30 08:31 UTC by xiaxyi

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Support the new resource - hosting azure function app in container app environment.

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-09-04 06:10 UTC, ms-zhenhua requested changes
Hi @xiaxyi ,

Thanks for this PR - I've taken a look through and left some comments inline. If we can fix those up, this should be good to go 👍

2024-09-04 06:10 UTC, ms-zhenhua commented on internal/services/appservice/linux_function_app_on_container_resource_test.go
> +    registry_username   = ""
could you also test `registry_username` and `registry_password` with values?

2024-09-04 06:10 UTC, ms-zhenhua commented on internal/services/appservice/linux_function_app_on_container_resource_test.go
> +func TestAccLinuxFunctionAppOnContainer_basicDocker(t *testing.T) {
seems `storage_key_vault_secret_id, site_config.application_insights_key, site_config.elastic_instance_minimum ,site_config.linux_fx_version, identity` are not test. Could you add these testcases?

2024-10-17 02:37 UTC, xiaxyi commented on internal/services/appservice/linux_function_app_on_container_resource.go
> +			siteConfig := helpers.ExpandSiteConfigLinuxFunctionAppOnContainer(linuxFunctionAppOnContainer.SiteConfig, nil, metadata, linuxFunctionAppOnContainer.Registries[0], linuxFunctionAppOnContainer.Func
This is the required field

2024-10-17 09:55 UTC, xiaxyi commented
Thanks @ms-zhenhua for the review, I updated the code per comment, also made the PR to "ready to review" status as the api issue was fixed.

2024-12-04 05:37 UTC, katbyte requested changes
test failure
```

------- Stdout: -------
=== RUN   TestAccLinuxFunctionAppOnContainer_basicMCRUpdate
=== PAUSE TestAccLinuxFunctionAppOnContainer_basicMCRUpdate
=== CONT  TestAccLinuxFunctionAppOnContainer_basicMCRUpdate
    testcase.go:173: Step 2/3 error: Pre-apply plan check(s) failed:
        'azurerm_linux_function_app_on_container.test' - expected action to not be Replace, path: [[name]] tried to update a value that is ForceNew
--- FAIL: TestAccLinuxFunctionAppOnContainer_basicMCRUpdate (1118.55s)
FAIL
```

2025-01-22 15:07 UTC, xiaxyi commented
checking with the service team about the api behavior, will update the pr once confirmed

2025-04-10 06:36 UTC, alefteris commented
@xiaxyi Hello. Has there been any update, so that this PR can move forward? Thanks.

2025-06-04 04:44 UTC, xiaxyi commented
The patch api is replacing the value now, the PR is ready for review

2025-06-11 14:10 UTC, DanielBertocci commented
I see that there are updates about this topic:

[Announcing Native Azure Functions Support in Azure Container Apps](https://techcommunity.microsoft.com/blog/appsonazureblog/announcing-native-azure-functions-support-in-azure-container-apps/4414039?utm_source=chatgpt.com)

> A new hosting method for running Azure Functions directly in Azure Container Apps is now available (see [announcement](https://techcommunity.microsoft.com/blog/appsonazureblog/announcing-native-azure-functions-support-in-azure-container-apps/4414039)) and recommended for most new workloads. This integration allows you to leverage the full features and capabilities of Azure Container Apps while benefiting from the functions programming model and simplicity of auto-scaling provided by Azure Functions.

Is still this the direction to go? With the _kind_ parameter, it could be just exposed on _azurerm_container_app_.

2025-06-12 06:38 UTC, dgensert commented
It might be more work required though, but i concur with @DanielBertocci.

2026-08-03 07:00 UTC, closed without merging