`hdinsights` - Add support for Accelerated Writes with HDInsight HBase Clusters
hashicorp/terraform-provider-azurerm pull request #27293
Opened 2024-09-05 10:04 UTC by MrAlex475

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Add support for Accelerated Writes with HDInsight HBase Clusters. This fixes #9142

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

I attempted to run the tests for services/hdinsight but encountered several policy violations deploying to my cloud environment. This is due to the opinionated corporate environment in use for my development

Sorry for the inconvenience

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_hdinsight_hadoop_cluster` - Support for Accelerated Writes with HDInsight HBase Clusters. Adding property `enable_accelerated_writes`

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #9142

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-09-05 23:25 UTC, mbfrahry requested changes
Hey @MrAlex475, thanks for this PR. I wrote a comment about refactoring the name.

We should also write this attribute back into state and add a test to make sure it works

2024-09-11 10:08 UTC, MrAlex475 commented on internal/services/hdinsight/hdinsight_hbase_cluster_resource.go
> +			"enable_accelerated_writes": {
Updated, I've also had a go at adding to State and some unit tests. 
I'm not confident I've got this right, sorry in advance

2024-09-11 10:33 UTC, MrAlex475 commented
@mbfrahry I've made the changes to refactor the name. 
I've also had a go at adding the value to state and unit tests to confirm
Apologies if it's not quite right

2024-09-20 03:41 UTC, katbyte requested changes
we have some test failures
<img width="1462" alt="image" src="https://github.com/user-attachments/assets/52c4e028-62f0-44e0-b5af-11cc922e44ad">

2025-01-28 13:46 UTC, stephybun commented
Since we haven't heard back I'm going to close this PR for the moment. Let us know whenever you're ready to pick this back up again and we can reopen this!

2025-01-28 13:46 UTC, closed without merging