New resource: `azurerm_key_vault_managed_hardware_security_module_key_rotation_policy`
hashicorp/terraform-provider-azurerm pull request #27306
Opened 2024-09-06 11:27 UTC by wuxu92

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Add key rotation policy support for Managed HSM Keys. Since this based on a Data plane API, I created a New resource for it instead of integrating into the Managed HSM Key resource. Based on my test, notification is not supported in MHSM Key. There is only one rotate policy for each key and there is no separation resource/id for it, so the new resource just resuse the managed hsm key id as its resource id.

https://learn.microsoft.com/en-us/azure/key-vault/managed-hsm/key-rotation

Given that creating a Managed HSM resource is a heavy operation, I created only one AccTest with both basic and update included. The creation/update of the rotation policy is fast.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```
--- PASS: TestAccMHSMKeyRotationPolicy_all (2749.04s)
PASS
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_key_vault_managed_hardware_security_module_key_rotation_policy` - New resource for Managed HSM Key rotation policy

This is a (please select all that apply):

- [ ] Bug Fix
- [x] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-09-13 02:56 UTC, katbyte requested changes

2024-09-13 02:56 UTC, katbyte commented on website/docs/r/key_vault_managed_hardware_security_module_key_rotation_policy.html.markdown
> +* `expire_after` - (Required) Specify the expiration time of the key.
is this a date? a duration? what format?
```suggestion
* `expire_after_date` - (Required) Specify the expiration time of the key.
```
```suggestion
* `expire_after_duration` - (Required) Specify the expiration time of the key.
```

2024-09-13 02:56 UTC, katbyte commented on website/docs/r/key_vault_managed_hardware_security_module_key_rotation_policy.html.markdown
> +
why is this sperator here?

2024-09-13 02:56 UTC, katbyte commented on website/docs/r/key_vault_managed_hardware_security_module_key_rotation_policy.html.markdown
> +* `expire_after` - (Required) Specify the expiration time of the key.
please detail what this actually means, is it related to the lifecycle actions/trigger not the key?

2024-09-13 02:56 UTC, katbyte commented on internal/services/managedhsm/key_vault_managed_hardware_security_module_key_rotation_policy_resource.go
> +			if err != nil {
these lines can be merged

2024-09-13 02:56 UTC, katbyte commented on internal/services/managedhsm/key_vault_managed_hardware_security_module_key_rotation_policy_resource.go
> +		Trigger: &keyvault.LifetimeActionsTrigger{},
are there other actions possible here? what about for trigger?

2024-09-13 02:56 UTC, katbyte commented on internal/services/managedhsm/key_vault_managed_hardware_security_module_key_rotation_policy_resource.go
> +		res.ExipreAfter = pointer.From(p.Attributes.ExpiryTime)
what does this expire? what happens ?

2024-09-13 02:56 UTC, katbyte commented on website/docs/r/key_vault_managed_hardware_security_module_key_rotation_policy.html.markdown
> +* `time_after_creation` - (Optional) Specify the rotation time after creation in the format of ISO86061. Exactly one of `time_after_creation` or `time_before_expiry` should be specified.
this is not clear, it should be explicit in what it is doing when
```suggestion
* `time_after_creation_to_rotate` - (Optional) Specify the rotation time after creation in the format of ISO86061. Exactly one of `time_after_creation` or `time_before_expiry` should be specified.
```

also is this ISO 8601 duration not ISO86061?

2024-09-13 02:56 UTC, katbyte commented on website/docs/r/key_vault_managed_hardware_security_module_key_rotation_policy.html.markdown
> +* `time_before_expiry` - (Optional) Specify the rotation time before expiration in the format of ISO86061. Exactly one of `time_after_creation` or `time_before_expiry` should be specified.
same here
```suggestion
* `time_before_expiry_to_rotate` - (Optional) Specify the rotation time before expiration in the format of ISO86061. Exactly one of `time_after_creation` or `time_before_expiry` should be specified.
```

2024-09-13 05:44 UTC, jackofallops requested changes
Hi @wuxu92 - Just a couple of additional comments to @katbyte 's review to take a look at.

2024-09-13 05:44 UTC, jackofallops commented on internal/services/managedhsm/key_vault_managed_hardware_security_module_key_rotation_policy_resource.go
> +		expiryTime = utils.String(policy.ExipreAfter)
Can we not use the `utils` package here as we're deprecating these functions, and instead use the `pointer` package as you have done in the flatten below?
```suggestion
		expiryTime = pointer.To(policy.ExipreAfter)
```

2024-09-13 05:44 UTC, jackofallops commented on internal/services/managedhsm/key_vault_managed_hardware_security_module_key_rotation_policy_resource_test.go
> +	data := acceptance.BuildTestData(t, "azurerm_key_vault_managed_hardware_security_module_key", "test")
This is the wrong resource here?
```suggestion
	data := acceptance.BuildTestData(t, "azurerm_key_vault_managed_hardware_security_module_key_rotation_policy", "test")
```

2024-09-16 06:50 UTC, jackofallops requested changes
Thanks for the updates @wuxu92 - Spotted a couple typos and whitespace items if you can take a look, then I think we should be good to run the test.

2024-09-16 06:50 UTC, jackofallops commented on internal/services/managedhsm/key_vault_managed_hardware_security_module_key_rotation_policy_resource.go
> +			// settign a blank policy to delete the existing policy
```suggestion
			// setting a blank policy to delete the existing policy
```

2024-09-16 06:50 UTC, jackofallops commented on internal/services/managedhsm/key_vault_managed_hardware_security_module_key_rotation_policy_resource.go
> +	ExipreAfter       string `tfschema:"expire_after"`
Typo here
```suggestion
	ExpireAfter       string `tfschema:"expire_after"`
```

2024-09-16 06:50 UTC, jackofallops commented on internal/services/managedhsm/key_vault_managed_hardware_security_module_key_rotation_policy_resource_test.go
> +
unnecessary whitespace here?
```suggestion
```

2024-09-16 06:50 UTC, jackofallops commented on internal/services/managedhsm/key_vault_managed_hardware_security_module_key_rotation_policy_resource_test.go
> +resource "azurerm_key_vault_managed_hardware_security_module" "test" {
```suggestion
}

resource "azurerm_key_vault_managed_hardware_security_module" "test" {
```

2024-09-16 06:50 UTC, jackofallops commented on internal/services/managedhsm/key_vault_managed_hardware_security_module_key_rotation_policy_resource_test.go
> +
unnecessary whitespace here?
```suggestion
```

2024-09-16 06:50 UTC, jackofallops commented on internal/services/managedhsm/key_vault_managed_hardware_security_module_key_rotation_policy_resource_test.go
> +resource "azurerm_key_vault_certificate" "cert" {
```suggestion
}

resource "azurerm_key_vault_certificate" "cert" {
```

2024-09-19 03:16 UTC, katbyte approved these changes
Thanks @wuxu92  - LGTM 🛋️

2024-09-19 03:45 UTC, merged