`azurerm_container_app_job` - Add `Identity` property to Container App Job Scaling Rules
hashicorp/terraform-provider-azurerm pull request #27489
Opened 2024-09-24 15:56 UTC by Dionmm

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description
In Azure Container App Jobs they have recently added support for authenticating using a managed identity in scaling rules. This allows rules to be added without the need for less secure methods (such as PATs, SAS tokens, or connection strings) to be used for the scaling rules' authentication.

Either user assigned or system identities can be used.

All scaling rules should have an identity property that accepts the resource ID for a user assigned identity or system in the case of a system assigned identity.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.

Some tests appear to be failing on the `main` branch when running locally, specifically `TestAccContainerAppJob_withWorkloadProfileUpdate`

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_container_app_job` - add support for Managed Identity in scaling rules

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #26570
Related #26994

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-10-02 12:27 UTC, ghjklw commented
@Dionmm thank you, I'm looking forward to using it! Is it correct that you have implemented managed identity for scale rules both for `azurerm_container_app` and `azurerm_container_app_job`?

It looks like you have only updated the documentation for `azurerm_container_app_job`.

2024-10-17 03:27 UTC, katbyte requested changes

2024-10-17 03:27 UTC, katbyte commented on internal/services/containerapps/helpers/container_apps.go
> +				"identity": {
could we use one of the common schema identity functions here? ie
```
"identity": commonschema.UserAssignedIdentityOptional(),
```

2025-01-10 18:07 UTC, nquandt commented
@Dionmm could you review @katbyte 's requested changes?

2025-02-03 15:39 UTC, spawluk-zartis commented on website/docs/r/container_app_job.html.markdown
> +* `identity` - (Optional) The identity to use for the scale rule. This can either be the Resource ID of a User Assigned Identity, or `System` for the System Assigned Identity.
I think this doc section should be added to `azurerm_container_app.template.custom_scale_rule`

2025-02-15 15:40 UTC, Dionmm commented on internal/services/containerapps/helpers/container_apps.go
> +				"identity": {
We can, done.

2025-04-16 11:51 UTC, stephybun requested changes
Thanks for this PR @Dionmm. In addition to the comments left in-line could you also add test cases for the `azurerm_container_app` resource since these schema changes affect that resource as well.

2025-04-19 11:20 UTC, closed without merging