add sub_path property to container app volume_mount
hashicorp/terraform-provider-azurerm pull request #27533
Opened 2024-09-29 13:50 UTC by stergem

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_container_app` - Support for subPath in volumeMounts [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #23765

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-10-17 03:37 UTC, katbyte submitted a review, later dismissed
Thanks @stergem - LGTM 🍨

2024-10-17 03:55 UTC, katbyte commented on internal/services/containerapps/container_app_resource_test.go
> +        sub_path = "subdirectory"
```suggestion
        name       = azurerm_container_app_environment_storage.test.name
        path         = "/tmp/testdata"
        sub_path = "subdirectory"
```

2024-10-17 13:52 UTC, jackofallops requested changes
Hi @stergem - Spotted a small problem while skimming through, can you take a look at the below?

Thanks!

2024-10-17 13:52 UTC, jackofallops commented on internal/services/containerapps/helpers/container_apps.go
> +					Optional:    true,
This should be computed only as it is used by a data source only.
```suggestion
					Computed:    true,
```

2025-02-07 07:21 UTC, stephybun approved these changes
Tests look good, thanks for this @stergem LGTM 👍

2025-02-07 07:22 UTC, merged