New Resource: `azurerm_eventgrid_namespace`
hashicorp/terraform-provider-azurerm pull request #27682
Opened 2024-10-17 14:49 UTC by catriona-m

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Adding `azurerm_eventgrid_namespace` as a new resource.

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* New Resource: `azurerm_eventgrid_namespace` [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [x] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-10-29 09:14 UTC, stephybun requested changes
Thanks @catriona-m, could you take a look at the review comments left in-line?

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +		"name": {
Can we add validation on this?

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +			ConfigMode: pluginsdk.SchemaConfigModeAttr,
This isn't `Computed` so I don't think we need to be setting this on the block
```suggestion
```

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +					"ip_mask": {
Any validation here? I think we can validate CIDR input

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +								},
Validation here?

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +								},
Validation here?

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +				state.Location = model.Location
```suggestion
				state.Location = location.Normalize(model.Location)
```

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +		return &ipRules
If we're not supplying any inbound IP rules I think we should be returning nil here instead of an empty InboundIPRule slice

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +		return &topicSpacesConfig
Same here

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +		return &topicSpacesConfig
And here

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +func expandAlternativeAuthenticationNameSources(input []string) *[]namespaces.AlternativeAuthenticationNameSource {
And here

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +		return &dynamicRoutingEnrichments
Here too

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +		return &staticRoutingEnrichments
Here too

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +	output.RouteTopicResourceId = pointer.From(topicSpacesConfig.RouteTopicResourceId)
We should parse this before setting into state so that we can catch any potential casing inconsistencies in the API.

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource_test.go
> +
```suggestion
```

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource_test.go
> +
```suggestion
```

2024-10-29 09:14 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource_test.go
> +			Config: r.basicWithTags(data),
Tags can be updated but it looks like we don't cover this in the tests

2024-10-29 09:14 UTC, stephybun commented on website/docs/r/eventgrid_namespace.html.markdown
> +* `capacity` - (Optional)  (Optional) Specifies the Capacity / Throughput Units for an Eventgrid Namespace. Valid values can be between `1` and `40`.
```suggestion
* `capacity` - (Optional) Specifies the Capacity / Throughput Units for an Eventgrid Namespace. Valid values can be between `1` and `40`.
```

2024-10-29 09:14 UTC, stephybun commented on website/docs/r/eventgrid_namespace.html.markdown
> +* `maximum_client_sessions_per_authentication_name` - (Optional) Specifies the maximum number of client sessions epr authentication name. Valid values can be between `1` and `100`.
```suggestion
* `maximum_client_sessions_per_authentication_name` - (Optional) Specifies the maximum number of client sessions per authentication name. Valid values can be between `1` and `100`.
```

2024-10-29 09:14 UTC, stephybun commented on website/docs/r/eventgrid_namespace.html.markdown
> +* `route_topic_id` - (Optional) Specifies the Event Grid topic resource id to route messages to.
```suggestion
* `route_topic_id` - (Optional) Specifies the Event Grid topic resource ID to route messages to.
```

2024-11-04 11:15 UTC, sbugalski commented
Any update on this please?

2024-11-11 13:08 UTC, catriona-m commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +	ZoneRedundant            bool                                       `tfschema:"zone_redundant"`
Thanks @stephybun - I tested this and confirmed the api handles setting this based on location so it can be removed here 👍

2024-11-19 07:48 UTC, stephybun approved these changes
Thanks @catriona-m. A few more minor comments, but other than that this LGTM provided the tests are passing!

2024-11-19 07:48 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource.go
> +	var output []InboundIpRuleModel
Forgot to flag this in my previous review, there is a difference between declaring a slice like this and like
`output := make([]InboundIpRuleModel, 0)`

Which is that the declaration `var output []InboundIpRuleModel` evaluates to `nil` if nothing has been appended to it, whereas initialising it with `make` will result in an empty slice `[]` which is what we want to setting values into state.

Can you please update this, as well as all the other flatten functions to 
```suggestion
	output := make([]InboundIpRuleModel, 0)
```

2024-11-19 07:48 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource_test.go
> +func (r EventGridNamespaceResource) basicWithTags(data acceptance.TestData) string {
Minor but we could just call this 
```suggestion
func (r EventGridNamespaceResource) tags(data acceptance.TestData) string {
```

2024-11-19 07:48 UTC, stephybun commented on internal/services/eventgrid/eventgrid_namespace_resource_test.go
> +func (r EventGridNamespaceResource) basicWithTagsUpdated(data acceptance.TestData) string {
Likewise 
```suggestion
func (r EventGridNamespaceResource) tagsUpdated(data acceptance.TestData) string {
```

2024-11-19 17:01 UTC, catriona-m commented
> Thanks @catriona-m. A few more minor comments, but other than that this LGTM provided the tests are passing!

Thanks @stephybun - the tests are passing so going to merge this now 👍

2024-11-19 17:13 UTC, merged