New Resource: `azurerm_dev_center_project_pool`
hashicorp/terraform-provider-azurerm pull request #27706
Opened 2024-10-21 02:03 UTC by neil-yechenwei

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description
This PR is to support Dev Center Project Pool.

API Reference:
https://github.com/Azure/azure-rest-api-specs/blob/cfe318beba82c1e5bda6a600f91de32cba814364/specification/devcenter/resource-manager/Microsoft.DevCenter/stable/2023-04-01/vdi.json#L179

Overview:
https://learn.microsoft.com/en-us/azure/dev-box/how-to-manage-dev-center#attach-a-network-connection-to-a-dev-center
https://learn.microsoft.com/en-us/azure/dev-box/how-to-configure-network-connections?tabs=AzureADJoin

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* New Resource: `azurerm_dev_center_project_pool`

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/26704

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-10-23 07:43 UTC, ms-zhenhua requested changes
Hi @neil-yechenwei, 

Thanks for this PR - I've taken a look through and left some minor comments inline. If we can fix those up, this should be good to go 👍

2024-10-23 07:43 UTC, ms-zhenhua commented on internal/services/devcenter/dev_center_project_pool_resource.go
> +	if input == nil || (input != nil && pointer.From(input.Status) == pools.StopOnDisconnectEnableStatusDisabled) {
```suggestion
	if input == nil || pointer.From(input.Status) == pools.StopOnDisconnectEnableStatusDisabled {
```

2024-10-23 07:43 UTC, ms-zhenhua commented on internal/services/devcenter/dev_center_project_pool_resource.go
> +	return gracePeriodMinutes
```suggestion
	return pointer.From(input.GracePeriodMinutes)
```

2024-10-23 08:03 UTC, neil-yechenwei commented on internal/services/devcenter/dev_center_project_pool_resource.go
> +	return gracePeriodMinutes
Updated

2024-10-23 08:03 UTC, neil-yechenwei commented on internal/services/devcenter/dev_center_project_pool_resource.go
> +	if input == nil || (input != nil && pointer.From(input.Status) == pools.StopOnDisconnectEnableStatusDisabled) {
Updated

2024-10-23 08:06 UTC, neil-yechenwei commented
@ms-zhenhua , thanks for the comments. I updated PR. Please take another look.

2024-10-23 08:07 UTC, ms-zhenhua approved these changes
@neil-yechenwei ,

Thank you for your updates. LGTM~

2024-10-23 14:09 UTC, stephybun reviewed
Thanks @neil-yechenwei! This looks good, I just have one suggestion around the naming of one of the properties.

2024-10-23 14:09 UTC, stephybun commented on internal/services/devcenter/dev_center_project_pool_resource.go
> +		"network_connection_name": {
I think this would be clearer as 
```suggestion
		"dev_center_attached_network_name": {
```

2024-10-24 01:12 UTC, neil-yechenwei commented on internal/services/devcenter/dev_center_project_pool_resource.go
> +		"network_connection_name": {
Updated

2024-10-24 01:29 UTC, neil-yechenwei commented
@stephybun , thanks for the comments. I updated PR. Please take another look.

2024-10-24 09:04 UTC, stephybun approved these changes
Thanks @neil-yechenwei LGTM 👍

2024-10-24 09:04 UTC, merged