`azurerm_public_ip` - support for the `domain_name_label_scope` property
hashicorp/terraform-provider-azurerm pull request #27748
Opened 2024-10-24 09:59 UTC by sinbai

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Support for the `domain_name_label_scope` property.

Swagger: https://github.com/Azure/azure-rest-api-specs/blob/fe44d3261ff0ea816315126120672ccec78c3074/specification/network/resource-manager/Microsoft.Network/stable/2023-11-01/publicIpAddress.json#L619

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

PASS: TestAccPublicIpStatic_update (300.85s)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_public_ip` - support for the `domain_name_label_scope` property [GH-27730]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27730

2024-10-24 23:05 UTC, katbyte requested changes
test failure
```
------- Stdout: -------
=== RUN   TestAccPublicIpStatic_canLabelBe63
=== PAUSE TestAccPublicIpStatic_canLabelBe63
=== CONT  TestAccPublicIpStatic_canLabelBe63
    testcase.go:173: Step 1/3 error: Error running pre-apply plan: exit status 1
        
        Error: domain_name_label must contain only lowercase alphanumeric characters, numbers and hyphens. It must start with a letter, end only with a number or letter and not exceed 63 characters in length
        
          with azurerm_public_ip.test,
          on terraform_plugin_test.tf line 43, in resource "azurerm_public_ip" "test":
          43:   domain_name_label = "6lv2zfdpd98dl0yse8w2ajdh0qm8xypfdtbmncy7hjtetbquacbp2ozjeq37by2"
        
--- FAIL: TestAccPublicIpStatic_canLabelBe63 (6.83s)
FAIL
```

2024-10-25 02:40 UTC, sinbai commented
> TestAccPublicIpStatic_canLabelBe63



> test failure
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccPublicIpStatic_canLabelBe63
> === PAUSE TestAccPublicIpStatic_canLabelBe63
> === CONT  TestAccPublicIpStatic_canLabelBe63
>     testcase.go:173: Step 1/3 error: Error running pre-apply plan: exit status 1
>         
>         Error: domain_name_label must contain only lowercase alphanumeric characters, numbers and hyphens. It must start with a letter, end only with a number or letter and not exceed 63 characters in length
>         
>           with azurerm_public_ip.test,
>           on terraform_plugin_test.tf line 43, in resource "azurerm_public_ip" "test":
>           43:   domain_name_label = "6lv2zfdpd98dl0yse8w2ajdh0qm8xypfdtbmncy7hjtetbquacbp2ozjeq37by2"
>         
> --- FAIL: TestAccPublicIpStatic_canLabelBe63 (6.83s)
> FAIL
> ```

Hi @katbyte thanks for your time. Test case has been updated and passed. Could you please take another look?

![image](https://github.com/user-attachments/assets/51bd9a4d-9d42-4ffc-a8a5-31d4ed0ad594)

2024-11-05 19:26 UTC, katbyte commented on internal/services/network/public_ip_resource_test.go
> +`, data.RandomInteger, data.Locations.Primary, data.RandomInteger, fmt.Sprintf("test%s", strings.ToLower(data.RandomStringOfLength(59))))
```suggestion
`, data.RandomInteger, data.Locations.Primary, data.RandomInteger, fmt.Sprintf("test%s", strings.ToLower(data.RandomStringOfLength(59)))) // prepend with test (4+59) to ensure the string starts with a letter
```

2024-11-05 23:03 UTC, katbyte commented on website/docs/r/public_ip.html.markdown
> +-> **Note** Once `domain_name_label_scope` is specified, it cannot be changed, changing it forces a new resource to be created.
```suggestion
* `domain_name_label_scope` - (Optional) Scope for the domain name label. If a domain name label scope is specified, an A DNS record is created for the public IP in the Microsoft Azure DNS system with a hashed value includes in FQDN. Possible values are `NoReuse`, `ResourceGroupReuse`, `SubscriptionReuse` and `TenantReuse`. Changing this forces a new Public IP to be created.
```

2024-11-05 23:03 UTC, katbyte approved these changes
LGTM 🍯

2024-11-05 23:05 UTC, merged