`azurerm_security_center_pricing` - add additional update when `subplan` changed
hashicorp/terraform-provider-azurerm pull request #27805
Opened 2024-10-29 08:59 UTC by ziyeqf

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

When `subplan` changes, there might be extensions enabled by default, do an additional update for this case.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

Testing in progress..

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_security_center_pricing` - add additional update when `subplan` changed [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27338

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-12-11 18:08 UTC, yoavfr commented
Hi @ziyeqf - what's happening with this? We have a customer waiting on it.

2024-12-11 23:48 UTC, ziyeqf commented
kindly bubble this up

2024-12-12 06:48 UTC, ziyeqf commented
convert to draft to update

2024-12-16 01:04 UTC, ziyeqf commented
<img width="547" alt="image" src="https://github.com/user-attachments/assets/3c9815cd-6350-40a7-b037-382bc772afe9" />

2025-01-08 08:05 UTC, yoavfr commented
@ziyeqf - looks like this is stuck? Who needs to approve?

2025-01-16 11:58 UTC, yoavfr commented
@ziyeqf ping. There is a customer waiting for this since October. Microsoft is not looking very good here.

2025-02-13 11:06 UTC, stephybun requested changes

2025-02-13 11:06 UTC, stephybun commented on internal/services/securitycenter/security_center_subscription_pricing_resource.go
> +
```suggestion
```

2025-02-13 11:06 UTC, stephybun commented on internal/services/securitycenter/security_center_subscription_pricing_resource.go
> +
```suggestion
```

2025-02-13 11:06 UTC, stephybun commented on internal/services/securitycenter/security_center_subscription_pricing_resource.go
> +
```suggestion
```

2025-02-13 11:06 UTC, stephybun commented on internal/services/securitycenter/security_center_subscription_pricing_resource.go
> +		return fmt.Errorf("setting %s: %+v", id, updateErr)
```suggestion
		return fmt.Errorf("updating %s: %+v", id, updateErr)
```

2025-02-13 11:06 UTC, stephybun commented on internal/services/securitycenter/security_center_subscription_pricing_resource.go
> +	// The extensions list from backend might vary after `tier` changed, thus we need to retire it again.
should this be?
```suggestion
	// The extensions list from backend might vary after `tier` changed, thus we need to retrieve it again.
```

2025-02-13 11:06 UTC, stephybun commented on internal/services/securitycenter/security_center_subscription_pricing_resource.go
> +			return fmt.Errorf("setting %s: %+v", id, updateErr)
```suggestion
			return fmt.Errorf("updating %s: %+v", id, updateErr)
```

2025-02-13 11:06 UTC, stephybun commented on internal/services/securitycenter/security_center_subscription_pricing_resource.go
> +	updateResponse, updateErr := client.Update(ctx, *id, update)
we should be able to reuse `err` here
```suggestion
	updateResponse, err := client.Update(ctx, *id, update)
```

2025-02-13 11:06 UTC, stephybun commented on internal/services/securitycenter/security_center_subscription_pricing_resource.go
> +		_, updateErr := client.Update(ctx, *id, update)
```suggestion
		_, err = client.Update(ctx, *id, update)
```

2025-02-13 11:06 UTC, stephybun commented on website/docs/5.0-upgrade-guide.html.markdown
> +
This isn't a 5.0 change anymore so this should be removed

2025-02-19 02:30 UTC, ziyeqf commented
kindly bubble this up

2025-02-24 05:27 UTC, ziyeqf commented
kindly ping @stephybun

2025-02-26 07:31 UTC, merged