azurerm_pim_active_role_assignment: add support for RBAC conditions.
hashicorp/terraform-provider-azurerm pull request #27947
Opened 2024-11-08 16:01 UTC by jkroepke

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2025-01-30 17:26 UTC, wyattfry commented
Tests passed
<img width="442" alt="image" src="https://github.com/user-attachments/assets/f8ff1923-7fe5-4d4c-b797-5e8c01c3be6d" />

2025-01-31 15:57 UTC, wyattfry approved these changes
nice work

2025-02-17 11:46 UTC, binech91 commented
Hey, I have a use case where I need this feature. Is it planned for release soon, or should I look for a workaround?

2025-02-17 13:09 UTC, jackofallops submitted a review, later dismissed
Hi @jkroepke - Spotted a couple of additional changes to take a look at if you could please?

Thanks

2025-02-17 13:09 UTC, jackofallops commented on website/docs/r/pim_eligible_role_assignment.html.markdown
> +
Since we can't provide helpful validation on this property, maybe a hint on where users can go to find out about valid values? Also, notes are placed after the properties they're referring to.

```suggestion
* `condition` - (Optional) The condition that limits the resources that the role can be assigned to. See the [official conditions documentation](https://learn.microsoft.com/en-us/azure/role-based-access-control/conditions-overview#what-are-role-assignment-conditions) for details. Changing this forces a new resource to be created.

* `condition_version` - (Optional) The version of the condition. Supported values include `2.0`. Changing this forces a new resource to be created.

~> **NOTE:** `condition_version` is required when specifying `condition` and vice versa.

```

2025-02-17 13:09 UTC, jackofallops commented on internal/services/authorization/pim_eligible_role_assignment_resource_test.go
> +		},
Can we update this test to use the `data.ImportStep()` instead of checking the specific values?

2025-02-17 18:00 UTC, erenabiri commented
Hi there, i'm also curious when this will be available.   Please let me know ^_^

2025-02-19 19:30 UTC, wyattfry requested changes
Looks good, just one minor change on the acceptance test and it will be good to merge.

2025-02-19 19:30 UTC, wyattfry commented on internal/services/authorization/pim_eligible_role_assignment_resource_test.go
> +		},
```suggestion
	data.ResourceTest(t, r, []acceptance.TestStep{
		{
			Config: r.condition(data),
			Check: acceptance.ComposeTestCheckFunc(
				check.That(data.ResourceName).ExistsInAzure(r),
			),
		},
		data.ImportStep("schedule.0.start_date_time"),
```

2025-02-20 15:36 UTC, jkroepke commented
Thanks, should be ready for a review now.

2025-02-20 15:45 UTC, wyattfry approved these changes
Thanks @jkroepke LGTM 👍

2025-02-20 15:45 UTC, merged