Azure Container Registry: Update API to 2023-11-01-preview
hashicorp/terraform-provider-azurerm pull request #27983
Opened 2024-11-12 06:05 UTC by magodo

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

The ones that failed also happen in the TC.

<details>
<summary>Test Result</summary>
<pre>
> TF_ACC=1 go test -v -timeout=20h -run='TestAccContainerRegistry' ./internal/services/containers
=== RUN   TestAccContainerRegistryAgentPool_basic
=== PAUSE TestAccContainerRegistryAgentPool_basic
=== RUN   TestAccContainerRegistryAgentPool_requiresImport
=== PAUSE TestAccContainerRegistryAgentPool_requiresImport
=== RUN   TestAccContainerRegistryAgentPool_complete
=== PAUSE TestAccContainerRegistryAgentPool_complete
=== RUN   TestAccContainerRegistryCacheRule_basic
=== PAUSE TestAccContainerRegistryCacheRule_basic
=== RUN   TestAccContainerRegistryCacheRule_requiresImport
=== PAUSE TestAccContainerRegistryCacheRule_requiresImport
=== RUN   TestAccContainerRegistry_basic
=== PAUSE TestAccContainerRegistry_basic
=== RUN   TestAccContainerRegistry_requiresImport
=== PAUSE TestAccContainerRegistry_requiresImport
=== RUN   TestAccContainerRegistry_basicManagedStandard
=== PAUSE TestAccContainerRegistry_basicManagedStandard
=== RUN   TestAccContainerRegistry_basicManagedPremium
=== PAUSE TestAccContainerRegistry_basicManagedPremium
=== RUN   TestAccContainerRegistry_basic2Premium2basic
=== PAUSE TestAccContainerRegistry_basic2Premium2basic
=== RUN   TestAccContainerRegistry_complete
=== PAUSE TestAccContainerRegistry_complete
=== RUN   TestAccContainerRegistry_update
=== PAUSE TestAccContainerRegistry_update
=== RUN   TestAccContainerRegistry_geoReplicationLocation
=== PAUSE TestAccContainerRegistry_geoReplicationLocation
=== RUN   TestAccContainerRegistry_networkAccessProfileIp
=== PAUSE TestAccContainerRegistry_networkAccessProfileIp
=== RUN   TestAccContainerRegistry_networkAccessProfileUpdate
=== PAUSE TestAccContainerRegistry_networkAccessProfileUpdate
=== RUN   TestAccContainerRegistry_zoneRedundancy
=== PAUSE TestAccContainerRegistry_zoneRedundancy
=== RUN   TestAccContainerRegistry_geoReplicationZoneRedundancy
=== PAUSE TestAccContainerRegistry_geoReplicationZoneRedundancy
=== RUN   TestAccContainerRegistry_geoReplicationRegionEndpoint
=== PAUSE TestAccContainerRegistry_geoReplicationRegionEndpoint
=== RUN   TestAccContainerRegistry_anonymousPull
=== PAUSE TestAccContainerRegistry_anonymousPull
=== RUN   TestAccContainerRegistry_dataEndpoint
=== PAUSE TestAccContainerRegistry_dataEndpoint
=== RUN   TestAccContainerRegistry_networkRuleBypassOption
=== PAUSE TestAccContainerRegistry_networkRuleBypassOption
=== RUN   TestAccContainerRegistry_encryption
=== PAUSE TestAccContainerRegistry_encryption
=== RUN   TestAccContainerRegistryScopeMap_basic
=== PAUSE TestAccContainerRegistryScopeMap_basic
=== RUN   TestAccContainerRegistryScopeMap_requiresImport
=== PAUSE TestAccContainerRegistryScopeMap_requiresImport
=== RUN   TestAccContainerRegistryScopeMap_complete
=== PAUSE TestAccContainerRegistryScopeMap_complete
=== RUN   TestAccContainerRegistryTask_dockerStep
    container_registry_task_resource_test.go:42: `ARM_TEST_ACR_TASK_GITHUB_REPO_URL` must be set for acceptance tests!
--- SKIP: TestAccContainerRegistryTask_dockerStep (0.00s)
=== RUN   TestAccContainerRegistryTask_fileTaskStep
    container_registry_task_resource_test.go:42: `ARM_TEST_ACR_TASK_GITHUB_REPO_URL` must be set for acceptance tests!
--- SKIP: TestAccContainerRegistryTask_fileTaskStep (0.00s)
=== RUN   TestAccContainerRegistryTask_encodedTaskStep
    container_registry_task_resource_test.go:42: `ARM_TEST_ACR_TASK_GITHUB_REPO_URL` must be set for acceptance tests!
--- SKIP: TestAccContainerRegistryTask_encodedTaskStep (0.00s)
=== RUN   TestAccContainerRegistryTask_dockerStepBaseImageTrigger
    container_registry_task_resource_test.go:42: `ARM_TEST_ACR_TASK_GITHUB_REPO_URL` must be set for acceptance tests!
--- SKIP: TestAccContainerRegistryTask_dockerStepBaseImageTrigger (0.00s)
=== RUN   TestAccContainerRegistryTask_dockerStepSourceTrigger
    container_registry_task_resource_test.go:42: `ARM_TEST_ACR_TASK_GITHUB_REPO_URL` must be set for acceptance tests!
--- SKIP: TestAccContainerRegistryTask_dockerStepSourceTrigger (0.00s)
=== RUN   TestAccContainerRegistryTask_dockerStepTimerTrigger
    container_registry_task_resource_test.go:42: `ARM_TEST_ACR_TASK_GITHUB_REPO_URL` must be set for acceptance tests!
--- SKIP: TestAccContainerRegistryTask_dockerStepTimerTrigger (0.00s)
=== RUN   TestAccContainerRegistryTask_identity
    container_registry_task_resource_test.go:42: `ARM_TEST_ACR_TASK_GITHUB_REPO_URL` must be set for acceptance tests!
--- SKIP: TestAccContainerRegistryTask_identity (0.00s)
=== RUN   TestAccContainerRegistryTask_fileTaskStepRegistryCredential
    container_registry_task_resource_test.go:42: `ARM_TEST_ACR_TASK_GITHUB_REPO_URL` must be set for acceptance tests!
--- SKIP: TestAccContainerRegistryTask_fileTaskStepRegistryCredential (0.00s)
=== RUN   TestAccContainerRegistryTask_systemTask
=== PAUSE TestAccContainerRegistryTask_systemTask
=== RUN   TestAccContainerRegistryTask_requiresImport
    container_registry_task_resource_test.go:42: `ARM_TEST_ACR_TASK_GITHUB_REPO_URL` must be set for acceptance tests!
--- SKIP: TestAccContainerRegistryTask_requiresImport (0.00s)
=== RUN   TestAccContainerRegistryTaskSchedule_basic
    container_registry_task_resource_test.go:42: `ARM_TEST_ACR_TASK_GITHUB_REPO_URL` must be set for acceptance tests!
--- SKIP: TestAccContainerRegistryTaskSchedule_basic (0.00s)
=== RUN   TestAccContainerRegistryTokenPassword_basic
=== PAUSE TestAccContainerRegistryTokenPassword_basic
=== RUN   TestAccContainerRegistryTokenPassword_complete
=== PAUSE TestAccContainerRegistryTokenPassword_complete
=== RUN   TestAccContainerRegistryTokenPassword_update
=== PAUSE TestAccContainerRegistryTokenPassword_update
=== RUN   TestAccContainerRegistryTokenPa [...]

2024-11-18 11:42 UTC, stephybun commented on internal/services/containers/client/client.go
> +	containerregistry_v2023_06_01_preview "github.com/hashicorp/go-azure-sdk/resource-manager/containerregistry/2023-11-01-preview"
```suggestion
	containerregistry_v2023_11_01_preview "github.com/hashicorp/go-azure-sdk/resource-manager/containerregistry/2023-11-01-preview"
```

2024-11-19 03:27 UTC, magodo commented
@stephybun Updated, thx!

2024-11-19 08:01 UTC, stephybun requested changes

2024-11-19 08:01 UTC, stephybun commented on internal/services/containers/client/client.go
> +	containerRegistryClient_v2023_06_01_preview, err := containerregistry.NewClientWithBaseURI(o.Environment.ResourceManager, func(c *resourcemanager.Client) {
```suggestion
	containerRegistryClient_v2023_11_01_preview, err := containerregistry.NewClientWithBaseURI(o.Environment.ResourceManager, func(c *resourcemanager.Client) {
```

2024-11-19 08:01 UTC, stephybun commented on internal/services/containers/client/client.go
> +		ContainerRegistryClient:                     containerRegistryClient_v2023_06_01_preview,
```suggestion
		ContainerRegistryClient:                     containerRegistryClient_v2023_11_01_preview,
```

2024-11-19 08:09 UTC, magodo commented
Thank you for pointing this out! Updated.

2024-11-19 09:17 UTC, stephybun approved these changes
Thanks @magodo LGTM 👍

2024-11-19 09:18 UTC, merged