Add Node.js 22 in function application_stack
hashicorp/terraform-provider-azurerm pull request #28081
Opened 2024-11-21 08:31 UTC by wojtekmaj

On 10/24/2024, support for Node.js 22 in Azure Functions has been added as public preview.
Read more: https://azure.microsoft.com/en-us/updates?id=Azure-Functions-support-for-Nodejs-22

Note 1: This PR does not update Azure Web App application_stack, because it seems like Node.js 22 is not supported there yet.

Note 2: I have absolutely no idea what I'm doing, I tried to kinda sorta follow the changes from 7367b6ed1b948a99412a8ef11169c50711500559, with consideration for Note 1.

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2025-01-31 12:10 UTC, stephybun commented on internal/services/appservice/helpers/function_app_schema.go
> +	NodeVersion           string                   `tfschema:"node_version"`                // Supported values `12LTS`, `14LTS`, `16LTS`, `18LTS, `20LTS`, `22LTS`
You will need to update the validation of this property in the actual schema to accept `22` as a value. If you search for `func linuxFunctionAppStackSchema()` in the provider you'll find the schema that corresponds to this model.

2025-01-31 12:10 UTC, stephybun commented on internal/services/appservice/helpers/function_app_schema.go
> +	NodeVersion           string `tfschema:"node_version"`                // Supported values `12LTS`, `14LTS`, `16LTS`, `18LTS, `20LTS`, `22LTS`
Same for this, but looking for the windows schema equivalent.

2025-02-05 14:45 UTC, southwolf commented
@wojtekmaj I believe NodeJS 22 is now supported in Web App. 
<img width="741" alt="image" src="https://github.com/user-attachments/assets/a4ad27a8-2ba2-4167-8a52-c705bf65ef87" />

2025-02-05 14:51 UTC, southwolf requested changes
I believe NodeJS 22 LTS is now available to Web App stack so it should also be added to 

[internal/services/appservice/helpers/app_stack.go
](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/helpers/app_stack.go)

2025-02-06 10:23 UTC, wojtekmaj commented on internal/services/appservice/helpers/function_app_schema.go
> +	NodeVersion           string                   `tfschema:"node_version"`                // Supported values `12LTS`, `14LTS`, `16LTS`, `18LTS, `20LTS`, `22LTS`
I believe that has been tackled already in #28472.

2025-02-06 10:24 UTC, wojtekmaj commented on internal/services/appservice/helpers/function_app_schema.go
> +	NodeVersion           string `tfschema:"node_version"`                // Supported values `12LTS`, `14LTS`, `16LTS`, `18LTS, `20LTS`, `22LTS`
Addressed.

2025-02-24 06:56 UTC, closed without merging