`hdinsight_spark_cluster_resource`: Add support for `availability_zones`
hashicorp/terraform-provider-azurerm pull request #28149
Opened 2024-12-02 07:08 UTC by jiaweitao001

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [x] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2025-03-18 13:23 UTC, stephybun requested changes

2025-03-18 13:23 UTC, stephybun commented on internal/services/hdinsight/hdinsight_spark_cluster_resource.go
> +			"availability_zones": commonschema.ZonesMultipleOptional(),
Convention in the provider is to call these `zones`
```suggestion
			"zones": commonschema.ZonesMultipleOptional(),
```

2025-03-18 13:23 UTC, stephybun commented on internal/services/hdinsight/hdinsight_spark_cluster_resource.go
> +		payload.Zones = pointer.To(expandHDInsightAvailabilityZones(v))
There are functions available to expand and flatten zones
```suggestion
		payload.Zones = pointer.To(zones.ExpandUntyped(d.Get("zones").(*schema.Set).List()))
```

2025-03-18 13:23 UTC, stephybun commented on internal/services/hdinsight/hdinsight_spark_cluster_resource.go
> +				d.Set("availability_zones", pointer.From(model.Zones))
```suggestion
				d.Set("availability_zones", zones.FlattenUntyped(props.AvailabilityZones))
```

2025-03-18 13:23 UTC, stephybun commented on internal/services/hdinsight/hdinsight_spark_cluster_resource_test.go
> +func TestAccHDInsightSparkCluster_availabilityZones(t *testing.T) {
If zones are update-able then this test should be extended to update it. Furthermore this property should be added to the `complete` test config as well.

2025-03-19 13:21 UTC, jiaweitao001 commented on internal/services/hdinsight/hdinsight_spark_cluster_resource.go
> +			"availability_zones": commonschema.ZonesMultipleOptional(),
Changed.

2025-03-19 13:21 UTC, jiaweitao001 commented on internal/services/hdinsight/hdinsight_spark_cluster_resource.go
> +		payload.Zones = pointer.To(expandHDInsightAvailabilityZones(v))
Changed.

2025-03-19 13:21 UTC, jiaweitao001 commented on internal/services/hdinsight/hdinsight_spark_cluster_resource.go
> +				d.Set("availability_zones", pointer.From(model.Zones))
Fixed.

2025-03-19 13:21 UTC, jiaweitao001 commented on internal/services/hdinsight/hdinsight_spark_cluster_resource_test.go
> +func TestAccHDInsightSparkCluster_availabilityZones(t *testing.T) {
Added to complete test.

2025-03-20 07:28 UTC, stephybun commented on internal/services/hdinsight/hdinsight_spark_cluster_resource_test.go
> +func TestAccHDInsightSparkCluster_availabilityZones(t *testing.T) {
@jiaweitao001 
> If zones are update-able then this test should be extended to update it

This comment hasn't been addressed, currently we're not testing the update of this property, can you please add test coverage for this?

2025-03-21 02:06 UTC, jiaweitao001 commented on internal/services/hdinsight/hdinsight_spark_cluster_resource_test.go
> +func TestAccHDInsightSparkCluster_availabilityZones(t *testing.T) {
Hi @stephybun , this property is not updatable. I've added description in the docs.

2025-03-24 10:45 UTC, stephybun commented on internal/services/hdinsight/hdinsight_spark_cluster_resource_test.go
> +func TestAccHDInsightSparkCluster_availabilityZones(t *testing.T) {
If this property isn't update-able then we should be using the ForceNew commonschema for zones so that the resource will be recreated if it's changed

`commonschema.ZonesMultipleOptionalForceNew()`

2025-03-24 10:46 UTC, stephybun requested changes

2025-03-24 10:46 UTC, stephybun commented on internal/services/hdinsight/hdinsight_spark_cluster_resource.go
> +			"zones": commonschema.ZonesMultipleOptional(),
```suggestion
			"zones": commonschema.ZonesMultipleOptionalForceNew(),
```

2025-03-25 02:08 UTC, jiaweitao001 commented on internal/services/hdinsight/hdinsight_spark_cluster_resource.go
> +			"zones": commonschema.ZonesMultipleOptional(),
Sure. Changed.

2025-03-25 07:01 UTC, stephybun approved these changes
Thanks @jiaweitao001 LGTM 👍

2025-03-25 07:02 UTC, merged