`azurerm_api_management_api`: add costom poller for `import` openapi
hashicorp/terraform-provider-azurerm pull request #28193
Opened 2024-12-06 02:35 UTC by wuxu92

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

As the LRO of importing an OpenAPI file, the polling URL requires the `asyncId` query string to retrieve the actual failure message. This PR adds a custom poller to override the default provisioningState poller.

Also setting the `Partial` to true is required to fix the issue https://github.com/hashicorp/terraform-provider-azurerm/issues/24379#issuecomment-1899251199.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```
--- PASS: TestAccApiManagementApi_importOpenapiInvalide (180.43s)
PASS
```

![image](https://github.com/user-attachments/assets/f2230571-3671-480d-b3ec-90ecca512ad1)

The failing cases are not related to this PR. Some of them are fixed in #28194.

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_api_management_api` - fix poller of importing OpenAPI content [GH-23322]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #23322, fixes #22042, fixes #28201 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-12-09 11:43 UTC, jackofallops requested changes
Thanks @wuxu92 - The changes here I think are made more complicated due to the combined create+update, could you take a look at splitting that before applying the custom poller? (I think a separate PR to do this, then rebase your work here on that when merged will be the fastest way to get this in, due to the complexity of review and safety of testing)

Thanks

2024-12-09 11:43 UTC, jackofallops commented on internal/services/apimanagement/api_management_api_resource.go
> +		d.Partial(true)
I feel this is symptomatic of the combined `CreateUpdate`, can we split this before continuing with this custom poller to make this less difficult to maintain?

2025-02-20 12:53 UTC, byronbayer commented
is there any chance this can get merged in and approved.

2025-03-10 07:58 UTC, jackofallops requested changes
Hi @wuxu92 - Thanks for this. Just a few items to take a quick look at, but looking mostly good.

2025-03-10 07:58 UTC, jackofallops commented on internal/services/apimanagement/testdata/api_management_api_openapi_invalide.yaml
> +            default: PRODUCTIVEInvalide
This looks like a typo? Should it be?
```suggestion
            default: PRODUCTIVEInvalid
```

2025-03-10 07:58 UTC, jackofallops commented on internal/services/apimanagement/custompollers/api_management_api_poller.go
> +
Can we add godoc here to explain the purpose of this custom polller? something like:
```suggestion
// NewAPIManagementAPIPoller - creates a new custom poller for API Management API to handle the case where... [details here]
```

2025-03-10 07:58 UTC, jackofallops commented on internal/services/apimanagement/api_management_api_resource.go
> +	if description != "" {
agreed, can we pull the `description :=` line down to here for better visibility, and use `d.GetOk()` here to ensure the value is populated and not the zero response?

2025-03-10 07:58 UTC, jackofallops commented on internal/services/apimanagement/testdata/api_management_api_openapi_invalide.yaml
> +# Copyright (c) HashiCorp, Inc.
Similar typo in the file name? Should this be:
`internal/services/apimanagement/testdata/api_management_api_openapi_invalid.yaml` ?

2025-04-17 09:52 UTC, Pedroms1 commented
@jackofallops were you able to review these changes? The issue is creating some impact

2025-05-01 14:34 UTC, J0F3 commented
@katbyte @mbfrahry @jackofallops

Could someone please review this PR? This is a very serious bug in the `azurerm_api_management_api` resource which makes the resource almost useless in many cases. The initial issue https://github.com/hashicorp/terraform-provider-azurerm/issues/23322 is now open since September 2023! Unfortunately, there seems almost now reaction to it form Hashicorp / Maintainer of the provider itself to it. 
So, I am really apricate when someone would look into it so that this issue can finally be fixed. 

Thank you!

2025-05-13 13:44 UTC, merged