New Resource - `azurerm_linux_function_app_flex_consumption`
hashicorp/terraform-provider-azurerm pull request #28199
Opened 2024-12-06 10:11 UTC by xiaxyi

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-12-06 16:45 UTC, nzthiago commented
We don't want customers to worry about operating system (and we don't have plans to make a specific Windows version of Flex in the foreseeable future) - recommend simplifying the name not to have Linux in it.

2024-12-10 01:29 UTC, xiaxyi commented
Thanks @nzthiago for the suggestions, @jackofallops are you agree with the idea of removing the `linux` part?

2024-12-27 20:05 UTC, pcsrijith commented
@jackofallops : Could you please update on @nzthiago 's suggestions? We are eagerly waiting for this actually.

2025-01-06 22:34 UTC, NipunaPrashan commented
Happy New Year @jackofallops. Could you be able to check on the suggestions?

2025-01-08 11:56 UTC, stephybun commented
@xiaxyi please go ahead and remove `linux` from the resource name

2025-01-08 12:25 UTC, stephybun requested changes
@xiaxyi, as a heads up this will require a few rounds of reviews, but I've made a first pass through to call out some consistency and style choices. Could you fix those up? I can then go over this in detail with our App Service SME.

Thanks!

2025-01-08 12:25 UTC, stephybun commented on internal/services/appservice/helpers/function_app_schema.go
> +	AppInsightsInstrumentationKey string                      `tfschema:"application_insights_key"` // App Insights Instrumentation Key
Can we remove this comment here since it isn't really alluding to anything helpful (the name is already descriptive)
```suggestion
	AppInsightsInstrumentationKey string                      `tfschema:"application_insights_key"`
```

2025-01-09 07:33 UTC, xiaxyi commented on internal/services/appservice/linux_function_app_flex_consumption_resource.go
> +				return fmt.Errorf("the Site Name %q failed the availability check: %+v", id.SiteName, *model.Message)
yes, this is the name of the function app that's about to be created. if that's what you are asking?

2025-01-09 08:02 UTC, xiaxyi commented
@stephybun Thanks for the review, I understand it will take server rounds of review, that's totally fine.

I updated the pr based on the comments, feel free to let me know if anything needed.

2025-01-09 08:05 UTC, pcsrijith commented
> @stephybun Thanks for the review, I understand it will take server rounds of review, that's totally fine.
> 
> I updated the pr based on the comments, feel free to let me know if anything needed.

I believe, `linux` word needs to be removed from filenames, MR title and in codes as well.

2025-01-14 17:49 UTC, nzthiago commented
@stephybun I believe this is ready for the next round of review, thank you

2025-01-24 00:42 UTC, nzthiago commented
@stephybun checking in to progress with this PR, thank you

2025-01-27 12:06 UTC, stephybun requested changes

2025-01-27 12:06 UTC, stephybun commented on internal/services/appservice/function_app_flex_consumption_resource_test.go
> +  name                  = "blobforfc"
```suggestion
  name                  = "acctestblobforfc"
```

2025-02-02 14:54 UTC, sam-bryant commented
Just checking in on this.  We're eager.  😁

2025-02-04 06:44 UTC, dvasdekis commented
@xiaxyi not sure if you have seen this review?

2025-02-07 06:10 UTC, xiaxyi commented
updated code based on the comments, ran all the tests and failed reason is not related

2025-02-08 17:18 UTC, pcsrijith commented
@stephybun awaiting review and approval

2025-02-11 19:11 UTC, joshvito commented
Patiently awaiting this feature! Thanks

2025-02-11 19:57 UTC, ryaneastabrook commented
Ran into same issue, would love to see this merged!

2025-02-12 07:36 UTC, stephybun requested changes
In addition to the local location overrides for the tests, can you please address these last few comments.

2025-02-12 07:36 UTC, stephybun commented on website/docs/r/function_app_flex_consumption.html.markdown
> +~> **NOTE:** For storage related settings, please use related properties that are available such as `storage_account_access_key`, terraform will assign the value to keys such as `WEBSITE_CONTENTAZURE
Since these reviews, we've introduced a guide on [documentation standards](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/documentation-standards.md). Please title case all of the notes 
```suggestion
~> **Note:** For storage related settings, please use related properties that are available such as `storage_account_access_key`, terraform will assign the value to keys such as `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING`, `AzureWebJobsStorage` in app_setting.
```

2025-02-12 07:36 UTC, stephybun commented on internal/services/appservice/registration.go
> +		FunctionAppFlexConsumptionResource{},
still not sorted alphabetically

2025-02-12 07:36 UTC, stephybun commented on website/docs/r/linux_function_app.html.markdown
> +* `flex_function_app_deployment` - (Optional) A `flex_consumption_app_deployment` block as defined below.
These documentation updates on the linux function app should be removed since these properties haven't been added to the resource.

2025-02-12 07:48 UTC, xiaxyi commented on website/docs/r/linux_function_app.html.markdown
> +* `flex_function_app_deployment` - (Optional) A `flex_consumption_app_deployment` block as defined below.
removed

2025-02-12 07:52 UTC, stephybun commented on website/docs/r/function_app_flex_consumption.html.markdown
> +~> **NOTE:** For storage related settings, please use related properties that are available such as `storage_account_access_key`, terraform will assign the value to keys such as `WEBSITE_CONTENTAZURE
@xiaxyi this hasn't been addressed, I'm asking for all instances of `NOTE` in the documentation to be recased to `Note`.

2025-02-17 03:35 UTC, dvasdekis commented
Hi @stephybun it appears that the requested changes have been made in the latest commit?

2025-02-19 14:11 UTC, ryaneastabrook commented
Is there any help the community can provide to get this moving again?

2025-02-26 02:44 UTC, xiaxyi commented
Hi @stephybun, I'm not sure about why all the test cases failed due to the `400 error`, despite of the fact that I've set the test location to eastus2 via the environment `ARM_TEST_LOCATION`. I've ran all the failed test cases separately and now they all passed. Would you mind continue to review this PR and let me know your comments? Thanks!

2025-02-26 08:14 UTC, stephybun requested changes

2025-02-26 11:39 UTC, pcsrijith commented on internal/services/appservice/function_app_flex_consumption_resource_test.go
> +`, data.RandomInteger, data.Locations.Primary, data.RandomString, data.RandomInteger)
@stephybun : If we are suggesting to hardcode it to `eastus2`, does that mean customers can only create the resource in `eastus2` region, even if other regions are supported from Azure? If I'm not wrong, there are many regions which support flex consumption plans.

2025-02-26 12:29 UTC, stephybun commented on internal/services/appservice/function_app_flex_consumption_resource_test.go
> +`, data.RandomInteger, data.Locations.Primary, data.RandomString, data.RandomInteger)
@pcsrijith this hardcodes the region only for our acceptance tests and has no bearing on what regions users will be able to provision this in.

2025-02-26 17:40 UTC, nzthiago commented
@stephybun it looks like data.Locations.Primary is set to West Europe in the acceptance test.  Flex Consumption is currently in North Europe, Southeast Asia, East Asia, Eas US 2, Southcentral US, Australia East, East US, West US 2, UK South, West US 3, and Sweden Central. 

Not a huge deal but would data.Locations.Secondary or data.Locations.Ternary match one of those? If so it might be better instead of fully hardcoding the region.

2025-02-27 08:50 UTC, stephybun approved these changes
Tests looks good, thanks @xiaxyi LGTM 👍 
![image](https://github.com/user-attachments/assets/ed925aa2-0cff-490a-b159-5b59b1716d39)

2025-02-27 08:51 UTC, merged

2025-02-27 09:16 UTC, pcsrijith commented
Thank you @xiaxyi , @nzthiago and @stephybun for MR. Will create the resources as soon as 4.21.0 goes live.

2025-02-28 13:54 UTC, AELO23 commented
this is awesome!!

2025-03-03 04:41 UTC, xiaxyi commented
Please try using `  storage_container_endpoint                    ="${azurerm_storage_account.test.primary_blob_endpoint}${azurerm_storage_container.test.name}"
`

2025-03-03 15:45 UTC, david-haugh commented
Thanks, everyone, for this! Does it include a parameter for always-ready instances?

2025-03-11 06:49 UTC, xiaxyi commented
The `always_ready` config is included in the PR https://github.com/hashicorp/terraform-provider-azurerm/pull/29023

2025-03-11 08:48 UTC, xiaxyi commented
The `https_only` is included https://github.com/hashicorp/terraform-provider-azurerm/issues/29006