`azurerm_cognitive_account`: allows `bypass` property for `network_acls`
hashicorp/terraform-provider-azurerm pull request #28221
Opened 2024-12-09 16:36 UTC by feliperezende-barbosa

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This PR implements the `network_acls.bypass` property for `azurerm_coginitive_account`. [Azure Services for Azure OpenAI](https://learn.microsoft.com/en-us/azure/ai-services/cognitive-services-virtual-networks?tabs=portal#grant-access-to-trusted-azure-services-for-azure-openai)

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/cognitive -run=TestAccCognitiveAccount_networkAclsVirtualNetworkRules -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccCognitiveAccount_networkAclsVirtualNetworkRules
=== PAUSE TestAccCognitiveAccount_networkAclsVirtualNetworkRules
=== CONT  TestAccCognitiveAccount_networkAclsVirtualNetworkRules
--- PASS: TestAccCognitiveAccount_networkAclsVirtualNetworkRules (220.30s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/cognitive	222.013s
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_cognitive_account` - support for the `bypass` to trusted Azure Services property [GH-0000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-12-18 13:49 UTC, catriona-m requested changes
Thanks for this @feliperezende-barbos. This is looking good so far. Could we also add additional test steps to set this to `AzureServices` and back to `None` so we can confirm that updating this property works as expected? Thanks!

2024-12-18 14:32 UTC, feliperezende-barbosa commented
> Thanks for this @feliperezende-barbos. This is looking good so far. Could we also add additional test steps to set this to `AzureServices` and back to `None` so we can confirm that updating this property works as expected? Thanks!

Sure, but just to add something. In the test I set the `bypass` to `None` first and then I update to `AzureServices`. Would you like to add one more step to back from `AzureServices` to `None` or just change the order of the acctest that already exists? Thanks.

2024-12-19 17:31 UTC, catriona-m requested changes
Thanks for updating the tests @feliperezende-barbosa. I had a look at the results and it appears we have a failure, but once that is addressed I can take another look. Thanks!

```
------- Stdout: -------
=== RUN   TestAccCognitiveAccount_networkAcls
=== PAUSE TestAccCognitiveAccount_networkAcls
=== CONT  TestAccCognitiveAccount_networkAcls
    testcase.go:173: Step 1/6 error: Error running apply: exit status 1
        Error: creating Account (Subscription: "*******"
        Resource Group Name: "acctestRG-cognitive-241219155302861835"
        Account Name: "acctestcogacc-241219155302861835"): unexpected status 400 (400 Bad Request) with error: NetworkAclsBypassNotSupported: The Kind 'Face' does not support Trusted Services.
          with azurerm_cognitive_account.test,
          on terraform_plugin_test.tf line 68, in resource "azurerm_cognitive_account" "test":
          68: resource "azurerm_cognitive_account" "test" {
--- FAIL: TestAccCognitiveAccount_networkAcls (177.11s)
FAIL
```

2024-12-19 17:49 UTC, feliperezende-barbosa commented
> Thanks for updating the tests @feliperezende-barbosa. I had a look at the results and it appears we have a failure, but once that is addressed I can take another look. Thanks!
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccCognitiveAccount_networkAcls
> === PAUSE TestAccCognitiveAccount_networkAcls
> === CONT  TestAccCognitiveAccount_networkAcls
>     testcase.go:173: Step 1/6 error: Error running apply: exit status 1
>         Error: creating Account (Subscription: "*******"
>         Resource Group Name: "acctestRG-cognitive-241219155302861835"
>         Account Name: "acctestcogacc-241219155302861835"): unexpected status 400 (400 Bad Request) with error: NetworkAclsBypassNotSupported: The Kind 'Face' does not support Trusted Services.
>           with azurerm_cognitive_account.test,
>           on terraform_plugin_test.tf line 68, in resource "azurerm_cognitive_account" "test":
>           68: resource "azurerm_cognitive_account" "test" {
> --- FAIL: TestAccCognitiveAccount_networkAcls (177.11s)
> FAIL
> ```

I realized that you have tested the `TestAccCognitiveAccount_networkAcls` but the correct to test is `TestAccCognitiveAccount_networkAclsVirtualNetworkRules`. `TestAccCognitiveAccount_networkAcls` is for another sort of test. The problem was caused because the `bypass` property works for the Kind `OpenAI` and not for the Kind `Face` as you can see the error: `Account Name: "acctestcogacc-241219155302861835"): unexpected status 400 (400 Bad Request) with error: NetworkAclsBypassNotSupported: The Kind 'Face' does not support Trusted Services.` That's why I've changed the Kind from `Face` to `OpenAI` in `TestAccCognitiveAccount_networkAclsVirtualNetworkRules`. You can check it out in this [link](https://learn.microsoft.com/en-us/azure/ai-services/cognitive-services-virtual-networks?tabs=portal#grant-access-to-trusted-azure-services-for-azure-openai).

2025-01-08 16:23 UTC, catriona-m commented
> > Thanks for updating the tests @feliperezende-barbosa. I had a look at the results and it appears we have a failure, but once that is addressed I can take another look. Thanks!
> > ```
> > ------- Stdout: -------
> > === RUN   TestAccCognitiveAccount_networkAcls
> > === PAUSE TestAccCognitiveAccount_networkAcls
> > === CONT  TestAccCognitiveAccount_networkAcls
> >     testcase.go:173: Step 1/6 error: Error running apply: exit status 1
> >         Error: creating Account (Subscription: "*******"
> >         Resource Group Name: "acctestRG-cognitive-241219155302861835"
> >         Account Name: "acctestcogacc-241219155302861835"): unexpected status 400 (400 Bad Request) with error: NetworkAclsBypassNotSupported: The Kind 'Face' does not support Trusted Services.
> >           with azurerm_cognitive_account.test,
> >           on terraform_plugin_test.tf line 68, in resource "azurerm_cognitive_account" "test":
> >           68: resource "azurerm_cognitive_account" "test" {
> > --- FAIL: TestAccCognitiveAccount_networkAcls (177.11s)
> > FAIL
> > ```
> 
> I realized you had tested the `TestAccCognitiveAccount_networkAcls` instead of `TestAccCognitiveAccount_networkAclsVirtualNetworkRules`. The problem was caused because the `bypass` property works for the Kind `OpenAI` and not for the Kind `Face` as you can see in the error: `Account Name: "acctestcogacc-241219155302861835"): unexpected status 400 (400 Bad Request) with error: NetworkAclsBypassNotSupported: The Kind 'Face' does not support Trusted Services.` That's why I've changed the Kind from `Face` to `OpenAI` in `TestAccCognitiveAccount_networkAclsVirtualNetworkRules`. You can check it out in this [link](https://learn.microsoft.com/en-us/azure/ai-services/cognitive-services-virtual-networks?tabs=portal#grant-access-to-trusted-azure-services-for-azure-openai). I fixed the `TestAccCognitiveAccount_networkAcls` because both tests are related. I've updated the PR in `Testing` section with the test results I've performed for both scenarios.

Thanks for your reply @feliperezende-barbosa. My concern is that adding this property seems to be affecting existing configurations which are not using the `bypass` property and which previously worked without error beforehand. Would you be able to take another look at fixing this up? Thanks!

2025-01-09 19:14 UTC, feliperezende-barbosa commented
Thanks @catriona-m, it had the risk of affecting the existing configurations that are not using and do not support it. I've added more tests and one more validating an error that does not support the `bypass` property. Could you please take a look again? Thanks again.

2025-01-14 15:36 UTC, catriona-m requested changes
Thanks for updating this @feliperezende-barbosa - I have left one query inline but I can take another look once that is addressed. Thanks!

2025-01-14 17:07 UTC, feliperezende-barbosa commented
> Thanks for updating this @feliperezende-barbosa - I have left one query inline but I can take another look once that is addressed. Thanks!

Hi @catriona-m, I cannot see any query inline. Could you please check this out? Thanks

2025-01-15 15:03 UTC, catriona-m commented on internal/services/cognitive/cognitive_account_resource.go
> +	} else {
is it possible for a user to use a `kind` of `OpenAI` and not set `bypass`?

2025-01-15 15:04 UTC, catriona-m commented
> > Thanks for updating this @feliperezende-barbosa - I have left one query inline but I can take another look once that is addressed. Thanks!
> 
> Hi @catriona-m, I cannot see any query inline. Could you please check this out? Thanks

Sorry about that @feliperezende-barbosa - not sure how it got lost, but Ive added the comment again now!

2025-01-16 01:00 UTC, feliperezende-barbosa commented on internal/services/cognitive/cognitive_account_resource.go
> +	} else {
I have fixed this. Following when creating the resource on portal or using an API, the default value is `AzureServices`.

2025-01-17 16:07 UTC, catriona-m commented on website/docs/r/cognitive_account.html.markdown
> +
There is no default value for `bypass` set in the schema currently, and if `bypass` can only be used when `kind` is `OpenAI`, then I don't think we should set a default for this property.

It would be good to add a note under the property about which kind is supported rather than having it in the description too.

```suggestion
* `bypass` - (Optional) Whether to allow trusted Azure Services to access the service. Possible values are `None` and `AzureServices`. 

-> **NOTE:** `bypass` can only be set when `kind` is set to `OpenAI `.

```

2025-01-17 18:36 UTC, feliperezende-barbosa commented on internal/services/cognitive/cognitive_account_resource.go
> +	}
Much better. Thanks

2025-01-28 16:12 UTC, catriona-m approved these changes
Thanks for making the requested changes on this @feliperezende-barbosa - LGTM!

2025-01-28 16:12 UTC, merged