`azurerm_kusto_cluster` - Fixes `virtual_network_configuration` block
hashicorp/terraform-provider-azurerm pull request #28249
Opened 2024-12-11 07:24 UTC by liuwuliuyun

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Affected Resource: `azurerm_kusto_cluster`

Background: https://github.com/hashicorp/terraform-provider-azurerm/pull/24733

The MS Kusto service team and the customer success team have informed me that deleting the `virtual_network_configuration` block in `azurerm_kusto_cluster` will trigger forceNew and delete all existing data in the Kusto cluster, which is not the intended outcome. I have been able to reproduce this issue on my local machine with assistance from the Kusto team. The expected behavior is that removing the `virtual_network_configuration` block should set it to the `Disabled` state.

 Changes
- Remove all forceNew labels from the subproperties of the `virtual_network_configuration` block in the `azurerm_kusto_cluster` resource.
- Include a custom diff function to prevent any changes to the subproperties of the `virtual_network_configuration` block, except for the creation and removal of the block itself.
- I have confirmed with the service team that setting the `virtual_network_configuration` block to the `Disabled` state will not change `public_network_access_enabled` to `false`, so I have removed this description from the document.
- I have also confirmed through local tests that the `State` can be changed from `Disabled` to `Enabled` again, so I have updated the documentation accordingly.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

![Screenshot 2024-12-11 143337](https://github.com/user-attachments/assets/c3fe051e-2c5b-4085-803f-c509e57cb2fc)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

`azurerm_kusto_cluster` - Fixes block `virtual_network_configuration` [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

2025-01-31 17:40 UTC, wyattfry commented on internal/services/kusto/kusto_cluster_resource.go
> +				if oldSubnetId != "" && newSubnetId != "" && oldSubnetId != newSubnetId {
```suggestion
				if oldSubnetId != newSubnetId {
```
I believe this condition can be simplified

2025-01-31 17:42 UTC, wyattfry commented on internal/services/kusto/kusto_cluster_resource.go
> +				if oldPublicIpId != "" && newPublicIpId != "" && oldPublicIpId != newPublicIpId {
```suggestion
				if oldPublicIpId != newPublicIpId {
```
Same here

2025-01-31 17:42 UTC, wyattfry commented on internal/services/kusto/kusto_cluster_resource.go
> +				if oldDataManagementPublicIpId != "" && newDataManagementPublicIpId != "" && oldDataManagementPublicIpId != newDataManagementPublicIpId {
```suggestion
				if oldDataManagementPublicIpId != newDataManagementPublicIpId {
```
And here

2025-01-31 17:44 UTC, wyattfry commented on website/docs/r/kusto_cluster.html.markdown
> +* `data_management_public_ip_id` - (Required) Data management's service public IP address resource id. This property could not be changed after the cluster is created.
```suggestion
* `data_management_public_ip_id` - (Required) Data management's service public IP address resource id. This property cannot be changed after the cluster is created.
```

2025-02-12 08:00 UTC, cosh commented on internal/services/kusto/kusto_cluster_resource.go
> +				if oldSubnetId != newSubnetId {
Good. So can you merge it?

2025-02-13 03:29 UTC, liuwuliuyun commented
Hi @wyattfry, I have reset this branch to the original commit. Let me know if you think there are still changes needed, and I am happy to assist with merging this PR.

2025-02-20 17:15 UTC, mbfrahry reviewed
Hey @liuwuliuyun, I can see the want to do this approach but unfortunately, erroring when someone wants to change a value isn't a good user experience. 

I'm not sure the best path forward though but I did want to talk through letting `State` be settable by the user. At that point, they can disable it when they want rather than us trying to figure out when to set it to Disabled.

2025-02-21 18:05 UTC, dhayalan85 commented
@liuwuliuyun I have followed the procedure https://discuss.hashicorp.com/t/removing-virtual-network-configuration-block-from-azurerm-kusto-cluster-forcing-the-resource-to-be-replaced/71723.

we followed for migrating our existing cluster. It appears that the current instructions could result in the deletion and recreation of our existing cluster, which we would like to avoid. 

Could you please check at your end to see if there’s a way to migrate our existing cluster without needing to delete it?

2025-03-06 02:08 UTC, liuwuliuyun commented
> Hey @liuwuliuyun, I can see the want to do this approach but unfortunately, erroring when someone wants to change a value isn't a good user experience.
> 
> I'm not sure the best path forward though but I did want to talk through letting `State` be settable by the user. At that point, they can disable it when they want rather than us trying to figure out when to set it to Disabled.

I agree, so let's treat this as a special case and let the user decide what `State` they want to set. However, this could be a breaking change. If you are okay with this, I will start working on adding this property to fix the issue permanently and prevent further trouble for everyone.

2025-03-06 02:23 UTC, liuwuliuyun commented
The current complex logic for changing `State` makes it difficult for developers and end users to maintain and could result in permanent data loss. Therefore, I highly suggest we implement the above changes and explicitly make this a property.

2025-03-06 07:56 UTC, liuwuliuyun commented
Rerun test result:
![Screenshot 2025-03-06 153906](https://github.com/user-attachments/assets/ed101e83-cabd-41c5-a374-99c7e11abcb6)

2025-03-06 08:01 UTC, liuwuliuyun commented
> @liuwuliuyun I have followed the procedure https://discuss.hashicorp.com/t/removing-virtual-network-configuration-block-from-azurerm-kusto-cluster-forcing-the-resource-to-be-replaced/71723.
> 
> we followed for migrating our existing cluster. It appears that the current instructions could result in the deletion and recreation of our existing cluster, which we would like to avoid.
> 
> Could you please check at your end to see if there’s a way to migrate our existing cluster without needing to delete it?

If this PR could get merged, you can use the latest AzureRM provider to set state="Disabled" to do this. I will do a test locally later to see if it works.

2025-04-03 22:40 UTC, mbfrahry requested changes
Hey @liuwuliuyun, apologies for missing the context that this block has been deprecated and we need to provide a path forward to move away from it. My suggestion to add `state` was wrong and we can instead modify that for the user instead of having the user modify it. I've added more suggestions inline

2025-04-03 22:40 UTC, mbfrahry commented on internal/services/kusto/kusto_cluster_resource.go
> +						"state": {
I missed the context that this block is deprecated so the orginal implementation of this was correct that we can Enable/Disable this for the user. Apologies for missing that context

2025-04-08 07:32 UTC, liuwuliuyun commented on internal/services/kusto/kusto_cluster_resource.go
>  				MaxItems: 1,
Okay, given that this PR is too old and most changes will be discarded, I will create a seperate PR later for adding the deprecation message.

2025-04-08 07:33 UTC, liuwuliuyun commented on internal/services/kusto/kusto_cluster_resource.go
> +						"state": {
Same as above, I will close this PR as the block is deprecated.

2025-04-08 07:38 UTC, liuwuliuyun commented
> @liuwuliuyun I have followed the procedure https://discuss.hashicorp.com/t/removing-virtual-network-configuration-block-from-azurerm-kusto-cluster-forcing-the-resource-to-be-replaced/71723.
> 
> we followed for migrating our existing cluster. It appears that the current instructions could result in the deletion and recreation of our existing cluster, which we would like to avoid.
> 
> Could you please check at your end to see if there’s a way to migrate our existing cluster without needing to delete it?

Sorry for missing your comment earlier. Given that some time has passed since the PR was raised, I suggest the following: 1. Check the latest document on this block and use the migration tool provided by the service team. 2. If you want to use Terraform to manage this by changing the `state` property, you could try the AzAPI provider to do this explicitly. 3. I will mark this block as deprecated and add a deprecation message in this block in a seperate PR.

2025-04-08 07:39 UTC, closed without merging