`azurerm_mssql_managed_instance` - support for properties `database_format` and `hybrid_secondary_usage`
hashicorp/terraform-provider-azurerm pull request #28248
Opened 2024-12-11 05:57 UTC by sinbai

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Support new properties `database_format` and `hybrid_secondary_usage`.

`database_format`: https://github.com/Azure/azure-rest-api-specs/blob/494d37ef9b1ab34ebab08c00da5675302594dc78/specification/sql/resource-manager/Microsoft.Sql/preview/2023-08-01-preview/ManagedInstances.json#L1322

`hybrid_secondary_usage`: https://github.com/Azure/azure-rest-api-specs/blob/494d37ef9b1ab34ebab08c00da5675302594dc78/specification/sql/resource-manager/Microsoft.Sql/preview/2023-08-01-preview/ManagedInstances.json#L1072

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```

PASS: TestAccMsSqlManagedInstance_hybridSecondaryUsage (1155.90s)
PASS: TestAccMsSqlManagedInstance_databaseFormat (5974.55s)
PASS: TestAccMsSqlManagedInstance_basic (7356.78s)
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_mssql_managed_instance` - support for properties `database_format` and `hybrid_secondary_usage`

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

2025-02-25 10:05 UTC, stephybun requested changes
One minor comment, otherwise this will be good to go

2025-02-25 10:05 UTC, stephybun commented on website/docs/r/mssql_managed_instance.html.markdown
> +~> **NOTE:** Changing `database_format` from `AlwaysUpToDate` to `SQLServer2022` forces a new SQL Managed Instance to be created.
```suggestion
~> **Note:** Changing `database_format` from `AlwaysUpToDate` to `SQLServer2022` forces a new SQL Managed Instance to be created.
```

2025-02-26 03:26 UTC, sinbai commented on website/docs/r/mssql_managed_instance.html.markdown
> +~> **NOTE:** Changing `database_format` from `AlwaysUpToDate` to `SQLServer2022` forces a new SQL Managed Instance to be created.
Fixed.

2025-02-26 03:33 UTC, sinbai commented
> One minor comment, otherwise this will be good to go

Hi @stephybun thanks for your feedback, I have fixed it. Could you please take another look?

2025-02-26 06:39 UTC, stephybun approved these changes
Thanks @sinbai LGTM 👍

2025-02-26 06:42 UTC, merged