`azurerm_postgresql_server` - deprecate `ssl_enforcement_enabled` and `ssl_minimal_tls_version_enforced` no longer accpets `TLSEnforcementDisabled`, `TLS1_0` or `TLS1_1` as a value in 5.0
hashicorp/terraform-provider-azurerm pull request #28247
Opened 2024-12-11 05:25 UTC by ziyeqf

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

As the [announcement](https://azure.microsoft.com/en-us/updates/v2/update-retirement-tls1-0-tls1-1-versions-azure-services/), update the documents and deprecate tls 1.0 and tls 1.1 in v5.0

Also, deprecate `ssl_enforcement_enabled` in 5.0 since it will always be `true` when `ssl_minimal_tls_version_enforced` is set to `1.2`

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

In progress

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_postgresql_server` - deprecate `ssl_enforcement_enabled` and `ssl_minimal_tls_version_enforced` no longer accpets `TLSEnforcementDisabled`, `TLS1_0` or `TLS1_1` as a value in 5.0 [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [x] Breaking Change

## Related Issue(s)

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2025-01-28 11:12 UTC, stephybun requested changes

2025-01-28 11:12 UTC, stephybun commented on internal/services/postgres/postgresql_server_resource.go
> +			Required:   true,
This probably wants to become `Optional` so users can begin removing it from their configs
```suggestion
			Optional:   true,
```

2025-01-28 11:12 UTC, stephybun commented on internal/services/postgres/postgresql_server_resource_test.go
> +	}
Since this property is deprecated, I think it's acceptable to have one test or template that still includes it (to check that it still works) but to remove it from all other test configurations.

Since we have it in the template I'd suggest removing it from this and all other test configurations below
```suggestion
```

2025-03-17 00:57 UTC, ziyeqf commented
kindly bubble this up

2025-06-04 05:07 UTC, ziyeqf commented
kindly bubble up

2025-06-19 18:04 UTC, sreallymatt requested changes
Hi @ziyeqf, I've left a couple minor comments inline

2025-06-19 18:04 UTC, sreallymatt commented on website/docs/r/postgresql_server.html.markdown
>  * `ssl_minimal_tls_version_enforced` - (Optional) The minimum TLS version to support on the sever. Possible values are `TLSEnforcementDisabled`, `TLS1_0`, `TLS1_1`, and `TLS1_2`. Defaults to `TLS1_2`
Since we've deprecated the other TLS values we should remove them from the doc.

Could you also remove the `ssl_enforcement_enabled` property from this doc both on ln89 and in the example?

```suggestion
* `ssl_minimal_tls_version_enforced` - (Optional) The minimum TLS version to support on the sever. The only possible value is `TLS1_2`. Defaults to `TLS1_2`.
```

2025-06-19 18:04 UTC, sreallymatt commented on website/docs/r/postgresql_server.html.markdown
> +~> **NOTE:** Azure Services will require TLS 1.2+ by August 2025, please see this [announcement](https://azure.microsoft.com/en-us/updates/v2/update-retirement-tls1-0-tls1-1-versions-azure-services/)
minor change as we're aiming to make all notes consistently titlecased

```suggestion
~> **Note:** Azure Services will require TLS 1.2+ by August 2025, please see this [announcement](https://azure.microsoft.com/en-us/updates/v2/update-retirement-tls1-0-tls1-1-versions-azure-services/) for more information.
```

2025-06-19 18:04 UTC, sreallymatt commented on internal/services/postgres/postgresql_server_resource.go
> +			Deprecated: "The `ssl_enforcement_enabled` property is deprecated as Azure services will require TLS1.2+ to connect.",
We should add the major version in which this property will be removed

```suggestion
			Deprecated: "The `ssl_enforcement_enabled` property is deprecated and will be removed in v5.0 of the AzureRM provider as Azure services will require TLS1.2+ to connect.",
```

2025-07-03 18:10 UTC, sreallymatt commented on website/docs/r/postgresql_server.html.markdown
> +* `ssl_minimal_tls_version_enforced` - (Optional) The minimum TLS version to support on the sever. Possible values are `TLSEnforcementDisabled` and `TLS1_2`. Defaults to `TLS1_2`.
`TLSEnforcementDisabled ` is not an accepted value in the schema

```suggestion
* `ssl_minimal_tls_version_enforced` - (Optional) The minimum TLS version to support on the sever. The only possible value is `TLS1_2`. Defaults to `TLS1_2`.
```

2025-07-03 18:12 UTC, sreallymatt commented on website/docs/r/postgresql_server.html.markdown
>  * `ssl_minimal_tls_version_enforced` - (Optional) The minimum TLS version to support on the sever. Possible values are `TLSEnforcementDisabled`, `TLS1_0`, `TLS1_1`, and `TLS1_2`. Defaults to `TLS1_2`
`` Could you also remove the `ssl_enforcement_enabled property` from this doc both on ln89 and in the example? ``

Is still outstanding, could you remove it from the example?

2025-07-07 16:48 UTC, sreallymatt commented on website/docs/r/postgresql_server.html.markdown
> +~> **Note:** Azure Services will require TLS 1.2+ by August 2025, please see this [announcement](https://azure.microsoft.com/en-us/updates/v2/update-retirement-tls1-0-tls1-1-versions-azure-services/)
Sorry, missed this earlier, but looks like there's a typo that's been here for a while, we might as well fix it while we're here (`sever` -> `server`) and a minor change to the note + note spacing

```suggestion
* `ssl_minimal_tls_version_enforced` - (Optional) The minimum TLS version to support on the server. The only possible value is `TLS1_2`.  Defaults to `TLS1_2`.

~> **Note:** Azure Services will require TLS 1.2+ by August 2025, please see this [announcement](https://azure.microsoft.com/en-us/updates/v2/update-retirement-tls1-0-tls1-1-versions-azure-services/) for more information.
```

2025-07-21 03:25 UTC, ziyeqf commented
I think this PR is not required since the resource is being deprecated in v5.0.

2025-07-21 03:25 UTC, closed without merging