[Enhancement:] azurerm_cdn_frontdoor_profile - add support for the identity property
hashicorp/terraform-provider-azurerm pull request #28281
Opened 2024-12-13 22:49 UTC by WodansSon

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

The purpose for this PR are as follows:

* add support for the `identity` field in the the AFD Profile resource

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [X] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [X] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [X] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_cdn_frontdoor_profile` - add support for the `identity` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [X] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #20289

Supersedes: #28068

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2025-01-08 06:36 UTC, jackofallops requested changes
Thanks @WodansSon - just a couple minor comments on the tests, but otherwise LGTM. I'll get the tests run as soon as the changes below are in and then we should be good to go.

2025-01-08 06:36 UTC, jackofallops commented on internal/services/cdn/cdn_frontdoor_profile_resource_test.go
> +	})
Missed import step here?
```suggestion
		data.ImportStep(),
		{
			Config: r.complete(data),
			Check: acceptance.ComposeTestCheckFunc(
				check.That(data.ResourceName).ExistsInAzure(r),
				check.That(data.ResourceName).Key("response_timeout_seconds").HasValue("240"),
			),
		},
		data.ImportStep(),
	})
```

2025-01-08 06:36 UTC, jackofallops commented on internal/services/cdn/cdn_frontdoor_profile_resource_test.go
> +	})
```suggestion
		data.ImportStep(),
		{
			Config: r.complete(data),
			Check: acceptance.ComposeTestCheckFunc(
				check.That(data.ResourceName).ExistsInAzure(r),
				check.That(data.ResourceName).Key("response_timeout_seconds").HasValue("240"),
			),
		},
		data.ImportStep(),
	})
```

2025-01-08 09:23 UTC, pie-r commented
@WodansSon looking forward to seeing this merged ;)

2025-01-09 03:49 UTC, WodansSon commented on internal/services/cdn/cdn_frontdoor_profile_resource_test.go
> +	})
Fixed.

2025-01-09 03:50 UTC, WodansSon commented on internal/services/cdn/cdn_frontdoor_profile_resource_test.go
> +	})
Fixed.

2025-01-09 12:03 UTC, jackofallops commented
Tests all look good 👍 

![image](https://github.com/user-attachments/assets/9d0a35e1-4345-4a06-bcef-ca7f3f655afc)

2025-01-09 12:04 UTC, jackofallops approved these changes
Thanks @WodansSon - LGTM now 👍

2025-01-09 12:08 UTC, merged