Update the redisenterprise sdk to 2024-10-01 to update SKU list
hashicorp/terraform-provider-azurerm pull request #28280
Opened 2024-12-13 20:46 UTC by yfvham

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Update teh redisenterprise sdk to 2024-10-01. This resolves the missing skus (namely E1). 

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_redis_enterprise_cluster` - support for the new skus [GH-27080]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27080

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-12-18 15:57 UTC, catriona-m requested changes
Hi @yfvham thanks for submitting this. This looks ok to me, but it seems the build is failing for some reason - could you try running `go mod vendor` on this and pushing again? Thanks!

2024-12-18 17:45 UTC, yfvham commented
> Hi @yfvham thanks for submitting this. This looks ok to me, but it seems the build is failing for some reason - could you try running `go mod vendor` on this and pushing again? Thanks!

This has been completed.

2025-01-08 15:24 UTC, yfvham commented
> Hi @yfvham thanks for submitting this. This looks ok to me, but it seems the build is failing for some reason - could you try running `go mod vendor` on this and pushing again? Thanks!

@catriona-m This has been completed but I am struggling to find the line the review was on. Thank you for the help.

2025-01-08 16:02 UTC, catriona-m approved these changes
Thanks for updating this @yfvham LGTM!

2025-01-08 16:03 UTC, merged