[Dependencies:] `azurerm_cdn_frontdoor_rule`, `azurerm_cdn_frontdoor_ruleset` and `cdn_frontdoor_rule_actions` - upgrade to resources to `2024-02-01` API to enable support for the JS Challenge field
hashicorp/terraform-provider-azurerm pull request #28308
Opened 2024-12-17 07:46 UTC by WodansSon

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

* `cdn_frontdoor_rule_actions` - upgrade resource to `2024-02-01/rules` API
* `cdn_frontdoor_rule_actions` - upgrade resource to `2024-02-01/origins` API
* `azurerm_cdn_frontdoor_rule` - upgrade resource to `2024-02-01/rules` API
* `azurerm_cdn_frontdoor_rule` - upgrade resource to `2024-02-01/rulesets` API
* `azurerm_cdn_frontdoor_ruleset` - upgrade resource to `2024-02-01/rulesets` API

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2025-01-31 11:48 UTC, jackofallops requested changes
Thanks @WodansSon - Handful of fairly minor stuff to check if you could. Also, I can see you rant the CI tests, and it looks like there are some failures introduced if you can check those over?

Thanks!

2025-01-31 11:48 UTC, jackofallops commented on internal/services/cdn/frontdoorruleconditions/cdn_frontdoor_rule_conditions.go
> +	// NOTE: There are now 14 different "Any" operators in the new API, however they are all the same so I am just hardcoding this here now...
Can you open an issue detailing this so it's tracked somewhere along with what we're planning to change it to if this is just for now?

2025-01-31 11:48 UTC, jackofallops commented on internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go
> +		originGroup, err := origins.ParseOriginIDInsensitively(*override.OriginGroup.Id)
Is this the correct ID type here? origin vs originGroup?

2025-02-01 05:51 UTC, WodansSon commented on internal/services/cdn/cdn_frontdoor_firewall_policy_resource_test.go
>  		return nil, fmt.Errorf("retrieving %s: %+v", id, err)
Fixed.

2025-02-01 05:59 UTC, WodansSon commented on internal/services/cdn/cdn_frontdoor_rule_resource.go
> +		if response.WasNotFound(result.HttpResponse) {
Fixed.

2025-02-01 06:02 UTC, WodansSon commented on internal/services/cdn/cdn_frontdoor_rule_resource.go
> +			d.Set("cdn_frontdoor_rule_set_id", ruleSet.ID())
Fixed.

2025-02-01 06:04 UTC, WodansSon commented on internal/services/cdn/cdn_frontdoor_rule_resource.go
> +			d.Set("cdn_frontdoor_rule_set_name", ruleSet.RuleSetName)
Fixed.

2025-02-01 06:06 UTC, WodansSon commented on internal/services/cdn/cdn_frontdoor_rule_resource.go
> +		if deliveryRuleCondition.DeliveryRuleCondition().Name == c.ClientPort.Name {
I don't believe a `strings.Equalfold()` is needed here as both of the values are being pulled directly from the SDK. So if these are different we have much bigger fish to fry. 🙂

2025-02-01 06:09 UTC, WodansSon commented on internal/services/cdn/cdn_frontdoor_rule_resource_test.go
>  		}
Fixed.

2025-02-01 06:12 UTC, WodansSon commented on internal/services/cdn/cdn_frontdoor_rule_set_resource.go
> +	// func NewRuleSetID(subscriptionId string, resourceGroupName string, profileName string, ruleSetName string)
Indeed. 🤣

2025-02-01 06:17 UTC, WodansSon commented on internal/services/cdn/cdn_frontdoor_rule_set_resource.go
>  	if d.IsNewResource() {
Fixed.

2025-02-01 06:20 UTC, WodansSon commented on internal/services/cdn/cdn_frontdoor_rule_set_resource.go
> +		if response.WasNotFound(resp.HttpResponse) {
Fixed.

2025-02-01 06:22 UTC, WodansSon commented on internal/services/cdn/cdn_frontdoor_rule_set_resource_test.go
>  		return nil, fmt.Errorf("retrieving %s: %+v", id, err)
Fixed.

2025-02-01 06:33 UTC, WodansSon commented on internal/services/cdn/cdn_frontdoor_shared_schema.go
> +	"github.com/hashicorp/go-azure-sdk/resource-manager/cdn/2024-02-01/rules"
No, I was just attempting to make the API version consistent across all of the resources. I have updated all references to the `rules` API to now be `.../cdn/2024-09-01/rules`. Nice catch... 🙈

2025-02-01 07:40 UTC, WodansSon commented on internal/services/cdn/frontdoorruleconditions/cdn_frontdoor_rule_conditions.go
> +	// NOTE: There are now 14 different "Any" operators in the new API, however they are all the same so I am just hardcoding this here now...
I don't believe an issue is required here, these fields were added due to the swagger issue opened by HashiCorp to allow the Pandora SDK to build the API correctly. Every `condition` now has it's own `Any` field (e.g., `ClientPortOperatorAny`, `CookiesOperatorAny`, `HostNameOperatorAny`, etc.) So I believe hardcoding this value is acceptable here as this function is a general function that will be called by all `conditions`.

2025-02-02 07:03 UTC, WodansSon commented on internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go
> +		originGroup, err := origins.ParseOriginIDInsensitively(*override.OriginGroup.Id)
DOH! No that is not, totally missed that... 🙉 Fixed.

2025-02-03 12:45 UTC, jackofallops approved these changes
Thanks @WodansSon for the updates, this LGTM now 👍 
And the tests are looking good too
![image](https://github.com/user-attachments/assets/5ace46d8-4aa3-43dd-963d-d32dc574de77)

2025-02-03 13:15 UTC, merged