azurerm_container_app – support for termination_grace_period_seconds
hashicorp/terraform-provider-azurerm pull request #28307
Opened 2024-12-17 06:49 UTC by CheeseMite

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Add support for `termination_grace_period_seconds` property of the `azurerm_container_app` resource

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Change Log

* `azurerm_container_app` - support for the `termination_grace_period_seconds` property

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-12-18 16:15 UTC, catriona-m requested changes
Hi @CheeseMite thanks for submitting this. This is looking good but it looks like there is a linting error - could you run `make terrafmt` on the test file which should hopefully fix this? Thanks!

2025-01-08 17:30 UTC, CheeseMite commented on internal/services/containerapps/helpers/container_apps.go
> +				},
sure, the default value is 30 seconds according to the [Application lifecycle management in Azure Container Apps
](https://learn.microsoft.com/en-us/azure/container-apps/application-lifecycle-management#shutdown). Should I set this as default?

2025-01-14 17:25 UTC, catriona-m commented on internal/services/containerapps/helpers/container_apps.go
> +				},
I had look into this and it seems it can be valid for this to be nil, so we can leave this as it is

2025-01-14 17:29 UTC, catriona-m requested changes
Thanks @CheeseMite - I just noticed this needs a different docs file, but otherwise this is looking good, thanks!

2025-01-14 17:29 UTC, catriona-m commented on website/docs/d/container_app.html.markdown
this docs file is for the the datasource, could we move this change to website/docs/r/container_app.html.markdown?

2025-01-14 22:08 UTC, CheeseMite commented on website/docs/d/container_app.html.markdown
added to the resource doc. No need to remove from the data source docs as both use the same schema

2025-01-15 16:32 UTC, catriona-m approved these changes
Thanks for updating the resource doc @CheeseMite - LGTM!

2025-01-15 16:33 UTC, merged