wip
hashicorp/terraform-provider-azurerm pull request #28319
Opened 2024-12-17 19:06 UTC by wyattfry

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2024-12-19 19:02 UTC, wyattfry commented on internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go
> +		"identity": commonschema.SystemAssignedUserAssignedIdentityOptional(),
This the crux of the identity bug fix, `SystemOrUserAssignedIdentityOptional` is XOR, exclusive or. `SystemAssignedUserAssignedIdentityOption` is true OR, i.e. one, the other, or both.

2024-12-21 03:00 UTC, wyattfry commented
1 failing acceptance test, due to timeout, rerunning that one test
<img width="265" alt="image" src="https://github.com/user-attachments/assets/67e0a5f9-2d97-4f82-9b60-26240f24e693" />
```
        API Response:
        ----[start]----
        {"name":"31930286-4dff-48ff-a098-15853e0712d0","status":"Failed","startTime":"2024-12-20T17:23:44.937Z","error":{"code":"ConflictingServerOperation","message":"Server
        'acctestsqlserver241220165729791029' is busy with another operation. Please
        try your operation later."}}
        -----[end]-----
--- FAIL: TestAccMsSqlManagedInstance_identity (4482.45s)
```

2025-01-02 14:58 UTC, wyattfry commented on internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go
> +					SubnetId:                         pointer.To(state.SubnetId),
because subnet_id has since become mutable (idk about the admin creds), it must now be included in resource updates.

2025-01-02 15:03 UTC, wyattfry commented
> 1 failing acceptance test, due to timeout, rerunning that one test <img alt="image" width="265" src="https://private-user-images.githubusercontent.com/23287561/397900913-67e0a5f9-2d97-4f82-9b60-26240f24e693.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MzA0NDgsIm5iZiI6MTczNTgzMDE0OCwicGF0aCI6Ii8yMzI4NzU2MS8zOTc5MDA5MTMtNjdlMGE1ZjktMmQ5Ny00ZjgyLTliNjAtMjYyNDBmMjRlNjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDE1MDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0N2Y5MzhhYWJkMTc4YWYxMzMwN2IxYTRlZTk1M2RmYjIyMjUzZmJlNDM4MWZiZmJjMTMzZDM2M2JhN2QzOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VoyTCKWO4BUsj2sHNireRULfifx5ofSXZsDLXg_nqV8">
> 
> ```
>         API Response:
>         ----[start]----
>         {"name":"31930286-4dff-48ff-a098-15853e0712d0","status":"Failed","startTime":"2024-12-20T17:23:44.937Z","error":{"code":"ConflictingServerOperation","message":"Server
>         'acctestsqlserver241220165729791029' is busy with another operation. Please
>         try your operation later."}}
>         -----[end]-----
> --- FAIL: TestAccMsSqlManagedInstance_identity (4482.45s)
> ```

Test succeeded on the first retry
![image](https://github.com/user-attachments/assets/18879efa-fb08-4bed-9b62-522a8de21b95)

2025-01-02 15:57 UTC, catriona-m requested changes
Thanks @wyattfry - I left a couple of minor comments inline but otherwise this is looking pretty good 😄

2025-01-02 15:57 UTC, catriona-m commented on internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go
> -			ForceNew:     true,
could we update the docs to reflect this too?

2025-01-02 15:57 UTC, catriona-m commented on internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go
> +		"identity": commonschema.SystemAssignedUserAssignedIdentityOptional(),
the docs may need updating for this too

2025-01-02 15:57 UTC, catriona-m commented on internal/services/mssqlmanagedinstance/mssql_managed_instance_resource_test.go
> +  name                 = "subnet2-%[2]d"
could we prefix this resource name with `acctest`?

```suggestion
  name                 = "acctestsubnet2-%[2]d"
```

2025-01-02 17:27 UTC, wyattfry commented on internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go
> -			ForceNew:     true,
certainly

2025-01-02 17:27 UTC, wyattfry commented on internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go
> +		"identity": commonschema.SystemAssignedUserAssignedIdentityOptional(),
roger

2025-01-02 17:46 UTC, wyattfry commented on internal/services/mssqlmanagedinstance/mssql_managed_instance_resource_test.go
> +  name                 = "subnet2-%[2]d"
certainly

2025-01-03 10:45 UTC, catriona-m approved these changes
Thanks @wyattfry LGTM ✨

2025-01-03 14:55 UTC, merged