`azurerm_orchestrated_virtual_machine_scale_set` - support `upgrade_mode` and `rolling_upgrade_policy`
hashicorp/terraform-provider-azurerm pull request #28354
Opened 2024-12-20 07:35 UTC by ms-zhenhua

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Support [UpgradePolicy](https://github.com/Azure/azure-rest-api-specs/blob/1cb540f95dc8993540918943a75d02ebfeeda0ca/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2024-07-01/virtualMachineScaleSet.json#L3897) for Flex VMSS.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [n/a] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

--- PASS: TestAccOrchestratedVirtualMachineScaleSet_otherUpgradePolicyErrorValidation (28.76s)
--- PASS: TestAccOrchestratedVirtualMachineScaleSet_otherRollingUpgrade (308.14s)
--- PASS: TestAccOrchestratedVirtualMachineScaleSet_otherUpgradePolicy (349.25s)
PASS

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_orchestrated_virtual_machine_scale_set` - support `upgrade_mode` and `rolling_upgrade_policy` [GH-28270]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/28270

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2025-02-27 19:45 UTC, mimckitt commented
@rcskosir  anything we can do to get a reviewer on this PR :)

2025-03-06 17:05 UTC, sreallymatt reviewed
Hi @ms-zhenhua, I've left a couple comments inline for you to review, thanks!

2025-03-06 17:05 UTC, sreallymatt commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +				ForceNew: true,
Are we sure this is `ForceNew` and are we sure about the default being the same in all configurations? (For example, in `virtual_machine_scale_set_resource.go` this is not `ForceNew`)

Should this be `Required` in 5.0?

2025-03-06 17:05 UTC, sreallymatt commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +			"rolling_upgrade_policy": VirtualMachineScaleSetRollingUpgradePolicySchema(),
Could you clarify why this is not using the same schema as the `rolling_upgrade_policy` property in `azurerm_virtual_machine_scale_set`?

2025-03-06 19:32 UTC, sreallymatt requested changes
Hi @ms-zhenhua, I've gone back over this PR and have left some comments, there was also a panic when I ran the tests for this PR. Would you mind taking a look?

2025-03-06 19:32 UTC, sreallymatt commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +					_, hasHealthExtension, err = expandOrchestratedVirtualMachineScaleSetExtensions(v.(*pluginsdk.Set).List())
When running the tests there was a panic that seems like it may be related to this call to `expandOrchestratedVirtualMachineScaleSetExtensions`

The test that failed: `TestAccOrchestratedVirtualMachineScaleSet_extensionProtectedSettingsFromKeyVault`

Could you investigate?

2025-03-06 19:32 UTC, sreallymatt commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +					return fmt.Errorf("a health extension must be specified when `upgrade_mode` is set to Rolling")
Minor suggestion to stay consistent with how we usually format error messages, will require an update to the test on ln313 of `orchestrated_virtual_machine_scale_set_resource_other_test.go` as well

```suggestion
					return fmt.Errorf("a health extension must be specified when `upgrade_mode` is set to `Rolling`")
```

2025-03-06 19:32 UTC, sreallymatt commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +	rollingUpgradePolicy, err := ExpandVirtualMachineScaleSetRollingUpgradePolicy(rollingUpgradePolicyRaw, len(zones) > 0, false)
Since it doesn't look like `rollingUpgradePolicyRaw` is used elsewhere in this function we can simplify this

```suggestion
	rollingUpgradePolicy, err := ExpandVirtualMachineScaleSetRollingUpgradePolicy(d.Get("rolling_upgrade_policy").([]interface{}), len(zones) > 0, false)
```

2025-03-06 19:32 UTC, sreallymatt commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +		return err
Could we wrap this error?

```suggestion
		return fmt.Errorf("expanding `rolling_upgrade_policy`: %+v", err)
```

2025-03-06 19:32 UTC, sreallymatt commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +		}
I think we could simplify this to the below, what do you think?

```suggestion
		if existing.Model.Properties.UpgradePolicy != nil {
			upgradePolicy = *existing.Model.Properties.UpgradePolicy
		}
		upgradePolicy.Mode = pointer.To(virtualmachinescalesets.UpgradeMode(d.Get("upgrade_mode").(string)))
```

2025-03-06 19:32 UTC, sreallymatt commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +		rollingUpgradePolicy, err := ExpandVirtualMachineScaleSetRollingUpgradePolicy(rollingRaw, len(zones) > 0, false)
Since we don't seem to be using the zones variable anywhere after this can we simplify this to the below, this would also avoid having the variable collide with the package name

```suggestion
		rollingUpgradePolicy, err := ExpandVirtualMachineScaleSetRollingUpgradePolicy(rollingRaw, len(zones.ExpandUntyped(d.Get("zones").(*schema.Set).List())) > 0, false)
```

2025-03-06 19:32 UTC, sreallymatt commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +			return err
could we wrap this error message?
```suggestion
			return fmt.Errorf("expanding `rolling_upgrade_policy`: %+v", err)
```

2025-03-06 19:32 UTC, sreallymatt commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource_other_test.go
> +			ExpectError: regexp.MustCompile("a health extension must be specified when `upgrade_mode` is set to Rolling"),
```suggestion
			ExpectError: regexp.MustCompile("a health extension must be specified when `upgrade_mode` is set to `Rolling`"),
```

2025-03-06 19:32 UTC, sreallymatt commented on website/docs/r/orchestrated_virtual_machine_scale_set.html.markdown
> +* `upgrade_mode` - (Optional) Specifies how Upgrades (e.g. changing the Image/SKU) should be performed to Virtual Machine Instances. Possible values are `Automatic`, `Manual` and `Rolling`. Defaults
```suggestion
* `upgrade_mode` - (Optional) Specifies how upgrades (e.g. changing the Image/SKU) should be performed to Virtual Machine Instances. Possible values are `Automatic`, `Manual` and `Rolling`. Defaults to `Manual`. Changing this forces a new resource to be created.
```

2025-03-06 19:32 UTC, sreallymatt commented on website/docs/r/orchestrated_virtual_machine_scale_set.html.markdown
> +* `rolling_upgrade_policy` - (Optional) A `rolling_upgrade_policy` block as defined below. This is Required and can only be specified when `upgrade_mode` is set to `Automatic` or `Rolling`. Changing
I think this might make it more clear that this cannot be specified only when `upgrade_mode` is manual and required otherwise?

```suggestion
* `rolling_upgrade_policy` - (Optional) A `rolling_upgrade_policy` block as defined below. This is Required when `upgrade_mode` is set to `Automatic` or `Rolling` and cannot be specified when `upgrade_mode` is set to `Manual`. Changing this forces a new resource to be created.
```

2025-03-06 19:32 UTC, sreallymatt commented on website/docs/r/orchestrated_virtual_machine_scale_set.html.markdown
> +* `pause_time_between_batches` - (Required) The wait time between completing the update for all virtual machines in one batch and starting the next batch. The time duration should be specified in ISO
```suggestion
* `pause_time_between_batches` - (Required) The wait time between completing the update for all virtual machines in one batch and starting the next batch. The time duration should be specified in ISO 8601 duration format.
```

2025-03-07 02:39 UTC, ms-zhenhua commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +					_, hasHealthExtension, err = expandOrchestratedVirtualMachineScaleSetExtensions(v.(*pluginsdk.Set).List())
apologies, my mistake.  I had intended to make this validation take effect in `plan` stage. However, the value of `expandProtectedSettingsFromKeyVaultVMSS` does not exist in `plan` stage. Seems it is unsafe to check non-primitive type of attributes in `plan` stage, I will remove this validation. Thank you for pointing out this issue.

2025-03-17 07:27 UTC, ms-zhenhua commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +					return fmt.Errorf("a health extension must be specified when `upgrade_mode` is set to Rolling")
updated. The new code is in `resourceOrchestratedVirtualMachineScaleSetCreate` method.

2025-03-17 07:28 UTC, ms-zhenhua commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +	rollingUpgradePolicy, err := ExpandVirtualMachineScaleSetRollingUpgradePolicy(rollingUpgradePolicyRaw, len(zones) > 0, false)
updated. Thanks.

2025-03-17 07:28 UTC, ms-zhenhua commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +		return err
updated. Thanks

2025-03-17 07:29 UTC, ms-zhenhua commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +		}
updated. Thanks.

2025-03-17 07:29 UTC, ms-zhenhua commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +		rollingUpgradePolicy, err := ExpandVirtualMachineScaleSetRollingUpgradePolicy(rollingRaw, len(zones) > 0, false)
updated. Thanks.

2025-03-17 07:30 UTC, ms-zhenhua commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +			return err
updated. Thanks.

2025-03-17 07:30 UTC, ms-zhenhua commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource_other_test.go
> +			ExpectError: regexp.MustCompile("a health extension must be specified when `upgrade_mode` is set to Rolling"),
updated. Thanks.

2025-03-17 07:30 UTC, ms-zhenhua commented on website/docs/r/orchestrated_virtual_machine_scale_set.html.markdown
> +* `upgrade_mode` - (Optional) Specifies how Upgrades (e.g. changing the Image/SKU) should be performed to Virtual Machine Instances. Possible values are `Automatic`, `Manual` and `Rolling`. Defaults
updated. Thanks.

2025-03-17 07:32 UTC, ms-zhenhua commented on website/docs/r/orchestrated_virtual_machine_scale_set.html.markdown
> +* `rolling_upgrade_policy` - (Optional) A `rolling_upgrade_policy` block as defined below. This is Required and can only be specified when `upgrade_mode` is set to `Automatic` or `Rolling`. Changing
since it is not required by `Automatic`, I updated it as below:

* `rolling_upgrade_policy` - (Optional) A `rolling_upgrade_policy` block as defined below. This is Required when `upgrade_mode` is set to `Rolling` and cannot be specified when `upgrade_mode` is set to `Manual`. Changing this forces a new resource to be created.

2025-03-17 07:32 UTC, ms-zhenhua commented on website/docs/r/orchestrated_virtual_machine_scale_set.html.markdown
> +* `pause_time_between_batches` - (Required) The wait time between completing the update for all virtual machines in one batch and starting the next batch. The time duration should be specified in ISO
updated. Thanks.

2025-03-17 07:45 UTC, ms-zhenhua commented
Hi @sreallymatt ,

Thank you for the review. I have resolved all the comments. Besides, I set a default value for `upgrade_mode` in `read` method. The reason is the API response will not take `upgrade_mode` if the request does not have `VirtualMachineProfile`, which is by design of Azure backend service. Could you please have another review? Thanks.

2025-03-31 19:44 UTC, sreallymatt reviewed
Thanks for making those changes @ms-zhenhua, I left one comment on the CustomizeDiff for your consideration

2025-03-31 19:44 UTC, sreallymatt commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +				}
I think this might be a little more clear if we're explicit about what we're checking for rather than checking for the inverse of `upgradeMode == virtualmachinescalesets.UpgradeModeAutomatic || upgradeMode == virtualmachinescalesets.UpgradeModeRolling`, WDYT?

```suggestion
				if upgradeMode == virtualmachinescalesets.UpgradeModeManual && len(rollingUpgradePolicyRaw) > 0 {
					return fmt.Errorf("a `rolling_upgrade_policy` block cannot be specified when `upgrade_mode` is set to `%s`", string(upgradeMode))
				}
				
				if upgradeMode == virtualmachinescalesets.UpgradeModeRolling && len(rollingUpgradePolicyRaw) == 0 {
					return fmt.Errorf("a `rolling_upgrade_policy` block must be specified when `upgrade_mode` is set to `%s`", string(upgradeMode))
				}
```

2025-04-01 02:58 UTC, ms-zhenhua commented on internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go
> +				}
That makes sense. Updated.

2025-04-01 13:48 UTC, sreallymatt approved these changes
Thanks @ms-zhenhua, LGTM!

2025-04-01 13:49 UTC, merged