`azurerm_route_server` - Add support for `hub_routing_preference` property
hashicorp/terraform-provider-azurerm pull request #28363
Opened 2024-12-21 19:29 UTC by bubbletroubles

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

- Add support for the `hub_routing_preference` property in `azurerm_route_server`.
- Updated docs to sort properties in alphabetical order, and added new docs for the `hub_routing_preference` property.

Here are the references for this feature 
- https://learn.microsoft.com/en-us/azure/virtual-wan/about-virtual-hub-routing-preference
- https://learn.microsoft.com/en-us/rest/api/virtualwan/virtual-hubs/create-or-update?view=rest-virtualwan-2024-05-01&tabs=HTTP#hubroutingpreference

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [X] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [X] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [X] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_route_server` - support for the `hub_routing_preference` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [X] Enhancement
- [ ] Breaking Change

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2025-01-07 13:37 UTC, stephybun requested changes

2025-01-07 13:37 UTC, stephybun commented on internal/services/network/route_server_resource.go
> +				Computed: true,
Can we set a default value here instead of `Computed`? Or does the default value depend on the route server configuration?

2025-01-07 13:37 UTC, stephybun commented on internal/services/network/route_server_resource.go
> +			HubRoutingPreference:       (*virtualwans.HubRoutingPreference)(pointer.To(d.Get("hub_routing_preference").(string))),
Can we change this to 
```suggestion
			HubRoutingPreference:       pointer.To(virtualwans.HubRoutingPreference(d.Get("hub_routing_preference").(string))),
```

2025-01-07 13:37 UTC, stephybun commented on internal/services/network/route_server_resource.go
> +			payload.Properties.HubRoutingPreference = (*virtualwans.HubRoutingPreference)(pointer.To(v.(string)))
```suggestion
			payload.Properties.HubRoutingPreference = pointer.To(virtualwans.HubRoutingPreference(v.(string))),
```

2025-01-07 13:37 UTC, stephybun commented on internal/services/network/route_server_resource.go
> +			payload.Properties.HubRoutingPreference = nil
Does this reset the preference back to a default?

2025-01-07 13:37 UTC, stephybun commented on internal/services/network/route_server_resource.go
> +			}
This can be simplified to 
```suggestion
			d.Set("hub_routing_preference", pointer.From(props.HubRoutingPreference))
```

2025-01-07 13:37 UTC, stephybun commented on internal/services/network/route_server_resource_test.go
> +			),
Can we add another step updating the config back to `basic` to test the behaviour on line 228
https://github.com/hashicorp/terraform-provider-azurerm/blob/83444612400941ff4f4aa167eff17e29799e5f46/internal/services/network/route_server_resource.go#L228

2025-01-07 13:37 UTC, stephybun commented on website/docs/r/route_server.html.markdown
> +* `subnet_id` - (Required) The ID of the Subnet that the Route Server will reside. Changing this forces a new resource to be created.
We appreciate the alphabetical ordering here, but the pattern we try to follow in the docs is to list all `Required` properties first in alphabetical order (except for name, resource group, location), then all `Optional` properties in alphabetical order.

2025-01-07 19:41 UTC, bubbletroubles commented on website/docs/r/route_server.html.markdown
> +* `subnet_id` - (Required) The ID of the Subnet that the Route Server will reside. Changing this forces a new resource to be created.
Thanks - I was following the guidance [Guide: Extending a Resource - Docs](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/guide-new-fields-to-resource.md#docs) which says to use the same order as the Schema, which is alphabetical [Guide: Extending a Resource - Schema](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/guide-new-fields-to-resource.md#schema).

I'll update this PR as per your suggestion.

2025-01-07 20:03 UTC, bubbletroubles commented on internal/services/network/route_server_resource.go
> +				Computed: true,
When I didn't have this set to Computed, the tests were failing. The issue was

- It would set the property (e.g. `hub_routing_preference = "ASPath"`)
- It would run `terraform apply`
- The property would be set correctly - so far so good
- It would then remove the `hub_routing_preference` property from the test config
- It then run `terraform plan`
- It says it will perform the following
```
          # azurerm_route_server.test will be updated in-place
          ~ resource "azurerm_route_server" "test" {
              - hub_routing_preference           = "ExpressRoute" -> null
                id                               = "<resource-id>"
                name                             = "acctestrs-241221104344729540"
                # (9 unchanged attributes hidden)
            }
```
- But I get the error ` testcase.go:173: Step 1/6 error: After applying this test step, the non-refresh plan was not empty.`

The way the API works is that it always needs to be set as either `ExpressRoute`, `ASPath` or `VPNGateway`. The default is ExpressRoute [as per the MS Docs](https://learn.microsoft.com/en-us/azure/virtual-wan/about-virtual-hub-routing-preference#:~:text=ExpressRoute%20(This%20is%20the%20default%20setting)), but we can't assume its ExpressRoute as customers may have changed it manually before support for the property exists. 

In this scenario, is `Computed` appropriate? Or is there a better way to handle it?

2025-01-07 21:59 UTC, bubbletroubles commented on internal/services/network/route_server_resource.go
> +			payload.Properties.HubRoutingPreference = nil
It will leave the value as it was last set and the `hub_routing_preference` will no longer be managed via terraform. Is this the best way to achieve this, or is there a more preferred way?

2025-01-07 22:56 UTC, bubbletroubles commented
@stephybun thanks for the review. I've updated the code as per your suggestions and added the extra test. There are still a couple of open comments - let me know how you want them addressed.

Updated tests are passing - results are [here](https://dev.azure.com/bubbletroubles/terraform/_build/results?buildId=155&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=33e5d3ec-87e7-5f80-0281-074c6962cb44)

2025-01-07 22:57 UTC, bubbletroubles commented on internal/services/network/route_server_resource_test.go
> +			),
Updated the test to include config back to basic.

2025-02-04 10:07 UTC, stephybun commented on internal/services/network/route_server_resource.go
> +				Computed: true,
I understand the desire to make the introduction of this property accommodate users that have had to use workarounds to set this property outside of Terraform, but if there is a publicly documented as well as a behavioural default for a property like we do in this case then we should be setting that as the default over setting it to computed.

Computed is typically reserved for behaviours where the default value changes dependent on the resource configuration/tenant/location etc.

2025-02-05 22:57 UTC, bubbletroubles commented
Hi @stephybun I've updated the PR to remove the computed property and fix the update logic. It's ready for you to re-review.

Test are passing - https://dev.azure.com/bubbletroubles/terraform/_build/results?buildId=177&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=33e5d3ec-87e7-5f80-0281-074c6962cb44

2025-02-05 22:59 UTC, bubbletroubles commented on internal/services/network/route_server_resource.go
> +				Computed: true,
Thanks stephybun - this has been updated in the latest commits. Ready for you to review :)

2025-02-05 23:00 UTC, bubbletroubles commented on internal/services/network/route_server_resource.go
> +			payload.Properties.HubRoutingPreference = nil
Hi stephybun - I've make this more in line with other properties in the latest commit. Ready for your re-review.

2025-02-06 09:15 UTC, stephybun reviewed
A final comment on the docs, then this should be good to go!

2025-02-06 09:15 UTC, stephybun commented on website/docs/r/route_server.html.markdown
> +* `hub_routing_preference` - (Optional) The hub routing preference. Valid values are `ASPath`, `ExpressRoute` or `VpnGateway`.
```suggestion
* `hub_routing_preference` - (Optional) The hub routing preference. Valid values are `ASPath`, `ExpressRoute` or `VpnGateway`. Defaults to `ExpressRoute`.
```

2025-02-06 10:11 UTC, bubbletroubles commented
Thanks @stephybun I've applied your suggestion for the docs. Should be good to go.

2025-02-06 10:24 UTC, stephybun approved these changes
Thanks for this @bubbletroubles LGTM 🚀

2025-02-06 10:24 UTC, merged