New data source: `azurerm_dynatrace_monitor`
hashicorp/terraform-provider-azurerm pull request #28381
Opened 2024-12-25 07:25 UTC by jiaweitao001

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [x] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

2025-01-13 12:38 UTC, jackofallops requested changes
Hi @jiaweitao001 - Thanks for the PR. Some comments to take a look at below if you could please?

2025-01-13 12:38 UTC, jackofallops commented on internal/services/dynatrace/dynatrace_monitors_data_source.go
> +		},
Is there a reason we're doing 2 levels of nesting here for a single value? Can this just be flattened to the top level?

Also, this property doesn't appear to be supported by the related resource, should it even be included here?

2025-01-14 05:57 UTC, jiaweitao001 commented on internal/services/dynatrace/dynatrace_monitors_data_source.go
> +					UserInfo:                      FlattenDynatraceUserInfo(metadata.ResourceData.Get("user").([]interface{})),
Will fix.

2025-01-14 05:57 UTC, jiaweitao001 commented on website/docs/d/dynatrace_monitors.html.markdown
> +A `identity` block supports the following:
Will fix.

2025-01-14 05:57 UTC, jiaweitao001 commented on website/docs/d/dynatrace_monitors.html.markdown
> +* `type` - The type of identity used for the resource. Only possible value is `SystemAssigned`.
Will fix.

2025-01-14 05:57 UTC, jiaweitao001 commented on website/docs/d/dynatrace_monitors.html.markdown
> +A `plan` block supports the following:
Will fix.

2025-01-14 05:57 UTC, jiaweitao001 commented on website/docs/d/dynatrace_monitors.html.markdown
> +A `user` block supports the following:
Will fix.

2025-02-14 07:26 UTC, WodansSon requested changes
@jiaweitao001, Thank you for this PR! I have given it a look, while it mostly LGTM I did leave a comment with some questions about the implementation. If you can take a look at that, I will be happy to look again once that is addressed. Thanks! 🚀

2025-02-14 07:26 UTC, WodansSon commented on internal/services/dynatrace/helper.go
> +}
Couldn't these two functions be collapsed into a single function (e.g., `FlattenDynatraceEnvironmentProperties`)? I don't understand why we need the second `FlattenDynatraceEnvironmentInfo` function unless it is called from another resource? Also, should these be public functions vs. a private function (e.g., `FlattenDynatraceEnvironmentProperties` vs. `flattenDynatraceEnvironmentProperties`)?

```suggestion
func FlattenDynatraceEnvironmentProperties(input *monitors.DynatraceEnvironmentProperties) 
	result := []EnvironmentProperties{}

	if input == nil {
		return result 
	}

	if input.EnvironmentInfo != nil {
		result.EnvironmentInfo.EnvironmentId = pointer.From(input.EnvironmentInfo)
	}

	return result 
}
```

2025-02-14 07:36 UTC, WodansSon commented on website/docs/d/dynatrace_monitors.html.markdown
> +* `type` - The type of identity used for the resource. Only possible value is `SystemAssigned`.
@jackofallops / @jiaweitao001, should we even expose `type` if the only valid value is `SystemAssigned`?

2025-02-14 07:41 UTC, jiaweitao001 commented on internal/services/dynatrace/helper.go
> +}
@WodansSon , I'm not combining these 2 functions because there're other attributes under this `EnvironmentProperties` as well as `EnvironmentInfo`, the service said they will give us more details on how to configure them recently so I'll leave the functions uncollapsed.

2025-02-14 08:33 UTC, WodansSon commented on internal/services/dynatrace/helper.go
> +}
@jiaweitao001, I understand that, however, as more and more child `EnvironmentProperties` are exposed by the service team we would just need to inline those blocks into the one flatten function (e.g, `flattenDynatraceEnvironmentsProperties`), making the code much easier to read/understand and maintain moving forward for repo maintainers. If we end up with 12 flatten functions that get called from the parent flatten function it becomes exponentially more complicated to understand what the code is doing and review.

2025-02-15 05:02 UTC, WodansSon approved these changes
@jiaweitao001, thanks for pushing those changes, this LGTM now! 🚀

2025-02-15 05:03 UTC, WodansSon commented
Tests Pass?:
![image](https://github.com/user-attachments/assets/5d34089d-ca41-4284-87d6-613b00449042)

2025-02-15 05:45 UTC, merged