New resource: `azurerm_netapp_volume_group_oracle`
hashicorp/terraform-provider-azurerm pull request #28391
Opened 2024-12-27 23:18 UTC by paulomarquesc

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

This PR implements a new Azure NetApp Files resource called Volume Group for Oracle.

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [X] Bug Fix
- [X] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

2025-01-09 23:02 UTC, mbfrahry reviewed
Hey @paulomarquesc, I took a look over this PR and it mostly seems fine. My main concern is that existing tests are being changed which might lead to breaking changes. Can you confirm that migrating from the current version of the provider to this version doesn't cause issues?

2025-01-10 00:16 UTC, paulomarquesc commented on internal/services/netapp/netapp_account_encryption_resource_test.go
> +    certificate_permissions = []
All changes to unrelated tests is due to they were failing and this PR adds fixes for those, the AKV one is a good example since a behavior on AKV resources changed and all tests that required an AKV to be brought up started failing because it started returning those properties, like certificate_persmissions and causing the state to be inconsistent for the test since I wasn't defining it when I implemented those tests.

2025-01-10 00:17 UTC, paulomarquesc commented on internal/services/netapp/validate/volume_group_oracle_volumes_validation.go
> +	if len(*volumeList) < len(RequiredVolumesForOracle()) {
Good catch, I'll remove those checks.

2025-01-10 00:17 UTC, paulomarquesc commented on internal/services/netapp/validate/volume_group_oracle_volumes_validation.go
> +		if len(protocolTypeList) > 1 {
Same as above, will remove the check.

2025-01-10 00:18 UTC, paulomarquesc commented on website/docs/r/netapp_volume_group_oracle.html.markdown
> +* `zone` - (Optional) Specifies the Availability Zone in which the Volume should be located. Possible values are `1`, `2` and `3`, depending on the Azure region. Changing this forces a new resource t
Thanks, just committed this. suggestion.

2025-01-30 23:03 UTC, mbfrahry requested changes
Hey @paulomarquesc, I've left a few more comments to clean up but it overall looks good.

2025-01-30 23:03 UTC, mbfrahry commented on internal/services/netapp/validate/volume_group_oracle_volumes_export_policy_validation_test.go
> +				Nfsv41: utils.Bool(true),
```suggestion
				Nfsv41: pointer.To(true),
```

2025-01-30 23:12 UTC, paulomarquesc commented on internal/services/netapp/netapp_volume_group_oracle_data_source.go
> +			Required: true,
Gosh, completely missed this.

2025-01-31 23:49 UTC, paulomarquesc commented on internal/services/netapp/netapp_volume_group_oracle_resource.go
> +						Computed: true, // O+C - Adding this because Terraform is not being able to build proper deletion graph, it is trying to delete the snapshot policy before the volume because this is in a deeper
Let's leave this for a future PR. If you can give me a PR where this pattern is used, that would be great for next edge case.

2025-02-05 21:49 UTC, mbfrahry requested changes
Hey @paulomarquesc, I think we're there but some of the unit tests you added are failing

2025-02-05 22:47 UTC, paulomarquesc commented
> Hey @paulomarquesc, I think we're there but some of the unit tests you added are failing

Let me check it.

2025-02-06 00:38 UTC, paulomarquesc commented
> go test -run TestValidateNetApp ./internal/services/netapp/validate/ -v -count=1

Resolved.

2025-02-06 18:33 UTC, paulomarquesc commented
Fixed linting issue.

2025-02-10 21:42 UTC, mbfrahry approved these changes
LGTM!

2025-02-10 21:44 UTC, merged