New Resource: azurerm_relay_hybrid_connection
hashicorp/terraform-provider-azurerm pull request #4832
Opened 2019-11-07 18:35 UTC by DSakura207

--- PASS: TestAccAzureRMHybridConnection_basic
--- PASS: TestAccAzureRMHybridConnection_full
--- PASS: TestAccAzureRMHybridConnection_update

Resolution for #1320. 

First time pull request 😄

2019-11-07 22:11 UTC, mbfrahry requested changes
Hey @DSakura207. These changes look great. I've requested quite a few changes but the comments are almost entirely cleanup/organization focused so we maintain consistency in the provider codebase.

2019-11-07 22:11 UTC, mbfrahry commented on azurerm/resource_arm_relay_hybrid_connection_test.go
> +func TestAccAzureRMHybridConnection_basic(t *testing.T) {
We should add Relay to these tests names to better categorize them at a glance
```suggestion
func TestAccAzureRMRelayHybridConnection_basic(t *testing.T) {
```

2019-11-07 22:11 UTC, mbfrahry commented on azurerm/resource_arm_relay_hybrid_connection_test.go
> +func TestAccAzureRMHybridConnection_full(t *testing.T) {
```suggestion
func TestAccAzureRMRelayHybridConnection_full(t *testing.T) {
```

2019-11-07 22:11 UTC, mbfrahry commented on azurerm/resource_arm_relay_hybrid_connection_test.go
> +func TestAccAzureRMHybridConnection_update(t *testing.T) {
```suggestion
func TestAccAzureRMRelayHybridConnection_update(t *testing.T) {
```

2019-11-07 22:11 UTC, mbfrahry commented on azurerm/internal/services/relay/client.go
> +	HybridConnectionsClient := relay.NewHybridConnectionsClientWithBaseURI(o.ResourceManagerEndpoint, o.SubscriptionId)
We should organize these like:
```
NamespacesClient := relay.NewNamespacesClientWithBaseURI(o.ResourceManagerEndpoint, o.SubscriptionId)
o.ConfigureClient(&NamespacesClient.Client, o.ResourceManagerAuthorizer)

HybridConnectionsClient := relay.NewHybridConnectionsClientWithBaseURI(o.ResourceManagerEndpoint, o.SubscriptionId)
o.ConfigureClient(&HybridConnectionsClient.Client, o.ResourceManagerAuthorizer)
```

2019-11-07 22:11 UTC, mbfrahry commented on azurerm/provider.go
> +		"azurerm_relay_hybrid_connection":                                                resourceArmHybridConnection(),
This should be moved up one to keep this list alphabetical

2019-11-07 22:11 UTC, mbfrahry commented on azurerm/resource_arm_relay_hybrid_connection.go
> +				Optional: true,
Would it make sense to add validation here?
```suggestion
				Optional: true,
				ValidateFunc: validate.NoEmptyStrings,
```

2019-11-07 22:11 UTC, mbfrahry commented on azurerm/resource_arm_relay_hybrid_connection.go
> +		Timeout:    60 * time.Minute,
In the [Timeout](https://github.com/terraform-providers/terraform-provider-azurerm/pull/4832/files#diff-f981b0107e947bfa3d8bc26df9924a16R33) section defined in the schema, you defined the Delete timeout as 30 minutes. We should sync these up so this is either 30 minutes or the delete timeout defined above is 60 minutes.

2019-11-07 22:11 UTC, mbfrahry commented on azurerm/resource_arm_relay_hybrid_connection_test.go
> +	resource_group_name = "${azurerm_resource_group.test.name}"
Adding a space so the equals sign lines up a little better
```suggestion
	resource_group_name  = "${azurerm_resource_group.test.name}"
```

2019-11-07 22:11 UTC, mbfrahry commented on azurerm/resource_arm_relay_hybrid_connection_test.go
> +	resource_group_name = "${azurerm_resource_group.test.name}"
```suggestion
	resource_group_name  = "${azurerm_resource_group.test.name}"
```

2019-11-07 22:11 UTC, mbfrahry commented on azurerm/resource_arm_relay_hybrid_connection_test.go
> +	name                 = "acctestrnhc-%d"
We should line all these equal signs up

2019-11-07 22:11 UTC, mbfrahry commented on azurerm/resource_arm_relay_hybrid_connection_test.go
> +	name                 = "acctestrnhc-%d"
We should line all these equal signs up

2019-11-07 22:18 UTC, mbfrahry commented
Also, thank you for submitting your first PR! This is a great start

2019-11-08 00:46 UTC, DSakura207 reviewed
Hello @mbfrahry , thanks for your quick reply. I've update my branch with your suggestions. Hopefully my finger is not fat so that the commit can pass checks 🤞

2019-11-08 02:40 UTC, mbfrahry approved these changes
This all looks great! Thanks for fixing it up.

2019-11-08 02:40 UTC, merged

2019-11-08 02:41 UTC, mbfrahry commented
@DSakura207, thanks again for working on this. It should make it into the next release

2019-11-21 22:50 UTC, schlbra commented
@mbfrahry Can we please add this to the next release? Or can you confirm which release will have this included?