Adding data source for vnet
hashicorp/terraform-provider-azurerm pull request #533
Opened 2017-11-07 14:48 UTC by dcaro

Adding a data source for vnet in Azure.

2017-11-09 16:17 UTC, tombuildsstuff requested changes
Hey @dcaro 

Thanks for opening this PR - I've taken a look through and left some comments in-line but this is off to a good start; the only thing missing that I can see at this point is some documentation - would it be possible to add some for this Data Source?

Thanks!

2017-11-15 06:26 UTC, dcaro reviewed
Including suggested changes from @tombuildsstuff and added documentation.

2017-11-25 23:32 UTC, pmarques commented on azurerm/data_source_virtual_network_test.go
> +				name 			= "subnet1"
Use spaces to keep indentation

2017-11-25 23:33 UTC, pmarques commented on azurerm/data_source_virtual_network_test.go
> +			name 						= "peer-1to2"
Use spaces to keep indentation (same for next 3 lines)

2017-11-25 23:33 UTC, pmarques commented
There are some indentation that could be fixed but this LGTM and I need this feature.
Can we merge this?

2017-11-26 02:27 UTC, dcaro commented
@pmarques I have updated the code to include spaces instead of tabs. @tombuildsstuff let me know if you see any issues.

2017-11-27 09:44 UTC, tombuildsstuff commented on website/docs/d/virtual_network.html.markdown
> +---
just noticed there isn't a sidebar entry for this Data Source - I've pushed a commit to fix this :)

2017-11-27 09:51 UTC, tombuildsstuff reviewed
Hey @dcaro 

Thanks for pushing the latest changes - I've taken another look through and have left some comments inline, but this mostly LGTM. I've also pushed a commit to add the Data Source to the sidebar - however upon running the tests I noticed the Peering test failed:

```
$ acctests azurerm TestAccDataSourceArmVirtualNetwork_
=== RUN   TestAccDataSourceArmVirtualNetwork_basic
--- PASS: TestAccDataSourceArmVirtualNetwork_basic (77.07s)
=== RUN   TestAccDataSourceArmVirtualNetwork_peering
--- FAIL: TestAccDataSourceArmVirtualNetwork_peering (95.24s)
	testing.go:459: Step 0 error: Check failed: Check 3/3 error: data.azurerm_virtual_network.test: Attribute 'vnet_peerings.%' expected "1", got "0"
FAIL
exit status 1
FAIL	github.com/terraform-providers/terraform-provider-azurerm/azurerm	172.327s
```

If we can fix up the broken test this PR otherwise looks good to merge :)

Thanks!

2017-12-05 15:57 UTC, tombuildsstuff commented
ping @dcaro - have you had a chance to look into this yet? :)

2017-12-06 19:50 UTC, dcaro commented
@tombuildsstuff I have some issues with the second test. I traced the response from the REST API and I see that the peering is correctly provisioned when running the testAccDataSourceArmVirtualNetwork_peering function. The interpretation of the response is the issue. I'm trying to narrow down the function where this fails but so far, to me, it looks like an issue in terraform. Any help on this would be welcome.

2017-12-07 10:47 UTC, tombuildsstuff commented
@dcaro sure - used the configuration from the failing test (and added some variables) to take a look into this:

```
resource "azurerm_resource_group" "test" {
  name     = "tharvey-devrg"
  location = "West Europe"
}

resource "azurerm_virtual_network" "test1" {
  name                = "tharvey-nw1"
  address_space       = ["10.0.1.0/24"]
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_virtual_network" "test2" {
  name                = "tharvey-nw2"
  address_space       = ["10.0.2.0/24"]
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_virtual_network_peering" "test1" {
  name                      = "peer-1to2"
  resource_group_name       = "${azurerm_resource_group.test.name}"
  virtual_network_name      = "${azurerm_virtual_network.test1.name}"
  remote_virtual_network_id = "${azurerm_virtual_network.test2.id}"
}

data "azurerm_virtual_network" "test" {
  resource_group_name = "${azurerm_resource_group.test.name}"
  name                = "${azurerm_virtual_network.test1.name}"
}
```

In order to understand what's going on, we can inspect what the Terraform Graph for this Terraform Configuration using the command `terraform graph | dot -Tpng > graph.png` - which in this case generates:

![original](https://user-images.githubusercontent.com/666005/33710947-1f269b16-db3a-11e7-8905-2f6be21ee879.png)

Given the `azurerm_virtual_network_peering ` resource isn't referenced within the `azurerm_virtual_network` data source (known as an Implicit Dependency) - Terraform believes it should be able to execute these in Parallel, as shown in the graph (since there's no lines between them) - where it's possible the VNet Peering may not exist.

We can use the `depends_upon` graph to specify an Explicit Dependency as shown in the configuration below:

```
resource "azurerm_resource_group" "test" {
  name     = "tharvey-devrg"
  location = "West Europe"
}

resource "azurerm_virtual_network" "test1" {
  name                = "tharvey-nw1"
  address_space       = ["10.0.1.0/24"]
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_virtual_network" "test2" {
  name                = "tharvey-nw2"
  address_space       = ["10.0.2.0/24"]
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_virtual_network_peering" "test1" {
  name                      = "peer-1to2"
  resource_group_name       = "${azurerm_resource_group.test.name}"
  virtual_network_name      = "${azurerm_virtual_network.test1.name}"
  remote_virtual_network_id = "${azurerm_virtual_network.test2.id}"
}

data "azurerm_virtual_network" "test" {
  resource_group_name = "${azurerm_resource_group.test.name}"
  name                = "${azurerm_virtual_network.test1.name}"
  depends_on          = ["azurerm_virtual_network_peering.test1"]
}
```

The Terraform Graph for this looks like so:

![graph](https://user-images.githubusercontent.com/666005/33710956-28b32abe-db3a-11e7-911d-969790b54aff.png)

which means that the `vnet_peerings` are included in the Data Source (since they exist at this point). More information on [Implicit and Explicit Dependencies is available on this page](https://www.terraform.io/intro/getting-started/dependencies.html#implicit-and-explicit-dependencies).

I've confirmed that `props.VirtualNetworkPeerings` has a value at this point too - so I'm hoping that should be helpful? :)

Thanks!

2017-12-07 18:06 UTC, dcaro commented
Thanks so much @tombuildsstuff I will update my PR today !

2017-12-08 07:17 UTC, dcaro commented
@tombuildsstuff when I introduce the dependency, I have the following error when I run the test:
API server listening at: 127.0.0.1:50704
	testing.go:459: Step 0 error: After applying this step and refreshing, the plan was not empty:
		DIFF:
		
		CREATE: data.azurerm_virtual_network.test
		  address_spaces.#:    "" => "<computed>"
		  dns_servers.#:       "" => "<computed>"
		  name:                "" => "acctestvnet-1-4667103784115642641"
		  resource_group_name: "" => "acctest4667103784115642641-rg"
		  subnets.#:           "" => "<computed>"
		  vnet_peerings.%:     "" => "<computed>"
		
		STATE:
		
		azurerm_resource_group.test:
[properties of the resource group]

                azurerm_virtual_network.test1:
[properties of the virtual network]

		Dependencies:
		    azurerm_resource_group.test

		azurerm_virtual_network.test2:
[properties of the virtual network]

               Dependencies:
		    azurerm_resource_group.test
		azurerm_virtual_network_peering.test1:
[properties of the virtual network peering]

		  Dependencies:
		    azurerm_resource_group.test
		    azurerm_virtual_network.test1
		    azurerm_virtual_network.test2

2017-12-08 12:20 UTC, tombuildsstuff approved these changes
LGTM - thanks for this 👍

2017-12-08 12:20 UTC, tombuildsstuff commented
@dcaro so after digging into this, it appears that a data source with a `depends_on` will be re-triggered whenever a `plan` is attempted. Whilst it's possible to work around this by referencing the virtual network name via `${azurerm_virtual_network_peering.test1.virtual_network_name}` - I instead figured it better to split this out into two separate test-steps as shown below:

```
func TestAccDataSourceArmVirtualNetwork_peering(t *testing.T) {
	dataSourceName := "data.azurerm_virtual_network.test"
	ri := acctest.RandInt()

	name_vnet_1 := fmt.Sprintf("acctestvnet-1-%d", ri)
	location := testLocation()

	resource.Test(t, resource.TestCase{
		PreCheck:  func() { testAccPreCheck(t) },
		Providers: testAccProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceArmVirtualNetwork_peering(ri, location),
			},
			{
				Config: testAccDataSourceArmVirtualNetwork_peeringWithDataSource(ri, location),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(dataSourceName, "name", name_vnet_1),
					resource.TestCheckResourceAttr(dataSourceName, "address_spaces.0", "10.0.1.0/24"),
					resource.TestCheckResourceAttr(dataSourceName, "vnet_peerings.%", "1"),
				),
			},
		},
	})
}
```

I've pushed a commit to add support for this and this Data Source now LGTM - thanks for this :)

Tests pass:

```
$ acctests azurerm TestAccDataSourceArmVirtualNetwork_
=== RUN   TestAccDataSourceArmVirtualNetwork_basic
--- PASS: TestAccDataSourceArmVirtualNetwork_basic (76.72s)
=== RUN   TestAccDataSourceArmVirtualNetwork_peering
--- PASS: TestAccDataSourceArmVirtualNetwork_peering (102.65s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	179.391s
```

2017-12-08 12:42 UTC, merged

2017-12-08 14:07 UTC, pmarques commented
@tombuildsstuff do you have any details about the next release date? I would like to have this available without compiling my own.

2017-12-08 14:28 UTC, tombuildsstuff commented
@pmarques "soon" - it'll be next week, but I'd rather not commit to a specific day/date - hope that helps :)