d/azurerm_kubernetes_cluster uitgebreid met kubelet_identity en identity
hashicorp/terraform-provider-azurerm pull request #6527
Opened 2020-04-17 17:43 UTC by aristosvo

Fixes #6514

2020-04-21 07:16 UTC, tombuildsstuff requested changes
hey @aristosvo 

Thanks for this PR :)

Taking a look through this mostly LGTM - if we can fix up the comments then this should otherwise be good to merge 👍 

Thanks!

2020-04-21 07:16 UTC, tombuildsstuff commented on azurerm/internal/services/containers/data_source_kubernetes_cluster.go
> +				ForceNew: true,
this is a Data Source - so this wants to be Computed only (and not Optional/ForceNew)

2020-04-21 07:16 UTC, tombuildsstuff commented on azurerm/internal/services/containers/data_source_kubernetes_cluster.go
> +		kubeletIdentity := flattenKubernetesClusterIdentityProfile(props.IdentityProfile)
since the fields for a Data Source can differ, we intentionally duplicate the flatten functions - as such can we pull this in here?

2020-04-21 07:16 UTC, tombuildsstuff commented on azurerm/internal/services/containers/data_source_kubernetes_cluster.go
> +	if err := d.Set("identity", flattenKubernetesClusterManagedClusterIdentity(resp.Identity)); err != nil {
(same here) can we duplicate this flatten function for the data source

2020-05-22 20:32 UTC, aristosvo commented
Comments implemented!

2020-05-25 15:32 UTC, tombuildsstuff approved these changes
LGTM - thanks for this @aristosvo

2020-05-25 22:30 UTC, merged