`azurerm_mssql_database` `min_capacity` change validation
hashicorp/terraform-provider-azurerm pull request #8308
Opened 2020-09-01 02:46 UTC by yupwei68

Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/8226

2020-09-01 04:57 UTC, tombuildsstuff requested changes
hi @yupwei68 

Thanks for this PR.

Taking a look through here it appears that we can add `0` as an allowed value here (as `1` and `2` are) - which should solve this and provide examples of valid values here; at the same time can we also add an acceptance test to cover this missing use-case? If we can fix those up then we should be able to take another look

Thanks!

2020-09-01 04:57 UTC, tombuildsstuff commented on azurerm/internal/services/mssql/mssql_database_resource.go
> +				ValidateFunc: validation.FloatAtLeast(0),
alternatively we could add `0` as an allowed value here:

```suggestion
				ValidateFunc: azValidate.FloatInSlice([]float64{0, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 2.25, 2.5, 3, 4, 5}),
```

can we also add an acceptance test for this SKU?

2020-09-01 05:53 UTC, yupwei68 commented
Hi @tombuildsstuff Thanks for your comments. Please continue reviewing.

2020-09-02 08:44 UTC, tombuildsstuff requested changes
hi @yupwei68 

Taking a look through the unit test looks good, but can we add an acceptance test to ensure that #8226 is fixed?

Thanks!

2020-09-02 08:44 UTC, tombuildsstuff commented on azurerm/internal/services/mssql/mssql_database_resource.go
> +				ValidateFunc: validate.MsSqlDatabaseMinCapacity,
can we add an [Acceptance Test](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/mssql/tests/mssql_database_resource_test.go#L16-L33) to provision a Database with the Capacity of `0` to confirm the Basic SKU / #8226 is fixed

2020-10-04 19:16 UTC, merged